### ISSUE TITLE
onPageNotFound 生命周期函数无效

### ISSUE THREAD

**Issue by dream2023** [Meituan-Dianping/mpvue#1001]
问题简单描述：
如标题，新克隆项目， 最新基础库，onPageNotFound生命周期函数仍然无效
然后，用原生试了一下，可以

**Comment by dream2023** [comment]
没人吗？？

**Comment by ilp64** [comment]
@dream2023 我这里也需要用到这个生命周期函数，请问最后你是怎么解决的。

**Comment by dream2023** [comment]
> @dream2023 我这里也需要用到这个生命周期函数，请问最后你是怎么解决的。

这不是bug，而是根本没有做这个功能，没看到打了 enhancement tag吗

**Comment by hucq** [comment]
已经修改完毕，本周会发新版本
