### ISSUE TITLE
2018-09-10更新后提示VM372:1 thirdScriptError   sdk uncaught third Error   Unexpected identifier   SyntaxError: Unexpected identifier

### ISSUE THREAD

**Issue by JesseWeb** [Meituan-Dianping/mpvue#1002]
#### 

![image](https://user-images.githubusercontent.com/23567445/45337708-fe043300-b5bb-11e8-9834-4d995a05ab6f.png)
![image](https://user-images.githubusercontent.com/23567445/45338333-2ccfd880-b5bf-11e8-950e-5b2e84cd1bbb.png)

**Comment by JesseWeb** [comment]
@nbhaohao 测试反馈: 勾选ES6 转 ES5 依旧无效

**Comment by JesseWeb** [comment]
### bug反馈
用回旧版本后没有再出现这个问题

**Comment by TonyLuo** [comment]
遇到同样的问题

**Comment by TonyLuo** [comment]
npm run dev 一切正常，没有这个问题， 跑npm run build后就出现这个问题

**Comment by Jiangjinjin1** [comment]
我也遇到这个问题，然后选择了基础调试库为2.3.0就不报错了，试试看行不行

**Comment by JesseWeb** [comment]
找到问题,是因为有一个没有在app.json中注册的页面导致的,删除或者在app.json中注册即可.

**Comment by ccoo23** [comment]
> 我也遇到这个问题，然后选择了基础调试库为2.3.0就不报错了，试试看行不行

我彳亍了。。。
