### ISSUE TITLE
新建项目无APPid，后来加上也是不行

### ISSUE THREAD

**Issue by Niofh** [Meituan-Dianping/mpvue#1008]
# [问题简单描述]
新建项目无APPid，后来加上也是不行。重启项目，删除dist目录都无不行

![image](https://user-images.githubusercontent.com/15324717/45399907-8e09b180-b67c-11e8-80e2-3e02663d7dff.png)

![image](https://user-images.githubusercontent.com/15324717/45399879-6f0b1f80-b67c-11e8-9a61-4de266e98dd6.png)

**Comment by LeeHarlan** [comment]
微信开发工具重启

**Comment by aOrz** [comment]
微信开发工具重启 or 开发者工具删了项目，再添加
