### ISSUE TITLE
过滤器处理数据无效等

### ISSUE THREAD

**Issue by lanshengzhong** [Meituan-Dianping/mpvue#101]
![image](https://user-images.githubusercontent.com/20151096/37453632-4436bd24-2873-11e8-8b14-07b72f44ae42.png)

![image](https://user-images.githubusercontent.com/20151096/37453620-3b670672-2873-11e8-9213-e45922126419.png)

![image](https://user-images.githubusercontent.com/20151096/37452790-953dce04-2870-11e8-8169-1404836f4a71.png)

![image](https://user-images.githubusercontent.com/20151096/37452812-a75964a4-2870-11e8-8a88-13562ce7e7d6.png)

**Comment by falost** [comment]
是不支持 filter 过滤器 的 
[具体请看](http://mpvue.com/mpvue/#_7)

**Comment by lanshengzhong** [comment]
那该怎么处理呢  后台返回的时间数据  需要格式化时分秒

**Comment by samwang1027** [comment]
computed

**Comment by lanshengzhong** [comment]
谢谢 computed是可以的

**Comment by F-loat** [comment]
@LeftShoot 提前对数组进行 map
