### ISSUE TITLE
mmp 云开发三部曲

### ISSUE THREAD

**Issue by qiaolevip** [Meituan-Dianping/mpvue#1013]
在线云开发，首选微信云开发：
[微信云开发文档](https://developers.weixin.qq.com/miniprogram/dev/wxcloud/basis/getting-started.html)

1. First Step
```project.config.json```  Line 10：
```json
	"miniprogramRoot": "./miniprogram/",
	"cloudfunctionRoot": "./cloudfunctions/",
	"compileType": "miniprogram",
```

2. Second Step
```config/index.js```  Line 8：
```javascript
    assetsRoot: path.resolve(__dirname, '../dist/miniprogram'),
```

3. Third Step
```buiild/webpack.base.conf.js```  Line Plugins：
```javascript
plugins: [
    new MpvuePlugin(),
    new CopyWebpackPlugin([{
      from: '**/*.json',
      to: ''
    }], {
      context: 'src/'
    }),
    new CopyWebpackPlugin([
      {
        from: path.resolve(__dirname, '../static'),
        to: path.resolve(__dirname, '../dist/miniprogram/static'),
        ignore: ['.*']
      }
    ]),
    new CopyWebpackPlugin([
      {
        from: path.resolve(__dirname, '../project.config.json'),
        to: path.resolve(__dirname, '../dist/project.config.json'),
        ignore: ['.*']
      }
    ]),
    new CopyWebpackPlugin([
      {
        from: path.resolve(__dirname, '../cloudfunctions'),
        to: path.resolve(__dirname, '../dist/cloudfunctions'),
        ignore: ['.*']
      }
    ])
  ]
```

Run like this Structure: :100: 
![image](https://user-images.githubusercontent.com/996755/45476865-acea6f80-b772-11e8-9683-de47c6076a74.png)

Application APP , Scan It Enter >
![image](https://user-images.githubusercontent.com/996755/45477036-297d4e00-b773-11e8-84c2-c48f7838d611.png)

**Comment by aOrz** [comment]
赞

**Comment by aOrz** [comment]
可以 PR 到 https://github.com/mpvue/mpvue-docs 文档仓库

**Comment by 378978764** [comment]
是怎么做到没有标题栏的？是整个webview吗？

**Comment by qiaolevip** [comment]
> 是怎么做到没有标题栏的？是整个webview吗？

@378978764 app.json配置
```
"window": {
    "navigationStyle": "custom"
  }
```

**Comment by will-17173** [comment]
似乎除了第一步，后面的都是没有用的。参考`https://github.com/xxxsimons/mpvue-cloud`

**Comment by Renford** [comment]
还是不支持查询命令，如eq、and、or等，怎么破？
```
const _ = db.command
db.collection('todos').where({
  progress: _.eq(50)
})
.get({
  success: console.log,
  fail: console.error
})
```

**Comment by qiaolevip** [comment]
云开发："mpvue": "v2.4.1"

1. First Step
project.config.json Line 10：
```javascript
  "miniprogramRoot": "./miniprogram/",
  "cloudfunctionRoot": "./cloudfunctions/",
```

2. Second Step
config/index.js Line 20：
```javascript
wx {
  platform: 'wx/miniprogram'
```

3. Third Step
buiild/webpack.base.conf.js End of file Plugins：
```javascript
if (/^(swan)|(tt)$/.test(PLATFORM)) {
  baseWebpackConfig = merge(baseWebpackConfig, {
    plugins: [
      new CopyWebpackPlugin([{
        from: path.resolve(__dirname, projectConfigMap[PLATFORM]),
        to: path.resolve(config.build.assetsRoot)
      }])
    ]
  })
} else if ('wx' === PLATFORM) {
// Add here
  const rootDir = config.build.assetsRoot.replace('/miniprogram', '')
  baseWebpackConfig = merge(baseWebpackConfig, {
    plugins: [
      new CopyWebpackPlugin([{
        from: path.resolve(__dirname, projectConfigMap.tt),
        to: path.resolve(rootDir, './')
      }]),
      new CopyWebpackPlugin([{
        from: path.resolve(__dirname, '../cloudfunctions'),
        to: path.resolve(rootDir, './cloudfunctions')
      }])
    ]
  })
}
```

![image](https://user-images.githubusercontent.com/996755/54470085-33910f80-47dd-11e9-9a84-18ad7028c624.png)

**Comment by linyongfu2013** [comment]
@qiaolevip 
运行失败，`miniprogram`   `cloudfunctions` 这两个目录要手工建吗？

**Comment by gap1994** [comment]
显示找不到app.json,怎么办

**Comment by gap1994** [comment]
1：config/index.js Line20
`platform: 'wx/miniprogram'`
2:  project.config.json line10
`"miniprogramRoot": "./miniprogram/",
	  "cloudfunctionRoot": "./cloudfunctions/",`
3:  build/webpack.base.conf.js Line108 Plugins：
`plugins: [
    // api 统一桥协议方案
    new webpack.DefinePlugin({
      'mpvue': 'global.mpvue',
      'mpvuePlatform': 'global.mpvuePlatform'
    }),
    new MpvuePlugin(),
    new CopyWebpackPlugin([{
      from: '**/*.json',
      to: ''
    }], {
      context: 'src/'
    }),
    new CopyWebpackPlugin([
      {
        from: path.resolve(__dirname, '../static'),
        to: path.resolve(config.build.assetsRoot, './static'),
        ignore: ['.*']
      }
    ]),
    new CopyWebpackPlugin([
      {
        from: path.resolve(__dirname, '../project.config.json'),
        to: path.resolve(__dirname, '../dist/wx/project.config.json'),
        ignore: ['.*']
      }
    ]),
    new CopyWebpackPlugin([
      {
        from: path.resolve(__dirname, '../cloudfunctions'),
        to: path.resolve(__dirname, '../dist/wx/cloudfunctions'),
        ignore: ['.*']
      }
    ])
  ]`
4: main.js end line:
`if (!wx.cloud) {
  console.error('请使用 2.2.3 或以上的基础库以使用云能力')
} else {
  wx.cloud.init({
    traceUser: true,
    env: 'test-xxxxxxx'
  })
}`
5: 使用云函数：
`mounted{
  // env是你云开发的环境id。
  const db = wx.cloud.database({ env: 'test-xxxxxxxx' })
  this.db.collection('数据库表').get()
  .then(res=>{
    console.log(res.data)
    // 可以进行数据初始化
  })
  .cathc(console.error)
}`
有什么错的请多多指教，我第一次用这个
