### ISSUE TITLE
input使用handleinput改变值问题

### ISSUE THREAD

**Issue by herodhb** [Meituan-Dianping/mpvue#1014]
# [问题简单描述]
mpvue版本1.0.9
input无法使用handleinput返回一个字符串来改变值
**问题复现步骤:**
<input @input="handleInput" />

methods: {
  handleInput () {
    return '123'  // 无效
  }
}
**期望的表现:**
input的值会被替换成123

**Comment by MarcWong** [comment]
需要给input绑定v-model，可参见我的[issues-1015](https://github.com/Meituan-Dianping/mpvue/issues/1015)

**Comment by herodhb** [comment]
升级到1.0.13之后问题解决。
