### ISSUE TITLE
创建一个基于 mpvue-quickstart 模板的新项目，新增页面不会把页面路径自动增加到app.json的pages中

### ISSUE THREAD

**Issue by magicLaLa** [Meituan-Dianping/mpvue#1018]
# [问题简单描述]

**问题复现步骤:**

1. [第一步]
npm install --global vue-cli@2.9
2. [第二步]
vue init mpvue/mpvue-quickstart my-project
3. [其他步骤...]
在src下pages新增一个文件夹，从index文件下复制过来，在重新npm run dev 之后，没有在app.json中找到新增的页面路径地址.

**Comment by magicLaLa** [comment]
http://mpvue.com/change-log/2018.7.24/

**Comment by zxzhgk** [comment]
新版本的，增加page要自己手写了，因为他把配置从JS文件中移出来了，这样不好直接编辑json文件了

**Comment by magicLaLa** [comment]
@zxzhgk 嗯嗯 谢谢你
