### ISSUE TITLE
怎么发送http请求啊  求实例代码

### ISSUE THREAD

**Issue by zilinyo** [Meituan-Dianping/mpvue#102]
# [问题简单描述]

**问题复现步骤:**

1. [第一步]
2. [第二步]
3. [其他步骤...]

**期望的表现:**

[在这里描述期望的表现]

**观察到的表现:**

[在这里描述观察到的表现]

**屏幕截图和动态 GIF 图**

![复现步骤的屏幕截图和动态 GIF 图](图片的 url)

**Comment by falost** [comment]
你可以封装一下 wx.request 这个方法
https://mp.weixin.qq.com/debug/wxadoc/dev/api/network-request.html#wxrequestobject

**Comment by anchengjian** [comment]
顺便补充一个 [在mpvue中如何优雅的封装ajax？](https://www.zhihu.com/question/268448161/answer/337821230)
