### ISSUE TITLE
动态组件 component  :is报错

### ISSUE THREAD

**Issue by Synaric** [Meituan-Dianping/mpvue#1023]
按照vue文档如下实现动态组件：
```
<template>
    <div class="clz_container">
       <component :is="layoutItem"></component>
    </div>
</template>

<script>
  export default {
    name: 'clz_list',
    data () {
      return {
        layoutItem: {
          name: 'goods_item',
          component: {
            template: '<div style="width: 100rpx; height: 100rpx; background: red">111</div>'
          }
        }
      }
    }
  }
</script>
```
出现错误：jsEnginScriptError
Cannot set property Symbol(Symbol.species) of function RegExp() { [native code] } which has only a getter
TypeError: Cannot set property Symbol(Symbol.species) of function RegExp() { [native code] } which has only a getter

**Comment by cdll** [comment]
好好看看文档 http://mpvue.com/mpvue/#_16
![image](https://user-images.githubusercontent.com/8576686/45679956-4f886100-bb6c-11e8-9de3-a872c50a92d3.png)
