### ISSUE TITLE
如何解决手机发热、内存不足、掉电速度快等一系列问题？

### ISSUE THREAD

**Issue by Renford** [Meituan-Dianping/mpvue#1025]
操作几分钟，掉电速度很快，手机发热，内存不足。但并无明显异常、报错信息
有解决方案吗？

**Comment by cgxqd123** [comment]
要注意数据的冗余

**Comment by raohong** [comment]
重写吧 mpvue  只适合玩具项目和几个页面的小项目

**Comment by hucq** [comment]
给出具体场景问题描述或者代码示例重新提一个issue，这样的提问无法有针对性回复。
