### ISSUE TITLE
如何动态设置page的样式

### ISSUE THREAD

**Issue by hyuanyuanlisiwei** [Meituan-Dianping/mpvue#1041]
# [问题简单描述]

**问题复现步骤:**

1,  模态框框滚动的时候 page 也跟着滚动
2,  弹出模态框的时候, 需要设置page: overflow:hidden
3, 但是mpvue中没有用page标签, 如何动态设置page的样式呢

**期望的表现:**

[在这里描述期望的表现]

**观察到的表现:**

[在这里描述观察到的表现]

**屏幕截图和动态 GIF 图**

![复现步骤的屏幕截图和动态 GIF 图](图片的 url)

**Comment by hucq** [comment]
或者可以通过 style 来实现。

**Comment by baimoer** [comment]
为什么要关闭呢，解决办法是什么

**Comment by teri5354** [comment]
这个问题完全没有得到解决方法就关闭了
