### ISSUE TITLE
存在将未绑定在 WXML 的变量传入 setData

### ISSUE THREAD

**Issue by weiyunpeng** [Meituan-Dianping/mpvue#1042]
# [问题简单描述]
setData操作会引起框架处理一些渲染界面相关的工作，一个未绑定的变量意味着与界面渲染无关，传入setData会造成不必要的性能消耗
**问题复现步骤:**

1. [第一步]
2. [第二步]
3. [其他步骤...]

**期望的表现:**

[在这里描述期望的表现]

**观察到的表现:**

变量名 | 调用堆栈 | 调用组件 | 页面
-- | -- | -- | --
$root.0 | Vue$3.initDataToMP [as _initDataToMP] -> Vue$3.<anonymous> -> Array.<anonymous> -> nextTickHandler | Page | pages/index/index
$root.0,1 | VueComponent.updateDataToMP [as $updateDataToMP] -> VueComponent.patch [as __patch__] -> VueComponent.Vue._update -> VueComponent.updateComponent -> Watcher.get -> new Watcher | Page | pages/index/index
$root.0 | Audit_setTimeout_pages/index/index | Page | pages/index/index
$root.0 | Vue$3.updateDataToMP [as $updateDataToMP] -> Vue$3.patch [as __patch__] -> Vue$3.Vue._update -> Vue$3.updateComponent -> Watcher.get -> Watcher.run | Page | pages/index/index
$root.0,1 | Audit_setTimeout_pages/index/index | Page | pages/index/index
$root.0,1 | VueComponent.updateDataToMP [as $updateDataToMP] -> VueComponent.patch [as __patch__] -> VueComponent.Vue._update -> VueComponent.updateComponent -> Watcher.get -> Watcher.run | Page | pages/index/index
$root.0 | Vue$3.initDataToMP [as _initDataToMP] -> Vue$3.<anonymous> -> Array.<anonymous> -> nextTickHandler | Page | pages/home/index
$root.0 | Vue$3.updateDataToMP [as $updateDataToMP] -> Vue$3.patch [as __patch__] -> Vue$3.Vue._update -> Vue$3.updateComponent -> Watcher.get -> new Watcher | Page | pages/home/index
$root.0 | Audit_setTimeout_pages/home/index | Page | pages/home/inde

[在这里描述观察到的表现]

**屏幕截图和动态 GIF 图**

![复现步骤的屏幕截图和动态 GIF 图](图片的 url)

**Comment by zxzhgk** [comment]
小程序工具检测的么，我也有这个问题，应该不用理会，

**Comment by weiyunpeng** [comment]
> 小程序工具检测的么，我也有这个问题，应该不用理会，

影响性能呀

**Comment by aOrz** [comment]
这些变量都是有用到的，看下 mpvue 的源码
