### ISSUE TITLE
支持async await 

### ISSUE THREAD

**Issue by gakaki** [Meituan-Dianping/mpvue#105]

**Comment by gakaki** [comment]
好吧是我没仔细用可以的支持  只是会报 await is reverse word 如果function上没有加async 直接用await调用的话

**Comment by falost** [comment]
async await   是支持的

**Comment by yedf** [comment]
created () {
(async () => {
let a = {}
a.b.c = 0
})()
},
期望的表现:

期望在控制台里面报告created中不能够赋值给undefined

观察到的表现:

没有任何提示

**Comment by suinia** [comment]
模拟器上没问题，真机上不行。我看编译后的代码还是 async await。需要自己配置吗？
