### ISSUE TITLE
mpvue scss keyframes build failed

### ISSUE THREAD

**Issue by luojinghui** [Meituan-Dianping/mpvue#1056]
### Description
I am using animation with scss keyframes, I add keyframes ,but at compile time, an error occurred

### Code
```
<div class="modal"><div>
<style lang="scss" scoped>
    .modal {
        position: fixed;
        bottom: 0;
        left: 0;
        right: 0;
        width: 100%;
        height: 100%;
        z-index: 10;
        background-color: rgba(0, 0, 0, 0.5);
        display: flex;
        align-items: center;
        justify-content: space-around;
        animation:bgChange 2s ease infinite;
    }
    @keyframes bgChange {
        form {
            background-color: rgba(0, 0, 0, 0);
        }
        to {
            background-color: rgba(0, 0, 0, 0.5);
        }
    }
</style>
```

### Expected performance
I expect it to have a gradient background animation，but I can't get it.

### Error
![image](https://user-images.githubusercontent.com/12367406/46136104-68ce9300-c279-11e8-8198-e55f59982fdb.png)

**Comment by ivanlee93** [comment]
Let's change @keyframes to @webkit-keyframes. 
If not, you can switch to stylus and pass the test

**Comment by ivanlee93** [comment]
@keyframes 需要前缀 @-webkit-keyframes 如果不行，换stylus，测试通过

**Comment by luojinghui** [comment]
放弃了，不加动画了。
