### ISSUE TITLE
部分安卓机打开首页页面空白，审核未通过

### ISSUE THREAD

**Issue by taichenglu** [Meituan-Dianping/mpvue#1057]
小程序"xxxx"代码发布审核结果

你的小程序"xxxx"代码发布审核未通过，原因如下：
1:小程序可用性和完整性不符合规则:
(1):小程序打开首页页面空白，无法加载，尝试打开调试仍如此，请优化后再提交审核（测试环境wifi，Andriod 8.0.0，微信6.7.2，Honor 8 Lite）

----------------------------

大部分手机都好，就这个手机不行，被打回很多次了，是 mpvue 的问题吗？

```
<div v-if="fetchOk">
  首页
</div>
```

fetchOk 默认 false，接口请求成功后标记成 true，是 v-if 的兼容问题？

mpvue 版本 1.0.11

**Comment by hucq** [comment]
根据你的描述，我判断是其它地方的问题，目前定位的原因恐怕不准确。再仔细定位一下。
