### ISSUE TITLE
不支持分包加载

### ISSUE THREAD

**Issue by weineel** [Meituan-Dianping/mpvue#106]
小程序支持的[分包加载](https://mp.weixin.qq.com/debug/wxadoc/dev/framework/subpackages.html)，感觉不太好配置，是不是现在还不支持，没有找到相关文档。

**Comment by aOrz** [comment]
同 #26 ,请不要提重复问题，生成页面路径已支持配置 http://mpvue.com/build/mpvue-loader/#_2
