### ISSUE TITLE
mpvue框架开发小程序wx.getUpdateManager() 只能在模拟器使用，真机上不行

### ISSUE THREAD

**Issue by codingJia** [Meituan-Dianping/mpvue#1061]
在App.vue的代码如下
onLaunch (options) {}添加如下代码，
![wx20180928-164737](https://user-images.githubusercontent.com/22971213/46198137-51a5a900-c33e-11e8-88fa-1eac43f185e7.png)
在模拟器上可以正常使用，但是在真机上没有任何作用的，这是什么原因

**Comment by JokerLoLgrey** [comment]
要写在app.vue的onshow里面

**Comment by xiaomingming** [comment]
首先，要在App.vue中定义，其次，注意该API的兼容性。

**Comment by codingJia** [comment]
不起作用是因为第一次发版时，app.vue还没有这段代码，等到第二次发版时才有这段代码，所以只有到第三次再次发版的时候才能起作用。但是也是在有些机型会有弹窗提示，有些还是没有，不过代码已经是最新的了

**Comment by xiaomingming** [comment]
> 不起作用是因为第一次发版时，app.vue还没有这段代码，等到第二次发版时才有这段代码，所以只有到第三次再次发版的时候才能起作用。但是也是在有些机型会有弹窗提示，有些还是没有，不过代码已经是最新的了

API对基础库有要求的，对应的就是用户微信版本高低的要求。跟机型没多大关系，是用户微信版本问题。
