### ISSUE TITLE
现在还不能支持在花括号里直接计算输出吗？如 <div>{{test.toFixed(2)}}</div> 无法解析

### ISSUE THREAD

**Issue by AWeiJie** [Meituan-Dianping/mpvue#107]
# [问题简单描述]

**问题复现步骤:**

1. [第一步]
2. [第二步]
3. [其他步骤...]

**期望的表现:**

[在这里描述期望的表现]

**观察到的表现:**

[在这里描述观察到的表现]

**屏幕截图和动态 GIF 图**

![复现步骤的屏幕截图和动态 GIF 图](图片的 url)

**Comment by aOrz** [comment]
因微信小程序模板不支持这种运算，所以暂不支持
