### ISSUE TITLE
这个项目还维护么

### ISSUE THREAD

**Issue by nyrf** [Meituan-Dianping/mpvue#1077]
如果不维护的话发个声吧，我们公司新的项目准备用，但上次提的问题一直没人跟进了，怕到时不维护了太麻烦，谢谢

**Comment by DreamPWJ** [comment]
估计已经没空维护了

**Comment by zhaotoday** [comment]
三四个月没更新了！

**Comment by nyrf** [comment]
决定了，不用mpvue了，好在公司有react经验，转到taro了，mpvue不更新新功能没啥，那么多大的bug也不修复就有过说不过去了。还是希望能维护的，我个人对vue使用的还是挺多

**Comment by DreamPWJ** [comment]
@nyrf 对 新功能不指望  bug太多还不维护 就是说明维护太不给力  当前开源值得赞赏  但是开源让人家入坑就不厚道了

**Comment by DreamPWJ** [comment]
taro已在观察  如果维护积极 bug不多的话  也已经准备切入 一个react都不会的人都准备用taro  说明被mpvue维护太失望了

**Comment by zhaotoday** [comment]
坑，又和 Weex 一样了。

**Comment by DreamPWJ** [comment]
vue生态项目非常多  但是坑更多 高质量的不多   还是angular和react的生态项目高质量的多

**Comment by hucq** [comment]
#1034
