### ISSUE TITLE
后台传递的数据怎么赋值  ？

### ISSUE THREAD

**Issue by zilinyo** [Meituan-Dianping/mpvue#108]
# [问题简单描述]

**问题复现步骤:**

1. [第一步]
          success: function(res) {
              //可以赋值到result但是不能显示
              this.result=res.data
              //this.setData is not function
              this.setData({result:res.data})
          }
2. [第二步]
3. [其他步骤...]

**期望的表现:**

[在这里描述期望的表现]

**观察到的表现:**

[在这里描述观察到的表现]

**屏幕截图和动态 GIF 图**

![复现步骤的屏幕截图和动态 GIF 图](图片的 url)

**Comment by F-loat** [comment]
data 里有写 result 这个属性没，没的话不行

**Comment by kevinlvhsl** [comment]
es6中不要用function 作为回调函数， 而应使用箭头函数。
