### ISSUE TITLE
mpvue 获取元素宽度和高度还有位置

### ISSUE THREAD

**Issue by nzjcnjzx** [Meituan-Dianping/mpvue#1080]
作为小程序，现在不能在像之前操作dom了 ，微信有提供了获取元素宽高和位置的api ， 好像在mpvue是不支持的， 那么在mpvue中如何去获取元素的宽高和位置呢？

**Comment by Alexixyc** [comment]
SelectorQuery wx.createSelectorQuery()

**Comment by aOrz** [comment]
微信的 API 是都支持的
