### ISSUE TITLE
编译正常通过，10个页面中有一个页面没有正常生成 main.wxml

### ISSUE THREAD

**Issue by YinChangSheng** [Meituan-Dianping/mpvue#1081]
# 问题简述
使用 mpvue 的脚手架生成模板工程，10个页面，编译正常通过，无报错，其中有一个页面的 main.wxml 没有生成。

# 问题详细描述
编译正常通过
项目之前一直都在使用 npm run dev 开调试开发
项目开发到稳尾声的时候使用 npm run build
小程序开发者工具报错：page not found ，经过查找后发现，这个页面
index.vue.wxml, main.js, store.js, main.wxss 都生成了，唯独没有生成 main.wxml
删除 dist 目录后，重新编译，依然如此。就连之前的 npm run dev 也会这样
因为 index.wxml 是个模板文件，我将其他页面的index.wxml修改了一份到这个页面下，项目恢复运行
每次都发生，不知道是不是其他人的也会这样

补充一下， 每次都是那个页面出现这样的问题，每次必现，那个页面代码也很普通，基本和其他页面类似。

**Comment by hucq** [comment]
看不出你的文件目录和命名，可尝试如下方式：

1. 确认一下入口文件的命名是否统一，默认为 index.vue
2. 其它编译出的文件是否有正常
3. 尝试回退 mpvue-loader 的版本，譬如 1.1.0

**Comment by YinChangSheng** [comment]
1. 文件应该没有问题，我看过webpack的配置，所以都是按照规范来的

├── [ 160]  address
│   ├── [ 164]  index.vue
│   ├── [  87]  main.js
│   └── [ 325]  store.js
├── [ 192]  item-cart
│   ├── [9.7K]  index.vue
│   ├── [ 223]  main.js
│   ├── [ 360]  main.json
│   └── [3.2K]  store.js
├── [ 192]  item-detail
│   ├── [6.1K]  index.vue
│   ├── [  87]  main.js
│   ├── [ 275]  main.json
│   └── [   1]  store.js
├── [ 128]  login-portal
│   ├── [1.9K]  index.vue
│   └── [  88]  main.js
├── [ 192]  main
│   ├── [ 14K]  index.vue
│   ├── [  87]  main.js
│   ├── [ 289]  main.json
│   └── [ 795]  store.js
├── [ 160]  my-center
│   ├── [6.3K]  index.vue
│   ├── [ 223]  main.js
│   └── [   2]  main.json
├── [ 192]  order-buy
│   ├── [ 14K]  index.vue
│   ├── [ 249]  main.js
│   ├── [ 413]  main.json
│   └── [4.5K]  store.js
└── [ 160]  order-list
    ├── [5.7K]  index.vue
    ├── [  87]  main.js
    └── [ 208]  main.json

2. 都检查过了，其他编译的文件都正常

3. 现在的mpvue的依赖，不知道有什么问题
"mpvue-loader": "^1.1.2",
"mpvue-template-compiler": "^1.0.11",
 "mpvue-webpack-target": "^1.0.0"

**Comment by weiyunpeng** [comment]
不同名

**Comment by YinChangSheng** [comment]
问题已经解决，初步原因是main.js的代码有点问题。稍晚一点，时间，我会把问题的复现方式，以及原因发出来。

**Comment by shaojingchao** [comment]
> 1. 文件应该没有问题，我看过webpack的配置，所以都是按照规范来的
> 
> ├── [ 160] address
> │   ├── [ 164] index.vue
> │   ├── [ 87] main.js
> │   └── [ 325] store.js
> ├── [ 192] item-cart
> │   ├── [9.7K] index.vue
> │   ├── [ 223] main.js
> │   ├── [ 360] main.json
> │   └── [3.2K] store.js
> ├── [ 192] item-detail
> │   ├── [6.1K] index.vue
> │   ├── [ 87] main.js
> │   ├── [ 275] main.json
> │   └── [ 1] store.js
> ├── [ 128] login-portal
> │   ├── [1.9K] index.vue
> │   └── [ 88] main.js
> ├── [ 192] main
> │   ├── [ 14K] index.vue
> │   ├── [ 87] main.js
> │   ├── [ 289] main.json
> │   └── [ 795] store.js
> ├── [ 160] my-center
> │   ├── [6.3K] index.vue
> │   ├── [ 223] main.js
> │   └── [ 2] main.json
> ├── [ 192] order-buy
> │   ├── [ 14K] index.vue
> │   ├── [ 249] main.js
> │   ├── [ 413] main.json
> │   └── [4.5K] store.js
> └── [ 160] order-list
> ├── [5.7K] index.vue
> ├── [ 87] main.js
> └── [ 208] main.json
> 
> 1. 都检查过了，其他编译的文件都正常
> 2. 现在的mpvue的依赖，不知道有什么问题
>    "mpvue-loader": "^1.1.2",
>    "mpvue-template-compiler": "^1.0.11",
>    "mpvue-webpack-target": "^1.0.0"

请教个问题，你的目录结构用什么功能生成的呢？

**Comment by YinChangSheng** [comment]
这个问题上个月我已经解决，没有贴出来。
我贴出来说一下。可能我的原因比较特殊
![image](https://user-images.githubusercontent.com/5326189/48245022-df87b000-e423-11e8-8332-33558275d099.png)

这样写没有问题

![image](https://user-images.githubusercontent.com/5326189/48245030-eb737200-e423-11e8-8070-81dd9e667a75.png)

这样写就会出问题

我这样做是为了做一层统一的登录拦截
