### ISSUE TITLE
一个页面一直轮回点击，点返回的时候页面显示的数据都是上一个页面的？？

### ISSUE THREAD

**Issue by YangCSir** [Meituan-Dianping/mpvue#1089]
![image](https://user-images.githubusercontent.com/21410207/46795595-1dd67480-cd7d-11e8-9c66-2928c383e5f6.png)
我从这个页面点击下面的点滴生活的商家得到
![image](https://user-images.githubusercontent.com/21410207/46795893-d8ff0d80-cd7d-11e8-985c-c865514496c6.png)
我点返回闪了一下上一页的数据，然后又变成点滴生活这个商家的数据
![image](https://user-images.githubusercontent.com/21410207/46795920-eddba100-cd7d-11e8-8838-ba31f82fc466.png)

大概的描述就是这样，请问这个原因是怎么造成的呢

**Comment by aOrz** [comment]
参考 #140
