### ISSUE TITLE
使用mpvue关于同一页面跳转

### ISSUE THREAD

**Issue by mschange** [Meituan-Dianping/mpvue#1090]
问题描述： A页面(A数据)   点击跳转  到  A页面,(此时是B数据), 点击跳转  到  A页面,(此时是C数据),然后 再点击右上角返回,  回到A页面B数据，再点击右上角返回，回到A页面A数据

解决办法：根据上面的大佬方案解决，但是在清除数据的时候，在mounted生命周期中发现并没有清除，在onHide生命周期中可以解决该问题

代码：
let dataArr = [];
async mounted() {
    // Object.assign(this.$data, this.$options.data());
    // 这里可以接受页面传递过来的参数，赋值等操作
    const {
      id, type, subjectId = 0, shareUid = '',
    } = this.$route.query;
    await Promise.all([
     // 这里调用数据请求等
    dataArr.push({ ...this.$data });
  },
  onUnload() {
    // 对保存的数组进行操作，主要用来点击返回按钮的时候用
    dataArr.pop();
    const dataNum = dataArr.length;
    if (!dataNum) return;
    Object.assign(this.$data, dataArr[dataNum - 1]);
  },
  // 这里对数据进行清空，防止跳转的时候闪屏
  onHide() {
    Object.assign(this.$data, this.$options.data());
    console.log('页面发生变化会触发该事件');
  },

**Comment by aOrz** [comment]
参考 #140
