### ISSUE TITLE
使用 babel-plugin-transform-decorators-legacy babel插件支持装饰器语法，出现`Syntax Error: Unexpected token`的错

### ISSUE THREAD

**Issue by weineel** [Meituan-Dianping/mpvue#11]
### 测试代码

```
function defaultResult(target, name, descriptor) {
  const oFunc = descriptor.value
  descriptor.value = function(...arg) {
    return new Promise((resolve, reject) => {
      oFunc.apply(target, arg)
        .then(data => {
          console.log(data)
        })
        .catch(err => reject(err))
    })
  }

  return descriptor
}

class CustomerTotalApi {

  @defaultResult
  static getXXX() {
    return new Promise((resolve, reject) => {
      setTimeout(() => {
        resolve('CustomerTotalApi descriptor')
      }, 2000)
    })
  }
}

export default CustomerTotalApi

```

> 以上代码通过babel命令行和`babel-plugin-transform-decorators-legacy`插件可以正常编译。

### error
![image](https://user-images.githubusercontent.com/13328625/37197028-05ac1fe0-23b4-11e8-8b00-cc5196ae9637.png)

### 通过修改`mpvue-loader`的配置可以时错误消失，但是无法生成小程序项目了。
![image](https://user-images.githubusercontent.com/13328625/37197170-b41cd79a-23b4-11e8-8bce-0b5c910969fd.png)

**Comment by weineel** [comment]
## 添加装饰器的过程
1. 安装`babel-plugin-transform-decorators-legacy`插件
```
npm install babel-plugin-transform-decorators-legacy --save-dev
```
2. `babelrc` 中添加插件 `"plugins": ["transform-decorators-legacy", "transform-runtime"]`
```
{
  "presets": [
    ["env", {
      "modules": false,
      "targets": {
        "browsers": ["> 1%", "last 2 versions", "not ie <= 8"]
      }
    }],
    "stage-2"
  ],
  "plugins": ["transform-decorators-legacy", "transform-runtime"],
  "env": {
    "test": {
      "presets": ["env", "stage-2"],
      "plugins": ["istanbul"]
    }
  }
}
```
> 正常情况下，这样就可以使用装饰器了。

## 查看mpvue-loader源码
[const { metadata } = babel.transform(content, { plugins: [parseConfig] })](https://github.com/mpvue/mpvue-loader/blob/11e672234f26e672039c7f6257683e1ae64f6385/lib/mp-compiler/index.js#L138)

将这一行改为
```
const { metadata } = babel.transform(content, { plugins: [parseConfig, "transform-decorators-legacy"] })
```
就可以通过编译了。

## 猜想

是不是`mpvue-load`在使用babel编译代码时没有加载`babelrc`中的配置？

**Comment by anchengjian** [comment]
欢迎多看看代码提 PR

**Comment by weineel** [comment]
## 解决了
> 是`mpvue-quickstart`项目 `build/webpack.base.conf.js`的配置问题。

**调换** `babel-loader`和`mpvue-loader`的位置就行了, `webpack-loader`的加载顺序是至下向上的。

因为`checkMPEntry`设置为`true`时，`mpvue-loader`编译js时没有加载`babelrc`的配置。所以要先使用`babel-loader`进行编译。

```js
{
  test: /\.js$/,
  include: [resolve('src'), resolve('test')],
  use: [
    {
      loader: 'mpvue-loader',
      options: {
        checkMPEntry: true
      }
    },
    'babel-loader'
  ]
}
```

@anchengjian 
看源码时在想一个问题，既然要用`babel-loader`进行加载js，为什么在`mpvue-loader`中还要调用babel-core编译js呢（`checkMPEntry`设置为`true`时）？

**Comment by anchengjian** [comment]
mpvue-loader 本来的功能只打包 .vue 文件，但我们还用它来按照要求生成 wxml js wxss json 等文件，所以就用了两次，可以考虑后期优化这部分用法为 webpack plugin，降低 loader 的复杂度。

**Comment by anchengjian** [comment]
mpvue-loader@1.0.2 发布后已修复该问题。

**Comment by Stupidism** [comment]
@weineel 我想直接改成stage-1 遇到了相同的问题, 但在调换了顺序之后还是无效

**Comment by weineel** [comment]
@Stupidism 
我遇到的问题已经在mpvue-loader@1.0.2中解决了。
你遇到的问题具体是怎样的？
