### ISSUE TITLE
app onLaunch/onShow 无法触发

### ISSUE THREAD

**Issue by GeonGD** [Meituan-Dianping/mpvue#1106]
在App.vue中使用onLaunch和onShow钩子函数，但没有调用
export default {
    onLaunch(opt) {
        console.log("Launch", opt);
    },
    onShow(opt) {
        console.log("Show", opt);
    }
};
没有调用，也没有log
根据文档使用this.$root.$mp.appOptions,但打印为undefined，求解答

**Comment by awarriorer** [comment]
解决了么？

**Comment by GeonGD** [comment]
> 解决了么？
解决了
export default {
   mpType: 'app'
}
app.vue里面这样写就可以了

**Comment by awarriorer** [comment]
多谢！

**Comment by aLIEzsss4** [comment]
好用

**Comment by shangxinxiaoshuaige** [comment]
@GeonGD 你这样写，其他的生命周期能够执行吗？
