### ISSUE TITLE
当Array<Object>格式的列表由子组件渲染时，如果v-for绑定的key值不同，数据更新不会触发视图更新

### ISSUE THREAD

**Issue by MessiLiu** [Meituan-Dianping/mpvue#1108]
# [问题简单描述]

**问题复现步骤:**

1. 父组件代码
```vue
<template>
  <div>
    <children v-for="item in list" :key="item.id" :content="item.content" />
    <button @click="update">update</button>
  </div>
</template>

<script>
  import children from '@/components/children.vue'

  export default {
    components: {
      children
    },
    data() {
      return {
        list: [
          {id: 1, type: 'text', content: 'aaa'},
          {id: 2, type: 'text', content: 'bbb'},
          {id: 3, type: 'text', content: 'ccc'}
        ]
      }
    },
    methods: {
      update() {
        // 更新正常
        this.list.splice(1, 1, {id: 2, content: 'ggg'})

        // 更新失败
        this.list.splice(1, 1, {id: 4, content: 'ggg'})
      }
    }
  }
</script>
```
2. 子组件代码
```vue
<template>
  <h1>{{content}}</h1>
</template>

<script>
  export default {
    props: {
      content: String
    }
  }
</script>
```
3. 点击父组件中的`button`

**期望的表现:**
![image](https://user-images.githubusercontent.com/16557699/47198775-bc2b9100-d3a0-11e8-87a3-da617b5deeca.png)

**观察到的表现:**
第一次点击按钮时，bbb变成了ggg，但瞬间又变回bbb，在屏幕上看起来就像是bbb闪了一下
第二次点击按钮时，bbb变成了ggg，但此时的ggg相当于上一次的状态，举个例子来说：假如我预想的是第一次点击变成ggg，第二次点击变成hhh。那么实际测试的结果是：第一次点击后bbb闪了一下并没有变，第二次点击后变成了ggg，第三次点击后变成hhh

**屏幕截图和动态 GIF 图**
![-2](https://user-images.githubusercontent.com/16557699/47199207-10377500-d3a3-11e8-9af0-c146d1aff072.gif)

**Comment by MessiLiu** [comment]
最新的测试结果：在新的key和旧的key相同的情况下视图正常更新，如果不同则如我上述所说

**Comment by zxzhgk** [comment]
尝试过 使用set方法更新么

**Comment by MessiLiu** [comment]
> 尝试过 使用set方法更新么

试过set，跟上面一样的效果

**Comment by MessiLiu** [comment]
谜一般的机器人。。。

**Comment by MessiLiu** [comment]
> @MessiLiu 解决了吗，我也碰到这个问题

暂时没解决，先避免出现这种情况，有时间再想想啥原因

**Comment by xinconan** [comment]
我也遇到了，用了splice和filter都没有用，显示的是上一个操作的结果

**Comment by xinconan** [comment]
用setTimeout解决了

**Comment by SnowCoCo** [comment]
> 用setTimeout解决了

为什么用setTimeout有效果了？
