### ISSUE TITLE
static下的静态资源 run dev后不会拷贝到dist下面吗

### ISSUE THREAD

**Issue by rocing** [Meituan-Dianping/mpvue#1110]
# static下的静态资源 run dev后不会拷贝到dist下面吗
我看webpack下面有CopyWebpackPlugin.
如果不手动拷贝 npm run dev会报错 
`events.js:182
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, open '****/dist/static/imgs/logo.png'
`

**Comment by jiaxiaon** [comment]
除非新建一个文件需要重新build一下，其他的图片什么的都是热加载啊

**Comment by L-minimalist** [comment]
散了吧，现在项目都没人维护了

**Comment by rocing** [comment]
> 除非新建一个文件需要重新build一下，其他的图片什么的都是热加载啊

真不行 每次都要手动复制过去

**Comment by rocing** [comment]
> 散了吧，现在项目都没人维护了

入坑了怎么办

**Comment by F-loat** [comment]
这个是 webpack 配置的问题，建议使用官方模板生成一个新项目，没问题的话对比下具体配置

**Comment by zhangruinian** [comment]
issue多的吓人呀 ,感觉作者维护的心累,人太少

**Comment by hucq** [comment]
1. 会拷贝的，检查一下 static 目录是不是对的；
2. 如果改了位置，webpack 构建规则也需要调整。
3. 重新初始化一个项目，对比下 build 目录下的构建规则。
4.实在解决不了，发个demo出来。
