### ISSUE TITLE
mpvue1.0.11版本在http请求的参数使用扩展运算符展开对象时报错

### ISSUE THREAD

**Issue by XdyGoGo** [Meituan-Dianping/mpvue#1112]
# [问题简单描述]
mpvue1.0.11版本在http请求的参数使用扩展运算符展开对象时报错
**问题复现步骤:**
 ERROR  Failed to compile with 1 errors10:34:56

 error  in ./src/common/request.js

Syntax Error: Unexpected token (50:4)
  48 | export function get (options = {}) {
  49 |   return request({
> 50 |     ...options,
     |     ^
  51 |     method: 'GET'
  52 |   })
  53 | }

1. [第一步]
2. [第二步]
3. [其他步骤...]

**期望的表现:**
是否需要配置babelrc？据说mpvue1.0.11不是已经修复了扩展运算符失效的问题吗
[在这里描述期望的表现]

**观察到的表现:**

[在这里描述观察到的表现]

**屏幕截图和动态 GIF 图**

![复现步骤的屏幕截图和动态 GIF 图](图片的 url)

**Comment by AibiTi** [comment]
#1123

**Comment by F-loat** [comment]
mpvue-loader 早期版本不会读取外部的 babelrc 配置，已经修复过了，可以调整配置试下

**Comment by aOrz** [comment]
同上
