### ISSUE TITLE
this.$root.$mp参数报错未定义

### ISSUE THREAD

**Issue by thisisonepz** [Meituan-Dianping/mpvue#1114]
# [this.$root.$mp参数拿不到]

**问题复现步骤:**

1. [created(){
   console.log(this.$root)
 //这个能拿到控制台能看到$mp的参数值
  console.log(this.$root.$mp)
// 报错未定义

 }]

**我希望拿到$mp的参数:**

[{
  appOptions：{
     path:"pages/index/main"
  },
 query:{},
 referrerInfo{},
 scene:1001
}]

**但是我拿到的:**

[是undefined]

**屏幕截图和动态 GIF 图**

![image](https://user-images.githubusercontent.com/28385124/47276198-05b9ed00-d5e8-11e8-9413-d0e45a02ef25.png)

**Comment by songGuangHui** [comment]
看下文档的生命周期，created是拿不到的
