### ISSUE TITLE
mp-loader路径设置问题

### ISSUE THREAD

**Issue by KennyWho** [Meituan-Dianping/mpvue#112]
mpvue-quickstart启动后 webpack引用的是./static目录，没有./static编译会报错，src/pages/下的页面使用src="../../../static/"路径可以访问图片，但在手机预览时无法显示图片。

复现方式，用quickstart启动一个项目，引入图片，手机预览。

原因是mp-loader生成的dist/components/目录与static/目录同级。暂时解决方法是把复制static到src目录下。

**Comment by F-loat** [comment]
使用 /static/xxx 的方式引用
