### ISSUE TITLE
用vant-weapp里的field组件，blur事件获取不到输入框里的值

### ISSUE THREAD

**Issue by Amyuan23** [Meituan-Dianping/mpvue#1122]
## 用vant-weapp里的field组件，blur事件获取不到输入框里的值

**问题复现步骤：**

```
<van-field
    :value="phone"
    clearable
    label="手机"
    placeholder="请输入手机号"
    :error-message= "errMessage"
    @blur="blurPhone"
 />
```

```
    blurPhone (e) {
      this.phone = e.mp.detail
      console.log(e)
    }
```

**期望的表现：**

e.mp.detail的值为输入的手机号

**观察到的表现：**

e.mp.detail的值为 undefined

**Comment by jerryachel** [comment]
> 
> ## 用vant-weapp里的field组件，blur事件获取不到输入框里的值
> 
> **问题复现步骤：**
> 
> ```
> <van-field
>     :value="phone"
>     clearable
>     label="手机"
>     placeholder="请输入手机号"
>     :error-message= "errMessage"
>     @blur="blurPhone"
>  />
> ```
> 
> ```
>     blurPhone (e) {
>       this.phone = e.mp.detail
>       console.log(e)
>     }
> ```
> 
> **期望的表现：**
> 
> e.mp.detail的值为输入的手机号
> 
> **观察到的表现：**
> 
> e.mp.detail的值为 undefined

看了下vant的文档和源码，是vant的blur本来就没有回调输入值，不是mpvue的锅。
如果需要在失焦的时候获取值，建议直接获取value的值

**Comment by Amyuan23** [comment]
> > ## 用vant-weapp里的field组件，blur事件获取不到输入框里的值
> > **问题复现步骤：**
> > ```
> > <van-field
> >     :value="phone"
> >     clearable
> >     label="手机"
> >     placeholder="请输入手机号"
> >     :error-message= "errMessage"
> >     @blur="blurPhone"
> >  />
> > ```
> > ```
> >     blurPhone (e) {
> >       this.phone = e.mp.detail
> >       console.log(e)
> >     }
> > ```
> > **期望的表现：**
> > e.mp.detail的值为输入的手机号
> > **观察到的表现：**
> > e.mp.detail的值为 undefined
> 
> 看了下vant的文档和源码，是vant的blur本来就没有回调输入值，不是mpvue的锅。
> 如果需要在失焦的时候获取值，建议直接获取value的值

你说的对，是我蠢了，捂脸，用confirm就可以完成我想要的需求了。

**Comment by litianyangz** [comment]
<van-field :value="password" type="password" @input="pwdVal" clearable placeholder="请输入密码" />
<van-button type="primary" round size="large" @click="submitCellphone">登录</van-button>
有没有发现这个组件带clearable 属性的输入框 点击清空按钮之后 点击登录按钮之后 第一次点击不生效，只有点击第二次点击事件生效

**Comment by susan007** [comment]
> <van-field :value="password" type="password" @input="pwdVal" clearable placeholder="请输入密码" />
> <van-button type="primary" round size="large" @click="submitCellphone">登录
> 有没有发现这个组件带clearable 属性的输入框 点击清空按钮之后 点击登录按钮之后 第一次点击不生效，只有点击第二次点击事件生效

我发现了，只要使用了clearable，那么界面的下一个事件就不生效，点两次才生效。但没找到好的解决办法。
