### ISSUE TITLE
mpvue/example中 echarts怎么刷新视图

### ISSUE THREAD

**Issue by softshild** [Meituan-Dianping/mpvue#1126]
https://github.com/mpvue/examples/tree/master/echarts
怎么动态跟新echarts展示的数据？接口好像没有暴露出echarts实例，应该怎么获取到实例？

**Comment by softshild** [comment]
var chartComponent = this.$root.$mp.page.selectComponent('#mychart-dom-bar')
          if (chartComponent && chartComponent.chart) {
            chartComponent.chart.setOption(options)
          }

已找到获取echarts实例方式。。。

**Comment by superguoger** [comment]
太赞了 找了好久
