### ISSUE TITLE
子组件this.$root.$mp.query 得到的是上次打开页面的值

### ISSUE THREAD

**Issue by xiejun-net** [Meituan-Dianping/mpvue#1127]
## 子组件this.$root.$mp.query 得到的是上次打开页面的值

![image](https://user-images.githubusercontent.com/12869626/47474882-c4c21280-d84b-11e8-9d9b-254c54875044.png)

下次打开页面的时候this.price的值不变

**Comment by 1160007652** [comment]
我也是， 跳转路由时，获取完信息。点击下方的更多列表又进入这个页面。后退时。获取到的是 上一次的id

**Comment by bacy** [comment]
听说新版本已经解决这个问题了

**Comment by heyushuo** [comment]
不要直接跳转,使用 wx.redirectTo跳转,小程序本身就限制了跳转次数,你如果来回跳转,会叠加很多层

**Comment by zxzhgk** [comment]
使用 https://github.com/HelloZJW/mpvue-page-factory 他的这个方法可以解决同一页面多次访问时 watch,props,computed 等一系列缓存问题

**Comment by YangQii** [comment]
> 不要直接跳转,使用 wx.redirectTo跳转,小程序本身就限制了跳转次数,你如果来回跳转,会叠加很多层

其实我私信你问的就是这个问题，然后用下面这个 mpvue-page-factory 解决的

**Comment by hucq** [comment]
@xiejun-net 这个问题的解法：使用小程序生命周期即可，譬如 `onLoad`
vue 的生命周期和小程序有差别，目前的同步策略并不是最优。
