### ISSUE TITLE
mpvue分包配置（仅供参考）

### ISSUE THREAD

**Issue by zyh9** [Meituan-Dianping/mpvue#1130]
function getEntry (rootSrc, path) {
	var map = {};
	glob.sync(rootSrc + '/' + path + '/**/main.js')
	.forEach(file => {
		var key = relative(rootSrc, file).replace('.js', '');
		map[key] = file;
	})
	return map;
}

let entry;
const pagesEntry = getEntry(resolve('./src'), 'pages')
let {subPackages} = require('../src/main.json')
if(subPackages){
	let entryPath = subPackages.map(({root})=>({root}))
	let entryArray = [];
	entryPath.forEach( e =>{
		entryArray.push(getEntry(resolve('./src'), e['root']))
	})
	entry = Object.assign({}, appEntry, pagesEntry, ...entryArray)
}else entry = Object.assign({}, appEntry, pagesEntry)

**Comment by tolerious** [comment]
以前的main.js如何改成main.json？
