### ISSUE TITLE
为什么叫 mpvue 而不叫 myvue？

### ISSUE THREAD

**Issue by AibiTi** [Meituan-Dianping/mpvue#1134]
## 为什么叫 mpvue 而不叫 myvue？
为什么叫 mpvue 而不叫 myvue？

**新功能相关的问题issue或讨论：**

[在这里引用新功能相关的讨论]

**新功能的实现：**

[在这里填写或简单描述功能的实现方式或需求的解决方式]

**相关项目或文档：**

[在这里引用相关项目或文档地址]

**Comment by aOrz** [comment]
命名而已，不用太纠结
