### ISSUE TITLE
使用官方swiper，当重新进页面获取数据不一致时，多出的数据会变成空白页

### ISSUE THREAD

**Issue by JokerLoLgrey** [Meituan-Dianping/mpvue#1141]
## [问题简单描述]
使用mpvue开发，官方组件swiper轮播图数据发生改变时，部分图片数据不会渲染，但是图片张数是正确的，

如果轮播张数相同就不会出现这个bug
**问题复现步骤：**

1. [第一步]
2. [第二步]
3. [其他步骤...]

**期望的表现：**

[在这里描述期望的表现]

**观察到的表现：**

[在这里描述观察到的表现]

**屏幕截图或动态图：**
![img_0147](https://user-images.githubusercontent.com/33446705/47650529-7b5f2380-dbbb-11e8-805e-73e4a061a391.GIF)

![复现步骤的屏幕截图和动态 GIF 图](图片的 url)
[建议提供可运行的demo]

**Comment by aOrz** [comment]
[问题简单描述] 要改成你的标题
