### ISSUE TITLE
mpvue与官方swiper组件有bug

### ISSUE THREAD

**Issue by JokerLoLgrey** [Meituan-Dianping/mpvue#1144]
## mpvue与官方swiper组件有bug

**问题复现步骤：**

根据id的不同，同一页面请求不同数据，当轮播图片数据不统一时，比上一次多余的数据会被渲染成空白页，但是轮播图片张数是正确的

**期望的表现：**

根据id的不同，同一页面请求不同数据，轮播正常显示

**观察到的表现：**

数据不加载

**屏幕截图或动态图：**

![img_0147](https://user-images.githubusercontent.com/33446705/47651814-27563e00-dbbf-11e8-9a86-75ba37a1d95d.GIF)

已解决 swiper-item 不能写style样式，数据更新会覆盖生成的style

**Comment by JokerLoLgrey** [comment]
已解决了

**Comment by bacy** [comment]
> 已解决了

请问如何解决的？

**Comment by JokerLoLgrey** [comment]
> > 已解决了
> 
> 请问如何解决的？

我是因为在swiper-item这个标签写了行内样式，动态加载数据时，会覆盖小程序组件自己生成的行内样式

**Comment by hucq** [comment]
我试了一下没复现问题，如果还有问题贴一下代码。
