### ISSUE TITLE
组件嵌套，父组件通过props传值给子组件，第二次进入后数据不更新

### ISSUE THREAD

**Issue by zxzhgk** [Meituan-Dianping/mpvue#1148]
有一个公共组件A,一个入口页面B,一个详情页面C. 详情页面C中使用了公共组件A, 现在通过B页面进入C页面，C页面props 传值给公共组件A,退出C页面，然后再同B页面进入C页面，此时公共组件A显示的数据还是第一次进入C页面的数据，没有更新

**Comment by zxzhgk** [comment]
感谢大佬 https://github.com/HelloZJW/mpvue-page-factory 他的这个方法可以解决同一页面多次访问时 watch,props,computed 等一系列缓存问题

**Comment by guoPengSong** [comment]
> 感谢大佬 https://github.com/HelloZJW/mpvue-page-factory 他的这个方法可以解决同一页面多次访问时 watch,props,computed 等一系列缓存问题

感谢大佬也解决了我的问题
