### ISSUE TITLE
间接 import 组件无法生成 wxml

### ISSUE THREAD

**Issue by armyja** [Meituan-Dianping/mpvue#115]
// src/pages/index/index.vue
```
<template>
  <toptips />
</template>

<script>
import {TopTips} from 'mpvue-zanui'
export default {
  components: {
    toptips: TopTips
  },
...
</script>
```

// node_modules/mpvue-zanui/index.js
```
import TopTips from './src/components/zan/toptips'
export {TopTips}
```
// xxx/.../xxx/toptips.vue
```
<template >
  <div>this is a toptips</div>
</template>
```
![image](https://user-images.githubusercontent.com/11900676/37521964-6c8788b8-295d-11e8-870d-93948021eac5.png)

而把 `import {TopTips} from 'mpvue-zanui'` 改成 
`import {TopTips} from 'mpvue-zanui/src/components/zan/toptips'`，就能正常显示。

![image](https://user-images.githubusercontent.com/11900676/37522164-101ef844-295e-11e8-89c1-8ca87db68c7e.png)

（两种 import 方式都能正常调用子组件的方法）希望 [mpvue-loader 升级重构](https://trello.com/c/5SiexnBu/18-mpvue-loader-%E5%8D%87%E7%BA%A7%E9%87%8D%E6%9E%84) 之后能解决这个问题~

**Comment by youngluo** [comment]
我也出现了上述问题

**Comment by hwaphon** [comment]
同上

**Comment by suinia** [comment]
在单独的js中import组件没法正常调用
```
// index.vue 
<card :text="'xxxx'"></card>
<script>
  import vm from './vm';
  export default vm;
</script>

//  vm.js
import card from '@/components/card';
export default {
    components: {
      card
    }
  };
```

只能这样：
// index.vue
<script>
  import card from '@/components/card';
  export default {
    components: {
      card
    }
  };
</script>
