### ISSUE TITLE
scroll-view原生组件滚动到顶部bug

### ISSUE THREAD

**Issue by Megan-TA** [Meituan-Dianping/mpvue#1151]
## [问题简单描述]
scroll-view 在做tab选项切换 view展示不通内容
如果设置 scroll-top 再触发滑到底部加载更多方法 加载完滚动条会回到顶部 

**问题复现步骤：**
代码如下：
```shell
<scroll-view
      class = 'scrollView'
      scroll-y
      :scroll-top = '0'
      enable-back-to-top
      @scrolltolower = 'handlerScrollToLower'
      >
      <Item
        :datas = 'datas'
      />
      <div class="no-more-data" v-if = 'noDataFlag'>
        暂无更多数据！
      </div>
</scroll-view>
```

1. [第一步]
拖动最底部触发自动加载更多
2. [第二步]
加载完成之后 scroll-view内部滚动条瞬间回到最顶部
3. [其他步骤...]

**期望的表现：**

加载数据之后不会回到顶部，切换tab时候回到顶部

[在这里描述期望的表现]

**观察到的表现：**

[在这里描述观察到的表现]

**屏幕截图或动态图：**

![复现步骤的屏幕截图和动态 GIF 图](图片的 url)
[建议提供可运行的demo]

**Comment by zxzhgk** [comment]
#639

**Comment by Megan-TA** [comment]
> #639

按照639的修改源码的更新策略是解决了 不过这样修改源码的方式是一个最优解吗？
