### ISSUE TITLE
配置页面单独的config不起作用

### ISSUE THREAD

**Issue by tanhualang** [Meituan-Dianping/mpvue#1153]
![qq 20181101132704](https://user-images.githubusercontent.com/30031243/47834260-dc644280-ddd9-11e8-97f4-1ede943461c6.jpg)
如图，在单个页面的main.js加入了配置项，但并不起作用，还是显示全局app.json的配置

**Comment by zxzhgk** [comment]
mpvue-loader 版本是多少

**Comment by NO-MAP** [comment]
新建一个main.json
和index.vue 同级
`{
	"navigationBarTitleText": "demo“
}`

**Comment by tanhualang** [comment]
> 新建一个main.json
> 和index.vue 同级
> `{ "navigationBarTitleText": "demo“ }`

嗯嗯，之后发现了要这样

**Comment by tanhualang** [comment]
> mpvue-loader 版本是多少

之后发现了需要建一个json文件写

**Comment by aOrz** [comment]
新版本 loader 需要再目录下建 json 文件配置

**Comment by F-loat** [comment]
可以使用 [mpvue-config-loader](https://juejin.im/post/5bffd5de51882526a643fcd1) 来简化配置
