### ISSUE TITLE
smartprogram alpha user feedback 

### ISSUE THREAD

**Issue by hucq** [Meituan-Dianping/mpvue#1155]
# mpvue 开发百度小程序指导手册

## 注意：
- 功能内测阶段，尚不对外开放，使用请谨慎，也欢迎反馈问题。
- 所有此功能的用户反馈都请直接回复到下方，为集中管理，请勿另开issue.

---
#####  第一步：初始化项目

构建脚本有较大调整，暂未集成到 mpvue-quickstart，初始化项目工程，请直接使用示例项目:

```
git clone git@github.com:hucq/mpvue-platform-sample.git

```

##### 第二步：更新依赖版本
为不影响历史用户，支持百度小程序的功能暂不开放，只能通过指定 @beta 版本号安装

```
npm install
npm install mpvue@beta mpvue-loader@beta mpvue-template-compiler@beta
```

##### 第三步骤：构建目标代码
当前可构建微信和百度两个平台目标代码，具体参考 package.json 中 script 指令，构建百度平台如下

```
npm run dev:swan  // 开发模式
npm run build:swan // 线上模式
```

##### 注意事项

1. 示例代码中 api 调用建议统一改为 mpvue 前缀，如需对特定平台做单独处理，可通过 mpvuePlatform 判断

```
    let logs;
    if (mpvuePlatform === 'swan') {
      logs = mpvue.getStorageSync('logs');
      // 此处 mpvue 等价于 swan
      // 其它处理
    } else if (mpvuePlatform === 'wx') {
      logs = mpvue.getStorageSync('logs');
      // 此处 mpvue 等价于 wx
    }
```
2. 图片目录默认统一为 static，与 src 并列 
3. **请锁定 mpvue 依赖的版本号**(mpvue， mpvue-loader, mpvue-template-compiler)，请勿试用版本号区间范围匹配规则

---
## 进阶使用
上述方案可使用已经发布到 npm 的指定版本。开发期间如需修改 mpvue 代码，可 clone 源码并通过 npm link 的方式在本地运行。方式如下

##### 第一步：clone 源码
目前最新的代码均在 `feature/platform` 分支

```
git clone git@github.com:Meituan-Dianping/mpvue.git   主仓库
git clone git@github.com:mpvue/mpvue-loader.git   loader仓库
```

##### 第二部：修改代码和构建
- `mpvue` 源码存放在 src 目录，修改后需要构建，`mpvue-loader` 无需构建,
- 构建后的目标文件在 package 目录 `mpvue`, `mpvue-template-compiler` 中
- 可分别进入目录，使用 npm link 命令关联到全局

构建方式：

```
npm run build:mpvue

// 或开发模式
npm run dev:mpvue
npm run dev:mpvue:compiler
```

##### 第三部：使用 npm link 指令应用本地代码
在实际项目中通过 npm link 使用本地代码

```
cd packages/mpvue
npm link

cd packages/mpvue-template-compiler 
npm link

cd myproject
npm link mpvue

cd mpvue-loader
npm link mpvue-template-compiler
```

##### beta 版本更新记录：
1. 本地图片使用：图片目录统一在 static 目录，通过根路径引用，网络图片建议写完整url（scheme)
2. 双向绑定语法
3. require 根路径问题
4. 一些页面级别的设置 如：onShareAppMessage 的设置没有生效
5. 建议示例中加入less、sass构建，现在默认css构建不支持@import语法
6. 统一api 调用，通过 mpuve 前缀调用，形如 mpvue.getUserInfo，也可通过 mpvuePlatform 判断当前环境做分支调用，如 if (mpvuePlatform === 'swan') swan.getUserInfo

**Comment by hucq** [comment]
## 注意事项：同一字段设置相同值不生效问题

##### 案例介绍
scroll-view 中，scrollTop 维护在 data 中并设定初始值 0，内容滚动后想要重新回到顶部，再次设定为0，实际不触发。

##### 问题原因：
scrollTop 并没有在滚动过程中维护更新，再次设置将被忽略，在 vuejs 中将忽略此更新，mpvue 不会触发 setData 调用

##### 解决方案：
将 scrollTop 在滚动事件中维护更新，记录在 data 中，使再次设置时新旧值不同

##### 示例代码：

```
<template>
  <div class="section">
    <scroll-view
      scroll-y="true"
      style="height:300px;border:1rpx solid gray;box-sizing:border-box;"
      @scroll="scroll"
      :scroll-top="scrollTop"
    >
      <div class="scroll-view-item bc_green"></div>
      <div class="scroll-view-item bc_red"></div>
      <div class="scroll-view-item bc_yellow"></div>
      <div class="scroll-view-item bc_blue"></div>
      <div class="scroll-view-item bc_green"></div>
      <div class="scroll-view-item bc_red"></div>
      <div class="scroll-view-item bc_yellow"></div>
      <div class="scroll-view-item bc_blue"></div>
    </scroll-view>
  </div>
</template>

<script>
  export default {
    data () {
      return {
        scrollTop: 100
      }
    },

    methods: {
      scroll(e) {
        this.scrollTop = e.target.scrollTop
        console.log(e)
      }
    },

    created () {
      setTimeout(() => {
        this.scrollTop = 100;
      }, 5E3)
      setTimeout(() => {
        this.scrollTop = 100;
      }, 10E3)
    }
  }
</script>

<style scoped>
  .scroll-view-item{
    width:100%;
    height:200px;
  }
  .bc_green{
    background-color:green;
  }
  .bc_red{
    background-color:red;
  }
  .bc_yellow{
    background-color:yellow;
  }
  .bc_blue{
    background-color:blue;
  }
</style>
```

**Comment by hucq** [comment]
# 功能新增：.frameworkinfo 

## 介绍
该功能将在执行 百度小程序构建的时候，在项目根目录和dist目录分别生成一份配置文件，用于辅助百度小程序排查问题，内容形如：

```
{
    "toolName": "mpvue",
    "toolFrameWorkVersion":"1.0.14-1",
    "toolCliVersion":"0.0.4",
    "createTime":1545987718972
}
```

## 字段含义解释：
- "toolName" 框架名称
- "toolFrameWorkVersion" 框架版本号
- "toolCliVersion" 模板工程版本号
- "createTime" 构建时间


## 使用方式
使用最新版本的 mpvue/quick-start 项目模板创建项目即可获得所有功能
如需增量自定义配置，可以参考修改：https://github.com/mpvue/mpvue-quickstart/pull/56/files

**Comment by OEEO** [comment]
请问，如果，图片还想像之前那样打包，要怎么配置呢？
因为有些图片是放在分包里的，不想放在static里。

**Comment by OEEO** [comment]
问题：列表渲染时，在自定义组件标签（列表中的某一项）中通过 :key="key"，给自定义组件绑定key时，组件的事件无法触发。目前只能把整个列表定义为一个组件，然后在组件内部 v-for，:key="key"，这样才有效。应该是组件间的那个索引没引绑定的问题

**Comment by shimengno1** [comment]
你好，请问，我用mpvue开发可以同时生产支付宝小程序，微信小程序，百度小程序的代码吗？就是一段代码跨平台

**Comment by levinzero** [comment]
你好，请问关于组件间的通信，在开发工具中调试没有问题，在手机中预览发现组件间的通信不会触发
