### ISSUE TITLE
单独的page页面写的main.json除了标题能改变 其他配置都会被全局main.json样式覆盖

### ISSUE THREAD

**Issue by Megan-TA** [Meituan-Dianping/mpvue#1156]
## [问题简单描述]

单独的page页面写的main.json除了标题能改变 其他配置都会被全局main.json样式覆盖

比如：
pags/list/main.json  下定义整个列表页的背景色是白色 而外部全部全局的背景色是红色，最后所有的page都是红色。

**期望的表现：**

每个页面的main.json可以覆盖全局设置的默认页面样式

**Comment by Megan-TA** [comment]
"mpvue-loader": "^1.1.2" 已更新多送1.1.1版本以上

**Comment by F-loat** [comment]
查看下 dist 目录下生成的文件是否有问题

**Comment by wuxiaolan91** [comment]
我更新成楼上这样子标题也还是不出来
`"mpvue-loader": "^1.1.2",`
代码
`const app = new Vue(App)
app.$mount()
export default {
  config: {
    'navigationBarTitleText': '最新约稿函'
  }
}`
标题啊还是全局配置的那个标题.
