### ISSUE TITLE
图片引入报错

### ISSUE THREAD

**Issue by wcharles666** [Meituan-Dianping/mpvue#1158]
## [问题简单描述]
使用import引用assests中图片报错

**问题复现步骤：**
**期望的表现：*这个如何解决*

[在这里描述期望的表现]

**屏幕截图或动态图：**
**代码：  
```<template>  
  <view class="indexBox">  
    <img :src="navBg" alt="" class="indexImg">  
  </view>  
</template>  
<script>  
import navBg from "@/assests/indexBg.png";  
export default {  
  data () {  
    return {  
      navBg  
    }  
  } 
报错信息：   
This dependency was not found:

* @/assests/indexBg.png in ./node_modules/babel-loader/lib!./node_modules/mpvue-loader/lib/selector.js?type=script&index=0!./src/pages/index/index.vue

To install it, you can run: npm install --save @/assests/indexBg.png

**Comment by wcharles666** [comment]
代码：
<template>
  <view class="indexBox">
    <img :src="navBg" alt="" class="indexImg">
  </view>
</template>

<script>
import navBg from "@/assests/indexBg.png";
export default {
  data () {
    return {
      navBg
    }
  },
报错信息：
This dependency was not found:

* @/assests/indexBg.png in ./node_modules/babel-loader/lib!./node_modules/mpvue-loader/lib/selector.js?type=script&index=0!./src/pages/index/index.vue

To install it, you can run: npm install --save @/assests/indexBg.png

**Comment by wcharles666** [comment]
代码：  
`<template>
  <view class="indexBox">
    <img :src="navBg" alt="" class="indexImg">
  </view>
</template>

<script>
import navBg from "@/assests/indexBg.png";
export default {
  data () {
    return {
      navBg
    }
  },`  
报错信息：  
This dependency was not found:

* @/assests/indexBg.png in ./node_modules/babel-loader/lib!./node_modules/mpvue-loader/lib/selector.js?type=script&index=0!./src/pages/index/index.vue

To install it, you can run: npm install --save @/assests/indexBg.png

**Comment by NextBoy** [comment]
你的assets文件夹放在哪，@是指向src文件夹

**Comment by wcharles666** [comment]
查了下@ 对应的路径   谢谢 已解决！
