### ISSUE TITLE
希望能尽快支持slot

### ISSUE THREAD

**Issue by cuijiemmx** [Meituan-Dianping/mpvue#116]
这个用法太常用了...支持了好从wepy迁移过来

**Comment by cuijiemmx** [comment]
如果支持全部slot特性比较麻烦的话，请先支持下最常见的简单用法吧

**Comment by anchengjian** [comment]
最好可以列出常见的简单方法有哪些，我们做了一部分的简单支持，但诸如 组件 作为 slot ，scoped slot 等这种较为复杂的用法还无法支持。

**Comment by blade254353074** [comment]
感觉文档上说的有点不清楚，详细的不支持列表：
![image](https://user-images.githubusercontent.com/9346008/37563576-eb92cb88-2abe-11e8-823a-90b7d29cfa5a.png)

所以是不支持 slot，还是不支持 scoped slot 呢？希望文档能讲清楚这些问题

**Comment by cuijiemmx** [comment]
@anchengjian 我觉得比较常用的是vue文档中的单个插槽和具名插槽（当然需要支持组件作为slot，不然组件化不完整）
https://cn.vuejs.org/v2/guide/components.html

@blade254353074 说的文档问题我觉得很对，没说清楚是否支持部分slot用法，具体支持哪部分slot用法，应该讲清楚一些

**Comment by blade254353074** [comment]
```html
<component>
  <div>
    <p>Foobar</p>
    <sub>Foobaz</sub>
  </div>
</component>
```

至少这种 Slot 要支持吧？
@anchengjian

**Comment by anchengjian** [comment]
@blade254353074 这种是最简单，也是最先支持的，如果你那儿渲染有问题的话，可能某个地方出了 bug，建议新开 issue 提一下详细复现过程。

**Comment by F-loat** [comment]
组件作为 slot 内容，具名 slot，slot 事件透传这几个在开发一些容器类组件时都会比较有用

**Comment by blade254353074** [comment]
@anchengjian 

会报 template not found，我有时间发 issue

```html
<component>
  <div>
    <p>Foobar</p>
  </div>
  <div>Foobaz</div>
</component>
```

这种也支持么？

**Comment by presidentma** [comment]
refs也不能用吧

**Comment by xxxxxMiss** [comment]
这个确实很常用，用了slot的组件，目前都无法直接使用。还有就是希望mpvue尽快支持组件上的`class`,`style`

**Comment by blade254353074** [comment]
@anchengjian 
`<badge v-if="userInfo.accountType">{{ badgeText }}</badge>`  
这种 slot 也不支持么

**Comment by anchengjian** [comment]
[1.0.8](https://github.com/Meituan-Dianping/mpvue/releases/tag/1.0.8) 修复了一些 slot bug，请升级相应的 `mpvue mpvue-template-compiler mpvue-loader` 后再用

**Comment by gatinul** [comment]
@anchengjian 貌似无法对slot的内容进行热更新，需要重新npm run dev才会生效

**Comment by anchengjian** [comment]
@gatinul 试试 https://github.com/mpvue/mpvue-loader/releases/tag/1.0.13 这个最新的版本
