### ISSUE TITLE
VM94:2 未找到入口 app.json 文件，或者文件读取失败，请检查后重新编译。

### ISSUE THREAD

**Issue by yiyaxueyu** [Meituan-Dianping/mpvue#1162]
## [问题简单描述]
VM94:2 未找到入口 app.json 文件，或者文件读取失败，请检查后重新编译。

**问题复现步骤：**

1. 按步骤走到 npm run dev ，在小程序中报错

**期望的表现：**
正常运行

**Comment by z410814773** [comment]
刚接触mpvue，昨天也遇到了这个问题

**Comment by liyangmsn** [comment]
project.config.json里
miniprogramRoot 改成 dist/wx/

**Comment by liujinhuan** [comment]
> project.config.json里
> miniprogramRoot 改成 dist/wx/

真正的解决了我的问题。

**Comment by fanfan1280** [comment]
1，config/index.js 里面
    index: path.resolve(__dirname, `../dist/${fileExt.platform}/index.html`),
    assetsRoot: path.resolve(__dirname, `../dist/${fileExt.platform}`),
改成：
    index: path.resolve(__dirname, `../dist/index.html`),
    assetsRoot: path.resolve(__dirname, `../dist/`),
2，build/webpack.dev.config里面
       filename: utils.assetsPath('[name].[contenthash].css')
改成：
      filename: utils.assetsPath(`[name].wxss`)

**Comment by ShiningDan** [comment]
https://github.com/mpvue/mpvue-quickstart/pull/54

**Comment by ShiningDan** [comment]
https://github.com/mpvue/mpvue-quickstart/commit/3fcca8fb24415a6d3321f967e50a39db7a088508

已修复

**Comment by HarborZeng** [comment]
> project.config.json里
> miniprogramRoot 改成 dist/wx/

这个办法没有解决我的问题，依旧提示未找到入口 app.json 文件，@ShiningDan

**Comment by tolerious** [comment]
npm run dev怎么卡住不动了，  也不能生成dist文件夹。

**Comment by xiguakaoya** [comment]
> npm run dev怎么卡住不动了， 也不能生成dist文件夹。

vue文件里面没有<script></script>，就会一直编译。或者App.vue,main.js放置的目录有问题。

**Comment by DunDunDunAbandon** [comment]
> dist/wx/

为啥我不行。。
