### ISSUE TITLE
taro全面支持微信/百度/支付宝了，mpvue啥时候能开始支持啊

### ISSUE THREAD

**Issue by duminghong** [Meituan-Dianping/mpvue#1166]
## 建议支持百度/支付宝小程序
强烈期待mpvue支持啊~

**Comment by mpandar** [comment]
顶一个

**Comment by wuhy** [comment]
如果有开发百度小程序，欢迎关注下 https://github.com/ecomfe/okam

**Comment by TonyLuo** [comment]
对比下taro的更新频率，感觉这个项目要凉

**Comment by TonyLuo** [comment]
alpha 版本支持百度小程序，但还没看到支付宝小程序的支持版本。
https://github.com/Meituan-Dianping/mpvue/issues/1155
