### ISSUE TITLE
引入第三方组件后，如何使用selectComponent

### ISSUE THREAD

**Issue by dogscar** [Meituan-Dianping/mpvue#117]
引入第三方组件后，在page里this.selectComponent('#id') 没有效果。有正确的调用方法吗？

**Comment by F-loat** [comment]
你是想实现什么功能啊，获取到页面实例后应该可以使用这个方法

**Comment by daiqing2009** [comment]
如何获得页面实例？

**Comment by vopdoo** [comment]
@dogscar 是怎么解决的呢 看你关闭了

**Comment by kevinlvhsl** [comment]
> @dogscar 是怎么解决的呢 看你关闭了

他之前关闭了，是因为那时候页面的原型上Component里面还有selectComponent方法，
新版的mpvue中没有这个方法了。。。所以会报错。
