### ISSUE TITLE
ios8 设备弹出invoking page() in async task

### ISSUE THREAD

**Issue by TimorCookie** [Meituan-Dianping/mpvue#1176]
## [问题简单描述]
ios8系统设备下会弹出以下警告和报错
从表现来看整个页面都无法注册 样式及交互全部失效

Page[pages/index/main] not found. May be caused by: 1.forgot to add page route in app.json. 2.Invoking Page{} in async task.

thirdScriptError
sdk uncaught third error
SyntaxError
line:16045,column:0,SynataxError:Unexpected keyword 'const'. Const declarations are not supported in strict mode. Stack:

**问题复现步骤：**

1. [第一步]
2. [第二步]
3. [其他步骤...]

**期望的表现：**

[在这里描述期望的表现]

**观察到的表现：**

[在这里描述观察到的表现]

**屏幕截图或动态图：**

![复现步骤的屏幕截图和动态 GIF 图](图片的 url)
[建议提供可运行的demo]

**Comment by kinder1995** [comment]
同问，求解~

**Comment by TimorCookie** [comment]
> 同问，求解~

我这边自己解决了 是引入的一个插件没有被转为es5语法
你可以检查看看是否有引入的第三方插件没有被babel解析
