### ISSUE TITLE
Cannot read property 'call' of undefined;at App onError function

### ISSUE THREAD

**Issue by ckken** [Meituan-Dianping/mpvue#118]
根路径 App.vue
```
 export default {
   created () {
 
   },
   onError (e) {
     console.error(e)
   }
}
```

![image](https://user-images.githubusercontent.com/3890513/37533930-48f921f6-297e-11e8-9847-760152573e14.png)

**Comment by anchengjian** [comment]
[1.0.6](https://github.com/Meituan-Dianping/mpvue/releases/tag/1.0.6) 已经修复，请升级 mpvue, mpvue-template-compiler, mpvue-loader

**Comment by ckken** [comment]
目前遇到了更加恐怖的问题，两个component 点击事件会互相触发！暂时再官网下
