### ISSUE TITLE
子组件数据无法更新

### ISSUE THREAD

**Issue by yz-xlame** [Meituan-Dianping/mpvue#1183]
props传入一个Boolean，我在tap事件触发后修改为!boolean却发现，下次触发还是最开始的值，请问这个是什么原因

**Comment by yz-xlame** [comment]
props初次传值好像只有string或者number(大概会转成strinig)会生效

**Comment by zxzhgk** [comment]
#140 或者直接 https://github.com/HelloZJW/mpvue-page-factory

**Comment by yz-xlame** [comment]
@zxzhgk 我几天前发现了，我可以使用v-bind来操作，这个可以做到（啊，想哭）

**Comment by Andyczc** [comment]
@yz-xlame 有参照的代码吗？我也遇到子组件props传值同步问题

**Comment by zhoufanglu** [comment]
父组件传值到子组件 传不到，请问楼主怎么解决的？  v-bind是什么鬼
