### ISSUE TITLE
npm run dev 后dist下面的页面文件里面生成了多余的文件，怎么配置？

### ISSUE THREAD

**Issue by fanfan1280** [Meituan-Dianping/mpvue#1189]
![_20181114181722](https://user-images.githubusercontent.com/25970278/48476263-8c559900-e839-11e8-887c-b66b743185d9.png)

**Comment by chenxi2008** [comment]
run dev只是生成测试代码，生成的文件不需要你人为操作，另外如果你要上线可以使用：
run build 这样应该不会有多余的代码

**Comment by F-loat** [comment]
*.vue.wxml 是存放实际页面代码的文件，*.map 是调试用的，可以在配置中关闭

**Comment by hucq** [comment]
`build/webpack.dev.conf.js` 目录，注释配置项：
```
devtool: '#source-map',
```
