### ISSUE TITLE
v-else 元素上绑定事件失效

### ISSUE THREAD

**Issue by GaryChangCN** [Meituan-Dianping/mpvue#119]
# v-else 元素上绑定事件失效

**问题复现步骤:**

1. <div @click="foo1" v-if="a">line 1<div/>
2. <div @click="foo2" v-else>line 2<div/>
3. [其他步骤...]

**期望的表现:**

foo2 正常使用

**观察到的表现:**

foo2 失效，查看编译后的代码发现没有 foo2

**Comment by anchengjian** [comment]
同 #18 请升级 mpvue, mpvue-template-compiler, mpvue-loader 这三个依赖
