### ISSUE TITLE
刚学习 mpvue，请教一下 使用文档的问题，没有看懂。

### ISSUE THREAD

**Issue by xiaomizhou66** [Meituan-Dianping/mpvue#1191]
文档中下面的内容没有看懂，

因为 小程序说明文中， app.js 的生命周期还有onError，onPageNotFound，还有 pages.js 的周期也还有其他的。

请教一下是因为文档没有更新，还是只能兼容小程序 的部分功能？

`
除了 Vue 本身的生命周期外，mpvue 还兼容了小程序生命周期，这部分生命周期钩子的来源于微信小程序的 Page， 除特殊情况外，不建议使用小程序的生命周期钩子。

app 部分：
onLaunch，初始化
onShow，当小程序启动，或从后台进入前台显示
onHide，当小程序从前台进入后台
page 部分：

onLoad，监听页面加载
onShow，监听页面显示
onReady，监听页面初次渲染完成
onHide，监听页面隐藏
onUnload，监听页面卸载
onPullDownRefresh，监听用户下拉动作
onReachBottom，页面上拉触底事件的处理函数
onShareAppMessage，用户点击右上角分享
onPageScroll，页面滚动
onTabItemTap, 当前是 tab 页时，点击 tab 时触发 （mpvue 0.0.16 支持）`

**Comment by xiaomizhou66** [comment]
还有 class 与 style 中的一句话不明白

文档：最佳实践见上文支持的语法，从性能考虑，建议不要过度依赖此。
请教下，这个此，指的是？


将分别被转换成:

<view class="_p" style=" {{'color:' + activeColor + ';' + 'font-size:' + fontSize + 'px' + ';'}}">666</view>
<view class="_p" style=" {{'color:' + activeColor + ';' + 'font-size:' + fontSize + 'px' + ';'}}">777</view>
不支持 官方文档：Class 与 Style 绑定 中的 classObject 和 styleObject 语法。

最佳实践见上文支持的语法，从性能考虑，建议不要过度依赖此。

此外还可以用 computed 方法生成 class 或者 style 字符串，插入到页面中，举例说明：

**Comment by zxzhgk** [comment]
1. 生命周期 就是融合了小程序和vue的什么周期，都可以用
2.还有 class 与 style 不支持直接绑定一个对象例如：
<div v-bind:style="styleObject"></div>
data: {
  styleObject: {
    color: 'red',
    fontSize: '13px'
  }
}
这样的不支持
