### ISSUE TITLE
用vant-weapp里的van-tabbar组件，change事件无效

### ISSUE THREAD

**Issue by teri5354** [Meituan-Dianping/mpvue#1193]
我已经成功引用了van-tabbar组件，mpvue的官方文档中提到bindchange="eventName" 事件，需要写成 @change="eventName"。使用如下
使用方案一
<van-tabbar :active="active" @change="onChange">
      <van-tabbar-item icon="shop">标签</van-tabbar-item>
      <van-tabbar-item icon="chat" dot>标签</van-tabbar-item>
      <van-tabbar-item icon="records" info="5">标签</van-tabbar-item>
      <van-tabbar-item icon="gold-coin" info="20">标签</van-tabbar-item>
    </van-tabbar>

使用方案二

<van-tabbar active="{{ active }}" bind:change="onChange">
  <van-tabbar-item icon="shop">标签</van-tabbar-item>
  <van-tabbar-item icon="chat" dot>标签</van-tabbar-item>
  <van-tabbar-item icon="records" info="5">标签</van-tabbar-item>
  <van-tabbar-item icon="gold-coin" info="20">标签</van-tabbar-item>
</van-tabbar>

调用的方法：
 onChange (event) {
     console.log('test')
 }

运行情况：
方案一：并没有调到onChange方法，控制台并没有打印出test
方案二：Component "pages/index/main" does not have a method "onChange" to handle event "change"

请问应该如何解决？？

**Comment by d0apga** [comment]
你有解决不触发change事件的问题吗

**Comment by teri5354** [comment]
@d0apga 我之前使用1.0.13版本是可以使用的，现在升级到1.1.0之后，所有子组件的事件全部失效，现在都不知道怎么解决，坑死了

**Comment by d0apga** [comment]
@teri5354 我现在使用1.0.18版本了，最新版本也没人来填坑

**Comment by snpstudios** [comment]
1.10.18 这个change还是坑，抹不平了吗？
