### ISSUE TITLE
使用vue init mpvue/mpvue-quickstart my-project  初始化项目却报找不到app.json

### ISSUE THREAD

**Issue by mickeyzhou** [Meituan-Dianping/mpvue#1194]
生成的dist目录下有一个wx子目录
是不是mpvue-loader有升级啊，能不能在文档里告知下新的使用说明,突然升级有点蒙

**Comment by liyangmsn** [comment]
#1162

**Comment by Yansuuu** [comment]
我这里也是，下载的最新版本，不仅 app.json 不会打包到 dist/wx ，
其他 page 的 .json 文件也不行
static 文件夹也不会打包到 dist/wx 文件夹中
最后是在 dist/wx 文件夹中手动添加 app.json
然后在 src 中放置静态文件夹
不过，只有 img 标签并写好 src 直接引入的图片会自动打包，根据模板动态生成的不行

**Comment by Wilson-yanwxyt** [comment]
我这里也有问题：1、两台电脑，在一台电脑上，用模板生成后，可以正常使用；另一台电脑却一直有问题，“未找到入口app.json...”。完全同样的步骤。 也参考了这里的文档，没有找到原因，已经重新处理了N遍。微信开发工具和node 都升级到最新版本了（其中node 安装过 LTS 和current两个最新版本）

**Comment by F-loat** [comment]
可以试下使用 [mpvue-config-loader](https://juejin.im/post/5bffd5de51882526a643fcd1)

**Comment by Wilson-yanwxyt** [comment]
问题解决了：
1、环境删除重建。 npm 卸载，全局安装的npm 和npm-chche 删除； 删除微信web开发工具。
2、全新安装。
3、成功。

**Comment by ShiningDan** [comment]
是的，因为马上会发布对于百度小程序的支持，所以 dist 目录下面分成了 wx/ 以及 swan/。如果无法接受 dist 目录被分配成两个子目录，可以选择锁定 mpvue-loader 的版本。

**Comment by jiaxiaon** [comment]
> 是的，因为马上会发布对于百度小程序的支持，所以 dist 目录下面分成了 wx/ 以及 swan/。如果无法接受 dist 目录被分配成两个子目录，可以选择锁定 mpvue-loader 的版本。

这个需要怎么配置呢？
