### ISSUE TITLE
请问mpvue如何引入腾讯视频插件

### ISSUE THREAD

**Issue by lian8306** [Meituan-Dianping/mpvue#1196]
## [问题简单描述]

**问题复现步骤：**

1. [第一步] 在app.json 文件中加入
"plugins":
    {
        "videoPlugin":
        {
            "version": "1.2.2",
            "provider": "wxa75efa648b60994b"
        }
    }
2. [第二步]在需要使用插件的文件夹内的main.js中加入

export default {
    config: {
        usingComponents: {
            "txv-video": "plugin://videoPlugin/video"
        }
    }
}
3. [其他步骤...]在对应的页面中调用
<txv-video vid="j0028bofno2" playerid="txv1" ></txv-video>
页面无任何效果

**期望的表现：**可以正常显示腾讯视频

[在这里描述期望的表现]

**观察到的表现：**
页面无任何变化，插件没有生效

[在这里描述观察到的表现]

**屏幕截图或动态图：**
 
![qq 20181115230016](https://user-images.githubusercontent.com/3616813/48561153-57753f00-e92a-11e8-8675-27f8d512d5c4.jpg)
![qq 20181115230021](https://user-images.githubusercontent.com/3616813/48561155-580dd580-e92a-11e8-983c-bdd77e12682c.jpg)
![qq 20181115230027](https://user-images.githubusercontent.com/3616813/48561156-580dd580-e92a-11e8-9bfa-3600c5ae15e4.jpg)

![复现步骤的屏幕截图和动态 GIF 图](图片的 url)
[建议提供可运行的demo]

**Comment by lian8306** [comment]
在引用的目录下创建main.json也试过，没有生效

**Comment by hucq** [comment]
> 这个博客有详细介绍
> https://blog.csdn.net/qq_39953537/article/details/81042969

感谢 @l-x-f

**Comment by fffx** [comment]
按照@hucq 给的博客链接, 我一一照做, 只是版版本改成了最新的`1.2.4`, 然后控制台报错:  `找不到playerid为txv1的txv-video组件 `,  然后我看了下该[插件的FAQ](https://github.com/tvfe/txv-miniprogram-plugin#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)  
我终于发现`dist/wx/pages/main.json ` 里面是一个json对象`{ }`, 于是我把它改成了

```
{
  "usingComponents": {
        "txv-video":  "plugin://videoPlugin/video"
    }
}
```


然后就可以了.
我的环境
```
"mpvue": "^1.0.11",
``
