### ISSUE TITLE
mpvue开发小程序打开页面空白

### ISSUE THREAD

**Issue by adwardWang** [Meituan-Dianping/mpvue#1198]
各位好，江湖救急，mpvue开发小程序上线的时候遇到一个问题，
1.在本机上跑的测试本好好的。
2.上传代码之后体验版页面加载不到任何数据了。
3.但是可以获取到用户头像。

**Comment by chenxi2008** [comment]
在接口请求的地方用console.log打印接口返回值，然后小程序右上角三个点打开调试模式，重新进入小程序看log的返回值；先要知道哪里的问题

**Comment by hucq** [comment]
看看接口是否有返回数据，域名是否被限制，应该可以定位问题。
