### ISSUE TITLE
如何支持类似于vue的transition属性, 还有何时能上健全的文档~

### ISSUE THREAD

**Issue by ChangerHe** [Meituan-Dianping/mpvue#12]

**Comment by aOrz** [comment]
因为 mpvue 使用了 vue 的 runtime，绝大多数的 vue 的 api 我们都支持，所以我们的文档仅列出了和 vue 不同的部分

**Comment by z704600202qj** [comment]
mpvue 可以是用路由吗？

**Comment by anchengjian** [comment]
@z704600202qj http://mpvue.com/qa/#vue-router
