### ISSUE TITLE
通过computed 绑定class的组件样式，无法生效， 不会打包到dist 里面

### ISSUE THREAD

**Issue by fanyongfeng** [Meituan-Dianping/mpvue#120]
<template>
  <div :style="profileStyle" :class="avatarClass">
    <image :src="url" mode="scaleToFill"  :style="profileStyle" />
  </div>
</template>
<script>

export default {
  props: {
    url: {
      type: String,
      default: ''
    },
    width: {
      type: Number,
      default: 38
    },
    className: {
      type: String,
      default: ''
    }
  },
  computed: {
    avatarClass() { return `${this.className} profile`},
    profileStyle() { return `height: ${this.width}px; width: ${this.width}px;`}
  }
}
</script>

<style>
  .profile {
    overflow: hidden;
    border-radius: 50%;
    display: inline-block;
  }
  .avatar {
    margin: 7px 7px 0;
  } 
</style>

**Comment by anchengjian** [comment]
1、你的 computed 中的 return 后面的语法有错误。
2、http://mpvue.com/mpvue/#class-style 文档说明不支持 classObject 和 styleObject 语法。

建议：
1、把表达式写在 template 中
2、computed 一个 computedClassStr 或者 computedStyleStr

**Comment by fanyongfeng** [comment]
我return 出来一个string，只是copy过来之后 string前后的 ` 符号不见了

**Comment by fanyongfeng** [comment]
而且如果我把组件里面的样式copy 出来写到page 本身vue 文件中，那么组件样式就生效了

**Comment by anchengjian** [comment]
明白了，你 copy 过来没写 markdown code 格式，被 github 的渲染给弄错乱了。

你尝试下升级到最新版本再试一下，参考 #91

**Comment by fanyongfeng** [comment]
已经是最新版了  还是不行

**Comment by Jackliu007888** [comment]
@fanyongfeng 官方文档说暂不支持在组件中使用 :class

**Comment by fanyongfeng** [comment]
@Jackliu007888 我是用的计算属性返回的class 字符串

**Comment by harrydengchao** [comment]
我也遇到同样的问题。
这个功能非常常用，https://github.com/Meituan-Dianping/mpvue/issues/470
