### ISSUE TITLE
真机预览调试时提示import and export may only appear at the top level

### ISSUE THREAD

**Issue by Alcantara6** [Meituan-Dianping/mpvue#1203]
## 使用开发者工具进行真机预览或调试不能编译

**问题复现步骤：**

在开发者工具能正常运行，不过控制台会有报错
 thirdScriptError 
 sdk uncaught third Error 
 Unexpected token export 
 SyntaxError: Unexpected token export

**屏幕截图或动态图：**
![image](https://user-images.githubusercontent.com/29516057/48656716-e9cd2e00-ea63-11e8-953b-a7301697426e.png)

![image](https://user-images.githubusercontent.com/29516057/48656724-023d4880-ea64-11e8-8347-fb04e7abcac4.png)

**Comment by hucq** [comment]
检查和修正一下语法错误，错处位置已经列出来了。

**Comment by AlllenShen** [comment]
ES6转ES5打开
![image](https://user-images.githubusercontent.com/16975592/58449071-87549900-813c-11e9-83d5-f080d2817a8e.png)
