### ISSUE TITLE
项目配置问题: 场景是两个tabbar页面， 同指向一个page页， 传入不同query

### ISSUE THREAD

**Issue by IceGogh** [Meituan-Dianping/mpvue#1205]
## [问题简单描述]
tabbar首页 无法传入query
1. 尝试在 app.json 中， 直接将 query 在写 pagePath 后面， 但是编译提示报错

 `    "list": [
      {
        "pagePath": "pages/sell/main?type=sell",
        "iconPath": "static/img/xiao1@2x.png",
        "query": "type=sell",
        "selectedIconPath": "static/img/xiao@2x.png",
        "text": "销"
      },
      {
        "pagePath": "pages/sell/main?type=in",
        "query": "type=sel2l",
        "iconPath": "static/img/cun1@2x.png",
        "selectedIconPath": "static/img/cun@2x.png",
        "text": "存"
      },`

**Comment by hucq** [comment]
在微信官方文档寻求解决方案吧，是在不行可以通过其它方式传递数据，譬如本次存储。
