### ISSUE TITLE
mpvue可以设置全局样式吗

### ISSUE THREAD

**Issue by yeyan1996** [Meituan-Dianping/mpvue#1206]
## [我想在App.vue中设置全局样式(*)但是似乎不起作用，是否是小程序限制了全局样式呢]

**屏幕截图或动态图：**

![_20181118195909](https://user-images.githubusercontent.com/39046570/48672087-6d724200-eb6c-11e8-896c-2000e40d4691.png)

**Comment by andyxmq** [comment]
在style 加上scoped就行了

**Comment by ShiningDan** [comment]
https://developers.weixin.qq.com/miniprogram/dev/framework/view/wxss.html

请参考目前支持的选择器。不支持 *
