### ISSUE TITLE
idea不能识别webpack别名

### ISSUE THREAD

**Issue by dengshenkk** [Meituan-Dianping/mpvue#1209]
## [问题简单描述]
idea不能识别@别名,idea已经设置了webpack的配置文件
**问题复现步骤：**

1. [第一步]
npm init mpvue/mpvue-quickstart myapp
2. [第二步]
idea 设置 搜索webpack 设置配置文件路径为myapp/build/webpack.base.conf.js
3. [其他步骤...]
idea版本 2018.2.4
**期望的表现：**
在页面中能方便引用,并且能够被idea识别,方便改名重构

[在这里描述期望的表现]
希望以下格式
```javascript
import componentA from '@/components/componentA '
```
**观察到的表现：**
而非这种
```javascript
import componentA from '../../components/componentA '
```
[在这里描述观察到的表现]

**屏幕截图或动态图：**

![复现步骤的屏幕截图和动态 GIF 图](图片的 url)
[建议提供可运行的demo]

**Comment by hucq** [comment]
不熟悉这款工具，辛苦另寻他法。

**Comment by JsonSong89** [comment]
idea的setting可以设置下webpack,这个应该跟mpvue无关吧
