### ISSUE TITLE
转H5

### ISSUE THREAD

**Issue by xiaoxue1234** [Meituan-Dianping/mpvue#1210]
我们有现成的小程序项目，想要转成h5怎样转呢

**Comment by F-loat** [comment]
可以参考下 https://github.com/F-loat/ithome-lite ，目前需要自己处理组件及 api 差异的

**Comment by hucq** [comment]
mpvue 暂不直接处理此类转换，因为无法提供和微信小程序一致的一套 api 能力。
只能手动迁移并修改小程序平台 api 差异部分。
