### ISSUE TITLE
自定义组件调用时组件 css中属性名中包含大写字符属性失效

### ISSUE THREAD

**Issue by panyu97py** [Meituan-Dianping/mpvue#1212]
## [问题简单描述]

在src components 目录下新增组件 并在page 目录下import
若组件css中包含大写字母 则该css属性失效

**问题复现步骤：**

1. [第一步]
2. [第二步]
3. [其他步骤...]

**期望的表现：**

[组件的css定义属性无大小写字母限制]

**观察到的表现：**

[组件使用大写css时 属性失效]

**屏幕截图或动态图：**

![复现步骤的屏幕截图和动态 GIF 图](图片的 url)
![menu saveimg savepath20181122140544](https://user-images.githubusercontent.com/38545728/48884581-1320fc00-ee60-11e8-82c9-b37da0648ace.jpg)
![menu saveimg savepath20181122140632](https://user-images.githubusercontent.com/38545728/48884582-1320fc00-ee60-11e8-8d7d-87032c16b73e.jpg)
![menu saveimg savepath20181122141005](https://user-images.githubusercontent.com/38545728/48884698-8dea1700-ee60-11e8-81ca-b1bc1ab3c8cb.jpg)
![menu saveimg savepath20181122140708](https://user-images.githubusercontent.com/38545728/48884708-98a4ac00-ee60-11e8-96bd-783c3b4b0a7b.jpg)
![menu saveimg savepath20181122140740](https://user-images.githubusercontent.com/38545728/48884713-9fcbba00-ee60-11e8-8fc4-a1081cde7010.jpg)

**Comment by Dewyzee** [comment]
![image](https://user-images.githubusercontent.com/4916726/51449929-6680cf00-1d69-11e9-8a9b-e8d986bb8c17.png)
我这边按照你描述的class中包含大写字母是可以的呢？

**Comment by panyu97py** [comment]
时间有点久了 也有点忘了 这个下次在出现类似问题我再提 issue
