### ISSUE TITLE
[Feature Request]适时将div编译到cover-view

### ISSUE THREAD

**Issue by Amorites** [Meituan-Dianping/mpvue#1215]
## 适时将div编译到cover-view

**新功能相关的问题issue或讨论：**

目前`div`,`img`会被编译成`view`,`image`。如果想让一个组件可以覆盖原生组件map、video、canvas、camera、live-player、live-pusher等，需要将所有`div`, `img`改成`cover-view`， `cover-image`，一方面工作量比较大，另一方面统一改成cover-xx可能会影响组件的复用。

**新功能的实现：**

想了几种可能的方式处理这种情况：

1. 将`cover-view`内部元素全部编译成cover-view/cover-image。这样只需要在组件外面包一层即可解决`cover-view`。
2. 给元素加一个只对mpvue有效的属性如`mp-cover=true`，将这个元素及其子元素编译成cover-view/cover-image。

**相关项目或文档：**

[小程序关于cover-view的文档](https://developers.weixin.qq.com/miniprogram/dev/component/cover-view.html)

**Comment by NineSu** [comment]
一年了  ~  杳无音讯

**Comment by Amorites** [comment]
目前微信支持了同层渲染，这个 issue 可以关掉了

**Comment by NineSu** [comment]
呃  同层渲染？？ 老哥文档链接给个
