### ISSUE TITLE
当引用vue2-toast后，点击按钮触发toast事件，程序报错

### ISSUE THREAD

**Issue by nijunjie** [Meituan-Dianping/mpvue#1216]
## [问题简单描述]
当引用vue2-toast后，点击按钮触发toast事件，程序报错
**问题复现步骤：**
1. 建立mpvue小程序项目
2. 引用vue2-toast 或 引用mint-ui 后，点击按钮触发 this.$toast.top('XXX')， 程序报错

**观察到的表现：**
这是src文件夹里的main.js
![image](https://user-images.githubusercontent.com/16549894/49058327-62e12980-f1b8-11e8-99d9-4cf1fb469fa0.png)

这是index 文件夹里的 index.vue
![image](https://user-images.githubusercontent.com/16549894/49058388-9fad2080-f1b8-11e8-9585-9d43386aced3.png)

这是index 文件夹里的 main.js
![image](https://user-images.githubusercontent.com/16549894/49058469-ffa3c700-f1b8-11e8-947a-4b268a2bb998.png)

这是test1 文件夹里的index.vue
![image](https://user-images.githubusercontent.com/16549894/49058520-2eba3880-f1b9-11e8-81a0-33a5c93d7b05.png)

这是test1 文件夹里的 main.js
![image](https://user-images.githubusercontent.com/16549894/49058422-ca977480-f1b8-11e8-8342-ccb5d8f1166a.png)

这是报错
![image](https://user-images.githubusercontent.com/16549894/49058309-52c94a00-f1b8-11e8-9a80-15e31c39345b.png)

报错为：
Please do not register multiple Pages in pages/test1/main.js

**Comment by hucq** [comment]
通过 vue cli 工具重新初始化一下项目，`mpvue-webpack-target` 和 `build/webpacl.base.config.js` 构建规则。
