### ISSUE TITLE
在src下创建的新目录不会编译到dist里面

### ISSUE THREAD

**Issue by dxwb** [Meituan-Dianping/mpvue#1217]
我想新建一个目录放小程序的tamplate，但是发现这个目录不会编译到dist里面

**Comment by GuoJieLun** [comment]
webpack.base.conf.js 里面可以配置打包哦，官方上面默认是src/pages/下面

**Comment by dxwb** [comment]
> webpack.base.conf.js里面可以配置打包哦，官方上面默认是src / pages /下面

可以具体点吗，菜鸟看不懂配置，百度也找不到方法

**Comment by hucq** [comment]
如果是用mpvue 开发的template, 引用路径正确就行。
如果是原生的template, 那就配置一个静态资源拷贝规则就行，参见` build/webpack.base.config.js`  中 static 目录的拷贝规则写法。
