### ISSUE TITLE
原有h5项目怎么转成mpvue小程序

### ISSUE THREAD

**Issue by cz848** [Meituan-Dianping/mpvue#122]
对原有h5项目来讲，想要转成mpvue小程序如何做？需要注意些什么？有没有合适的例子推荐？

**Comment by zjz894251se** [comment]
有的很难啊，哎，有些框架大量的dom操作,window方法,还有各种render，这种的就别折腾了。

**Comment by cz848** [comment]
我改一下：一份标准的vue+vuex+axios+vue-router的h5项目，转成mpvue小程序怎么转？因为官方文档没看到有相关例子，所以不知道从哪下手。

**Comment by lolPlatinumPlayer** [comment]
vue-router不支持哦

**Comment by zjz894251se** [comment]
vue-router基本功能还是可以通过自己写plugin解决的，复杂的话就另当别论了。

**Comment by wudan1874** [comment]
您好想问下 一个使用jquery写的原有项目， 想要用mpvue重写一下，可以像vue一样引入jquery吗 谢谢啦。

**Comment by zjz894251se** [comment]
@wudan1874 不行的，目前的话，死了这条心吧。

**Comment by wudan1874** [comment]
@zjz894251se 这个项目里面用到themeforest的模板，涉及很多模板里面的js文件，如果用小程序原生来写也基本是不可能的对吧？ 那这种情况的话 是不是只有用小程序原生或者mpvue来重新写 别无他法？谢谢您啦。

**Comment by zjz894251se** [comment]
@wudan1874 就用mpvue重写吧，最起码原来的样式还能用，用原生就苦逼了。

**Comment by wudan1874** [comment]
好的谢谢您 @zjz894251se

**Comment by F-loat** [comment]
使用 [flyio](https://github.com/wendux/fly/blob/master/README-CH.md) 可以替代 axios
使用 [mpvue-entry](https://github.com/F-loat/mpvue-entry) 可以复用之前的文件结构
使用 [mpvue-router-patch](https://github.com/F-loat/mpvue-router-patch) 可以部分复用 $router 及 $route 相关的代码
在 mpvue 中使用 vuex 与在 vue 中基本没有区别，无需改动
