### ISSUE TITLE
mpvue加载图片的时候会阻止其他渲染dom的操作吗？

### ISSUE THREAD

**Issue by VictorMemory** [Meituan-Dianping/mpvue#1223]
页面图片没有加载完成的时候继续请求数据，数据返回了但是没有渲染，图片加载完成后就可以渲染了

**Comment by ShiningDan** [comment]
应该不会，图片加载不属于 Vue 或者小程序生命周期中的事件，两者是不冲突的。怀疑是微信本身渲染能力的限制。
