### ISSUE TITLE
使用分包之后打包global变量的问题

### ISSUE THREAD

**Issue by jinggk** [Meituan-Dianping/mpvue#1229]
问题：
自定义在global上的全局变量 dev情况下是好的，build之后就提示找不到了
![image](https://user-images.githubusercontent.com/21035344/49213088-6f56c380-f3fe-11e8-83e1-135c742f49cb.png)
这个wxCommon是在main.js执行的时候定义在global上的，并且在eslintrc中定义成了全局的变量
![image](https://user-images.githubusercontent.com/21035344/49213152-91e8dc80-f3fe-11e8-89cc-2bb67c4c9570.png)
本地跑的时候没有问题，build之后就报错了，根据官方提供的分包文档做了对webpack的修改，build过程不会报错，没有任何问题

**Comment by Bravo123** [comment]
尝试在build之前将dist文件夹删除

**Comment by jinggk** [comment]
没用，找到问题了，是production环境下的webpack配置了UglifyJsPlugin,在分包的情况下会有问题。。

**Comment by JasonBoy** [comment]
workaround 还是 有没有完美的解决方案？
