### ISSUE TITLE
如何升级 mpvue 项目？

### ISSUE THREAD

**Issue by blade254353074** [Meituan-Dianping/mpvue#123]
```bash
npm update ?
```

```bash
npm update mpvue ?
```

不太懂这种封装的框架怎么升级

**Comment by anchengjian** [comment]
小版本升级直接更新依赖就好，大版本升级的话，才可能会对应构建的大幅更新。所以，目前只需要直接更新 npm 包就好了。
目前看起来本地升级最简单的方式是使用 [npm-check](https://github.com/dylang/npm-check)，把所有跟 mpvue 相关的包都升级一下。

有点需要注意的是：

mpvue 和 mpvue-template-compiler 必须同版本。

**Comment by blade254353074** [comment]
项目配置文件也会一起更新么？

**Comment by anchengjian** [comment]
小版本升级只需要升级包和 package.json ，webpack 相关的构建配置文件在大版本升级的时候才会有大幅更新，暂不考虑相关配置自动更新，在大版本升级的时候，建议按照自己 mpvue-qucikstart 的 pr 记录进行整理升级。

**Comment by blade254353074** [comment]
嗯 明白了，如果文档有更新方法的描述会更好

**Comment by anchengjian** [comment]
收到这个建议了，会考虑补充到文档。[quickstart-支持升级-mpvue-版本](https://trello.com/c/0BgW2F0g/35-quickstart-%E6%94%AF%E6%8C%81%E5%8D%87%E7%BA%A7-mpvue-%E7%89%88%E6%9C%AC)
