### ISSUE TITLE
<checkbox>原生组件中value无法绑定

### ISSUE THREAD

**Issue by anpoz** [Meituan-Dianping/mpvue#1235]
## [问题简单描述]
<checkbox>原生组件使用:value无法绑定正确的值

**问题复现步骤：**

1. 代码如下
![e2h zd1_atyqp 7r_y lz3](https://user-images.githubusercontent.com/2825342/49279992-e6a25b00-f4c3-11e8-97b7-1f453d4a112e.png)

2. 实际WXML
![qq 20181130171851](https://user-images.githubusercontent.com/2825342/49280040-0c2f6480-f4c4-11e8-8ab3-5844fb9cf78b.png)

**期望的表现：**

让value能正确绑定

**Comment by ShiningDan** [comment]
没有复现你的 bug，请提 mpvue，mpvue-loader 的版本号

**Comment by ShiningDan** [comment]
v-model 不是小程序组件的属性，所以 v-model 本身会被转义成 value 以及 bindchange/bindinput 两个属性。所以在使用 v-model 的时候不要同时使用 value 属性
