### ISSUE TITLE
请问：vue3.x的环境，如何构建mpvue项目？

### ISSUE THREAD

**Issue by skyflyscroll** [Meituan-Dianping/mpvue#1239]
issueConfigs:
  -
    bannedTitle: "系统vue版本是3.0.5，创建方式和2.X不同。如何构建mpvue项目呢？"

**Comment by skyflyscroll** [comment]
环境中有的项目已经是基于vue3.x创建的了～因为不想降低版本，才想问有没有基于高版本的vue创建项目。

**Comment by F-loat** [comment]
两个版本的指令可以共存的，[文档](https://cli.vuejs.org/zh/guide/creating-a-project.html#%E6%8B%89%E5%8F%96-2-x-%E6%A8%A1%E6%9D%BF-%E6%97%A7%E7%89%88%E6%9C%AC)

**Comment by hucq** [comment]
参见 @F-loat 的回复。
