### ISSUE TITLE
生成包体积比原生大的问题

### ISSUE THREAD

**Issue by cmideal** [Meituan-Dianping/mpvue#124]
# [问题简单描述]
在开发中发现,很大的体积是由于增加了引入vue解析引起的
可以看到解析后的还是div解析绑定关系，
` t._v(" "), a("div", {
          staticClass: "counter",
          attrs: {
            eventid: "3"
          },
          on: {
            tap: function(e) {
              t.navTo("/pages/counter/counter")
            }
          }
        }`
同时引入自己写的js文件，会直接打包在一个文件中，比如我20个文件引用进来，一个js块10kb ,
通过这种方式那么至少要占用200kb的空间。
这种方式是否可以引入dll方式或者其它？

**问题复现步骤:**
直接打包然后看dist/static/js 下面对应的文件即可，
1. [第一步]
2. [第二步]
3. [其他步骤...]

**期望的表现:**
减少重复没必要的代码
[在这里描述期望的表现]

**观察到的表现:**

[在这里描述观察到的表现]

**屏幕截图和动态 GIF 图**

![复现步骤的屏幕截图和动态 GIF 图](图片的 url)

**Comment by anchengjian** [comment]
引入了一个框架，肯定会有代码膨胀（冗余）的问题，在小程序限制包大小的情况下，会格外的明显。

同时你的发现很敏锐，包大小优化是我们最近一段时间正在做的事情，你举例的这段打包代码是我们所需要的 vDom （虚拟DOM）相关的代码，它保证了事件和复杂事件表达式的正确执行。

然后关于重复 JS 的问题，建议在  https://github.com/mpvue/mpvue-quickstart/blob/master/template/build/webpack.prod.conf.js#L76-L86 这个位置尝试进行打封装，我们之前做的是所有被用到两次以上的包都会被编译进 vendor ，后来因为 vendor.wxss 没有很好的处理，而暂时恢复了相关逻辑 https://github.com/mpvue/mpvue-quickstart/pull/7/files 后期会持续进行包大小优化。

**Comment by cmideal** [comment]
> 同时你的发现很敏锐，包大小优化是我们最近一段时间正在做的事情，你举例的这段打包代码是我们所需要的 vDom （虚拟DOM）相关的代码，它保证了事件和复杂事件表达式的正确执行

我发现这块会增加至少50%以上的代码体积，如果结构复杂的话，这块可能更甚，
`staticClass: "recommendShop-shop-info-btn expose-log",
    attrs: {
      "data-acm": "3.mce.1_8_1172ut32.70195.0.aptzWqMBf6QDm.m_10609161-asn_14155148-pos_1",
      "data-href": "/pages/shop/home/index?shopId=1172ut32",
      "data-log-index": "1",
      "data-log-mod": "10009_40",
      "data-ptp-c": "mod_class_recommendShop",
      "data-ptp-d": "1"
    }`
这样一段简单的代码，把所有的属性都增加上去，是否可以根据小程序修改一定的虚拟参数，保证级别，否则如果页面布局复杂，那么这个体积将很复杂
因为页面中有一定的结构了，是否可以拿来即用
以上是我的个人简洁，未对虚拟dom进行深入研究的一些针对特定的小程序的一些思考，如有不对希望指正。

**Comment by anchengjian** [comment]
已经考虑到了，会优化掉冗余代码。
