### ISSUE TITLE
enablePullDownRefresh无法回弹

### ISSUE THREAD

**Issue by teri5354** [Meituan-Dianping/mpvue#1244]
我在main.js里，使用enablePullDownRefresh:true，问题有下面两个
1、背景色是处理好的，在小程序模拟器可以看到...的样式，但是到真机上面看不到
2、小程序模拟器可以正常回弹（速度有点慢），但是到真机上面看不到回弹效果
请问应该如何处理？

**Comment by hucq** [comment]
从你描述的信息无法看出问题，建议排查一下其它情况，或者提供可以复现的 代码。

**Comment by coldhurt** [comment]
回弹调用wx.stopPullDownRefresh()
