### ISSUE TITLE
改变vue中data里的list数据，但页面里的列表不刷新

### ISSUE THREAD

**Issue by mickeyzhou** [Meituan-Dianping/mpvue#1246]
有人遇到过这种问题吗，现在网上找到的解决方案是：
1.  先将list设置为null
2. ajax获取到远程的数据后，再用获取的数据设置list

我想知道这个是我代码写的不正确，还是mpvue本身就有这个数据更新，但页面不同步刷新的bug。
虽然现在解决了，但是觉得有点hack，想知道有没有更好的解决方案。

我知道wepy框架是，data更新后，要调用this.$apply()，强制更新数据,mpvue有这样的api吗

**Comment by kailcc** [comment]
从你描述的信息无法看出问题，建议参考一些例子，或者提供可以复现的 代码。

**Comment by anZong** [comment]
数组直接赋值是可以的
`this.list=res.data`
但是如果赋值前后数组长度一样就有问题了，我的是给`v-for` 增加`key`
`<div v-for="(item,index) in list" :key="index">{{item}}</div>`
key最好用index，我的key用`item.id`，就出现了更新不及时的问题，第二次请求接口的时候才会刷新上次的数据

**Comment by hucq** [comment]
上述两个描述中的问题都未能复现，建议提供mpvue 版本号，示例代码。

**Comment by javascripet** [comment]
> 上述两个描述中的问题都未能复现，建议提供mpvue 版本号，示例代码。

我也出现了数组push进去值, 界面不更新, 琢磨了很久发现跟小程序调试基础库版本有关, 1.9.93及以下没问题, 以上就不行了界面不更新

**Comment by javascripet** [comment]
> 上述两个描述中的问题都未能复现，建议提供mpvue 版本号，示例代码。

mpvue 1.0.13

**Comment by anchel** [comment]
我也遇到这个问题了

**Comment by yunhappy** [comment]
"mpvue": "^1.0.18" 同样问题，
我是这么解决的，

1. 先赋值给临时变量，再赋值回来，

2.改变任意一个非list变量

**Comment by xingqiwu55555** [comment]
很遗憾，这里没有解决方案，我也遇到了这个问题，我贴一下代码：

我的场景是：搜索，第一次搜关键词，返回数组长度为1的列表；第二次搜不同关键词，也是返回数组长度为1的列表；长度相同，但是列表结果不同，页面还是显示第一次的结果(闪现了下第一次的结果)，我必须再点击一次搜索按钮，它才返回第二次的结果；

```
<list-item
    v-for="item in list"
    :key="item.id"
    :item="item"
    @delete="deleteItem"
/>
```

**Comment by guoPengSong** [comment]
> 从你描述的信息无法看出问题，建议参考一些例子，或者提供可以复现的 代码。
亲测可用，mpvue太坑了，困扰了我好几个小时

**Comment by guoPengSong** [comment]
> 数组直接赋值是可以的
> `this.list=res.data`
> 但是如果赋值前后数组长度一样就有问题了，我的是给`v-for` 增加`key`
> `<div v-for="(item,index) in list" :key="index">{{item}}</div>`
> key最好用index，我的key用`item.id`，就出现了更新不及时的问题，第二次请求接口的时候才会刷新上次的数据
谢谢，把key改成index能解决我的问题，mpvue太坑了，困扰了我好几个小时

**Comment by guoPengSong** [comment]
> 数组直接赋值是可以的
> `this.list=res.data`
> 但是如果赋值前后数组长度一样就有问题了，我的是给`v-for` 增加`key`
> `<div v-for="(item,index) in list" :key="index">{{item}}</div>`
> key最好用index，我的key用`item.id`，就出现了更新不及时的问题，第二次请求接口的时候才会刷新上次的数据

谢谢，把key改成index能解决我的问题，mpvue太坑了，困扰了我好几个小时
