### ISSUE TITLE
 mpvue-template-compiler问题

### ISSUE THREAD

**Issue by shuangmuyingzi** [Meituan-Dianping/mpvue#1250]
## mpvue-template-compiler模块安装不上的问题，在node_modules里面没有

Vue packages version mismatch:

- vue@1.0.13
- mpvue-template-compiler@1.0.16
实际我的vue版本都3.1.1了

**Comment by Geniusning** [comment]
同上，也出现这个问题

**Comment by Mis-zhang** [comment]
各种BUG，能不能修复测试好了再上线！体验及其不好！

**Comment by Mis-zhang** [comment]
文档也能不能更新一下，按照文档走一遍，然后各种模块找不到，各种引用出错！

**Comment by hucq** [comment]
`mpvue` `mpvue-template-compiler` 需要保持版本号一致，实际安装的版本号不一致会提示出错。
如果没有修改配置中的版本号，重新安装会自动升级到最新版本，目前会自动升级到 1.0.18，文档稍后会更新。

目前 mpvue 的命令行工具还是依赖 2.x 的

@Mis-zhang 可以把你的问题列一下，或者直接在群里at我

**Comment by Mis-zhang** [comment]
您好，为什么不能热更新了，就是以前一直都可以，突然一下子就不能热更新了，修改点代码就得从新打包一次，而且第一次进入某个页面会丢失样式，第二次进入就好了，这是什么原因啊，别这样搞事啊，明天就要上线项目了！如果不从新打包会报错（thirdScriptError 
 sdk uncaught third Error 
 Cannot read property 'call' of undefined 
 TypeError: Cannot read property 'call' of undefined）这个错误！急..........

**Comment by yudaming** [comment]
mpvue-template-compiler 没有2.0以上的版本那 你2.0 又引入了 怎么搞？
 "mpvue-template-compiler": "^2.0.0"
