### ISSUE TITLE
初始化项目后，启动报错，eslint（airbnb）不通过

### ISSUE THREAD

**Issue by youzipi** [Meituan-Dianping/mpvue#1251]
## 初始化项目后，启动报错，eslint（airbnb）不通过

**问题复现步骤：**

安装官网文档 初始化项目后，启动报错。
eslint 选的是 airbnb based。
**期望的表现：**

[在这里描述期望的表现]

**观察到的表现：**

[在这里描述观察到的表现]

**屏幕截图或动态图：**

![image](https://user-images.githubusercontent.com/5629307/49772998-44d40700-fd2a-11e8-9376-82094293ca13.png)

**Comment by hucq** [comment]
可以在 `.eslintrc.js` 中设置规则，其它代码规则根据需要调整即可。
```
'import/no-unresolved': [
      2,
      { caseSensitive: false }
   ],
'import/extensions': ['error', 'always', {
      'js': 'never',
      'vue': 'never',
      'json': 'never'
    }],
```

**Comment by youzipi** [comment]
> 可以在 `.eslintrc.js` 中设置规则，其它代码规则根据需要调整即可。
> 
> ```
> 'import/extensions': ['error', 'always', {
>   'js': 'never',
>   'vue': 'never',
>   'json': 'never'
> }],
> 'import/no-unresolved': [2, {
>   'caseSensitive': false
> }],
> ```

照着修改了，还是报错：
![image](https://user-images.githubusercontent.com/5629307/49781921-6abfd280-fd4f-11e8-8faf-9d721cac0d20.png)
之前 也报了 `Definition not found` 的错误，之前的截图里忘了给出了。

我把这两个配置都 设置 `off` 后，可以正常运行，也没有报 not found 的错。
>
node: 10.11.0
eslint: 4.19.1
