### ISSUE TITLE
clearInterval清除定时器无效果 清除器id输出Timeout{_id:'}

### ISSUE THREAD

**Issue by itweblin** [Meituan-Dianping/mpvue#1252]
## [问题简单描述]

**问题复现步骤：**

1. [第一步]
2. [第二步]
3. [其他步骤...]

**期望的表现：**

[在这里描述期望的表现]

**观察到的表现：**

[在这里描述观察到的表现]

**屏幕截图或动态图：**

![复现步骤的屏幕截图和动态 GIF 图](图片的 url)
[建议提供可运行的demo]

**Comment by itweblin** [comment]
编译时 文件自动引入import { clearInterval } from 'timers' 导致报错，把import { clearInterval } from 'timers'注释掉后clearInterval正常

**Comment by hucq** [comment]
@itweblin 看起来是你的 timers 写法不对，仔细检查代码和出错信息。看不出和框架的关系。

**Comment by hucq** [comment]
1. `timers.js` 中是怎么写的，看起来问题出在这个文件中
2. clearInterval 是重写的么，是要实现与内置的 clearInterval 不一样的功能么？
