### ISSUE TITLE
请问下为什么m p vu e不直接用vue的生命周期，而是将小程序的生命周期带进来，生命周期保持一致不是更好吗

### ISSUE THREAD

**Issue by front-end-developer-candy** [Meituan-Dianping/mpvue#1256]
## [在此简单描述您的建议]

**新功能相关的问题issue或讨论：**

[在这里引用新功能相关的讨论]

**新功能的实现：**

[在这里填写或简单描述功能的实现方式或需求的解决方式]

**相关项目或文档：**

[在这里引用相关项目或文档地址]

**Comment by hucq** [comment]
@front-end-developer-candy  是很好的建议，目前的实现方案不是最优。
好与不好分场景，如果仅就小程序开发而言，使用小程序生命周期是更好的时机控制。
如果考虑和H5公用方案，那vue 生命周期可能更佳。

#### 解释一下为什么：
> 在小程序内运行，则所有的时机控制最终都依赖于小程序本身生命周期，所有框架最后都会hook到小程序的生命周期上。

1. 就vue 和小程序来说，两者的生命周期定义有明显差异，目前不能做到较好的对齐。
2. 就 mpvue 的设计来看，我们对 vue 对象生命周期的维护与小程序本身（app, page，component）的生命周期不一致。
