### ISSUE TITLE
事实证明，mpvue 再次跑路。

### ISSUE THREAD

**Issue by AibiTi** [Meituan-Dianping/mpvue#1269]
## 事实证明，mpvue 再次跑路

**问题复现步骤：**

1. mpvue 几个月都没有更新，期间微信小程序更新了 N 次。 
2. 一堆新的 bug 和 旧的 bug 没有解决。期间微信小程序 API 更新，导致更多新的 BUG 出现。
3. 维护者不活跃。
4. 无法适配其他小程序方案，例如百度小程序，头条小程序。
5. Issues 无人问答，仅合并一些 PR，上几个月更新尽然是 update README.md。

**期望的表现：**

mpvue 一天更新 10 次。

**观察到的表现：**

mpvue 几个月都没有更新，期间微信小程序更新了 N 次。

**消极的表现：**

卸载 《美团 App》等美团系列应用。

**屏幕截图或动态图：**

![timg](https://user-images.githubusercontent.com/40224479/50078342-aa8c2b80-0221-11e9-878b-a53d361dbf7c.jpg)

**Comment by joenil** [comment]
什么叫再次跑路，就从来没回来过好吗

**Comment by zxzhgk** [comment]
官方最近挺活跃的呀，之前数据更新的那个大BUG也修复了

**Comment by hucq** [comment]
@AibiTi 心态如此失衡，是哪里出了什么问题，可以单独讨论一下。
我最近的支持频率已经有较大改善，不知道你是选择性看不见还是不会看。
意见和批评我都是接受的，摆事实讲道理，明显乱说不好。
你的其它帖子也充满了敌意和劣气，不是好的心态！！

**Comment by DreamPWJ** [comment]
![image](https://user-images.githubusercontent.com/16730031/50211787-709f5e80-03b4-11e9-8ab5-a73db7217a59.png)
附上图片 基本上github更新都是超过半多月一次甚至好几个月  如果mpvue问题很少 一年更新一次都没人说  可是问题那么多 这个频率实在不解

**Comment by hucq** [comment]
@DreamPWJ 感谢你的提醒，我继续改进。

**Comment by yz-xlame** [comment]
一天更新10次？这特么比一晚七次都厉害了把
