### ISSUE TITLE
checkbox无法绑定变量?

### ISSUE THREAD

**Issue by hudongyang** [Meituan-Dianping/mpvue#127]
想做个TODOS练练手,  checkbox无法绑定变量

html:
`<input type="checkbox" v-model="checked">`

js:
`data: function() {
            return {
                todos: [],
                checked: false
            }
        }`

开发者工具中的变量没啥反应??
![image](https://user-images.githubusercontent.com/1802377/37574445-ddeb6240-2b5b-11e8-8f85-5709ad822093.png)

刚测试了下radio也无法绑定

**Comment by anchengjian** [comment]
建议还是直接用原生微信小程序组件吧，同 #66

**Comment by hudongyang** [comment]
谢谢
