### ISSUE TITLE
wxs功能现在可以支持吗？

### ISSUE THREAD

**Issue by missyii** [Meituan-Dianping/mpvue#1270]
## [在此简单描述您的建议]

**新功能相关的问题issue或讨论：**wxs现在支持吗？如果需要定制化渲染怎么办，不能用函数，computed也不能传参数

[在这里引用新功能相关的讨论]

**新功能的实现：**

[在这里填写或简单描述功能的实现方式或需求的解决方式]

**相关项目或文档：**

[在这里引用相关项目或文档地址]

**Comment by missyii** [comment]
不知道大家是怎么解决的

**Comment by AibiTi** [comment]
这项目，估计要凉了。

**Comment by hucq** [comment]
@missyii wxs 现阶段不支持。
我建议可以在vue中进行该部分功能的定制，可能习惯了wxs 会觉得比较趁手。但直接通过数据来控制应该也没问题, mvvm 的能力可以达成的。

具体实现方式可以贴出代码，我们具体讨论实现方式。
