### ISSUE TITLE
请问如何获得转发人的信息？

### ISSUE THREAD

**Issue by eacdy** [Meituan-Dianping/mpvue#1272]
## 请问如何获得转发人的信息？

**问题复现步骤：**

1. 我的代码如下：
```javascript
onShareAppMessage() {
    return {
      title: '111',
      desc: 'aaaaa',
      path: 'pages/share/list/main',
      imageUrl: '/static/img/ccc.png',
      success: (res) => {
        console.log('分享成功');
      }
    };
  }
```

**期望的表现：**

转发后，console打印“分享成功”，然后用wx.getShareInfo，获得当前转发人的信息。

**观察到的表现：**

可以正常转发，但是console不会打印……所以我想问下，如何才能用wx.getShareInfo获得当前转发人的信息呢？

**Comment by hucq** [comment]
@eacdy api 上并没有标明可以接受成功或者失败的回调，是以不执行 console 语句[你可查阅微信小程序文档](https://developers.weixin.qq.com/miniprogram/dev/framework/app-service/page.html?search-key=onShareAppMessage#onshareappmessageobject)

getShareInfo 返回的数据内容也请直接参考官方接口文档。

**Comment by eacdy** [comment]
@hucq 不好意思，这里有说明，我是个新手，参考项目比较老。。。
onShareAppMessage现在已经不支持回调了：<https://developers.weixin.qq.com/community/develop/doc/0000447a5b431807af57249a551408?page=4#comment-list>
