### ISSUE TITLE
npm run dev时候报错，未找到app.json

### ISSUE THREAD

**Issue by jiaxiaon** [Meituan-Dianping/mpvue#1273]
我已经配置好，miniprogramRoot也是"dist/wx/"，但是dev还是报错，在线等

**Comment by AibiTi** [comment]
@jiaxiaon 不用等了，#1269

**Comment by hucq** [comment]
@jiaxiaon app.json 没生成，需要在源代码中单独配置app.json，在几个版本之前是自动提取生成app.json的，后来为了支持分包功能，将app.json交由开发者自动定义。

如果不清楚如何生成，可以重新初始化一个示例项目并拷贝出 app.json

**Comment by dwqs** [comment]
@hucq 需要单独配置 app.json 是从哪个版本开始的？在 release 和change log 中都没有找到声明

**Comment by MarcWong** [comment]
需要降级mpvue-loader，我这边测试1.0.13、1.0.14都可以
