### ISSUE TITLE
for...in...遍历Object会遍历到__keyPath

### ISSUE THREAD

**Issue by JasonMgz0411** [Meituan-Dianping/mpvue#1276]
## [for...in...遍历Object会遍历到__keyPath]

**问题复现步骤：**

1. [第一步]
state数据：
 `data: {
       testData: 1
 }`
mutations操作
`[SET_TEST_DATA](state) {
        state.data.testData = 2;
}`
2. [第二步]
打印日志：
`onShow() {
        this.setTestData();
        console.log(this.data);
}`
日志中vuex修改后的data存在一个可枚举的属性
`__keyPath: {testData: true}`
但是如果业务需要遍历以上的data时会遍历到此属性   影响渲染

**期望的表现：**
期望__keyPath不可枚举

**Comment by zybieku** [comment]
@JasonMgz0411  同样遇到了,莫名其妙添加了_keypath,加hasOwnProperty也不行

**Comment by JasonMgz0411** [comment]
@zybieku 对应的对象的`__keyPath`设置为不可枚举就好了
`Object.defineProperty(resolveData, "__keyPath", {
       enumerable: false
});`

**Comment by zybieku** [comment]
@JasonMgz0411 每个对象都手动这样做?

**Comment by zybieku** [comment]
@JasonMgz0411 好吧.谢谢老哥.

**Comment by hucq** [comment]
已经发布，请更新 
```
yarn add mpvue@1.0.19 mpvue-template-compiler@1.0.19
```
