### ISSUE TITLE
自定义组件使用render方法渲染，控制台提示模板未找到

### ISSUE THREAD

**Issue by joenil** [Meituan-Dianping/mpvue#1277]
## [问题简单描述]
自定义组件使用render方法渲染，控制台提示模板未找到

**问题复现步骤：**
![image](https://user-images.githubusercontent.com/11400674/50262104-6b8cee80-044a-11e9-855b-8e947dea6e42.png)

**期望的表现：**
正常渲染

**观察到的表现：**
因为模板没有找到，什么也没渲染出来

**屏幕截图或动态图：**
![image](https://user-images.githubusercontent.com/11400674/50262165-bb6bb580-044a-11e9-9c3d-e9d8abe5cca0.png)

**Comment by F-loat** [comment]
需要预编译，不支持 render 函数的
