### ISSUE TITLE
windows下mpvue-simple build报错

### ISSUE THREAD

**Issue by aoxls** [Meituan-Dianping/mpvue#128]
报错信息如下：
Command failed: curl `npm config get registry`mpvue-simple -s

**Comment by anchengjian** [comment]
请升级 [mpvue-simple@1.0.6](https://github.com/mpvue/mpvue-simple/pull/4), 解决了这个问题。

**Comment by aoxls** [comment]
还有个问题请教下，我在用mpvue-simple进行构建的时候，会报一串这样的错误，是什么原因呢？
![image](https://user-images.githubusercontent.com/4845651/37762657-eb3b4b92-2df7-11e8-8951-987505240395.png)
