### ISSUE TITLE
全局main.js的config配置和当前页面的main.js的config无法配置到小程序

### ISSUE THREAD

**Issue by AK47-dadada** [Meituan-Dianping/mpvue#1285]
入坑mpvue不久，但是发现了如题这个问题，有点不太理解这个问题，为什么前置的版本可以，迭代之后的就不行呢？手动配置main.json真的好吗？或者是不是因为我使用不当导致的呢？可以给个解决方案吗？

**Comment by feelslive** [comment]
入坑试了不行，还是手写main.json文件吧

**Comment by AK47-dadada** [comment]
> 入坑试了不行，还是手写main.json文件吧

那main.js这个文件似乎有点鸡肋了啊，虽然我知道它是做什么的，但是似乎除了生成文件别的一无是处啊

**Comment by sideFlower** [comment]
以前的版本是可以在main.js中设置的，后面main.json出来了

**Comment by AK47-dadada** [comment]
> 以前的版本是可以在main.js中设置的，后面main.json出来了

感觉有点违背初衷吧，代码也没得到妥善管理，感觉真的很不三不四

**Comment by hucq** [comment]
建议按照新的实例项目模板初始化吧
```
vue init mpvue/mpvue-quickstart my-project
```

将window配置独立出来已经有较长时间了，在初始化项目的时候应该能看见示例也是在 .json 文件中的。
将配置放到 main.js 其实并不是什么好方案，所以我们调整了。
