### ISSUE TITLE
注册表单页面input的v-model双向绑定部分手机主要是ios手机输入不了中文 一输入就自动清空 英文可以输入 限制的长度是30

### ISSUE THREAD

**Issue by tomatosqq** [Meituan-Dianping/mpvue#1288]
## [问题简单描述]

**问题复现步骤：**

1. 注册表单页面input的v-model双向绑定部分手机主要是ios手机输入不了中文 一输入就自动清空 英文可以输入 限制的长度是30
2. 改成英文输入法就能输入英文

![image](https://user-images.githubusercontent.com/7625212/50390612-22071100-0774-11e9-8fc4-79cc48af28f3.png)

**Comment by liuhonga324** [comment]
同遇到这个问题，版本1.0.11

**Comment by tomatosqq** [comment]
@liuhonga324 谢谢🙏
