### ISSUE TITLE
事件冒泡 @click.stop问题

### ISSUE THREAD

**Issue by KennyWho** [Meituan-Dianping/mpvue#129]
mpvue版本1.0.5
子元素的绑定的click.stop指定依然会触发父元素的事件，冒泡事件无法取消。请问如何使用小程序的catch时间？或者click.stop是否良好支持。

**Comment by anchengjian** [comment]
注意看文档 http://mpvue.com/mpvue/#_12 中的踩坑注意：

> .stop 的使用会阻止冒泡，但是同时绑定了一个非冒泡事件，会导致该元素上的 catchEventName 失效！

**Comment by KennyWho** [comment]
@anchengjian OK 明白了 自定义事件也是非冒泡

**Comment by mcu13321** [comment]
那该如何避免呢

**Comment by haryzxw** [comment]
刚也遇到这个问题，同问如何在mpvue中使用catch事件！阻止事件冒泡？ 请问现在有好的实现方法了吗

**Comment by lessthanno** [comment]
bad:

```
<div @click.stop="">
   <div @click=""></div>
</div> 
```

good:
```
<div @click.stop="">
 <div @click.stop=""></div>
</div>
```

**Comment by cdll** [comment]
not working with wxml structure like: 
````vue
/* page.vue */
<template>
  <nav-bar >
    <block slot='page'>
      <button @tap='log'>click me</button>
    </block>
  </nav-bar>
</template>

<script>
  export default{
    methods: {
      log(){
        console.info(`parent event~`)
      }
    }
  }
</script>
/* component.vue */
<template>
  <div >
    <button @click.stop='dude'>dude</button>
    <slot name='page'></slot>
  </div>
</template>

<script>
  export default{
    methods: {
      dude(){
        console.info(`child event~`)
      }
    }
  }
</script>
````
any good idea to work around?

**Comment by cdll** [comment]
> not working with components structure like:
> 
> ```
> /* page.vue */
> <template>
>   <div class='root'>
>     <nav-bar >
>       <block slot='page'>
>         <button @tap='log'>click me</button>
>       </block>
>     </nav-bar>
>   </div>
> </template>
> 
> <script>
>   export default{
>     methods: {
>       log(){
>         console.info(`parent event~`)
>       }
>     }
>   }
> </script>
> 
> /* component.vue */
> <template>
>   <div >
>     <button @click.stop='dude'>dude</button>
>     <slot name='page'></slot>
>   </div>
> </template>
> 
> <script>
>   export default{
>     methods: {
>       dude(){
>         console.info(`child event~`)
>       }
>     }
>   }
> </script>
> ```
> 
> any good idea to work around?

well, worked around with @touchend in ``component.vue``~
