### ISSUE TITLE
小程序基本都是中国在做吧，为啥文档 中英文结合；目录是英文的。看着好难受。我感觉要么做个纯中文，要么提供中英文两个版本。

### ISSUE THREAD

**Issue by fengxtao** [Meituan-Dianping/mpvue#1290]
## [在此简单描述您的建议]

**新功能相关的问题issue或讨论：**

[在这里引用新功能相关的讨论]

**新功能的实现：**

[在这里填写或简单描述功能的实现方式或需求的解决方式]

**相关项目或文档：**

[在这里引用相关项目或文档地址]

**Comment by fengxtao** [comment]
文档目录可不可以不要英文的。   中英文结合 好难受，哪儿那么多外国人看小程序。

**Comment by MoeMoeFish** [comment]
有文档就不错了，要啥自行车🚲

**Comment by hucq** [comment]
@fengxtao  我会考虑进行适当调整。
