### ISSUE TITLE
mpvue  radio 怎么修改默认的 radio 大小

### ISSUE THREAD

**Issue by jnpd** [Meituan-Dianping/mpvue#1297]
## [问题简单描述]

**问题复现步骤：**
 checkBox 根本找不到 在哪里设置的样式
1. [第一步]
2. [第二步]
3. [其他步骤...]

**期望的表现：**
能修改checkbox 的样式
[在这里描述期望的表现]

**观察到的表现：**

[在这里描述观察到的表现]

**屏幕截图或动态图：**

![复现步骤的屏幕截图和动态 GIF 图](图片的 url)
[建议提供可运行的demo]

**Comment by hucq** [comment]
可以修改的，对于标签转换的场景，如果你想写标签选择器，需要用转换前的标签名称。或者把你的代码贴出来看一下。

```
<template>
<checkbox :value="value" :checked="checked"/>
</template>

<style>
checkbox{
    background-color:blue;
}
</style>
```
