### ISSUE TITLE
引用小程序自定义组件如何接收小程序自定义组件抛出的事件？

### ISSUE THREAD

**Issue by kagari2613** [Meituan-Dianping/mpvue#1299]
一个小程序自定义组件（不是vue组件）内部用triggerevevt('事件名'）把事件抛到了父级，父级组件如何接收这个事件呢？

**Comment by yeyi361936738** [comment]
请问你是怎么解决这个问题的呢

**Comment by kagari2613** [comment]
是我代码写错了，triggerEvent抛出的事件正常接受可以

YEYI <notifications@github.com> 于 2019年1月17日周四 19:35写道：

**Comment by xchz** [comment]
@kagari2613 大佬 看一下你是怎么接收的

**Comment by yeyi361936738** [comment]
triggerEvent可以被vue的事件接受？我试了不可以的。我把组件用vue重新写了一遍

kagari <notifications@github.com> 于2019年1月21日周一 下午11:24写道：

**Comment by xchz** [comment]
@kagari2613 @yeyi361936738 我debug了一下
triggerEvent确实会触发vue事件
triggerEvent调用之后会进入handleProxyWithVue 
```
function handleProxyWithVue (e) {
  var rootVueVM = this.$root;
  var type = e.type;
  var target = e.target; if ( target === void 0 ) target = {};
  var currentTarget = e.currentTarget;
  var ref = currentTarget || target;
  var dataset = ref.dataset; if ( dataset === void 0 ) dataset = {};
  var comkey = dataset.comkey; if ( comkey === void 0 ) comkey = '';
  var eventid = dataset.eventid;
  var vm = getVM(rootVueVM, comkey.split(','));
```
当小程序原生子组件在ready里调用triggerEvent时，如果vue组件mounted还没有被调用，那么`getVM(rootVueVM, comkey.split(','));`得到值是null，则父组件绑定的事件就触发不了

**Comment by kagari2613** [comment]
试试nextTick

chris <notifications@github.com> 于 2019年1月31日周四 13:34写道：
