### ISSUE TITLE
entry配置入口'xx/xx'形式，嵌套结构错乱

### ISSUE THREAD

**Issue by mcu13321** [Meituan-Dianping/mpvue#130]
# [问题简单描述]

**问题复现步骤:**
配置如下：
```
entry: {
        app: path.resolve('./src/main.js'),
        course: path.resolve('./src/pages/course/main.js'),
        'course/detail': path.resolve('./src/pages/course/detail/main.js')
},
```

**期望的表现:**

配置项course/detail按照文档中所示生成

```
── course
│   │   ├── course.js
│   │   ├── course.wxml
│   │   ├── course.wxss
│   │   └── detail
│   │           ├── detail.js
│   │           ├── detail.wxml
│   │           └── detail.wxss
```

**观察到的表现:**

生成的结构为
```
── course
│   │   ├── course.js
│   │   ├── course.wxml
│   │   ├── course.wxss
│   │   └── detail
│   │       └── course
│   │           ├── detail.js
│   │           ├── detail.wxml
│   │           └── detail.wxss
```
如上图结构，多了一层course

**Comment by h5-zzh** [comment]
现在确实不支持多层嵌套
参考webpack.base.conf.js,如果想要支持自己试试修改下这个配置。
function resolve (dir) {
  return path.join(__dirname, '..', dir)
}

function getEntry (dir, entryFile) {
  const files = fs.readdirSync(dir)
  return files.reduce((res, k) => {
    const page = path.resolve(dir, k, entryFile)
    if (fs.existsSync(page)) {
      res[k] = page
    }
    return res
  }, {})
}

const appEntry = { app: resolve('./src/main.js') }
const pagesEntry = getEntry(resolve('./src/pages'), 'main.js')
const entry = Object.assign({}, appEntry, pagesEntry)

**Comment by anchengjian** [comment]
无法复现

![image](https://user-images.githubusercontent.com/8679331/37586093-3b586862-2b96-11e8-88f2-0a565ff2c28a.png)

只能建议升级 mpvue、mpvue-template-compile、mpvue-loader 到最新版本

**Comment by mcu13321** [comment]
@anchengjian 谢谢回答，升级之后恢复原状

**Comment by h5-zzh** [comment]
关于循环嵌套的配置，可以动态遍历entry
```
function resolve (dir) {
  return path.join(__dirname, '..', dir)
}
let arr =[]

function readDirSync(path){    
  var pa = fs.readdirSync(path)
  pa.forEach(function(ele,index){  
      var info = fs.statSync(path+"/"+ele)      
      if(info.isDirectory()){  
          readDirSync(path+"/"+ele);  
      }else{  
        let num =  path.indexOf('pages/')+6
        arr.push(path.slice(num)) 
      }     
  })  
}  

function getEntry (dir, entryFile) { 
  readDirSync(dir)
  const files = arr
  console.log(files)
  return files.reduce((res, k) => {
    const page = path.resolve(dir, k, entryFile)
    if (fs.existsSync(page)) {
      res[k] = page
    }
    return res
  }, {})
}

const appEntry = { app: resolve('./src/main.js') }
const pagesEntry = getEntry(resolve('./src/pages'), 'main.js')
const entry = Object.assign({}, appEntry, pagesEntry)
```

**Comment by anchengjian** [comment]
@mcu13321 恢复原状是达到预期了？

**Comment by mcu13321** [comment]
@anchengjian 并没有到达预期，预期是和打包前的层级结构一致，也就是子目录也有一级目录，升级之后只是没有如上图那样循环嵌套了。

**Comment by ZionStark** [comment]
@anchengjian 关于目录嵌套的问题，目前有更好的解决吗？

**Comment by anchengjian** [comment]
请使用最新的 `vue init mpvue/mpvue-quickstart my-project` 试一下，已默认对嵌套路径做了支持
