### ISSUE TITLE
我们之前有微信版本使用mpvue开发,现在需要迁移一版百度小程序,使用百度提供的迁移工具转换以后,出现错误:

### ISSUE THREAD

**Issue by jiaqiyun** [Meituan-Dianping/mpvue#1300]
issueConfigs:
  -
    bannedTitle: "问题简单描述"
    subtitles:
      - "问题复现步骤："
      - "期望的表现："
      - "观察到的表现："
INFO : "child terminated"

INFO : "compile start..."

INFO : "[ 2018-12-29 23:15:26 ]: 自定义组件: static/iview/formData/formData.swan 编译通过"

INFO : "[ 2018-12-29 23:15:34 ]: Page页面: pages/index/index.swan 编译通过"

ERROR : "[ 2018-12-29 23:15:36 ]: C:/phpStudy/PHPTutorial/WWW/zq/test/app.js\nModule not found: Error: Can't resolve 'common/manifest.js' in 'C:\\phpStudy\\PHPTutorial\\WWW\\zq\\test'\nresolve 'common/manifest.js' in 'C:\\phpStudy\\PHPTutorial\\WWW\\zq\\test'\n Parsed request is a module\n No description file found\n resolve as module\n C:\\phpStudy\\PHPTutorial\\WWW\\zq\\test\\node_modules doesn't exist or is not a directory\n C:\\phpStudy\\PHPTutorial\\WWW\\zq\\node_modules doesn't exist or is not a directory\n C:\\phpStudy\\PHPTutorial\\WWW\\node_modules doesn't exist or is not a directory\n C:\\phpStudy\\PHPTutorial\\node_modules doesn't exist or is not a directory\n C:\\phpStudy\\node_modules doesn't exist or is not a directory\n C:\\node_modules doesn't exist or is not a directory\n[C:\\phpStudy\\PHPTutorial\\WWW\\zq\\test\\package.json]\n[C:\\phpStudy\\PHPTutorial\\WWW\\zq\\test\\node_modules]\n[C:\\phpStudy\\PHPTutorial\\WWW\\zq\\node_modules]\n[C:\\phpStudy\\PHPTutorial\\WWW\\node_modules]\n[C:\\phpStudy\\PHPTutorial\\node_modules]\n[C:\\phpStudy\\node_modules]\n[C:\\node_modules]\n @ C:/phpStudy/PHPTutorial/WWW/zq/test/app.js 4:0-29\n @ C:/Users/ADMINI~1/AppData/Local/Temp/.temp_swan_compilation/154609652229320497/app.js,C:/phpStudy/PHPTutorial/WWW/zq/test/app.js\nModule not found: Error: Can't resolve 'common/vendor.js' in 'C:\\phpStudy\\PHPTutorial\\WWW\\zq\\test'\nresolve 'common/vendor.js' in 'C:\\phpStudy\\PHPTutorial\\WWW\\zq\\test'\n Parsed request is a module\n No description file found\n resolve as module\n C:\\phpStudy\\PHPTutorial\\WWW\\zq\\test\\node_modules doesn't exist or is not a directory\n C:\\phpStudy\\PHPTutorial\\WWW\\zq\\node_modules doesn't exist or is not a directory\n C:\\phpStudy\\PHPTutorial\\WWW\\node_modules doesn't exist or is not a directory\n C:\\phpStudy\\PHPTutorial\\node_modules doesn't exist or is not a directory\n C:\\phpStudy\\node_modules doesn't exist or is not a directory\n C:\\node_modules doesn't exist or is not a directory\n[C:\\phpStudy\\PHPTutorial\\WWW\\zq\\test\\package.json]\n[C:\\phpStudy\\PHPTutorial\\WWW\\zq\\test\\node_modules]\n[C:\\phpStudy\\PHPTutorial\\WWW\\zq\\node_modules]\n[C:\\phpStudy\\PHPTutorial\\WWW\\node_modules]\n[C:\\phpStudy\\PHPTutorial\\node_modules]\n[C:\\phpStudy\\node_modules]\n[C:\\node_modules]\n @ C:/phpStudy/PHPTutorial/WWW/zq/test/app.js 5:0-27\n @ C:/Users/ADMINI~1/AppData/Local/Temp/.temp_swan_compilation/154609652229320497/app.js"

ERROR : "[ 2018-12-29 23:15:36 ]: Error: user code Syntax Error"
      - "屏幕截图或动态图："
    bannedContents:
      - "第一步"
      - "第二步"
      - "其他步骤..."
      - "在这里描述期望的表现"
      - "在这里描述观察到的表现"
      - "复现步骤的屏幕截图和动态 GIF 图"
      - "图片的 url",
      - "建议提供可运行的demo"
  -
    bannedTitle: "在此简单描述您的建议"
    subtitles:
      - "新功能相关的问题issue或讨论："
      - "新功能的实现："
      - "相关项目或文档："
    bannedContents:
      - "在这里引用新功能相关的讨论"
      - "在这里填写或简单描述功能的实现方式或需求的解决方式"
      - "在这里引用相关项目或文档地址"

comments:
  closeIssue: "issue不符合格式要求，请确保格式正确且填写所有有效信息。\n请保留issue模板中的各级小标题（如“期望的表现：”），并使用有效信息替换模板默认内容（如“[在这里描述期望的表现]”）"

**Comment by hucq** [comment]
@jiaqiyun mpvue 支持百度小程序转换，参考： https://github.com/Meituan-Dianping/mpvue/issues/1155
