### ISSUE TITLE
给对象添加属性，数据结构会多出一个_keyPath

### ISSUE THREAD

**Issue by 1paopao** [Meituan-Dianping/mpvue#1312]
## [问题简单描述]

**问题复现步骤：**

1. [第一步]
2. [第二步]
3. [其他步骤...]

**期望的表现：**
只希望可以添加该有的属性，不需要_keyPath,否则入参到接口 会报错~~  求解，谢谢
[在这里描述期望的表现]

**观察到的表现：**

[在这里描述观察到的表现]

**屏幕截图或动态图：**
出现的情况：
![image](https://user-images.githubusercontent.com/21901968/50681630-320dd300-1047-11e9-995c-8a55424aa4ad.png)
![image](https://user-images.githubusercontent.com/21901968/50681661-46ea6680-1047-11e9-881d-a8dd8effb717.png)

![复现步骤的屏幕截图和动态 GIF 图](图片的 url)
[建议提供可运行的demo]
<template>
	<div class="box">
		test
	</div>
</template>

<script>
export default {

  name: 'test',

  data () {
    return {
    	obj: {}
    }
  },
  created() {
  	console.log('添加属性')
  	this.$set(this.obj, 'name', 'paopao')
  	console.log('obj=====', this.obj)
  }
}
</script>

<style lang="css" scoped>
</style>

**Comment by zybieku** [comment]
手动判断吧，暂时大家都是这样
if(params.__keyPath){
    Object.defineProperty(params, "__keyPath", { enumerable: false });
  }
