### ISSUE TITLE
mpvue中_keyPath怎么设置不可枚举

### ISSUE THREAD

**Issue by 1paopao** [Meituan-Dianping/mpvue#1313]
## [问题简单描述]

**问题复现步骤：**

1. [第一步]
2. [第二步]
3. [其他步骤...]

**期望的表现：**

[在这里描述期望的表现]

**观察到的表现：**

[在这里描述观察到的表现]

**屏幕截图或动态图：**

![复现步骤的屏幕截图和动态 GIF 图](图片的 url)
[建议提供可运行的demo]

**Comment by AK47-dadada** [comment]
你好，我也遇到过同样的问题，但是后来我用delete操作符简单粗暴的干掉了它，因为影响到了展示数据，当然就你的问题而言，可以使用Object.defineProperty(obj, property, setter);来处理，我是根据原生js帮你回答的这个问题 希望对你有所帮助

**Comment by zybieku** [comment]
上面老哥说的极是，我也是暂时这样处理 
if(obj.__keyPath){
    Object.defineProperty(obj, "__keyPath", { enumerable: false });
  }

**Comment by bacy** [comment]
> 上面老哥说的极是，我也是暂时这样处理
> if(obj.__keyPath){
> Object.defineProperty(obj, "__keyPath", { enumerable: false });
> }

每个obj都要这么来一下吗？

**Comment by hucq** [comment]
新版本已经修复了。
