### ISSUE TITLE
编译后的app.json没有permission字段

### ISSUE THREAD

**Issue by conan51551** [Meituan-Dianping/mpvue#1314]
小程序更新了用户定位必须在app.json中加permission字段，而在main.js中写入该字段却没有在编译的app.json中
在main.js中加入=>
permission:{
    scope_userLocation:{
      desc:"你的位置信息将用于小程序位置接口的效果展示"
    }
  }
在生成的dist文件中的app.json中没有

**Comment by LUOQING1994** [comment]
按照微信官方给出的实例 我们只需要在app.json中加入以下字段即可
![image](https://user-images.githubusercontent.com/20340633/50745420-049e7080-1265-11e9-8fa0-00198f093206.png)

**Comment by syhsghr1993** [comment]
升级最近的版本，原先定义的main.js里面的小程序需要的字段，不放在main.js里了，都会放在各自的.json文件中，编译的时候拷贝过去。不记得哪个版本里这样修改的，升级需要注意下
![image](https://user-images.githubusercontent.com/11493449/50807405-3ed74300-1335-11e9-9bbb-ec165932060a.png)
