### ISSUE TITLE
无法将数据渲染到dom上

### ISSUE THREAD

**Issue by BigYangBrother** [Meituan-Dianping/mpvue#1320]
我在一个page中的data里面定义一个空对象，在created里面赋值，在dom中渲染不出来

**问题复现步骤：**

1. data中定义变量
2. created中赋值
3. dom中渲染

**期望的表现：**

渲染出来数据

**观察到的表现：**

未渲染出数据

**屏幕截图或动态图：**

![复现步骤的屏幕截图和动态 GIF 图](图片的 url)
[建议提供可运行的demo]

**Comment by BigYangBrother** [comment]
不知道是不是版本问题

**Comment by spencer1994** [comment]
@BigYangBrother 请问一下是什么问题导致的呢？

**Comment by monomichael** [comment]
@spencer1994 在 `created` 这个时机，DOM 还没有准备好，设置数据不渲染是预期表现
