### ISSUE TITLE
cover-image无法显示图片

### ISSUE THREAD

**Issue by tzc123** [Meituan-Dianping/mpvue#1322]
## [问题简单描述]

**问题复现步骤：**

1. [第一步]
创建一个map标签，并创建cover-image标签
```
<map>
   <cover-image src="../../images/location.png"></cover-image>
</map>
```
**期望的表现：**
图片正常显示并且覆盖在地图上

**观察到的表现：**
图片未被编译打包到小程序的目录下

猜测可能是只会根据img的src属性寻找图片打包，而不会对cover-image做处理

**Comment by Dewyzee** [comment]
> ## [问题简单描述]
> **问题复现步骤：**
> 
> 1. [第一步]
>    创建一个map标签，并创建cover-image标签
> 
> ```
> <map>
>    <cover-image src="../../images/location.png"></cover-image>
> </map>
> ```
> **期望的表现：**
> 图片正常显示并且覆盖在地图上
> 
> **观察到的表现：**
> 图片未被编译打包到小程序的目录下
> 
> 猜测可能是只会根据img的src属性寻找图片打包，而不会对cover-image做处理

目前如涉及到使用本地图片资源，建议统一放在static目录下。static在打包构建过程中会拷贝到生产目录下

**Comment by tzc123** [comment]
了解

**Comment by Bravo123** [comment]
但是分包中的cover-image引用本地资源如何解决呢
不可能所有分包的图片资源都放在static目录中吧？？
