### ISSUE TITLE
mpvue新项目 npm run dev报错

### ISSUE THREAD

**Issue by Ixiaodai** [Meituan-Dianping/mpvue#1324]
## [问题简单描述]

**问题复现步骤：**
进入新项目目录后, 执行npm run dev, 报错
查询了一些方法, 更改config/index.js内的端口号依然报错,
出师未捷身先死, 求帮忙~~

<img width="1343" alt="wx20190109-195356 2x" src="https://user-images.githubusercontent.com/8499708/50898161-4425b200-1449-11e9-8883-3eeaf310b17d.png">

**环境：**
- mac book pro
- node v8.9.0
- npm v5.5.1

**Comment by Dewyzee** [comment]
`sudo vi /etc/hosts`
加上
`127.0.0.1 localhost`
或者
`::1  localhost`
试试

**Comment by Ixiaodai** [comment]
> `sudo vi /etc/hosts`
> 加上
> `127.0.0.1 localhost`
> 或者
> `::1 localhost`
> 试试

兄弟, localhost也要配个hosts的原因是啥呢
