### ISSUE TITLE
用最新的mpvue-quickstart初始化的项目，DevTools failed to parse SourceMa

### ISSUE THREAD

**Issue by syhsghr1993** [Meituan-Dianping/mpvue#1325]
## 用最新的mpvue-quickstart初始化的项目，增加typescript支持后,断点没有指向原先的ts文件，并出现DevTools failed to parse SourceMap的警告

**问题复现步骤：**

1. vue init mpvue/mpvue-quickstart my-project
2. 增加typescript支持
![image](https://user-images.githubusercontent.com/11493449/50940615-9bb13580-14bc-11e9-9c74-471dab18dc50.png)
此处根据官方示例配置。省略后面部分配置内容。。。
3. 在app.vue或者xxx.ts文件中写一些最简单的代码

**期望的表现：**

断点可以关联到ts文件

**观察到的表现：**

1.failed to parse SourceMap报警 2.debug是编译后的文件

**屏幕截图或动态图：**

![image](https://user-images.githubusercontent.com/11493449/50941085-6d345a00-14be-11e9-8aba-b1ab86ca918c.png)
![image](https://user-images.githubusercontent.com/11493449/50941127-981eae00-14be-11e9-9a1e-1d7f52890f87.png)

根据之前的有人提过的退回webpack-mpvue-asset-plugin版本 到0.1.1，map文件格式是对了，但是断点的位置会乱跳，部分无法点击断点
![image](https://user-images.githubusercontent.com/11493449/50941160-b84e6d00-14be-11e9-80f8-d2632315f6ae.png)

断点异常动图：
![debuggif](https://user-images.githubusercontent.com/11493449/50941999-ff8a2d00-14c1-11e9-95ad-3e2734d1cb52.gif)

当前版本
![image](https://user-images.githubusercontent.com/11493449/50942294-1d0bc680-14c3-11e9-92fe-685697b83d25.png)

**Comment by conan51551** [comment]
把`webpack-mpvue-asset-plugin`保持在0.1.1版本就不会有DevTools failed to parse SourceMap警告
