### ISSUE TITLE
v-if判断某个值之后，我的点击事件失效了

### ISSUE THREAD

**Issue by AK47-dadada** [Meituan-Dianping/mpvue#1327]
你好，今天做项目遇到一个问题，就是用v-if判断某个值之后，我的点击事件失效了，请问有什么解决办法吗？

描述：
某页面带某参数跳转到列表页 该列表页获取该参数之后进行赋值，然后v-if执行到元素上面，神奇的问题发生了，该元素的点击事件完全无效，希望给出确切的回答，谢谢

**Comment by Dewyzee** [comment]
> 你好，今天做项目遇到一个问题，就是用v-if判断某个值之后，我的点击事件失效了，请问有什么解决办法吗？
> 
> 描述：
> 某页面带某参数跳转到列表页 该列表页获取该参数之后进行赋值，然后v-if执行到元素上面，神奇的问题发生了，该元素的点击事件完全无效，希望给出确切的回答，谢谢

@AK47-dadada 可以贴下你实现的源码看下吗

**Comment by AK47-dadada** [comment]
> > 你好，今天做项目遇到一个问题，就是用v-if判断某个值之后，我的点击事件失效了，请问有什么解决办法吗？
> > 描述：
> > 某页面带某参数跳转到列表页 该列表页获取该参数之后进行赋值，然后v-if执行到元素上面，神奇的问题发生了，该元素的点击事件完全无效，希望给出确切的回答，谢谢
> 
> @AK47-dadada 可以贴下你实现的源码看下吗

我都用v-show去实现了，没必要了吧，你看看我的流程自己演示一遍也行啊。
顺便问一下，这里v-show的 div.classname 是原生vue定义的 还是mpvue定义的？[图片]，差点没被坑死
