### ISSUE TITLE
远程调试和预览时图片没有显示出来

### ISSUE THREAD

**Issue by Cai-Wencong** [Meituan-Dianping/mpvue#133]
电脑上调试图片有正常出来，不过用手机调试时发现图片没有显示出来，根据其他人的说法是dist文件夹编译的时候图片路径没有进行更改，本来src文件夹下的页面图片引用是'../../../static/images/xx.png'，编译到dist里时路径是没有改的，编译到dist时正确的路径应该是'../../static/images/xx.png'，我把dist里的路径改了确实能显示了，不过这样改很麻烦，希望这个bug能尽早解决

**Comment by aOrz** [comment]
可用在源码里面写编译后应该引用的路径

**Comment by F-loat** [comment]
应该使用 /static/images/xx.png 这种形式

**Comment by towry** [comment]
有可能和小程序有关。我们是直接上传到CDN上用绝对地址的。

**Comment by aOrz** [comment]
问题同 #152 ，我先关了重复的问题
