### ISSUE TITLE
数据拿到了，却报错，然而却渲染出来了 不知道什么原因 求大佬帮忙

### ISSUE THREAD

**Issue by loveapple-pan** [Meituan-Dianping/mpvue#1330]
## 下面上代码
![image](https://user-images.githubusercontent.com/26113253/51095597-e00c4080-17f0-11e9-9bb0-794050cc84a3.png)

![image](https://user-images.githubusercontent.com/26113253/51095606-ee5a5c80-17f0-11e9-83ef-b4a0d1848f52.png)

求大佬帮忙

**Comment by dengliqiang** [comment]
在页面渲染时，data里面的topic.title字段不存在
`
<p v-if='topic.title'>{{ topic.title }}<p>
`
或者
`
data: {
  return {
    topic: {
      title: '' ,
   }
  }
}
`

**Comment by dengliqiang** [comment]
在页面渲染时，data里面的topic.title字段不存在
`<p v-if='topic.title'>{{ topic.title }}</p>`
或者
`
data: {
	return {
		topic: {
			title: '',
		}
	}
}
`

**Comment by dengliqiang** [comment]
在页面渲染时，data里面的currentDetail.title字段不存在
<p v-if='currentDetail.title'>{{ currentDetail.title }}</p>
或者
data: { return { currentDetail: { title: '', } } }

**Comment by dengliqiang** [comment]
在页面渲染的时候，currentDetail的title字段不存在
解决办法：
`<p v-if='currentDetail.title'>{{ currentDetail.title }}</p>`
或者
`data: {
	return {
		currentDetail: {
			title: '',
		}
	}
}`

**Comment by loveapple-pan** [comment]
> 在页面渲染的时候，currentDetail的title字段不存在
> 解决办法：
> `<p v-if='currentDetail.title'>{{ currentDetail.title }}</p>`
> 或者
> `data: { return { currentDetail: { title: '', } } }`

谢谢 解决了
