### ISSUE TITLE
微信开发者工具预览的时候报错，提示代码包过大，要怎么解决呢

### ISSUE THREAD

**Issue by qin-ziqi** [Meituan-Dianping/mpvue#1331]
## [问题简单描述]
开发过程中想在手机上预览效果，点击微信开发者工具中的预览时，会出现代码包过大的问题，请问要如何配置呢？

**屏幕截图或动态图：**
![image](https://user-images.githubusercontent.com/20514829/51107754-b96afb80-182a-11e9-9a67-f6788a21f863.png)

**Comment by qin-ziqi** [comment]
编译的时候如何配置忽略掉node_module文件

**Comment by Dylan-WY** [comment]
小程序本省就只支持2M的大小，你看看你包内的无用组件，无用图片，全部删除掉，超过100kb的静态资源放到OSS上通过连接引入，再试试吧。

**Comment by hucq** [comment]
先尝试分包方案，依然不行那就只有精简或者重构代码。
