### ISSUE TITLE
@scroll不生效

### ISSUE THREAD

**Issue by bobodegithub** [Meituan-Dianping/mpvue#1335]
就一个简单的事件，@scroll，为何不生效！

**Comment by bobodegithub** [comment]
<scroll-view @scroll="aaa">
      <p>asdsadsadsadsa</p>
      <p>asdsadsadsadsa</p>
      <p>asdsadsadsadsa</p>
      <p>asdsadsadsadsa</p>
      <p>asdsadsadsadsa</p>
      <p>asdsadsadsadsa</p>
      <p>asdsadsadsadsa</p>
      <p>asdsadsadsadsa</p>
      <p>asdsadsadsadsa</p>
      <p>asdsadsadsadsa</p>
      <p>asdsadsadsadsa</p>
      <p>asdsadsadsadsa</p>
      <p>asdsadsadsadsa</p>
      <p>asdsadsadsadsa</p>
      <p>asdsadsadsadsa</p>
      <p>asdsadsadsadsa</p>
      <p>asdsadsadsadsa</p>
      <p>asdsadsadsadsa</p>
      <p>asdsadsadsadsa</p>
      <p>asdsadsadsadsa</p>
      <p>asdsadsadsadsa</p>
      <p>asdsadsadsadsa</p>
      <p>asdsadsadsadsa</p>
      <p>asdsadsadsadsa</p>
      <p>asdsadsadsadsa</p>
      <p>asdsadsadsadsa</p>
    </scroll-view>

**Comment by Dylan-WY** [comment]
![image](https://user-images.githubusercontent.com/23611348/51300468-f1f71900-1a66-11e9-8f8a-5bd475459da6.png)

![image](https://user-images.githubusercontent.com/23611348/51300490-0804d980-1a67-11e9-8072-f281bce50eb1.png)


![image](https://user-images.githubusercontent.com/23611348/51300478-fae7ea80-1a66-11e9-8923-7db5e94f6bc4.png)

是生效的啊，你注意看下你的scroll方法是否写在了methods内。。。这种问题
