### ISSUE TITLE
Page is not constructed because it is not found

### ISSUE THREAD

**Issue by 15521054523** [Meituan-Dianping/mpvue#1336]
## [问题简单描述]

**问题复现步骤：**

1. [第一步]
mpvue编译报错，怎么改都报错
2. [第二步]
3. [其他步骤...]

**期望的表现：**

[在这里描述期望的表现]

**观察到的表现：**

[在这里描述观察到的表现]

**屏幕截图或动态图：**
![image](https://user-images.githubusercontent.com/19297519/51254028-07266600-19db-11e9-9a2c-aa9a0e6e5187.png)

![复现步骤的屏幕截图和动态 GIF 图](图片的 url)
[建议提供可运行的demo]

**Comment by Dylan-WY** [comment]
你npm run build 然后在npm start试试

**Comment by hucq** [comment]
给一个可以复现问题的代码 @15521054523

**Comment by Nanve** [comment]
你好，这个问题你解决了吗，我现在也出现了

**Comment by Nanve** [comment]
我把dist文件删除，重新yarn run dev可以了

**Comment by wjcuij** [comment]
谢谢，搞了我一天，差点想用原生写了

**Comment by wjcuij** [comment]
@hucq https://github.com/wjcuij/demo/blob/master/img/WechatIMG44799.png
好像是文件建多了就会，还有我从配置到出现这个问题没npm run build过，以至于dist的文件夹里连以前删掉的文件都还存在。

**Comment by Nanve** [comment]
每一次新建页面就需要重新编译了




| |
18106919127
邮箱：18106919127@163.com
|

Signature is customized by Netease Mail Master

On 01/26/2019 21:42, HuangCJ wrote:

@hucqhttps://github.com/wjcuij/demo/blob/master/img/WechatIMG44799.png
好像是文件建多了就会，还有我从配置到出现这个问题没npm run build过，以至于dist的文件夹里连以前删掉的文件都还存在。

**Comment by 15521054523** [comment]
npm run build 然后在npm start
亲测有效

**Comment by hucq** [comment]
> @hucq https://github.com/wjcuij/demo/blob/master/img/WechatIMG44799.png
> 好像是文件建多了就会，还有我从配置到出现这个问题没npm run build过，以至于dist的文件夹里连以前删掉的文件都还存在。

文件名写错了。

**Comment by susan007** [comment]
@9yues npm run build 后确实可以看到页面了
