### ISSUE TITLE
建议可以做一下各个小程序平台的适配。

### ISSUE THREAD

**Issue by mofiggHasSugar** [Meituan-Dianping/mpvue#1338]
现在小程序平台较多，咱们mpvue是不是可以参照一下taro，不仅可以适配微信小程序，还可以适配支付宝小程序，百度智能小程序，字节跳动小程序呢？

**Comment by hucq** [comment]
百度已经支持，年前会发布头条和支付宝的方案，请关注。

**Comment by mofiggHasSugar** [comment]
好的，多谢。
