### ISSUE TITLE
mpvue是支持nextTick的对吧

### ISSUE THREAD

**Issue by sideFlower** [Meituan-Dianping/mpvue#1341]
如题

**Comment by F-loat** [comment]
小程序中 nextTick 无法保证渲染已完成，mpvue 里大概只能延时重试这样

**Comment by hucq** [comment]
可以使用，使用上可以当做setTimeout 这样的延迟函数调用，无法保证界面渲染同步。mpvue 在小程序中的渲染还隔着一层。
