### ISSUE TITLE
旧项目改造分包后  原static里面的图片资源应该放到哪个目录底下

### ISSUE THREAD

**Issue by ljq353** [Meituan-Dianping/mpvue#1343]
旧项目改造后 原static貌似不进行打包 问下 应该修改什么配置 还是说放到指定的目录下

**Comment by Dewyzee** [comment]
根目录下的static会在打包的时候拷贝到dist目录下，至于分包目录需要在build目录下webpack.base.conf.js中添加入口文件

**Comment by Dewyzee** [comment]
原static里面的图片资源还是放在根目录下的static下面就可以

**Comment by ljq353** [comment]
> 原static里面的图片资源还是放在根目录下的static下面就可以

是在webpack.base.conf.js中 需要添加配置吗 现在项目不会打包static 需要打包完 人工在把static粘过去

**Comment by Dewyzee** [comment]
> > 原static里面的图片资源还是放在根目录下的static下面就可以
> 
> 是在webpack.base.conf.js中 需要添加配置吗 现在项目不会打包static 需要打包完 人工在把static粘过去

static目录与src目录同级，都在根目录下哈。静态资源放在这里就行
