### ISSUE TITLE
 安卓 Android @getphonenumber="getPhoneNumber" 无法触发回调  

### ISSUE THREAD

**Issue by SimmonHou** [Meituan-Dianping/mpvue#1346]
## [问题简单描述]
Android @getphonenumber="getPhoneNumber" 无法触发回调函数
**问题复现步骤：**
  <button  class="login-btn" open-type="getPhoneNumber" @getphonenumber="getPhoneNumber"></button>
  getPhoneNumbers(e) {
      console.log('------',e);
}
1. [第一步]
2. [第二步]
3. [其他步骤...]

**期望的表现：**

[在这里描述期望的表现]

**观察到的表现：**

[在这里描述观察到的表现]

**屏幕截图或动态图：**

![复现步骤的屏幕截图和动态 GIF 图](图片的 url)
[建议提供可运行的demo]

**Comment by SimmonHou** [comment]
在iOS上表现正常

**Comment by Dewyzee** [comment]
@SimmonHou https://developers.weixin.qq.com/community/develop/doc/000aa0ab584ae0557ae79a1a956400?highLine=getPhoneNumber%2520%25E5%259B%259E%25E8%25B0%2583
可能是微信版本升级导致，建议换一个低版本的试试看？如果是版本问题可能需要等官方解决

**Comment by SimmonHou** [comment]
已解决,表象是不放在组件内使用就可以,具体是什么原因待解
