### ISSUE TITLE
更新到最新的版本后，自定义组件绑定事件失效

### ISSUE THREAD

**Issue by teri5354** [Meituan-Dianping/mpvue#1348]
1、自定义组件test （测试代码）
<template>
  <van-tabbar active="1" @change="onChange">
    <van-tabbar-item icon="home-o">标签</van-tabbar-item>
    <van-tabbar-item icon="search" dot>标签</van-tabbar-item>
    <van-tabbar-item icon="friends-o" info="5">标签</van-tabbar-item>
    <van-tabbar-item icon="setting-o" info="20">标签</van-tabbar-item>
  </van-tabbar>
</template>

methods: {
onChange() {
console.log('test')
}
}

2、在b页面引用该组件

原先的mpvue 1.0.13版本，子组件的onChange事件可以正常使用。本次升级到1.1.0之后，发现所有的子组件绑定的事件已经无法使用了，请问有什么方法解决吗？项目中引用了不少公共组件，急！！！

**Comment by teri5354** [comment]
作者大大们可不可以帮忙看一下呀，我用上 @change.self="onChange"也是不行的

**Comment by DemonGao** [comment]
+1

**Comment by DemonGao** [comment]
![image](https://user-images.githubusercontent.com/17852566/52033256-4cac6c80-255f-11e9-9b92-843f8239615f.png)
![image](https://user-images.githubusercontent.com/17852566/52033262-559d3e00-255f-11e9-930c-a1d517819994.png)
修改package.json 重新npm i一下吧

**Comment by hucq** [comment]
1.0.20 之后 1.4.0 之前的版本，是2.0的早期版本。
2.0 发布后新创建的项目默认使用 2.0，原先 1.x 的老项目会在 1.4.x 的版本上长期维护，版本号以 1.4.0 开始迭代。
根据需求升级 1.4.x, 或者 使用 2.0.x

**Comment by teri5354** [comment]
经测试,使用2.0.2该问题已经修复了

**Comment by wushu843639932** [comment]
版本已经修改到2.0.2后，自定义的组件的事件还是触发不了

**Comment by wushu843639932** [comment]
@hucq
