### ISSUE TITLE
页面之间的跳转 参数传递

### ISSUE THREAD

**Issue by linfengaixixi** [Meituan-Dianping/mpvue#135]
# [问题简单描述]
页面之间的跳转 参数传递
**问题复现步骤:**
   wx.navigateTo({
                url: '../index/index?aa=bb&cc=dd'
  })

在 index onLoad 方法中怎么获取参数aa 和 cc 
onLoad(options){
    // 输出options 是 undefined
    console.log(options);

}

页面之间的跳转 参数 该如何获取？

**Comment by anchengjian** [comment]
文档 http://mpvue.com/qa/#page-onload-options
