### ISSUE TITLE
插槽上的事件无法响应

### ISSUE THREAD

**Issue by HADB** [Meituan-Dianping/mpvue#1351]
## [问题简单描述]

**问题复现步骤：**

1. 组件代码：
order-group.vue

```
<template>
    <div class="order-group">
        <slot />
    </div>
</template>
```
2. 调用的代码：
```
<template>
    <order-group>
        <input @change="test">
    </order-group>
</template>

<script>
export default {
    components: {
        orderGroup
    },
    methods: {
        test() {
            console.log('test')
        }
    }
}
</script>
```
3. 修改 input 的值

**期望的表现：**

触发 test 方法

**观察到的表现：**

不能触发 test 方法

**Comment by yz-xlame** [comment]
你可能需要多试一下，我也没有太掌握为什么，但是有的时候可以触发一些事件，而有的时候不行

**Comment by Holmeshaw** [comment]
文档里说 input 的 change 事件被转为 blur 事件了，blur 的时候就可以触发。

**Comment by wuxiaolan91** [comment]
mpvue 的文档里不是说不支持 slot 么

> Slot（scoped 暂时还没做支持）

**Comment by wuxiaolan91** [comment]
测了下 支持 slot
只是 slot里的内容修改后需要手动 npm run dev 下才更新的内容才会在开发者工具里生效, hot reload则开发者工具里显示的还是旧的内容

**Comment by sideFlower** [comment]
那么神奇...

**Comment by yz-xlame** [comment]
slot是可以使用的，请仔细看文档说的是无法使用slot的scoped，而不是无法使用slot

**Comment by HADB** [comment]
看这个更新频率和 issue 的处理情况，感觉 mpvue 已经凉凉了
