### ISSUE TITLE
数据存放问题

### ISSUE THREAD

**Issue by ZHANGSHAOKANG** [Meituan-Dianping/mpvue#1353]
文档最佳实践中的第一条：
 冗余数据不要挂在 data 里，所有在 data/props/computed 中的数据，每次变更都会从微信小程序的 JSCore 进程，通过 setData 序列化成字符串后发送到 JSRender 进程。所以，如果你的数据量巨大的时候，会导致页面非常卡顿。

问题：
这句话的意思是：最好用vuex来管理数据，并且vuex管理的数据不在页面的computed中映射进来吗？

**Comment by mythshuazi** [comment]
我使用的是vuex来管理数据，但发现主index.vue里面加载了vuex中的数据，两个子组件也同样加载了vuex数据，但是在小程序开发者工具中看AppData，同样的数据是两份
![image](https://user-images.githubusercontent.com/7909545/51959204-3aaec900-248e-11e9-9499-695c610c6511.png)

**Comment by hucq** [comment]
这是 mpvue 的实现逻辑，为处理虚拟 dom 和模板中的组件嵌套关系映射所作的实现。截图部分的数据结构对应到 vue 虚拟 dom(vue 组件粒度）结构。
