### ISSUE TITLE
如何配置支持  Tailwind CSS？

### ISSUE THREAD

**Issue by lilianjin** [Meituan-Dianping/mpvue#1354]
请问如何配置：Tailwind CSS
https://tailwindcss.com/docs/examples/buttons

**Comment by Dewyzee** [comment]
@lilianjin 创建tailwind.js， 参考官网配置根目录下的.postcssrc.js或者postcss.config.js。tailwind.css可以放在static目录中，在main.js中import进来。详细的教程可以借鉴
[USING TAILWIND WITH VUE.JS](https://flaviocopes.com/vue-tailwind/)
[vue-cli-tailwind-example](https://github.com/adamwathan/vue-cli-tailwind-example)
[How to Configure your Vue js app to use Tailwind CSS](https://medium.com/backticks-tildes/how-to-configure-your-vue-js-app-to-use-tailwind-css-a6f95d06e1c7),
试了下，对于小程序的兼容存在问题，你可以尝试下

**Comment by lilianjin** [comment]
感谢， 我再试试！

**Comment by lilianjin** [comment]
@Dewyzee 哥们 兼容的问题有办法解决不？

**Comment by Dewyzee** [comment]
> @Dewyzee 哥们 兼容的问题有办法解决不？

可能需要针对性开发，除了css部分，打包进来的js部分也需要单独处理

**Comment by lilianjin** [comment]
@Dewyzee 已经搞定，很简单。对了再请教一个问题，可以使用swiper.js吗？感谢
