### ISSUE TITLE
mpvue1.0.18的bug，关于更新对象时_keyPath的问题

### ISSUE THREAD

**Issue by spencer1994** [Meituan-Dianping/mpvue#1357]
## [问题简单描述]
之前已经有issue提过这个问题了，怕官方没看到再提多一次。

相关问题如下：

首先1.0.18是再1.0.13的基础上优化了数据全量更新的性能。相关链接如下：
[更新某个data属性，这里实际是更新了全部data属性](https://github.com/Meituan-Dianping/mpvue/issues/500)

更新了1.0.18后的源码里面有个bug导致对象更新的时候出异常。相关链接如下：
[对象赋值后，对象属性再次赋值会造成对象赋值无效](https://github.com/Meituan-Dianping/mpvue/issues/1305)
[for...in...遍历Object会遍历到__keyPath](https://github.com/Meituan-Dianping/mpvue/issues/1276)

如果像下面这个issue说的要手动判断的话，感觉不太合适。
[给对象添加属性，数据结构会多出一个_keyPath](https://github.com/Meituan-Dianping/mpvue/issues/1312)

@sexdevil 希望大佬能关注一下这个问题。

**Comment by hucq** [comment]
已经发布，请更新 
```
yarn add mpvue@1.0.19 mpvue-template-compiler@1.0.19
```

**Comment by sexdevil** [comment]
不好意思 前阵子业务比较忙 解决慢了
