### ISSUE TITLE
vue对象的data双向数据绑定只能支持2层，超过2层只有单向绑定

### ISSUE THREAD

**Issue by Sunzhuokai** [Meituan-Dianping/mpvue#1358]
## [问题简单描述]
vue中的data双向数据绑定只能支持2层对象，超过2层只有单向绑定
**问题复现步骤：**
1. [第一步]
data 中指定一个需要绑定的对象 test
```
data () {
      return {
        test: { test: { test: 'test' } },
        test1: { test1: ‘test’ },
         }
```
2. [第二步]
把这个对象绑定到页面上
3. [其他步骤...]
分别更改对象的最内层的值为‘123’
**期望的表现：**
页面上应该都会更新为123
**观察到的表现：**
其中test的值不变，test1的值变为123

**屏幕截图或动态图：**

![复现步骤的屏幕截图和动态 GIF 图](图片的 url)
[建议提供可运行的demo]

**Comment by Sunzhuokai** [comment]
测试了下是因为页面中用了usingComponents造成的，有什么解决办法吗？

**Comment by xfworld** [comment]
你把复杂结构改成单层不就完事了

**Comment by Sunzhuokai** [comment]
你说的真对
