### ISSUE TITLE
vue的filter在mpvue的数组渲染中有什么好的替代方案吗?

### ISSUE THREAD

**Issue by JsonSong89** [Meituan-Dianping/mpvue#1361]
mpvue目前不支持filter和在template中使用method,在做一些开发的时候非常不方便.

目前我的做法是外部使用计算属性,数组渲染则使用赋值前map并Vue.set,非常繁琐.

还有其他更好的做法吗?感觉这是刚需啊,如果能支持最好,不能支持,也请官方给一个最佳实践吧.

**Comment by hucq** [comment]
暂不计划支持 filter，这一步操作在数据模型中先处理好再使用吧。
