### ISSUE TITLE
多个组件引用同一个vuex数据，在开发者工具的AppData存在多个值

### ISSUE THREAD

**Issue by mythshuazi** [Meituan-Dianping/mpvue#1364]
页面的index.vue引用了对应的vuex中的数据，其两个子组件也引用了同样的vuex中的数据，
相同的数据在微信小程序开发者工具中AppData中查看同时存在3份一样的数据，这样的重复数据，在数据量大的场景下，效率会很低吧
![image](https://user-images.githubusercontent.com/7909545/51959438-51095480-248f-11e9-95b4-e6549e99bd14.png)

上图这种重复数据是正常的吗，还是我的代码有问题？

是否有方法做到引用一个vuex的数据，在AppData中只会存在一份？

**Comment by hucq** [comment]
不影响，目前的设计还做不到一份。
appData 是从 vue data 同步而来，实际维护的还是在 vue data中，不影响。
