### ISSUE TITLE
新建项目报错 Final loader didn't return a Buffer or String

### ISSUE THREAD

**Issue by zhaixiyun** [Meituan-Dianping/mpvue#1365]
## [新建项目运行npm run dev报错 Final loader didn't return a Buffer or String]

![image](https://user-images.githubusercontent.com/23442223/51963860-cc730200-249f-11e9-8515-786a8c3b0ad0.png)

 error  in ./src/pages/index/index.vue

Module build failed: Error: Final loader didn't return a Buffer or String
    at runLoaders (E:\popcornmall\node_modules\webpack\lib\NormalModule.js:204:4
6)
    at E:\popcornmall\node_modules\loader-runner\lib\LoaderRunner.js:373:3
    at iterateNormalLoaders (E:\popcornmall\node_modules\loader-runner\lib\Loade
rRunner.js:214:10)
    at iterateNormalLoaders (E:\popcornmall\node_modules\loader-runner\lib\Loade
rRunner.js:221:10)
    at E:\popcornmall\node_modules\loader-runner\lib\LoaderRunner.js:236:3
    at Object.context.callback (E:\popcornmall\node_modules\loader-runner\lib\Lo
aderRunner.js:111:13)
    at compileWxml.call.then.catch (E:\popcornmall\node_modules\mpvue-loader\lib
\template-compiler\index.js:99:12)
    at process._tickCallback (internal/process/next_tick.js:68:7)

 @ ./src/pages/index/index.vue 10:0-328
 @ ./src/pages/index/main.js

看到有说是版本的问题，但是更改版本或者锁死版本还是没用

**Comment by Destinygu** [comment]
我昨天开发还没问题，今天也碰到这种情况了

**Comment by smoothdvd** [comment]
@zhaixiyun @Destinygu mpvue, mpvue-template-compiler退回1.0.18就好了。

**Comment by Destinygu** [comment]
@smoothdvd 
![1](https://user-images.githubusercontent.com/18415454/51965574-eb27c780-24a4-11e9-89f7-0eb805d84940.png)
![image](https://user-images.githubusercontent.com/18415454/51965600-fd096a80-24a4-11e9-9013-5a8a066b8429.png)
mpvue, mpvue-template-compiler之前版本是1.0.11，都升到1.0.18后可以正常打开，可是之前能够正常打开的页面报错了。main.js检查过没有问题，这也是mpvue编译的问题？

**Comment by nikolaiku** [comment]
同。按照官网的五分钟教程。出现该问题。

**Comment by zybieku** [comment]
新版的问题,把package.json里面的 这两个写死就好了,不要^
"mpvue": "1.0.18"
"mpvue-template-compiler": "1.0.18"

**Comment by hucq** [comment]
@zhaixiyun @Destinygu @smoothdvd @zybieku @nikolaiku 
1.0.19 和 1.0.20 版本会有这个问题

### 解决方案：
将 mpvue-loader 升级到 1.2.0 即可，其他依赖不用锁定任何版本.

### 操作方式：
- 新建项目直接重新安装
- 使用 1.0.18 以后的版本，将mpvue-loader升级到最新即可（1.2.0）

**Comment by hnty545** [comment]
我将mpvue升级到1.2.0之后报这个错

C:\_develop\workspace_wx\vue-smart-publish-mix\node_modules\mpvue-loader\lib\mp-compiler\util.js:19
  const filePath = `/${resolveSrc(context, file)}.${fileExt.template}`
Cannot read property 'template' of undefined

**Comment by herodhb** [comment]
新建项目还是有同样的问题

**Comment by minyin** [comment]
"mpvue": "^2.0.0",
"mpvue-loader": "^2.0.0",
"mpvue-template-compiler": "^2.0.0",
依然存在该问题，我从mpvue-quickstart开始开发，引入了一个第三方库，库里使用vue nextTick。 @hucq

**Comment by wushu843639932** [comment]
"mpvue": "^2.0.3",
"mpvue-loader": "^2.0.1",
"mpvue-template-compiler": "^2.0.3",
在引入第三方库时出现该问题

**Comment by zwblue** [comment]
> "mpvue": "^2.0.0",
> "mpvue-loader": "^2.0.0",
> "mpvue-template-compiler": "^2.0.0",
> 依然存在该问题，我从mpvue-quickstart开始开发，引入了一个第三方库，库里使用vue nextTick。 @hucq
你子组件改个不常见的名字试试

**Comment by zwblue** [comment]
> "mpvue": "^2.0.3",
> "mpvue-loader": "^2.0.1",
> "mpvue-template-compiler": "^2.0.3",
> 在引入第三方库时出现该问题

你子组件名字改个不常见的名字试试

**Comment by luodanyalian** [comment]
> > "mpvue": "^2.0.0",
> > "mpvue-loader": "^2.0.0",
> > "mpvue-template-compiler": "^2.0.0",
> > 依然存在该问题，我从mpvue-quickstart开始开发，引入了一个第三方库，库里使用vue nextTick。 @hucq
> > 你子组件改个不常见的名字试试

改了不行

**Comment by Czde1989** [comment]
今天新建项目，也出现这个问题了。。。怎么解决？
“mpvue-loader”  版本是：“^2.0.0”

**Comment by dyyliao123** [comment]
有解决方案吗

**Comment by ietwangwei** [comment]
我把组件名称换成可能跟预留标签不一样的标签就可以了

**Comment by wangcpsnow** [comment]
我项目也遇到了，是因为有style的一个三目运算符，去掉后就没事儿了
