### ISSUE TITLE
webpack-mpvue-vendor-plugin 0.1.4 source map 只显示src/components下的vue文件

### ISSUE THREAD

**Issue by smoothdvd** [Meituan-Dianping/mpvue#1366]
## [问题简单描述]
webpack-mpvue-vendor-plugin 0.1.4 source map 只显示src/components下的vue文件

**问题复现步骤：**

1. [第一步]
2. [第二步]
3. [其他步骤...]

**期望的表现：**
显示src/下所有的vue文件

[在这里描述期望的表现]

**观察到的表现：**

[在这里描述观察到的表现]

**屏幕截图或动态图：**
<img width="254" alt="screen shot 2019-01-30 at 3 14 53 pm" src="https://user-images.githubusercontent.com/22420/51964981-1f01ed80-24a3-11e9-8077-4dea04e6483c.png">

![复现步骤的屏幕截图和动态 GIF 图](图片的 url)
[建议提供可运行的demo]

**Comment by smoothdvd** [comment]
webpack-mpvue-vendor-plugin 0.1.4 为什么会在.map里加上
```
require("../../common/manifest.js.map")
require("../../common/vendor.js.map")
require("../../common/manifest.js.map")
require("../../common/vendor.js.map")
```
微信开发者工具报：
DevTools failed to parse SourceMap: http://127.0.0.1:26600/appservice/pages/index/main.js.map

去掉就正常了

**Comment by Dewyzee** [comment]
@smoothdvd 问题已修后，请关注后续发布的版本，感谢提出的宝贵建议

**Comment by Dewyzee** [comment]
@smoothdvd 问题已修复，请关注后续发布的版本，感谢提出的宝贵建议

**Comment by hucq** [comment]
如配置上还有问题重新升级即可。
