### ISSUE TITLE
computed中出错之后会影响全局，导致所有页面methods中对数据的操作没有调用小程序的setData方法

### ISSUE THREAD

**Issue by 1165506270** [Meituan-Dianping/mpvue#1367]
## [问题简单描述]

**问题复现步骤：**

1. [第一步]
新建一个mpvue-quickstart项目， 
在pages/index/index.vue中将computed写成这样
```
computed: {
    count() {
      console.log(aaa);
      return ''
    },
  },
```
在pages/counter/index.vue替换成以下
```
<template>
  <div class="counter-warp">
    <p>Vuex counter：{{ count }}</p>
    <p>测试值a：{{ a }}</p>
    <p>
      <button @click="increment">+</button>
      <button @click="decrement">-</button>
    </p>

    <a href="/pages/index/main" class="home">去往首页</a>
  </div>
</template>

<script>
// Use Vuex
import store from './store';

export default {
  computed: {
    count() {
      return store.state.count;
    },
  },
  data() {
    return {
      a: 1
    }
  },
  methods: {
    increment() {
      console.log('触发了');
      this.a += 1;
      store.commit('increment');
    },
    decrement() {
      store.commit('decrement');
    },
  },
};
</script>

<style>
.counter-warp {
  text-align: center;
  margin-top: 100px;
}
.home {
  display: inline-block;
  margin: 100px auto;
  padding: 5px 10px;
  color: blue;
  border: 1px solid blue;
}
</style>
```
2. [第二步]
启动小程序
在index页面的输入框随便录入，然后跳转到VUEX示例页面按+号，会出现increment方法调用了，但数值没有变化，查看调试工具的appData也是没有变化的。 后退再回到这个页面之后数值就更新了
3. [其他步骤...]

**期望的表现：**

希望即使一个方法里出现了错误，也不要影响到全局。

**Comment by Dewyzee** [comment]
@1165506270 其实不太明白你这么做的意图何在。你的问题是因为你在计算属性中引用未定义变量导致报错，从而影响了watcher队列执行。而关于你这个解决方法，从VUE源码的上下文可以知道重置状态前是需要完成一些动作的
![image](https://user-images.githubusercontent.com/4916726/52052328-f1936d80-2590-11e9-8a10-6e270c4df337.png)
所以你在这里抛错后直接调用是不太妥当的。

**Comment by 1165506270** [comment]
@Dewyzee 这里引用未定义变量只是为了方便重现场景，我这边实际出现的场景是生产环境中由于客户的网络问题，导致后端的接口没有返回数据，从而使computed中报错，然后就使整个小程序无法正常使用了，需要删除小程序再下载才可以解决问题。事后我也处理了那个地方的在后端无数据返回情况会报错的问题。
但是我认为在一个页面的computed报错了，从而影响整个程序运行是不合理的。

**Comment by hucq** [comment]
@1165506270 可以在对应页面的 `main.js` 文件中设置 `errorHandler` 消除异常影响。示例如下：

```
// add this to handle exception
Vue.config.errorHandler = function (err) {
  if (console && console.error) {
    console.error(err)
  }
}
```

**Comment by savioryu** [comment]
能大致解释一下原因吗？

**Comment by twpDesigner** [comment]
@1165506270 这个bug最后有好的解决方案吗
我也遇到了类似的问题

**Comment by coolRoger** [comment]
写严谨一点的js逻辑可以防止computed异常, 例如定义给需要return的变量添加default值, 确认computed代码块到最后始终return变量
