### ISSUE TITLE
掉用小程序 API wx.chooseImage

### ISSUE THREAD

**Issue by zhaozhiqiang1** [Meituan-Dianping/mpvue#1368]
## [问题简单描述]

**问题复现步骤：**

1. [第一步] 掉用小程序 API wx.chooseImage 打开相册选择图片点击完成
2. [第二步]
3. [其他步骤...]

**期望的表现：** 

选择完图片之后就关闭相册不会再次进入到相册中

**观察到的表现：**
掉用小程序 API wx.chooseImage 打开相册选择图片之后，又跳回到了相册中。

**屏幕截图或动态图：**

![复现步骤的屏幕截图和动态 GIF 图](图片的 url)
[建议提供可运行的demo]

**Comment by Dewyzee** [comment]
@zhaozhiqiang1 相关源码方便贴下吗？我这边验证是不存在这个问题的，我是IOS 12，微信7.0版本

**Comment by Dewyzee** [comment]
@zhaozhiqiang1 贴的代码貌似没啥问题的，可以确认下在小程序生命周期中是否有额外处理，另外可能跟手机系统以及微信版本有关，可以参考 [小程序wx.chooseImage 相册功能](https://developers.weixin.qq.com/community/develop/doc/0002c012ed0610039908f34c656400?highLine=chooseImage)

**Comment by hucq** [comment]
建议排查代码逻辑，推测是代码逻辑问题。如果小程序api本身没bug，可以判断是否有多次调用api.
如能给出最小出错代码，我们可以更方便判断问题。
