### ISSUE TITLE
如果作者不准备维护这个仓库了，是否寻求社区接手

### ISSUE THREAD

**Issue by shengxinjing** [Meituan-Dianping/mpvue#1369]
如果作者不准备维护这个仓库了，是否寻求社区接手
毕竟当年是小程序非常领先的解决方案，现在已经落后很多了

**Comment by smoothdvd** [comment]
没觉得落后啊

**Comment by shengxinjing** [comment]
@smoothdvd 支付宝小程序，头条小程序 百度小程序都不支持  还不算落后吗？

**Comment by Dewyzee** [comment]
@shengxinjing 百度小程序发布的版本已经支持了哈，头条与支付宝的支持已经开发完毕即将发布

**Comment by shengxinjing** [comment]
@Dewyzee 赞啊 我还以为不咋更新了 期待 有具体的上线时间吗

**Comment by shengxinjing** [comment]
官网文档没看到如何支持百度小程序的命令鸭

**Comment by smoothdvd** [comment]
@shengxinjing 落不落后又不是完全根据支持平台来的

**Comment by Dewyzee** [comment]
> 官网文档没看到如何支持百度小程序的命令鸭

文档以及配套的插件正在陆续补充，感谢关注
