### ISSUE TITLE
textarea @click 事件失效

### ISSUE THREAD

**Issue by limengfan12** [Meituan-Dianping/mpvue#1370]
## textarea  @click 事件失效

**问题复现步骤：**

1. <textarea  class="weui-input textarea-input" v-model="fulldz" disabled @click="openSelect"  @blur="xzdqonce=(fulldz=='')"/>

2. 点击事件失效，去掉disabled 会自动弹出键盘

**期望的表现：**
期望能有点击事件，但是不要弹出键盘

**Comment by Dewyzee** [comment]
@limengfan12 这个可能是微信本身不支持。基于微信原生语法disabled后也无法触发绑定的事件，另外textarea属于原生组件，内部的行为暂时没有较好的方法来进行修改，基于您自己的使用场景可以尝试下其它的解决方案
