### ISSUE TITLE
1.1.2版本v-for内部组件事件生效

### ISSUE THREAD

**Issue by 909559792** [Meituan-Dianping/mpvue#1372]
## 1.1.2版本v-for内部组件事件生效
1. 我用官方模板试了一下，如果没有在v-for里面是可以生效事件的。但是在v-for里面则失效了。

**Comment by hucq** [comment]
升级一下即可，版本为 2.0.3，老项目将同步升级到 1.4.2 ，重新安装依赖即可

```
yarn add mpvue@2.0.3 mpvue-template-compiler@2.0.3
```

**Comment by 909559792** [comment]
> 升级一下即可，版本为2.0.3，老项目将同步升级到1.4.2，重新安装依赖即可
> 
> ```
> yarn add mpvue@2.0.3 mpvue-template-compiler@2.0.3
> ```
已经升级2.0版本 感谢大佬
