### ISSUE TITLE
小程序原生picker不支持双向绑定吗？

### ISSUE THREAD

**Issue by joze2016** [Meituan-Dianping/mpvue#1373]
我在使用原生date picker时候，怎么无法双向绑定value呢

模板部分用的pug语法
`picker(mode="date" :value="start")`
`    .picker {{start}}`

js data部分
`data () {
    return {
      start: '2019-02-14'
    };
  },`

修改日期后，页面没有变化，我哪里写错了吗？

**Comment by joze2016** [comment]
是因为小程序控件不支持双向绑定吗？我需要通过@change事件去更新start？

`picker(mode="date" :value="start" @change="bindDateChange")`

`methods: {
    bindDateChange (e) {
      console.log("date changed", e);
      this.start = e.mp.detail.value;
    }
  }`

**Comment by liufeics** [comment]
<picker mode="date" :value="startDate" @change="bindStartDateChange" :end="endDate">
        <div class="picker" :class="startDate ? 'active' : ''">
         {{startDate ? startDate : '请选择开始时间'}}
         <span class="iconfont icon-riqi"></span>
        </div>
      </picker>

**Comment by liufeics** [comment]
<picker mode="date" :value="startDate" @change="bindStartDateChange" :end="endDate">
        < div class="picker" :class="startDate ? 'active' : ''">
         {{startDate ? startDate : '请选择开始时间'}}
         <span class="iconfont icon-riqi"></span>
        </ div>
      </ picker>

**Comment by joze2016** [comment]
> <picker mode="date" :value="startDate" @change="bindStartDateChange" :end="endDate">
> < div class="picker" :class="startDate ? 'active' : ''">
> {{startDate ? startDate : '请选择开始时间'}}
> 
> </ div>
> </ picker>

@liufeics bindStartDateChange方法里写的什么？

**Comment by liufeics** [comment]
bindStartDateChange(e) {
      console.log(e.mp.detail.value);
      console.log('picker发送选择改变，携带值为', e.mp.detail.value);
      this.startDate = e.mp.detail.value;
    },

**Comment by joze2016** [comment]
> bindStartDateChange(e) {
> console.log(e.mp.detail.value);
> console.log('picker发送选择改变，携带值为', e.mp.detail.value);
> this.startDate = e.mp.detail.value;
> },

那就是没有双向绑定了，谢谢了

**Comment by choudac** [comment]
我也写点什么记录一下e.mp.detail.value;
