### ISSUE TITLE
不触发vue组件的click事件

### ISSUE THREAD

**Issue by d0apga** [Meituan-Dianping/mpvue#1375]
## [问题简单描述]
编写一个vue组件，在div上面定义的click事件不触发
**问题复现步骤：**

1. 页面page/index.vue， 引入组件Card
2. Card引入组件CardItem
3. CardItem里面定义click事件onClick

**期望的表现：**
选项卡订单页面，点击CardItem组件的文字控制台打印onClick

**观察到的表现：**
选项卡订单页面，点击CardItem组件的文字控制台没有输出onClick

**屏幕截图或动态图：**

"mpvue": "^2.0.0"
"mpvue-loader": "^2.0.0"
"mpvue-template-compiler": "^2.0.0"
"mpvue-webpack-target": "^1.0.3"
"webpack-mpvue-vendor-plugin": "^2.0.0"
"webpack-mpvue-asset-plugin": "^2.0.0"

下面是demo:
[my-project.zip](https://github.com/Meituan-Dianping/mpvue/files/2862931/my-project.zip)

麻烦看一下这个问题

**Comment by d0apga** [comment]
发现是v-for的问题， 在v-for前面加一个组件Card，这个组件可以触发事件

**Comment by d0apga** [comment]
#1372

**Comment by d0apga** [comment]
已修复？

**Comment by hucq** [comment]
> 已修复？
重复问题保留一个即可

**Comment by 909559792** [comment]
有修复没？

**Comment by d0apga** [comment]
还没有， 先用1.0.18版本吧

**Comment by hucq** [comment]
@d0apga @909559792 升级一下即可，具体版本为 2.0.3，老项目将同步升级到 1.4.2 ，重新安装依赖即可

```
yarn add mpvue@2.0.3 mpvue-template-compiler@2.0.3
```

**Comment by d0apga** [comment]
感谢感谢(*^_^*)
