### ISSUE TITLE
做小程序列表瀑布流时遇到的问题，mpvue中setData没有回调吗？

### ISSUE THREAD

**Issue by spencer1994** [Meituan-Dianping/mpvue#1378]
## [问题简单描述]
在做小程序瀑布流时，调用了wx.createSelectorQuery().selectAll去获取元素的高度来判断当前元素是放在左边还是放在右边，但是由于渲染层渲染速度的问题，导致元素没渲染完成则调用了wx.createSelectorQuery().selectAll获取到的高度不完整。

设置setTimeout的话可以实现但是很不科学。查询到小程序[setData有callback回调](https://developers.weixin.qq.com/miniprogram/dev/framework/app-service/page.html#pageprototypesetdataobject-data-function-callback)，想咨询一下mpvue里面有吗？有的话应该怎么设置？是否是我遗漏了，我查了源码及看文档均无发现。

这个问题是在mpvue@1.0.20出现的，应该是优化了数据赋值的方式才会出现的。在mpvue@1.0.13是没有问题的。

异常效果：
![image](https://user-images.githubusercontent.com/19463934/52766284-aafa4480-3061-11e9-8f12-fbb157455cdd.png)

期望效果：
![image](https://user-images.githubusercontent.com/19463934/52766290-b5b4d980-3061-11e9-9ba6-bace829b3347.png)

**Comment by hucq** [comment]
1.0.20 性能应该是优于 1.0.13 的。
mpvue 更新数据只能使用 vue 的方式，setData 并不对外暴露了。
框架内部 setData 会有频繁调用，回调也不易开放出来。
设置数据到渲染完成中间确有时间差，这里我建议你换一个思路吧，小程序和web应用还是有一些差异。
譬如将获取高度的时机提前，或者根据数据就能算出高度。

**Comment by spencer1994** [comment]
@hucq 谢谢你的建议。

只是这个列表的数据比较复杂，有多种形式，比较难根据数据就能计算出高度，不用小程序的wx.createSelectorQuery()获取节点高度的画，计算出来的也不准确，因为在不同机型上rpx渲染出来的高度是不一样的。

我在想想怎么办。
