### ISSUE TITLE
编译后，main.js顶部写了两遍“../../common/manifest.js”是怎么个情况？

### ISSUE THREAD

**Issue by microkof** [Meituan-Dianping/mpvue#1379]
## [问题简单描述]

打开编译后任一page的main.js，顶部是这样子：

```
require("../../common/manifest.js")
require("../../common/vendor.js")
require("../../common/manifest.js")
require("../../common/vendor.js")
```

虽然不妨碍使用，但是这是干嘛呢？

**问题复现步骤：**

打开小程序目录里随意一个page的main.js即可。

**期望的表现：**

写一遍不就行了？

**Comment by hucq** [comment]
根据最新的 quickstart 项目中的 build 配置，更新一下即可。
新版本 build/dev-server.js 中移除了 webpack 方法调用的回调参数。
