### ISSUE TITLE
两个入口同时引入一个组件时，样式失效

### ISSUE THREAD

**Issue by EasonYou** [Meituan-Dianping/mpvue#138]
# 组件样式同时引用失效
两个入口同时引入一个组件时，样式失效

**问题复现步骤:**

1. 定义一个组件 my-button，并定义样式，我在这用的语法是scss，并加入scoped（没有scoped也有问题）
2. 在index引用组件my-button，成功
3. 在index引用组件my-button，在pageA引用my-button，样式都失效，应该是没有编译到

**期望的表现:**

应该是在多个页面引用组件，样式要编译进去

本来以为是组件问题，后来试了两个组件，同样有问题

系统是ubuntu + wine运行开发者工具，不过应该没什么关系，毕竟是找不到样式，没有编译进去吧我猜？

**Comment by aOrz** [comment]
装一下 webpack-mpvue-asset-plugin 这个插件，在，webpack.base.config.js 中引入并配置，例：
```javascript
var MpvuePlugin = require('webpack-mpvue-asset-plugin')；
module.exports = {
  entry: entry,
     ......
  plugins: [
    new MpvuePlugin()
  ]
}```

**Comment by EasonYou** [comment]
@aOrz 解决了，感谢
