### ISSUE TITLE
'mpvuePlatform' is not defined   'mpvue' is not defined

### ISSUE THREAD

**Issue by annadevelop** [Meituan-Dianping/mpvue#1381]
## [问题简单描述]
E:\myvue\vuebegin\my-project\src\App.vue
  14:9   error  'mpvuePlatform' is not defined  no-undef
  15:14  error  'mpvue' is not defined          no-undef
  17:7   error  'mpvue' is not defined          no-undef
  22:14  error  'mpvue' is not defined          no-undef
  24:7   error  'mpvue' is not defined          no-undef

E:\myvue\vuebegin\my-project\src\pages\index\index.vue
  57:11  error  'mpvuePlatform' is not defined            no-undef
  58:9   error  'mpvue' is not defined                    no-undef
  60:9   error  'mpvue' is not defined                    no-undef
  70:9   error  'app' is assigned a value but never used  no-unused-vars

E:\myvue\vuebegin\my-project\src\pages\logs\index.vue
  41:9   error  'mpvuePlatform' is not defined  no-undef
  42:14  error  'mpvue' is not defined          no-undef
  44:14  error  'mpvue' is not defined          no-undef

**问题复现步骤：**

1. [第一步]
vue init mpvue/mpvue-quickstart my-project
2. [第二步]
cd mp-project
npm install
npm run dev

**期望的表现：**
运行成功
[在这里描述期望的表现]

**观察到的表现：**
报错
[在这里描述观察到的表现]

**屏幕截图或动态图：**
！！！
![复现步骤的屏幕截图和动态 GIF 图](图片的 url)
[建议提供可运行的demo]

**Comment by doornot** [comment]
同问，我也遇到了这样的问题。Eslint很多报错，Airbnb和Standard两种preset都试过。

**Comment by hucq** [comment]
> 同问，我也遇到了这样的问题。Eslint很多报错，Airbnb和Standard两种preset都试过。

我后续会上传一个符合lint 规则的版本，你可以先关掉代码检查或者格式化一下。

**Comment by hucq** [comment]
eslint 规则已经补全，可使用新模板即可。
若选择不更新，可以在  `.eslintrc.js` 中增加 globals 配置，示例如下：

```javascript
globals: {
    App: true,
    Page: true,
    wx: true,
    swan: true,
    tt: true,
    my: true,
    getApp: true,
    getPage: true,
    requirePlugin: true,
    mpvue: true,
    mpvuePlatform: true
  }
```

**Comment by yuana1** [comment]
可以了
