### ISSUE TITLE
pick-view标签bindpickstart & bindpickend事件监听不到

### ISSUE THREAD

**Issue by BowenTH** [Meituan-Dianping/mpvue#1383]
```javascript
<picker-view class="pick" @change="pickChange" @pickstart="pickstart" @pickend="pickend">
</pick-view>
```
change能监听到，pickstart跟pickend监听不到

**Comment by Dewyzee** [comment]
感谢反馈，我确认下

**Comment by Dewyzee** [comment]
@BowenTH 可以监听到，确认下是否跟你标签名写错有关系
![image](https://user-images.githubusercontent.com/4916726/53006469-3a439580-3470-11e9-9f2a-40d33b7563d8.png)
