### ISSUE TITLE
项目删除包从新下载 项目能启动 但是报错 事件失效

### ISSUE THREAD

**Issue by cg4212440** [Meituan-Dianping/mpvue#1384]
项目删除包从新下载 项目能启动 但是报错 事件失效。 旧包可以正常启动

**Comment by hucq** [comment]
辛苦补充一下信息：

1. 前后版本是否有升级，现在的版本是多少（mpvue, mpvue-loader）
2. 报错信息是什么
3. 事件是如何写的

**Comment by PengDon** [comment]
我也昨天也遇到这个问题了。
目前版本信息：
"mpvue": "^1.0.13",
"mpvue-loader": "^1.1.4",
问题描述：
     同样的代码，开个新分支重新下载依赖就跑步起来了，试了官网的那个小例子也跑不起来了。
报错信息：
  提示项目ode_modules\mpvue-loader\lib目录下的loader.js文件报错
具体的报错代码：
 if (!mpOptions.fileExt) {
    throw new Error(
      '[mpvue-loader] need "fileExt" option in file "build/vue-loader.conf.js"，init a new project and copy the directory "build/" to this porject, or just check the "fileExt" option'
    )
  }
截图：
![image](https://user-images.githubusercontent.com/9321637/52841265-ce42f380-3136-11e9-856c-c8c5df239b5b.png)

**Comment by cg4212440** [comment]
> 辛苦补充一下信息：
> 
> 1. 前后版本是否有升级，现在的版本是多少（mpvue，mpvue-loader）
> 2. 报错信息是什么 没有报错信息 正常启动 就是有下包的警告
> 3. 事件是如何写的 ：@tap 我用的是小程序swiper组件，我发现把swiper去掉 子组件事件就会好
但是之前都没问题啊。如果去掉 代码得大改。。受不了啊
截图：![image](https://user-images.githubusercontent.com/39072527/52853800-9b5d2780-3157-11e9-8250-cf97d2ed905a.png)

**Comment by xiaopc** [comment]
1. package-lock.json 里 mpvue 1.0.7, mpvue-loader 1.0.10，本地不更新没问题。
2. package.json 里 mpvue ^1.0.6, mpvue-loader ^1.0.8，install & build 报错。
3. 所有 page 的 js 全都是这条错误

**Comment by hucq** [comment]
版本依赖问题，mpvue-loader  1.1.4 是有问题：
如果是老项目，再重新安装一下依赖

```
yarn add mpvue@1.4.0 mpvue-loader@1.4.0 mpvue-template-compiler@1.4.0
```

新项目才能使用 2.0.0

**Comment by PengDon** [comment]
新建分支，重新安装依赖还是没法启动，项目代码和配置完全一样，目前试了把版本都变成1.4.0，启动还是报错
  以前的分支，可以正常启动

目前版本：
![image](https://user-images.githubusercontent.com/9321637/53141736-2c0a8c00-35cc-11e9-95c0-4513e56722ab.png)

**问题复现步骤：**
1. git拉一个新分支
2. 重新下载依赖
3. 启动报错
报错截图：
![image](https://user-images.githubusercontent.com/9321637/53141821-928faa00-35cc-11e9-935d-2858ecf34d94.png)

**Comment by fc653074701** [comment]
同上  使用

> yarn add mpvue@1.4.0 mpvue-loader@1.4.0 mpvue-template-compiler@1.4.0

安装对应依赖后问题依旧得不到解决
![image](https://user-images.githubusercontent.com/10204908/53145724-3d5b9480-35dc-11e9-9af4-48e75cd7a737.png)

**Comment by Kuohao-wu** [comment]
2种方法

1. 升级最新的mpvue2.0。 升级指南: https://github.com/Meituan-Dianping/mpvue/releases/tag/2.0.0
2. 升级2.0会增加头条、百度、支付宝小程序的支持，不想升级的同学，可以对以下依赖进行版本锁定，即可， 亲测可用，当然不升旧bug则不能得到解决，风险自行承担。

```json
"mpvue": "1.0.13",
"mpvue-loader": "1.1.4",  
"mpvue-template-compiler": "1.0.13"
```

**Comment by chenzicheng** [comment]
> 2种方法
> 
> 1. 升级最新的mpvue2.0。 升级指南: https://github.com/Meituan-Dianping/mpvue/releases/tag/2.0.0
> 2. 升级2.0会增加头条、百度、支付宝小程序的支持，不想升级的同学，可以对以下依赖进行版本锁定，即可， 亲测可用，当然不升旧bug则不能得到解决，风险自行承担。
> 
> ```json
> "mpvue": "1.0.18",
> "mpvue-loader": "1.1.4",  
> "mpvue-template-compiler": "1.0.18"
> ```

**Comment by qinghua5453** [comment]
> 2种方法
> 
> 1. 升级最新的mpvue2.0。 升级指南: https://github.com/Meituan-Dianping/mpvue/releases/tag/2.0.0
> 2. 升级2.0会增加头条、百度、支付宝小程序的支持，不想升级的同学，可以对以下依赖进行版本锁定，即可， 亲测可用，当然不升旧bug则不能得到解决，风险自行承担。
> 
> ```json
> "mpvue": "1.0.18",
> "mpvue-loader": "1.1.4",  
> "mpvue-template-compiler": "1.0.18"
> ```
确实有效，升级2.0的话慎重，特别是已有的仓库升级的，当然新的cli拉下来肯定2.0是没问题的。
下午跟同事一起搞了4个小时，升级了2.0。也短短嘘嘘 试了其他方法，都不行，自己电脑拉下来，也是报错。按照这位说的操作，就可以了。
