### ISSUE TITLE
mpvue2.0   v-else指令失效

### ISSUE THREAD

**Issue by LiuJinYang9527** [Meituan-Dianping/mpvue#1389]
## [问题简单描述]
使用官方最新模板初始化的项目，v-else指令失效

### 编译前的代码
`
<template>
    <div v-if="false">123 </div>
    <div v-else>321</div>
</template>
`

### 编译后的代码
`
<template name="08ba974b">
  <view wx:if="{{false}}" class="_div data-v-89d62aa2">123 </view>
</template>
`

编译后的wxml文件没有wx:else相关语句

**Comment by LadyChatterleyLover** [comment]
我也遇到了,v-else不生效,不知道是什么原因

**Comment by lostinfo** [comment]
+1

**Comment by jetBn** [comment]
怎么解决的？？
