### ISSUE TITLE
vue 中的 $refs用不了 并且 wx.createSelectorQuery() 报  Cannot read property '__wxWebviewId__' of undefined

### ISSUE THREAD

**Issue by myzqy** [Meituan-Dianping/mpvue#139]
# [问题简单描述]
想获取DOM,获取到页面的高度和元素的高度，但是
1、vue中的$refs 对象获取不到
2、wx.createSelectorQuery() 报 Cannot read property '__wxWebvie
3、document.getElementById 也用不了

求官方人员解答

**Comment by anchengjian** [comment]
按道理应该是用 `wx.createSelectorQuery()` 进行获取。没获取到可能是因为 js 初始化有数据的时候，render 进程中的 DOM 还没准备好，可以试着 setTimeout 或者其他异步方法延迟获取试一下。
