### ISSUE TITLE
子组件事件失效

### ISSUE THREAD

**Issue by cg4212440** [Meituan-Dianping/mpvue#1390]
1.父组件：
![image](https://user-images.githubusercontent.com/39072527/52894456-84b0e200-31e4-11e9-95c3-d7df052b2f86.png)
2：子组件
 ![image](https://user-images.githubusercontent.com/39072527/52894466-b9249e00-31e4-11e9-9311-6f4b57eab2e0.png) 事件失效打印不出！！！！！
![image](https://user-images.githubusercontent.com/39072527/52894470-cc376e00-31e4-11e9-9a99-1f81545f3d98.png) 
3：![image](https://user-images.githubusercontent.com/39072527/52894477-e07b6b00-31e4-11e9-8fc4-d3f904a7884f.png)
去掉循环 点击事件生效！！！
"mpvue": "^2.0.0",
"mpvue-loader": "^2.0.0",
"mpvue-template-compiler": "^2.0.0",

**Comment by spencer1994** [comment]
附议一下

**Comment by imyellow** [comment]
我也遇到了，调试了一下午，发现在 for 里组件内部的自定义事件失效
"mpvue": "^1.0.20"

**Comment by hucq** [comment]
我现在处理一下。

**Comment by caiyongqiang** [comment]
> 此问题同于 #1393
> 新项目升级到 2.0.2 即可。
> 
> ```
> yarn add mpvue@2.0.2 mpvue-template-compiler@2.0.2
> ```
> 老项目升级到 1.4.1 即可。
> 
> ```
> yarn add mpvue@1.4.1 mpvue-template-compiler@1.4.1
> ```

我发现升级了，还是无效，还有其他办法吗？

**Comment by bacy** [comment]
我用的1.4.2，我发现事件恢复了，但是数据不对，表现出来的问题是，我点的是第10条，却判定我点了第3条

**Comment by 0415ypt00** [comment]
1.4.1好用 2.0.2根本就不好用

**Comment by caiyongqiang** [comment]
> 此问题同于 #1393
> 新项目升级到 2.0.2 即可。
> 
> ```
> yarn add mpvue@2.0.2 mpvue-template-compiler@2.0.2
> ```
> 老项目升级到 1.4.1 即可。
> 
> ```
> yarn add mpvue@1.4.1 mpvue-template-compiler@1.4.1
> ```

测试过，发现如果组件两层调用1.4.1可以，但是组件三层调用又失效了，然后更新到1.4.2三层可以点击触发，但是二层调用点击事件又不行了

**Comment by julywind** [comment]
> > 此问题同于 #1393
> > 新项目升级到 2.0.2 即可。
> > ```
> > yarn add mpvue@2.0.2 mpvue-template-compiler@2.0.2
> > ```
> > 
> > 
> > 老项目升级到 1.4.1 即可。
> > ```
> > yarn add mpvue@1.4.1 mpvue-template-compiler@1.4.1
> > ```
> 
> 测试过，发现如果组件两层调用1.4.1可以，但是组件三层调用又失效了，然后更新到1.4.2三层可以点击触发，但是二层调用点击事件又不行了

升级到2.0.2 还是不行  最新的2.0.6也不行
