### ISSUE TITLE
selectComponent  这个api 在无效 mpvue2.0

### ISSUE THREAD

**Issue by zengkaii** [Meituan-Dianping/mpvue#1391]
## selectComponent  这个api 在无效
导致无法使用第三方组件库
![image](https://user-images.githubusercontent.com/38418699/52895844-014ebb00-31fb-11e9-9ecf-7218482cbfab.png)

**问题复现步骤：**
使用的是vant 

1. [第一步] 安装使用了vant 组件
![image](https://user-images.githubusercontent.com/38418699/52895848-07449c00-31fb-11e9-880f-5ace0c61e430.png)

2. [第二步] 页面也有引用
![image](https://user-images.githubusercontent.com/38418699/52895855-11ff3100-31fb-11e9-835f-13d825f417c7.png)

3. [其他步骤...]

**期望的表现：**
能够有toast 效果
[在这里描述期望的表现]

**观察到的表现：**
未找到 van-toast 节点，请确认 selector 及 context 是否正确
![image](https://user-images.githubusercontent.com/38418699/52895869-33f8b380-31fb-11e9-9c2d-57a7dd044470.png)

[在这里描述观察到的表现]

**屏幕截图或动态图：**

![复现步骤的屏幕截图和动态 GIF 图](图片的 url)
[建议提供可运行的demo]

**Comment by zsh2017** [comment]
this.$root.$mp.page.selectComponent('#idname')

**Comment by zengkaii** [comment]
> this.$root.$mp.page.selectComponent('#idname')

已经解决了 ，#van-toast id 一定要是这个，这是vantui 设置的

**Comment by chuan02162** [comment]
> > this.$root.$mp.page.selectComponent('#idname')
> 
> 已经解决了 ，#van-toast id 一定要是这个，这是vantui 设置的

请问如何解决的
