### ISSUE TITLE
mpvue2.0版本 所有平台差异都得自己编写吗？？

### ISSUE THREAD

**Issue by lhf2** [Meituan-Dianping/mpvue#1395]
## [问题简单描述]

**问题复现步骤：**

安装完之后看代码都需要判断平台是什么写特定的代码

![image](https://user-images.githubusercontent.com/10812579/52937248-95568900-3399-11e9-8503-75ee4211b9e8.png)
![image](https://user-images.githubusercontent.com/10812579/52937258-9daec400-3399-11e9-854d-8d9fdb342878.png)
如果差异太多的话会写很多if语句 有没有优化方案？？？

**Comment by hucq** [comment]
api 差异只有一小部分，示例只是示范如果判断当前平台。
对于需要处理差异的场景，可以写一份适配代码抹平差异。
