### ISSUE TITLE
 初始化项目的时候报错vue-cli · [package.json] Missing helper: "if_or"

### ISSUE THREAD

**Issue by liujiusheng** [Meituan-Dianping/mpvue#1396]
## [问题简单描述]
使用yarn初始化项目的时候报错
**问题复现步骤：**

1. yarn global add @vue/cli
2. vue init mpvue/mpvue-quickstart mpvue
3. 一路回车

**期望的表现：**

初始化成功

**观察到的表现：**

报错vue-cli · [package.json] Missing helper: "if_or"

**屏幕截图或动态图：**

![image](https://user-images.githubusercontent.com/9045263/52940414-7a881280-33a1-11e9-8ab6-cb9a0ed9d170.png)

[建议提供可运行的demo]

**Comment by Dewyzee** [comment]
@liujiusheng 感谢反馈，我这边确认下

**Comment by Dewyzee** [comment]
@liujiusheng 应该是vue-cli存在问题，方便提供下您cli的版本以及系统环境吗？问题可以参考[https://github.com/vuejs/vue-cli/issues/794](https://github.com/vuejs/vue-cli/issues/794)以及[https://github.com/vuejs/vue-cli/issues/627](https://github.com/vuejs/vue-cli/issues/627)，解决途径可以尝试改为npm全局安装vue-cli试试

**Comment by liujiusheng** [comment]
> @liujiusheng 应该是vue-cli存在问题，方便提供下您cli的版本以及系统环境吗？问题可以参考[vuejs/vue-cli#794](https://github.com/vuejs/vue-cli/issues/794)以及[vuejs/vue-cli#627](https://github.com/vuejs/vue-cli/issues/627)，解决途径可以尝试改为npm全局安装vue-cli试试

我也怀疑是vue-cli的问题。vue-cli 2.9.6。win10。node10.14.1。npm试了好像也不行。
