### ISSUE TITLE
demo打包成支付宝后，开发工具报错Cannot find module 'global'

### ISSUE THREAD

**Issue by leeviok** [Meituan-Dianping/mpvue#1397]
demo打包成支付宝后，开发工具报错
页面未加载成功，一片空白
![_20190218180145](https://user-images.githubusercontent.com/25154944/52943088-4c0d3600-33a7-11e9-9fcc-64e168ae1166.png)

**Comment by hucq** [comment]
我确认一下

**Comment by hucq** [comment]
很抱歉没有 windows 环境，暂时不能复现。建议你可以如下方式排查一下：

- 代码构建是否正常
- 微信平台是否正常
- 升级一下看看是否正常。

**Comment by hucq** [comment]
重新安装 webpack-mpvue-vendor-plugin 插件即可，
修复版本为： 2.0.2

**Comment by samhuangszu** [comment]
mac os 一直有这个问题：Module not found: Can't resolve 'global'
重新安装 webpack-mpvue-vendor-plugin 插件即可，
修复版本为： 2.0.2

**Comment by zmisgod** [comment]
> mac os 一直有这个问题：Module not found: Can't resolve 'global'
> 重新安装 webpack-mpvue-vendor-plugin 插件即可，
> 修复版本为： 2.0.2

我现在是mac os， mpvue版本是 2.0.6，问题依旧

> global未找到，请检查package.json配置，并尝试重新安装node_modules依赖
Module not found: Can't resolve 'global' in '/Users/meow/mywebs/node/grabageClassificationAssistant/dist/my'
(undefined) ./common/manifest.js

**Comment by zmisgod** [comment]
> > mac os 一直有这个问题：Module not found: Can't resolve 'global'
> > 重新安装 webpack-mpvue-vendor-plugin 插件即可，
> > 修复版本为： 2.0.2
> 
> 我现在是mac os， mpvue版本是 2.0.6，问题依旧
> 
> > global未找到，请检查package.json配置，并尝试重新安装node_modules依赖
> > Module not found: Can't resolve 'global' in '/Users/meow/mywebs/node/grabageClassificationAssistant/dist/my'
> > (undefined) ./common/manifest.js

---------------------------

已解决，将webpack-mpvue-vendor-plugin包强制更新成2.0.2版本解决。
`npm i webpack-mpvue-vendor-plugin@2.0.2`
