### ISSUE TITLE
mpvue2.0 windows10 cli没法生成app.json文件

### ISSUE THREAD

**Issue by yudaming** [Meituan-Dianping/mpvue#1402]
代码下载：
[my-project.zip](https://github.com/Meituan-Dianping/mpvue/files/2878207/my-project.zip)
## [问题简单描述]
win10-64 按照这个步骤生成不了 小程序的Json文件 没有error信息
https://github.com/Meituan-Dianping/mpvue/releases/tag/2.0.0

**问题复现步骤：**
本地 node npm 版本
node:11.10.0
npm: 6.7.0
之前10.15也不行升级到11也不行

**Comment by yudaming** [comment]
貌似是因为中文路径的问题

**Comment by Michel-Yang** [comment]
全英文路径，遇到同样问题

**Comment by wuzhifeibuhuifei** [comment]
> 
> 
> 代码下载：
> [my-project.zip](https://github.com/Meituan-Dianping/mpvue/files/2878207/my-project.zip)
> ## [问题简单描述]
> 
> win10-64 按照这个步骤生成不了 小程序的Json文件 没有error信息
> https://github.com/Meituan-Dianping/mpvue/releases/tag/2.0.0
> 
> **问题复现步骤：**
> 本地 node npm 版本
> node:11.10.0
> npm: 6.7.0
> 之前10.15也不行升级到11也不行

请问这个问题已经解决了吗
