### ISSUE TITLE
Resolve error: Cannot read property 'platform' of undefined

### ISSUE THREAD

**Issue by KokoTa** [Meituan-Dianping/mpvue#1404]
![image](https://user-images.githubusercontent.com/14892053/52993267-9c8b9e80-344e-11e9-96c0-2841f773c6aa.png)
引入组件时报该错误，请问这是什么问题？将 eslintrc 删除后，编译可以正常执行。

**Comment by rchunping** [comment]
也遇到了， 升级到 1.0.19 1.0.20 就出现这个无法编译

**Comment by hucq** [comment]
eslint 规则的问题，随手修复一下即可。
可以参考最新的 quickstart 项目中 .eslintrc.js 配置。
或者直接参考：[.eslintrc.js](https://github.com/mpvue/mpvue-quickstart/blob/master/template/.eslintrc.js#L40)
