### ISSUE TITLE
npm build 小程序工具报错

### ISSUE THREAD

**Issue by zhangzilong1992** [Meituan-Dianping/mpvue#1405]
## [问题简单描述]
开发环境没有任何问题，正式上线前打包npm build，小程序开发工具报错

**问题复现步骤：**

1. [第一步]

npm build 打包

2. [第二步]
3. [其他步骤...]

**期望的表现：**

期望表现正常

**观察到的表现：**

[在这里描述观察到的表现]

**屏幕截图或动态图：**
![0 0 xj2 ur2 ul b9qtd](https://user-images.githubusercontent.com/33406752/52998502-67874800-345e-11e9-9eb0-40b7ee658559.png)

![jp 1gr kzin gf12dqd 17](https://user-images.githubusercontent.com/33406752/52998537-7f5ecc00-345e-11e9-9c79-4db1704b67ac.png)

![复现步骤的屏幕截图和动态 GIF 图](图片的 url)
[建议提供可运行的demo]

**Comment by hucq** [comment]
开发者工经常会有这样的问题，尤其涉及到文件目录重建的时候。通常重新打开一下项目即可。

**Comment by zhangzilong1992** [comment]
> 开发者工经常会有这样的问题，尤其涉及到文件目录重建的时候。通常重新打开一下项目即可。

不仅仅是开发工具报错，真机调试也报错，上传后也依旧打不开

**Comment by zhangzilong1992** [comment]
> 开发者工经常会有这样的问题，尤其涉及到文件目录重建的时候。通常重新打开一下项目即可。

已经定位原因，是因为lodash导致的
