### ISSUE TITLE
mpvue 2.0.x 默认配置不生成sourcemap了?

### ISSUE THREAD

**Issue by smoothdvd** [Meituan-Dianping/mpvue#1409]
## [问题简单描述]
mpvue 2.0.x 默认配置在开发模式下用微信开发者工具运行时无法找到sourcemap

**问题复现步骤：**

1. [第一步]
yarn dev:wx

**期望的表现：**
可以通过sourcemap定位到源文件并调试

**Comment by hucq** [comment]
在配置文件中开启即可，位置参见：[webpack.dev.conf.js](https://github.com/mpvue/mpvue-quickstart/blob/master/template/build/webpack.dev.conf.js#L30)

```
  // devtool: '#source-map',
```

**Comment by smoothdvd** [comment]
@hucq 这行去掉注释之后运行yarn dev:wx:
```
/Dev/app-mpvue2/node_modules/webpack/lib/SourceMapDevToolPlugin.js:37
                sourceMap = asset.map(options);
                                  ^

TypeError: asset.map is not a function
```

**Comment by hucq** [comment]
请升级一下 
```
yarn add webpack-mpvue-vendor-plugin@2.0.1
```

**Comment by smoothdvd** [comment]
@hucq 可以了

**Comment by jytx** [comment]
> 请升级一下
> 
> ```
> yarn add webpack-mpvue-vendor-plugin@2.0.1
> ```

生成sourceMap不正确要怎么解决

**Comment by spiritelf** [comment]
您好，您有没有遇到过微信开发工具里断点设置不准的情况，比如说点击选择“28”行，实际上跑到“30”行的这种情况？
现在mpvue 2.0里没有webpack那个文件夹了。
