### ISSUE TITLE
以字符串为 slot 插入时，报 template not found。

### ISSUE THREAD

**Issue by blade254353074** [Meituan-Dianping/mpvue#141]
**问题复现步骤:**

![code-1](https://user-images.githubusercontent.com/9346008/37652393-5da321f6-2c76-11e8-90ef-7a262a9dd4ae.png)
![code-2](https://user-images.githubusercontent.com/9346008/37652332-20ad238c-2c76-11e8-8702-ff00fac721c7.png)

**期望的表现:**

不报错

**观察到的表现:**

报错
![image](https://user-images.githubusercontent.com/9346008/37652136-7f565b8e-2c75-11e8-86d7-34f4bfb6cd25.png)

**Comment by anchengjian** [comment]
暂时无法复现

![image](https://user-images.githubusercontent.com/8679331/37660771-24114234-2c8e-11e8-96a6-6d1aae820591.png)

**Comment by blade254353074** [comment]
我也不知道为什么，因为用 String 作为 slot 之前是用过的，没有问题。

**Comment by blade254353074** [comment]
所以你看是我写法有问题呢，还是其他原因。
需要其他信息的话和我说。

**Comment by anchengjian** [comment]
单纯的看你贴出来的代码，找不出问题

**Comment by F-loat** [comment]
更新下版本试试，我更新后就没这个问题了
