### ISSUE TITLE
在app.vue的onLaunch中判断用户是否登录，没有登录则跳转到登录页面，但是现在在onLaunch中无法进行页面跳转，是否是因为在onLaunch中页面还没有注册？请问怎么处理这个非常常用的功能

### ISSUE THREAD

**Issue by jiutianxuannan** [Meituan-Dianping/mpvue#1410]
## [问题简单描述]

**问题复现步骤：**

1. [第一步]
2. [第二步]
3. [其他步骤...]

**期望的表现：**

[在这里描述期望的表现]

**观察到的表现：**

[在这里描述观察到的表现]

**屏幕截图或动态图：**

![复现步骤的屏幕截图和动态 GIF 图](图片的 url)
[建议提供可运行的demo]

**Comment by Holmeshaw** [comment]
在onLaunch里好像只能用 wx.reLaunch 跳转页面。

**Comment by hucq** [comment]
你判断的对，小程序 app 和 page 的生命周期有先后顺序，官网有说明，你的时机不对。
