### ISSUE TITLE
头条小程序开发工具不能打开文件并使用

### ISSUE THREAD

**Issue by 17610776808** [Meituan-Dianping/mpvue#1412]
## [问题简单描述]

**问题复现步骤：**

1. [第一步]
2. [第二步]
3. [其他步骤...]

**期望的表现：**

[在这里描述期望的表现]

**观察到的表现：**

[在这里描述观察到的表现]

**屏幕截图或动态图：**

![复现步骤的屏幕截图和动态 GIF 图](图片的 url)
[建议提供可运行的demo]

**Comment by 17610776808** [comment]
npm run dev:tt后,用头条开发者工具打不开安装的目录

**Comment by 17610776808** [comment]
@Dewyzee 微信开发者工具可以打开安装目录,并使用,看到页面效果, 头条开发者工具不能
![image](https://user-images.githubusercontent.com/42405527/53142302-5bba9380-35ce-11e9-8903-f95051a6c4ab.png)

**Comment by watsonhaw** [comment]
@fistSea 是导入dist下的tt文件，你这个是新建工程了，鹅的天啊~
