### ISSUE TITLE
webpack getEntry 函数建议修改

### ISSUE THREAD

**Issue by cokeknight** [Meituan-Dianping/mpvue#1413]
## [问题简单描述]
function getEntry (rootSrc) {
  var map = {}
  glob.sync(rootSrc + '/pages/**/index.js')
    .forEach(file => {
      var key = relative(rootSrc, file).replace('.js', '')
      map[key] = file
    })
  return map
}

const appEntry = { app: resolve(`./src/main.${process.env.PLATFORM}.js`) }
const pagesEntry = getEntry(resolve('./src'), 'pages/**/index.js')
你们这个getEntry 第二个参数根本没用到啊
**问题复现步骤：**

1. [第一步]
2. [第二步]
3. [其他步骤...]

**期望的表现：**

[在这里描述期望的表现]

**观察到的表现：**

[在这里描述观察到的表现]

**屏幕截图或动态图：**

![复现步骤的屏幕截图和动态 GIF 图](图片的 url)
[建议提供可运行的demo]

**Comment by hucq** [comment]
感谢你的建议。
