### ISSUE TITLE
头条小程序的问题

### ISSUE THREAD

**Issue by 17610776808** [Meituan-Dianping/mpvue#1414]
![image](https://user-images.githubusercontent.com/42405527/53148287-2e2d1480-35e5-11e9-9575-16280a874c08.png)

**Comment by 17610776808** [comment]
![image](https://user-images.githubusercontent.com/42405527/53148321-4dc43d00-35e5-11e9-858f-0ff1c574e575.png)

**Comment by answer-huang** [comment]
目录指定到 my-project/dist/tt 下试试, 记得先 build .

**Comment by 17610776808** [comment]
@answer-huang 一样的问题,

**Comment by hucq** [comment]
使用姿势的问题：
已经构建出项目了，使用导入项目，而不是新建项目。
