### ISSUE TITLE
v-for的:key怎么设置使其不按照索引index排序，需要按照id排序

### ISSUE THREAD

**Issue by shihaha** [Meituan-Dianping/mpvue#1417]
如下是v-for的目标数组：
`let arr = [{id: "0", name: "a"},{id: "2", name: "c"},{id: "1", name: "b"}]`
在html中使用如下写法来遍历上面的数组：
`v-for="item in arr" :key="item.id"`
正确的结果应该按照id来排序，应该显示a，b，c
但是实际还是按照索引index排序的，得到的结果是a，c，b
请问应该怎么写？

**Comment by cnyyk** [comment]
问题不在 v-for，在你的数据。提供数据的时候就应该排好序
