### ISSUE TITLE
mpvue2.0支持webpack4吗？

### ISSUE THREAD

**Issue by pantt** [Meituan-Dianping/mpvue#1418]
## [问题简单描述]
升级webpack4报错，一直解决不了,mpvue是2.0.2最新版了
![default](https://user-images.githubusercontent.com/44255498/53234964-b259c780-36cb-11e9-8f84-f803c70a3f66.png)

**问题复现步骤：**

1. [第一步]
2. [第二步]
3. [其他步骤...]

**期望的表现：**

[在这里描述期望的表现]

**观察到的表现：**

[在这里描述观察到的表现]

**屏幕截图或动态图：**

![复现步骤的屏幕截图和动态 GIF 图](图片的 url)
[建议提供可运行的demo]

**Comment by hucq** [comment]
并未对 webpack 4 做适配。
