### ISSUE TITLE
demo打包到支付宝小程序报错

### ISSUE THREAD

**Issue by ayafree** [Meituan-Dianping/mpvue#1419]
![image](https://user-images.githubusercontent.com/28883143/53236731-f4850800-36cf-11e9-8db0-92717ab672f3.png)

**Comment by Dewyzee** [comment]
@ayafree 尝试把webpack-mpvue-vondor-plugin升级到最新版本试试呢？

**Comment by ayafree** [comment]
> @ayafree 尝试把webpack-mpvue-vondor-plugin升级到最新版本试试呢？

已经是最新版本了，还是不行

**Comment by ayafree** [comment]
> @ayafree 尝试把webpack-mpvue-vondor-plugin升级到最新版本试试呢？

换成2.0.1就没有这个错误
