### ISSUE TITLE
Canvas 元素部分事件不支持

### ISSUE THREAD

**Issue by F-loat** [Meituan-Dianping/mpvue#142]
touchstart, touchmove, touchend, touchcancel, longpress 这几个事件绑定在 canvas 元素上不生效，click, tap 等是可以的，上述 canvas 不支持的事件其他元素是支持的

**Comment by 252860883** [comment]
今天也发现了这个问题

**Comment by JoshuaYang** [comment]
+1

**Comment by aOrz** [comment]
预计今晚发版修复 https://github.com/Meituan-Dianping/mpvue/commit/855cd589f4d4d63823bf754ef88af2d4928925f5

**Comment by aOrz** [comment]
已修复，见：https://github.com/Meituan-Dianping/mpvue/releases/tag/1.0.7
