### ISSUE TITLE
关于mpvue2.0.0打包后dist无法生成app.json

### ISSUE THREAD

**Issue by zcwcsj** [Meituan-Dianping/mpvue#1421]
window7下mpvue2.0.0打包后dist无法生成app.json。试过把mpvue-loader：“2.0.0”，"miniprogramRoot": "dist/wx/",都不行。路径没有没有中文路径

**Comment by Michel-Yang** [comment]
楼主是否解决。我也遇到同样的问题

**Comment by qzmly100** [comment]
这个问题关闭了？还是已经解决？

**Comment by wuzhifeibuhuifei** [comment]
楼主这个问题解决了吗，怎么没有人回答了呢，这个问题应该挺常见吧

**Comment by wuzhifeibuhuifei** [comment]
> 
> 
> 楼主是否解决。我也遇到同样的问题



> 
> 
> window7下mpvue2.0.0打包后dist无法生成app.json。试过把mpvue-loader：“2.0.0”，"miniprogramRoot": "dist/wx/",都不行。路径没有没有中文路径

你好，请问这个问题你解决了吗

**Comment by zcwcsj** [comment]
没有人告诉我怎么解决的。这是练习用的时间太久了我也忘记自己是怎么搞定的了。而且现在我公司都不用这个

**Comment by zcwcsj** [comment]
自己整的我忘记了好早之前了




------------------ 原始邮件 ------------------
发件人: "wuzhifeibuhuifei"<notifications@github.com>; 
发送时间: 2019年8月29日(星期四) 下午4:54
收件人: "Meituan-Dianping/mpvue"<mpvue@noreply.github.com>; 
抄送: "过"<604535486@qq.com>; "State change"<state_change@noreply.github.com>; 
主题: Re: [Meituan-Dianping/mpvue] 关于mpvue2.0.0打包后dist无法生成app.json (#1421)




楼主这个问题解决了吗，怎么没有人回答了呢，这个问题应该挺常见吧

**Comment by zcwcsj** [comment]
是在不行就自己手动写一个




------------------ 原始邮件 ------------------
发件人: "wuzhifeibuhuifei"<notifications@github.com>; 
发送时间: 2019年8月29日(星期四) 下午4:54
收件人: "Meituan-Dianping/mpvue"<mpvue@noreply.github.com>; 
抄送: "过"<604535486@qq.com>; "State change"<state_change@noreply.github.com>; 
主题: Re: [Meituan-Dianping/mpvue] 关于mpvue2.0.0打包后dist无法生成app.json (#1421)



 
楼主是否解决。我也遇到同样的问题
   
window7下mpvue2.0.0打包后dist无法生成app.json。试过把mpvue-loader：“2.0.0”，"miniprogramRoot": "dist/wx/",都不行。路径没有没有中文路径
  
你好，请问这个问题你解决了吗

**Comment by wuzhifeibuhuifei** [comment]
感谢楼主这么早的问题还来回答一下，找到原因了，是因为2.0版本取消了自动生成app.json
