### ISSUE TITLE
bugfix 1375 后遗症

### ISSUE THREAD

**Issue by Beven91** [Meituan-Dianping/mpvue#1425]
## [问题简单描述]

首先非常感谢你们出色的工作，最近在升级到2.0.0以后，发现了一个问题，

该问题属于在[`bugfix1375`](https://github.com/Meituan-Dianping/mpvue/issues/1375) 后产生的问题，

请看以下部分代码

```js
 // bugfix #1375: 虚拟dom的compid和真实dom的comkey在组件嵌套时匹配出错，comid会丢失前缀，需要从父节点补充
  let comkey = keys.join(KEY_SEP)
  let comidPrefix = ''
  return keys.reduce((res, key) => {
    const len = res.$children.length
    for (let i = 0; i < len; i++) {
      const v = res.$children[i]
      let k = getComKey(v)
      if (comidPrefix) {
        k = comidPrefix + KEY_SEP + k
      }
      // 找到匹配的父节点
      if (comkey.indexOf(k) === 0) {
        comidPrefix = k
        res = v
        return res
      }
    }
    return res
  }, vm)
```
其中
```js
comkey.indexOf(k) === 0
```
这个判断无法覆盖到，以下情况：
> 在for循环中，如果总项大于10，那么会产生以下部分重叠的
*  data-comkey=`0_0_1` 与 data-comkey=`0_0_10` 
*  data-comkey=`0_0_1` 与 data-comkey=`0_0_11` 
*  data-comkey=`0_0_1` 与 data-comkey=`0_0_12`
*  data-comkey=`0_0_2` 与 data-comkey=`0_0_20`
... 等等

如果原本是 点击 data-comkey='0_0_10' 实际获取到的`vm` 是data-comkey='0_0_1'

**问题复现步骤：**

*  使用vue-cli创建一个mpvue模板工程
```
 vue init mpvue/mpvue-quickstart my-project
```

* 修改模板中的`pages/index/index.vue`
> 添加一个for 循环输出10个以上的`card`组件
```js
users:[
        { name:'钱一'},
        { name:'杜二' },
        { name:'张三' },
        { name:'李四'},
        { name:'王五'},
        { name:'赵六' },
        { name:'李七'},
        { name:'秦八'},
        { name:'杨九' },
        { name:'司徒十'},
        { name:'嵇十一'},
        { name:'萧十二'}
 ],
```
```html
<div class="userinfo-nickname">
    <block v-for="(u,index) in users" :key="index">
        <card :text="u.name"></card>
    </block>
</div>
```

* 修改`component/card.vue`
> 新增内部点击事件
```html
<template>
  <div>
    <p class="card" @click="showText">卡片：{{text}}</p>
  </div>
</template>
<script>
export default {
  props: ['text'],
  methods: {
    showText () {
      // 这里，在点击第10项card，实际的`this`指向的是第数组下标为=1的card
      console.log(this.text);
    }
  }
};
</script>
```

**期望的表现：**

点击卡片(card) 名称为: `嵇十一` 应该在控制台输出`嵇十一`

**观察到的表现：**

点击卡片(card) 名称为: `嵇十一` 实际在控制台输出`杜二`

**Comment by Dewyzee** [comment]
@Beven91 感谢对问题的跟踪与反馈，我们会尽快修复

**Comment by bacy** [comment]
![image](https://user-images.githubusercontent.com/5163569/53310181-bd3c7400-38e6-11e9-90f8-8c56bb08cd5a.png)
这个问题昨天我们线上版本出现了，我稍微改了下源码，把遍历子控件，换成倒序，可以解决这个问题

**Comment by hucq** [comment]
问题修复完毕，请重新安装 mpvue, mpvue-template-compiler，最新版本为 2.0.4

**Comment by Beven91** [comment]
好的，谢谢了。
