### ISSUE TITLE
mpvue2.0版本下配置typescript

### ISSUE THREAD

**Issue by pantt** [Meituan-Dianping/mpvue#1427]
## [问题简单描述]
用之下命令初始化项目以后按照官网配置typescript
# 初始化项目
vue init mpvue/mpvue-quickstart myproject
cd myproject
npm i

然后一直报错：
![default](https://user-images.githubusercontent.com/44255498/53312206-22946300-38ef-11e9-9624-2c3f78eafe4f.png)

检查了下相关文件里有这个配置啊,，

**问题复现步骤：**

1. [第一步]
2. [第二步]
3. [其他步骤...]

**期望的表现：**

[在这里描述期望的表现]

**观察到的表现：**

[在这里描述观察到的表现]

**屏幕截图或动态图：**

![复现步骤的屏幕截图和动态 GIF 图](图片的 url)
[建议提供可运行的demo]

**Comment by Beven91** [comment]
请问，是怎么启动的，会不会是启动的platform没有适配?

**Comment by rchunping** [comment]
文档过时了，修改一下就能用

```javascript
// ts文件的loader
      {
        test: /\.tsx?$/, 
        exclude: /node_modules/,
        use: [
          'babel-loader',
          {
            loader: 'mpvue-loader',
            options: {
              checkMPEntry: true
             ,fileExt: config.build.fileExt  // 加上这个！！！
            }
          },
          {
            // loader: 'ts-loader',
            loader: 'awesome-typescript-loader',
            options: {
              // errorsAsWarnings: true,
              useCache: true,
            }
          }
        ]
      },
```

**Comment by pantt** [comment]
> 
> 
> 文档过时了，修改一下就能用
> 
> vue-loader.conf.js 加上下面这段
> 
> ```js
> ts: [ //添加对应vue的loader
>     'babel-loader',
>     {
>       // loader: 'ts-loader',
>       loader: 'awesome-typescript-loader',
>       options: {
>         // errorsAsWarnings: true,
>         useCache: true,
>       }
>     }
>   ]
> ```
> 
> webpack.base.conf.js 修改一行
> 
> ```js
> // ts文件的loader
>       {
>         test: /\.tsx?$/, 
>         exclude: /node_modules/,
>         use: [
>           'babel-loader',
>           {
>             loader: 'mpvue-loader',
>             options: {
>               checkMPEntry: true
>              ,fileExt: config.build.fileExt  // 加上这个！！！
>             }
>           },
>           {
>             // loader: 'ts-loader',
>             loader: 'awesome-typescript-loader',
>             options: {
>               // errorsAsWarnings: true,
>               useCache: true,
>             }
>           }
>         ]
>       },
> ```

感谢感谢，就是webpack.base.conf.js 里面没加那一行，加上就行了谢谢大大么么哒！~~

**Comment by pantt** [comment]
> 
> 
> 请问，是怎么启动的，会不会是启动的platform没有适配?

按照楼下说的就好了，就因为没加一行配置

**Comment by pantt** [comment]
又出现问题了，虽然按照官网配置编译通过了，但是将src中的文件全部改成ts的时候又报错了，
估计还是没配好，
报错如下
<img width="771" alt="image" src="https://user-images.githubusercontent.com/44255498/53327066-fe9e4500-3921-11e9-9e9b-4babc11864c3.png">
package.json中的信息如下：
<img width="380" alt="image" src="https://user-images.githubusercontent.com/44255498/53327192-47ee9480-3922-11e9-9aaf-6c1c7c3dc3a8.png">
<img width="380" alt="image" src="https://user-images.githubusercontent.com/44255498/53327207-4f15a280-3922-11e9-8fb0-c0aa1d37bbbf.png">
请各位大大帮忙看一下，自己捣鼓好几天了都木有配好，头皮发麻

**Comment by hucq** [comment]
ts 辛苦自行配置解决吧。

**Comment by rchunping** [comment]
@pantt 

你先精简到一个页面，然后放github上来，我看看有啥问题。

我这里几个mpvue项目用typescript都没问题

**Comment by gatspy** [comment]
没有types吗 mpvue.switchTab怎么引入呢?
