### ISSUE TITLE
使用支付宝小程序开发工具运行npm run dev:my 报Cannot read property 'newPage' of undefined

### ISSUE THREAD

**Issue by mooseChan21** [Meituan-Dianping/mpvue#1429]
电脑系统: win7

**Comment by Dewyzee** [comment]
@mooseChan21 辛苦确认下mpvue版本号呢

**Comment by mooseChan21** [comment]
版本号为2.0.0，在main.js中全局引入vuex后 并把store传入到new Vue (store)后，启动支付宝小程序运行报Cannot read property 'newPage' of undefined
> @mooseChan21 辛苦确认下mpvue版本号呢

**Comment by Dewyzee** [comment]
重新安装 webpack-mpvue-vendor-plugin 插件即可，
修复版本为： 2.0.2
[](url)

**Comment by Dewyzee** [comment]
重新安装 webpack-mpvue-vendor-plugin 插件,最新版本2.0.2

**Comment by Dewyzee** [comment]
@mooseChan21 采用vuex我们验证不存在你所描述的问题。先尝试将webpack-mpvue-vendor-plugin版本升至最新试试，最新版本2.0.2

**Comment by weikeduoppp** [comment]
从老版本升级过来, 也发现这样的错误, 已是最新版本2.0.2
![tim 20190226143554](https://user-images.githubusercontent.com/29790122/53392340-0ae2da80-39d4-11e9-9244-a8009f0242ef.png)

**Comment by wxl1225015** [comment]
> 版本号为2.0.0，在main.js中全局引入vuex后 并把store传入到new Vue (store)后，启动支付宝小程序运行报Cannot read property 'newPage' of undefined
> 
> > @mooseChan21 辛苦确认下mpvue版本号呢



> @mooseChan21 辛苦确认下mpvue版本号呢

今天通过mpvue-quickstart创建的脚手架，通过npm run dev:my打包完成后，在支付宝开发工具运行，结果，出现了如下的错误，mpvue，mpvue-template-compiler都是2.0.3，webpack-mpvue-vendor-plugin根据您之前的回复改为了2.0.2，但是还是报第一位老哥提出的问题Cannot read property 'AFAppX' of undefined和Cannot read property 'newPage' of undefined，请尽快解答，领导催的很急

**Comment by Dewyzee** [comment]
@wxl1225015 系统环境是windows？

**Comment by wxl1225015** [comment]
Win7 64位

**Comment by wxl1225015** [comment]
> @wxl1225015 系统环境是windows？

系统环境win7 64位，node版本是8.9.0，vue版本2.9.2

**Comment by mooseChan21** [comment]
> webpack-mpvue-vendor-plugin

webpack-mpvue-vendor-plugin 安装2.0.1  可以解决Cannot read property 'AFAppX' of undefined ，vuex 挂载到Vue.prototype.$store = store 另外 const app = new Vue(App) 这里不要写store进去  可以解决Cannot read property 'newPage' of undefined

**Comment by wxl1225015** [comment]
> const app = new Vue(App)

webpack-mpvue-vendor-plugin 昨天已安装2.0.1，但还是会出现这个问题，至于您说的store的问题，我都没安装vuex，是不是2.0以后必须得安装vuex

**Comment by mooseChan21** [comment]
> > const app = new Vue(App)
> 
> webpack-mpvue-vendor-plugin 昨天已安装2.0.1，但还是会出现这个问题，至于您说的store的问题，我都没安装vuex，是不是2.0以后必须得安装vuex

你把整个node_modules删除了 再安装一遍吧  我这边按照我上面说的方法几个平台都是没问题的

**Comment by wxl1225015** [comment]
> > > const app = new Vue(App)
> > 
> > 
> > webpack-mpvue-vendor-plugin 昨天已安装2.0.1，但还是会出现这个问题，至于您说的store的问题，我都没安装vuex，是不是2.0以后必须得安装vuex
> 
> 你把整个node_modules删除了 再安装一遍吧 我这边按照我上面说的方法几个平台都是没问题的

老哥问您下，webpack-mpvue-vendor-plugin您是直接在package,json直接改的版本号，然后在install的么，我这边删除后再装还是有问题

**Comment by mooseChan21** [comment]
> > > > const app = new Vue(App)
> > > 
> > > 
> > > webpack-mpvue-vendor-plugin 昨天已安装2.0.1，但还是会出现这个问题，至于您说的store的问题，我都没安装vuex，是不是2.0以后必须得安装vuex
> > 
> > 
> > 你把整个node_modules删除了 再安装一遍吧 我这边按照我上面说的方法几个平台都是没问题的
> 
> 老哥问您下，webpack-mpvue-vendor-plugin您是直接在package,json直接改的版本号，然后在install的么，我这边删除后再装还是有问题

我是npm install webpack-mpvue-vendor-plugin@2.0.1 --save-dev 就会替换掉原来的2.0.2版本了

**Comment by wxl1225015** [comment]
> > > > > const app = new Vue(App)
> > > > 
> > > > 
> > > > webpack-mpvue-vendor-plugin 昨天已安装2.0.1，但还是会出现这个问题，至于您说的store的问题，我都没安装vuex，是不是2.0以后必须得安装vuex
> > > 
> > > 
> > > 你把整个node_modules删除了 再安装一遍吧 我这边按照我上面说的方法几个平台都是没问题的
> > 
> > 
> > 老哥问您下，webpack-mpvue-vendor-plugin您是直接在package,json直接改的版本号，然后在install的么，我这边删除后再装还是有问题
> 
> 我是npm install webpack-mpvue-vendor-plugin@2.0.1 --save-dev 就会替换掉原来的2.0.2版本了

终于可以了，老哥十分感谢！！

**Comment by mooseChan21** [comment]
> > > > > > const app = new Vue(App)
> > > > > 
> > > > > 
> > > > > webpack-mpvue-vendor-plugin 昨天已安装2.0.1，但还是会出现这个问题，至于您说的store的问题，我都没安装vuex，是不是2.0以后必须得安装vuex
> > > > 
> > > > 
> > > > 你把整个node_modules删除了 再安装一遍吧 我这边按照我上面说的方法几个平台都是没问题的
> > > 
> > > 
> > > 老哥问您下，webpack-mpvue-vendor-plugin您是直接在package,json直接改的版本号，然后在install的么，我这边删除后再装还是有问题
> > 
> > 
> > 我是npm install webpack-mpvue-vendor-plugin@2.0.1 --save-dev 就会替换掉原来的2.0.2版本了
> 
> 终于可以了，老哥十分感谢！！
不客气
