### ISSUE TITLE
百度小程序，数据变更后，视图层没有更新。

### ISSUE THREAD

**Issue by yinshanhu** [Meituan-Dianping/mpvue#1430]
## [问题简单描述]
百度小程序，数据变更后，视图层没有更新。
**问题复现步骤：**

1. 安装 mpvue-quickstart 官方demo，并安装依赖。

2. 原有index.vue 页面内新增一个标签，并绑定事件：**<switch @change="changeEvt"></switch>**

3.在原有的表单标签上绑定 v-show="showFlag" ：<form class="form-container" **v-show="showFlag"**>

4. data(){} 方法内注册变量：**showFlag : true**

5.新增methods：
   **changeEvt(){
      this.showFlag = !this.showFlag;
      console.log(this.showFlag);
    }**

**期望的表现：**

重复点击switch按钮，form标签下的内容随之显隐。

**观察到的表现：**

第一次隐藏了，之后不再显示。

**屏幕截图或动态图：**

1. 初始页面
![image](https://user-images.githubusercontent.com/47800953/53384885-6c488080-39b7-11e9-8028-5fe8305d5783.png)

2. 点击 switch
![image](https://user-images.githubusercontent.com/47800953/53384906-81251400-39b7-11e9-93d5-6a3acd197cec.png)

3.再点击switch
![image](https://user-images.githubusercontent.com/47800953/53384565-525a6e00-39b6-11e9-8674-bea6287c8ad0.png)

## 下面是index.vue页面的完整代码

```javascript
<template>
  <div @click="clickHandle">

    <div class="userinfo" @click="bindViewTap">
      <img class="userinfo-avatar" v-if="userInfo.avatarUrl" :src="userInfo.avatarUrl" background-size="cover" />
      <img class="userinfo-avatar" src="/static/images/user.png" background-size="cover" />

      <div class="userinfo-nickname">
        <card :text="userInfo.nickName"></card>
      </div>
    </div>

    <div class="usermotto">
      <div class="user-motto">
        <card :text="motto"></card>
      </div>
    </div>

    <switch @change="changeEvt"></switch>

    <form class="form-container" v-show="showFlag">
      <input type="text" class="form-control" :value="motto" placeholder="v-model" />
      <input type="text" class="form-control" v-model="motto" placeholder="v-model" />
      <input type="text" class="form-control" v-model.lazy="motto" placeholder="v-model.lazy" />
    </form>


    <div class="all">
        <div class="left">
        </div>
        <div class="right">
        </div>
    </div>
  </div>
</template>

<script>
import card from '@/components/card'

export default {
  data () {
    return {
      showFlag:true,
      motto: 'Hello miniprograme',
      userInfo: {
        nickName: 'mpvue',
        avatarUrl: 'http://mpvue.com/assets/logo.png'
      }
    }
  },

  components: {
    card
  },

  methods: {
    changeEvt(){
      this.showFlag = !this.showFlag;

      console.log(this.showFlag);
    },
    bindViewTap () {
      const url = '../logs/main'
      if (mpvuePlatform === 'wx') {
        mpvue.switchTab({ url })
      } else {
        mpvue.navigateTo({ url })
      }
    },
    clickHandle (ev) {
      //console.log('clickHandle:', ev)
      // throw {message: 'custom test'}
    }
  },

  created () {
    // let app = getApp()
  }
}
</script>

<style scoped>
.userinfo {
  display: flex;
  flex-direction: column;
  align-items: center;
}

.userinfo-avatar {
  width: 128rpx;
  height: 128rpx;
  margin: 20rpx;
  border-radius: 50%;
}

.userinfo-nickname {
  color: #aaa;
}

.usermotto {
  margin-top: 150px;
}

.form-control {
  display: block;
  padding: 0 12px;
  margin-bottom: 5px;
  border: 1px solid #ccc;
}
.all{
  width:7.5rem;
  height:1rem;
  background-color:blue;
}
.all:after{
  display:block;
  content:'';
  clear:both;
}
.left{
  float:left;
  width:3rem;
  height:1rem;
  background-color:red;
}

.right{
  float:left;
  width:4.5rem;
  height:1rem;
  background-color:green;
}
</style>

```
## 环境

"mpvue": "^2.0.4",
"mpvue-loader": "^2.0.1",
"mpvue-template-compiler": "^2.0.4"

或 

"mpvue": "^2.0.0",
"mpvue-loader": "^2.0.0",
"mpvue-template-compiler": "^2.0.0"

**Comment by fc653074701** [comment]
微信小程序发现同样问题

**Comment by Dewyzee** [comment]
@yinshanhu 我们尽快验证完毕发布，感谢反馈

**Comment by hucq** [comment]
> 微信小程序发现同样问题，数据变更之后视图无法更新。
> `this.$forceUpdate();`也不起作用。`this.$set()`也试过了。。

case 不一样吧，我知道百度小程序实现上是有差异。

**Comment by yinshanhu** [comment]
@hucq 目前能定位是哪里的问题吗？

**Comment by hucq** [comment]
升级到 2.0.5 即可

```
mpvue@2.0.5
mpvue-template-compiler@2.0.5
```

**Comment by yinshanhu** [comment]
六六六 @hucq

**Comment by ccr1002** [comment]
现在我更新为2.0.5以后第一次dev是可以的然后在处理其他页面的业务然后过了一会又会发生视图无法更新的情况必须得把整个dist包删除重新dev才能正常 @hucq

**Comment by cdd111** [comment]
> 升级到 2.0.5 即可
> 
> ```
> mpvue@2.0.5
> mpvue-template-compiler@2.0.5
> ```

更新到2.06在百度小程序还是有问题

**Comment by cdd111** [comment]
> 升级到 2.0.5 即可
> 
> ```
> mpvue@2.0.5
> mpvue-template-compiler@2.0.5
> ```
升级到2.0.6还是更新不了

**Comment by CodingYiyi** [comment]
> > 升级到 2.0.5 即可
> > ```
> > mpvue@2.0.5
> > mpvue-template-compiler@2.0.5
> > ```
> 
> 升级到2.0.6还是更新不了

same issue
