### ISSUE TITLE
视图修改以后，必须npm run dev 才能生效

### ISSUE THREAD

**Issue by qfgyd2004** [Meituan-Dianping/mpvue#1434]
## [问题简单描述]
1、部分页面，修改视图以后 必须重启才生效
2、修改routes 配置，控制台报错
环境： 
mpvue  2.0.0
mpvue-loader 2.0.0

**Comment by hucq** [comment]
很抱歉，不能明白具体问题，辛苦完整描述一下。

**Comment by qfgyd2004** [comment]
@hucq   修改模板，增加标签，删除标签，或者修改表达式，控制台编译完成，开发者工具里不生效，只有npm run dev 才生效，做的太痛苦了一点，每次修改必须重启，说清楚了吗？
