### ISSUE TITLE
微信小程序，数据变更后，视图层没有更新。

### ISSUE THREAD

**Issue by fc653074701** [Meituan-Dianping/mpvue#1435]
## [问题简单描述]

原有老项目，升级2.0之后，微信小程序，数据变更后，视图层没有更新。

**问题复现步骤：**

1、按照升级清单更新依赖项版本，也可使用如下安装命令

依赖升级脚本

`yarn add mpvue@2.0.2 mpvue-template-compiler@2.0.2 mpvue-loader@2.0.0 webpack-mpvue-asset-plugin@2.0.0 webpack-mpvue-vendor-plugin@2.0.0`
2、更新构建脚本
初始化一个新项目
拷贝新项目中的 build ，config 目录到老项目中
拷贝新项目中的 package.json 中 script 指令到老项目中
[上两步可参见](https://github.com/Meituan-Dianping/mpvue/releases/tag/2.0.0)

**期望的表现：**

重复点击按钮，单选样式会切换。

**观察到的表现：**

点击之后数据改变了，视图没有改变。【另外原本左滑可以拖动显示删除操作也因为数据变了视图没变失效了】

**屏幕截图或动态图：**

![image](https://user-images.githubusercontent.com/10204908/53461979-42f22800-3a7d-11e9-8f18-ab21c87090de.png)

我这边是希望可以通过`checked`的不同，来回切换样式的。大致代码如下
`<span class="iconfont icon-xuanze radio" :class="[subItem.checked ? 'icon-xuanzhong active' : '']" @tap="checkSingle(index,subIndex,subItem)"></span>`
如上图所示：打印出来的数据值已被修改，但是视图没有更新。

第一次提问，描述不好希望可以见谅。

**Comment by hucq** [comment]
问题同于 #1430 
请更新如下依赖到 2.0.5 版本即可
```
yarn add mpvue@2.0.5 mpvue-template-compiler@2.0.5
```
