### ISSUE TITLE
打包的时候报错

### ISSUE THREAD

**Issue by ly-lewis** [Meituan-Dianping/mpvue#1442]
报错内容：
[mpvue-loader] need "fileExt" option in file "build/vue-loader.conf.js"，init a new project and copy the directory "build/" to this porject, or just check the "fileExt" option

**Comment by hucq** [comment]
我给的提示很清楚啊：重新初始化一个项目，把构建脚本拷贝过来覆盖一下。
老版本升级是需要升级构建脚本的。
