### ISSUE TITLE
使用mpvue开发小程序，v-for新生成的元素上绑定的事件失效

### ISSUE THREAD

**Issue by shihaha** [Meituan-Dianping/mpvue#1445]
HTML代码如下：

```
  <view
    v-show="!showLoading"
    v-for="(item, index) in cards"
    :key="index"
    class="body-swiper"
    @touchstart="touchstart"
    @touchend="touchend($event, index, item.content.user.id)"
    :style="{'z-index': (10 - index), top: item.top + 'px'}"
    :animation="item.animation">
      <!-- 不相关的内容 -->
  </view>
```
js代码如下：
对ajax接口返回的数据做处理：

```
      for(let i=0;i<res.data.list.length;i++) {
        // 有一些不相关的内容
        let item = {
          content: res.data.list[i],
          top: 18,
          animation: {}
        };
        this.cards.push(item);
        this.showLoading = false;
      }
```
其中`res.data.list`中的数据是每次返回10条，
在初次进入页面时，请求接口的前10条数据循环生成的卡片上是有`touchstart`和`touchend`事件的，
之后的第二个10条中的数据循环生成的卡片元素上的事件就不起作用了

请问应该怎么改？

**Comment by Dewyzee** [comment]
请将mpvue以及mpvue-template-compiler升级至最新版本试试

**Comment by shihaha** [comment]
@Dewyzee 
您好，请问怎么升级mpvue和mpvue-template-compiler
我的package.json内容如下：
`  "scripts": {
    "dev:wx": "node build/dev-server.js wx",
    "start:wx": "npm run dev:wx",
    "build:wx": "node build/build.js wx",
    "dev:swan": "node build/dev-server.js swan",
    "start:swan": "npm run dev:swan",
    "build:swan": "node build/build.js swan",
    "dev:tt": "node build/dev-server.js tt",
    "start:tt": "npm run dev:tt",
    "build:tt": "node build/build.js tt",
    "dev:my": "node build/dev-server.js my",
    "start:my": "npm run dev:my",
    "build:my": "node build/build.js my",
    "dev": "node build/dev-server.js wx",
    "start": "npm run dev",
    "build": "node build/build.js wx"
  },
  "dependencies": {
    "mpvue": "^2.0.0",
    "vuex": "^3.0.1"
  },
  "devDependencies": {
    "axios": "^0.18.0",
    "babel-core": "^6.22.1",
    "babel-loader": "^7.1.1",
    "babel-plugin-transform-runtime": "^6.22.0",
    "babel-preset-env": "^1.3.2",
    "babel-preset-stage-2": "^6.22.0",
    "babel-register": "^6.22.0",
    "chalk": "^2.4.0",
    "connect-history-api-fallback": "^1.3.0",
    "copy-webpack-plugin": "^4.5.1",
    "css-loader": "^0.28.11",
    "cssnano": "^3.10.0",
    "eventsource-polyfill": "^0.9.6",
    "express": "^4.16.3",
    "extract-text-webpack-plugin": "^3.0.2",
    "file-loader": "^1.1.11",
    "friendly-errors-webpack-plugin": "^1.7.0",
    "glob": "^7.1.2",
    "html-webpack-plugin": "^3.2.0",
    "http-proxy-middleware": "^0.18.0",
    "mkdirp": "^0.5.1",
    "mpvue-loader": "^2.0.0",
    "mpvue-template-compiler": "^2.0.0",
    "mpvue-webpack-target": "^1.0.3",
    "node-sass": "^4.11.0",
    "optimize-css-assets-webpack-plugin": "^3.2.0",
    "ora": "^2.0.0",
    "portfinder": "^1.0.13",
    "postcss-loader": "^2.1.4",
    "postcss-mpvue-wxss": "^1.0.0",
    "prettier": "~1.12.1",
    "px2rpx-loader": "^0.1.10",
    "relative": "^3.0.2",
    "rimraf": "^2.6.0",
    "sass-loader": "^7.1.0",
    "semver": "^5.3.0",
    "shelljs": "^0.8.1",
    "uglifyjs-webpack-plugin": "^1.2.5",
    "url-loader": "^1.0.1",
    "vue-style-loader": "^4.1.0",
    "webpack": "^3.11.0",
    "webpack-bundle-analyzer": "^2.2.1",
    "webpack-dev-middleware-hard-disk": "^1.12.0",
    "webpack-merge": "^4.1.0",
    "webpack-mpvue-asset-plugin": "^2.0.0",
    "webpack-mpvue-vendor-plugin": "^2.0.0"
  },
  "engines": {
    "node": ">= 4.0.0",
    "npm": ">= 3.0.0"
  },
  "browserslist": [
    "> 1%",
    "last 2 versions",
    "not ie <= 8"
  ]`

**Comment by Dewyzee** [comment]
npm install mpvue-template-compiler@2.0.6 mpvue@2.0.6

**Comment by shihaha** [comment]
@Dewyzee 
多谢大神的耐心指导，
最后发现问题出在`:style="{'z-index': (10 - index), top: item.top + 'px'}"`这句话里的`(10 - index)`，具体原理还没搞清，欢迎交流

**Comment by imfangli** [comment]
`mpvue-template-compiler@2.0.5 mpvue@2.0.5` 升级到最新后 click 事件无效问题已修复
但是 `v-for` 循环几次，点击事件就会被出发几次

**Comment by wooderpecker** [comment]
升到最新版本还是 触发不了事件

**Comment by Vasilis-wx** [comment]
升到最新版本还是 触发不了事件

**Comment by Vasilis-wx** [comment]
> `mpvue-template-compiler@2.0.5 mpvue@2.0.5` 升级到最新后 click 事件无效问题已修复
> 但是 `v-for` 循环几次，点击事件就会被出发几次

我更新了还是没有用
