### ISSUE TITLE
mpvue里怎么实现自定义tabBar: custom-tab-bar？

### ISSUE THREAD

**Issue by smoothdvd** [Meituan-Dianping/mpvue#1447]
小程序文档：[https://developers.weixin.qq.com/miniprogram/dev/framework/ability/custom-tabbar.html](url)

**Comment by hucq** [comment]
这看起来是要在构建打包环节增加一些配置支持。
后续会考虑在构建脚本上支持一下，短期看，你可以自己写一段构建脚本，将涉及到的配置文件调整成微信要求的目录结构即可。

**Comment by solocao** [comment]
哈哈，希望尽快支持

**Comment by hekui** [comment]
临时解决方法，采用原生写法，在构建时拷贝出来：
1、在src目录创建custom-tab-bar目录，放置原生写法（包括：index.js,index.json,index.wxml,index.wxss文件）。
2、修改/build/webpack.base.conf.js文件中的plugins，增加一个拷贝：
`
   // copy custom-tab-bar
    new CopyWebpackPlugin([
      {
        from: path.resolve(__dirname, '../src/custom-tab-bar'),
        to: path.resolve(config.build.assetsRoot, './custom-tab-bar'),
        ignore: ['.*']
      }
    ])
`

**Comment by jetBn** [comment]
这边有写成的吗？？想看看。

**Comment by jetBn** [comment]
> 临时解决方法，采用原生写法，在构建时拷贝出来：
> 1、在src目录创建custom-tab-bar目录，放置原生写法（包括：index.js,index.json,index.wxml,index.wxss文件）。
> 2、修改/build/webpack.base.conf.js文件中的plugins，增加一个拷贝：
> 
> ```js
>    // copy custom-tab-bar
>     new CopyWebpackPlugin([
>       {
>         from: path.resolve(__dirname, '../src/custom-tab-bar'),
>         to: path.resolve(config.build.assetsRoot, './custom-tab-bar'),
>         ignore: ['.*']
>       }
>     ])
> ```

能问下切换的时候有bug怎么处理的

**Comment by hekui** [comment]
> > 临时解决方法，采用原生写法，在构建时拷贝出来：
> > 1、在src目录创建custom-tab-bar目录，放置原生写法（包括：index.js,index.json,index.wxml,index.wxss文件）。
> > 2、修改/build/webpack.base.conf.js文件中的plugins，增加一个拷贝：
> > ```js
> >    // copy custom-tab-bar
> >     new CopyWebpackPlugin([
> >       {
> >         from: path.resolve(__dirname, '../src/custom-tab-bar'),
> >         to: path.resolve(config.build.assetsRoot, './custom-tab-bar'),
> >         ignore: ['.*']
> >       }
> >     ])
> > ```
> 
> 能问下切换的时候有bug怎么处理的

什么bug？是选中状态不对么？  
选中状态的话，这个是跟 `mpvue` 无关的，  
1、本身 `tabBar` 是在每个页面是单独的实例  
2、设置选中态的方法是在 `tabBar` 对应页面设置：
```javascript
// 类似这样
  onShow () {
    if (typeof this.getTabBar === 'function' && this.getTabBar()) {
      this.getTabBar().setData({
        selected: 'index'
      })
    }
  },
```

**Comment by jetBn** [comment]
> > > 临时解决方法，采用原生写法，在构建时拷贝出来：
> > > 1、在src目录创建custom-tab-bar目录，放置原生写法（包括：index.js,index.json,index.wxml,index.wxss文件）。
> > > 2、修改/build/webpack.base.conf.js文件中的plugins，增加一个拷贝：
> > > ```js
> > >    // copy custom-tab-bar
> > >     new CopyWebpackPlugin([
> > >       {
> > >         from: path.resolve(__dirname, '../src/custom-tab-bar'),
> > >         to: path.resolve(config.build.assetsRoot, './custom-tab-bar'),
> > >         ignore: ['.*']
> > >       }
> > >     ])
> > > ```
> > 
> > 
> > 能问下切换的时候有bug怎么处理的
> 
> 什么bug？是选中状态不对么？
> 选中状态的话，这个是跟 `mpvue` 无关的，
> 1、本身 `tabBar` 是在每个页面是单独的实例
> 2、设置选中态的方法是在 `tabBar` 对应页面设置：
> 
> ```js
> // 类似这样
>   onShow () {
>     if (typeof this.getTabBar === 'function' && this.getTabBar()) {
>       this.getTabBar().setData({
>         selected: 'index'
>       })
>     }
>   },
> ```

就是跳转使用的switchTab好像会有问题

**Comment by jetBn** [comment]
this.getTabBar()获取不到

**Comment by hekui** [comment]
多看下官方文档和示例，肯定是没问题的。注意下：  
1、配置好 `app.json`  
2、`this.getTabBar() ` 是在 `tabBar` 所在的***页面***使用。

**Comment by jetBn** [comment]
方法是有不过是在$mp.page里

**Comment by heidaren0000** [comment]
> 方法是有不过是在$mp.page里

老哥一句话把我点醒了, 优秀
