### ISSUE TITLE
小程序页面内调用 this.getTabBar 获取 tabBar 实例方法失效

### ISSUE THREAD

**Issue by YogaLin** [Meituan-Dianping/mpvue#1449]
## [调用 this.getTabBar 方法获取 tabBar 实例失败]
微信文档中：
【每个 tab 页下的自定义 tabBar 组件实例是不同的，可通过自定义组件下的 getTabBar 接口，获取当前页面的自定义 tabBar 组件实例。】
https://developers.weixin.qq.com/miniprogram/dev/framework/ability/custom-tabbar.html?search-key=getTabBar

官方例子：
```
Component({
  pageLifetimes: {
    show() {
      if (typeof this.getTabBar === 'function' &&
        this.getTabBar()) {
        this.getTabBar().setData({
          selected: 0
        })
      }
    }
  }
})
```

如何在 mpvue 的 page 里调用这个 getTabBar 获取 tabBar 实例呢？

**Comment by solocao** [comment]
本来我也想做自定义tab导航的，感觉在mpvue中是实现不了了，现在不支持吧。只能手动修改mpvue编译后的文件了。

**Comment by smoothdvd** [comment]
@solocao 我改了一下不能切换tab啊。可以分享一下你怎么改的？

**Comment by YogaLin** [comment]
> @solocao 我改了一下不能切换tab啊。可以分享一下你怎么改的？

可以

> 本来我也想做自定义tab导航的，感觉在mpvue中是实现不了了，现在不支持吧。只能手动修改mpvue编译后的文件了。

手动修改后page页面不能调用 this.getTabBar 方法，页面的 tabBar 实例会重新生成，选择的tab会变回去默认的。

**Comment by YogaLin** [comment]
> @solocao 我改了一下不能切换tab啊。可以分享一下你怎么改的？

大概意思是手动写一个文件夹在根目录叫 custom-tab-bar ，然后 app.json 里，tabBar -> custorm 配置为 true，具体参考

**Comment by smoothdvd** [comment]
@YogaLin 我试过了，就是不能切换，因为不知道怎么把这段代码
```
Component({
  pageLifetimes: {
    show() {
      if (typeof this.getTabBar === 'function' &&
        this.getTabBar()) {
        this.getTabBar().setData({
          selected: 0
        })
      }
    }
  }
})
```
里的pageLifetimes放在mpvue哪里

**Comment by YogaLin** [comment]
> @YogaLin 我试过了，就是不能切换，因为不知道怎么把这段代码
> 
> ```
> Component({
>   pageLifetimes: {
>     show() {
>       if (typeof this.getTabBar === 'function' &&
>         this.getTabBar()) {
>         this.getTabBar().setData({
>           selected: 0
>         })
>       }
>     }
>   }
> })
> ```
> 里的pageLifetimes放在mpvue哪里

对呀，所以我开了这个 issue ，我已经改回原生的配置 tabBar 了..

**Comment by smoothdvd** [comment]
@YogaLin 我是自己先hideTabBar，再用cover-view/cover-image画了一个

**Comment by Smilefish2** [comment]
找到了...
`onShow () {
      console.error(this.$root.$mp.page.getTabBar())
}`

**Comment by YogaLin** [comment]
> �找到了...
> 
> ```
> onShow () {
>       console.error(this.$root.$mp.page.getTabBar())
>       this.$root.$mp.page.getTabBar().setData({
>         selected: 4
>       })
> }
> ```
> 亲测可用[捂脸]

Nice work，我也验证了一下可以。

**Comment by smoothdvd** [comment]
@YogaLin @Smilefish2 改了一下构建脚本，看看对不对。

in config/index.js
```
module.exports = {
  build: {
    env: require('./prod.env'),
    index: path.resolve(__dirname, `../dist/${fileExt.platform}/index.html`),
    assetsRoot: path.resolve(__dirname, `../dist/${fileExt.platform}`),
    ...
    wxCustomTabBarRoot: path.resolve(__dirname, `../dist/${fileExt.platform}`),
    ...
```

in build/webpack.base.conf.js
```
// for custom tab bar on wechat mini-program
if (process.env.PLATFORM === 'wx') {
  baseWebpackConfig = merge(baseWebpackConfig, {
    plugins: [
      new CopyWebpackPlugin([{
        from: path.resolve(__dirname, '../custom-tab-bar'),
        to: path.resolve(config.build.wxCustomTabBarRoot, './custom-tab-bar'),
        ignore: ['.*']
      },])
    ]
  })
}
```

**Comment by teng14** [comment]
> > �找到了...
> > ```
> > onShow () {
> >       console.error(this.$root.$mp.page.getTabBar())
> >       this.$root.$mp.page.getTabBar().setData({
> >         selected: 4
> >       })
> > }
> > ```
> > 亲测可用[捂脸]
> 
> Nice work，我也验证了一下可以。

不行呀，this.$root.$mp.page 没有getTabBar方法

**Comment by smoothdvd** [comment]
@teng14 在main.json里加上“"usingComponents": {}”了吗？
另外，这个自定义tabbar功能太弱了，其实也没什么用。

**Comment by AAAAugust** [comment]
> �找到了...
> 
> ```
> onShow () {
>       console.error(this.$root.$mp.page.getTabBar())
>       this.$root.$mp.page.getTabBar().setData({
>         selected: 4
>       })
> }
> ```
> 
> 亲测可用[捂脸]

请问这句话要加到哪个文件里啊
