### ISSUE TITLE
npm run dev之后就一直这样Starting to optimize CSS...

### ISSUE THREAD

**Issue by liurongji** [Meituan-Dianping/mpvue#145]
![image](https://user-images.githubusercontent.com/14249672/37692111-a1c41892-2cf1-11e8-99ca-ee041d16aed8.png)

**Comment by liurongji** [comment]
![image](https://user-images.githubusercontent.com/14249672/37692099-90edd9fe-2cf1-11e8-8f85-072e84976b51.png)

**Comment by falost** [comment]
官方开发者们 已经在复现处理中了 稍等结果吧

**Comment by doerme** [comment]
一样遇到这个问题 还没解决么？

**Comment by falost** [comment]
可以试试 https://github.com/Meituan-Dianping/mpvue/issues/147

**Comment by anchengjian** [comment]
已经修复，请 `vue init mpvue/mpvue-quickstart my-project` 使用。
