### ISSUE TITLE
打包出来的vendor太大了，webpack为啥不自动压缩一下。

### ISSUE THREAD

**Issue by freecodemakerxu** [Meituan-Dianping/mpvue#1452]
打包出来的微信小程序，vendor超过500M，微信开发者工具跳过打包。

**Comment by aOrz** [comment]
500kb？500M 有点夸张了吧？

**Comment by hucq** [comment]
mpvue 运行时是大小既定的，vender 大小会根据各个项目实际使用情况有差异，剩下的是各个项目中引用的依赖。如果太大，你分析判断是否调整依赖。或者自行修改构建脚本中 vender 的生成规则

**Comment by freecodemakerxu** [comment]
请问，哪个构建版本有自动打包压缩代码的功能，我的代码全部不压缩。

**Comment by YarenTang** [comment]
> 请问，哪个构建版本有自动打包压缩代码的功能，我的代码全部不压缩。

尝试 npm run build
