### ISSUE TITLE
2.0.x async-await、promise，在百度小程序中运行报错

### ISSUE THREAD

**Issue by OEEO** [Meituan-Dianping/mpvue#1454]
项目本来是做微信小程序，使用了大量的async-await异步写法，打包成微信小程序的时候没有问题，打包成百度小程序就会报错。

我用mpvue官方示例做测试，在App.vue 文件中加入async-await，promise 都会导致以下报错（百度开发者工具），在微信开发者工具中是没问题的。有什么办法可以解决这个问题么？

![image](https://user-images.githubusercontent.com/30562940/53720131-f0f53c00-3e9a-11e9-8b4f-46a42eb62298.png)

**Comment by OEEO** [comment]
把百度开发者工具从2.0.9更新到2.0.10，上述问题已解决

**Comment by fengb4676** [comment]
我用百度最新的开发工具2.2.1还会报这个问题。
