### ISSUE TITLE
v-for循环对象，会取出__newReference

### ISSUE THREAD

**Issue by guangzhengyu** [Meituan-Dianping/mpvue#1455]
## 使用v-for循环渲染一个对象的时候，会把取出一个`__newReference`，导致undefined reference错误

**问题复现步骤：**

1. 
```javascript
data () {
  return { 
    obj: {
      a: 1,
      b: 2
   }
}
```

2. 
```vue
<div v-for="(value, key) in obj" :key="key">
{{key}}
</div>
```

**期望的表现：**
a  
b

**观察到的表现：**
a
b
__newReference

[在这里描述观察到的表现]

开发者工具AppData截图：
![image](https://user-images.githubusercontent.com/46769446/53727343-f22e6500-3eaa-11e9-84ec-6b5905e1fc1d.png)

**Comment by Dewyzee** [comment]
感谢反馈，尝试更新到最新版本

**Comment by ibinzhou** [comment]
升级2.0.5之后发现的这个问题, 这个问题在2.0.5中还存在, 什么时候能更新?
