### ISSUE TITLE
为什么 子组件里面（有slot）关闭 和 查看 都触发查看事件 data-eventid 一样的

### ISSUE THREAD

**Issue by l987974** [Meituan-Dianping/mpvue#1458]
## [问题简单描述]

**问题复现步骤：**

1. [第一步]这是父页面
![image](https://user-images.githubusercontent.com/22335100/53800809-887c8c80-3f78-11e9-9ebc-ade4f62a65d1.png)

2. [第二步]这是子组件
![image](https://user-images.githubusercontent.com/22335100/53800848-a3e79780-3f78-11e9-8176-ca1f02b91455.png)

3. [其他步骤...]这是开发者工具里面查看的data-eventid 是一样的 怎么回事 难怪会触发同一个事件
![image](https://user-images.githubusercontent.com/22335100/53800702-43f0f100-3f78-11e9-9177-5a47bb209ccb.png)

**期望的表现：**

[在这里描述期望的表现]能够触发不同的事件 不要搞混了

**观察到的表现：**

[在这里描述观察到的表现]

**屏幕截图或动态图：**

![复现步骤的屏幕截图和动态 GIF 图](图片的 url)
[建议提供可运行的demo]

**Comment by newUserdd** [comment]
这两天也遇到了这个问题，弹窗组件里面用slot，这个问题现在解决了吗？方便给下解决方案吗

**Comment by Dewyzee** [comment]
感谢反馈，我们尽快确认

**Comment by Dewyzee** [comment]
@newUserdd mpvue在slot支持上目前还存在问题，不建议使用slot，在官方文档中有说明不支持使用的特性

**Comment by newUserdd** [comment]
@Dewyzee 文档里面说不支持scoped，我也没用这个属性。 [我现在的解决办法是：增加一些隐藏元素并给他们加上事件，让他们先占去前面几个com-eventid的值，而且如果是用v-for 生成的事件是没有这个问题
![mpvue-eventid](https://user-images.githubusercontent.com/14305343/53865716-d651cd00-402a-11e9-8f70-7434cbaabd19.png)

**Comment by l987974** [comment]
我的解决办法是 那个关闭的叉 放到父页面 跟 查看的那个按钮 一起 插进去 然后 eventid 就不一样了 一个2 一个3 data-comkey还是一样 不知道这个有什么用 反正 问题解决了 不干扰了

**Comment by l987974** [comment]
> @newUserdd mpvue在slot支持上目前还存在问题，不建议使用slot，在官方文档中有说明不支持使用的特性

但是用了一下 发现 好像可以用了 然后就用了
