### ISSUE TITLE
编译百度小程序后 @click时间触发不了

### ISSUE THREAD

**Issue by wxl1225015** [Meituan-Dianping/mpvue#1459]
## [问题简单描述]
百度小程序的点击事件不能触发
**问题复现步骤：**

1. [第一步]mpvue-quickstart构建项目后，依赖安装完成
2. [第二步]npm run dev:swan后@click事件触发不了,但是@change事件能够触发
3. [其他步骤...]

**Comment by Dewyzee** [comment]
方便贴下你当前的环境信息以及相关代码吗？我们这边验证是没有问题的

**Comment by wxl1225015** [comment]
> 方便贴下你当前的环境信息以及相关代码吗？我们这边验证是没有问题的

电脑环境window 64位，mpvue@2.0.5，mpvue-template-compiler@2.0.5，webpack-mpvue-vendor-plugin@2.0.1。

![swan1](https://user-images.githubusercontent.com/26914216/53859751-a5b56780-4019-11e9-93e8-0211d1ed37bc.png)
![swan2](https://user-images.githubusercontent.com/26914216/53859755-a9e18500-4019-11e9-99fe-2c60d602c390.png)
![swan3](https://user-images.githubusercontent.com/26914216/53859763-acdc7580-4019-11e9-9c60-2a3def8b1bd6.png)

**Comment by wxl1225015** [comment]
windows64位，打错了，不好意思，switch的change事件就能触发

![swan4](https://user-images.githubusercontent.com/26914216/53859887-2aa08100-401a-11e9-9eb8-a4b9c7244b63.png)
![swan5](https://user-images.githubusercontent.com/26914216/53859895-2ffdcb80-401a-11e9-9383-fd5515670b1b.png)
