### ISSUE TITLE
微信手机端调试模式下报错：Converting circular structure to JSON

### ISSUE THREAD

**Issue by EasonYou** [Meituan-Dianping/mpvue#146]
# 移动端调试模式报错

出现错误如下图所示。
在开发阶段或者手机端不打开调试模式完全没有问题，出现的情况也比较怪异，具体在复现步骤说明。

![2016654205](https://user-images.githubusercontent.com/16911502/37692379-15f27398-2cf3-11e8-9c1d-c0cb54995654.jpg)

**问题复现步骤:**

出错的情况
假设出错页面为A
1. 打开调试模式
2. A不为主页，从主页进入，报错
3. A为主页，直接扫码进入，不报错

**期望的表现:**
当然是不报错...

**观察到的表现:**
在A页面中，调用了swiper组件，还有两个自定义组件
页面组件除了定义components还有data，并没有调用其他的方法或者钩子函数
也没有监听任何data
swiper里面调用了组件，但测试过组件没有影响

如果需要gif图后面再补上

另外问下一个小程序小白的问题，这样调试模式有问题可以非调试模式ok的情况下，审核能通过吗？

**Comment by anchengjian** [comment]
这个看起来是真机上 vconsole 在输出一个环形的对象时候报错了，去[微信开发者社区](https://developers.weixin.qq.com/)发帖吧。
