### ISSUE TITLE
百度小程序中，v-for 中如果是子组件，数组更新时，列表视图不更新

### ISSUE THREAD

**Issue by OEEO** [Meituan-Dianping/mpvue#1463]
百度小程序中，v-for 中如果是子组件，数组更新时，列表视图不更新。

**Comment by Dewyzee** [comment]
@OEEO 自组件数据更新还是父组件更新？方便贴下相关的代码吗

**Comment by OEEO** [comment]
父组件数据更新，也就是下面代码的resultList长度更新。

后来我调试偶然发现是**多个页面共用一个子组件listItem导致的问题**，我把listItem组件复制多个，分别命名，每个页面引入不同的，就不会出现这个问题了。（在微信小程序中引用同一组件是不会有这个问题的，只在百度小程序中有问题）
`
          <div class="result-list"  v-if="resultList.length > 0">
            <listItem v-for="(item, index) in resultList"
                      :key="index"
                      :item="item">
            </listItem>
          </div>
`

**Comment by Dewyzee** [comment]
@OEEO 你好，我们这边验证是可以更新的，mpvue@2.0.4.你那边问题版本方便提供下吗

**Comment by OEEO** [comment]
我试了一下，我这边也可以了。不过我中间更过版本，也改过一些其它bug，所以我也不是很确定了，现在也没时间回滚找问题了。所以问题关闭了吧。
