### ISSUE TITLE
事件编译问题

### ISSUE THREAD

**Issue by l-jw** [Meituan-Dianping/mpvue#1467]
## [问题简单描述]
事件编译问题
**问题复现步骤：**
![image](https://user-images.githubusercontent.com/45445188/54012458-13e06280-41b1-11e9-9bfe-4bb9e74c9bc6.png)
![image](https://user-images.githubusercontent.com/45445188/54012485-278bc900-41b1-11e9-8aa7-e53edb3408cc.png)

1. [第一步]
创建图一组件
2. [第二步]
图二引入组件
3. [其他步骤...]
点击事件打印出  2 而且是执行两次

**期望的表现：**
打印 11111    2

[在这里描述期望的表现]

**观察到的表现：**
![image](https://user-images.githubusercontent.com/45445188/54012632-979a4f00-41b1-11e9-93ed-0b47bc1e321a.png)
点击一次所打印的结果
[在这里描述观察到的表现]

**屏幕截图或动态图：**

![复现步骤的屏幕截图和动态 GIF 图](图片的 url)
[建议提供可运行的demo]

**Comment by l-jw** [comment]
官方管不管了，不管了捐给社区，开源的出来不维护

**Comment by Dewyzee** [comment]
mpvue版本号是多少呢
