### ISSUE TITLE
升级到2.x之后，组件中再套一个组件的话，最里面的组件的元素上无法触发 @click 事件

### ISSUE THREAD

**Issue by HADB** [Meituan-Dianping/mpvue#1469]
## [问题简单描述]

**问题复现步骤：**

1. mpvue 从 1.x 升级到 2.x
2. 按照官方教程升级
3. 原先正常的代码中的@click事件无法触发，经过测试，只有当组件中再套一个组件的话，最里面的组件中的元素上，无法触发 @click 事件。

**期望的表现：**

可以正常触发 @click 事件

**观察到的表现：**

如上所述

**屏幕截图或动态图：**

略

**Comment by ZjVirus** [comment]
+1

**Comment by Dewyzee** [comment]
麻烦提供下当前的mpvue版本呢？

**Comment by HADB** [comment]
@Dewyzee 2.0.2

**Comment by Dewyzee** [comment]
@HADB 先尝试升级到2.0.4试试呢

**Comment by HADB** [comment]
你们 release 都不在 GitHub 上打个 tag 吗？都不知道有更新了😂

**Comment by AndrewZheng** [comment]
暂不支持在组件引用时，在组件上定义 click 等原生事件、v-show（可用 v-if 代替）和 class style 等样式属性(例：<card class="class-name"> </card> 样式是不会生效的)，因为编译到 wxml，小程序不会生成节点，建议写在内部顶级元素上。

http://mpvue.com/mpvue/#vue_1

**Comment by HADB** [comment]
@AndrewZheng 你没有理解我的意思，我知道不支持在组件上定义 click 事件。我是在组件里面的 div 上定义的事件，并且不只是 click ，所有事件都不生效了。

**Comment by HADB** [comment]
我举个例子：
#### 页面：
```
<template>
...
    <component-a />
...
</template>
```

#### component-a
```
<template>
...
    <component-b />
...
</template>
```

#### component-b
```
<template>
...
    <div @click="onClick" />
...
</template>
```

是 component-b 上面的 click 事件无法响应

**Comment by sideFlower** [comment]
m

**Comment by HADB** [comment]
经测试，升级到 2.0.5 之后，问题已经不存在

**Comment by HADB** [comment]
提个建议，在 npm 上发布更新后，在 GitHub 上最好能发个 release，让我们好知道有更新。现在 npm 上的版本已经是 2.0.5 了，GitHub 上还是 2.0.2

**Comment by lxzy-yun** [comment]
升级到2.0.5后，组件上定义v-if后，组件里面的事件也都无法执行

**Comment by cizkey** [comment]
同上，遇到了2.0.5~2.06， 在组件上使用v-if，点击事件第一次执行总是执行页面中第一个@click的方法。不使用v-if则正常。

**Comment by cdd111** [comment]
没有用v-if  在组件的组件里调用@click还是失效
