### ISSUE TITLE
未找到 app.json 中的定义的 pages "pages/index/main" 对应的 WXML 文件

### ISSUE THREAD

**Issue by reallyloveme** [Meituan-Dianping/mpvue#147]
npm run dev 后一直在Starting to optimize CSS,小程序运行时一直提示上述错误

![image](https://user-images.githubusercontent.com/28882818/37692949-18713a60-2cf7-11e8-8684-f47fa6b58e59.png)

**Comment by falost** [comment]
如果是使用最新版的，并且在window系统下的话，请 修改下build/webpack.base.conf.js 文件中的
```function getEntry (dir, entryFile) {
  var files = glob.sync(dir + '/pages/**/main.js');
  var map = {};
  files.forEach(file => {
    var key = file.replace(dir + '/', '').replace(/\.js$/, '');
    map[key] = file;
  })
  return map;
}
```
修改为 
```
function getEntry (dir, entryFile) {
  var files = glob.sync(dir + '/pages/**/main.js');
  var map = {};
  files.forEach(file => {
    var key = path.dirname(file).slice(dir.length + 1).replace(path.sep, '/')
    file = file.replace(/\//g, '\\')
    map[key] = file;
  })
  return map;
}
```
然后重新执行下 npm run dev

**Comment by Blubiubiu** [comment]
然而并没有用

**Comment by falost** [comment]
@Blubiubiu 是否可以提供下 错误信息呢

**Comment by doerme** [comment]
修改build/webpack.base.conf.js 之后 

 Starting to optimize CSS...
 DONE  Compiled successfully in 2372ms14:53:46

然后一直卡在这里没反应了。

**Comment by Blubiubiu** [comment]
@falost 报错信息同题主，还是一直卡在Starting to optimize CSS... ，下载的最新版，发现代码中已经如你所说改过了

**Comment by anchengjian** [comment]
已经修复，请 `vue init mpvue/mpvue-quickstart my-project` 使用。

**Comment by reallyloveme** [comment]
ok了，thanks

**Comment by iaei** [comment]
``` 
VM2646:2 ./pages/home/home.wxss
File not found: ../../static/css/pages/home/home.wxss
(anonymous) @ VM2646:2
```
npm run dev后, dist中的css/pages下的文件夹任为初始时的样子. 没有被编译
