### ISSUE TITLE
onPullDownRefresh下拉没有效果

### ISSUE THREAD

**Issue by zcwcsj** [Meituan-Dianping/mpvue#1470]
onPullDownRefresh:function(){//下拉触发
	console.log("sadas")  //打印不出来
},

同级的main.js
export default {
  config: {
    "enablePullDownRefresh": true
  }
}

 "dependencies": {
    "mpvue": "^2.0.0",
    "vuex": "^3.0.1",
    "wafer2-client-sdk": "^2.1.0"
  },

**Comment by Dewyzee** [comment]
"enablePullDownRefresh"配置放在main.json中配置或者在项目配置app.json的window项中配置。页面中事件注册onPullDownRefresh与页面的生命周期钩子函数同级

**Comment by boxshadow** [comment]
> "enablePullDownRefresh"配置放在main.json中配置或者在项目配置app.json的window项中配置。页面中事件注册onPullDownRefresh与页面的生命周期钩子函数同级

理论上是这样，但是现在我也遇到相同的问题， main.js设置了开启下拉刷新，同级vue文件中注册了onPullDownRefresh事件，可是下拉刷新的视图效果出现了，onPullDownRefresh事件却没有执行
