### ISSUE TITLE
关于mpvue凉凉的建议

### ISSUE THREAD

**Issue by BigBigBao** [Meituan-Dianping/mpvue#1471]
## [关于mpvue凉凉的建议]

**已经入坑，确实是最辣鸡的小程序框架。弃坑，建议mpvue到此为止吧**

**Comment by BigBigBao** [comment]
没有金刚钻就别揽瓷器活！好好一个iview，在mpvue里用起来都不如手撸，求求了美团啊

**Comment by BOMBOMBANG** [comment]
nb
