### ISSUE TITLE
npm run dev 报错

### ISSUE THREAD

**Issue by Ammmong123** [Meituan-Dianping/mpvue#1473]
Module build failed: Error: [mpvue-loader] need "fileExt" option in file "build/vue-loader.conf.js"，init a new project and copy the directory "build/" to this porject, or just check the "fileExt" option
克隆了好几个项目运行都报错了，但是又可以通过官方命令行创建快速模版；npm node都重装过还是不行

**Comment by lxchuan12** [comment]
> Module build failed: Error: [mpvue-loader] need "fileExt" option in file "build/vue-loader.conf.js"，init a new project and copy the directory "build/" to this porject, or just check the "fileExt" option
> 克隆了好几个项目运行都报错了，但是又可以通过官方命令行创建快速模版；npm node都重装过还是不行

@Ammmong123 
这是因为依赖安装不对。可以锁定依赖版本。另外建议项目作者修复该问题。
参考这个ISSUE #1384  [项目删除包从新下载 项目能启动 但是报错 事件失效](https://github.com/Meituan-Dianping/mpvue/issues/1384) 
的解决方案。
>
>1. 升级最新的mpvue2.0。 升级指南: https://github.com/Meituan-Dianping/mpvue/releases/tag/2.0.0
>2. 升级2.0会增加头条、百度、支付宝小程序的支持，不想升级的同学，可以对以下依赖进行版本锁定，即可， 亲测可用，当然不升旧bug则不能得到解决，风险自行承担。
```package.json
"mpvue": "1.0.18",
"mpvue-loader": "1.1.4",  
"mpvue-template-compiler": "1.0.18"
```

**Comment by Ammmong123** [comment]
我试了第二种方法，fileExt的错误没了，我尝试了清除缓存和node_modules,重新安装，和修改了端口依旧报这个错误。node我重装了尝试也是同样的问题
`events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, open 'E:\git clone\cgw_applet\static\images\add-to-mine.png?v=2'
Emitted 'error' event at:
    at lazyFs.open (internal/fs/streams.js:115:12)
    at FSReqWrap.args [as oncomplete] (fs.js:140:20)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cgwwexin@1.0.0 dev: `node build/dev-server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the cgwwexin@1.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Administrator.USER-20180630XE\AppData\Roaming\npm-cache\_logs\2019-03-11T03_38_34_847Z-debug.log
`

**Comment by Dewyzee** [comment]
麻烦提供下当前mpvue、mpvue-template-compiler以及mpvue-loader版本

**Comment by Ammmong123** [comment]
@Dewyzee 最近没看信息抱歉，后面发现是同事在首页引用的图片地址错误会报这种错误，已解决
