### ISSUE TITLE
组件中点击事件无法触发

### ISSUE THREAD

**Issue by caiyongqiang** [Meituan-Dianping/mpvue#1475]
## [问题简单描述]
组件中调用组件，在1.4.1中能触发最后那个组件，但是版本1.4.2就不行；在组件中调用组件在调用组件，在版本1.4.1无法触发点击事件，而在版本1.4.2中可以触发；感觉版本兼容做的不够好
**问题复现步骤：**

1. [第一种情况]
要展示的当前页面引用组件：
`<div><insuranceSearchMask></insuranceSearchMask></div>`
在组件insuranceSearchMask中代码调用另一个组件getUserInfoAuth：
`<div><getUserInfoAuth></getUserInfoAuth></div>`
在最后组件getUserInfoAuth中代码如下：
`<div>
    <button @click="toLogin" class="button">{{title}}</button>
  </div>`
这种情况下版本：v 1.4.2点击事件toLogin是可以触发的，但是在版本：v 1.4.1是无法触发的
2. [第二种情况]
在pages文件夹下面新增一个文件夹postalInsurance
在postalInsurance中代码引用组件如下：
`<div class="setmeal" @click="closeFn()">
      <setmeal v-on:closeFn='closeFn' type='1'></setmeal>
    </div>`
在组件setmeal中代码：
`<div class="meal_sure" @click.stop="meal_sure">确定</div>`
这种情况版本1.4.1中点击事件meal_sure是可以触发的，但是在1.4.2是无法触发点击事件meal_sure

**Comment by caiyongqiang** [comment]
不知道什么原因第二种情况不见了，现在补回：
2. [第二种情况] 在pages文件夹下面新增一个文件夹postalInsurance 在postalInsurance中代码引用组件如下： `<div class="setmeal" @click="closeFn()">
      <setmeal v-on:closeFn='closeFn' type='1'></setmeal>
    </div>`；
在组件setmeal中代码： `<div class="meal_sure" @click.stop="meal_sure">确定</div>`；
 这种情况版本1.4.1中点击事件meal_sure是可以触发的，但是在1.4.2是无法触发点击事件meal_sure

**Comment by Dewyzee** [comment]
![image](https://user-images.githubusercontent.com/4916726/54197545-2f27d680-44ff-11e9-8da7-55cc7faf0a28.png)
版本1.4.2验证不存在问题哈

**Comment by shangjingfei** [comment]
same issue
