### ISSUE TITLE
mpvue升级2.0运行npm run dev报错

### ISSUE THREAD

**Issue by 1152574267** [Meituan-Dianping/mpvue#1476]
npm run dev

No parser and no filepath given, using 'babel' the parser now but this will throw an error in the future. Please specify a parser or a filepath so one can be inferred.

**Comment by Dewyzee** [comment]
麻烦贴下具体的报错呢？前面贴的内容为warning，不影响项目构建

**Comment by 1152574267** [comment]
没有其他报错

**Comment by 1152574267** [comment]
> 麻烦贴下具体的报错呢？前面贴的内容为warning，不影响项目构建

没有其他报错
