### ISSUE TITLE
mpvue 内使用 map polyline无法连接线路

### ISSUE THREAD

**Issue by m17319325007** [Meituan-Dianping/mpvue#1479]
## [问题简单描述]

**问题复现步骤：**

1. [第一步]
<map
        id="myMap"
        scale="14"
        longitude="108.89244"
        latitude="34.195895"
        :polyline="polyline"
        show-location
      ></map>
2. [第二步]
polyline: [
        {
          points: [
            {
              latitude: 34.195895,
              longitude: 108.89244
            },
            {
              latitude: 34.2298998476,
              longitude: 108.9466953278
            }
          ],
          color: "#000000",
          width: 5
        },
        {
          points: [
            {
              latitude: 34.2298998476,
              longitude: 108.9466953278
            },
            {
              latitude: 34.2759426987,
              longitude: 108.9617156982
            }
          ],
          color: "#000000",
          width: 5
        }
      ]。

**期望的表现：**
线路连接，数据在原生小程序测试可以实现
**观察到的表现：**
线路未连接
**屏幕截图或动态图：**
在mavue环境中测试
![QQ图片20190312172359](https://user-images.githubusercontent.com/23732011/54189052-f599a000-44eb-11e9-8f1c-015e89455c45.png)
在默认环境中测试
![QQ图片20190312172423](https://user-images.githubusercontent.com/23732011/54189178-385b7800-44ec-11e9-9846-471ee1b2ab1b.png)

**Comment by Dewyzee** [comment]
您好，我们这边验证是符合预期的。mpvue为2.0.4版本
![image](https://user-images.githubusercontent.com/4916726/54201099-d0b32600-4507-11e9-842e-c1bd82a47e0a.png)

**Comment by Dewyzee** [comment]
您好，我们这边验证是符合预期的。mpvue为2.0.4版本
![image](https://user-images.githubusercontent.com/4916726/54201141-e4f72300-4507-11e9-8481-24e158597e97.png)

**Comment by Dewyzee** [comment]
![image](https://user-images.githubusercontent.com/4916726/54201451-a44bd980-4508-11e9-8f94-ce81b4d5de24.png)

您好，我们这边验证是符合预期的。mpvue为2.0.4版本。
