### ISSUE TITLE
mpvue 不支持 requestAnimationFrame

### ISSUE THREAD

**Issue by fantasthu** [Meituan-Dianping/mpvue#148]
# npm 安装 minirefresh 发现不支持 requestAnimationFrame?
**问题复现步骤:**
1.npm install minirefresh
2.引入相应库,npm start

**期望的表现:**
minirefresh可以在mpvue中使用

**观察到的表现**
1.npm start 命令工具报错
```
(node:25530) DeprecationWarning: loaderUtils.parseQuery() received a non-string value which can be problematic, see https://github.com/webpack/loader-utils/issues/56
parseQuery() will be replaced with getOptions() in the next major version of loader-utils.
```
2.小程序开发者工具报错
![image](https://user-images.githubusercontent.com/9922079/37696343-e3c0ae94-2d10-11e8-8445-dcf1dcdd3242.png)

**Comment by hucq** [comment]
小程序和浏览器有较大区别，不支持使用DOM, BOM一类的操作，如果要实现类似效果，可以参考使用 css3 动画。框架本身缺乏底层支持，无法显示。
