### ISSUE TITLE
有没有类似vue中路由拦截的功能，实现对登录状态的判断

### ISSUE THREAD

**Issue by freecodemakerxu** [Meituan-Dianping/mpvue#1480]

**Comment by freecodemakerxu** [comment]
授权页面比较多的情况下，工作量大哇。

**Comment by Cweili** [comment]
@freecodemakerxu 试试 https://github.com/Cweili/vue-router-mp

**Comment by hucq** [comment]
mpvue 不具备这个功能，需要自己实现。

**Comment by microJ** [comment]
@freecodemakerxu 
亲 wx api 的增强路由，支持 beforeEach、afterEach
https://github.com/microJ/wx-nav
