### ISSUE TITLE
mpvue 2.0 引入 百度统计、神策问题

### ISSUE THREAD

**Issue by Howie126313** [Meituan-Dianping/mpvue#1482]
## [问题简单描述]
mpvue 升级到2.0后，项目引入百度统计和神策SDK，放在 vue 下引入时，引入不生效
**问题复现步骤：**

1. [第一步]
main.js 正常代码如下
```
import './utils/bd/mtj-wx-sdk.js'
import sensors from './utils/sensorsdata/sensorsdata.min.js'

import Vue from 'vue'
import App from './App'
import '../static/css/common.css'
import fly from '@/constants/http'
import landzloading from '@/components/public/landzloading'
import imgs from '@/components/public/imgs'
import exMap from '@/components/public/exMap'
import exDataChart from '@/components/public/exDataChart'
import landzQrBottom from '@/components/public/landzQrBottom'
import { BASE_URL, IMAGE_BASEURL } from '@/constants/sys'
import echartsJS from '../static/libs/echarts.min.js'

sensors.init()
```
2. [第二步]
正常情况下在 getApp()中，会存在 mtj 和 sensors 对象。
当引入放在 vue 引入下，不会生效。
3. [其他步骤...]

**期望的表现：**

[在这里描述期望的表现]

**观察到的表现：**

[在这里描述观察到的表现]

**屏幕截图或动态图：**
![getApp()截图](https://upload-images.jianshu.io/upload_images/8610628-5bfbb7bc8b4843aa.jpg?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

![复现步骤的屏幕截图和动态 GIF 图](图片的 url)
[建议提供可运行的demo]

**Comment by Dewyzee** [comment]
你好，我们基于2.x版本验证是能挂载到App实例上的。请确认下是否存在别的库干扰～
![image](https://user-images.githubusercontent.com/4916726/54337129-e5f39600-4668-11e9-9ddb-3553fb5f789a.png)
![image](https://user-images.githubusercontent.com/4916726/54337140-ee4bd100-4668-11e9-95ef-047f69ccaabe.png)

**Comment by Howie126313** [comment]
@Dewyzee 是可以挂载到App实例上的，但是当引入写在 vue 引入下面的时候就不生效了。
```
import Vue from 'vue'

import './utils/bd/mtj-wx-sdk.js'
import sensors from './utils/sensorsdata/sensorsdata.min.js'

import App from './App'
import '../static/css/common.css'
sensors.init()
```

**Comment by Howie126313** [comment]
@Dewyzee 想确定一下问题的原因~不明白为啥~谢谢~
