### ISSUE TITLE
通过this.$refs拿不到子组件

### ISSUE THREAD

**Issue by sunkint** [Meituan-Dianping/mpvue#149]
比如定义个组件叫做`MyInput`
然后父组件里引用它
`<MyInput ref="child"></MyInput>`
无法在父组件里通过`this.$refs.child`拿到这个子组件的实例
不知道能不能得到解决。

**Comment by falost** [comment]
看 https://github.com/Meituan-Dianping/mpvue/issues/73

**Comment by sunkint** [comment]
主要我是想在 v-for 上使用 ref 来拿一串子组件的内部复杂状态
