### ISSUE TITLE
配置web worker报错

### ISSUE THREAD

**Issue by daisygogogo** [Meituan-Dianping/mpvue#1490]
## [问题简单描述]

**问题复现步骤：** app.json中配置"workers": "workers"，是按照小程序文档来配置的，在别的原生项目上可以用，但是mpvue项目中报错，VM25339:5 workers 字段需为 目录

**屏幕截图或动态图：**
![image](https://user-images.githubusercontent.com/35161604/54490626-5d882600-48f2-11e9-8440-7d9773bd7a73.png)

**Comment by hucq** [comment]
ide 提示该字段应该对应一个实际目录，你需要确保在构件好的 dist 目录下确认该目录是否存在。

**Comment by immafrady** [comment]
对应的worker文件无法被webpack识别到（因为其他页面没有明显的引用），所以压根就没被打包进去！

**Comment by melunar** [comment]
worker 目录未找到，确认下app.json配置目录是否正确
