### ISSUE TITLE
data中的二维数组无法使用v-for循环渲染

### ISSUE THREAD

**Issue by Aaronxjs** [Meituan-Dianping/mpvue#1493]
## [问题简单描述]

**问题复现步骤：**

1. [第一步]
2. [第二步]
3. [其他步骤...]

**期望的表现：**

[在这里描述期望的表现]

**观察到的表现：**

[在这里描述观察到的表现]

**屏幕截图或动态图：**

![复现步骤的屏幕截图和动态 GIF 图](图片的 url)
[建议提供可运行的demo]

**Comment by Aaronxjs** [comment]
一维数组可以，二维数组就不行

**Comment by hucq** [comment]
@Aaronxjs 应该不存在你说的这种情况，可以把代码发出来看看，另外提供下mpvue的版本。

**Comment by Aaronxjs** [comment]
> @Aaronxjs 应该不存在你说的这种情况，可以把代码发出来看看，另外提供下mpvue的版本。

感谢您的回复，发现是我代码的问题，已经解决。
