### ISSUE TITLE
能否新增组件的递归调用，类似Vue中子组件调用自身

### ISSUE THREAD

**Issue by GTRgoSky** [Meituan-Dianping/mpvue#1495]
## [在此简单描述您的建议]

![image](https://user-images.githubusercontent.com/21190726/54595739-2fc7ec00-4a6e-11e9-95a2-822432d039b7.png)

[在这里引用新功能相关的讨论]

**新功能的实现：**

希望可以实现

**相关项目或文档：**

https://cn.vuejs.org/v2/guide/components-edge-cases.html#%E9%80%92%E5%BD%92%E7%BB%84%E4%BB%B6

**Comment by hucq** [comment]
暂为列入计划，欢迎提供pr.
