### ISSUE TITLE
支持pages/device/device， 但不支持 pages/device/list/list 的问题

### ISSUE THREAD

**Issue by myzqy** [Meituan-Dianping/mpvue#150]
pages 下面
目前只能  pages/device/device    pages/deviceDetail/deviceDetail

我想文件目录能够有更多灵活性
比如：
pages/device/list/list   列表页面
pages/device/detail/detail   详细页面
pages/device/new/new   添加页面

目前我试很多次了，如果 pages/device/new/new  这么做，是用不了的。
确定吗？
能不能优化一下

**Comment by anchengjian** [comment]
已经把多路径做成了默认配置，请 `vue init mpvue/mpvue-quickstart my-project` 使用，或者自定义 [entry](https://github.com/mpvue/mpvue-quickstart/blob/master/template/build/webpack.base.conf.js#L13-L30)

**Comment by smithyj** [comment]
@anchengjian 改动entry文件会不会影响后期与官方的同步更新
