### ISSUE TITLE
triggerEvent()在 mpvue中使用报错！

### ISSUE THREAD

**Issue by ALshas** [Meituan-Dianping/mpvue#1505]
在mpvue中怎么使用triggerEvent()

我用mpvue重用triggerEvent()会显示

_this.triggerEvent is not a function;at api request success callback function

TypeError: _this.triggerEvent is not a function

这样滴~~

![image](https://user-images.githubusercontent.com/24910851/54799151-ec9c9180-4c96-11e9-89e9-4895d710ba48.png)

**Comment by l-jw** [comment]
在vue里面写emit啊。

**Comment by hucq** [comment]
emit！
