### ISSUE TITLE
使用这个框架之后，不能分享，用onShareAppMessage

### ISSUE THREAD

**Issue by ALshas** [Meituan-Dianping/mpvue#1508]
用了这个框架，加上    
onShareAppMessage(res) {
      console.log( ,res)
      return {
        title: "自定义转发标题",
        path: "/pages/index/main"
      };
    },
点击右上角的胶囊，不能分享！！！！

**Comment by hucq** [comment]
一直是可以的。查不出问题就把代码发出来看看。

**Comment by ALshas** [comment]
> 一直是可以的。查不出问题就把代码发出来看看。

是的 
是我没看文档
