### ISSUE TITLE
vue 文件的里面的js如果是包引入会导致组件不能被编译识别？

### ISSUE THREAD

**Issue by ifuner** [Meituan-Dianping/mpvue#151]
# [问题简单描述]

**问题复现步骤:**

1. page/index/index.vue 里面的js代码过多所有就单独创建了js，vue那边通过script src引入
2. 在js包里面引入其他组件

**期望的表现:**

希望能解决这个问题，一起加油mpvue

**观察到的表现:**

无法编译引入的包里面的引入的组件

**屏幕截图和动态 GIF 图**

![复现步骤的屏幕截图和动态 GIF 图](图片的 url)

**Comment by hucq** [comment]
看描述不能确认你的问题。
通过 script src 的方式引入外部依赖的方式应该不是一个科学的方案，建议采用ES module的方式导入导出，即export， import
