### ISSUE TITLE
mpvue2.0.5，data中的object，如果未在template中使用，会在页面返回后被添加 __newReference

### ISSUE THREAD

**Issue by EvenCom** [Meituan-Dianping/mpvue#1512]
#### 在data中添加了一个object类型的数据，如果未在template渲染中用到该数据，mpvue会在页面onshow时（即进入一个页面后，回退到当前页面时）给该数据添加__newReference属性，且该属性可被枚举。

**mpvue版本号：2.0.5**

**最小化代码**

```
<script>
data() {
   return {
       test: {
           a: 1
       }
   }
},
onShow() {
    console.log(Object.keys(this.test));   
   // 在页面回退时触发的onshow中，test就被添加了__newReference
}
</script>
```

**运行结果截图**

![image](https://user-images.githubusercontent.com/5886485/54970119-f33f4780-4fbb-11e9-8c6b-9c58e7312ab0.png)

**Comment by zzhero** [comment]
同求

**Comment by Dewyzee** [comment]
在2.0.6版本中已经解决，稳定版本还未升上来，可以先手动升级
