### ISSUE TITLE
mpvue 2.0.x 百度小程序 ios 真机测试时下  Promise、async-await 出错

### ISSUE THREAD

**Issue by OEEO** [Meituan-Dianping/mpvue#1514]
mpvue 2.0.x 百度小程序 ios 真机测试时  Promise、async-await，会导致所有事件无效，v-for 无效，即导致页面直接错误。

mpvue版本，mpvue@2.0.5。百度开发者工具2.0.14。

示例代码 ，在app.vue ，created中加入以下代码。
```javascript
    let doSomeSync = () => {
      return new Promise((resolve, reject) => {
        resolve()
      })
    }
    doSomeSync()
      .then(() => {
        mpvue.showToast({ title: 'Promise' })
      })
```

**在安卓真机、百度开发者工具中，以及ios 远程调试模式中，都没有此问题，只有ios打包预览、体验、上线时，才会出现此问题。**

**Comment by OEEO** [comment]
顺便说一下，我用来调试的 ios 手机是 iphone6 plus。手头上没有其它的 ios 手机，其它机型情况未知。如果有相应解决方案，请求赐教。项目中大量使用了 Promise ，改起来会很蛋痛，谢谢。

**Comment by lechengyu** [comment]
iPhone6s plus，12.2系统，遇到同样问题。

**Comment by lechengyu** [comment]
已经有相关讨论及解决方案，链接 #1488

**Comment by OEEO** [comment]
> 已经有相关讨论及解决方案，链接 #1488

感谢。
