### ISSUE TITLE
img src 使用相对路径无法加载图片 例：<img src="../../images/LOGO.png">

### ISSUE THREAD

**Issue by myzqy** [Meituan-Dianping/mpvue#152]
问题，如题

报错
Failed to load local image resource /src/images/head.png 
 the server responded with a status of 404 (HTTP/1.1 404 Not Found)

**Comment by F-loat** [comment]
/static/xx.jpg，或者前面加个 ~

**Comment by myzqy** [comment]
感谢
~../../images/head.png  好像没用
但是放在根目录static下，就可以使用。
不过官方文档上好像没说需要这么处理

**Comment by F-loat** [comment]
~@/images/xxx.jpg 这种应该行

**Comment by myzqy** [comment]
~@ 各种重组试了一下，还是不行

**Comment by hucq** [comment]
问题确认，我们列入问题中解决！

**Comment by linrunzheng** [comment]
<template>
    <div>
        <img :src="imgUrl">
    </div>
</template>

<script>
import imgUrl from '@/img/a.png'

export default {
    data() {
        return {
            imgUrl
    }
}
</script>

**Comment by lavyun** [comment]
解决了吗？使用/static好像就不能享受url-loader了。而且在background中又是可以使用相对路径的。这样我assets和static中都需要有images目录，有点麻烦。

**Comment by cwc845982120** [comment]
@myzqy 不要使用相对路径 使用绝对路径就没问题了！亲测有效

**Comment by cwc845982120** [comment]
@hucq 不要使用相对路径 使用绝对路径就没问题了！亲测有效

**Comment by fengcen** [comment]
我也遇到了这个问题，希望跟进一下

**Comment by cwc845982120** [comment]
@fengcen 不要使用相对路径 使用绝对路径就没问题 
像这样<img src="/static/image.png">
远程调试、预览、打包后都没问题，亲测有效！

**Comment by cwc845982120** [comment]
@fengcen 不要使用相对路径 使用绝对路径就没问题
像这样“src="/static/image.png">”
远程调试、预览、打包后都没问题，亲测有效！

**Comment by fengcen** [comment]
@cwc845982120 但是我需要打包成 base64 格式，不能使用绝对路径。

**Comment by cwc845982120** [comment]
@fengcen 那你webpack那边对图片的处理是怎样的，是webpack不起作用还是图片路径的问题呢？

**Comment by fengcen** [comment]
应该是 mpvue-loader 没有正确处理 `<img>` 标签里面的 `src` 属性。

**Comment by zjz894251se** [comment]
分享一个我目前的解决方案：
修改node_modules\mpvue-loader\lib\template-compiler\modules\transform-require.js文件如下
```` javascript
//1.增加urlToRequire 方法
function urlToRequire (url) {
  // same logic as in transform-require.js
  const firstChar = url.charAt(0)
  if (firstChar === '.' || firstChar === '~' || firstChar === '@') {
    if (firstChar === '~') {
      const secondChar = url.charAt(1)
      url = url.slice(secondChar === '/' ? 2 : 1)
    }
    return `require("${url}")`
  } else {
    return `"${url}"`
  }
}
//2.修改rewrite 方法
function rewrite (attr, name) {
  if (attr.name === name) {
    const value = attr.value
    // only transform static URLs
    if (value.charAt(0) === '"' && value.charAt(value.length - 1) === '"') {
      attr.value = urlToRequire(value.slice(1, -1))
      return true
    }
  }
}
````

**Comment by zjz894251se** [comment]
分享一个我目前的解决方案：
修改node_modules\mpvue-loader\lib\template-compiler\modules\transform-require.js文件如下
``` javascript
//1.增加urlToRequire 方法
function urlToRequire (url) {
  // same logic as in transform-require.js
  const firstChar = url.charAt(0)
  if (firstChar === '.' || firstChar === '~' || firstChar === '@') {
    if (firstChar === '~') {
      const secondChar = url.charAt(1)
      url = url.slice(secondChar === '/' ? 2 : 1)
    }
    return `require("${url}")`
  } else {
    return `"${url}"`
  }
}
//2.修改rewrite 方法
function rewrite (attr, name) {
  if (attr.name === name) {
    const value = attr.value
    // only transform static URLs
    if (value.charAt(0) === '"' && value.charAt(value.length - 1) === '"') {
      attr.value = urlToRequire(value.slice(1, -1))
      return true
    }
  }
}

**Comment by zjz894251se** [comment]
@myzqy 试试我的解决办法，跟vue-loader路径处理保持一致

**Comment by ganksolo** [comment]
留名，看下最终的解决方案。

**Comment by ysfscream** [comment]
把静态资源文件放到 static 里试试

**Comment by F-loat** [comment]
@zjz894251se 可以去 pr，能找到这个问题的原因就更好

**Comment by gmonking** [comment]
mark

**Comment by banxi1988** [comment]
我感觉遇到类似的问题。
怎么让 image-src 中的图片让 url-loader 加载成 base64 呢？
尝试这样写：
`<image src="~@/assets/ic_lock_small.png" class="icon-lock icon"/>`
和这样写： `<image src="~@/assets/ic_lock_small.png" class="icon-lock icon"/>` 
都无效。
我这个图片很小的。只有 500 多字节。

**Comment by F-loat** [comment]
@banxi1988 更新下 mpvue-loader

**Comment by banxi1988** [comment]
@F-loat  感谢回复。
已经更新到 1.0.14

```
+ mpvue-loader@1.0.14
updated 2 packages in 19.976s
```

使用方式1 ： `<image src="~@/assets/ic_lock_small.png" class="icon-lock icon"/>` 无效。
使用方式2： `<image src="url('~@/assets/ic_lock_small.png')" class="icon-lock icon"/>` 无效。

是不是指定路径的格式不对？
`assets` 目录是在 `src` 目录下。

**Comment by F-loat** [comment]
@banxi1988 不会转成 base64 但是会复制图片到 dist 文件夹里，应该可以正常显示

**Comment by banxi1988** [comment]
@F-loat  也没有复制到 static 目录。
![image](https://user-images.githubusercontent.com/726774/40815953-a0f4d9ec-657c-11e8-924d-01a707a7a284.png)

**Comment by F-loat** [comment]
https://github.com/mpvue/mpvue-loader/pull/19 你参考这个 pr 看下

**Comment by F-loat** [comment]
@banxi1988 看起来是只支持了 `../xxx` 这种相对路径的形式

**Comment by Aimee1608** [comment]
之前写Vue 项目 对于动态引用src 的时候是用require可以编译相对路径  现在不好用了
<img   :src="require('../assets/img/enter_4.png')"/>
被迫转移目录到static  文件夹下面
<img   src="/static/img/enter_4.png"/>

**Comment by Aimee1608** [comment]
之前写Vue 项目 对于动态引用src 的时候是用require可以编译相对路径 现在不好用了
`<img   :src="require(../assets/img/enter_4.png')"/>`
被迫转移目录到static 文件夹下面
`<img   src="/static/img/enter_4.png"/>`

**Comment by fanyj1994** [comment]
使用 `require('')`来引入就可以了
