### ISSUE TITLE
引入 iview weapp ui组件，内存撑爆的问题

### ISSUE THREAD

**Issue by gslancer** [Meituan-Dianping/mpvue#1524]
当前 mpvue 为2.0.0，下载iview weapp 后，放入项目static下。
并在需要的各个页面(不到20个页面)main.json中引入相关ui组件。
真机调试的时候，微信开发工具中显示，内存飙升，一堆错误，连接信息中的未确认一直往上涨。
手机预览小程序，手机发热烫的厉害得很。

请教下，是我引入姿势不对么？

**Comment by caffreycc** [comment]
请直接引入iview weapp 项目目录下的dist目录到你的项目下，在main.js或者app.json声明组件按需调用，

**Comment by gslancer** [comment]
要使用 import-weapp-component ！！！！！
