### ISSUE TITLE
单文件内没有style标签时，生成页面的wxss引用一个不存在的wxss

### ISSUE THREAD

**Issue by lzq4047** [Meituan-Dianping/mpvue#153]
# .vue文件没有style块的时候，dist中对应page下面的wxss文件中引用了一个wxss，但是这个wxss并没有生成

**问题复现步骤:**

1. 新建.vue文件
2. 不写style块
3. 构建

**期望的表现:**

没有style的页面生成的wxss不引用static下面的wxss

**观察到的表现:**

没有style的页面生成的wxss引用了static下面的一个wxss，但是这个wxss不存在

**屏幕截图和动态 GIF 图**

![image](https://user-images.githubusercontent.com/17979867/37700059-1622c2f0-2d25-11e8-83c5-dc7cb1b1b61f.png)

**Comment by anchengjian** [comment]
已修复，请升级 mpvue-loader 到最新版 
https://github.com/Meituan-Dianping/mpvue/releases/tag/1.0.7
