### ISSUE TITLE
slot不支持绑定模板数据？

### ISSUE THREAD

**Issue by Pasoul** [Meituan-Dianping/mpvue#1533]
## [扼要问题描述]

子组件里定义了具名slot，再父组件中使用时，slot不支持绑定父组件的data

**mpvue 版本号：1.0.11**

[mpvue@1.0.11]

**最小化复现代码：**

子组件
```
<template>
   <div class="sticky">
     <div class="sticky-item">
       <slot name="title"></slot>
     </div>
   </div>
</template>
```
父组件
```
<template>
   <div class="wrapper">
     <Sticky>
       <div slot="title">
         标题是：{{title}}
       </div>
    </Sticky>
   </div>
</template>
<script>
import Sticky from '@/components/sticky';
export default {
  components: {
    Sticky
  },
  data() {
    return {
      title: 123
    };
  }
};
</script>
```

**观察到的表现：**

title并不会被渲染，这应该是个老问题，不知道升级到哪个版本可以解决此问题？

**截图或动态图：**

![image](https://user-images.githubusercontent.com/22902187/55696792-27216080-59f1-11e9-818c-155e753e5459.png)

**Comment by sunshineroper** [comment]
- -和你一样的问题。。我升级到最新的 mapvue2.0.5都不行 @Pasoul
