### ISSUE TITLE
v-for的key值绑定不能使用方括号

### ISSUE THREAD

**Issue by niaodan2b** [Meituan-Dianping/mpvue#1539]
## [扼要问题描述]
v-for的key值绑定不能使用方括号

以下代码运行正常：
`<li v-for="item in list" :key="item.id"></li>`

换成以下写法，整个项目无法运行，报错“missing ) after argument list”：
`<li v-for="item in list" :key="item['id']"></li>`

仔细翻阅了文档，未发现相关的说明，不知道是bug还是已知的限制

**mpvue 版本号：**

[mpvue@2.0.0]

**Comment by niuyongchang** [comment]
用item.id呢

**Comment by niaodan2b** [comment]
> 
> 
> 用item.id呢

item.id是可以的，见我第一个例子，但有时候属性名带"-"，比如item['v-key']，就不能用点号了

**Comment by hucq** [comment]
:key 这个属性是小程序的实现，微信小程序也不支持这种写法。[参考官方文档](https://developers.weixin.qq.com/miniprogram/dev/framework/view/wxml/list.html)，这个值只能是：
1. 属性名字符串
2. 保留关键字 *this
