### ISSUE TITLE
后台是Django，mpvue小程序提交表单时如何获取csrf_token?

### ISSUE THREAD

**Issue by JasonHXiang** [Meituan-Dianping/mpvue#154]
# [问题简单描述]
后台是Django，使用mpvue进行表单提交时如何获取csrf_token？
**问题复现步骤:**

1. 后台Django制作了一个接口，用于接受前台的表单POST提交
2. 小程序中组装数据之后，POST到该接口，将会返回一个html，内容是CSRF跨域禁止访问。
3. 在web上，可以使用document.cookie等一系列操作可以获取到csrf_token，与表单数据一起传到后台，可以完成正常POST操作

**期望的表现:**

目前希望小程序是否有可能直接通过方法获取到csrf_token，与表单数据一起提交到接口。

**观察到的表现:**

如上描述2条

**Comment by hucq** [comment]
建议这位同学仔细了解下微信小程序对服务端接口和域名的规则要求，小程序中并没有cookie机制。
mpvue 框架本身并不对http请求做任何包装和扩展。你提到的这个问题，是一个纯后端问题。
