### ISSUE TITLE
怎么关闭css转wxss的功能

### ISSUE THREAD

**Issue by imgss** [Meituan-Dianping/mpvue#1552]
## 给rich-text节点添加的样式被转换

**mpvue 版本号：**

[mpvue@1.0.18]

**最小化复现代码：**

```html
<template>
<rich-text nodes="<strong>st<strong>"></rich-text>
</template>

<style>
strong{
  color: red;
}
</style>
```

**问题复现步骤：**

1. [第一步]
2. [第二步]
3. [其它...]

**观察到的表现：**

`strong` 被转换成 `._strong`，导致rich-text节点样式失效

**Comment by hucq** [comment]
你使用的 `strong` 标签名和 HTML 的重名了，目前所有HTML内置标签我们都会默认转换，对应的css选择器也会同步修改。你自定义一个标签名就行了。

**Comment by imgss** [comment]
这个问题不是很大。我用 `htmlStr.replace` 给strong标签加了一个 `_strong` 的class
