### ISSUE TITLE
引入任何小程序插件后 页面中请求后push数组不会再重新渲染页面

### ISSUE THREAD

**Issue by yfcool** [Meituan-Dianping/mpvue#1554]
> ## app.json中的plugins对象中只要添加一个插件的对象，所有页面中的push或set都不再会重新使页面渲染，必须forceUpdate强制刷新后才能显示数据样式。如果删除了app.json中的plugins对象后又恢复渲染
> **mpvue 版本号：
> 
> [mpvue@1.0.11] / [mpvue@1.4.0]

**Comment by yfcool** [comment]
> ## app.json中的plugins对象中只要添加一个插件的对象，所有页面中的push或set都不再会重新使页面渲染，必须forceUpdate强制刷新后才能显示数据样式。如果删除了app.json中的plugins对象后又恢复渲染
> **mpvue 版本号：
> 
> [mpvue@1.0.11] / [mpvue@1.4.0]
> 
> **最小化复现代码： "plugins": { "tencentvideo": { "version": "1.2.4", "provider": "wx******************"
> }
> }

**Comment by xywai1993** [comment]
我去，这个问题真的存在,所有对数组修改的方法都不会更新组件

**Comment by xywai1993** [comment]
> > ## app.json中的plugins对象中只要添加一个插件的对象，所有页面中的push或set都不再会重新使页面渲染，必须forceUpdate强制刷新后才能显示数据样式。如果删除了app.json中的plugins对象后又恢复渲染
> > **mpvue 版本号：
> > [mpvue@1.0.11] / [mpvue@1.4.0]
> > **最小化复现代码： "plugins": { "tencentvideo": { "version": "1.2.4", "provider": "wx******************"
> > }
> > }

想问问老铁有没有解决这个问题

**Comment by uhr** [comment]
调了一上午，原来坑埋得这么深。数组的方法应该都不行了，得重新赋值this.arr = [...this.arr]

**Comment by yfcool** [comment]
> > > ## app.json中的plugins对象中只要添加一个插件的对象，所有页面中的push或set都不再会重新使页面渲染，必须forceUpdate强制刷新后才能显示数据样式。如果删除了app.json中的plugins对象后又恢复渲染
> > > **mpvue 版本号：
> > > [mpvue@1.0.11] / [mpvue@1.4.0]
> > > **最小化复现代码： "plugins": { "tencentvideo": { "version": "1.2.4", "provider": "wx******************"
> > > }
> > > }
> 
> 想问问老铁有没有解决这个问题

我现在的方案很蠢，就是用forceUpdate强制刷新，应该是底层机制有问题。

**Comment by xywai1993** [comment]
> > > > ## app.json中的plugins对象中只要添加一个插件的对象，所有页面中的push或set都不再会重新使页面渲染，必须forceUpdate强制刷新后才能显示数据样式。如果删除了app.json中的plugins对象后又恢复渲染
> > > > **mpvue 版本号：
> > > > [mpvue@1.0.11] / [mpvue@1.4.0]
> > > > **最小化复现代码： "plugins": { "tencentvideo": { "version": "1.2.4", "provider": "wx******************"
> > > > }
> > > > }
> > 
> > 
> > 想问问老铁有没有解决这个问题
> 
> 我现在的方案很蠢，就是用forceUpdate强制刷新，应该是底层机制有问题。

我这不能这么干，因为页面太多了。哎，不知道引用小程序插件的源码在哪一行

**Comment by xywai1993** [comment]
此项目是不是没人维护了

**Comment by cytle** [comment]
被坑+1天，实际上这是微信的坑。使用插件的`Array.prototype`和正常的是不一样的

### 正常的Array.prototype

![image](https://user-images.githubusercontent.com/5120505/58324088-6d733780-7e58-11e9-8f5f-481b23f55213.png)

### 使用插件的Array.prototype

![image](https://user-images.githubusercontent.com/5120505/58324071-5c2a2b00-7e58-11e9-9b4c-3c78077a46e2.png)

**Comment by uhr** [comment]
> 被坑+1天，实际上这是微信的坑。使用插件的`Array.prototype`和正常的是不一样的
> 
> ### 正常的Array.prototype
> ![image](https://user-images.githubusercontent.com/5120505/58324088-6d733780-7e58-11e9-8f5f-481b23f55213.png)
> 
> ### 使用插件的Array.prototype
> ![image](https://user-images.githubusercontent.com/5120505/58324071-5c2a2b00-7e58-11e9-9b4c-3c78077a46e2.png)

被重写了是吧

**Comment by cytle** [comment]
> **TL;DR** 根据下面运行情况，猜测：在微信小程序使用插件时候，数组创建时候，数组的方法会被重新赋值一次，而不是原型继承，造成使用`__proto__`继承的`Vue`响应式数组没法按预期执行。

分别在未使用插件和使用插件(App.json中有plugins字段)的情况下执行下面代码

``` js
const arrayProto = Array.prototype
const arrayMethods = Object.create(arrayProto)
Object.defineProperty(arrayMethods, 'push', { 
  value(...args) {
    console.log('Modified push', args)
  }, 
  enumerable: false,
    writable: true,
    configurable: true
})
arrayMethods.aaaaaa = 'arrayMethods' // 做个标记
const foo = [];
foo.__proto__ = arrayMethods
foo.push(100) // 未使用插件: Modified push ; 使用插件: 和Array.prototype.push一样
```

这时候可以打印下`foo`变量

**未使用插件的foo**

![image](https://user-images.githubusercontent.com/5120505/58393784-db934680-8072-11e9-8a1f-193c369ecedb.png)

**使用插件的foo**

![image](https://user-images.githubusercontent.com/5120505/58393944-928fc200-8073-11e9-9f21-552190847f0d.png)

由上可知，使用插件时候，**所有数组实例都会直接挂载数组方法（覆盖隐式原型__proto__没用）**

另外如果你去打印`foo.__proto__ === arrayMethods`，值是true，不过隐式原型并没有被覆盖（这不重要哈）

``` js
foo.__proto__ === arrayMethods // true
```

源码([core/observer/index.js#L48-L51](https://github.com/Meituan-Dianping/mpvue/blob/master/src/core/observer/index.js#L48-L51))可知`Vue`在覆盖数组方法时候，会有两种情况

1. 如果支持隐式原型(即`hasProto = '__proto__' in {}`为true)，则通过覆盖隐式原型
2. 否则，直接覆盖数组对象方法

无论在什么情况下，小程序`hasProto`都为true，但又无法通过覆盖隐式原型，把数组方法替换为响应式方法，因此造成响应式数组没法按预期执行

**Comment by xywai1993** [comment]
这个bug什么时候可以发布新版本修复呀

**Comment by buyijiuyang** [comment]
我也想知道 这个问题什么时候能够解决 …新手入坑太不友好了
