### ISSUE TITLE
配置plugins后页面数组不渲染

### ISSUE THREAD

**Issue by NinjaJin** [Meituan-Dianping/mpvue#1558]
## [扼要问题描述]

**mpvue 版本号：**

[mpvue@1.4.0]

**最小化复现代码：**

```
// 示例代码：
methods: {
    getReadList() {
        this.bookList = [];
        request(`book/all`, "GET").then(res => {
            if (res.status == 1000) {
                res.content.forEach(item => {
                    this.bookList.push(item)
                });
            }
        });
    }
},
onLoad() {
    this.getReadList();
}
```

**问题复现步骤：**

在A页面onLoad时请求接口并赋值渲染，代码如上
在app.json中配置了plugins后，这种写法页面渲染不出bookList的数据。
如果在请求回调中不通过forEach循环，直接this.bookList = res.content能正常渲染。
很困惑，这到底是什么原因呢？

**Comment by hucq** [comment]
数据增量更新的 diff 算法问题，我们在2.0上修复了这个问题，和后续几个问题修复后一起同步到 1.4 上。
暂时先用直接赋值的方式吧。后续关注版本更新。
