### ISSUE TITLE
请问mpvue2.0，如何动态修改app.json

### ISSUE THREAD

**Issue by Newgar** [Meituan-Dianping/mpvue#1559]
问题描述：因为2.0在src 和每个page里添加了app.json和main.json，个人尝试在src的main.js里写
export default {
  config: {}
}
发现不起作用，请问除了降版本以外，mpvue2.0能够使用之前的在main.js里配置app.json的方法或者有别的方法动态修改app.json么

mpvue版本：2.0

**Comment by hucq** [comment]
mpvue 2.0 中对 app.json 的配置集中到 app.json 文件中。
app.json 从来都不支持动态配置，原先是在构建阶段提取规则后生成的这个文件，现在统一到一个地方集中修改了。
