### ISSUE TITLE
mpvue2.0 如何使用断点调试文件？

### ISSUE THREAD

**Issue by syyzz3** [Meituan-Dianping/mpvue#1563]
![QQ截图20190421183458](https://user-images.githubusercontent.com/11385973/56469188-d2f29380-6468-11e9-9095-f52d31433113.png)
之前的版本默认在source下\\webpack中会有可调试断点的文件，为什么在新版本中没有了？
该在如何进行配置？

**Comment by love999262** [comment]
build/webpack.conf.js下（DEV模式）加一项 devtool: 'source-map',

**Comment by syyzz3** [comment]
@love999262 为什么我看到webpack.conf.js中有devtool: '#source-map'的注释代码。
这个#号有什么作用？

**Comment by love999262** [comment]
可以删掉#

**Comment by syyzz3** [comment]
@love999262 您好，您有没有遇到过断点设置不准的情况，比如说点击选择“28”行，实际上跑到“30”行的这种情况？

**Comment by love999262** [comment]
可以试试devtool: 'cheap-module-source-map',

**Comment by syyzz3** [comment]
@love999262 谢谢

**Comment by syyzz3** [comment]
@love999262 您好，我设置了devtool: 'cheap-module-source-map',之后，就报eval is not a function的错误，是什么原因呢？

**Comment by spiritelf** [comment]
> @love999262 您好，您有没有遇到过断点设置不准的情况，比如说点击选择“28”行，实际上跑到“30”行的这种情况？

我也是遇到这样情况。。解决了吗？

**Comment by spiritelf** [comment]
> @love999262 您好，我设置了devtool: 'cheap-module-source-map',之后，就报eval is not a function的错误，是什么原因呢？

也是一样。。有人解决了吗？
