### ISSUE TITLE
npm run dev卡着不动

### ISSUE THREAD

**Issue by jetBn** [Meituan-Dianping/mpvue#1564]
## [npm run dev 后卡在 node build/dev-server.js wx]

**mpvue 版本号：2.0.0

[mpvue@2.0.0]

**观察到的表现：一直卡在 node build/dev-server.js wx

**截图或动态图：**
![TIM截图20190422100955](https://user-images.githubusercontent.com/26957220/56479267-273c5880-64e7-11e9-9b16-a6d7cadcc8ad.png)
![TIM截图20190422101021](https://user-images.githubusercontent.com/26957220/56479269-2c010c80-64e7-11e9-8496-6e4dae35111f.png)
![TIM截图20190422101013](https://user-images.githubusercontent.com/26957220/56479273-2e636680-64e7-11e9-9eaf-63cfbc940770.png)

**Comment by shrekuu** [comment]
@jetBn  会不会跟电脑配置有关呢? 截图下你电脑配置来看看吧.

**Comment by jetBn** [comment]
> @jetBn 会不会跟电脑配置有关呢? 截图下你电脑配置来看看
解决了 ，，公司的电脑硬盘有问题。
