### ISSUE TITLE
mpvue dev:wx 打包过大导致无法预览

### ISSUE THREAD

**Issue by lenvonsam** [Meituan-Dianping/mpvue#1566]
## [扼要问题描述]
用了最新的mpvue/mpvue-quickstart创建项目，在项目写到一半的时候，想预览就报打包超过2M，用npm run dev:wx启动的项目
**mpvue 版本号：**
2.0.0
[mpvue@x.x.x]
"mpvue-loader": "^2.0.0",
"mpvue-template-compiler": "^2.0.0",
"mpvue-webpack-target": "^1.0.3",

**截图或动态图：**
![image](https://user-images.githubusercontent.com/10168476/56627772-c98c4580-6679-11e9-902c-83c6d33fd564.png)

**Comment by lenvonsam** [comment]
有没有大佬能解决这个问题

**Comment by ChickenBreast** [comment]
> 有没有大佬能解决这个问题，急着用，在线等~~~

你是不是放太多图片文件(而且体积还不小)进static里了?

**Comment by lenvonsam** [comment]
![image](https://user-images.githubusercontent.com/10168476/56710463-ddf33f80-6758-11e9-9f10-f4a22b38f4d4.png)
@ChickenBreast 一共就这几张图片。。。

**Comment by lenvonsam** [comment]
![image](https://user-images.githubusercontent.com/10168476/56710541-4510f400-6759-11e9-9870-965158959c80.png)
@ChickenBreast vendor为啥这么大。。。

**Comment by ChickenBreast** [comment]
> ![image](https://user-images.githubusercontent.com/10168476/56710541-4510f400-6759-11e9-9870-965158959c80.png)
> @ChickenBreast vendor为啥这么大。。。

我没遇过这种情况诶,我之前是因为static图片放太多,  你这个会不会是因为有引用过大于500k的js文件?

**Comment by lenvonsam** [comment]
mpvue支持subpackages吗
@ChickenBreast

**Comment by xywai1993** [comment]
@lenvonsam  这个问题我也遇到过， 解决办法是修改webpack配置，使的支持 subpackages 。
我的配置如下：

在 webpack.base.conf.js 的基础上修改如下
`

function getEntry(rootSrc, paths) {
    var map = {};
    glob.sync(rootSrc + paths).forEach(file => {
        var key = relative(rootSrc, file).replace('.js', '');
        map[key] = file;
    });
    return map;
}

const appEntry = { app: resolve('./src/main.js') };
const pagesEntry = getEntry(resolve('./src'), '/pages/**/main.js');
const pagesEntryB = getEntry(resolve('./src'), '/packageb/pages/**/main.js');
const entry = Object.assign({}, appEntry, pagesEntry, pagesEntryB);
`

src 目录下 新建  /packageb/pages/  文件夹 作为分包的页面  ，

然后app.json 也同样设置分包的参数就可以了。

**Comment by xywai1993** [comment]
@lenvonsam  还有一种简单的操作 ， Dev环境也 压缩代码~~

**Comment by lenvonsam** [comment]
dev 压缩代码是什么意思，vendor不就是帮你压缩代码了吗？
@xywai1993

**Comment by xywai1993** [comment]
@lenvonsam  那是混淆了，并没有进一步压缩

**Comment by daisygogogo** [comment]
@lenvonsam  把dist文件删除，然后重新打包，npm run build，我之前遇到过

**Comment by LauJon** [comment]
> > ![image](https://user-images.githubusercontent.com/10168476/56710541-4510f400-6759-11e9-9870-965158959c80.png)
> > @ChickenBreast vendor为啥这么大。。。
> 
> 我没遇过这种情况诶,我之前是因为static图片放太多, 你这个会不会是因为有引用过大于500k的js文件?

请问最后怎么解决的？

**Comment by lenvonsam** [comment]
> > > ![image](https://user-images.githubusercontent.com/10168476/56710541-4510f400-6759-11e9-9870-965158959c80.png)
> > > @ChickenBreast vendor为啥这么大。。。
> > 
> > 
> > 我没遇过这种情况诶,我之前是因为static图片放太多, 你这个会不会是因为有引用过大于500k的js文件?
> 
> 请问最后怎么解决的？

把dist文件删除，然后重新打包，npm run build，我之前遇到过

**Comment by Jane-blog** [comment]
不丑化代码情况下，怎么给vendor拆包，有知道的吗？
