### ISSUE TITLE
No parser and no filepath given, using 'babel' the parser now but this will throw an error in the future. Please specify a parser or a filepath so one can be inferred.

### ISSUE THREAD

**Issue by Adgeros** [Meituan-Dianping/mpvue#1567]
运行报错：
No parser and no filepath given, using 'babel' the parser now but this will throw an error in the future. Please specify a parser or a filepath so one can be inferred.

虽然没有影响构建，但是这个是什么问题呢

**Comment by Michel-Yang** [comment]
遇到同样的问题？楼主是否已解决

**Comment by Adgeros** [comment]
> 遇到同样的问题？楼主是否已解决

未解决

**Comment by Michel-Yang** [comment]
我是在升级到2.0版本时，遇到这个问题。项目可以正常构建。但是会有这个提示

**Comment by Adgeros** [comment]
> 我是在升级到2.0版本时，遇到这个问题。项目可以正常构建。但是会有这个提示

一样的
