### ISSUE TITLE
Flex布局,设置flex属性按比例(权重)布局,box-sizing: border-box无效

### ISSUE THREAD

**Issue by phoenixsky** [Meituan-Dianping/mpvue#1568]
## [扼要问题描述]
Flex布局,设置flex属性按比例(权重)布局,如果设置了padding或者margin,就会超出比例部分,同时设置box-sizing: border-box无效
**mpvue 版本号：2.00

**最小化复现代码：**
```
<template>
  <div>
    <div style="width: 10rem;background-color: #2196F3">
      我是一半宽度(10rem),用来校准
    </div>

    <div style="display: flex;flex-direction: row;">
      <div style="flex: 1;box-sizing: border-box;background-color: gray">我flex1,没有padding</div>
      <div style="flex: 1;box-sizing: border-box;background-color: gold;padding: 0 10px">我flex1,有padding</div>
    </div>
    <div style="width: 10rem;background-color: #2196F3;padding:0 10px;box-sizing: border-box">
      我是一半宽度,设置了padding
    </div>
  </div>
</template>
```
**截图或动态图：**
![image](https://user-images.githubusercontent.com/6359214/56646659-8bf7de80-66b2-11e9-9d7d-8e75587c9ad0.png)

**Comment by Dewyzee** [comment]
这应该不是框架本身的原因，flex布局本身计算比较复杂，可以参考以下进行理解：
https://teamtreehouse.com/community/does-boxsizing-borderbox-work-with-flexbox
https://stackoverflow.com/questions/37353792/flex-basis-and-box-sizing
https://stackoverflow.com/questions/34753491/how-does-flex-shrink-factor-in-padding-and-border-box
