### ISSUE TITLE
在 template 内使用 methods 中的函数，无法显示返回值

### ISSUE THREAD

**Issue by blade254353074** [Meituan-Dianping/mpvue#157]
# [问题简单描述]

**问题复现步骤:**

```js
import { currencyParse } from '@/utils/price-parse' // 货币格式化

export default {
  data () {
    return {
      list: []
    }
  },
  methods: {
    timeParse,
    currencyParse,
    console: console.log
  }
}
```

```html
<template>
  <div class="order-price">¥ {{ currencyParse(item.price) }}</div>
</template>
```

**期望的表现:**

render => `<div class="order-price">¥ 233.00</div>`

**观察到的表现:**

render => `<div class="order-price">¥ </div>`

**屏幕截图和动态 GIF 图**

![image](https://user-images.githubusercontent.com/9346008/37722425-f46e56aa-2d66-11e8-825b-d60bf2d651cb.png)

![image](https://user-images.githubusercontent.com/9346008/37722454-04669d38-2d67-11e8-93a7-88966683854d.png)

**Comment by blade254353074** [comment]
这个 bug 很尴尬啊。。。

**Comment by aOrz** [comment]
因 wxml 的限制，不支持此特性

**Comment by JessYan0913** [comment]
那么这样的需求怎么解决
