### ISSUE TITLE
mpvue-simple工具支持mpvue2.0吗？

### ISSUE THREAD

**Issue by superSheng11** [Meituan-Dianping/mpvue#1578]
##最近想用mpvue实现支付宝、微信、头条小程序的开发，但是项目是已经存在的旧项目，打算先让一部分功能通过 mpvue 编写，于是看到了官方文档推荐mpvue-simple，发现自己下载下mpvue-simple根本无法启动项目，一推报错，发现mpvue-simple依赖的mpvue是1.x，并不是最新的mpvue2.x,不知道是自己理解写法有问题，还是mpvue-simple只支持mpvue1.0？

**Comment by Dewyzee** [comment]
@superSheng11 抱歉目前还未支持到2.x版本，1.x版本报错的话，可以尝试将mpvue以及mpvue-template-compiler版本控制在1.0.18以内
