### ISSUE TITLE
切换回原页面后 mounted 无法再次触发

### ISSUE THREAD

**Issue by ahan** [Meituan-Dianping/mpvue#1580]
## [扼要问题描述]

**mpvue 版本号：**

[mpvue@2.0.0]

**最小化复现代码：**

```
  mounted () {
    console.log('mounted')
  }
```

**问题复现步骤：**

1. [第一步]
使用官方` mpvue-quickstart` 创建干净项目，`vue init mpvue/mpvue-quickstart my-project`
2. [第二步]
在 `./my-project/src/pages/index/index.vue` 的 `mounted` 块里添加` console.log()` 印记
3. [其它...]
打开微信开发者工具，切换去别的页面后，再切回 index 页面

**观察到的表现：**

`mounted` 只输出一次

**截图或动态图：**

![QQ20190506-195634](https://user-images.githubusercontent.com/654880/57223563-176d5a00-7039-11e9-9412-85b697049726.png)

**Comment by ChickenBreast** [comment]
tab切换和 使用 navigateTo, 因为页面没有被卸载, 所以返回时mounted不会执行, 但是小程序的onLoad onShow会执行

**Comment by ahan** [comment]
> tab切换和 使用 navigateTo, 因为页面没有被卸载, 所以返回时mounted不会执行, 但是小程序的onLoad onShow会执行

我是看到 mpvue 官网文档中提到 
> 除了 Vue 本身的生命周期外，mpvue 还兼容了小程序生命周期，这部分生命周期钩子的来源于微信小程序的 Page， 除特殊情况外，不建议使用小程序的生命周期钩子。
> [](http://mpvue.com/mpvue/)

我要的钩子是每次来到页面触发一次，不知在 mpvue 中是用哪种钩子，或是只能采用 onShow 了？

**Comment by ChickenBreast** [comment]
> @ChickenBreast 我是看到 mpvue 官网文档中提到
> 
> > 除了 Vue 本身的生命周期外，mpvue 还兼容了小程序生命周期，这部分生命周期钩子的来源于微信小程序的 Page， 除特殊情况外，不建议使用小程序的生命周期钩子。
> > [实例生命周期](http://mpvue.com/mpvue/)
> 
> 我要的钩子是每次来到页面触发一次，不知在 mpvue 中是用哪种钩子，或是只能采用 onShow 了？

之前写错了，返回的时候onLoad也不会执行，只会执行onShow。所以如果是每次回到页面都要执行的话，只能onShow了

**Comment by ChickenBreast** [comment]
@ahan  之前写错了，返回的时候onLoad也不会执行，只会执行onShow。所以如果是想要每次回到页面都要执行的钩子话，只能onShow了

**Comment by Dewyzee** [comment]
@ChickenBreast ，小程序打开新页面会创建一个页面栈。例如入口页面为A，从A->B会新增一个B的页面栈，A继续存在，A触发onHide，B触发一些列生命周期钩子。从B回退到A，B页面栈销毁，A页面触发onShow，不再重新创建实例，采用mpuve框架的场景同样也不会重新执行一遍生命钩子函数
