### ISSUE TITLE
v-for循环自定义组件插糟不能用模板语法

### ISSUE THREAD

**Issue by sunshineroper** [Meituan-Dianping/mpvue#1583]
## [扼要问题描述]

**mpvue 版本号：**

[mpvue@2.0.5]

**最小化复现代码：**

[建议提供最小化可运行的代码：附件或文本代码]

```
// 自定义组件
<panel>
 <slot></slot>
</panel>

调用的时候

<panel v-for="i in 3">{{i}}</panel>
```

**问题复现步骤：**

  @@自定义组件内的内容不显示
**观察到的表现：**

[在这里描述观察到的表现]

**截图或动态图：**

![复现步骤截图或gif图片](图片的 url)

**Comment by xfantasy** [comment]
我也遇到这个问题了，后面把solt去掉就好了，好蛋痛
