### ISSUE TITLE
微信小程序用v-html渲染出富文本 但是 支付宝小程序html有内容 但没有渲染出来

### ISSUE THREAD

**Issue by alohajeanne** [Meituan-Dianping/mpvue#1588]
issueConfigs:
  -
    bannedTitle: "can not show rich-text in alipay miniprogram "
    subtitles:
      - "问题复现步骤：" 使用 <div v-html="richText" :style="scale"></div> ; richText是富文本内容
      - "期望的表现：" 支付宝/微信 都渲染出富文本
      - "观察到的表现：" 微信渲染出 但是支付宝没有
      - "屏幕截图或动态图："
    bannedContents:
      - "第一步"
      - "第二步"
      - "其他步骤..."
      - "在这里描述期望的表现"
      - "在这里描述观察到的表现"
      - "复现步骤的屏幕截图和动态 GIF 图"
      - "图片的 url",
      - "建议提供可运行的demo"
  -
    bannedTitle: "在此简单描述您的建议"
    subtitles:
      - "新功能相关的问题issue或讨论："
      - "新功能的实现："
      - "相关项目或文档："
    bannedContents:
      - "在这里引用新功能相关的讨论"
      - "在这里填写或简单描述功能的实现方式或需求的解决方式"
      - "在这里引用相关项目或文档地址"

comments:
  closeIssue: "issue不符合格式要求，请确保格式正确且填写所有有效信息。\n请保留issue模板中的各级小标题（如“期望的表现：”），并使用有效信息替换模板默认内容（如“[在这里描述期望的表现]”）"

**Comment by Dewyzee** [comment]
微信小程序富文本支持Array以及String类型，支付宝仅支持Array，如果要兼容到两个平台，建议遵循两个平台规范写，如下：
```javascript
export default {
   data() {
     return {
         richText: [{
           name: 'div',
           attrs: {
             class: 'test_div_class',
             style: 'color: green;'
           },
          children: [{
            type: 'text',
            text: 'Hello&nbsp;World! This is a text node.'
          }]
       }]
     }
   }
}
