### ISSUE TITLE
mpvue文档错别字

### ISSUE THREAD

**Issue by JoviCheng** [Meituan-Dianping/mpvue#159]
# [问题简单描述]
http://mpvue.com/qa/

"因为 webpack 编译的文件使用配置的 entry 决定的，新增的页面并**没用**添加进 entry，所以需要手动 npm run dev 一下，考虑不是高频操作，所以还可以忍受"

**问题复现步骤:**

1. [第一步]
2. [第二步]
3. [其他步骤...]

**期望的表现:**

[在这里描述期望的表现]

**观察到的表现:**

[在这里描述观察到的表现]

**屏幕截图和动态 GIF 图**
![image](https://user-images.githubusercontent.com/8762574/37725435-eadae318-2d6d-11e8-9660-40a355ad75e7.png)

![复现步骤的屏幕截图和动态 GIF 图](图片的 url)

**Comment by aOrz** [comment]
已修改，感谢
