### ISSUE TITLE
组件样式不生效

### ISSUE THREAD

**Issue by zhiguoliang** [Meituan-Dianping/mpvue#160]
组件代码：
![image](https://user-images.githubusercontent.com/26423212/37748709-d335956c-2dbf-11e8-8d00-ddc23201a377.png)

在微信开发者工具上显示效果：
![image](https://user-images.githubusercontent.com/26423212/37748555-356a5dea-2dbf-11e8-9ccc-fa7d45251b62.png)
，这个组件在首页引用的时候组件css样式生效，当在其它页面引用的时候都没办法编译出css

**Comment by weineel** [comment]
你可以说参考下这个：[issue #7](https://github.com/Meituan-Dianping/mpvue/issues/7)

**Comment by zhiguoliang** [comment]
感谢，已经解决
