### ISSUE TITLE
自定义组件属性默认值失效的问题。

### ISSUE THREAD

**Issue by weineel** [Meituan-Dianping/mpvue#161]
# 问题简单描述

> 自定义组件属性默认值问题。

1. 使用组件时，传递了属性，导致默认值失效。
2. 如果在使用组件时，不传递属性，默认值是起作用的。
3. 在进行网络请求时，要显示一个默认值（有时候是数组的长度），导致报错。

**Comment by anchengjian** [comment]
你在 index page 中 card 的 text 字段只传了一个空对象， text.arr 当然为 undefined ，text.arr.length 应该就报错了吧。

**Comment by weineel** [comment]
感谢
