### ISSUE TITLE
typescript 支持不?

### ISSUE THREAD

**Issue by yishenggudou** [Meituan-Dianping/mpvue#162]
想咨询下作者有计划 支持 typescript 吗

**Comment by aOrz** [comment]
貌似可以用 ts，参考： https://github.com/WingGao/mpvue-ts-demo

**Comment by zhangchen91** [comment]
这个 demo 试了下，有 bug 啊
https://github.com/WingGao/mpvue-ts-demo/issues/3

**Comment by thundernet8** [comment]
@zhangchen91 可以试下我写的[脚手架](https://github.com/thundernet8/generator-mpvue-project)，支持生成js/ts的，我修改了mpvue-loader, 以支持ts，同时做了通用能力的上层抽象为[common-mpvue](https://github.com/thundernet8/common-mpvue)
