### ISSUE TITLE
是否支持微信的websocket

### ISSUE THREAD

**Issue by fangsj** [Meituan-Dianping/mpvue#1621]
## 项目需要支持mqtt 的websocket，不知道websocket是否支持微信的支付宝的

**新功能相关的问题issue或讨论：**
我在文档内没有找到关于websocket的相关描述，故想询问一下官方是否支持？

**Comment by cytle** [comment]
`mpvue`是`view`库，`websocket`还是官方的api的使用方法啊

- `sokcet.io`跨端可以考虑下 https://github.com/cytle/socket.io-mp-client
- `websocket` 可以考虑下 小程序websocket实现 https://github.com/cytle/mp-websocket
