### ISSUE TITLE
通过push、splice操作数组没有及时将数据渲染到页面

### ISSUE THREAD

**Issue by 313224646** [Meituan-Dianping/mpvue#1624]
## [扼要问题描述]

**mpvue 版本号：**

[mpvue@2.0.0]

**最小化复现代码：**

[建议提供最小化可运行的代码：附件或文本代码]

```
// 示例代码：
<template>
  <div v-for="(item, index) in test" :key="index">{{item}}</div>
  <button @click="test.push(1)">add</button>
</template>
export default {
  data () { return { test: [] } }
}
```

**观察到的表现：**

通过push、splice操作数组没有及时将数据渲染到页面，微信开发者工具上，ios和安卓都一样。我记得以往，都是正常。

**截图或动态图：**
![demo3](https://user-images.githubusercontent.com/26915351/58775548-97ff8600-85f8-11e9-9a85-e7c8817a5dad.gif)

**Comment by zhaixiyun** [comment]
试试this.$forceUpdate()强制更新

**Comment by Dewyzee** [comment]
升到2.0.5试下

**Comment by 313224646** [comment]
> 试试this.$forceUpdate()强制更新

嗯，这方法可以解决这个问题。

**Comment by 313224646** [comment]
> 升到2.0.5试下
 
"mpvue": "^2.0.6"
"mpvue-loader": "^2.0.1"
"mpvue-template-compiler": "^2.0.6"

我升到了上面的版本，结果还是原来那样。
