### ISSUE TITLE
tabbar中调用wx.reLaunch只关闭了当前tabbar，其他的没关

### ISSUE THREAD

**Issue by guoshiqiufeng** [Meituan-Dianping/mpvue#1629]
## [tabbar中调用wx.reLaunch只关闭了当前tabbar，其他的没关]

**mpvue 版本号：**

[mpvue@2.0.5]

**问题复现步骤：**

1. [第一步] 有三个页面，登陆页和两个tabbar页面：首页、功能页
2. [第二步] 打开首页、功能页，在功能页调用wx.reLaunch到登陆页面
3. [其它...] 在微信开发工具中功能页关闭了，首页还在

**Comment by Dewyzee** [comment]
@guoshiqiufeng 没有太明白你所描述的首页还在是什么情况，可以贴下相关的代码与截图～～本地验证调用reLaunch后只保留一个页面栈
![image](https://user-images.githubusercontent.com/4916726/59248401-e0e8b780-8c54-11e9-89c0-e9e7adb91b19.png)

**Comment by guoshiqiufeng** [comment]
我刚新建了一个demo试了下，发现退出后确实只有login的页面栈
![image](https://user-images.githubusercontent.com/15354567/59249591-b9471e80-8c57-11e9-99a9-75c57ca001c2.png)
这个是现在项目中的，不同的地方就是退出登录用的弹窗
![image](https://user-images.githubusercontent.com/15354567/59249837-4e4a1780-8c58-11e9-8757-8041d941a256.png)
![image](https://user-images.githubusercontent.com/15354567/59249791-2bb7fe80-8c58-11e9-9652-d47219d1b307.png)
那应该是弹窗的问题吧，我改改看看

**Comment by guoshiqiufeng** [comment]
@Dewyzee 有点搞不懂了，
app.json
![image](https://user-images.githubusercontent.com/15354567/59251092-8d2d9c80-8c5b-11e9-84c5-b78586453ceb.png)
login页面
![image](https://user-images.githubusercontent.com/15354567/59251132-a59db700-8c5b-11e9-999e-3506c842ce02.png)
![image](https://user-images.githubusercontent.com/15354567/59251152-b2220f80-8c5b-11e9-9b70-5400541a1e42.png)
首页
![image](https://user-images.githubusercontent.com/15354567/59251173-bcdca480-8c5b-11e9-9641-d1568216fe07.png)
![image](https://user-images.githubusercontent.com/15354567/59251185-c5cd7600-8c5b-11e9-8ed8-56bea966a66d.png)
我的页面
![image](https://user-images.githubusercontent.com/15354567/59251213-d5e55580-8c5b-11e9-83fa-0323bc77a11a.png)
![image](https://user-images.githubusercontent.com/15354567/59251225-dd0c6380-8c5b-11e9-8d55-cef7751d5277.png)
点击退出登录
![image](https://user-images.githubusercontent.com/15354567/59251240-ebf31600-8c5b-11e9-889d-fc5ab010b461.png)

**Comment by guoshiqiufeng** [comment]
@Dewyzee 我拷贝代码重新install，发现没事了
