### ISSUE TITLE
mpvue2如何生成支付宝小程序？

### ISSUE THREAD

**Issue by syyzz3** [Meituan-Dianping/mpvue#1634]
使用mpvue2在dist目录下生成了wx，为什么没有生成支付宝小程序的项目？
是需要配置什么吗？在官网并没有找到相应介绍。

**Comment by Dewyzee** [comment]
如果采用的quickstart创建的项目的话，package.json里有build:my的命令～如果没有话可以参考微信小程序构建的格式，新建一个命令就好

**Comment by syyzz3** [comment]
@Dewyzee 谢谢
