### ISSUE TITLE
[建议]入口文件可公用

### ISSUE THREAD

**Issue by bigmeow** [Meituan-Dianping/mpvue#164]
目前每一个页面都对应一个main.js文件，代码大致雷同，太繁琐了，个人认为只需要写一个即可，这样可以一个文件夹下放多个vue文件
至于每个页面的config配置，可以写到vue单文件组件里面；
另外可以增加一份配置文件，类似于vue-router的配置，配置好页面和对应的vue文件的关系，根据配置生成webpack入口配置，然后webpack-mpvue-asset-plugin 插件根据配置来生成相应的小程序文件

**Comment by aOrz** [comment]
main.js 除了初始化一个 vue 实例还可以有更多的操作
