### ISSUE TITLE
script不支持src的方式

### ISSUE THREAD

**Issue by WingGao** [Meituan-Dianping/mpvue#165]
如果在模板里面用src的方式，则无法解析components
```js
//xxx.vue
<template>
   <card></card>
</template>
<script src="./index.js"></script>
<style>
</style>
```

**Comment by ifuner** [comment]
我也提过这个问题

**Comment by syhsghr1993** [comment]
+1

**Comment by syhsghr1993** [comment]
@WingGao 尝试了直接在script里面引组件的方式可以解决此问题，实际上看了mpvue-loader的源码mpvue-loader/lib/mp-compiler第96行，只处理了script.content里的组件，没有处理src的组件
![image](https://user-images.githubusercontent.com/11493449/37822072-611e4fe4-2ec0-11e8-9d4c-bbbb9df23bd6.png)
