### ISSUE TITLE
微信小程序真机调试的问题，define is not defined

### ISSUE THREAD

**Issue by lawrsp** [Meituan-Dianping/mpvue#1665]
## [扼要问题描述]
新建一个项目，模拟器运行没有问题
使用二维码扫描真机调试，页面上主要内容是空白，只有title 和 底下的tabbar
并且调试界面有一堆报错，“define is not defined”

**mpvue 版本号：**

mpvue@2.0.6

**最小化复现代码：**

就是创建一个模版项目：
```
$ vue init mpvue/mpvue-quickstart my-project
$ cd my-project
$ npm install
$ npm run dev
```

**截图或动态图：**

<img width="590" alt="屏幕快照 2019-07-09 17 32 17" src="https://user-images.githubusercontent.com/7957003/60878417-3fb04980-a272-11e9-8e69-4f3db1ccb910.png">

**Comment by wangshun2018** [comment]
微信开发者工具的问题，升级一下

**Comment by dang221** [comment]
微信开发工具已经是最新版了，也还是不行

**Comment by sherpifer** [comment]
请问解决了吗 ，我也遇到了这个问题

**Comment by wanglin88207056** [comment]
升级微信开发者工具，以解决

**Comment by dang221** [comment]
> 请问解决了吗 ，我也遇到了这个问题

升级一下就解决了，如果已经是最新的话可以去升级到那个开发版的最新

**Comment by lawrsp** [comment]
解决了，微信开发者工具的问题，升级到最新的 nightly build 的版本

**Comment by immafrady** [comment]
已经升级，升级后第一次能打开，之后就再也开不了了……

**Comment by alinvin** [comment]
升级之后不能预览 报错 每个文件夹下的main.js找不到 求解决
