### ISSUE TITLE
关于@touchmove.stop这个方法、

### ISSUE THREAD

**Issue by zhoufanglu** [Meituan-Dianping/mpvue#1669]
我有个悬浮球 （移动悬浮球的时候会触发，下拉刷新操作）
我给页面加上了@touchmove，就不会触发了
但是不移动的时候，我还是需要能下拉刷新（**所以请问如何让@touchmove.stop这个方法失效！**）

![touchmove](https://user-images.githubusercontent.com/24451091/61272258-4cd0b980-a7d9-11e9-8332-8ab81497f02a.gif)

@touchmove.stop 这个方法内加return 也没用，请问如何才能失效！！！

**Comment by Dewyzee** [comment]
麻烦贴下相关的代码

**Comment by zhoufanglu** [comment]
> 麻烦贴下相关的代码

不好意思那么久没看到。
1、我现在有个悬浮球，往下拖动的时候会触发下拉刷新。
2、我在页面上加了`<div class="body" @touchmove.stop="touchMoveFn">`

加了`touchmove` 之后，页面不让拖动了。请问有什么解决方法吗？ 
**悬浮球下拉的时候不触发下拉刷新。**

**Comment by zhoufanglu** [comment]
问题已解决，是@touchMoveFn的问题，悬浮球@touchMovue阻止事件冒泡就可以了。
