### ISSUE TITLE
首次打开小程序时会自动调用所有页面的created方法

### ISSUE THREAD

**Issue by Kay0806** [Meituan-Dianping/mpvue#167]
# [问题简单描述]

**问题复现步骤:**

1. mpvue项目初始化
2. 分别在自带的三个页面中的created方法中打印log

**期望的表现:**

当前打开哪个页面显示哪个页面的log

**观察到的表现:**

一次性打印出所有页面的log

**Comment by Kay0806** [comment]
追加：整个小程序的生命周期也完全被打乱，onLoad和onReady在每次打开页面的时候都会被调用

**Comment by Kay0806** [comment]
或者说就是这么设计的？

**Comment by anchengjian** [comment]
小程序本身设计是会在刚打开的时候就初始化所有的 page，所以会直接触发 created 生命周期。

**Comment by Kay0806** [comment]
好的 谢谢
