### ISSUE TITLE
computed中方法带参数时，页面不能显示返回值

### ISSUE THREAD

**Issue by chengdu0839** [Meituan-Dianping/mpvue#1676]
## [扼要问题描述]

**computed中方法带参数时，页面不显示返回值**

**截图或动态图：
调用方式：{{test(111)}}**
![image](https://user-images.githubusercontent.com/8373897/61924782-e64b5880-af9b-11e9-8dcf-1e1075a01f61.png)

**Comment by Dewyzee** [comment]
mpvue暂不支持这样使用
