### ISSUE TITLE
使用elementUI时css编译错误

### ISSUE THREAD

**Issue by Mrli2016** [Meituan-Dianping/mpvue#168]
**问题复现步骤:**

引入elementUI 编译时出现错误（尝试过WeUI也一样，初步判断为样式问题）
**期望的表现:**

能正常使用普通UI

**观察到的表现:**
Fri Mar 23 2018 09:04:08 GMT+0800 (CST)  WXSS 文件编译错误
VM1479:2 ./static/css/app.wxss
 unexpected token "~"
  1142 | 
  1143 | .weui-switch:checked,
> 1144 | .weui-switch-cp__input:checked ~ .weui-switch-cp__box {
       |                               ^
  1145 |   border-color: #04BE02;
  1146 |   background-color: #04BE02;
  1147 | }

![default](https://user-images.githubusercontent.com/27286851/37807305-a3b4f326-2e7f-11e8-8fb6-38279a1764ca.jpg)

**Comment by anchengjian** [comment]
由于小程序本身的限制，暂无法支持 elementUI / vux 这种有大量 DOM / BOM 操作的 UI 框架和库。
同理，axios 等也无法使用，如果他们不专门做小程序的适配的话。
