### ISSUE TITLE
对于目前使用mpvue已经打包好的微信小程序，要迁移到qq小程序上，需要修改哪些部分？

### ISSUE THREAD

**Issue by zz-11** [Meituan-Dianping/mpvue#1686]
## [扼要问题描述]

**mpvue 版本号：**

[mpvue@x.x.x]

**最小化复现代码：**

[建议提供最小化可运行的代码：附件或文本代码]

```
// 示例代码：
```

**问题复现步骤：**

1. [第一步]
2. [第二步]
3. [其它...]

**观察到的表现：**

[在这里描述观察到的表现]

**截图或动态图：**

![复现步骤截图或gif图片](图片的 url)

**Comment by Dewyzee** [comment]
可以对比下微信小程序与微信小程序的架构以及API上的差异（原则上来说差异不会太大），我理解可以先改API调用前缀试试
