### ISSUE TITLE
付费请人把现有微信小程序转web

### ISSUE THREAD

**Issue by yangdeyin2000** [Meituan-Dianping/mpvue#1688]
我有个在运行的微信小程序，商城类的。
小程序用微信原生代码写的。
后台部署在自己的服务器上。用的java，有源码，无接口文档。
想生成一套web版的东西，界面，操作流程和微信小程序一模一样（不需要微信付款）。
有感兴趣的请联系微信yangdeyin2000
抱歉了。不知道怎么找人，听说mpvue能把小程序转web
特来找懂的人。

帮忙，请勿删除本帖

**Comment by Dewyzee** [comment]
mpvue目前只支持同一套源码构建微信、百度、支付宝以及头条小程序，暂不支持将原生开发的小程序转Web
