### ISSUE TITLE
支付宝和微信不同api的兼容

### ISSUE THREAD

**Issue by blackcloud2333** [Meituan-Dianping/mpvue#1690]
## [扼要问题描述]

**mpvue 版本号：**

[mpvue@x.x.x]

**最小化复现代码：**

[建议提供最小化可运行的代码：附件或文本代码]

```
// 示例代码：
支付宝
```
mpvue.makePhoneCall({
        number: '400-6762-960' // 仅为示例，并非真实的电话号码
      })
```
微信
```
mpvue.makePhoneCall({
       phoneNumber: '400-6762-960' // 仅为示例，并非真实的电话号码
      })
```
**问题复现步骤：**

1. [第一步]
2. [第二步]
3. [其它...]

**观察到的表现：**

[在这里描述观察到的表现]

**截图或动态图：**

![复现步骤截图或gif图片](图片的 url)


```
虽然可以根据platform去做判断，但是代码里面通篇判断感觉很蠢，想寻求更好的解决办法
除此之外，还有授权的处理等等，这些东西感觉都不太统一，而且没有明确的文档来说明，mpvue是如何统一的。

=====================================
终于找到了文档
https://github.com/Meituan-Dianping/mpvue/releases
mpvue 在统一api调用方式上只做简单的前缀统一，并不抹平api差异，此部分交由开发同学自行决定

强烈建议官方把每次大版本更新比较特殊的这种写入文档当中

**Comment by liufeics** [comment]
那就把所有的差异化API封装一次咯，那不就可以直接用了

**Comment by blackcloud2333** [comment]
> 那就把所有的差异化API封装一次咯，那不就可以直接用了

这不是一个正常使用框架解决问题的思路，虽然能解决，但是既然都再封装一次，不如我自己再造一个轮子

**Comment by Dewyzee** [comment]
@blackcloud2333 感谢提的建议。抱歉mpvue目前不支持对API的差异进行抹平处理，对于这块的能力可能需要开发者自行进行解决。关于issue中提到的文档补充问题我们会在后续发布过程中改进
