### ISSUE TITLE
mpvue 百度小程序 带参数跳转后退时的问题 【微信也一样有问题】

### ISSUE THREAD

**Issue by db46rt00ors** [Meituan-Dianping/mpvue#1692]
## [mpvue 百度小程序 带参数跳转后退时的问题 【微信也一样有问题]

**mpvue 版本号：2.0.2

[mpvue@2.0.2]

**最小化复现代码：**

[建议提供最小化可运行的代码：附件或文本代码]

```
// 示例代码：见附件
```
[路由跳转mpvue.zip](https://github.com/Meituan-Dianping/mpvue/files/3476021/mpvue.zip)

**问题复现步骤：**

![image](https://user-images.githubusercontent.com/22002911/62607582-e733a100-b930-11e9-835e-e38ae7fa6372.png)
![image](https://user-images.githubusercontent.com/22002911/62607629-fadf0780-b930-11e9-9597-8de69f79a178.png)
![image](https://user-images.githubusercontent.com/22002911/62607647-03374280-b931-11e9-96e1-d2f4bd011045.png)
![image](https://user-images.githubusercontent.com/22002911/62607735-23ff9800-b931-11e9-9e97-66c808e20112.png)
![image](https://user-images.githubusercontent.com/22002911/62607786-3679d180-b931-11e9-8573-5b4c6228d114.png)

3. [其它...]

**观察到的表现：**

[在这里描述观察到的表现]

**截图或动态图：**

![复现步骤截图或gif图片](图片的 url)

**Comment by Dewyzee** [comment]
这是早期mpvue的生命周期设计上的问题，3.0的版本会进行调整修复。短期内如果有需要跳转同一页面的需求的话，比较原始的方法就是同一页面拷贝一份，配置不同的路由

**Comment by db46rt00ors** [comment]
大概什么时候上3.0
