### ISSUE TITLE
dist导入到小程序之后，小程序提示 请选择空目录

### ISSUE THREAD

**Issue by doudoul** [Meituan-Dianping/mpvue#17]

**Comment by doudoul** [comment]
按照步骤，执行了 npm run dev之后，新建一个小程序项目，目录选择dist 点击创建之后，小程序提示 请选择空目录

**Comment by aOrz** [comment]
你是选择了小程序生成 demo 项目了吧

**Comment by doudoul** [comment]
对呀，不然怎么选择呢？

**Comment by anchengjian** [comment]
http://mpvue.com/mpvue/quickstart/#3-mpvue

选择 小程序项目 并依次填好需要的信息：

- 项目目录：就是那个 dist 目录。
- AppID：没有的话可以点选体验“小程序”，只影响是否可以真机调试。
- 项目名称。

或者请具体截图看一下，也方便排查。

**Comment by falost** [comment]
在执行完 dev 或者 build 之后 ，需要确保 dist 目录中包含 app.jspn 或者 project.config.json 的文件
你不妨先看看这个目录中是否有个文件

**Comment by guoqing2015** [comment]
选择导入项目，不要选择新建项目
