### ISSUE TITLE
编译后的页面和wepy不兼容

### ISSUE THREAD

**Issue by aoxls** [Meituan-Dianping/mpvue#170]
将编译后的页面拷贝到已有的wepy项目中，在app.json里加入页面路径后编译报错，有解吗 ……
![image](https://user-images.githubusercontent.com/4845651/37809768-ba7c0188-2e8b-11e8-804b-2d919c800f17.png)

**Comment by anchengjian** [comment]
按道理，page 级的页面和其他小程序页面是互不干扰的，请发个 demo 来复现，这具体像是操作了某个 wx 的 API 报错。

**Comment by aoxls** [comment]
[test-wepy.zip](https://github.com/Meituan-Dianping/mpvue/files/1840378/test-wepy.zip)

这是一个用wepy脚手架生成的项目，其中/dist/mpvue目录下的文件是mpvue quickstart项目删掉逻辑代码后编译而成的，然后直接修改dist目录下app.json文件，加入页面路径，编译就报错了……

之前尝试过把编译后的页面集成到一个已有的原生小程序里，可以正常运行

**Comment by aOrz** [comment]
能提供下使用 mpvue 写的代码的源码吗

**Comment by aoxls** [comment]
[test-mpvue.zip](https://github.com/Meituan-Dianping/mpvue/files/1840664/test-mpvue.zip)
@aOrz 已上传，这个就是直接用quickstart模板生成的，然后删掉了里面的逻辑代码

**Comment by aOrz** [comment]
已经查明原因,因为你的项目中使用 promise-polyfill 重置了 Promise，导致的问题，预计今天发版本解决，你也可以去掉 Promise 的 polyfill（已经兼容的很好了，没有必要）

**Comment by aoxls** [comment]
确认是这个问题，非常感谢！不过这是老项目了，而且是wepy在构建时自动打包进去的，不怎么好改，期待新版本！

**Comment by aOrz** [comment]
已修复，见：https://github.com/Meituan-Dianping/mpvue/releases/tag/1.0.7
