### ISSUE TITLE
传递Number类型的参数时，在接受时变成了String类型

### ISSUE THREAD

**Issue by xuech** [Meituan-Dianping/mpvue#1710]
## [扼要问题描述]
在A页面通过`mpvue.navigateTo({'../ViewA/main?params=' + 100 })`
在B页面的onShow方法中通过`this.$root.$mp.query.params`得到的参数类型变成了`String`类型的‘3’
**mpvue 版本号：**
2.0.0
**最小化复现代码：**

```
A:
mpvue.navigateTo({'../ViewA/main?params=' + 100 })
```
B:
this.$root.$mp.query.params

**问题复现步骤：**
同上

**观察到的表现：**
实际在B页面中得到的参数是String类型

[在这里描述观察到的表现]

**截图或动态图：**

![复现步骤截图或gif图片](图片的 url)

**Comment by coolRoger** [comment]
这个是小程序的机制, 与mpvue无关, 必要时可以在获取query后进行类型转换
