### ISSUE TITLE
mpvue编译后的clearTimeout清除不了定时器，报错

### ISSUE THREAD

**Issue by snowsouls** [Meituan-Dianping/mpvue#1712]
## [扼要问题描述]

**mpvue 版本号：**

[mpvue@x.x.x]

**最小化复现代码：**
clickCancel() {
            let timer = setTimeout(function() {}, 2000);
            clearTimeout(timer);
}
[建议提供最小化可运行的代码：附件或文本代码]

```
// 示例代码：
```

**问题复现步骤：**

1. [第一步]
2. [第二步]
3. [其它...]

**观察到的表现：**
随意一个点击事件，增加timeout延时事件，并clearTimeout清除，报错
[在这里描述观察到的表现]

**截图或动态图：**

![Uploading image.png…]()

![复现步骤截图或gif图片](图片的 url)

**Comment by Dewyzee** [comment]
麻烦贴写相关错误截图呢

**Comment by snowsouls** [comment]
抱歉，我的问题
