### ISSUE TITLE
mpvue有没有同步开发小程序与h5的教程？

### ISSUE THREAD

**Issue by bruce-zhang932** [Meituan-Dianping/mpvue#1719]
官网上说"其中只需要更改小部分平台差异代码和更新下 webpack 的建构配置就可以直接运行。"，
具体如何修改？
官网的意思是开发完小程序后，复制出来一份改吧改吧吗？
如果我想同步开发，有没有同步开发的demo或者具体的配置？

**Comment by s11831252** [comment]
把vue webpack配置部份和 vue-loader的拷贝进来用使用
