### ISSUE TITLE
旧项目实现的是axios请求库，想迁移过来，测试发现一引入axios，就报错

### ISSUE THREAD

**Issue by killdada** [Meituan-Dianping/mpvue#172]
原先项目想要迁移过来，以前请求库使用的是axios，axios自己有适配器，打算自己配置下，但是发现直接
import axios from 'axios' 项目就报错了，如图
![qq 20180323122300](https://user-images.githubusercontent.com/16487810/37811355-a61555ba-2e94-11e8-8cf2-150e5e99f6a0.png)

**Comment by aOrz** [comment]
请求库可以参考 #109

**Comment by weizs** [comment]
axios + adapter 完美解决
