### ISSUE TITLE
遇见  normalizeComponent is not a function 的保存

### ISSUE THREAD

**Issue by qbboo** [Meituan-Dianping/mpvue#1720]
## [扼要问题描述]

**mpvue 版本号：**

[mpvue@x.x.x]

**最小化复现代码：**

[建议提供最小化可运行的代码：附件或文本代码]

```
// 示例代码：
```

**问题复现步骤：**
之前是好好地，更新一下开发者工具就报错了
微信版本号 1.02.1907300
1. [第一步] 
2. [第二步]
3. [其它……]

**观察到的表现：**

[在这里描述观察到的表现]

**截图或动态图：**
![image](https://user-images.githubusercontent.com/26472847/64423257-a5854a00-d0d8-11e9-8262-6220f02cd8cf.png)
![image](https://user-images.githubusercontent.com/26472847/64423284-ba61dd80-d0d8-11e9-9c7c-b8c00a3cff87.png)

![复现步骤截图或 gif 图片](图片的 url)

**Comment by choumai555** [comment]
解决问题了吗

**Comment by JesseZhao1990** [comment]
> 解决问题了吗

我的也报了，重启开发者工具就解决了

**Comment by JesseZhao1990** [comment]
> ## [扼要问题描述]
> **mpvue 版本号：**
> 
> [[mpvue@x.x.x](mailto:mpvue@x.x.x)]
> 
> **最小化复现代码：**
> 
> [建议提供最小化可运行的代码：附件或文本代码]
> 
> ```
> // 示例代码：
> ```
> 
> **问题复现步骤：**
> 之前是好好地，更新一下开发者工具就报错了
> 微信版本号 1.02.1907300
> 
> 1. [第一步]
> 2. [第二步]
> 3. [其它……]
> 
> **观察到的表现：**
> 
> [在这里描述观察到的表现]
> 
> **截图或动态图：**
> ![image](https://user-images.githubusercontent.com/26472847/64423257-a5854a00-d0d8-11e9-8262-6220f02cd8cf.png)
> ![image](https://user-images.githubusercontent.com/26472847/64423284-ba61dd80-d0d8-11e9-9c7c-b8c00a3cff87.png)
> 
> ![复现步骤截图或 gif 图片](图片的 url)

我的重启了一下开发者工具之后，不报了

**Comment by liang-kai** [comment]
也遇到，重启也不能解决

**Comment by PentaTea** [comment]
第一次重启开发者工具解决
第二次删除dist文件夹之后解决
