### ISSUE TITLE
mpvue-loader 解析组件时报错

### ISSUE THREAD

**Issue by jimyong88** [Meituan-Dianping/mpvue#1729]
## [扼要问题描述]

**mpvue 版本号：**

[mpvue@2.0.6]

**最小化复现代码：**

[建议提供最小化可运行的代码：附件或文本代码]

```
// 示例代码：
```

**问题复现步骤：** 

**观察到的表现：**

执行到resolveSrc报错：
context 值：/src/store
打印出来显示 originComponents是undefined类型Object.keys(originComponents)直接crash了

 ERROR  Failed to compile with 1 errors                                                                                                                               上午10:34:07

Module build failed: TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at resolveSrc (****/node_modules/mpvue-loader/lib/mp-compiler/index.js:206:39)
    at Object.compileMP (****/node_modules/mpvue-loader/lib/mp-compiler/index.js:168:5)
    at Object.module.exports (****/node_modules/mpvue-loader/lib/loader.js:60:22)

**截图或动态图：**

![复现步骤截图或gif图片](图片的 url)

**Comment by jimyong88** [comment]
我自己的问题，抱歉

**Comment by raojq-kylin** [comment]
我也报这个错，不过我这个是帮人家做二次迭代，现在报这个错跑不起来。请问你是怎么解决？

**Comment by icheer** [comment]
> 我也报这个错，不过我这个是帮人家做二次迭代，现在报这个错跑不起来。请问你是怎么解决？

避免使用app.js作为文件名就可以了, app.js似乎不能用来作为vuex下面的module文件名
