### ISSUE TITLE
mpvue 引入百度地图bmap-wx.js 报错？

### ISSUE THREAD

**Issue by Mixlong** [Meituan-Dianping/mpvue#174]
# [问题简单描述]

**问题复现步骤:**

1. [第一步]
2. [第二步]
3. [其他步骤...]

**期望的表现:**

[在这里描述期望的表现]

**观察到的表现:**
![tim 20180323164753](https://user-images.githubusercontent.com/27038897/37819907-047271f4-2eba-11e8-8620-c0662aa4f698.png)
![tim 20180323164822](https://user-images.githubusercontent.com/27038897/37819911-05e2c070-2eba-11e8-98fe-882107d2e3c5.png)

[在这里描述观察到的表现]

**屏幕截图和动态 GIF 图**

![复现步骤的屏幕截图和动态 GIF 图](图片的 url)

**Comment by aOrz** [comment]
是专门为小程序开发的地图 sdk 吗？如果不是的话，是不能直接把百度的地图 sdk 拿过去直接用的

**Comment by Mixlong** [comment]
是用的微信小程序专用的sdk ,  我之前在utils目录下，刚才把bmap-wx.js移动static 目录下，不走webpack 就没报错了。

**Comment by ghostsatan** [comment]
请教一下 如何在mpvue下引入百度地图 困扰了两天 用<script>方式引入的话 一直找不到bmap的对象 写成了异步也不行  请问有教程什么的么
