### ISSUE TITLE
build打包的时calc计算100%被转换成了1

### ISSUE THREAD

**Issue by ccr1002** [Meituan-Dianping/mpvue#1748]
## [扼要问题描述]
height: calc(100% - constant(safe-area-inset-bottom));
被转换成了height: calc(1 - constant(safe-area-inset-bottom));
**mpvue 版本号：1.0.11

[mpvue@x.x.x]

**最小化复现代码：**

[建议提供最小化可运行的代码：附件或文本代码]

```
// 示例代码：
```

**问题复现步骤：**

1. [第一步]
2. [第二步]
3. [其它...]

**观察到的表现：**

[在这里描述观察到的表现]

**截图或动态图：**

![复现步骤截图或gif图片](图片的 url)

**Comment by chuquancai** [comment]
用100vh试试？
