### ISSUE TITLE
分包后打包速度特别慢 

### ISSUE THREAD

**Issue by AprilTong** [Meituan-Dianping/mpvue#1751]
## [扼要问题描述]

**mpvue 版本号：**

[mpvue@x.x.x]

**最小化复现代码：**

[建议提供最小化可运行的代码：附件或文本代码]

```
// 示例代码：
```

**问题复现步骤：**

1. [第一步]
2. [第二步]
3. [其它...]

**观察到的表现：**

[在这里描述观察到的表现]

**截图或动态图：**

![复现步骤截图或gif图片](图片的 url)

**Comment by AprilTong** [comment]
"mpvue"的版本 "1.0.11",
![image](https://user-images.githubusercontent.com/24354441/67362872-b44b9180-f59e-11e9-8123-d1a308f8f40e.png)

**Comment by shrekuu** [comment]
@Tzrong   好像你这边的 mpvue 版本比较低，大家估计木有时间在低版本再分析测试分包性能问题了，大哥要不要升级一下？

**Comment by AprilTong** [comment]
已经尝试升级，编译速度确实快了比较多，谢谢。
![image](https://user-images.githubusercontent.com/24354441/68744157-ea74b200-062e-11ea-966d-f13e886880c6.png)
