### ISSUE TITLE
[代码格式化]如何在mpvue当中使用其他代码格式化工具比如standard?

### ISSUE THREAD

**Issue by blackcloud2333** [Meituan-Dianping/mpvue#1754]
## 项目当中引入standard无法接入项目

**mpvue 版本号：2.0.0

[mpvue@2.0.0]

**最小化复现代码：**

[建议提供最小化可运行的代码：附件或文本代码]
package.json
```
 "lint": "standard --plugin html **/*.{js,vue}",
  "fix": "standard --fix --plugin html **/*.{js,vue}",
```
## 报错信息
Error: Failed to load plugin 'html' declared in 'CLIOptions': eslint-plugin-html error: It seems that eslint is not loaded.
## 个人尝试
查了下发现说是eslint的版本问题，做了一下尝试
1. 更新eslint版本
2. 安装eslint-plugin-vue
3. 删除node_modules重新安装
4. 更新.editconfigrc为以下代码

```
// http://eslint.org/docs/user-guide/configuring

module.exports = {
  root: true,
  parser: 'babel-eslint',
  parserOptions: {
    sourceType: 'module',
    parser: 'babel-eslint',
    ecmaVersion: 2017
  },
  env: {
    browser: false,
    node: true,
    es6: true
  },
  // https://github.com/standard/standard/blob/master/docs/RULES-en.md
  extends: [
    'plugin:vue/essential',
    'standard'
  ],
  // required to lint *.vue files
  plugins: [
    'html',
    'vue'
  ],
  // add your custom rules here
  rules: {
    // allow paren-less arrow functions
    'arrow-parens': 0,
    // allow async-await
    'generator-star-spacing': 0,
    // allow debugger during development
    'no-debugger': process.env.NODE_ENV === 'production' ? 2 : 0
  },
  globals: {
    App: true,
    Page: true,
    wx: true,
    swan: true,
    tt: true,
    my: true,
    getApp: true,
    getPage: true,
    requirePlugin: true,
    mpvue: true,
    mpvuePlatform: true,
    getCurrentPages: true
  }
}

```
以上方法都无法解决问题，请问应该如何解决
**问题复现步骤：**

1.  安装standard，standard-loader
2.  更改package.json
3.  执行npm run lint 
**截图或动态图：**

![Xnip2019-10-23_11-39-38](https://user-images.githubusercontent.com/25345753/67355421-d25ac700-f589-11e9-9536-3e9b6b028b2e.jpg)

**Comment by qfgyd2004** [comment]
这种问题都跑来提issues?mpvue和你格式化有啥关系？

**Comment by blackcloud2333** [comment]
> 这种问题都跑来提issues?mpvue和你格式化有啥关系？

不懂你说的啥意思？
1. 换用格式化工具，mpvue项目跑步起来，问问题不是很正常吗？
2. 尝试过不同的方法解决不了的问题，不问难道正常吗？
3. 如果你知道有什么解决办法，欢迎拿着答案来评论
