### ISSUE TITLE
请问：小程序新的api 功能EventChannel 怎么实现呢？

### ISSUE THREAD

**Issue by gslancer** [Meituan-Dianping/mpvue#1756]
小程序navigateTo中新增的eventChannel，参考官网api如下：

wx.navigateTo({
  url: 'test?id=1',
  events: {
    // 为指定事件添加一个监听器，获取被打开页面传送到当前页面的数据
    acceptDataFromOpenedPage: function(data) {
      console.log(data)
    },
    someEvent: function(data) {
      console.log(data)
    }
    ...
  },
  success: function(res) {
    // 通过eventChannel向被打开页面传送数据
    res.eventChannel.emit('acceptDataFromOpenerPage', { data: 'test' })
  }
})

//test.js
Page({
  onLoad: function(option){
    console.log(option.query)
    const eventChannel = **this.getOpenerEventChannel()**
    eventChannel.emit('acceptDataFromOpenedPage', {data: 'test'});
    eventChannel.emit('someEvent', {data: 'test'});
    // 监听acceptDataFromOpenerPage事件，获取上一页面通过eventChannel传送到当前页面的数据
    eventChannel.on('acceptDataFromOpenerPage', function(data) {
      console.log(data)
    })
  }
})

主要是 this.getOpenerEventChannel() 怎么实现？

**Comment by zhaixiyun** [comment]
小程序文档有传参页面A和接参页面B，A页面方法与原生一样，主要是B页面接参方式多了点东西，B页面接参用this.$mp.page.getOpenerEventChannel().on('方法名', function (data) {console.log('A页面传参：',data)})，其他方法也类似，如果提示找不到对应方法就再原生示例部分添加this.$mp.page，小程序原生方法一般都给封装这里面了

**Comment by gslancer** [comment]
> 小程序文档有传参页面A和接参页面B，A页面方法与原生一样，主要是B页面接参方式多了点东西，B页面接参用this.$mp.page.getOpenerEventChannel().on('方法名', function (data) {console.log('A页面传参：',data)})，其他方法也类似，如果提示找不到对应方法就再原生示例部分添加this.$mp.page，小程序原生方法一般都给封装这里面了

谢谢！
