### ISSUE TITLE
checkbox :checked 中写表达式返回 Boolean 无法生效

### ISSUE THREAD

**Issue by blade254353074** [Meituan-Dianping/mpvue#176]
在小程序原生的 checkbox 上，如果这样写：

```vue
<checkbox :checked="item.checked" />
```

是没有问题的，但如果写表达式：

![image](https://user-images.githubusercontent.com/9346008/37840231-7490e942-2ef7-11e8-8f61-4988e7b239b3.png)

checked 表现就会不正常：表现为原生组件保持 checked 的状态，点击会闪一下（重新 render），但还是
 checked 状态，或者保持 not checked 状态，同样也是闪一下，保持的状态取决于 checked 里面的表达式。

![image](https://user-images.githubusercontent.com/9346008/37840818-0cfc689a-2ef9-11e8-9844-8af2511c004b.png)
<sub>上图表现为保持 not checked 状态</sub>

**Comment by anchengjian** [comment]
抱歉这部分给你带来了一些困扰，由于 wxml 的限制，目前暂不支持这种写法：http://mpvue.com/mpvue/#javascript

**Comment by blade254353074** [comment]
你们的文档我也在看，但没发现它准确地指出 bind 表达式的限制，只是说双括号有问题。像这种循环的 template 不能用表达式 只能通过再循环去处理数据了
