### ISSUE TITLE
dist没有自动清理？

### ISSUE THREAD

**Issue by dagang007** [Meituan-Dianping/mpvue#1760]
上一次有3个页面，我更改src下只有一个页面，npm start后，dist另2个页面还存在

"_id": "mpvue@2.0.6"

**Comment by shrekuu** [comment]
是的, 不自动清理, 你可以这样做: 

给 package.json 里的 script 加一行:

![image](https://user-images.githubusercontent.com/3136026/68360190-03c2bd80-015a-11ea-8f42-80d80f766fb6.png)


然后以后就可以这样清理 dist/wx 目录: 

```
npm run clean
```

**Comment by CaicoLeung** [comment]
build才会clean dist目录
