### ISSUE TITLE
关于mock.js问题

### ISSUE THREAD

**Issue by zhoufanglu** [Meituan-Dianping/mpvue#1768]
mpvue内不能使用mock.js吗？

**Comment by zhoufanglu** [comment]
有大佬能回答下吗？谢谢了

**Comment by yunikoro** [comment]
你好，@zhoufanglu。很久没有弄mpVue了，不知道我的项目是不是最新的mpVue脚手架，希望能帮到你。
mpVue的打包本质上是个node express服务，所以只要将mock相关的api作为一个middleware加入express中就可以了。

**三步：**
**1. 引入webpack-api-mocker-pro并被配置好。**
（我一直是用这个mocker，基本上api的延迟返回，HTTP status Code都能模拟，写起来也简单。）
**2. 将mock对象加入express对象。**
**3. 注释掉配置文件中对connect-history-api-fallback这个middleware的引用。**
（不知道connect-history-api-fallback这个插件在mpVue的脚手架中是干什么的，注释掉也不影响打包和本地调试。）

这是修改过后的mpVue脚手架的dev-server.js配置gist：
[https://gist.github.com/e85f417700d8954a9f1f5472250fc46a.git](url)

**Comment by ANT-CYJ** [comment]
放心吧，我已经收到啦。
