### ISSUE TITLE
v-model 2.0  突然失效

### ISSUE THREAD

**Issue by huyajie** [Meituan-Dianping/mpvue#1769]
## [v-model 不生效绑定不到对应的变量]

**mpvue 版本号：**

[mpvue@2.0.0]

**最小化复现代码：**

[建议提供最小化可运行的代码：附件或文本代码]

```
// 示例代码：
```
<input type="text" class="form-control" v-model="motto" placeholder="v-model" />
**问题复现步骤：**
vue  init  之后默认就不行
1. [第一步]
2. [第二步]
3. [其它...]

**观察到的表现：**

[在这里描述观察到的表现]

**截图或动态图：**

![复现步骤截图或gif图片](图片的 url)
![image](https://user-images.githubusercontent.com/7566894/69036607-38b7f580-0a21-11ea-9f4e-3cc252abc844.png)

**Comment by huyajie** [comment]
可能是模拟器的问题 在手机上是可以使用的

**Comment by jetBn** [comment]
真机有用吗？

**Comment by huyajie** [comment]
> 真机有用吗？
真机可以用

**Comment by ghost** [comment]
如果是在微信开发者工具中遇到这个问题，可以按如下步骤解决：
右上角“详情”按钮 -> 本地设置 -> 调试基础库，目前最新版本是2.9.3，把版本调低一些，这个问题就可以解决。
