### ISSUE TITLE
关于v-show采坑

### ISSUE THREAD

**Issue by anotherleon** [Meituan-Dianping/mpvue#178]
# [问题简单描述]
v-show指令转换小程序后不生效。而把v-show替换为vi-if则表现正常。
![v-show](https://user-images.githubusercontent.com/19590709/37882334-09019930-30d5-11e8-8b6f-1b4ac096de35.png)

**问题复现步骤:**
![v-show](https://user-images.githubusercontent.com/19590709/37882313-d8b15dce-30d4-11e8-9f19-731f8eaec7b2.gif)

**期望的表现:**
* 使用v-if表现正常：
![v-if](https://user-images.githubusercontent.com/19590709/37882338-0f6bb5d0-30d5-11e8-8ee3-05fdef1e4597.png)

![v-if](https://user-images.githubusercontent.com/19590709/37882307-d4b55202-30d4-11e8-93d7-dcf99a8de9a3.gif)

**Comment by anchengjian** [comment]
抱歉，没复现成功，给个可以复现的 demo 吧

``` html
<template>
  <div>
    <p v-show="vShow">vShowvShowvShowvShowvShowvShowvShow</p>
  </div>
</template>

<script>
export default {
  data () {
    return {
      vShow: false
    }
  },
  methods: {
    formSubmit (e) {
      console.log('Submit', e)
    }
  },
  created () {
    setTimeout(() => {
      this.vShow = true
    }, 2000)

    setTimeout(() => {
      this.vShow = false
    }, 5000)
  }
}

</script>
```

**Comment by bigmeow** [comment]
用自带的  hidden 属性吧，这个靠谱点

**Comment by mdsb100** [comment]
v-if似乎也有问题 用hidden吧

**Comment by mdsb100** [comment]
v-if仍然创建了对象

**Comment by ldwonday** [comment]
这个确实是一个bug！

**Comment by zhjlydia** [comment]
我测试的情况是这样的，在样式中设置了display属性之后，v-show就失效了

**Comment by liyunsheng** [comment]
> 我测试的情况是这样的，在样式中设置了display属性之后，v-show就失效了

发现设置了`:style=""`也会使v-show失效
