### ISSUE TITLE
子组件不能执行onShow里面的内容

### ISSUE THREAD

**Issue by noahlam** [Meituan-Dianping/mpvue#179]
# [问题简单描述]

**问题复现步骤:**

1. 在子组件不会执行onShow里面的内容
2.
    onLoad () {
      console.log('onLoad')
    },
    onShow () {
      console.log('onShow')
    },
    mounted () {
      console.log('mounted')
    },
3. 
**期望的表现:**

应该要打印
onLoad
onShow
mounted

**观察到的表现:**

打印结果 
onLoad
mounted

**Comment by noahlam** [comment]
进一步排查了一下,发现子组件的onShow生命周期,只有在页面第二次显示的时候,才会执行,而父组件的onShow,每次页面显示都会执行,包括第一次

**Comment by rchunping** [comment]
作为Page的才有这些生命周期函数吧

**Comment by aOrz** [comment]
因为在 onShow 的时候，子组件还没有创建，所以子组件第一次不会有 onShow 触发
