### ISSUE TITLE
小程序基础库2.9.0开始支持的新动画创建方式this.animate接口

### ISSUE THREAD

**Issue by southpush** [Meituan-Dianping/mpvue#1790]
## 怎么使用小程序新的接口this.animate

小程序基础库2.9.0开始支持新的动画接口， 官方文档演示这样的

```
    this.animate(selector, keyframes, duration, callback)
```
但是这个this跟mpvue里使用的this指向不一样，mpvue里的this也没有this.animate，请问要怎样在mpvue中使用这个this.animate接口呢？

**mpvue 版本号：**

2.0.6

**Comment by southpush** [comment]
打印了this出来发现了，this.$mp.page.animate()，接口在这里

**Comment by 1193950650** [comment]
很有帮助
