### ISSUE TITLE
同一个子组件,在2个不同的地方引用,会导致2个地方的样式都加载不了,而如果只在一个地方引用却没问题

### ISSUE THREAD

**Issue by noahlam** [Meituan-Dianping/mpvue#180]
我现在有2个页面,页面1叫 materialPreview 里面有个commentPublish子组件,这个页面是比较早开发.经过初步调试,该组件可以正常使用,没有任何样式问题.

现在我又新加了一个页面,叫comment, 这个页面里面,也需要用到这个 commentPublish 组件,然后我就在这comment这个页面,引入commentPublish组件(只要引入,都还没注册,也没使用),就会导致该组件的样式,在所有引用的页面,都没有掉了,用微信开发者工具查看一个页面的里title样式类,在没有引用的时候,Styles窗口里面显示的是这样
.title.data-v-5c566b7c {
 /* 这里省略了不必要展示的内容 */
}
而我如果在 comment 写上这一句 
 import commentPublish from '@/pages/materialPreview/components/commentPublish' 
,Styles窗口里面根本就没有关于title的样式(确切的说,是所有该子组件里面定义的样式,都没了.)
尝试给组件起个不同的名字,也一样没用.
 import commentPublishRef from '@/pages/materialPreview/components/commentPublish'

**Comment by anchengjian** [comment]
参考下 #177 ?

**Comment by noahlam** [comment]
好的,那我重新创建一个项目看看...

**Comment by noahlam** [comment]
找到问题了,是缺少了 webpack-mpvue-asset-plugin 这个插件导致的,新版的cli里面会自动添加这个插件,所以#177 说用新的重新建一个项目就可以了.

如果你不想重新建,也可以这么做
1,在package.json 的 devDependencies 里加上一行  "webpack-mpvue-asset-plugin": "^0.0.1",
2,在命令行执行npm i  安装一下新加的依赖
` (或者你也可以直接执行 npm i webpack-mpvue-asset-plugin --dev-save)`
3.在/build/webpack.base.conf.js 里面导入我们新添加的模块 
`var MpvuePlugin = require('webpack-mpvue-asset-plugin')`
4,还是在刚刚这个配置文件里面的跟 target,entry,module等属性同级的地方,加一个
```
plugins: [
    new MpvuePlugin()
]
```
5,重启项目,问题解决

如还未解决,检查一下package里面的这3个依赖的版本不低于以下.
```
"mpvue": "^1.0.6",
"mpvue-template-compiler": "^1.0.6",
"mpvue-loader": "^1.0.8",
```

**Comment by lianmt** [comment]
get，已收藏
