### ISSUE TITLE
不支持filters？

### ISSUE THREAD

**Issue by meltifa** [Meituan-Dianping/mpvue#183]
filters: {
      capitalize (value) {
        if (!value) return ''
        value = value.toString() + '哈哈哈哈'
        return value
      }
    }

最后渲染到页面上变成0了

**Comment by rchunping** [comment]
不支持， 

但是我真的觉得应该拿小程序的wxs部分来实现mpvue的filter功能

**Comment by aOrz** [comment]
暂不支持 filters

**Comment by Airkro** [comment]
期待实现，毕竟列表数据需要用
