### ISSUE TITLE
请问vue里面的组件比如mint-ui等插件能兼容进来吗

### ISSUE THREAD

**Issue by chenxuan0000** [Meituan-Dianping/mpvue#184]
# [问题简单描述]

**问题复现步骤:**

1. [第一步]
2. [第二步]
3. [其他步骤...]

**期望的表现:**

[在这里描述期望的表现]

**观察到的表现:**

[在这里描述观察到的表现]

**屏幕截图和动态 GIF 图**

![复现步骤的屏幕截图和动态 GIF 图](图片的 url)

**Comment by aOrz** [comment]
因为有些 vue 的特性 mpvue 不支持，可能需要做一些修改才能使用，https://github.com/mpvue/awesome-mpvue 这里有些已做了兼容的 UI 库，可以看下

**Comment by chenxuan0000** [comment]
谢谢
