### ISSUE TITLE
img标签src为空时，被编译为true

### ISSUE THREAD

**Issue by JJJJYYYY** [Meituan-Dianping/mpvue#185]
情况描述：
在组件中使用img标签中（直接写page上同样），src为空，得到控制台报错404，查看wxml，看到img.src为true，实际应该是空字符串
![组件代码](https://user-images.githubusercontent.com/32628989/37907388-88351cec-3137-11e8-85d9-bf048c0d8ee7.png)
![控制台](https://user-images.githubusercontent.com/32628989/37907637-436a096e-3138-11e8-8ab8-fc7b466e2d1a.png)
![wxml](https://user-images.githubusercontent.com/32628989/37907649-4b2493fe-3138-11e8-83ab-d939294ab740.png)

开发环境：
mpvue：v1.0.7
mpvue-loader：v1.0.9
mpvue-template-compiler: v1.0.7

**Comment by anchengjian** [comment]
最终编译成了 `<image src class="_img"></image>` 然后 wxml 解析成了 `src="true"`，是正常的，也请不要直接写一个空 img ，无实际意义啊。
