### ISSUE TITLE
能否集成自动生成雪碧图功能？

### ISSUE THREAD

**Issue by meltifa** [Meituan-Dianping/mpvue#186]
我们手头的h5项目想搬到小程序上，目前只能把以前构建好的雪碧图和css直接放到项目里，维护起来很不方便，如果是新项目也没办法生成雪碧图了，希望以后能添加这个功能

**Comment by lichangwei** [comment]
雪碧图适用于使用大量小图片的场景，其目的是减少HTTP请求，小程序的图片都变成本地的了，不需要使用雪碧图了。

**Comment by anchengjian** [comment]
如果小程序支持雪碧图的话，那 mpvue 也是支持的，你可以添加自定义的 webpack 相关配置实现自动拼接。
