### ISSUE TITLE
小程序map组件，如何移动到当前位置

### ISSUE THREAD

**Issue by sunshineyuyu** [Meituan-Dianping/mpvue#187]
在mpvue中使用小程序map组件，moveToLocation不起效果

        <map id="mymap" show-location></map>

    this.mapCtx = wx.createMapContext('mymap');
    this.mapCtx.moveToLocation();
没有反应，用getCenterLocation也获取不到信息，这是为什么

**Comment by vincent0324** [comment]
`
<template>
    <div class="map-holder">
        <map id="map"show-location>
            <cover-view @click="getCurrentLocation">复位</cover-view>
        </map>
    </div>
</template>

<script>
export default {
    methods: {
        getCurrentLocation () {
            this.mapCtx = wx.createMapContext('map')
            this.mapCtx.moveToLocation()
        }
    }
}
</script>
`

上面的代码测试有效，能提供更多的代码参考一下吗？

**Comment by sunshineyuyu** [comment]
感谢提供方式，我开始是在create中实用wx.createMapContext，之后通过click事件去触发moveToLocation，这时没有反应，用了介绍的方式其实是有，这个可能跟加载的顺序，可能map还没有加载出来
