### ISSUE TITLE
pug input指定默认值

### ISSUE THREAD

**Issue by liurongji** [Meituan-Dianping/mpvue#188]
![image](https://user-images.githubusercontent.com/14249672/37959537-ee6225f6-31e5-11e8-94eb-f2ad657df1e8.png)
![image](https://user-images.githubusercontent.com/14249672/37959553-f6b7314c-31e5-11e8-88e0-616941e3730e.png)

**Comment by anchengjian** [comment]
`v-model` 吧 https://cn.vuejs.org/v2/guide/forms.html
