### ISSUE TITLE
onLoad 函数无法获取到页面传入的参数

### ISSUE THREAD

**Issue by F-loat** [Meituan-Dianping/mpvue#19]
是要通过其他方式进行页面传参吗，示例代码如下
``` html
<a href="/pages/detail/detail?id=666">链接</a>
```
``` js
onLoad (options) {
  console.log(options) // undefined
},
```

**Comment by anchengjian** [comment]
http://mpvue.com/mpvue/#_17 

1. 如何获取小程序在 page onLoad 时候传递的 options

在所有 页面 的组件内可以通过 this.$root.$mp.query 进行获取。

**Comment by F-loat** [comment]
感谢，这个文档之前没看到，
![image](https://user-images.githubusercontent.com/16759376/37202589-db28941c-23c5-11e8-9cc4-0f99623771e1.png)
建议把 Mpvue 直接改成 Docs 吧

**Comment by evecalm** [comment]
mpvue v1.0.1 的 `this.$root.$mp.query` 未对 value 进行 `decodeURIComponent` 处理

**Comment by blade254353074** [comment]
@anchengjian
我觉得 mpvue 不需要再做 `decodeURIComponent`，和微信保持一致即可

**Comment by anchengjian** [comment]
@blade254353074 我支持

**Comment by blade254353074** [comment]
@evecalm 推荐用 qs 库

**Comment by evecalm** [comment]
又测试验证了下, query 的 key 会做 `decodeURIComponent` 处理, 但是 value 没有, 已自行处理了
