### ISSUE TITLE
真机上传图片报错，可以看下图片

### ISSUE THREAD

**Issue by zhouyingkai1** [Meituan-Dianping/mpvue#192]
# [问题简单描述]
真机上传图片报错，可以看下图片

**期望的表现:**
可以正常上传

**观察到的表现:**

![wechatimg3984](https://user-images.githubusercontent.com/19966486/38025044-89bb7a38-32b9-11e8-9f6b-c43456a71706.jpeg)

微信开发者工具上传是可以的。

**Comment by aOrz** [comment]
这个和 mpvue 相关吗？可以提供下 demo
