### ISSUE TITLE
设置 window 或者 page 的背景色不生效

### ISSUE THREAD

**Issue by ymqy** [Meituan-Dianping/mpvue#193]
# 设置 window 或者 page 的背景色不生效

**问题复现步骤:**

1. 设置应用 main.js 或者页面 main.js 的 config 对象中背景色属性为 HexColor

**期望的表现:**

希望背景色能生效

**观察到的表现:**

没有报错，也没有其他表现。

**屏幕截图和动态 GIF 图**

![复现步骤的屏幕截图和动态 GIF 图](https://i.loli.net/2018/03/28/5abb8ca4a6218.png)

**Comment by aOrz** [comment]
backgroundColor 设置的是下拉时候的背景色，非 page 的背景色，见：https://developers.weixin.qq.com/miniprogram/dev/framework/config.html

**Comment by ymqy** [comment]
你好，我设置了下拉的背景色还有页面的背景色都没有生效
`    window: {
      backgroundColor: '#000000',
}`
页面背景色设置代码
`export default {
  config: {
    backgroundColor: '#000000',
  },
};`

**Comment by anchengjian** [comment]
@ymqy 你写个 demo 吧

**Comment by ymqy** [comment]
没开启下拉刷新就看不到背景色，找的原因了，page只能样式控制对吗

**Comment by ymqy** [comment]
@anchengjian 谢谢哈，刚刚在手机不知道怎么@你，刚刚没理解到位
@aOrz 谢谢哈
