### ISSUE TITLE
加了tabBar之后，页面中的《a》标签无法跳转

### ISSUE THREAD

**Issue by lipingfang** [Meituan-Dianping/mpvue#195]
# [问题简单描述]

**问题复现步骤:**

1. [第一步]
2. [第二步]
3. [其他步骤...]

**期望的表现:**

[在这里描述期望的表现]

**观察到的表现:**

[在这里描述观察到的表现]

**屏幕截图和动态 GIF 图**

![复现步骤的屏幕截图和动态 GIF 图](图片的 url)

**Comment by lipingfang** [comment]
![image](https://user-images.githubusercontent.com/23228636/38065894-0fe4c262-3338-11e8-9e82-4899f269a386.png)

**Comment by lipingfang** [comment]
![image](https://user-images.githubusercontent.com/23228636/38065902-1ac3bf08-3338-11e8-9d74-56b05048fc2b.png)

**Comment by aOrz** [comment]
这是微信的限制，你可以使用原生写个 demo 试下

**Comment by xiao345** [comment]
那页面怎么做跳转？ @aOrz @lipingfang
