### ISSUE TITLE
mpvue如何支持动态组件<component></component>

### ISSUE THREAD

**Issue by 3243239283** [Meituan-Dianping/mpvue#196]
# [问题简单描述]
component渲染动态组件报错
**问题复现步骤:**
想用component做一个楼层自动排序渲染的效果，发现mpvue不支持component

**期望的表现:**
希望技术大神能修复一下或者给个降级方案

**Comment by anchengjian** [comment]
http://mpvue.com/mpvue/#_15 暂时还不支持 动态组件

**Comment by sanwv** [comment]
通过动态模板折中实现功能呢?
```
<template name="compa"><compa></compa></template>
<template name="compa"><compa></compa></template>

//走起
<template is=xxx></template>
```

**Comment by webyangpei** [comment]
> 通过动态模板折中实现功能呢?
> 
> ```
> <template name="compa"><compa></compa></template>
> <template name="compa"><compa></compa></template>
> 
> //走起
> <template is=xxx></template>
> ```是否可行？有没有例子啥的瞅瞅

**Comment by shuliuzhenhua** [comment]
也在烦这个问题，各位大佬有替代方案吗。
