### ISSUE TITLE
style三目无效

### ISSUE THREAD

**Issue by POI-ShiFeng** [Meituan-Dianping/mpvue#197]
# [问题简单描述]

场景一  :class="currentIndex==index? 'bigImg': 'smallImg'"
场景二  :style="{height:currentIndex==index? '160px':'140px'}"

两个场景做同样的事，场景一正常。场景二异常

**问题复现步骤:**

1. [第一步]
2. [第二步]
3. [其他步骤...]

**期望的表现:**

[在这里描述期望的表现]

**观察到的表现:**

[在这里描述观察到的表现]

**屏幕截图和动态 GIF 图**

![复现步骤的屏幕截图和动态 GIF 图](图片的 url)

**Comment by anchengjian** [comment]
你的版本是多少？

升级到最新的版本再试试

**Comment by POI-ShiFeng** [comment]
v1.0.7

**Comment by weiyunpeng** [comment]
"mpvue": "^1.0.12",
:style="'background:'+index === textArr.length ? activeBorColor : baseBorColor"
结果：style=" #cccccc"
期望：style="background:#cccccc"
