### ISSUE TITLE
input placeholder-class 无效

### ISSUE THREAD

**Issue by hychaoxxx** [Meituan-Dianping/mpvue#198]
placeholder-style 可以

**Comment by aOrz** [comment]
应该是 css 的 scoped 造成的，去掉 scoped 试试

**Comment by prozwang** [comment]
还是会有啊，placeholder-class 和 placeholder-style都无效

**Comment by prozwang** [comment]
@aOrz

**Comment by aOrz** [comment]
@prozwang 贴下代码

**Comment by sonicsunsky** [comment]
我这边测试也是无效的，.设置input组件的placeholder-class样式无效

**Comment by michaelize** [comment]
去掉scoped也可以作为可接受的解决方案吗？
