### ISSUE TITLE
请问如何配置页面啊，找死找不到在哪里配置

### ISSUE THREAD

**Issue by g1mi** [Meituan-Dianping/mpvue#2]
如题，想尝试一下新加的页面又不知道在哪里查资料，如果issue恼人，请谅解

**Comment by hucq** [comment]
不必配置，代码构建后会自动生成。

**Comment by g1mi** [comment]
http://mpvue.com/build/  没有认真找， 先仔细再好好研究研究，不会乱开issue了😥

**Comment by g1mi** [comment]
http://mpvue.com/mpvue/quickstart/ 
1.此项目中在已有的template里面更改代码（如counter or index ...）可实现热更新，实时编译刷新，但添加的新页面无法实时编译（在微信开发者工具中未得到更新）。
2.添加新页面代码后构建可自动生成页面，但是页面的显示顺序似乎按是pages文件夹下新页面文件夹的首字母顺序来显示的（微信app.json中是以第一个写到的页面为首页），目前该template是以counter为首页，添加boofar文件夹，编辑好代码后以boofar为首页显示。

**Comment by aOrz** [comment]
http://mpvue.com/build/mpvue-loader/ 
app.json／page.json 这一段落 可以看下

**Comment by g1mi** [comment]
@aOrz 非常感谢，原来是自己挖的坑
`
export default {
    // 这个字段下的数据会被填充到 app.json ／ page.json
    config: {
        pages: ['static/calendar/calendar'， '^pages/list/list'], // Will be filled in webpack
        window: {
            backgroundTextStyle: 'light',
            navigationBarBackgroundColor: '#455A73',
            navigationBarTitleText: '美团汽车票',
            navigationBarTextStyle: '#fff'
        }
    }
};
`
之前找到这里，但自己没细看，

> mpvue的page页面命名规则与小程序相同
> 假如新建boofar页面，mpvue当中的结构为
`
index.vue
main.js
`
> 但是在app层面的main.js中的配置中应写为
`
‘pages/boofar/boofar’
`
而不是'pages/boofar/index', 真的是自己挖坑自己跳，跳着还要叫！

另外， @aOrz 你好，新页面实时构建的问题依旧存在，原有页面改变可实现实时构建，但新页面一定得ctrl+c 重新npm run dev后才能在工具当中看到， 即使在main.js当中的pages当中配置好也无法被实时构建

**Comment by aOrz** [comment]
因为新的页面需要添加进 webpack 的 entry，entry 是通过遍历 src/pages 目录下的 main.js 获得的，故需要重启 webpack

**Comment by g1mi** [comment]
@aOrz  🆗

**Comment by vinson2016** [comment]
那现在页面间跳转怎么写啊，直接加vue-router的方式？

**Comment by aOrz** [comment]
页面跳转可以使用 a 标签，会被转成 小程序的 navigator

**Comment by alpacachen** [comment]
请问如何设置首页

**Comment by weineel** [comment]
@alpacachen `src/main.js`, 
```
export default {
    config: {
        pages: ['^pages/pagename/pagename']
    }
}
```

**Comment by vinson2016** [comment]
@aOrz 那js方法里跳转要怎么写，还是把文档写详细点吧，希望马上能用到项目里。

**Comment by anchengjian** [comment]
@vinson2016 js 的跳转方法直接用 `wx.` 相关方法即可

```
wx.navigateTo({
  url: 'test?id=1'
})
```

 https://mp.weixin.qq.com/debug/wxadoc/dev/api/ui-navigate.html#wxredirecttoobject

**Comment by Tzrong** [comment]
> @alpacachen `src/main.js`,
> 
> ```
> export default {
>     config: {
>         pages: ['^pages/pagename/pagename']
>     }
> }
> ```

你好 按照这个提示已添加 重启项目 进入的首页设置无效
