### ISSUE TITLE
vuex的初始化问题

### ISSUE THREAD

**Issue by ilovemyboys** [Meituan-Dianping/mpvue#20]
mpvue-loader是不是对vuex做了特殊处理？是在Vue初始化参数options上挂了一个init方法吗？
这个不是在Vue2.0之后就废弃了么

**Comment by anchengjian** [comment]
没做任何处理，就是原本 vue 组件和 vuex 的用法，mpvue 没有在 options 上挂载 init 方法。

**Comment by OkOkOkNoNoNo** [comment]
vuex的applyMixin方法里有如下代码：
const version = Number(Vue.version.split('.')[0])

  if (version >= 2) {
    Vue.mixin({ beforeCreate: vuexInit })
  } else {
    // override init and inject vuex init procedure
    // for 1.x backwards compatibility.
    const _init = Vue.prototype._init
    Vue.prototype._init = function (options = {}) {
      options.init = options.init
        ? [vuexInit].concat(options.init)
        : vuexInit
      _init.call(this, options)
    }
  }

mpvue是不是没有设置Version，导致这个判断有问题

**Comment by F-loat** [comment]
试用了下，除了没有绑定 this.$store，需要在每个页面引用 store.js 外，和在 vue 中使用没有区别

**Comment by tangsj** [comment]
目前 vuex 只能单独在每个页面里面使用吗？ 没有全局的store 吗？

**Comment by F-loat** [comment]
@tangsj store 是全局的，不过目前需要在每个页面都引用下

**Comment by tangsj** [comment]
@F-loat 每个引入  不都是新new 的一个store 吗

**Comment by F-loat** [comment]
@tangsj 示例那么写可能是有点歧义，你自己新建 src/store/index.js，然后在每个 vue 文件中引用即可

**Comment by tangsj** [comment]
@F-loat 恩恩，目前我这样测试是通了，就是感觉有点怪怪的。

**Comment by F-loat** [comment]
@tangsj 嗯，暂时先这么用吧，他们有在处理这个问题

**Comment by iyezhou** [comment]
![440fbde52413e133507291978332b1b](https://user-images.githubusercontent.com/26378961/37267123-45456caa-25f9-11e8-9a39-696e5cdba0d6.png)
![fdd164117082481e2f5ee0c04e9ede8](https://user-images.githubusercontent.com/26378961/37267127-473c89a8-25f9-11e8-930e-98f60ce699fc.png)
Vue版本识别好像有问题呢

**Comment by weineel** [comment]
> 可以自定义一个Vue插件，把vuex store 挂在到 `$store`，在`src/main.js`里import一下就行了。这样就可以在不同的页面直接使用`this.$store`获取同一个store对象了。
1. store.js
```javascript
import Vue from 'vue'
import Vuex from 'vuex'
import state from './states'
import mutations from './mutations'
import remind from '../pages/remind/store'

Vue.use(Vuex)

const debug = process.env.NODE_ENV !== 'production'

Vue.use({
  install(Vue, options) {

    Vue.prototype.$store = new Vuex.Store({
      state,
      mutations,
      // 使用了vuex的模块化。
      modules: {
        remind
      },
      strict: debug
      // plugins: debug ? [createLogger()] : []
    })
  }
})
```

2. `src/pages/remind/store.js`

```javascript
// initial state
const state = {
  test1: 'test1'
}

// getters
const getters = {
}

// actions
const actions = {
}

// mutations
const mutations = {
  test1nn(state, nv) {
    state.test1 = nv || 'test1nn'
  }
}

export default {
  namespaced: true,
  state,
  getters,
  actions,
  mutations
}
```

3. `src/main.js`

```javascript
import './store'
```

**Comment by OkOkOkNoNoNo** [comment]
这种方式component里能通过this.$store访问？
我是用Vue.extend来实现的

**Comment by F-loat** [comment]
目前的问题确实是因为 vue 版本号不对造成的，改到 2.0 以上就正常了，官方应该最近会解决

**Comment by weineel** [comment]
@ilovemyboys 可以的，我现在的项目里就是这么用的。

**Comment by aOrz** [comment]
升级到 mpvue，mpvue-loader,mpvue-template-compiler 到最新版，可解决问题

**Comment by weineel** [comment]
@aOrz 

升级到最新版后
1. vuex的namespace功能无法使用了。`mapState('remind', ['test1'])`，这种vuex 快捷方式会报`Cannot read property 'remind/' of undefined`的错。
2. 使用`this.$store.commit`会提示`this.$store.commit is not a function`, `this.$store`确实可以直接使用了。

> 不知道做了怎样的处理？有没有提供禁用这种处理的方法？

**Comment by aOrz** [comment]
@weineel 能不能提供个 demo？

**Comment by weineel** [comment]
@aOrz 
构建demo后，发现没有问题。仔细检查了自己的代码，发现是自己有个地方写错了。感谢。

**Comment by anchengjian** [comment]
分享一个 vuex 初始化全局 store 的方法：

```  javascript
import Vue from 'vue'
import App from './index'
import store from './store'

const app = new Vue({
    store,
    ...App
})
app.$mount()
```

**Comment by shhdgit** [comment]
@anchengjian 的方法要加在每个page的main.js里
顺带问下App.vue是做啥的

**Comment by bowencool** [comment]
@anchengjian 试了下好像没有用
``` javascript
const app = new Vue({
    store,
    ...App
})
app.$mount()
```

**Comment by F-loat** [comment]
@Bowennan vuex 实例化之后引入到各个页面里就行

可以在每个 main.js 文件里引入
``` js
const app = new Vue({
    store,
    ...App
})
app.$mount()
```

也可以在每个 vue 文件中引入
``` js
export default {
  data() {
    return {}
  },
  store
}
```

**Comment by syhsghr1993** [comment]
@F-loat 这样是否会造成编译后文件过大的问题，每个页面都会copy一份store文件

**Comment by F-loat** [comment]
store 是共用的啊，会打包在 vendor.js 里

**Comment by sideFlower** [comment]
这个 不可以在src/main.js中 直接 Vue.prototype.$store = store 吗 ？  然后this.$store....

**Comment by F-loat** [comment]
@sideFlower 可以的

**Comment by mdsb100** [comment]
@aOrz 请求重新打开这个issue，使用如下版本依然有问题。
```
"mpvue": "^1.0.9",
"vuex": "^2.3.1"
    "mpvue-loader": "^1.0.12",
    "mpvue-webpack-target": "^1.0.0",
    "mpvue-template-compiler": "^1.0.9",
```

**Comment by aOrz** [comment]
@mdsb100  具体描述下问题？

**Comment by ananiy** [comment]
@aOrz 我在新的page里面, computed的state都不更新 这个有遇到吗
