### ISSUE TITLE
slot备用内容绑定指令无效？

### ISSUE THREAD

**Issue by youngluo** [Meituan-Dianping/mpvue#200]
编译前：

```
<div>
  <slot>
    <span v-text="content"></span>
  </slot>
</div>
```

编译后：

```
<view>
  <label class="_span data-v-54348059"></label>
</view>
```
v-text指令无效

**Comment by anchengjian** [comment]
复杂 slot 目前支持程度有限

**Comment by youngluo** [comment]
@anchengjian 关于复杂slot的支持，建议提升实现的优先级，组件开发实在太受限了

**Comment by bigmeow** [comment]
@anchengjian  能支持小程序官方的slot否；换句话，组件的solt编译器不做处理，让官方去解析

**Comment by anchengjian** [comment]
[1.0.8](https://github.com/Meituan-Dianping/mpvue/releases/tag/1.0.8) 修复了一些相关问题，请升级相应的 `mpvue mpvue-template-compiler mpvue-loader` 再试一下，我本地是不能复现

**Comment by Pooh980219** [comment]
是否支持自定义指令

**Comment by anchengjian** [comment]
@Pooh980219 不支持
