### ISSUE TITLE
if you  have fixed fileName in pages,  you must remove the old

### ISSUE THREAD

**Issue by Bowennan** [Meituan-Dianping/mpvue#201]
# fixed fileName in pages, remove the old

**问题复现步骤:**

1. you have writen one file, name 'indexPage'
2. now, you want to fixed the fileName to 'indexpage'
3. you must remove the indexPage by yourself, the mpvue won't do it!
4. take care of your static file!

**期望的表现:**

Automatically modify the name of the file

**观察到的表现:**

 ./pages/indexPage/main.wxss File not found: ../../static/css/pages/frontpage/main.wxss
or  ./pages/indexPage/main.js File not found: ../../static/js/pages/frontpage/main.js

**屏幕截图和动态 GIF 图**

![复现步骤的屏幕截图和动态 GIF 图](图片的 url)

**Comment by anchengjian** [comment]
This is the same problem as http://mpvue.com/qa/#_2

**Comment by Bowennan** [comment]
no no no, have a try!

**Comment by aOrz** [comment]
you can add ` rm -rf dist`  in your build scripts。
