### ISSUE TITLE
tencent-wx-app支持的基础库是多少?

### ISSUE THREAD

**Issue by QiYunMeng1126** [Meituan-Dianping/mpvue#202]
比如说wx.showToast()中的icon在1.9.0之后开始支持none,而tencent-wx-app却没有

**Comment by aOrz** [comment]
tencent-wx-app 这个是指？

**Comment by QiYunMeng1126** [comment]
node_modules里面的,不是您们依赖进去的?
<img width="376" alt="2018-03-30 10 25 20" src="https://user-images.githubusercontent.com/13884135/38122561-616d737e-3408-11e8-8748-55b0e91d9aea.png">

**Comment by QiYunMeng1126** [comment]
搞错了.不好意思.
