### ISSUE TITLE
使用getPhoneNumber组件，无法识别回调函数？

### ISSUE THREAD

**Issue by shawn19911216** [Meituan-Dianping/mpvue#204]
使用getPhoneNumber时，
在template中添加<button open-type="getPhoneNumber" bindgetphonenumber="getNumber"> phone</button>来获取用户手机授权，
在methods中添加以下代码
getNumber() {
   console.log('123');
},

授权之后的显示如下,

![1522395668858](https://user-images.githubusercontent.com/28244548/38129261-de3fa926-3430-11e8-8c7b-7850ffb1338a.jpg)
![1522395640681](https://user-images.githubusercontent.com/28244548/38129270-e85594e8-3430-11e8-846a-b28861d02c51.jpg)

请问 如何正常使用获取用户手机授权

**Comment by aOrz** [comment]
小程序原生事件的监听形式为 将 bind 换成 @，例：bindgetphonenumber 应使用 vue 的时间监听方式 @getphonenumber
