### ISSUE TITLE
mpvue 动画效果怎么实现

### ISSUE THREAD

**Issue by yanpeng1995** [Meituan-Dianping/mpvue#205]
# [问题简单描述]
想要在mpvue里面实现vue里面的过渡动画效果
**问题复现步骤:**

1. [第一步]
2. [第二步]
3. [其他步骤...]

**期望的表现:**

[在这里描述期望的表现]

**观察到的表现:**

[在这里描述观察到的表现]

**屏幕截图和动态 GIF 图**

![复现步骤的屏幕截图和动态 GIF 图](图片的 url)

**Comment by aOrz** [comment]
可以用 css 实现或者小程序的 https://developers.weixin.qq.com/miniprogram/dev/api/api-animation.html#wxcreateanimationobject
