### ISSUE TITLE
如何在vue中设置去掉转发功能

### ISSUE THREAD

**Issue by zxy198717** [Meituan-Dianping/mpvue#206]
原生小程序只有实现`onShareAppMessage`才会有转发功能，但是用mpvue之后，默认就有转发，该怎么去掉呢？

**Comment by anchengjian** [comment]
抱歉，我们默认全部都开了分享。。。

https://github.com/Meituan-Dianping/mpvue/blob/master/src/platforms/mp/runtime/lifecycle.js#L212-L215

**Comment by bigmeow** [comment]
@anchengjian 所以现在只能去runtime的源码里把这行生命周期的代码干掉？

**Comment by zxy198717** [comment]
@bigmeow 直接去掉会造成没有转发功能了~~~

@anchengjian 期待官方能早日出解决方案

**Comment by mantutu** [comment]
同希望能早日出解决方案，我们的项目正在用mpvue

**Comment by loveLifeTeam** [comment]
使用onShareAppMessage初始化一下分享，这时候原生小程序，覆盖掉了mpvue的分享，在onLoad的时候添加wx.hideShareMenu（）;方法，这时候达到的效果：点击右上角，不会出现转发项。
