### ISSUE TITLE
project.config.json没有输出到dist文件夹

### ISSUE THREAD

**Issue by bowencool** [Meituan-Dianping/mpvue#209]
# [问题简单描述]
`project.config.json`没有输出到`dist`文件夹

**期望的表现:**
希望第一次启动时可以输出`/dist/project.config.json`文件，并和`project.config.json`实时同步

**Comment by bowencool** [comment]
目前是用`copy-webpack-plugin`直接复制过去了。根目录下的`project.config.json`有什么用，是个bug吗？
![image](https://user-images.githubusercontent.com/20217146/38169306-21aca31c-3599-11e8-9f01-412b363cbba2.png)

**Comment by aOrz** [comment]
https://developers.weixin.qq.com/miniprogram/dev/devtools/edit.html#%E9%A1%B9%E7%9B%AE%E9%85%8D%E7%BD%AE%E6%96%87%E4%BB%B6
`可以在项目根目录使用 project.config.json 文件对项目进行配置。`不需要非得是 dist 目录，打开时，直接打开项目目录即可

**Comment by zmqcherish** [comment]
但是开发云函数时候，是需要这个文件的
