### ISSUE TITLE
npm下载其他依赖时不能在项目中使用

### ISSUE THREAD

**Issue by flyingalex** [Meituan-Dianping/mpvue#210]
# 问题如题所说

**问题复现步骤:**
以`leancloud-storage` 这个包为例，
1. [第一步]
跑 `npm install --save leancloud-storage` 

2. [第二步]
在文件中加载这个包
```js
import { AV, User } from 'leancloud-storage';
````

**期望的表现:**
不会报错

**观察到的表现:**
报错显示依赖找不到

**屏幕截图和动态 GIF 图**
<img width="815" alt="2018-04-01 18 16 20" src="https://user-images.githubusercontent.com/11313145/38172121-04a79eee-35d9-11e8-979f-8c0cdb5fd55d.png">

**Comment by anchengjian** [comment]
fs 是 Node.js 的原生依赖包，在小程序里当然不支持。。。
你可以尝试引 leancloud 的 wx 小程序包，举个例子

```javascript
import { AV, User } from 'leancloud-storage/dist/av-weapp-min.js ';
```

**Comment by Michel-Yang** [comment]
遇到同样的问题
![微信图片_20190428112413](https://user-images.githubusercontent.com/19601873/56858155-4421d180-69a8-11e9-8057-1aaf0fead66f.png)
