### ISSUE TITLE
组件和小程序系统组件重名会引发比较隐晦的BUG

### ISSUE THREAD

**Issue by ksco** [Meituan-Dianping/mpvue#211]
# 组件和小程序系统组件重名会引发比较隐晦的BUG

**问题复现步骤:**

1. 定义一个和系统组件重名的 components，例如 `icon`；
2. 编译正常通过，如果一个组件内出现两次以上 `icon` 组件，则会引发错误；
3. 如下图所示：

![66bf4d4dd1a7242b0c2edf528e0146c7](https://user-images.githubusercontent.com/15257961/38172961-57d0a200-35e8-11e8-8dc5-e8e63e13ce7d.jpg)

**期望的表现:**

![549fd292-3fce-4b87-9886-69e01f0db7cc](https://user-images.githubusercontent.com/15257961/38173013-62a1ceec-35e9-11e8-980e-e0c95f7d888e.png)

**观察到的表现:**

![9e31d1867f9002ea637da6d2f0db1694](https://user-images.githubusercontent.com/15257961/38172979-ae24ef3a-35e8-11e8-9c48-bee4214d6a93.jpg)

**说明**

当然，定义和系统重名的组件报错是正常的，只是希望可以更加显式地提示一下，防止后人踩坑。😆

**Comment by soapper** [comment]
这个确实有问题

**Comment by hellolibo** [comment]
我还遇到不能 countdown 的情况

**Comment by aOrz** [comment]
文档已经标明：http://mpvue.com/qa/
