### ISSUE TITLE
更新mpvue-loader后 报this.cacheable

### ISSUE THREAD

**Issue by Herrengit** [Meituan-Dianping/mpvue#214]
# [问题简单描述]

更新mpvue-loader后，webpack跟着更新，报错 this.cacheable 找不到方法

**问题复现步骤:**

更新mpvue-loader

**Comment by anchengjian** [comment]
有 demo，提供一个 demo 吧

**Comment by aOrz** [comment]
webpack 版本多少

**Comment by aOrz** [comment]
尝试升级未复现，应该是是升级 webpack 版本导致的，目前不支持更高版本的 webpack，有问题再反馈
