### ISSUE TITLE
在 onHide 中重置 data 不会即刻生效，重新进入页面时会先显示旧状态

### ISSUE THREAD

**Issue by blade254353074** [Meituan-Dianping/mpvue#215]
onHide 中重置 data，进入到其他页面，
返回到之前的页面时，旧 data 状态依然保持，
然后会闪现为重置后的 data 状态

**Comment by blade254353074** [comment]
意味着我们应该在 onShow 中去重置需要重置的 data 会更好些？，反正 onHide 中做出的改变是不能立即 render 的，和在 onShow 中做出改变一样

**Comment by anchengjian** [comment]
#140 跟这个属于同一个问题

**Comment by blade254353074** [comment]
不一样，我按你说的在 onHide 中重置的数据

> 这个是可能的，因为页面数据是存在于 js 中，切换页面的时候是会把数据 setData 到 render 进程中，可能有个老数据显示的闪现，目前的解决方式可以在 onHide 的时候重置数据或者加载 loading 动画，在 onShow 的时候加载数和或者取消 loading 动画。
后期考虑可以从底层优化掉闪现的问题。

但出现了闪现问题

**Comment by phpcxy** [comment]
你的页面是tab吗，我也出现这样的情况了。在开发者工具中查看AppData那数据并没有被重置到

**Comment by tangw4wo** [comment]
解决了吗？我也是tabBar切换，在hide里重置或是show里重置，都会出现页面闪烁的问题

**Comment by ANT-CYJ** [comment]
放心吧，我已经收到啦。
