### ISSUE TITLE
如何配置单个页面的下拉刷新

### ISSUE THREAD

**Issue by SuperLiuYinXin** [Meituan-Dianping/mpvue#216]
# 如何配置单个页面的下拉刷新
我在使用的时候遇到一个问题，就是需要设置一个页面单独的下拉刷新，如果在全局的main.js使用的话所有页面都会有下拉刷新，这并不是我需要的。而且小程序支持单个页面开启下拉刷新。 
但是如果在每个pages目录下面的main.js配置的话又不会生效。（可能是我的配置不对）

在单个页面的main.js 中配置：
```javascript
import Vue from 'vue'
import App from './index'

const app = new Vue(App)
app.$mount()


// 这样并不生效
export default {
  config: {
    window: {
      navigationBarBackgroundColor: '#fff',
      navigationBarTextStyle: 'black',
      navigationBarTitleText: '...',
      navigationStyle: 'default',
      backgroundColor: '#fff',
      backgroundColorTop: '#fff',
      enablePullDownRefresh: true
    }
  }
}
````
最后我的解决方法是在生成的 `dist` 目录下面找到那个页面。手动加上  `页面名.json` 之后才可以的
```json
{
    "enablePullDownRefresh": true
}
```

**Comment by anchengjian** [comment]
应该是这样吧，window 貌似是 app 专有的

```javascript
export default {
   config: {
        "enablePullDownRefresh": true
    }
}
```

**Comment by SuperLiuYinXin** [comment]
谢谢大佬。可以了！

**Comment by SuperLiuYinXin** [comment]
主要是在文档里面没有介绍使用,希望在文档里面修改一下。

**Comment by anchengjian** [comment]
http://mpvue.com/build/mpvue-loader/#appjsonpagejson 在这个地方，写的不是很明显

**Comment by goodwong** [comment]
小程序比较坑，app.json要包裹在window字段里，page.json不用包裹。。。

**Comment by lemonpigpig** [comment]
各位大佬我的下拉刷新，三个点没有出来

**Comment by Jackliu007888** [comment]
@lemonpigpig 没有三个点。我是fixed一层不动。再加个空盒子 在空盒子里加刷新的点跟文字，加动画就很好

**Comment by McsNick** [comment]
@lemonpigpig 我遇到同样的问题，在单页面的main内添加配置解决了
export default {
  config: {
    backgroundTextStyle: 'dark'
  },
}

**Comment by yuzexia** [comment]
为啥我的在`dist`目录项有`page.json`，也不生效,
使用export default {} 进行设置也不生效，
mpvue-loader: 1.1.2

**Comment by kasep94** [comment]
@yuzexia mpvue-loader@1.1.2-rc.4 升级指南。
之前写在 main.js 中的 config 信息，需要在 main.js 同级目录下新建 main.json 文件，使用 webapck-copy-plugin copy 到 build 目录下

**Comment by liuleiasd** [comment]
和当前main.js平级新建一个main.json,   
{
  "enablePullDownRefresh": true
}
