### ISSUE TITLE
mpvue是否支持小程序当中的<template>标签？

### ISSUE THREAD

**Issue by ZionStark** [Meituan-Dianping/mpvue#218]
未看到文档中有提及这个？

**Comment by aOrz** [comment]
支持

**Comment by ZionStark** [comment]
@aOrz 请问如何使用？

**Comment by aOrz** [comment]
为什么要用 template 呢？

**Comment by ZionStark** [comment]
最近发现一个小程序UI库叫ZanUI，想试着引入到项目当中，看下效果如何。
但是发现它的部分组件是通过模板template引入的
我尝试了一些方式来引入 到最后却报错
关于mpvue开发文档中我也未找到相应的方法
所以特地来问问 不知道您有没有更好的方式
@aOrz

**Comment by aOrz** [comment]
可以看下 https://github.com/armyja/mpvue-zanui

**Comment by suinia** [comment]
找了一会还是没找到怎么使用?
```
<import src="../../components/html-parse/index.wxml" />
<template is="html-parse" />
```

**Comment by suinia** [comment]
@F-loat 请问知道怎么引入小程序的 template 吗？

**Comment by F-loat** [comment]
mpvue 的组件就会转为 template，你如果直接用 template 的话，应该不会被处理，所以组件最好是放在 static 目录里

**Comment by suinia** [comment]
可以引用了，不过 data 不知道怎么传递。

**Comment by F-loat** [comment]
双大括号就可以吧

**Comment by tingzhong666** [comment]
data不能传值，有什么方案吗
