### ISSUE TITLE
构建新的项目直接报错,找不到根目录下的game.json文件

### ISSUE THREAD

**Issue by yinminqian** [Meituan-Dianping/mpvue#22]
](url)

**Comment by anchengjian** [comment]
我们目前没有对小游戏进行支持，你该不会是选错 AppID 吧

**Comment by yinminqian** [comment]
不是,我选择的体验版,就是不用填写AppID,已经找出了问题,vue init 创建项目的时候取消安装了Eslint,就会报这个错误.全部安装提示的插件就好了.
