### ISSUE TITLE
入口 main.js 文件中, tabBar 图片路径无法识别

### ISSUE THREAD

**Issue by parrotdance** [Meituan-Dianping/mpvue#221]
**问题复现步骤:**

入口 `main.js` 文件中 , 在 `tabbar` 字段加入的图片路径无法识别. 

**期望的表现:**

图片路径可通过 `require` 方法设置为开发环境下的路径, 并引入对应的静态资源. 
编译后转为生产环境下路径.

**观察到的表现:**

在入口的 `main.js` 中, 使用 `require` 方法引入静态图片资源无效, 发现在编译后的文件中并未被打包到 `dist/static` 下.
后来通过手动将图片文件放入编译后的文件夹 `'dist/static'` 下, 并将 `main.js` 路径设置为打包后的路径, 即 `static/img/[name].[ext]` 才可正常识别.

**Comment by hanger121212** [comment]
本地图片资源可以放在根目录static下,与src同级,编译后就会在dist/static下了

**Comment by lil-Jay** [comment]
我也遇到这个问题了。更神奇的是我的电脑没问题，我同事的电脑就硬是编译不出图片

**Comment by lil-Jay** [comment]
也应该是不能放在src深层的页面路径中，放在最外层也方便配合cdn上传工具，打包时将整个static文件上传，以减少体积

**Comment by parrotdance** [comment]
我认为这不应该作为一个常规的解决方式, 应该从资源打包机制上解决这个问题.
