### ISSUE TITLE
组件嵌套组件会报错

### ISSUE THREAD

**Issue by Hadroning** [Meituan-Dianping/mpvue#223]
想做一个栅格的组件
<img width="333" alt="68f7d7fd-c548-4f1b-a94d-76dcfba764f6" src="https://user-images.githubusercontent.com/20159065/38234808-8dbc05b6-3751-11e8-98bf-21ff7baa5f66.png">

<img width="793" alt="dbf305c7-8df4-48c9-ae60-a3c011e1fb4f" src="https://user-images.githubusercontent.com/20159065/38234649-1010d542-3751-11e8-9e4d-9750ce5f9d49.png">

**Comment by aOrz** [comment]
能提供个demo 吗

**Comment by aOrz** [comment]
是使用的 slot 吗？

**Comment by Hadroning** [comment]
嗯，是用的slot，又发现了一个新问题，slot里面的元素绑定事件会失效...

**Comment by anchengjian** [comment]
[1.0.8](https://github.com/Meituan-Dianping/mpvue/releases/tag/1.0.8) 已修复，请升级相应的 `mpvue mpvue-template-compiler mpvue-loader` 后使用

**Comment by alex-chan** [comment]
1.0.8组件嵌套能渲染吗？我的不生效
