### ISSUE TITLE
师傅们，怎么取消页面切换时的动画，现在是左滑右滑的效果

### ISSUE THREAD

**Issue by Bowennan** [Meituan-Dianping/mpvue#224]
# 我自己写了一个navTabs，使用navigator的重定向跳转
![e2103431-9ddb-4c17-873a-beae3776a90c](https://user-images.githubusercontent.com/23648901/38236850-01cbbf72-3758-11e8-8232-2918b9a00494.png)
![a5dd5504-98ca-45fa-bb24-4f25a030df03](https://user-images.githubusercontent.com/23648901/38237196-1094f02c-3759-11e8-8b62-bb23671aed8e.png)

**问题复现步骤:**

1. [第一步]
2. [第二步]
3. [其他步骤...]

**期望的表现:**

[在这里描述期望的表现]

**观察到的表现:**

[在这里描述观察到的表现]

**屏幕截图和动态 GIF 图**

![复现步骤的屏幕截图和动态 GIF 图](图片的 url)

**Comment by F-loat** [comment]
不要使用 navigator 跳转，自定义 nav 只能把 tab 页都写在一个页面里
