### ISSUE TITLE
希望mpvue 支持v-html 

### ISSUE THREAD

**Issue by EzioL** [Meituan-Dianping/mpvue#225]
希望mpvue 支持v-html

**Comment by F-loat** [comment]
这个其实可以像 v-text 那样转成 rich-text 组件

**Comment by haryzxw** [comment]
@EzioL  同希望！话说 你有找到替代方法吗？ 我刚刚也碰到要解析富文本的问题

**Comment by F-loat** [comment]
@haryzxw 直接用 rich-text 组件，或者用 [mpvue-wxParse](https://github.com/F-loat/mpvue-wxParse)

**Comment by haryzxw** [comment]
@ @F-loat 嗯嗯  谢谢回复 我去试试看

**Comment by haryzxw** [comment]
@F-loat  啊 刚刚试了下 微信小程序的rich-text组件，但是看它是完全解析成文本了，不包含标签了，我没办法对富文本里面的标签添加css样式了。你推荐的另一个mpvue-wxparse 能解析成含标签的嘛？

**Comment by F-loat** [comment]
可以，你试试看，有问题去反馈就好

**Comment by haryzxw** [comment]
@F-loat  好的呀！ 3q～

**Comment by aOrz** [comment]
由于小程序能力限制暂不提供 v-html 指令
