### ISSUE TITLE
两页面互相跳转至第5次时，跳转失效

### ISSUE THREAD

**Issue by zgl0108** [Meituan-Dianping/mpvue#227]
两页面互相跳转至第5次时，跳转失效

官方my-project项目，首页获取图像后，
修改跳转地址为“pages/counter/counter”
点击跳转到"pages/counter/counter"页面，
在该页面点击“回到首页”又跳转至首页，
依次循环至第5次，跳转失效

**Comment by anchengjian** [comment]
https://developers.weixin.qq.com/miniprogram/dev/api/ui-navigate.html#wxnavigatetoobject 
**注意：目前页面路径最多只能十层。**
