### ISSUE TITLE
设置分包配置,编译后的app.json页面会重复

### ISSUE THREAD

**Issue by hanger121212** [Meituan-Dianping/mpvue#229]
mpvue: 1.0.7
mpvue-template-compiler: 1.0.7
mpvue-loader: 1.0.10

根据小程序的格式,在main.js中添加subPackages配置
```javascript
    subPackages: [{
      "root": "test_subpackages",
      "pages": [
        "testa", "testb"
      ]
    }],
```
在webpack的entry中引入分包的页面.
编译后的app.json分包页面重复
```javascript
{
  "pages": [
    "pages/cafe_house/cafe_house",
    "test_subpackages/testa",
    "test_subpackages/testb"
  ],
  "subPackages": [
    {
      "root": "test_subpackages",
      "pages": [
        "testa",
        "testb"
      ]
    }
  ],
}
```
小程序就会报错
![image](https://user-images.githubusercontent.com/16555766/38301116-33039e32-3831-11e8-860d-9a9605f730db.png)

**期望的表现:**

应该是mpvue-loader没做这方面的处理吧,或者增加取消自动加到pages的配置

**Comment by lil-Jay** [comment]
mpvue什么时候可以支持小程序分包啊，我的项目都要超2m了

**Comment by aOrz** [comment]
参考下 https://github.com/mpvue/mpvue-quickstart/pull/39 的配置改动，将 app.json 使用插件直接 copy 过去。

**Comment by aOrz** [comment]
@lil-Jay 参考 #672
