### ISSUE TITLE
v-for 中 index下标在vue中是Number  转义后是 String

### ISSUE THREAD

**Issue by jiangyanghe** [Meituan-Dianping/mpvue#230]
<img class="avatar" v-if="cyUsers.length > 0" v-for="(item, i) in cyUsers" :key="i" 
             :style="{ right: i*40+'rpx', zIndex: i*10}" src="https://static.iyunbao.com/website/health/iybApp/iyb_passport/user/team/apply_banner.png">

:style 中我想输出30 70 110 150 等差数列

**Comment by anchengjian** [comment]
number 转 string ，没毛病啊。。。
还有这个图片没看懂你的 `:style` 的逻辑，建议贴代码或者 demo
