### ISSUE TITLE
请求接口报TypeError: Cannot read property '__ob__' of undefined

### ISSUE THREAD

**Issue by winglau14** [Meituan-Dianping/mpvue#231]
# [问题简单描述]

**问题复现步骤:**

1. [第一步]第一次请求成功，页面不会报错
2. [第二步]第二次请求同一个接口，就报这个错误了，TypeError: Cannot read property '__ob__' of undefined
3. [其他步骤...]

**期望的表现:**

[在这里描述期望的表现]

**观察到的表现:**

[在这里描述观察到的表现]

**屏幕截图和动态 GIF 图**

![复现步骤的屏幕截图和动态 GIF 图](图片的 url)

**Comment by winglau14** [comment]
@aOrz  老哥，不好意思，代码没法提供，因为是公司内部的项目，然后我简单给你描述下吧，就是pageA=>pageB,pageA有个输入框，输入完成然后跳转到pageB，这时数据显示是正常的，然后返回pageA再重新输入跳转到pageB,数据状态还是上次操作的，然后我尝试了在onUnload里重置数据状态还是不行，这就算了，然后点击返回就报‘TypeError: Cannot read property '__ob__' of undefined’

**Comment by anchengjian** [comment]
是最新的 mpvue 么？[1.0.7](https://github.com/Meituan-Dianping/mpvue/releases/tag/1.0.7) 修复了一个类似的问题

**Comment by winglau14** [comment]
是1.07版本，还是不行啊，老哥，等你们修复了，再来继续玩起，555

**Comment by aOrz** [comment]
能不能提供个可复现的 demo，我们无法复现也无从查起

**Comment by JunaYa** [comment]
错误提示
   ```
TypeError: Cannot read property '__ob__' of undefined
    at VueComponent.Vue.$destroy (index.js:2115)
    at destroy (index.js:3079)
    at invokeDestroyHook (index.js:4561)
    at removeVnodes (index.js:4577)
    at updateChildren (index.js:4685)
    at patchVnode (index.js:4732)
    at updateChildren (index.js:4636)
    at patchVnode (index.js:4732)
    at Vue$3.patch (index.js:4846)
    at Vue$3.patch [as __patch__] (index.js:4920)
```
因为在组件 ComponentA 中保留了空的  data(){}, 组件 ComponentA 根据条件加载或销毁，即带有 v-if，当 Component 销毁时会出现上述问题，去掉 data(){}  就没解决了，具体原因没有深究。
