### ISSUE TITLE
关于相同路由页面只有一个实例的问题

### ISSUE THREAD

**Issue by fangdiao** [Meituan-Dianping/mpvue#233]
# [问题简单描述]
比如我进入详情页，然后在详情页中又通过 `wx.navigateTo` 进入下个详情页，以此类推。但是相同路由的页面只有一个实例，回退到上个详情页的时候依然显示的是最后一个详情页的数据。
我现在的方案是在state中放了一个模拟的detailStack，打开新的详情页就进栈，回退就出栈。但是这个有个问题是，每次回退是相当于重新渲染一次详情页，会有明显的渲染延迟，至少会闪一下，无法做到顺滑回退。请问mpvue会实现为相同路由的页面创建多个实例吗

**问题复现步骤:**

1. [第一步]
2. [第二步]
3. [其他步骤...]

**期望的表现:**

[在这里描述期望的表现]

**观察到的表现:**

[在这里描述观察到的表现]

**屏幕截图和动态 GIF 图**

![复现步骤的屏幕截图和动态 GIF 图](图片的 url)

**Comment by hucq** [comment]
相同问题，请参考[issue #140](https://github.com/Meituan-Dianping/mpvue/issues/140)
