### ISSUE TITLE
mpVue双向数据绑定,无法更新View绑定的class

### ISSUE THREAD

**Issue by Mixlong** [Meituan-Dianping/mpvue#234]
![1522990351994](https://user-images.githubusercontent.com/27038897/38403972-666d1e56-3999-11e8-856c-56f697d6e9ec.jpg)
# [问题简单描述]

**问题复现步骤:**

1. [第
![89733b38-889d-4078-ad3b-1ba488884be0](https://user-images.githubusercontent.com/27038897/38403909-22396ffa-3999-11e8-922e-d45c459bbb7c.png)
![d8ab7c23-bc33-4dfa-802a-2d9ddc718040](https://user-images.githubusercontent.com/27038897/38403913-29a7a0ea-3999-11e8-98ce-d1ff0f316235.png)

1.绑定v-model
2.输入表单数据不能更新，实现添加class
**期望的表现:**

**观察到的表现:**

[在这里描述观察到的表现]

**屏幕截图和动态 GIF 图**

![复现步骤的屏幕截图和动态 GIF 图](图片的 url)

**Comment by ShenJet** [comment]
buttom
button
