### ISSUE TITLE
支持输出小程序和静态文件到不同目录

### ISSUE THREAD

**Issue by fengcen** [Meituan-Dianping/mpvue#235]
可否支持配置输出小程序到 `dist/mina`，图片/音频等文件输出到 `dist/static`

需求：
开发小程序的时候，如果需要远程调试，因为图片/音频等文件和小程序在同一个目录，所以微信开发者工具会提示体积大于 2M，所以希望支持分离输出小程序文件和需要服务器的静态文件。

**Comment by aOrz** [comment]
可使用 https://github.com/webpack-contrib/copy-webpack-plugin 自行配置
