### ISSUE TITLE
有没有人遇到wx.request后无法更新data的情况

### ISSUE THREAD

**Issue by xxliud** [Meituan-Dianping/mpvue#240]
有没有人遇到无法更新data的情况
从接口success回来给data赋值以后在页面无法渲染出数据的问题
![image](https://user-images.githubusercontent.com/8509171/38464376-670e286c-3b3f-11e8-960f-f92aa344eaaf.png)
接口地址腻了, 请求都成功, this.holy 也打印出来，就是 for循环无法打印出数据, 感觉就像是 success打印this.holy能打印出数据,但是就是不能在for循环里显示

**Comment by anchengjian** [comment]
请注意 this 指向，特别是 wx.request 的 success 回调中
