### ISSUE TITLE
多次进入同一个页面，有一定几率数据渲染的时候变成了 undefined

### ISSUE THREAD

**Issue by fengcen** [Meituan-Dianping/mpvue#242]
# [问题简单描述]
多次进入同一个页面，有一定几率数据渲染的时候变成了 `undefined`。
分析 vuex 的 mutation log 发现数据是正确的。
通过 `onLoad` 打印出来的数据是正确的，但是渲染的页面打印出来的是空的。
数据是通过`vuex-class` 的 `@Getter()` 来获取的。

**问题复现步骤:**
项目用到了 `vuex`, `vuex-class` , `vue-property-decorator`，因为项目比较大，可能比较难通过简单的 demo 复现。但是判断应该是数据渲染的时候可能没有正确同步数据到小程序的页面。

**期望的表现:**
渲染正确的数据，而不是 `undefined`

**Comment by fengcen** [comment]
通过 `@Component({ props: ['name']})` 获取的数据也有一定几率渲染的时候是 `undefined`

**Comment by fengcen** [comment]
继续分析了一下我的代码，发现好像只是通过 `props` 传递的数据有一定几率渲染的时候是 `undefined`

**Comment by pcloth** [comment]
感觉应该是你获取数据到写入数据之间的时间差问题。讲道理来说，你无论进入页面多少次，数据获取到了就不会变回undefined，除非你有清空数据的动作？

**Comment by fengcen** [comment]
没有清空的逻辑，进入同一个页面不是返回重新接入，而是有一个流程，从一个页面一直走下去，走到最后直接返回首页，继续走一个循环，我换成使用 vuex 来传递数据而不是 props，就不会 undefined 了，只有通过 props 传递的数据有可能变成 undefined，我也想过有可能是数据同步的时间差问题

**Comment by tmj1220** [comment]
遇到问题类似，现在有什么解决方案吗
