### ISSUE TITLE
关于mpvue-router-patch的问题

### ISSUE THREAD

**Issue by ai2010yu** [Meituan-Dianping/mpvue#243]
mpvue-router-patch 大部分与 vue-router 一致，具体差异之后会补全，这句话我都理解是功能和vue-router基本一致包括用法，但是看了官方的列子那个it之家的列子
![image](https://user-images.githubusercontent.com/6140529/38466602-534d5662-3b5e-11e8-883f-91af163f759d.png)
![image](https://user-images.githubusercontent.com/6140529/38466605-7128499e-3b5e-11e8-9bba-f0fdf840c374.png)
只是在webpack里打包构建的时候做一个入口文件吗？不是很明白
而且
![image](https://user-images.githubusercontent.com/6140529/38466751-e00c6632-3b5f-11e8-987d-4366a7dfe7d0.png)
config这个属性是什么意思，属性里边的参数是什么意思

**Comment by F-loat** [comment]
这个涉及到另外一个库 [mpvue-entry](https://github.com/F-loat/mpvue-entry)

**Comment by F-loat** [comment]
@ai2010yu  不是，不过这两个库结合起来用会更利于转 web 时使用 vue-router

**Comment by F-loat** [comment]
主要功能是在 mpvue 中直接使用 $route 和 $router
