### ISSUE TITLE
mpvue-loader 热重载不触发

### ISSUE THREAD

**Issue by CXY037** [Meituan-Dianping/mpvue#245]
# [问题简单描述]

**问题复现步骤:**

1. [第一步] 保存vue文件不触发重载
2. [第二步] 保存main.js 文件触发重载
3. [其他步骤...]

**期望的表现:**

[在这里描述期望的表现]

**观察到的表现:**

[在这里描述观察到的表现]

**屏幕截图和动态 GIF 图**

![复现步骤的屏幕截图和动态 GIF 图](图片的 url)

**Comment by soapper** [comment]
我直接把weui.wxss 文件变更后缀后引入是否会引起这个问题？

**Comment by lizhoukai** [comment]
我也发现这个问题了，更改vue文件后，小程序窗口有显示刷新，但代码没同步，必须重启终端才可以

**Comment by F-loat** [comment]
使用的版本请说明一下

**Comment by lizhoukai** [comment]
@F-loat 我的是最新1.0.10

**Comment by anchengjian** [comment]
观察下命令行界面是否有抛异常报错

**Comment by xuanmos** [comment]
@lizhoukai 你的问题解决了吗？

**Comment by lizhoukai** [comment]
@xuanmos  暂没，测试了下，发现使用slot的代码部分，终端也没报错，更改后需要终端重启才正常。其他地方更改热加载显示正常。

**Comment by soapper** [comment]
@anchengjian  我感觉有可能是vue有时候截获了错误，然后构建没有成功吧，但是vue的错误在terminal与开发者工具console都不能显示这是个问题

**Comment by anchengjian** [comment]
请升级相应的 `mpvue mpvue-template-compiler mpvue-loader` 后再试一下，我本地没复现

**Comment by shanlh** [comment]
还有一样的问题，组件template里有改动，也看到小程序刷新了，但并没有更新，如果随意保存一下其他js文件就可以更新。
追查到了mpvue-loader/lib/mp-compiler/index.js的createWxml函数。
调试输出wxmlContent是应该得到的内容，但是没有在输出的wxml里更新。
感觉好像是emitFile这出了点问题。
把components整个去掉就不会出现这个问题。

**Comment by nqdy666** [comment]
我遇到同样的问题，vue代码更新了，编译通过，微信小程序也刷新了，微信小程序界面上的代码还是旧的

**Comment by charmingzuo** [comment]
遇到同样的问题，也是不用 components 就解决了

**Comment by hlg-facai** [comment]
估计是slot导致的，我加了slot就会，slot好多问题啊，作者加油

**Comment by aOrz** [comment]
已经发版了，看看能不能解决 https://github.com/mpvue/mpvue-loader/releases

**Comment by hlg-facai** [comment]
还是一样，老是要重新run dev才会更新

**Comment by shanlh** [comment]
还是没有，版本号如下
"mpvue": "^1.0.10",
"mpvue-loader": "^1.0.13",
"mpvue-template-compiler": "^1.0.10"

**Comment by shanlh** [comment]
保存下其他的js应该也可以的吧，重新run dev得麻烦死 @hlg-facai

**Comment by linrui1994** [comment]
https://github.com/mpvue/mpvue-loader/pull/14  提了个pr，在本地能正常热更，但是不使用webpack提供的emitFile感觉也不是很好，看有没更好的解决办法。

**Comment by soapper** [comment]
ok test

2018-04-28 10:27 GMT+08:00 null <notifications@github.com>:

**Comment by liu-dongyu** [comment]
mpvue-loader@1.1.4依然有这个问题..

**Comment by cuiyajie** [comment]
使用VSCode时，通过debugger来启动node进程时可以触发热更新

**Comment by 1977474741** [comment]
有好的解决方案了吗？
