### ISSUE TITLE
a标签导航失败

### ISSUE THREAD

**Issue by chenyang-biu** [Meituan-Dianping/mpvue#246]
# [问题简单描述]
```html
  点击 <a href="/pages/counter/main" class="counter">去往Vuex示例页面</a>
```
 => 
```html
 点击 <a href="/pages/index/main" class="home">去往首页</a>
```

反复操作 第三次 去往VUEX示例页面 navigator无效

**问题复现步骤:**

1. [第一步]
  vue init mpvue/mpvue-quickstart test-mpvue
2. [第二步]
  yarn
  yarn add mpvue
  yarn add mpvue-template-compiler mpvue-loader mpvue-webpack-target postcss-mpvue-wxss webpack-dev-middleware-hard-disk -D
3. [其他步骤...]
  npm run dev
**期望的表现:**

[在这里描述期望的表现]

**观察到的表现:**

[在这里描述观察到的表现]
 
**屏幕截图和动态 GIF 图**

![复现步骤的屏幕截图和动态 GIF 图](图片的 url)

**Comment by aOrz** [comment]
看下你的页面栈是不是超过10个了，小程序不允许页面层级超过10个
