### ISSUE TITLE
await 写在wx函数内的success中被认为是保留字报错

### ISSUE THREAD

**Issue by eeeeeeeason** [Meituan-Dianping/mpvue#247]
#写在函数内部
![image](https://user-images.githubusercontent.com/27959851/38482643-c6ed443e-3c02-11e8-8b5a-4aada949a2eb.png)
#写在函数外部
![image](https://user-images.githubusercontent.com/27959851/38482704-fbedbb1e-3c02-11e8-98cd-de5cc17972d7.png)

**Comment by F-loat** [comment]
async success () {}

**Comment by eeeeeeeason** [comment]
爱你！秒回，
