### ISSUE TITLE
template里面什么时候支持methods

### ISSUE THREAD

**Issue by yanxiafu** [Meituan-Dianping/mpvue#249]
在v-for里面使用item作为参数使用方法return 反映不到template元素上，很难受，看到文档上说不支持，什么时候能支持呀

**Comment by anchengjian** [comment]
[双线程模型](https://developers.weixin.qq.com/ebook?action=get_post_info&token=935589521&volumn=1&lang=zh_CN&book=miniprogram&docid=0006a2289c8bb0bb0086ee8c056c0a) JS 逻辑层和 WXML 渲染层不在同一个线程内，从现在方案的技术底层来说，无法实现。
