### ISSUE TITLE
小程序map组件个别事件(regionchange)绑定有问题

### ISSUE THREAD

**Issue by que01** [Meituan-Dianping/mpvue#253]
# [bindregionchange无效]
bindregionchange对应的回调不会被执行

**问题复现步骤:**

```html
    <map class="map" id="myMap"
         :longitude="mapCenter.longitude"
         :latitude="mapCenter.latitude"
         :markers="markers"
         :polyline="polyline"
         :include-points="true"
         scale="14"
         show-location
         :controls="controlsCfg"
         @controltap="controltap"
         @markertap="markertap"
         @tap="maptap"
         @regionchange="regionchange"
        ></map>
```
目前来说这个组件转译过程我检查过没问题，也就是说html语法转换 wxml 没啥问题，但是controltap、markertap、tap都没问题，但是regionchange死活没反应的样子。

表现是远程调试会提示
```
Invoke event handleProxy in page: pages/index/index
```
但是对应的回调完全没反应(console.log没被执行)

PS: 个人 debug了一下，问题应该是handleProxyWithVue处理不够完善，regionchange的type是 begin&&end,它们应该类似 touch行为。。。。

😂我这边暂时是写了一个if-else暂时做了个兼容层自己解决了，还是希望有更好的方案发布一下npm，根据自己的兼容层代码，个人猜测给wxmlDirectiveMap.js里面v-on.map 加一个'end': 'regionchange' 可能是一个自带bug buffer的解决办法。。。

**Comment by auven** [comment]
@que01 请问你是怎么解决这个问题的，我也遇到了这个问题

**Comment by F-loat** [comment]
文档有写这个问题 http://mpvue.com/mpvue/#_13

**Comment by anchengjian** [comment]
http://mpvue.com/mpvue/#_13 把文档贴过来：
> 
> 踩坑注意：
> 
> 列表中没有的原生事件也可以使用例如 bindregionchange 事件直接在 dom 上将bind改为@ @regionchange,同时这个事件也非常特殊，它的 event type 有 start 和 end 两个，导致我们无法在handleProxy 中区分到底是什么事件，所以你在监听此类事件的时候同时监听事件名和事件类型既 <map @regionchange="functionName" @end="functionName" @start="functionName"><map>

**Comment by aOrz** [comment]
事件无限联动是不是修改了 touchStartTimeStamp 导致地图触发了 regionchange ?

**Comment by vinceok** [comment]
我碰到的问题估计个题主一样，我在end里获取中心点的经纬度，地图移动时中心点又移回去了，很糟心

**Comment by vinceok** [comment]
![image](https://user-images.githubusercontent.com/13531512/39176604-cda608f4-47df-11e8-8e9e-11f250762ddd.png)
![image](https://user-images.githubusercontent.com/13531512/39176661-e983b60c-47df-11e8-8943-670bc8c9dab0.png)
把getCenterLocaltion放在regionChange里地图不会移回起点，但是放end里地图会自动移回起点

**Comment by anchengjian** [comment]
能不能给个 demo 仓库，这么贴图片，调试复现都比较难操作。

**Comment by vinceok** [comment]
大哥，这个demo真不好给，其实跟题主说的一样，但凡在begin,end里操作了data里的数据，就会有问题。所以我现在避免了这样操作。

**Comment by gengjiawen** [comment]
我这边begin end正常工作。

**Comment by gengjiawen** [comment]
@vinceok 你把这句话`let mapCtx = wx.createMapContext('map')`放到onReady里面就好了。

**Comment by vinceok** [comment]
@gengjiawen 这句和我的问题似乎没关系，地图上下文在拖动时已经早就生成了。我在getCenterLocation方法里有这行代码，另外：我新开了个issues,#401

**Comment by gengjiawen** [comment]
我之前跟你一样，放到这个里面中心点来回跑，你放到这里面相当于每次重新生成一个新的地图上下文。

**Comment by vinceok** [comment]
@gengjiawen 我刚试了下并没有用啊

**Comment by gengjiawen** [comment]
你给的demo缺少了图片,  图片去掉地图显示不出来 ..., 最好能给个repo啥的

**Comment by gengjiawen** [comment]
知道怎么解决问题了 ,但是不知道原因...
```js
  data () {
    return {
      mapCtx: null,
      // 搜索关键词
      keyword: '',
      // 当前位置经纬度
      current: {
        latitude: '39.909604',
        longitude: '116.397228'
      },
      longitude: 0,
      latitude: 0,
      // 充电站列表
      markers: []
    }
```

**Comment by gengjiawen** [comment]
@anchengjian @vinceok repo: https://github.com/gengjiawen/vue-demo/tree/master/mpvue-map.

**Comment by vinceok** [comment]
确实，latitude不能包含在obj里面，这问题真实困扰我好几天，按你的demo可以实现我的效果，多谢@gengjiawen

**Comment by katherinesnow** [comment]
我也遇到regionchange 的begin 和end 里面不能更新data 的问题，一旦更新data，地图就会闪跳回去原来位置（就相当于重新渲染了地图），可是现在确实是需要 在移动地图后 根据data 动态绑定图标对应的详细地址，其他人有没有解决办法呢？ 
效果类似于滴滴打车小程序， 拖动地图后下面的定位地址也会随时发生变化。

**Comment by katherinesnow** [comment]
后来想通过map 的@touchend="handletouchend" 执行操作，但是该处理只能在模拟器上生效，实机还是有如上问题. 

>  /**
         * [handletouchend 地图移动触摸结束]
         * @return {[type]} [description]
         */
        handletouchend(e) {
            console.log(e)
            console.log(this.mapCtx, 'this.mapCtx===================')
            this.mapCtx.getCenterLocation({
                success: (res) => {
                    const latitude = res.latitude
                    const longitude = res.longitude
                    console.log(latitude, longitude)
                    MapUtil.getUserLocationInfo({ latitude, longitude })
                    .then((addrInfo) => {
                        this.latitude = res.latitude
                        this.longitude = res.longitude
                        console.log(addrInfo)
                        this.currentPoiAddr = addrInfo.pois[0]
                        const isArea = MapUtil.getIsArea(this.currentPoiAddr.ad_info.adcode);
                        console.log(isArea)
                        this.currentPoiAddr.isArea = isArea
                        this.currentPoiAddr.adcode = this.currentPoiAddr.ad_info.adcode
                        this.currentPoiAddr.province = this.currentPoiAddr.ad_info.province
                        this.currentPoiAddr.city = this.currentPoiAddr.ad_info.city
                        this.currentPoiAddr.district = this.currentPoiAddr.ad_info.district
                    }).catch((err) => {
                        console.log(err, 'err===========')
                    })
                },
                fail(err) {
                    console.log(err, '============err')
                },
                complete(com) {
                    console.log(com, '=========complete')
                },
            });
        },

**Comment by katherinesnow** [comment]
但是用原生实现没有问题，后来想用原生下程序调用组件实现，可是小程序本身自定义组件中对 map 的regionchange 调用后无法通过this.data.mapCtx.getCenterLocation 获取到经纬度，但是原生的Page 页面中没有问题。小程序本身的自定义组件对map 的支持好像也有点问题，不知道大家有没有遇到过.

**Comment by gengjiawen** [comment]
getCenterLocation一些异步操作跟 vuex 一起用在真机上遇到了地图位置不断更改的问题, 最后在页面换掉vuex为eventbus才好的, 模拟器上没问题。

**Comment by gengjiawen** [comment]
@anchengjian @F-loat  longitude和latitude这两个变量封装成一个 object 地图漂移的问题能不能看下, 感觉这类问题相关性很强。

**Comment by hiboyluo** [comment]
@gengjiawen '一些异步操作更改 vuex store 在真机上遇到了地图位置不断更改的问题, 最后在页面换掉vuex为eventbus才好的, 模拟器上没问题'。请问这个问题如何解决？怎么换成eventbus?

**Comment by gengjiawen** [comment]
@hiboyluo 就是Vue自带的Eventbus，你去搜下就知道了。

**Comment by xwwww** [comment]
我的 regionChange 并没有被触发，不明白。。。

**Comment by lianruhe** [comment]
@gengjiawen @xwwww @vinceok 我的也是begin和end可以触发，但是regionchange不能触发，你们也是这样的情况吗？

**Comment by gengjiawen** [comment]
试下我的那个方案，应该就可以了
