### ISSUE TITLE
我想知道button获取手机授权回调怎么监听?

### ISSUE THREAD

**Issue by Mixlong** [Meituan-Dianping/mpvue#255]
# [问题简单描述]

**问题复现步骤:**

1. [第一步]
2. [第二步]
3. [其他步骤...]

**期望的表现:**

[在这里描述期望的表现]

**观察到的表现:**

[在这里描述
![tim 20180409175533](https://user-images.githubusercontent.com/27038897/38491709-44841abe-3c1f-11e8-8869-b32630013bda.png)
观察到的表现]

**屏幕截图和动态 GIF 图**

![复现步骤的屏幕截图和动态 GIF 图](图片的 url)

**Comment by F-loat** [comment]
@getphonenumber=“” 这样吧
