### ISSUE TITLE
求教：background-image支持吗

### ISSUE THREAD

**Issue by blingbling-bin** [Meituan-Dianping/mpvue#256]
background: url("../../../static/images/group.png");
和 background-image: url("../../../static/images/group.png");
都没有显示背景图

**Comment by Mixlong** [comment]
你路径有问题吧

**Comment by F-loat** [comment]
背景图建议使用线上的吧，小图的话应该用 “~@/assets/xxx” 这样调用，会转为 base64 格式的，目前支没支持我就不太清楚了。。

**Comment by tangsj** [comment]
图片不建议放到小程序包体里面 占用体积，放到线上环境后在background 里面用 图片路径比较好
