### ISSUE TITLE
mpvue的组件可以调用wx.createSelectorQuery().in()方法吗？

### ISSUE THREAD

**Issue by zuoxue0119** [Meituan-Dianping/mpvue#257]
在组件中
```javascript
 mounted() {
    let query = wx.createSelectorQuery(); //如何在这里调用 wx.createSelectorQuery().in(component)？
    query.select('.flex-text').boundingClientRect();
    query.select('.flex-text-content').boundingClientRect();
    query.exec((res) => {
      if (res && res[0] && res[1]) {
        let clientHeight = res[0].height || 0;
        let scrollHeight = res[1].height || 0;
        if (scrollHeight > clientHeight) {
          this.isMore = true;
        }
      }
    });
  }
```

**Comment by anchengjian** [comment]
mpvue不会禁止这些 API 的使用，报什么错？或者提供个demo吧

**Comment by zuoxue0119** [comment]
mpvue在component中是可以调用 wx.createSelectorQuery().in的方法，主要想问下wx.createSelectorQuery().in(componentA)的参数componentA如何获取？
如果使用原生的微信小程序在组件中调用wx.createSelectorQuery().in(this)即可，但是在mpvue组件this的属性中没有找到指向原生组件的变量

**Comment by anchengjian** [comment]
this.$mp.page 会指向原小程序 page

**Comment by zuoxue0119** [comment]
在组件中调用是需要指向原小程序component的变量，而不是指向原小程序page的
```javascript
//在component中这样调用，是无法起到createSelectorQuery.in当前组件的效果的
let query = wx.createSelectorQuery().in(this.$root.$mp.page)
```

**Comment by anchengjian** [comment]
mpvue 底层不是用自定义组件实现的，所以可能不会有指向 component 只会指向 page

**Comment by zuoxue0119** [comment]
如果需要mpvue的组件中wx.createSelectorQuery().in()有什么替代的解决办法？

**Comment by kala888** [comment]
@zuoxue0119 看起来我也要到相同问题了，怎么解决的？

**Comment by zhangsamhong** [comment]
尝试了在mounted中去调用wx.createSelectorQuery().in(this.$root.$mp.page)，发现还是返回[null]，后来查阅了vue的文档发现mounted回调的时候并不保证所有组件都被挂载，尝试添加this.$nextTick()
![image](https://user-images.githubusercontent.com/10106836/50549147-7a697180-0c92-11e9-9dba-5fefb35961b3.png)
查找的代码变为:
this.$nextTick(() => {
  wx.createSelectorQuery().in(this.$root.$mp.page)
  .........
})
结果还是返回[null]
觉得还是因为组件挂载未完成导致的问题，试了一下添加了一个setTimeout
最终变成
this.$nextTick(() => {
  setTimeout(() => {
    wx.createSelectorQuery().in(this.$root.$mp.page)
    .........
  }, 50)
})
结果就可以获取到boundingClientRect的数据了，这个怎么解决？
@anchengjian

**Comment by cleverboy32** [comment]
@zuoxue0119 请问你现在是怎么解决的？

**Comment by fu1252** [comment]
我也是，怎么解决？加了 in(this.$root.$mp.page)和没加一样

**Comment by fu1252** [comment]
找到解决方法了,测试有效，我的需求是折叠面板组件在多次调用后自动根据传入的内容计算包裹元素的高度
用query.selectAll（.elem）找出这个元素在组件多次渲染后的数组，再把这数组存到父组件的data里，用push方法，再把data用prop传进来，读取其中第一个数组的位置信息，最后shift()删除这个prop的第一个数组。

**Comment by fu1252** [comment]
找到解决方法了，可以根据传入的数据做动态id并选择查找这动态id的元素

**Comment by cleverboy32** [comment]
> 找到解决方法了，可以根据传入的数据做动态id并选择查找这动态id的元素

我试过啊， 这样查怎么都是返回 null. = =

**Comment by fu1252** [comment]
这是异步调用的问题，我一开始也这样，用promise接收结果就好了
我写的折叠面板组件，根据传入的内容自动计算包裹元素的高度,点击下拉按钮执行change，把高度存到data里。
change() {
  this.getRect().then(res => {
    this.elemHeight=res
  })
},
getRect() {
  let that=this
  return new Promise((resolve, reject) => {         
    let query = wx.createSelectorQuery()
    let elemId='#'+this.propObj.id
    query.select(elemId).boundingClientRect();
    query.exec(function (res) {                               
      console.log(res);      
      let value=res[0].height+'px'
      resolve(value)
    })
  });
}

**Comment by cleverboy32** [comment]
@fu1252  不行， 我看 wxml id 都显示了，但是我怎么获取元素就是查不到。
wxml 显示
![image](https://user-images.githubusercontent.com/17595456/57267712-a3bc6300-70b3-11e9-949e-49a1d993427d.png)

js 代码
![image](https://user-images.githubusercontent.com/17595456/57267662-7b346900-70b3-11e9-9f08-0a9eb05d0c38.png)
![image](https://user-images.githubusercontent.com/17595456/57267667-7ff91d00-70b3-11e9-81d8-0203177c8e4c.png)
![image](https://user-images.githubusercontent.com/17595456/57267676-88515800-70b3-11e9-84d0-a9460f9200e3.png)
![image](https://user-images.githubusercontent.com/17595456/57267685-91422980-70b3-11e9-868b-b935c4e257b5.png)

**Comment by fu1252** [comment]
@cleverboy32  
1.可能你那个Math.random（）div获取和getRect函数调用时返回值不同，.in(this.$root.$mp.page)没作用就去掉，这个动态id最好是来自后台固定，渲染组件时数据不一样这id值也不一样
2.如果不设置动态的id。我之前还摸索了另一个解决方法，你这里可能很合适，原代码不变，直接查询class，query.selectAll('.content')，把返回的数组先存到data再存到父组件data里， this.getRect().then(res => {this.elem = res[0];  this.$emit("onElemArr",this.elem);}）。父组件存数据是用push：onELemArr(param){   this.elemArr.push(param)},   接着子组件props接收这个elemArr，。在上面this.getRect()函数后面读取第一个数组值，然后删去这个数组，这样保证每一次渲染都获取最新的值
![搜狗截图20190507141111](https://user-images.githubusercontent.com/41353385/57275874-5ac7d700-70d2-11e9-9725-85cac195da00.png)
![搜狗截图20190507141234](https://user-images.githubusercontent.com/41353385/57275875-5b606d80-70d2-11e9-9f46-cdf1532b68d2.png)
![搜狗截图20190507141311](https://user-images.githubusercontent.com/41353385/57275877-5b606d80-70d2-11e9-83a8-439917b71e26.png)


.then(res=>{  this.value=this.propElemArr[0][0].height+"px";this.propElemArr[0].shift();console.log(this.propElemArr[0]);
