### ISSUE TITLE
分包及h5运行问题

### ISSUE THREAD

**Issue by cmideal** [Meituan-Dianping/mpvue#26]
### What problem does this feature solve?
小程序现在支持分包,请问我要怎么在这个里面使用分包

### What does the proposed API look like?
subpackages

**Comment by F-loat** [comment]
应该还不支持，期待对入口文件的处理再做优化吧，目前不太灵活

**Comment by aOrz** [comment]
生成页面路径已经支持配置 http://mpvue.com/build/mpvue-loader/#_2，能否满足需求？

**Comment by lil-Jay** [comment]
什么时候支持分包，我的项目都要超过2M了

**Comment by cmideal** [comment]
这个打包之后，不能分包，只是壳分开了，但是你引入的components和static 都在一起，那不还是打包在主包上了吗？这样也没有解决2M的操作

**Comment by freedomcly** [comment]
分包加载是通过app.json里的subPackages来判断，但现在只能自定义配置app.json中的pages。https://developers.weixin.qq.com/miniprogram/dev/framework/subpackages.html
所以现在还不支持分包？

**Comment by aOrz** [comment]
参考 #672
