### ISSUE TITLE
input  的 focus  属性设为 true，并不会使input聚焦

### ISSUE THREAD

**Issue by cottengc** [Meituan-Dianping/mpvue#260]
# [问题简单描述]

**问题复现步骤:**
```
<div class="code-fill" @click="focusInput(index)"></div>
<input type="number" :focus="setFocus" :maxlength="4" v-model="code">
data() {
      return {
        phone: '151 6065 8413',
        code: '',
        setFocus: false
      }
    },
methods: {
      focusInput(index) {
        this.setFocus = true;
      }
    }
```
1. [第一步]
点击div.code-fill 我想让下面那个input聚焦
2. [第二步]
然而setFocus设置成了true，input聚焦不了
3. [其他步骤...]

**期望的表现:**
input的focus属性可以让input聚焦
[在这里描述期望的表现]

**观察到的表现:**

[在这里描述观察到的表现]

**屏幕截图和动态 GIF 图**

![复现步骤的屏幕截图和动态 GIF 图](图片的 url)

**Comment by aOrz** [comment]
我试了下，没有复现，你是不是在在开发者工具里面尝试的？需要再真机里面才有效果

**Comment by cottengc** [comment]
第一次是可以聚焦的，但是你点击其他空白的地方让input失焦后，再点击div.code-fill 想让input聚焦就不可以了

**Comment by aOrz** [comment]
要想再次聚焦，需要将 focus 先置为 false，然后再设置为 true

**Comment by linweiwei123** [comment]
@cottengc 我一样的代码，进入一开始 是focus = "false" 也会调起键盘呢，你有遇到这样的问题吗
