### ISSUE TITLE
页面通过wx.navigateTo跳转时url中的参数无法传递的问题

### ISSUE THREAD

**Issue by milixie** [Meituan-Dianping/mpvue#261]
# [页面通过wx.navigateTo跳转时url中的参数无法传递的问题]

在页面A中，点击某个按钮链接到页面B
```
wx.navigateTo({
  url: `../detail/detail?id=${e.currentTarget.id}`
})
```

在页面B中

```
onLoad (options) {
      console.log(options)
    },
```
发现打印出来的 `options` 是 `undefined`

小程序原生的是可以传递url参数的

不知道是我写的有问题  还是框架的问题？

**Comment by chwech** [comment]
传参可以在this.$root.$mp.query获取到

**Comment by zhangjgymy** [comment]
wx.navigateTo({
  url: `../detail/main?id=${e.currentTarget.id}`
})


路劲应该是这样的吧
