### ISSUE TITLE
slot编译后在小程序中出现 template not found

### ISSUE THREAD

**Issue by 704826318** [Meituan-Dianping/mpvue#262]
# [问题简单描述]

插入自定义组件就报错

**屏幕截图和动态 GIF 图**
![before](https://thumbnail10.baidupcs.com/thumbnail/b5a466767a0ab360edcf174a1194a805?fid=1797407193-250528-271399934591626&rt=pr&sign=FDTAER-DCb740ccc5511e5e8fedcff06b081203-v9Hg%2fkN%2fP7Eyl3XkQwn%2feNfcRzs%3d&expires=8h&chkbd=0&chkv=0&dp-logid=2328768899108118169&dp-callid=0&time=1523408400&size=c10000_u10000&quality=90&vuk=1797407193&ft=image)

![after](https://thumbnail10.baidupcs.com/thumbnail/f89d02d9c83a68add59cde7c7cbf415a?fid=1797407193-250528-193808823861203&rt=pr&sign=FDTAER-DCb740ccc5511e5e8fedcff06b081203-OsYWh0nOqHuYPQFtmMatOfJkXFM%3d&expires=8h&chkbd=0&chkv=0&dp-logid=2328768899108118169&dp-callid=0&time=1523408400&size=c10000_u10000&quality=90&vuk=1797407193&ft=image)

插入文字完全没问题

![复现步骤的屏幕截图和动态 GIF 图](图片的 url)

**Comment by guider** [comment]
我也出现了这个问题

**Comment by anchengjian** [comment]
[1.0.8](https://github.com/Meituan-Dianping/mpvue/releases/tag/1.0.8) 已修复，请升级相应的 `mpvue mpvue-template-compiler mpvue-loader` 后使用

**Comment by guider** [comment]
@anchengjian 
  升级了1.0.8 这个问题仍会出现 求解

**Comment by anchengjian** [comment]
给个demo或者示例代码看看

**Comment by guider** [comment]
@anchengjian 
 https://github.com/guider/mpvue-slot-demo 这里是demo 时而好用时而无效

**Comment by szoyaung** [comment]
换成1.0.8虽然可以在slot里放组件了，但是我组件里写的动作不能用了（touchstart事件），
报了警告：Do not have handler in current page: pages/more/main. Please make sure that handler has been defined in pages/more/main, or pages/more/main has been added into app.json。
当我把我的组件不放在slot里的时候，就没有这个问题了。

**Comment by 704826318** [comment]
ok问题解决了，
命令：
`npm update mpvue-template-compiler mpvue-loader mpvue`

**Comment by LeftShoot** [comment]
@guider 发现一个办法。你把组件在的目录拷贝一份放在同级目录。比如component文件夹，就建一个component2。然后在引用页面修改目录指向为compnonet2, 页面自动编译就不会报错了。然后再指向回component。

**Comment by mdsb100** [comment]
npm run build 就是好的。 run dev就不行

**Comment by mdsb100** [comment]
npm update mpvue-template-compiler mpvue-loader mpvue 不起作用

**Comment by 704826318** [comment]
@mdsb100 那可能你的组件已经是最新的了

**Comment by mdsb100** [comment]
随机的 npm run build 有时好 有时不好

**Comment by dwqs** [comment]
@LeftShoot 我用你的方法还是不行
