### ISSUE TITLE
求助，使用v-for列表渲染，更新数据时错乱？

### ISSUE THREAD

**Issue by chwech** [Meituan-Dianping/mpvue#263]
# [问题简单描述]
使用v-for渲染列表，数据更新时，渲染出错。
**问题复现步骤:**
如下gif图
1. [第一步]
分别点击分类1，2。然后此时列表正确渲染。
2. [第二步]
点击分类2第一个商品的加号，添加一个商品。控制台打印的数据里count的值为1。这时是正确的。
3. [第三步]
点击分类1，渲染出来的第一个商品出错。控制台打印的数据并没有count，却渲染出上一步的1？
**期望的表现:**

期望第三步能正确渲染啊。不知我描述清楚没有？求助

**屏幕截图和动态 GIF 图**

![复现步骤的屏幕截图和动态 GIF 图](http://139.199.17.176/1.gif)

**Comment by aOrz** [comment]
给个小demo吧，看起来像是for 的时候没有设置或者设置了重复的 index 导致的

**Comment by chwech** [comment]
把渲染列表的key去掉就不会渲染错乱。
