### ISSUE TITLE
求助，有没有更好的validate组件

### ISSUE THREAD

**Issue by mazusheng** [Meituan-Dianping/mpvue#264]
# 表单验证场景较多，有没有通用简洁的表单验证组件

**Comment by shiweiqi19930328** [comment]
/*
纯javascript基于数据的表单验证
    @params {object} form表单数据
    @params {object} rules对应表单数据的验证规则
    		内置有telphone,email,identity验证，还有快速非空验证（空数组和空对象也认为是false），同时支持正则pattern和自定义验证方法validator
*/

const validate = function (form,rules){
	try{
		// 遍历所有需要验证的元素
		for(var i in rules){
			// 遍历验证规则
			if(rules[i] && rules[i] instanceof Array){
				rules[i].forEach(function(item){
					// 校验，有错误会外部被catch
					check(form[i],item)
				})
			}
		}
	}catch(err){
		return {
			valid : false,
			message : err
		}
	}
	//没有被catch到错误，就验证通过
	return {
		valid : true,
		message : '验证通过'
	}
	
	

	function check(value,rule){
		// 非空验证
		if(rule.required){
			// 0是false，需要规避掉
			if(!value && typeof(value) != 'number'){
				throw rule.message;
			}
			// 空数组和空对象也被认为是空
			if(typeof(value) == 'object' && Object.values(value).length == 0){
				throw rule.message;
			}
			
		}
		// 正则验证
		if(rule.pattern && !rule.pattern.test(value)){
			throw rule.message;
		}
		//自定义方法验证
		if(rule.validator){
			try{
				rule.validator(value)
			}catch(err){
				throw err;
			}
		}
		// 内置常见的验证
		if(rule.type){
			switch(rule.type){
				case 'telphone' : 
					if(!/^1[3456789]\d{9}$/.test(value)){
						throw rule.message;
					};
					break;
				case 'email' : 
					if(!/^[a-z0-9]+([._\\-]*[a-z0-9])*@([a-z0-9]+[-a-z0-9]*[a-z0-9]+.){1,63}[a-z0-9]+$/.test(value)){
						throw rule.message;
					};
					break;
				case 'identity' : 
					if(!checkIdentity(value)){
						throw rule.message;
					};
					break;
			}
		}
	}

	//验证身份证
	function checkIdentity (code) {    
        var city={11:"北京",12:"天津",13:"河北",14:"山西",15:"内蒙古",21:"辽宁",22:"吉林",23:"黑龙江 ",31:"上海",32:"江苏",33:"浙江",34:"安徽",35:"福建",36:"江西",37:"山东",41:"河南",42:"湖北 ",43:"湖南",44:"广东",45:"广西",46:"海南",50:"重庆",51:"四川",52:"贵州",53:"云南",54:"西藏 ",61:"陕西",62:"甘肃",63:"青海",64:"宁夏",65:"新疆",71:"台湾",81:"香港",82:"澳门",91:"国外 "};
        var tip = "";
        var pass= true;

        if(!code || !/(^\d{15}$)|(^\d{18}$)|(^\d{17}(\d|X|x)$)/.test(code)){
            tip = "身份证号格式错误";
            pass = false;
        }

        else if(!city[code.substr(0,2)]){
            tip = "地址编码错误";
            pass = false;
        }
        else{
            //18位身份证需要验证最后一位校验位
            if(code.length == 18){
                code = code.split('');
                //∑(ai×Wi)(mod 11)
                //加权因子
                var factor = [ 7, 9, 10, 5, 8, 4, 2, 1, 6, 3, 7, 9, 10, 5, 8, 4, 2 ];
                //校验位
                var parity = [ 1, 0, 'X', 9, 8, 7, 6, 5, 4, 3, 2 ];
                var sum = 0;
                var ai = 0;
                var wi = 0;
                for (var i = 0; i < 17; i++)
                {
                    ai = code[i];
                    wi = factor[i];
                    sum += ai * wi;
                }
                var last = parity[sum % 11];
                if(parity[sum % 11] != code[17]){
                    tip = "校验位错误";
                    pass =false;
                }
            }
        }
        return pass;
    }
}

**Comment by shiweiqi19930328** [comment]
自己手写一个喽

**Comment by aOrz** [comment]
非 mpvue 问题先关了，可以私下讨论
