### ISSUE TITLE
onLaunch 内代码不被执行

### ISSUE THREAD

**Issue by soapper** [Meituan-Dianping/mpvue#265]
# [问题简单描述]

**问题复现步骤:**

1.onLaunch 内代码不被执行

**期望的表现:**
应用进入时获取地理位置
目前是写在onLoad中

**Comment by 704826318** [comment]
onLoad和onShow我感觉就够用了

**Comment by yuconora** [comment]
https://developers.weixin.qq.com/miniprogram/dev/framework/app-service/app.html

**Comment by aOrz** [comment]
onLaunch 是可以正常触发的，给个可以复现的 demo ？

**Comment by soapper** [comment]
可以触发，在main.js app的就行，Please close

null <notifications@github.com>于2018年4月15日 周日16:35写道：
