### ISSUE TITLE
貌似在template中支持使用methods中的函数了

### ISSUE THREAD

**Issue by tim0991** [Meituan-Dianping/mpvue#266]
**屏幕截图和动态 GIF 图**
文档中的内容
![image](https://user-images.githubusercontent.com/26053904/38607761-1e13e484-3dac-11e8-8a44-daca81fefeeb.png)
实际的代码
![image](https://user-images.githubusercontent.com/26053904/38607786-2f57bfcc-3dac-11e8-9865-5a4597911914.png)

![image](https://user-images.githubusercontent.com/26053904/38607898-745571a0-3dac-11e8-97ea-c94fce0791ae.png)

如果如代码所示则希望可以修改文档

**Comment by aOrz** [comment]
不支持 <div>{{method()}}</div> 这种调用。
