### ISSUE TITLE
wx.getCurrentPages 是undefined

### ISSUE THREAD

**Issue by lrnman** [Meituan-Dianping/mpvue#273]
# [问题简单描述]

**问题复现步骤:**

1. [第一步]
2. [第二步]
3. [其他步骤...]

**期望的表现:**

[在这里描述期望的表现]

**观察到的表现:**

[在这里描述观察到的表现]

**屏幕截图和动态 GIF 图**

![复现步骤的屏幕截图和动态 GIF 图](图片的 url)

**Comment by yuconora** [comment]
getCurrentPages()直接调用的吧 没有wx.
