### ISSUE TITLE
mpvue的二维码生成问题

### ISSUE THREAD

**Issue by sydical** [Meituan-Dianping/mpvue#274]
# [问题简单描述]
分别使用以下三个包出现不同程度的问题
**问题复现步骤:**
import Qrcode from 'vue-qrcode'
import QRCode from 'qrcodejs2'
编译运行出错，提示第三方错误

import drawQrcode from 'weapp-qrcode'
显示空白，drawQrcode需要指定一个可能是canvas，可能是canvas原因。

请问有遇到这样的问题吗？

**Comment by aOrz** [comment]
qrcodejs2 和 vue-qrcode 应该是用到了 web 上的 canvas，不可以直接用。
试了下 weapp-qrcode，可以用

**Comment by yingye** [comment]
推荐使用 [weapp-qrcode](https://github.com/yingye/weapp-qrcode)
