### ISSUE TITLE
关于mpvue组件通信的支持

### ISSUE THREAD

**Issue by xuqiang521** [Meituan-Dianping/mpvue#275]
# 目前mpvue对组件通信是不支持的

**子组件通过$emit传递出自定义的一些事件，在父组件调用是无效的**

1. 子组件定义一个自定义的事件
2. 父组件进行事件引用
3. 父组件中对应的事件操作无效

**期望的表现:**

父子组件能够正常进行通信（包括状态和事件）

**观察到的表现:**

父子组件不能够进行通信

**屏幕截图和动态 GIF 图**

![image](https://user-images.githubusercontent.com/15885749/38693458-7e68c4f4-3eb9-11e8-8a6c-885821ff7a7b.png)
![image](https://user-images.githubusercontent.com/15885749/38693468-87ccbda2-3eb9-11e8-9117-dd6d4697fc50.png)
父组件中的@route事件，即handleRouter，并不会在相应的操作后被触发

**Comment by pcloth** [comment]
我试了一个可以用emit传递到父组件呢。

**Comment by anchengjian** [comment]
估计是 https://github.com/F-loat/mpvue-router-patch 相关的问题

**Comment by xuqiang521** [comment]
刚试了一下，又 OK 了。估计是因为微信开发工具的问题，也不是 [https://github.com/F-loat/mpvue-router-patch](https://github.com/F-loat/mpvue-router-patch)  导致的问题，不好意思了。这个 issue 先关了吧

**Comment by pcloth** [comment]
@anchengjian 我又试了一下，如果是页面里装了一个A组件，A组件又包含一个B组件,那B组件的emit出来的事件，A组件无法捕获。
也就是说三层关系，emit就失效了。

**Comment by ZQ7** [comment]
@xuqiang521 怎么解决的啊，掉坑里了，总提示这个： Do not have handler in current page，求助
