### ISSUE TITLE
unhandled promise rejection 没有任何提示

### ISSUE THREAD

**Issue by yedf** [Meituan-Dianping/mpvue#280]
# unhandled promise rejection 没有任何提示

**问题复现步骤:**

1. 脚手架生成一个代码
2. 在index.vue里面的
created () {
    (async () => {
      let a = {}
      a.b.c = 0
    })()
  },

**期望的表现:**

期望在控制台里面报告created中不能够赋值给undefined

**观察到的表现:**

没有任何提示

**Comment by githubyhy** [comment]
我也是一样的问题， 我这边Promise 中的方法报错，控制台不显示错误信息，没有任何提示

**Comment by anchengjian** [comment]
这个是 promise 本身 error 提示的问题，与 mpvue 本身关系不大。
可以用 promise.catch 去捕获，或者你这里用 try catch 捕获。或者：

```
window.onunhandledrejection = function (reason, p) {
  console.log('Unhandled Rejection at: Promise', p, 'reason:', reason)
  console.log(reason.stack)
}
```

**Comment by liusome** [comment]
小程序没有window对象，Promise对象的报错不会冒泡到全局，请看一下这个问题。

**Comment by anchengjian** [comment]
那就自己在 promise 的时候用 catch 去捕获吧

**Comment by liusome** [comment]
你的意思是只要用到promise的地方就单独用catch去捕获吗？

**Comment by yedf** [comment]
我尝试了多种方式，都没有一个地方能够全局捕获这类错误。
而普通的vue项目，node项目，wepy项目都能够默认情况下console.error出这个错误，并且提供了相关的全局处理器，例如window.onunhandledrejection process.on('unhandledRejection', cb) Promise._unhandledRejectionFn  
如果没有这个全局钩子，那么对于我定义的所有async function，全部都要加try catch，代码一下子要增多好多，能不能够从webpack层面，查一查这个全局处理钩子是如何弄丢了呢？
这个特性对于我这样的开发者，实在是太重要，上手mpvue的时候，由于这种静默的错误处理，导致多花了许多时间去找特别简单的错误 
麻烦看看这个issue能否重回open的状态 @anchengjian

**Comment by geminate** [comment]
另一个issues提到了解决方法。
#700
