### ISSUE TITLE
capture-catch怎么绑定

### ISSUE THREAD

**Issue by AHwwh** [Meituan-Dianping/mpvue#283]
capture-catch事件怎么绑定？小程序1.5.0以上是支持捕获的

**Comment by bigmeow** [comment]
![image](https://user-images.githubusercontent.com/10484248/38767713-5c4a39f0-4019-11e8-8f00-2b09bddefb6f.png)



mpvue现在还不支持，好在原生的写法是可以的，比如这个可以实现阻止用户移动屏幕

@anchengjian 现在小程序支持捕获了 
![image](https://user-images.githubusercontent.com/10484248/38767746-d95c6b66-4019-11e8-84f0-53c1672bd831.png)

**Comment by aOrz** [comment]
下个版本会加上

**Comment by ZhuRuiHeng** [comment]
@capture-catch="delitem"

**Comment by zjdgx** [comment]
> @capture-catch="delitem"

不起作用啊

**Comment by cdll** [comment]
> > @capture-catch="delitem"
> 
> 不起作用啊

not working +1

**Comment by zjdgx** [comment]
阻止事件用的是事件修饰符: {event}.stop, 如touchmove.stop="function xxx"

[事件修饰符](http://mpvue.com/mpvue/#_13)

**Comment by ZhuRuiHeng** [comment]
@click.stop="backHome"
backHome(){
     wx.switchTab({
         url:'/pages/index/main'
      })
}
