### ISSUE TITLE
slot插槽内的自定义组件数据无法渲染

### ISSUE THREAD

**Issue by 704826318** [Meituan-Dianping/mpvue#284]
# [问题简单描述]
// 父组件
```html
<template lang='pug'>
  .main
    action-sheet
      x-cart(
        :title = 'title'
      )
</template>
```

// 子组件 x-cart
``` html
<template lang='pug'>
  .cart
    .header
      .right
        .title {{title}}
</template>

<script>
export default {
  name: 'product-cart',
  data () {
    return {
    }
  },
  props: {
    title: {
      type: String,
      default: ''
    }
  },
  async mounted () {
    console.log(this.title) // 可以输出title “张三”
  }
}

```

```js
版本信息
{
    "mpvue": "^1.0.8",
    "mpvue-loader": "^1.0.11",
    "mpvue-template-compiler": "^1.0.8"
}
```
**屏幕截图和动态 GIF 图**
![imgggg](https://thumbnail10.baidupcs.com/thumbnail/d708a022a93ac69ca313543906d6f01f?fid=1797407193-250528-898464527078641&rt=pr&sign=FDTAER-DCb740ccc5511e5e8fedcff06b081203-KoLYLsCEGzh7j6J2PmVYdBi3LcM%3d&expires=8h&chkbd=0&chkv=0&dp-logid=2594236570590455715&dp-callid=0&time=1524398400&size=c10000_u10000&quality=90&vuk=1797407193&ft=image)
![复现步骤的屏幕截图和动态 GIF 图](图片的 url)

**Comment by 704826318** [comment]
demo代码我调整过跟截图有部分小差异

**Comment by chenjinxinlove** [comment]
我也遇到那个问题了

**Comment by a573367014** [comment]
me to ...

**Comment by lavyun** [comment]
up up up

**Comment by monsuns** [comment]
同在slot使用中遇到一些莫名其妙的问题,头疼

**Comment by LeftShoot** [comment]
发现slot内的自定义组件，里面绑定点击事件会失效。

**Comment by mdsb100** [comment]
#365

**Comment by Stupidism** [comment]
这个应该是props 和 data 的问题 #427
