### ISSUE TITLE
touch系列事件，e.touches是未定义

### ISSUE THREAD

**Issue by chenjinxinlove** [Meituan-Dianping/mpvue#286]
# [问题简单描述]
touch系列事件，e.touches是未定义
**问题复现步骤:**

1. [第一步]
```
<div 
        @touchstart.prevent="handlerStart"
        @touchmove.prevent="handlerMove"
        @touchend="handlerEnd"
    >
<script>
 methods: {
    handlerStart (e) {
      this.initiated = true
      console.log(e.touches)//是未定义
      const touch = e.touches ? e.touches[0] : e['mp'].touches[0]
    },
    handlerMove (e) {
    },
    handlerEnd (e) {
    }
  }</script>
```

**期望的表现:**
e.touches  和原生和微信小程序都是可以直接取到
[在这里描述期望的表现]

**观察到的表现:**
打印e 是在对象外面多了一个mp的key，我现在使用下面的代码兼容处理。
 const touch = e.touches ? e.touches[0] : e['mp'].touches[0]

**屏幕截图和动态 GIF 图**

![复现步骤的屏幕截图和动态 GIF 图](图片的 url)

**Comment by F-loat** [comment]
小程序本身的 event 相关参数在 e.mp 中，目前应该就是这么设计的

**Comment by chenjinxinlove** [comment]
但是小程序和原生是可以直接拿到呀，那样多加一层，在把vue的组件，拿过来直接用，就会报错。直接拿到不是更合理吗

**Comment by aOrz** [comment]
后续会加上，感谢反馈
