### ISSUE TITLE
components vue组件-生命周期

### ISSUE THREAD

**Issue by 372572571** [Meituan-Dianping/mpvue#287]
# [问题简单描述]
components vue组件-生命周期 是不可用的吗？那组件如何优化外部传递给组件的数据？
还是只能在外部优化后传入？

**Comment by 372572571** [comment]
例如我写了一个基础组件，在page中引用，基础组件中的 生命周期没反应，基础组件里的created之类的都没触发，props 倒是可以
`<bac-badge badgeValue=99+></bac-badge>` 例如这样的组件 
我在组件使用
created （）{
   console.log('badge')
}
这个是无法触发的。
是否需要另外安装其他的工具？

**Comment by aOrz** [comment]
试了下，created 是正常触发的，给个能复现的 demo ？

**Comment by 372572571** [comment]
...可以了，昨晚上试了好久没有成功过.
你说正常触发.我刚刚试了下，还真的可以了.
十分感谢  (⑉꒦ິ^꒦ິ⑉)

**Comment by aOrz** [comment]
那我先关了 issue
