### ISSUE TITLE
npm run build后组件样式不生效，已参考 #7

### ISSUE THREAD

**Issue by zhiguoliang** [Meituan-Dianping/mpvue#292]
一开始 npm run dev后组件样式生效，但是代码上传的时候出现
![image](https://user-images.githubusercontent.com/26423212/38779483-c68742c6-40fb-11e8-9615-bf849fb90910.png)
但是组件的样式是生效的，

当npm run build 之后组件样式全丢失

**Comment by WWuzixin** [comment]
我也想问下这个问题。我从公司clone代码到本地上，然后运行完npm install。run起来后一直报编译错误，说没有打包。请问是什么问题

**Comment by WWuzixin** [comment]
@aOrz 
![9b7ec0d7ab14b5749c4b26784402e6c](https://user-images.githubusercontent.com/33918898/39281126-b6a733d8-4935-11e8-86db-11fa60a5687e.png)
很奇怪的事，我直接把公司代码。git pull 到本地。居然编译没问题。可是公司这边的电脑编译就异常

**Comment by WWuzixin** [comment]
@aOrz 代码正常使用。预览也没问题。就只是编译异常

**Comment by aOrz** [comment]
sourcemap 文件不上传是没有问题的，不是一个bug
