### ISSUE TITLE
使用mpvue-simple构建页面，component中的 data 数据不生效的问题

### ISSUE THREAD

**Issue by zhroeqqtw** [Meituan-Dianping/mpvue#293]
目前项目主体是用的wepy编写，新的功能页面使用了mpvue-simple构建了单页面，在单页面中引入component，发现component中的data数据是不生效的：
![image](https://user-images.githubusercontent.com/9767820/38780238-f122b506-4105-11e8-8464-32dbcc65cdc5.png)
而且在调试工具内appData中看不到data的数据，只能看到props的
![image](https://user-images.githubusercontent.com/9767820/38780256-2f64da88-4106-11e8-9732-64c814c91aec.png)

改成props就没问题
![image](https://user-images.githubusercontent.com/9767820/38780244-062b65c4-4106-11e8-8f8a-fb37c7fa17bd.png)
调试工具内也是能看到的
![image](https://user-images.githubusercontent.com/9767820/38780265-44ba35cc-4106-11e8-8d18-50858a86127a.png)

这是bug吗？  还是缺少什么配置？

**Comment by aOrz** [comment]
是我们的一个隐藏的bug ，data 可以先设置为一个返回 Object 的function,例：
```
export default {
  props: ['text'],
  data () {
    return {
      dataText: 'dataText'
    }
  },
  created () {
    console.log('card created')
  }
}
```

**Comment by lishenggang** [comment]
@zhroeqqtw 你好！请问编译生成出来的文件要怎么在小程序中引用？
![_20180507162153](https://user-images.githubusercontent.com/8177204/39705943-6fb5fc0a-5242-11e8-9e74-431afea5250b.png)
我2个vue的组件现在生成了这么一堆文件，不知道要怎么在小程序项目中用！他们之间好像没啥关系！

**Comment by zhroeqqtw** [comment]
@lishenggang static下面的文件都是在components 中被引用的，不需要关注， 正常使用conponents里面的组件就可以了

**Comment by tailorsira** [comment]
@zhroeqqtw 你是如何实现wepy中的页面和mpvue这个单页面之间的跳转和通信呢？

**Comment by lishenggang** [comment]
@zhroeqqtw 这生成的组件里面，就是一个template，根本就没有引用static下面的文件，他们之间也没有任何联系
![image](https://user-images.githubusercontent.com/8177204/39904054-b3260048-5508-11e8-8d8d-698dd8275863.png)

**Comment by zhroeqqtw** [comment]
@tailorsira 页面跳转都是使用微信原生的api，wx.navigateTo等，跟框架关系不大的。

页面通信一般都是在页面跳转的时候在url上传值，然后在onload函数中取参数

**Comment by zhroeqqtw** [comment]
@lishenggang 你是要使用在原生小程序的页面中吗？这样好像不行的哦

**Comment by lishenggang** [comment]
@zhroeqqtw 所以这个不能用在原生小程序页面中？？？我看文档中就是这么写的呀！
![image](https://user-images.githubusercontent.com/8177204/39904551-1b39337e-550b-11e8-9395-6f70533de2a7.png)

**Comment by zhroeqqtw** [comment]
@lishenggang 这里的混用指的是项目中同时使用原生页面和mpvue页面，组件级别的混用是不支持的，就是说没办法在原生的页面中使用mpvue的组件，mpvue的组件只能使用在mpvue的页面中

**Comment by lishenggang** [comment]
@zhroeqqtw 可以看看你页面级编译的源文件目录，编译的配置，以及编译生成的文件目录么？我页面级的编译，也用不了，也会报错！
![image](https://user-images.githubusercontent.com/8177204/39904793-5ad429ca-550c-11e8-8919-5a9246671638.png)
![image](https://user-images.githubusercontent.com/8177204/39904804-6491f154-550c-11e8-9b7d-485f1b8bc38a.png)

**Comment by zhroeqqtw** [comment]
@lishenggang 我现在没在用mpvue了，现在是wepy+原生在开发，wepy和mpvue都存在同一个page无法存在多个实例的问题，只能写原生来规避了
