### ISSUE TITLE
picker的mode为multiSelector的时候columnchange事件修改数据页面无法更新

### ISSUE THREAD

**Issue by chenyaoyi88** [Meituan-Dianping/mpvue#294]
# [问题简单描述]
picker的mode为multiSelector的时候columnchange事件修改数据页面无法更新

**问题复现步骤:**

code：
```html
<view class="section">
      <view class="section__title">多列选择器</view>
      <picker mode="multiSelector" @change="bindMultiPickerChange" @columnchange="bindMultiPickerColumnChange" :value="multiIndex" :range="multiArray">
        <view class="picker">
          自定义时间选择：{{multiArray[0][multiIndex[0]]}}，{{multiArray[1][multiIndex[1]]}}，{{multiArray[2][multiIndex[2]]}}
        </view>
      </picker>
    </view>
```
`
methods: {
    bindMultiPickerColumnChange(e) {
      console.log('修改的列为', e.target.column, '，值为', e.target.value);

      const multiArray = this.multiArray;
      const multiIndex = this.multiIndex;

      multiIndex[e.target.column] = e.target.value;
      switch (e.target.column) {
        case 0:
          switch (multiIndex[0]) {
            case 0:
              multiArray[1] = [
                '扁性动物',
                '线形动物',
                '环节动物',
                '软体动物',
                '节肢动物'
              ];
              multiArray[2] = ['猪肉绦虫', '吸血虫'];
              break;
            case 1:
              multiArray[1] = ['鱼', '两栖动物', '爬行动物'];
              multiArray[2] = ['鲫鱼', '带鱼'];
              break;
            default:
          }
          multiIndex[1] = 0;
          multiIndex[2] = 0;
          break;
        case 1:
          switch (multiIndex[0]) {
            case 0:
              switch (multiIndex[1]) {
                case 0:
                  multiArray[2] = ['猪肉绦虫', '吸血虫'];
                  break;
                case 1:
                  multiArray[2] = ['蛔虫'];
                  break;
                case 2:
                  multiArray[2] = ['蚂蚁', '蚂蟥'];
                  break;
                case 3:
                  multiArray[2] = ['河蚌', '蜗牛', '蛞蝓'];
                  break;
                case 4:
                  multiArray[2] = ['昆虫', '甲壳动物', '蛛形动物', '多足动物'];
                  break;
                default:
              }
              break;
            case 1:
              switch (multiIndex[1]) {
                case 0:
                  multiArray[2] = ['鲫鱼', '带鱼'];
                  break;
                case 1:
                  multiArray[2] = ['青蛙', '娃娃鱼'];
                  break;
                case 2:
                  multiArray[2] = ['蜥蜴', '龟', '壁虎'];
                  break;
                default:
              }
              break;
            default:
          }
          multiIndex[2] = 0;
          break;
        default:
      }

      this.multiArray = multiArray;
      this.multiIndex = multiIndex;
    }
  }
`

**期望的表现:**
picker在页面的数据得到更新

**Comment by aOrz** [comment]
注意看下 vue 关于数组的文档https://cn.vuejs.org/v2/guide/list.html#%E6%B3%A8%E6%84%8F%E4%BA%8B%E9%A1%B9

**Comment by chenyaoyi88** [comment]
@aOrz 非常感谢，用 vm.$set(vm.items, indexOfItem, newValue) 把问题解决了！第一次玩小程序+vue 文档看得不够细，提出这么基础的问题真的非常抱歉！

**Comment by david2tdw** [comment]
不过这个issue还是有价值的，因为这个问题我也搞了半天。看到这个提问后 立马 解决。:)
