### ISSUE TITLE
input使用v-model时，input从中间删除时光标跳到最后

### ISSUE THREAD

**Issue by simpledyt** [Meituan-Dianping/mpvue#296]
**期望的表现:**
从中间删除内容后，光标停留在中间。

**Comment by sharkdong** [comment]
@anchengjian 你可以搜索一下美团汽车票的小程序，在搜索框里面输入一句话，然后从中间删除，就看到效果了，我们目前也遇到这样的问题，textarea都有这个问题

**Comment by sharkdong** [comment]
目前这个问题，有一个解决方案，就是使用lazy修饰符，然后提交校验的时候，使用setTimeout， 延时100ms左右，不过，不能做实时校验，但是也是一种解决办法，我们目前就是这样做的

**Comment by F-loat** [comment]
看了下小程序的文档，感觉并不推荐通过 value 来绑定 input 的值，value 只是用来设置初始值的，获取值可以通过事件或表单提交，修改值可以通过 input 事件 return value 来完成，input 毕竟是个原生组件，按照小程序给的方式处理好一点

> 当键盘输入时，触发input事件，event.detail = {value, cursor}，处理函数可以直接 return 一个字符串，将替换输入框的内容。

**Comment by cduyzh** [comment]
本人完美解决input的闪烁问题，

**Comment by McsNick** [comment]
亲测 子组件更新的时候加个定时器就可以解决v-model双向绑定导致光标闪烁的问题 可以试试
自定义组件
`<input
          v-if="!textarea"
          :value="currentValue"
          @input="handleInput"
          @blur="handleBlur"
>`
`props: {
     value: {
      type: String,
      default: ''
    },
  }`
`data() {
    return {
      currentValue: this.value
    }
  },`
`handleInput(e) {
      const { mp: { detail: { value } } } = e
      this.currentValue = value
      // 定时器解决光标闪烁，中间删除 光标会自动重置到末尾的问题， 不能删除！！
      setTimeout(() => this.$emit('input', value))
    },`
父组件直接使用v-model
`<o-field label="快递类型"
        v-model="localExpressCompany"
        placeholder="点击选择快递种类"
        is-link
        className="has-border-bottom"/>`
