### ISSUE TITLE
组件起名 name: 'tabbar', 出现问题, 是否有更多类似？

### ISSUE THREAD

**Issue by omozzww** [Meituan-Dianping/mpvue#297]
# 组件起名 name：'tabbar'，子组件访问不了该组件的方法

**问题复现步骤:**

1. 定义组件
```javascript
export default {
    name: 'tabbar',
    mounted () {

    },
    methods: {
      say () {
        console.log(111)
      }
    },
 }
```
    
2. 子组件访问父组件方法
```javascript
export default {
    name: 'child',
    mounted () {
      this.$parent.say()
    }
}
```

![0db2f86fd5f8368482e1ee200a0fa402](https://user-images.githubusercontent.com/24713872/38813355-4f95124e-41c1-11e8-8ac8-e98a7055f523.jpg)

**Comment by anchengjian** [comment]
意思是不起名 tabbar 就可以访问了？你这个示例代码看不出问题，给个 demo  吧

**Comment by omozzww** [comment]
对的，不起名tabbar就可以访问了
