### ISSUE TITLE
异步请求后获取元素宽度的值不正确

### ISSUE THREAD

**Issue by xlkit456852** [Meituan-Dianping/mpvue#298]
# [问题简单描述]
横向scroll-view中有若干个元素，元素因内容文字长度不一而宽度不一，内容由异步请求数据获得。希望在请求数据后获得各元素的宽度，计算出总长度，让scroll-view可以正常滑动。但实际上获取的宽度一致是同一个数值（39），并不会因元素内容不同而数值不同。导致scroll-view显示不全。
**（咨询过小程序开发者社区，官方建议在小程序的setData回调里面（第二个参数）里执行，但貌似未发现咱们mpvue有支持这个？）**

**问题复现步骤:**

1. [第一步]
mounted() 里面请求数据
2. [第二步]
请求数据后使用 this.$nextTick()包裹wx.createSelectorQuery().selectAll()获取元素的宽度。
（也试过在$nextTick里再包裹一层setTimeout里面获取元素宽度，结果还是一样。）
3. [其他步骤...]
也试过将请求数据放在小程序onReady里面，但是结果是一样。
另外如果在请求数据后，在另一个元素的click事件中获取这些元素的宽度，则可以正常获取大小不一的宽度值。所以我在想是不是还是渲染的问题？

**期望的表现:**

希望能正确获取变化后的元素宽度

**观察到的表现:**

获得的元素宽度一直全部是39。

**屏幕截图和动态 GIF 图**

**Comment by yuconora** [comment]
试着用css解决
item 动态设置宽度
 > .container {
    overflow: scroll;
    white-space: nowrap;
    .item {
      display: inline-block;
    }
  }

**Comment by anchengjian** [comment]
无论是从代码质量还是性能，能用 css 的不要用 js

**Comment by xlkit456852** [comment]
最终是要给这个scroll-view一个>=子元素总宽度的宽度，让他可以滑动，但是只用css怎么做到？

**Comment by xlkit456852** [comment]
最后用setTimeout 200ms 包裹，先应付着就可以，不过也不是很稳定，有时候也会不正确，设500ms以上就可以，但是等待又长了~

**Comment by hucq** [comment]
### 建议：
- 使用宽度自适的 css 布局方案自动控制滚动元素宽度，具体方案可以查阅css
- 一定要使用js计算元素尺寸，需要更合理的考虑时机，确保在数据模型更新后计算元素尺寸，目前看来时机不准。在未计算之前为确保页面不抖动，可以预先设置一个较大的宽度避免折行。
