### ISSUE TITLE
使用 原生 video 标签 ,报错.

### ISSUE THREAD

**Issue by alienshengzi** [Meituan-Dianping/mpvue#299]
![image](https://user-images.githubusercontent.com/24715399/38855871-635a04b0-4257-11e8-81b2-7e62ac861499.png)

将小程序的调试基础库 选在2.0.0 后 ,使用 video ,会出现以下错误.  之前的版本1.9.98不受影响.

![image](https://user-images.githubusercontent.com/24715399/38855971-ab29d43c-4257-11e8-8968-9d379d7d31fb.png)

**Comment by anchengjian** [comment]
看起来像是基础库本身的错，你可以用原生小程序写法试一下

**Comment by aOrz** [comment]
未复现，如果还有问题的话，提供个 demo
