### ISSUE TITLE
先给你们赞一个，canvas的接口有没有转码，globalCompositeOperation 这个接口小程序没有提供，你们有没有解决办法。 

### ISSUE THREAD

**Issue by liuhongyi0101** [Meituan-Dianping/mpvue#30]
`var c=document.getElementById("myCanvas");
var ctx=c.getContext("2d");

ctx.fillStyle="red";
ctx.fillRect(20,20,75,50);
ctx.globalCompositeOperation="source-over";
ctx.fillStyle="blue";
ctx.fillRect(50,50,75,50);

ctx.fillStyle="red";
ctx.fillRect(150,20,75,50);
ctx.globalCompositeOperation="destination-over";
ctx.fillStyle="blue";
ctx.fillRect(180,50,75,50);`

**Comment by aOrz** [comment]
mpvue 是个 mvvm 的框架，并没有对 web 和 小程序的api进行抹平，在 mpvue 里面可以直接使用 小程序的组件和 api
