### ISSUE TITLE
tabBar中设置图片路径问题

### ISSUE THREAD

**Issue by alwaysRemember** [Meituan-Dianping/mpvue#301]
# [问题简单描述]
在tabbar中设置图标 会出现找不到图标的问题
**问题复现步骤:**

1. [第一步]
2. [第二步]
3. [其他步骤...]

**期望的表现:**

[在这里描述期望的表现]

**观察到的表现:**

[在这里描述观察到的表现]

**屏幕截图和动态 GIF 图**
![image](https://user-images.githubusercontent.com/26773809/38859920-996b8970-4261-11e8-96fb-75146b63d4ab.png)
![image](https://user-images.githubusercontent.com/26773809/38859975-ad48969a-4261-11e8-893e-15cd0b2f724f.png)

![复现步骤的屏幕截图和动态 GIF 图](图片的 url)

**Comment by yuconora** [comment]
/static/images/xx.png

**Comment by neal1991** [comment]
放在 static 文件夹下还是有问题啊，也是提示文件不存在
```jsson
    tabBar: {
      list: [{
        pagePath: 'pages/index/main',
        text: '首页',
        iconPath: '/static/icons/home.png',
        selectedIconPath: '/static/icons/home-selected'
      }, {
        pagePath: 'pages/logs/main',
        text: '发现',
        iconPath: '/static/icons/discover',
        selectedIconPath: '/static/icons/dicover-selected'
      }, {
        pagePath: 'pages/counter/main',
        text: '我的',
        iconPath: '/static/icons/mine',
        selectedIconPath: '/static/icons/mini-selected'
      }],
    }, 
```

**Comment by fernandoxu** [comment]
怎么解决的呀？照上面那个弄也没有效
