### ISSUE TITLE
组件编译路径

### ISSUE THREAD

**Issue by JasonDRZ** [Meituan-Dianping/mpvue#302]
![image](https://user-images.githubusercontent.com/9544398/38876684-9184525e-428f-11e8-8031-9e6d85759ba4.png)
![image](https://user-images.githubusercontent.com/9544398/38876745-b534d0a2-428f-11e8-8024-8c587611b36e.png)
在这样的目录结构中，在开发时能够通过绝对路径找到，但是编译后这个深层嵌套的路径并没有得到修改，导致在实际运行时和真机调试中无法找到文件路径。

**Comment by JasonDRZ** [comment]
dev和build之后的dist目标项目在调试器上运行时，是可以找到对应的文件路径的。但是通过真机预览时，由于路劲并没有被修改，到时无法找到真实的文件路径。

**Comment by charmingzuo** [comment]
用 /static 开头

**Comment by JasonDRZ** [comment]
@charmingzuo 是我秀逗了，后面就是用的这个开头，哈哈哈。

**Comment by mdsb100** [comment]
不要用相对路径。这个issue其实可以关了
