### ISSUE TITLE
v-bind:style 使用+操作符结果错误

### ISSUE THREAD

**Issue by natee** [Meituan-Dianping/mpvue#303]
# v-bind:style中使用+全部按照字符串相加处理，预期应该正常处理数值相加
v-bind:style="{width: size+8+ 'px'}"
如：size=1,结果是width:18px

**期望的表现:**
可以正常识别+，因为*-都正常

**Comment by natee** [comment]
@soapper 这种方式编译错误

**Comment by anchengjian** [comment]
受限于微信的能力，styleObject 会被编译成 `'width:' + index + 8 + 'px'` 的 styleString ，所以导致了错误，应该可以做到编译成 `'width:' + (index + 8 + 'px')` 这种，能最大程度避免这种错误。

**Comment by soapper** [comment]
@Fancyhr 我晚上回家试一下

**Comment by F-loat** [comment]
#391

**Comment by aOrz** [comment]
已发版修复
