### ISSUE TITLE
怎么处理小程序里面的特殊事件

### ISSUE THREAD

**Issue by ifuner** [Meituan-Dianping/mpvue#304]
</button open-type="getPhoneNumber" bindgetphonenumber="getPhoneNumber"> </button>

如上获取当前用户的点击允许后返回值
官方文档地址:https://developers.weixin.qq.com/miniprogram/dev/api/getPhoneNumber.html

使用@click事件代替拿不到返回的对象
这个该怎么解决啊？

**Comment by anchengjian** [comment]
同 #204 , 文档 http://mpvue.com/mpvue/#_13

**Comment by ifuner** [comment]
已解决，感谢~要是官方文档上能更新上去就更好了，也方便更多开发
