### ISSUE TITLE
关于自定义组件

### ISSUE THREAD

**Issue by shawtung** [Meituan-Dianping/mpvue#305]
1.想问问之所以不使用原生自定义组件是因为开发mpvue的时候原生还没有吗? 后续会考虑用原生实现吗?

2.现在的自定义组件里内部也是要求只有唯一顶级元素的, 那为什么不能跟正常vue一样在自定义组件标签上绑定东西?  是因为小程序template标签的锅么?

**Comment by F-loat** [comment]
1. 小程序的原生自定义组件是支持的吧 [demo](https://github.com/mpvue/examples/tree/master/echarts)

2. 原生自定义组件1.6.3的基础库才支持，用这个来实现组件化不太合适

**Comment by shawtung** [comment]
现在基础库版本到2.0.0了呀~还需要考虑1.6.3吗?

**Comment by shawtung** [comment]
我的意思是mpvue实现的自定义组件, 并没有使用原生component来实现, 是考虑到基础库版本的问题吗?
@F-loat

**Comment by F-loat** [comment]
会有这方面的考虑吧，另外改写也需要时间，而且微信的版本也没那么乐观的

**Comment by shawtung** [comment]
好的,谢谢啦~

**Comment by rchunping** [comment]
我觉得需要更多评估一下，目前遇到一个问题，原生的自定义组件z-index无法提升覆盖父级组件（iOS上）
因为原生自定义组件在Shadow DOM里，CSS独立，一些组件效果将无法实现。

**Comment by shawtung** [comment]
@rchunping 
没有理解何为无法提升覆盖父组件..
比如可能会有哪些效果无法实现呢?

**Comment by rchunping** [comment]
@shawtung  比如要做个对话框组件，一般是需要一个半透明全屏遮盖层的，这时候iOS上，遮盖层的z-index无法让它覆盖在页面其他有z-index的区域上面。

当然这不是组件的问题，是各内核对Shadow DOM的处理不一致

**Comment by shawtung** [comment]
@rchunping 了解了, 看起来又是个美丽的饼...
谢谢~

**Comment by rchunping** [comment]
@shawtung 反正目前原生的自定义组件也能在mpvue里用的
