### ISSUE TITLE
小程序自定义埋点问题

### ISSUE THREAD

**Issue by fangdiao** [Meituan-Dianping/mpvue#306]
# [问题简单描述]
在原生小程序中，开发者在统计中添加自定义埋点，若需要添加字段则需要在原生的page.data中增加相应的埋点字段。像这样 
```javascript
Page({
  data: {
    id: "我是埋点的字段"
  },
  onLoad: function(options) {
    // Do some initialize when page load.
  }
})
```

但是在mpvue中的data与原生的data不一致，导致了自定义埋点增加字段无法生效。
而且在尝试使用 `$root[0].id`后也无效。
请问怎样才能获取到id
**问题复现步骤:**

1. [第一步]
2. [第二步]
3. [其他步骤...]

**期望的表现:**

[在这里描述期望的表现]

**观察到的表现:**

[在这里描述观察到的表现]

**屏幕截图和动态 GIF 图**

![复现步骤的屏幕截图和动态 GIF 图](图片的 url)

**Comment by younth** [comment]
mark

**Comment by younth** [comment]
@fangdiao `使用API进行上报` ，然后生成代码即可。

![image](https://user-images.githubusercontent.com/8591147/44647609-18151180-aa11-11e8-929f-7e6b01a0a99e.png)
