### ISSUE TITLE
一个使尽浑身解数也不知道什么问题的问题

### ISSUE THREAD

**Issue by Hadroning** [Meituan-Dianping/mpvue#308]
之前使用mpvue的项目都已经正常上线了
但是再次维护的时候发现新增conponent的数据、生命周期都出现了问题
试了N次，重新下了一个，发现还是这样
同样的组件，demo里默认的card 复制了一份改了个名，同一个位置调用，但就是一个生效 一个不生效
<img width="393" alt="1" src="https://user-images.githubusercontent.com/20159065/38924614-fe28af0e-432f-11e8-838c-c90e3fa1492b.png">
<img width="306" alt="2" src="https://user-images.githubusercontent.com/20159065/38924617-fe69f982-432f-11e8-91a9-9008dd66f3b9.png">
<img width="300" alt="3" src="https://user-images.githubusercontent.com/20159065/38924618-feac8ce8-432f-11e8-9085-342cd1308a89.png">
![a8a35038f68f58b9bcc05607a3881c11](https://user-images.githubusercontent.com/20159065/38924621-feed0412-432f-11e8-9c0d-194d76397e57.png)

**Comment by Hadroning** [comment]
大半天都在问自己到底哪里搞错了 到底是为什么

**Comment by 372572571** [comment]
给组件加上名称。 name：属性  name: 'card2'

**Comment by Hadroning** [comment]
加了也不好使...

**Comment by 372572571** [comment]
你把那个什么list 删了，把card 在复制一份改成组件
试了好几次这样就行了。。。

**Comment by Fancyhr** [comment]
这个应该是组件的名字问题吧

________________________________

**Comment by lanshengzhong** [comment]
组件名的问题估计   比如我自己写的名字为loading的组件就没有用

**Comment by nitta-honoka** [comment]
`card` 在小程序里面默认是**卡券**的名字，将 `card` 名字改掉试试

**Comment by Hadroning** [comment]
我就是复制的card，然后card好使list不好使，组件的name也加上了，也不好使

**Comment by charmingzuo** [comment]
我的用法和你区别只有2点：

**Comment by Hadroning** [comment]
组件名字的问题，不能用list这个关键字 我tm...

**Comment by 372572571** [comment]
。我就说那个list有毒了.....

**Comment by anchengjian** [comment]
https://github.com/Meituan-Dianping/mpvue/blob/master/src/platforms/mp/util/index.js#L7-L14

```
export const isReservedTag = makeMap(
  'template,script,style,element,content,slot,link,meta,svg,view,' +
  'a,div,img,image,text,span,richtext,input,switch,textarea,spinner,select,' +
  'slider,slider-neighbor,indicator,trisition,trisition-group,canvas,' +
  'list,cell,header,loading,loading-indicator,refresh,scrollable,scroller,' +
  'video,web,embed,tabbar,tabheader,datepicker,timepicker,marquee,countdown',
  true
)
```

当时借鉴了 weex ，大家伙来个 pr 到文档，避免后人踩坑啊

**Comment by anchengjian** [comment]
https://github.com/Meituan-Dianping/mpvue/blob/master/src/platforms/mp/util/index.js#L7-L14

```
export const isReservedTag = makeMap(
  'template,script,style,element,content,slot,link,meta,svg,view,' +
  'a,div,img,image,text,span,richtext,input,switch,textarea,spinner,select,' +
  'slider,slider-neighbor,indicator,trisition,trisition-group,canvas,' +
  'list,cell,header,loading,loading-indicator,refresh,scrollable,scroller,' +
  'video,web,embed,tabbar,tabheader,datepicker,timepicker,marquee,countdown',
  true
)
```

当时借鉴了 weex ，大家伙来个 pr 到文档，避免后人踩坑啊

**Comment by zxzhgk** [comment]
countdown 中标！！！！ 查了半天

**Comment by songlairui** [comment]
深深踩了一脚
