### ISSUE TITLE
自定义组件中绑定事件报错

### ISSUE THREAD

**Issue by nervouself** [Meituan-Dianping/mpvue#309]
# 自定义组件中绑定事件报错

**问题复现步骤:**
页面 a.vue 中引用了自定义组件 b.vue，在 b.vue 中有如下代码：

<image @tap="doSomething"></image>

 methods: {
  doSomething() {
     // some code
  }
}

在开发工具中切换到页面 a，点击组件 b 中的 image，报如下错：

thirdScriptError
Cannot read property 'page' of undefined;at pages/accountLoginView/main page handleProxy function
TypeError: Cannot read property 'page' of undefined
    at Vue$3.handleProxyWithVue [as $handleProxyWithVue] (http://127.0.0.1:52652/appservice/static/js/vendor.js:5428:29)

具体代码位置为：

 // TODO, enevt 还需要处理更多
  // https://developer.mozilla.org/zh-CN/docs/Web/API/Event
  if (handles.length) {
    var event = getWebEventByMP(e);
    handles.forEach(function (h) { return h(event); });
  } else {
    var currentPage = vm.$mp.page.route;  // 《《《《 这一行
    console.group(new Date() + ' 事件警告');
    console.warn(("Do not have handler in current page: " + currentPage + ". Please make sure that handler has been defined in " + currentPage + ", or " + currentPage + " has been added into app.json"));
    console.groupEnd();
  }

如果直接在页面 a.vue 中使用 image  并绑定事件并不会出错，实测错误和组件类型 image 没有关系，和绑定事件类型也没有关系，在组件 b.vue 中打印 this 发现并没有 $mp 这个属性。

**Comment by F-loat** [comment]
#279 有相关问题的反馈了，但是子组件中绑定的处理函数存在的话，应该不会有这个错误的啊

**Comment by nervouself** [comment]
我也感觉很费解，因为这个错误时有时无。。

**Comment by charmingzuo** [comment]
我遇到的情况是 doSomething 这个方法没有定义在 methods 对象里面：
```
export default {
  doSomething() {}
}
```
改成下面就好了
```
export default {
  methods: {
    doSomething() {}
  }
}
```

**Comment by nervouself** [comment]
@charmingzuo 我已经定义在 methods 里了～

@F-loat 我已经找到具体问题原因了，原因是我给事件绑定对象加了个 v-if，条件是傍边的 input 有值且 focus（没错这是个清空按钮），当我点清空的时候 focus 已经为 false 了，所以这个事件绑定对象消失了，于是报错。可以通过延迟设置 focus 来避免报错，但是很不优雅。。还是希望能优化下。。

**Comment by F-loat** [comment]
@nervouself 感觉还是你处理逻辑上的问题，修复之后是只会输出警告，不会报错了

**Comment by nervouself** [comment]
@F-loat 好吧~我这逻辑就是很简单啊~一个 input 在 focus 并且有值的时候出现一个❌，点❌清空 input

**Comment by F-loat** [comment]
@nervouself  你可以试下把 v-if 改成 v-show，之后我测下 vue 本身这样用有没有问题，没问题的话我们再想办法优化

**Comment by nervouself** [comment]
我改用 class 隐藏就不会报错啦，和 v-show 一个道理~
