### ISSUE TITLE
调用wx.reLaunch调转页面 该页面之前填写的数据不会重置

### ISSUE THREAD

**Issue by ZionStark** [Meituan-Dianping/mpvue#311]
# [问题简单描述]
一个简单的登录跳转，A为用户页面，B为登录页面。

B页面（登录页面）输入完手机号之后，调用wx.reLaunch跳转到A页面（用户页面）。
此时我在A页面进行注销登录，再调用wx.reLaunch返回B页面。
B页面我上次填写的手机号和验证码还在

A页面代码
![2018-04-19 10 25 31](https://user-images.githubusercontent.com/31435386/38967973-11f767e6-43bc-11e8-829f-bd35f3462091.png)

**期望的表现:**

![2018-04-19 10 27 18](https://user-images.githubusercontent.com/31435386/38968015-45a2ef70-43bc-11e8-97e5-ad4fab25de14.png)

**观察到的表现:**

![2018-04-19 10 27 10](https://user-images.githubusercontent.com/31435386/38968024-4e31c4ea-43bc-11e8-8c9a-4b606b4e1f30.png)

**Comment by Fancyhr** [comment]
[https://github.com/Meituan-Dianping/mpvue/issues/140](140)

**Comment by Fancyhr** [comment]
[140](https://github.com/Meituan-Dianping/mpvue/issues/140)

**Comment by Fancyhr** [comment]
[#140](https://github.com/Meituan-Dianping/mpvue/issues/140)

**Comment by Fancyhr** [comment]
[#140](https://github.com/Meituan-Dianping/mpvue/issues/140)请看这个问题

**Comment by ZionStark** [comment]
@Fancyhr 
谢谢回复，#140这个问题我之前已经查看过了。
现在有更好的解决办法了吗？

**Comment by Fancyhr** [comment]
暂时没有什么好办法~ 我之前也遇到，只能等修复了

**Comment by hushenao** [comment]
我目前也遇到了这个问题，有解决办法了吗

**Comment by Aimee1608** [comment]
重置数据这个方法太低级了，没有更好的解决方案吗？感觉要放弃mpvue 了
