### ISSUE TITLE
页面重复渲染的问题

### ISSUE THREAD

**Issue by wo2095296** [Meituan-Dianping/mpvue#313]
我从首页,跳到一个列表页面,然后再跳到详情页,如果我从详情页面返回到列表页面,再次进入的话,会重复生成几个一摸一样的详情页,在手机真机上有这样的情况,特别是安卓手机,有人遇到过这样的问题吗,是怎么样解决的

**Comment by aOrz** [comment]
问题同 #300  ，重复问题先关了
