### ISSUE TITLE
mpvue使用中几个头疼的bug

### ISSUE THREAD

**Issue by TJ-XiaJiaHao** [Meituan-Dianping/mpvue#316]
1. 组件渲染是串行的，而原生的是并行的。假设一个页面中用到了5个A组件，一个组件渲染时间大约为100毫秒，那么在原生中所有组件渲染完成约为100毫秒（并行渲染），而在mpvue中则需要约为500毫秒（串行渲染）。

2. 当动态绑定一个数据时，某些情况下即使该数据没有发生变化，也会被刷新（感觉像是mpvue不断地在赋值）。如下面是一个简单的slider，想要在拖动的时候实时修改标题，但是会不断地重新赋值为chapterIndex的值，就会出现回弹的bug，而且松手后的value不是最新的value，而是chapterIndex（下面注释部分为解决方案）。scroll-view如果动态绑定scrolltop也有同样的问题，input如果动态绑定value也会有同样的问题。

```
// 假设现在chapterIndex为0，slider最大为10
<slider :value="chapterIndex"
          @changing="sliderChooseChaptering"
          @change="sliderChooseChaptered">
          

// 拖动slider到5处
sliderChooseChaptering(e) {
    // this.chapterIndex = undefined;       // 通过设置为undefined可以避免滚动条回退
    this.toolbarTitle = 'new title';      // 改动了标题变量，但是slider会被重新赋值，小圆点回退到0处
},
          
sliderChooseChaptered(e) {
    let chapterIndex = e.mp.detail.value;
    console.log(chapterIndex);            // 值为0，而不是5
    // this.chapterIndex = chapterIndex;    // 重新赋值
}
```

3. scroll-view中无法监听到垂直的touchmove

```
<scroll-view style="height:100rpx" scroll-y @touchstart="tstart" @touchend="tend" @touchmove="tmove">
  <div style="height: 200rpx">我就想监听到垂直的move</div>
</scroll-view>
 

tstart() {
  console.log('tstart');        // 总是执行
},
tend() {
  console.log('tend');        // 总是执行
},
tmove() {
  console.log('tmove');        // 横向拖动时执行，垂直拖动时不执行
},
```

#### 说明：第二个问题会导致很多问题，比如输入框动态赋值，scroll-view动态绑定scroll-top，slider动态绑定数值，都会出现回退现象，即使动态绑定的值也实时更新，也会出现闪烁的现象，体验比较差。

**Comment by soapper** [comment]
input 问题发现了

**Comment by nervouself** [comment]
假如将题主的代码改成

```js
sliderChooseChaptering(e) {
    this.toolbarTitle = Math.random(); 
}
```

除了会发生题主所说的问题之外，在安卓机上（骁龙801的机器，非山寨机）会发生在拖动过程中画面中 toolbarTitle 变换的很迟缓，快速滑动几下以后手指停住， toolbarTitle 海市在继续缓慢的变化，感觉是滑动中触发的事件被推入一个数组然后每隔几十毫秒执行一个，慢慢消费，导致手指停住还没消费完的感觉。不仅仅是 slider 的滑动事件触发，包括 scroll-view 的 scroll 事件频繁触发也会导致类似的情况。

**Comment by seawenzhu** [comment]
up up up

**Comment by lanshengzhong** [comment]
up up up

**Comment by bigmeow** [comment]
@nervouself  MPVUE源码中 setData的最快频率是50ms,做了函数节流

**Comment by mdsb100** [comment]
其实这个可以参考 wepy吧。 做一个this.$apply()。让用户可选的去渲染。

**Comment by lemonpigpig** [comment]
不打算用mpvue了，如果这些问题不解决，很莫名其妙，一个数据变化就序列化所有的，

**Comment by zhuanglong** [comment]
解决了吗

**Comment by qinshou** [comment]
@TJ-XiaJiaHao 建议的复制value为undefined的确有效，但是又需要value作为页码，怎么都绕不过

已经打算退坑

**Comment by mdsb100** [comment]
@qinshou 你可以选择混写啊
