### ISSUE TITLE
mpvue中form validate应该如何做比较好?

### ISSUE THREAD

**Issue by Stupidism** [Meituan-Dianping/mpvue#317]
我现在计划自己实现一个Form和一个Field组件, 来统一管理诸如,自动focus下一个Field, 错误提示 等事情

**Comment by pcloth** [comment]
写个方法，报错调用微信小程序的接口。

**Comment by Stupidism** [comment]
@pcloth 你说的报错接口是指 showToast吗? 这也太粗糙了....

**Comment by aOrz** [comment]
和普通前端项目中 form validate 一致吧，可以参考下目前比较流行的方案

**Comment by Stupidism** [comment]
@aOrz 我试过 vue 生态圈中的 form validate 库, 好像都有用 dom. 所以不能用

**Comment by aOrz** [comment]
把 dom 改一改？
