### ISSUE TITLE
mpvue目前是否无法支持vue递归组件

### ISSUE THREAD

**Issue by z008hy** [Meituan-Dianping/mpvue#319]
目前mpvue是否还没支持vue的递归组件。如果使用递归组件只能多层套用

**Comment by anchengjian** [comment]
按我们现在的原理 wxml template 无法实现深层递归，所以 vue 组件也是无法递归的。

**Comment by z008hy** [comment]
好的，多谢解答

**Comment by johnnynode** [comment]
https://github.com/Meituan-Dianping/mpvue/issues/850
