### ISSUE TITLE
是否有支持原生自定义组件的计划

### ISSUE THREAD

**Issue by WalterZou** [Meituan-Dianping/mpvue#320]
RT 所述，目前组件是通过 template 来实现的，目前原生小程序已经支持自定义组件，请问有支持原生自定义组件的计划吗？

**Comment by anchengjian** [comment]
原生组件在设计时就考虑到了，不需要过多支持，请参考 https://github.com/mpvue/examples/tree/master/echarts 使用原生组件

**Comment by rchunping** [comment]
@WalterZou  可以改webpack配置来实现

假设你 src/native/coms 目录作为原生组件目录
比如child组件包含四个文件
child.js
child.json
child.wxml
child.wxss
按照原生小程序自定义组件的方式写就行

webpack.base.conf.js中的entry中添加你的原生组件 child.js 入口，把它当一个page来构建

其他.[wxml|json|wxss]文件需要复制到dist目录，可以在webpack.dev.conf.js 中配置
```javascript
     // copy custom static assets
    new CopyWebpackPlugin([
      {
        from: path.resolve(__dirname, '../static'),
        to: config.build.assetsSubDirectory,
        ignore: ['.*']
      }
    ]),
    // 这里添加下面代码
    // copy native to /dist/native
    new CopyWebpackPlugin([
      {
        from: path.resolve(__dirname, '../src/native'),
        to: 'native',
        ignore: ['.*', '*.js', '*.wxss'],
        force: true
      }
    ]),

    // copy native (.wxss) to static/css/native
    new CopyWebpackPlugin([
      {
        from: '**/*.wxss',
        to: 'static/css/native/',
        ignore: ['.*'],
        force: true,
        context: 'src/native/'
      }
    ]),
```

**Comment by anchengjian** [comment]
@WalterZou mpvue支持打包成原生组件，不过目前还没写文档。。。
具体操作是

1. 在 config 中添加 `{isComponent:true}`
2. 修改 mpType 注册为： `App.mpType = 'component'`

最后 打包出来就是一个原生组件。

**Comment by charmtiger** [comment]
这就是为什么没事就要翻翻 issue 的原因 😂

**Comment by qq157788394** [comment]
文档文档文档！

**Comment by Airkro** [comment]
晕， 应该是`{ component:true }`

**Comment by Airkro** [comment]
目前我使用这个方法编译出来的原生组件会接收不到props

**Comment by qq157788394** [comment]
@Airkro 我也一样。。。没文档猜起来真累。

**Comment by atzcl** [comment]
最新版依然存在这个问题，[#617](https://github.com/Meituan-Dianping/mpvue/pull/617) 的修复无效

**Comment by luojinghui** [comment]
@anchengjian 

> @WalterZou mpvue支持打包成原生组件，不过目前还没写文档。。。
> 具体操作是
> 
> 1. 在 config 中添加 `{isComponent:true}`
> 2. 修改 mpType 注册为： `App.mpType = 'component'`
> 
> 最后 打包出来就是一个原生组件。

可以详细的说明一下配置步骤吗？config在哪？在哪里修改mpType?

**Comment by cleverboy32** [comment]
@luojinghui  你知道怎么配置了么

**Comment by cleverboy32** [comment]
@Airkro  你怎么配置的啊， 我这边会把组件里的 slot 编译掉

**Comment by cleverboy32** [comment]
@Airkro 所以你是怎么配置的啊， 我组件里的 slot 都被编译了 = = ， 请帮帮我

**Comment by stanJ** [comment]
> 2\. component

能不能详细说一下config和mpType修改的地方？比如我有一个页面叫做order_list.vue，引用了组件order_item.vue，那我该怎么把order_item.vue编译成原生自定义组件呢？

**Comment by stanJ** [comment]
> @WalterZou mpvue支持打包成原生组件，不过目前还没写文档。。。
> 具体操作是
> 
> 1. 在 config 中添加 `{isComponent:true}`
> 2. 修改 mpType 注册为： `App.mpType = 'component'`
> 
> 最后 打包出来就是一个原生组件。

能不能详细说一下config和mpType修改的地方？比如我有一个页面叫做order_list.vue，引用了组件order_item.vue，那我该怎么把order_item.vue编译成原生自定义组件呢？
