### ISSUE TITLE
请问mpvue是否能够把url的img路径转换成base64?

### ISSUE THREAD

**Issue by Juliancn** [Meituan-Dianping/mpvue#321]
mpvue里面的img引入一个带有别名的src路径是不是不支持，是不是不支持呢？
![b1](https://user-images.githubusercontent.com/25763921/39029438-6562b322-448e-11e8-9642-1cd380e140ac.png)

其他疑问：
以下图片中的url-loader 配置的目的是干嘛（因为我发现并不能使url的图片地址改成base64,不知是否是是我的使用方式不对！！）
![b2](https://user-images.githubusercontent.com/25763921/39029434-60183b44-448e-11e8-9b53-ddcdd8cce7de.png)

**Comment by aOrz** [comment]
请更新最新的 mpvue、mpvue-template-compiler、mpvue-loader 试下
