### ISSUE TITLE
使用回退 $root.$mp.query没有更新

### ISSUE THREAD

**Issue by KennyWho** [Meituan-Dianping/mpvue#322]
执行后退操作后，从A?key=value1页面到B页面, 然后B页面跳转到A?key=value2页面，此时后退2次，A?key=value1这个页面的query还是key=value2。
可重复稳定复现。

**Comment by F-loat** [comment]
#140

**Comment by JasonDRZ** [comment]
可以使用自定义的页面跳转方案进行规避，并且能够不受wx.navigateTo路径数据传输的限制。详情见：[#349](https://github.com/Meituan-Dianping/mpvue/issues/349)

**Comment by Stupidism** [comment]
@KennyWho 我遇到相似的问题, 不知你的情况是否相同

不同的是在mounted中查看`this.$root.$mp.query`其实这个值更新了,
只是如果直接写的computed中的东西就不能更新成功.
如:
```
computed: {
  key() {
    return this.$root.$mp.query.key;
  }
}
```
可以通过主动用data赋值来使之生效:
```
mounted() {
  this.key = this.$root.$mp.query.key;
}
```
