### ISSUE TITLE
<slot>在run dev时成功编译，启动服务后，修改其中的内容不再编译

### ISSUE THREAD

**Issue by linrunzheng** [Meituan-Dianping/mpvue#324]
# ##[问题简单描述]

 slot里面的内容 ，在npm run dev的时候有效。

启动服务后，修改slot的内容，不再编译。

需要重新run dev，方可生效。

**期望的表现:**

启动服务后修改slot的内容可以立即生效

**Comment by aOrz** [comment]
同 #245  相同的问题先关闭了，集中在一起讨论
