### ISSUE TITLE
mpvue-simple build时错误

### ISSUE THREAD

**Issue by realxiouz** [Meituan-Dianping/mpvue#325]
# [问题简单描述]
公司小程序基本完成(原生开发),接手维护时想使用mpvue.使用mpvue-simple build时报错.
![js](https://user-images.githubusercontent.com/9744436/39082292-6764e78a-4583-11e8-9286-38b43a891e8a.gif)
![vue](https://user-images.githubusercontent.com/9744436/39082310-cc07e6b0-4583-11e8-9564-2f38a49527d0.gif)
![default](https://user-images.githubusercontent.com/9744436/39082315-cf1aa180-4583-11e8-8df6-07ae157fe646.gif)
运行 node a.js
build失败
![err](https://user-images.githubusercontent.com/9744436/39082335-156c4fe4-4584-11e8-895f-3200fda7bf83.gif)

**Comment by legendJaden** [comment]
同问，我用命令行执行，也遇到跟你一毛一样的错误，我开始以为是抽取样式的依赖包的问题，卸载重装之后依然不行。

**Comment by legendJaden** [comment]
请问楼主这个问题后来解决了么？ @realxiouz

**Comment by anchengjian** [comment]
目前 entry 格式有个强约束 http://mpvue.com/build/mpvue-loader/#entry 可以修改后再试试

**Comment by legendJaden** [comment]
@anchengjian 我按照mpvue-loader文档改了下entry，如图但还是报错，好像就是没有生成样式打包文件，然后压缩代码也有问题

**Comment by legendJaden** [comment]
@anchengjian 我按照mpvue-loader文档改了下entry，如图：
![mpvue-simple entry](https://user-images.githubusercontent.com/35457398/39734671-ede52c32-52aa-11e8-9b45-294d972f8c17.jpg)

但是依然报一样的错，如图：
![mpvue-simple css-missing](https://user-images.githubusercontent.com/35457398/39734775-420de02e-52ab-11e8-8f52-4662dde0770b.jpg)

值得注意的是，似乎确实抽取样式是有问题的，没有生成css文件夹以及对应的打包wxss文件，如图：
![mpvue-simple css-missing](https://user-images.githubusercontent.com/35457398/39734816-670cf950-52ab-11e8-8578-5c8d292323aa.jpg)

**Comment by legendJaden** [comment]
@anchengjian 我按照mpvue-loader文档改了下entry，如图：
![mpvue-simple entry](https://user-images.githubusercontent.com/35457398/39734850-942427ba-52ab-11e8-8243-3e24947881a3.jpg)

但是依然报一样的错，如图：
![mpvue-simple error-log](https://user-images.githubusercontent.com/35457398/39734854-9a4234b6-52ab-11e8-9917-8e77c0afbd8c.jpg)

值得注意的是，似乎确实抽取样式是有问题的，没有生成css文件夹以及对应的打包wxss文件，如图：
![mpvue-simple css-missing](https://user-images.githubusercontent.com/35457398/39734863-a0fc35fe-52ab-11e8-87d9-ebc1ef09d55c.jpg)

**Comment by anchengjian** [comment]
是不是少装了什么 css 的依赖，比如 sass less 什么的

**Comment by legendJaden** [comment]
没有使用这些预处理器哦，css-loader, postcss-loader, px2rpx-loader, vue-style-loader 都有

**Comment by anchengjian** [comment]
搞个可复现的 demo 吧

**Comment by jhs1873** [comment]
linux下不报错。win下报错信息和楼主一样

**Comment by hgs1** [comment]
请问楼主问题是否解决？

**Comment by hgs1** [comment]
> 搞个可复现的 demo 吧

你们倒是给个官方的好用的demo啊
