### ISSUE TITLE
想要做到login 接口又返回之后在渲染界面

### ISSUE THREAD

**Issue by fanyongfeng** [Meituan-Dianping/mpvue#327]
想要做到login 接口又返回之后在渲染界面

const app = new Vue({
  ...App,
  store,
});
login().then(res => {
  store.dispatch('login', res).then(res => {
    app.$mount();
  });
});

这样子做好像并不行？？

**Comment by JasonDRZ** [comment]
$mount()方法就好像小程序的Page()和App()两个实例方法，很简单的道理，你能让着两个实例方法异步不嘛？如果你想让login后在渲染页面，在页面里面用v-if设置一个标示不久OK了。。。

**Comment by fanyongfeng** [comment]
就是想加一个统一的登陆判断，登陆之后再去发起数据请求  加标记 在store里面 只能在每个页面里面去监听标记的变化。登陆之后发起数据请求。 这样子做是下策。不得已而为之。 至于在页面里面if。 生命周期函数里面需要先登陆后请求 然后标记if。 那么多独立页面。都需要做

**Comment by fanyongfeng** [comment]
小程序并不是只有一个主页入口。分享页也是入口

**Comment by fanyongfeng** [comment]
就好比在一个spa里面做自动登录，登陆之后才能拿着token去请求数据，所有的请求/渲染都要在登陆后，所以需要加一个唯一入口的登陆判断，而不是去每个页面里面判断

**Comment by Rem486** [comment]
@fanyongfeng 最近也遇到了这样的尴尬， 请问最后怎么处理的呢？

**Comment by vv13** [comment]
@Rem486 
![image](https://user-images.githubusercontent.com/9440756/45355947-6a9b2400-b5f4-11e8-971c-09efdd02e11c.png)
