### ISSUE TITLE
框架中使用<live-pusher/>和<live-play/>都有问题！！！！！！！！

### ISSUE THREAD

**Issue by szoyaung** [Meituan-Dianping/mpvue#329]
框架中使用小程序里的实时音视频组件，都有问题，全是白屏。
用原生的测试就是可以的。
求回复。
急！！！！！！！！

**Comment by szoyaung** [comment]
修改组件样式就可以了，但是还是期望能解决这个问题。

**Comment by sideFlower** [comment]
组件样式 怎么修改的 ？

**Comment by szoyaung** [comment]
live-pusher样式中的overflow:改成visible;就可以了，因为对css没有太多的了解，只是能用，所以我也不知道为什么会这样。
目前做测试时能解决了。。。

**Comment by aOrz** [comment]
我试了下，官方的 demo 拷贝到 mpvue 中就能使用，没有复现
