### ISSUE TITLE
用js抛出vue组件后，报template not found的错

### ISSUE THREAD

**Issue by linrui1994** [Meituan-Dianping/mpvue#33]
> 这样写的正常的
```js
import Toast from '@/Toast.vue'
```

> 下面这样写就出问题了
```js
import Toast from '@/toast.js'
```

```js
// toast.js
import Toast from './Toast.vue'

Toast.install = function (Vue) {
  Vue.component(Toast.name, Toast)
}

export default Toast
```

报错如下：

![image](https://user-images.githubusercontent.com/20953049/37244361-d8cb2a38-24c2-11e8-8a44-aa61f5d04cda.png)

请问这是个bug还是我哪里写错了

**Comment by anchengjian** [comment]
wxml 是 .vue 的 SFC 经过 mpvue-loader 生成的，js 文件默认不会生成 wxml 文件，所以会导致 template 找不到。
建议组件封装成 .vue 文件。
