### ISSUE TITLE
使用原生组件的坑，求解

### ISSUE THREAD

**Issue by yanxiafu** [Meituan-Dianping/mpvue#332]
1.swiper 的change事件和current属性问题：当current属性设置为动态data的时候，来回切换快的时候时会有影响，感觉像死循环，来回跳
2.movable-area /movable-view标签使用时scale事件和:scale-value相互影响，不设置缩放完就会跳回:scale-value的值，同步scale事件回调的scale-value值又会闪顿很严重

附带问题：还有不用微信原生组件，自己写的touchmove事件很卡，就算节流了还是卡，真机很明显

以上问题基本都是属性和事件相互影响造成的，问题是不写属性很多效果没法使用，应该很多原生组件对应都会有这个问题，这个问题我看其他issue里面稍微有提及，望解答

**Comment by JasonDRZ** [comment]
使用swiper时请注意一些问题，微信官方文档是有说过这点的，不要用change事件去触发current字段的更新，这样很容易造成死循环。如果你是在做联动控制，建议使用另一个触发事件，animationend事件，这样应该是可以避免死循环的问题。这个事件是在交互动画完成后才执行的，所以不会马上改变current的值，造成循环阻塞（前提是你的额duration字段不为0）。

**Comment by JasonDRZ** [comment]
关于执行事件卡顿的问题，其主要原因是mpvue的分包Data控制原理造成的，如果你使用实时事件进行快速的视图数据传递，在你的$rout主数据入口数据量不大的情况下是感觉不到卡顿的。但是，一旦你引入大量数据时，你的事件流的快速执行，可能会导致数据的频繁更新。数据更新的传输解析过程会附带很大的性能损耗，所以会出现卡顿。
优化建议：将需要进行实时事件处理的结构抽离成一个独立的mpvue模块，这样mpvue会将模块数据与主页面数据进行模块划分，这样让当前模块在快速执行事件方法修改数据时，就只会修改和传输当前组件的事件数据，降低数据传输量，这样能明显提高性能降低卡顿的可能性。

**Comment by yanxiafu** [comment]
@JasonDRZ swiper的问题我是通过animationend去解决的 虽然慢点，但是能用，我的第2点问题却没有其他事件可以使用呀，有没有办法，谢谢

**Comment by JasonDRZ** [comment]
@yanxiafu movable-area这个scale的问题，如果你是想用scale事件来控制其他组件的scale效果的话，建议将字段分割开来，不要用当前movable-area的scale事件去设置当前组件的scale-value字段，这样就避免了事件循环。比如，m-area-a的scale事件是onScaleA，控制当前组件的scale-value字段为scaleA,m-area-b的scale事件是onScaleB，控制当前组件的scale-value字段为scaleB,让他们之间的控制字段进行对应控制，不要引用当前组件的scale-value字段来控制scale大小，这样就没有问题了。
