### ISSUE TITLE
无法自定义修改input  type为CheckBox的样式。。。

### ISSUE THREAD

**Issue by CWTgithub** [Meituan-Dianping/mpvue#333]
![wechatimg15](https://user-images.githubusercontent.com/21306982/39105011-c9ada45a-46e5-11e8-91e3-d0a19036b483.jpeg)
编译前后都没法控制input为CheckBox的样式问题，总是被原生的给覆盖着。。。

**Comment by aOrz** [comment]
建议去 https://developers.weixin.qq.com/home? 提问

**Comment by qq157788394** [comment]
姿势不对，不要试图去改原生checkbox的样式，而要把他隐藏掉。然后再重新加个view标签，v-if="item.checked"来控制选中和非选中的样式

**Comment by CWTgithub** [comment]
那也就是说在mpvue中别用<input  type="checkbox"/>,换个div重新写是吧？？

**Comment by McsNick** [comment]
可以参考 https://blog.csdn.net/qq_32584661/article/details/80225407
亲测 可用
