### ISSUE TITLE
v-bind:style的转换问题，求解！

### ISSUE THREAD

**Issue by cquptpei** [Meituan-Dianping/mpvue#336]
# [按照官方给出的格式书写v-bind:style，但是转换后的格式并不是官方给出的那种]

**问题复现步骤:**

官方给出的转换后的格式：
style=" {{'color:' + activeColor + ';' + 'font-size:' + fontSize + 'px' + ';'}}"
自己本地转换后的格式：
style="{{(fontSize + 'px')? 'font-size' : ' '}}"

**期望的表现:**

为什么我自己本地的转换和官方给出的不一致呢？

**Comment by mdsb100** [comment]
```
:style="{height: height+'px',marginTop:(-height*0.5)+'px',left: shareContainerLeft+'rpx', transform: 'scale(0.7)', backgroundColor: 'rgba(0,0,0,0.7)'}"
```

我的style这么写的，可以用。我并没有2层'{}'

**Comment by F-loat** [comment]
可能和 #197 是同一个问题，把你在 vue 文件中的写法也贴一下

**Comment by lessthanno** [comment]
应该是版本问题，update下吧

**Comment by aOrz** [comment]
更新下版本试下，如果还不可以再打开 issue
