### ISSUE TITLE
browserslist 不生效

### ISSUE THREAD

**Issue by hopperhuang** [Meituan-Dianping/mpvue#337]
rt

配置如下：
 "browserslist": [
    "> 1%",
    "last 2 versions",
    "not ie <= 8"
  ]
}

编译出来的文件并没有自动补全前缀
diplay:flex 并没有自动补全

**Comment by sideFlower** [comment]
好像是build后 才会有前缀的吧

**Comment by hopperhuang** [comment]
@sideFlower build之后也没有。
background:linear-gradient(red,blue);
这个属性并没有自动补全前缀。

**Comment by JasonDRZ** [comment]
这个需要在vue-loader.conf.js文件中添加postcss插件模块才能生效的，简单方法：
![image](https://user-images.githubusercontent.com/9544398/39113879-9ae9e082-470f-11e8-8d33-2e9b9f66ce07.png)
注意，autoprefixer需要你自己安装哈。

**Comment by hopperhuang** [comment]
@JasonDRZ 是可以了，但是这样子的化browserslist的存在意义是什么呢？

还是有，再问一个问题就是，为什么直接再postcss-loader里面配置auotprefixer做plugin为什么不行呢？

// utils.js 里面这样子写会报错。
  var postcssLoader = {
    loader: 'postcss-loader',
    options: {
      ident: 'postcss',
      sourceMap: true,
      plugins: [
        autoprefixer({
          browsers: [
            '> 1%',
            'last 2 versions',
          ],
        }),
      ]
    }
  }

**Comment by JasonDRZ** [comment]
这个你得去vue-loader的官方文档问下官方了，我也这样试过，没有生效。看了官方文档给的配置方式才晓得的。官方还可以支持postcss路径的设置：[vue-loader](https://vue-loader.vuejs.org/zh-cn/options.html#postcss)

**Comment by hopperhuang** [comment]
@JasonDRZ 好的，谢谢。

**Comment by JasonDRZ** [comment]
no problem

**Comment by aOrz** [comment]
![image](https://user-images.githubusercontent.com/6347990/39122786-7f9a9cb8-4728-11e8-9ac8-e1dee9cbc32f.png)
微信开发者工具有，上传代码时样式自动补全，为啥还要自己配？

**Comment by hopperhuang** [comment]
@aOrz 不抬杠，虚心请教，那browserslist开放这个配置接口干嘛呢，设计的时候是有什么其他特别的用意吗？

**Comment by aOrz** [comment]
@hopperhuang quickStart 是从 vue 的quickStart 改过来的，autoprefixer 之前是加上了的，后来觉得没必要就去掉了

**Comment by hopperhuang** [comment]
@aOrz 好的，明白了。
