### ISSUE TITLE
Cannot read property 'call' of undefined;at App onError function

### ISSUE THREAD

**Issue by CXY037** [Meituan-Dianping/mpvue#338]
# [问题简单描述]

**问题复现步骤:**

1. [第一步] 小程序远程调试
2. [第二步] 下拉页面

![_ _20180423150640](https://user-images.githubusercontent.com/2595427/39111578-2f00f678-4708-11e8-8bc3-06de5f06b168.png)

**Comment by xing00** [comment]
我也遇到了...

**Comment by csq121605366** [comment]
我也遇到了

**Comment by yuconora** [comment]
线上版本 多次出现这个问题。。。

**Comment by godpan** [comment]
我也遇到了，不知道有啥好的解决方案没有

**Comment by aOrz** [comment]
已发版解决

**Comment by sideFlower** [comment]
在微信报警群 还是会收到  Cannot read property 'call' of undefined;at App onError function的错误

**Comment by wuxiaolan91** [comment]
我也还是遇到了这个错.
时间: 2019 年 7 月 11 日

**Comment by sherpifer** [comment]
> 我也还是遇到了这个错.
> 时间: 2019 年 7 月 11 日

你好想问一下你解决了吗
