### ISSUE TITLE
Cannot read property 'call' of undefined;at App onError function

### ISSUE THREAD

**Issue by xing00** [Meituan-Dianping/mpvue#341]
# [问题简单描述]
真机调试，控制台出现标题报错，开发者工具不会

**问题复现步骤:**

1. 按照官网文档新建小程序
2. npm run dev之后，在开发者工具选择远程调试，然后滚动页面就会出现下图所示问题：
<img width="806" alt="2018-04-23 5 07 25" src="https://user-images.githubusercontent.com/7943928/39118238-85cbeb44-471b-11e8-82e3-25a7a4c2ccb2.png">

package.json如下(部分项目信息隐藏了)：
{
  "name": "my-project",
  "version": "1.0.0",
  "description": "A Mpvue project",
  "scripts": {
    "dev": "node build/dev-server.js",
    "start": "node build/dev-server.js",
    "build": "rimraf dist && node build/build.js"
  },
  "dependencies": {
    "mpvue": "^1.0.9"
  },
  "devDependencies": {
    "mpvue-loader": "^1.0.12",
    "mpvue-webpack-target": "^1.0.0",
    "mpvue-template-compiler": "^1.0.9",
    "portfinder": "^1.0.13",
    "postcss-mpvue-wxss": "^1.0.0",
    "px2rpx-loader": "^0.1.8",
    "babel-core": "^6.22.1",
    "glob": "^7.1.2",
    "webpack-mpvue-asset-plugin": "^0.0.1",
    "babel-loader": "^7.1.1",
    "babel-plugin-transform-runtime": "^6.22.0",
    "babel-preset-env": "^1.3.2",
    "babel-preset-stage-2": "^6.22.0",
    "babel-register": "^6.22.0",
    "chalk": "^2.0.1",
    "connect-history-api-fallback": "^1.3.0",
    "copy-webpack-plugin": "^4.0.1",
    "css-loader": "^0.28.0",
    "cssnano": "^3.10.0",
    "eventsource-polyfill": "^0.9.6",
    "express": "^4.14.1",
    "extract-text-webpack-plugin": "^2.0.0",
    "file-loader": "^0.11.1",
    "friendly-errors-webpack-plugin": "^1.1.3",
    "html-webpack-plugin": "^2.28.0",
    "http-proxy-middleware": "^0.17.3",
    "webpack-bundle-analyzer": "^2.2.1",
    "semver": "^5.3.0",
    "shelljs": "^0.7.6",
    "uglifyjs-webpack-plugin": "^1.2.4",
    "optimize-css-assets-webpack-plugin": "^2.0.0",
    "ora": "^1.2.0",
    "rimraf": "^2.6.0",
    "url-loader": "^0.5.8",
    "vue-style-loader": "^3.0.1",
    "webpack": "^2.6.1",
    "webpack-dev-middleware-hard-disk": "^1.10.0",
    "webpack-merge": "^4.1.0",
    "postcss-loader": "^2.0.6"
  },
  "engines": {
    "node": ">= 4.0.0",
    "npm": ">= 3.0.0"
  },
  "browserslist": [
    "> 1%",
    "last 2 versions",
    "not ie <= 8"
  ]
}

**尝试方法:**
1、在开发群里询问群友，一个群友回复，没有发现同样问题，本机node版本为7.7.4，同事的node版本为9.5.0
2、在同事的机器上跑，复现问题，排除机器原因
3、查看issus，发现同样的问题，升级mpvue, mpvue-template-compiler, mpvue-loader没有解决问题。

**Comment by aOrz** [comment]
同 #338 ，重复问题先关了
