### ISSUE TITLE
组件不能使用slot

### ISSUE THREAD

**Issue by wuqiuyude** [Meituan-Dianping/mpvue#343]
`<component>`
`    <div>`
`   </div>`
`</component>`
mpvue升级为1.0.9之后，自定义组件依然会报template not found，关键是有的时候会报，有的时候不会，很魔幻。

代码逻辑就这么简单，不知道是怎么回事
然后如果在slot里面分发的是自定义组件，无法在自定义组件上绑定自定义事件，会报Do not have handler in current page

**Comment by jyootai** [comment]
还是贴上代码吧, 这样更能提高定位和解决问题的效率

**Comment by cuijiemmx** [comment]
同上，就是最简单的写法，有时会报template not found，有时不会服，另外父组件修改了slot中的内容后，需要重新npm run dev才能生效..

**Comment by pcloth** [comment]
我测试了一样，组件如果复用，slot部分就可能出错，原因是因为之前组件样式问题，修改了webpack.dev.conf.js里的
```
new webpack.optimize.CommonsChunkPlugin({
      name: 'vendor',
      minChunks: function (module, count) {
        // any required modules inside node_modules are extracted to vendor
        return (
          module.resource &&
          /\.js$/.test(module.resource) &&
          module.resource.indexOf('node_modules') >= 0
        ) || count>=2
      }
    }),
```
之前组件样式错误，把尾部的||count>=2删掉之后。

所以，问题就来了，如果将count>=2删除掉之后，组件的样式没问题了，但是slot会有问题，保留之后，样式就会出问题。

最后，我还是选择了保留，把组件的样式写到了页面级或者公共级，来暂时解决这个问题。

期待各位老大尽快修复并hack出完成的slot-scope功能。感谢感谢。

**Comment by mdsb100** [comment]
#365

**Comment by mdsb100** [comment]
issue365 有临时解决方案，作者下一个版本会修复
