### ISSUE TITLE
怎么获取子组件实例

### ISSUE THREAD

**Issue by zengyuanqiu** [Meituan-Dianping/mpvue#346]
# [问题简单描述]

**问题复现步骤:**

1. [第一步]
2. [第二步]
3. [其他步骤...]

**期望的表现:**

[在这里描述期望的表现]

**观察到的表现:**

[在这里描述观察到的表现]

**屏幕截图和动态 GIF 图**

![复现步骤的屏幕截图和动态 GIF 图](图片的 url)

**Comment by zengyuanqiu** [comment]
用this.$refs.child获取不到子组件实例，有什么办法能获取到

**Comment by aOrz** [comment]
mpvue 升级到最新版试下？

**Comment by Javebean** [comment]
@aOrz 这个和电脑出问题了重启一下有什么不同？
