### ISSUE TITLE
关于mapGetters和mapMutations

### ISSUE THREAD

**Issue by PedroGao** [Meituan-Dianping/mpvue#35]
请问一下，我在使用vuex的mapGetters和mapMutations时报错了，是目前不支持吗？

**Comment by weineel** [comment]
应该是支持的。。我用的时候没有问题。

**Comment by aOrz** [comment]
如果问题还存在，麻烦提供下复现 demo

**Comment by PedroGao** [comment]
我描述一下，我没有在全局里面使用vuex，而是在mpvue官方的starter里面的counter组件进行修改，也就是说，store是局部的，仅在counter组件里面，而在使用mapGetter的时候，提示我找不到getters。
```js
// https://vuex.vuejs.org/zh-cn/intro.html
// make sure to call Vue.use(Vuex) if using a module system
import Vue from 'vue';
import Vuex from 'vuex';

Vue.use(Vuex);

const store = new Vuex.Store({
  state: {
    count: 0
  },
  getters: {
    count: state => state.count
  },
  mutations: {
    increment: state => {
      state.count += 1;
    },
    decrement: state => {
      state.count -= 1;
    }
  }
});

export default store;
```
我猜测的原因是，mapGetter会在全局找getters结果没有找到在counter组件里面定义的getters。
我尝试用vuex的module前缀找到getters
```js
...mapGetters(['root/count'])
```
但是依然没有找到，错误信息如下

> Cannot read property 'getters' of undefined;at pages/movies/movies page lifeCycleMethod onReady function
TypeError: Cannot read property 'getters' of undefined
    at VueComponent.mappedGetter (http://127.0.0.1:52262/appservice/static/js/vendor.js:6624:67)
    at Watcher.get (http://127.0.0.1:52262/appservice/static/js/vendor.js:2304:31)
    at Watcher.evaluate (http://127.0.0.1:52262/appservice/static/js/vendor.js:2408:27)
    at VueComponent.computedGetter [as root/count] (http://127.0.0.1:52262/appservice/static/js/vendor.js:2629:23)
    at http://127.0.0.1:52262/appservice/static/js/vendor.js:4834:25

**Comment by aOrz** [comment]
@PedroGao 提供下mpvue版本号？

**Comment by F-loat** [comment]
页面的 main.js 里实例化 vue 是有传入 store 吗

**Comment by PedroGao** [comment]
我在main.js这样初始化，报错

```js
const app = new Vue({
  store: store,
  render: h => h(App)
});
app.$mount();
```

> Cannot read property 'getters' of undefined;at pages/counter/counter page lifeCycleMethod onReady function
TypeError: Cannot read property 'getters' of undefined

版本依赖如下：

```bash
"mpvue": "^1.0.1",
"vuex": "^2.3.1"
````

**Comment by F-loat** [comment]
你装个 npm-check，先把模块都更新下吧，另外 render 这种写法好像不行，改成解构试试

**Comment by PedroGao** [comment]
仍然是不行，我用npm-check更新了一下mpvue相关的包，在main.js中用如下方式初始化:
```js
import Vue from 'vue';
import App from './index';
import store from './store';
const app = new Vue({ store: store, render: h => h(App) });
app.$mount();
````
初始化并没有报错，证明初始化成功了。但是在mapGetters使用后，获得的getters不是我在store.js中定义的getters而是整个store对象。

**Comment by F-loat** [comment]
不懂你是什么意思，

**Comment by PedroGao** [comment]
不好意思，难为你了。通过this.$store确实可以输出store，但是还是不能通过mapGetters取出getters。

**Comment by anchengjian** [comment]
不支持自定义 render 方法，可以试试这样

```javascript
import Vue from 'vue';
import App from './index';
import store from './store';

const app = new Vue({
    store,
    ...App
});

app.$mount();

```

**Comment by PedroGao** [comment]
这样会报错。

> pages/welcome/welcome.js 出现脚本错误或者未正确调用 Page()

**Comment by XIEJUNXIRUOFENG** [comment]
这个问题怎么解决，我在PC端写测试的拆开的vuex完全没问题，复制过来这边getters就找不到了
![image](https://user-images.githubusercontent.com/19369059/37634998-06de643a-2c34-11e8-9b2d-fa78e42a65e2.png)

**Comment by XIEJUNXIRUOFENG** [comment]
请问你解决了吗，我在main.js一引用store就报错

**Comment by PedroGao** [comment]
没有，我还是使用了最原始的store.commit来完成的

**Comment by Jackliu007888** [comment]
我遇到同样的问题。

**Comment by bigmeow** [comment]
将vuex挂在vue原型下

**Comment by HAIHAI211** [comment]
我已经解决。
原因：mpvue有一个坑，不能直接在new Vue的时候传入store
措施：需要将vuex挂在vue原型下，Vue.prototype.$store = store

**Comment by aetherwu** [comment]
> 我已经解决。
> 原因：mpvue有一个坑，不能直接在new Vue的时候传入store
> 措施：需要将vuex挂在vue原型下，Vue.prototype.$store = store

求老师提示下挂好原型后，在vue里面要怎么调用 state/commit .....  还是不懂……

**Comment by tingzhong666** [comment]
> 我已经解决。
> 原因：mpvue有一个坑，不能直接在new Vue的时候传入store
> 措施：需要将vuex挂在vue原型下，Vue.prototype.$store = store

挂载后，用不了 commit
