### ISSUE TITLE
mpvue1.0.9 新起项目，手指动作都会报错

### ISSUE THREAD

**Issue by bb54661447** [Meituan-Dianping/mpvue#350]
在开发模式中，远程调试，在手机端做页面的上拉下拉，均报错，
![image](https://user-images.githubusercontent.com/13047160/39173250-cb47a846-47d6-11e8-9b62-a283ab4b0671.png)

**Comment by 704826318** [comment]
我也是这个问题，现在是不管什么页面只要触发页面滚动事件就报错，很受打击
建议题主标题改的明确一点

**Comment by aOrz** [comment]
问题同 #338 ，请不要开重复的 issue，预计下个版本修复
