### ISSUE TITLE
mpvue 1.0.9 不支持具名slot

### ISSUE THREAD

**Issue by teapot-py** [Meituan-Dianping/mpvue#351]
# [问题简单描述]

slot这个功能还是很有必要的，但是看官方文档说目前不支持slot
![image](https://user-images.githubusercontent.com/10125102/39176559-af2f0538-47df-11e8-96b0-717f581ff083.png)
但是自己试了一下，发现目前好像只有具名slot是不支持的。

![image](https://user-images.githubusercontent.com/10125102/39176665-eb12e006-47df-11e8-9065-665126faad24.png)

**Comment by anchengjian** [comment]
抱歉，具名也是支持的，支持不支持 scoped ，针对你这出问题可以提供一个 demo 么？

**Comment by pcloth** [comment]
具名slot是支持的，修改slot相关代码后，需要重新运行npm run dev。

**Comment by teapot-py** [comment]
确实是支持具名slot的。但是在加入新的具名slot时，需要重新运行 npm run dev

**Comment by mdsb100** [comment]
#365 不是不支持，时而好时而不好。。。

**Comment by mdsb100** [comment]
issue365 有临时解决方案，作者下一个版本会修复

**Comment by FAOfao931013** [comment]
`"mpvue-loader": "^1.0.13" `
已经解决这个问题了

**Comment by Vultur** [comment]
- grid-item.vue
`
<template>
  <div class="weui-grid" :style="style" @click="onClick">
    <div class="weui-grid__icon">
      <slot name="icon">
        <img :src="icon" />
      </slot>
    </div>
    <p class="weui-grid__label">
      <slot name="label">
        <span v-html="label"></span>
      </slot>
    </p>
    <slot></slot>
  </div>
</template>
`

- demo.vue
`
<grid-item>
  <img slot="icon" src="data:image/png;base64," />
  <span slot="label">Vue</span>
</grid-item>`

- 结果

slot=label 正常，slot=icon 没有渲染
