### ISSUE TITLE
getCurrentPages获取不到其他页面的信息

### ISSUE THREAD

**Issue by chenyaoyi88** [Meituan-Dianping/mpvue#354]
# [问题简单描述]

我的 a界面有一个重置 a 页面的方法，然后我在 b 页面想通过  getCurrentPages 获取其 a 页面，调用 a 的重置方法重置 a ，为什么在mpvue里面的  getCurrentPages 能找到 a 但是没有 a 的所有方法和属性？原生是有的。

或者是有什么其他的方法可以做到，用 vuex的话，回到 a 页面的时候会看到瞬变的一刻，体验非常不好。

**Comment by anchengjian** [comment]
1. mpvue 框架会对 page 对象进行一个包装，不是简单的拼叠，所以找不到是正确的，只有 vue 的方法能找到对应的。
2. 瞬变是已知的一个不足，我们在思考调整优化整个生命周期映射关系，请耐心等待一下。

**Comment by chenyaoyi88** [comment]
@anchengjian 找了一晚上 vue 文档和去测试了都没找到 vue 中对应小程序的 getCurrentPages 方法，在 a 页面点进去的 b 页面中，在 b 的 this 中找 $parent $children $root 都没找到 a ，最后用 eventbus 让 a 监听从 b 发过来的消息后调用方法改变页面，也是从 b 返回 a 页面的一瞬间才改变，表现和 vuex 一样露馅了。
