### ISSUE TITLE
关于构建目标的一些疑惑和问题

### ISSUE THREAD

**Issue by hopperhuang** [Meituan-Dianping/mpvue#355]
由于需求，需要用到crypto这种node的原生库。

但是吧crypto引入后，打印发现，好多方法是undefined的。

比如这些：
createHash,  createHmac,  createSign,  createVerify

是因为构建目标的问题，把这些方法都给省略掉了吗？还是怎么回事呢？

**Comment by anchengjian** [comment]
小程序环境是没有 Node.js 相关能力的，所以也不会有这些方法，也确实跟 target 有一些关系。

可以试试从 npm 上下载其他 crypto 相关的加密库，然后再使用。
