### ISSUE TITLE
建议：官方文档应该补全微信开发者工具的配置

### ISSUE THREAD

**Issue by dlmys** [Meituan-Dianping/mpvue#36]
按照quickstart生成的项目。微信开发者工具报错找不到app.js。查明原因是关闭了ES6 转 ES5。
建议，由于之前很多开发者会习惯以下配置
  - **关闭** ES6 转 ES5
  - **关闭** 代码压缩上传
  - **关闭** 上传代码时样式文件自动补全
  - **开启** 开发环境不校验请求域名、TLS版本以及HTTPS证书

可能会导致项目不能初始化成功。所以希望官方文档能写明这些不一样的配置。避免大家踩坑。

**Comment by aOrz** [comment]
已经通过在项目目录增加 project.config.json 解决，感谢您的建议
