### ISSUE TITLE
子组件中使用slot。启动时会报找不到模板，修改目录后编译却找到了。

### ISSUE THREAD

**Issue by LeftShoot** [Meituan-Dianping/mpvue#361]
# [问题简单描述]
 **在页面index.vue使用了子组件ActList.vue
 **在ActList.vue引用了子组件EwPaginator.vue，并写了<EwPaginator><slot></slot></EwPaginator>这种格式
 **在npm run dev 的时候，会提示 Template "data-v-18c3e4ec-slotList-0" not found.

 **但最神奇的是。我修改了ActList.vue的目录地址之后。编译又成功了。
    例如原先目录是 '../../components/ActList.vue'
    我复制出一个叫components2的文件夹
    修改指向components2即目录为 '../../components/ActList.vue'，保存编译。就不会报错了
    然后指回components。也不会报错。

**Comment by mdsb100** [comment]
关联 #365

**Comment by mdsb100** [comment]
issue365 有临时解决方案，作者下一个版本会修复
