### ISSUE TITLE
$root.mp.option.query不正确的问题

### ISSUE THREAD

**Issue by hopperhuang** [Meituan-Dianping/mpvue#364]
# [问题简单描述]

问题一：同页面跳转，从a?id=1 跳转到 a?id=2，然后从a?id=2回退到a?id=1, query参数中的id仍然是2，而不是1，可稳定复现。

问题二：从id=2的页面回退到id=1的页面后，调试工具的appdata栏，只显示空白页。什么数据追踪也没有。

**问题复现步骤:**

1. [第一步]
2. [第二步]
3. [其他步骤...]

**期望的表现:**

[在这里描述期望的表现]

**观察到的表现:**

[在这里描述观察到的表现]

**屏幕截图和动态 GIF 图**

![复现步骤的屏幕截图和动态 GIF 图](图片的 url)

**Comment by hopperhuang** [comment]
问题解决了，可以通过getCurrrentPages方法来获取当前所有的页面盏。最后一个就是当前页面的信息。
具体可以看小程序的这里的文档：https://developers.weixin.qq.com/miniprogram/dev/framework/app-service/route.html

我觉得在这个bug解决之前，都可以先用这个方法去追踪页面路由的信息。如果觉得可行的话，麻烦作者在文档里面提一下，让大家知道一下这个坑。

**Comment by anchengjian** [comment]
我建议直接给文档提 PR 😂

**Comment by hopperhuang** [comment]
@anchengjian 我懒呀。。。。。还是你们来吧。。。

**Comment by F-loat** [comment]
类似于 #140， 可以用同样的方法解决

**Comment by monw3c** [comment]
我是暂时这么解决
