### ISSUE TITLE
关于slot转码后为template？

### ISSUE THREAD

**Issue by iSword007** [Meituan-Dianping/mpvue#367]
我用Vue写了个组件，里面包含具名slot
cell-item.vue  代码如下

<img width="775" alt="wx20180426-160527 2x" src="https://user-images.githubusercontent.com/18645596/39293705-3273b370-496c-11e8-8af9-ec121b13ca2b.png">

结果slot并不可用，我查了了dist里面的转码，发现slot标签被转成template标签，如：

wxml文件

<img width="764" alt="wx20180426-160650 2x" src="https://user-images.githubusercontent.com/18645596/39293708-32f18c0a-496c-11e8-9ffc-700a21fa8e46.png">

请问如何解决？

**Comment by mdsb100** [comment]
#365

**Comment by iSword007** [comment]
我看了下微信小程序的官方文档，文档现在有专门的component自定义组件，mpvue用的是这个么，看转换后的源码感觉不太像。。。
<img width="986" alt="wx20180426-165717 2x" src="https://user-images.githubusercontent.com/18645596/39296264-033ac66e-4973-11e8-8f8e-2efa8a73b232.png">
