### ISSUE TITLE
页面里的created声明周期里为什么会在小程序载入时就运行？

### ISSUE THREAD

**Issue by shen-lan** [Meituan-Dianping/mpvue#368]
1.官网demo
2.我在logs/index.vue里 created生命周期里写console.log()，奇怪的是在小程序载入进来就执行了，然而这并不是首页啊。
3.是我使用姿势不对吗？谢谢

**Comment by jyootai** [comment]
单纯的在 vue 中 created 的执行时期是在实例创建完成后, 而在mpvue 中 每个页面的 beforeCreate 和 created 在程序启动时都会立即被同时调用,  这跟打包编译成目标代码有关, 你的页面都有一个main.js, 引用实例创建后beforeCreate 和 created 都会相继执行
