### ISSUE TITLE
关于mpvue px转rpx问题

### ISSUE THREAD

**Issue by xiaowuHgh** [Meituan-Dianping/mpvue#369]
小程序使用到雪碧图，background-position 中的px转为rpx会导致每个手机上定位到的背景图片不一致

**Comment by aOrz** [comment]
使用 /*px*/ 注释可以使 px 不被转为 rpx

**Comment by 634323580** [comment]
使用大写 PX

**Comment by superxiaobin** [comment]
// 改px2rpx包里的lib/px2rpx.js文件
return value.replace(pxGlobalRegExp, function ($0, $1) {
    if ($1 == 1) {
      return '1px'
    } else {
      return type === 'px' ? getValue($1 * dpr / config.baseDpr) : getValue($1 / config.rpxUnit);
    }
  });

**Comment by skyflyscroll** [comment]
楼上的方法，内联样式可以不转换成rpx，但是style里面的依然会转换成rpx啊～@superxiaobin

**Comment by skyflyscroll** [comment]
谢谢
