### ISSUE TITLE
【bug】可能是slot作用域处理上一个比较大而且重要的bug。wepy也有类似问题。

### ISSUE THREAD

**Issue by dlmys** [Meituan-Dianping/mpvue#37]
首先我们知道在使用slot插槽的时候按照vue的原则是：被分发的内容会在父作用域内编译。
然后看下面一个场景：

父组件模板:
`
\<template>
    \<type-group v-for="(item, index) in questionTypeMap" :key="index">
      \<div>
        \<p>{{ parentMsg }}\</p>
        \<p>{{ item}} {{ index }}\</p>
      \</div>
    \</type-group>
\</template>

    data () {
      return {
        parentMsg: '我是父组件的数据',
        questionTypeMap: [
          {
            name: 'choice',
            zhName: '选择题'
          },
          {
            name: 'fillin',
            zhName: '填空题'
          },
          {
            name: 'solution',
            zhName: '解答题'
          }
        ]
     }
`

子组件模板: (type-group)
`
\<template>
  \<div class="type-group">
     \<slot>\</slot>

  \</div>
\</template>
`

呈现结果：
只能看到 parentMsg: '我是父组件的数据',（这点相比wepy而言在slot分发时做了作用域优化处理）
看不到v-for循环出来的item和index。（wepy repeat出来有同样问题。而且wepy 使用slot时作用域更混乱）

**Comment by anchengjian** [comment]
http://mpvue.com/mpvue/#vue_1 暂不支持 scoped Slot（scoped 暂时还没做支持）

**Comment by HuskyToMa** [comment]
这个不是scoped的问题吧？而是在v-for的当前作用域中找不到这个值？使用slot的用的是父组件的数据而不是子组件的数据
