### ISSUE TITLE
如何在mpvue 中 input如何支持原生 EventHandle

### ISSUE THREAD

**Issue by leon570** [Meituan-Dianping/mpvue#370]
在xxx.vue 中 使用  input 标签 使用 bindconfirm EventHandle ,  提示未定义 

**问题复现步骤:**

1. <(和谐)input type="text" bindconfirm="test" (和谐)i/>
2. 在methods 或者 export default 中 定义 test() {console.log('用户按下了完成按钮')}
3. 在预览的页面 点击输入框 调出 键盘 ,输入 文本, 按下完成

**期望的表现:**

期望 控制台 输出 ‘用户按下了完成按钮’

**观察到的表现:**

返回 [publib]:17 Do not have test handler in current page

**Comment by F-loat** [comment]
vue 中通过 `@事件名` 或 `v-bind:事件名` 来绑定事件

**Comment by leon570** [comment]
sor 我没表达好 我想用的是 小程序 原生 input 组件的 bindconfirm 事件 
![image](https://user-images.githubusercontent.com/20178214/39301437-a41390e4-4981-11e8-8433-03985b2b53ee.png)
是小程序的 input 组件中的‘ bindconfirm’ EventHandle 用于监听 用户 键盘的 点击“完成”事件 
https://developers.weixin.qq.com/miniprogram/dev/component/input.html

**Comment by F-loat** [comment]
confirm 就是事件名

**Comment by aOrz** [comment]
可以看下文档： http://mpvue.com/mpvue/#_13

**Comment by leon570** [comment]
thx 这个 是 我自己没有 仔细阅读文档 的问题 , 谢谢 各位

**Comment by fengweihuan** [comment]
一样的问题 我咋弄不了啊

**Comment by cleverboy32** [comment]
input @focus="focusHandler" 触发 = =
