### ISSUE TITLE
引入融云的小程序sdk总报路径错误

### ISSUE THREAD

**Issue by ifuner** [Meituan-Dianping/mpvue#372]
# [问题简单描述]

**问题复现步骤:**
![image](https://user-images.githubusercontent.com/25742540/39307066-622ca022-4994-11e8-8954-f8e706d899fa.png)
![image](https://user-images.githubusercontent.com/25742540/39307081-7110e31e-4994-11e8-8bc1-a7aa91453082.png)

![image](https://user-images.githubusercontent.com/25742540/39307046-56fbad56-4994-11e8-966c-0216508b004b.png)

1. [第一步]
2. [第二步]
3. [其他步骤...]

**期望的表现:**

[在这里描述期望的表现]

**观察到的表现:**

[在这里描述观察到的表现]

**屏幕截图和动态 GIF 图**

![复现步骤的屏幕截图和动态 GIF 图](图片的 url)

**Comment by ifuner** [comment]
我在index.vue中引入了一个 require("../../utils/RongIMLib.xiaochengxu-1.0.0.js")（路径是对的）然后这个RongIMLib.xiaochengxu-1.0.0.js里面又require("./protobuf-2.1.6.js").protobuf 这个js。但是就是报错了

**Comment by aOrz** [comment]
protobuf-2.1.6.js 放什么地方了，建议直接写个demo 发过来，不然解决问题很低效，而且这种问题不是 mpvue 的问题，自己也可以解决的

**Comment by ifuner** [comment]
[demo.zip](https://github.com/Meituan-Dianping/mpvue/files/1953710/demo.zip)

**Comment by ifuner** [comment]
发个个文件，麻烦看看喽！因为这个是小程序的sdk，所以我使用mpvue报了这个错

**Comment by aOrz** [comment]
参考 #359 
![image](https://user-images.githubusercontent.com/6347990/39342817-607b0d40-4a0c-11e8-97a5-127eb5c4752b.png)

**Comment by ifuner** [comment]
求指教，没理由我的windows上不行吧

**Comment by aOrz** [comment]
在我这只会报 
```
This dependency was not found:

* fs in ./src/utils/protobuf-2.1.6.js
```
参考 #359 就解决了
