### ISSUE TITLE
页面配置后找不到对应的WXML文件

### ISSUE THREAD

**Issue by caicf** [Meituan-Dianping/mpvue#374]
VM1616:2 未找到 app.json 中的定义的 pages "pages/complain/main" 对应的 WXML 文件

**Comment by aOrz** [comment]
看看 dist 目录下有没有生成，没有的话贴出来代码看下
下次提 issue 请按照 issue 模板组织 issue 内容

**Comment by sideFlower** [comment]
我也遇到这个问题了;重新npm run dev就好了

**Comment by aOrz** [comment]
新增加页面是需要重新 run dev 的，这个在文档中有说明 http://mpvue.com/qa/#_2，问题我先关了，如果还没解决，再重新打开吧

**Comment by sideFlower** [comment]
对的 记得在文档哪个地方看到过
