### ISSUE TITLE
mpvue无法支持v-html指令

### ISSUE THREAD

**Issue by alwaysRemember** [Meituan-Dianping/mpvue#377]
# [问题简单描述]
在项目中我们需要使用富文本来书写某段介绍，但是尝试后发现不能使用v-html（数据是带HTML标签等等），请问有什么可以代替的方法么。
**问题复现步骤:**

1. [第一步]
2. [第二步]
3. [其他步骤...]

**期望的表现:**

[在这里描述期望的表现]

**观察到的表现:**

[在这里描述观察到的表现]

**屏幕截图和动态 GIF 图**

![复现步骤的屏幕截图和动态 GIF 图](图片的 url)

**Comment by F-loat** [comment]
1.0.9 起 v-html 会转为 rich-text 组件，如果不能满足需求的话可以使用 mpvue-wxParse

**Comment by aOrz** [comment]
因为小程序的限制，v-html 目前不能支持
