### ISSUE TITLE
app级别的生命周期在windows环境下不运行。

### ISSUE THREAD

**Issue by hopperhuang** [Meituan-Dianping/mpvue#378]
app级别的声明周期，created, onlaunch等，在windows环境下不执行。

**Comment by cxh1991** [comment]
怎么复现呢 代码都是正常写法   
在mpvue  app.vue里面这样写 无法执行 生命周期 都不行 估计是电脑原因
onLaunch(){
   console.log(2)
  },

**Comment by zxrliuyan** [comment]
我也是遇到这种情况

**Comment by aOrz** [comment]
长时间未提供更多信息，无法定位问题，先将问题关闭

**Comment by zhangruinian** [comment]
遇到 同样问题
