### ISSUE TITLE
关于组件的bug

### ISSUE THREAD

**Issue by jencia** [Meituan-Dianping/mpvue#38]
在组件内使写了样式，一个页面调用这个组件没问题，但两个和两个以上页面调用这个组件，这个组件的样式将会失效，将组件样式移到全局样式App.vue下能解决这问题，但这样做不合理，希望这个问题能得到解决。

**Comment by aOrz** [comment]
参考 https://github.com/Meituan-Dianping/mpvue/issues/7，会尽快解决
