### ISSUE TITLE
有tab 时 onReachBottom 不触发

### ISSUE THREAD

**Issue by supwjm** [Meituan-Dianping/mpvue#381]
# [问题简单描述]
在有tab选项卡的页面，为了使页面代码较为简洁，分成不同组件写不同tab内容，发现onReachBottom不触发（已经配置了enablePullDownRefresh：true）,无论放在组件中，还是放在父级页面，都不触发

**问题复现步骤:**

假设有下面优惠券组件list.vue

在list.vue 页面配置enablePullDownRefresh：true

<div class="container">
     
      <ul>
            <li>已使用</li>
           <li>未使用</li>
       </ul>

      <div class="coupon-list" >
        
        <unused v-if="tabs.selectedId == 'unused'"/>
        <used v-if="tabs.selectedId == 'used'"/>
      </div>
  </div>

无论在组件unused.vue 写onReachBottom，还是在list.vue 写onReachBottom，上拉触底的时候都不触发

**期望的表现:**

希望在子组件中触发onReachBottom

**观察到的表现:**

无论在组件unused.vue 写onReachBottom，还是在list.vue 写onReachBottom，上拉触底的时候都不触发

**Comment by F-loat** [comment]
onReachBottom 应该是页面才会触发吧，可以尝试在页面中调用子组件的方法

**Comment by supwjm** [comment]
我在页面中试过了，也不能触发，如果内容不写到子组件中是ok的

**Comment by F-loat** [comment]
你组件有设置整体高度或使用 scroll-view 没

**Comment by supwjm** [comment]
没设置高度，直接使用div,其他没有tab的情况下使用div是没问题的

**Comment by supwjm** [comment]
经排查，必须在页面最外层使用scroll-view并设置高度才会触发，页面onReachBottom和子组件onReachBottom都能触发，如果scroll-view不是最外层元素，则无法触发

**Comment by supwjm** [comment]
还是会有bug，滚动到只触发一次拉取数据，下次触发，需重新滚动到顶部，再滚动到底部，才触发

**Comment by supwjm** [comment]
估计是应为设置的是最外层scroll-view 和高度

**Comment by supwjm** [comment]
解决了，在最外层用scroll-view，scroll-view不用设置高度，也不能设置100%
