### ISSUE TITLE
后续有支持支付宝小程序的计划么

### ISSUE THREAD

**Issue by cd2001zxm** [Meituan-Dianping/mpvue#382]
# [问题简单描述]

**问题复现步骤:**

1. [第一步]
2. [第二步]
3. [其他步骤...]

**期望的表现:**

[在这里描述期望的表现]

**观察到的表现:**

[在这里描述观察到的表现]

**屏幕截图和动态 GIF 图**

![复现步骤的屏幕截图和动态 GIF 图](图片的 url)

**Comment by mdsb100** [comment]
需求池第四个
![wechatimg143](https://user-images.githubusercontent.com/2350193/39356901-cfa78b76-4a43-11e8-973f-bb7e81d54b30.jpeg)

**Comment by aOrz** [comment]
问题同 #100 ，提问前请看下有没有相同的问题
