### ISSUE TITLE
配置了tab选项卡不生效

### ISSUE THREAD

**Issue by mohong** [Meituan-Dianping/mpvue#384]
在src/main.js配置了选项卡信息不生效：

**问题复现步骤:**

1. [第一步]
在src/main.js配置了选项卡信息：
![](http://ob9qd20l4.bkt.clouddn.com/image-WX20180427-174833@2x.png)

2. [第二步]
查看效果以及编译后的代码，发现没有选项卡出现，且编译代码正确：

**期望的表现:**

正确配置选项卡后页面出现选项卡信息

**观察到的表现:**

正确配置选项卡后页面没有出现选项卡信息

![](http://ob9qd20l4.bkt.clouddn.com/image-WX20180427-175236@2x.png)

**Comment by aOrz** [comment]
> 且编译代码正确：

去 https://developers.weixin.qq.com/ 问下？

**Comment by mohong** [comment]
我用微信编辑器新建了一个小程序项目，把刚才编译过的app.json中的tabBar字段内容拷贝过去，会生效。。。但是在mpVue项目中确实看不到效果，也不报错。。。太神奇了。。。
