### ISSUE TITLE
微信小程序码使用接口B生成的, this.$root.$mp.query,能拿到scene?

### ISSUE THREAD

**Issue by QiYunMeng1126** [Meituan-Dianping/mpvue#388]
接口A是把参数直接拼在path后面的,而接口B是scene给参数的,这两种有点不一样.还有就是接口A有合适的测试方式,接口B,没找到合适的测试方式.大佬,帮看看呗!

**Comment by F-loat** [comment]
scene 是指从外部直接进入小程序时带的参数吗，在 onLunch 或者 onShow 里获取的吧好像，开发工具可以模拟这种情况的

**Comment by QiYunMeng1126** [comment]
不是这个意思,后台调用B类接口传一个key是scene, value是XXXX的参数,生成小程序码.我扫码进入小程序的时候需要拿到这个value值,处理对应的事情. https://developers.weixin.qq.com/miniprogram/dev/api/qrcode.html

**Comment by F-loat** [comment]
差不多吧，这个原生应该就是在 onLunch 或者 onShow 里获取，$mp 里有没有封装不太清楚，你可以试一下

**Comment by F-loat** [comment]
![image](https://user-images.githubusercontent.com/16759376/39394187-72dbe888-4b01-11e8-8327-b06df042e2df.png)
开发工具可以直接测的

**Comment by steveleeh** [comment]
二维码扫进来，this.$root.$mp.query.scene 是可以拿到这个值的

**Comment by QiYunMeng1126** [comment]
好的,谢谢各位大佬.

**Comment by MarcWong** [comment]
话说各位大佬有没有遇到初次扫码进入小程序无法读取二维码的场景值的问题，再次扫码又可以读取
