### ISSUE TITLE
npm run dev和npm run build 后生成的项目不一致

### ISSUE THREAD

**Issue by sideFlower** [Meituan-Dianping/mpvue#390]
![image](https://user-images.githubusercontent.com/23654129/39392986-3c10bf90-4af2-11e8-8a2b-9d8cd49fc52d.png)

**Comment by aOrz** [comment]
webpack 配置是怎么配的，run build 之后程序运行时遇到了什么问题？

**Comment by sideFlower** [comment]
webpack 没有动啊，都是项目生成时都配置，
在window上 build后报错缺少counter/main.wxss  手动建立这个文件又可以了， 
在Mac上 直接报错，但是没有报错信息。。。。

 就算 在src/main.js 中 pages:[] 中没有配置 'pages/counter/main'   build 后 还是会报这种错误；
