### ISSUE TITLE
less 文件中@font-face使用字体文件的相对地址总是404；

### ISSUE THREAD

**Issue by Jandysang** [Meituan-Dianping/mpvue#392]
# [问题简单描述]

![image](https://user-images.githubusercontent.com/5569884/39394739-189505f6-4b08-11e8-8e43-b2efbed0a2be.png)

![image](https://user-images.githubusercontent.com/5569884/39394784-9e7a1008-4b08-11e8-9264-826ffd79bca6.png)

**Comment by F-loat** [comment]
试下 `~@/assets` 这种，另外要把 webpack 配置里的 limit 调到足够大，小程序里只能使用 base64 编码后的

**Comment by F-loat** [comment]
还不行的话，就得手动先转下 base64 了
