### ISSUE TITLE
select 组建编译问题

### ISSUE THREAD

**Issue by SongOfSpring** [Meituan-Dianping/mpvue#393]
# [问题简单描述]
select组建编译时<option>成了<view class="_option data-v-48cbe20c"> 
**问题复现步骤:**
文档说几乎全支持官方文档的表单控件绑定，建议选择picker  ，我用的是vue的select demo然后测试发现展示了所有选项  dist编译的有问题
1. [第一步]
2. [第二步]
3. [其他步骤...]

**期望的表现:**

leader希望能够尽可能复用代码。。。。所以怎么这个能不用picker么？

**观察到的表现:**
见图片
``
**屏幕截图和动态 GIF 图**
![image](https://user-images.githubusercontent.com/17442685/39395606-f8cb3776-4b12-11e8-86da-c5310f7b0cf8.png)
![image](https://user-images.githubusercontent.com/17442685/39395613-02914fde-4b13-11e8-9c3c-4c31f4c1f2d5.png)
![image](https://user-images.githubusercontent.com/17442685/39395624-0b1a561e-4b13-11e8-9412-90d9ef947a5d.png)

![复现步骤的屏幕截图和动态 GIF 图](图片的 url)

**Comment by webHello** [comment]
我也遇到了这个问题

**Comment by songziyang** [comment]
请问楼主解决了吗？
