### ISSUE TITLE
如何清除小程序button组件的默认样式，比如边框

### ISSUE THREAD

**Issue by strawbreey** [Meituan-Dianping/mpvue#394]
# [问题简单描述]

**问题复现步骤:**
mpvue会把`button`的元素选择器编译成类选择器`_button`,导致无法清除微信小程序的默认样式

**期望的表现:**
1. 清除微信小程序默认样式
2或者`postcss-mpvue-wxss`能不把 `button`  元素选择器 编译成 类选择器

**观察到的表现:**
无法清除微信小程序button的默认样式，比如边框

**屏幕截图和动态 GIF 图**

![复现步骤的屏幕截图和动态 GIF 图](图片的 url)

**Comment by aOrz** [comment]
对于小程序和 web 都有的标签名称后续不会把 button 元素选择器 编译成 类选择器

**Comment by strawbreey** [comment]
问题已解决，引入bootstrap的时候，会默认给button是appearance属性。移除即可
