### ISSUE TITLE
组件间循环引用

### ISSUE THREAD

**Issue by Zhangjd** [Meituan-Dianping/mpvue#396]
# [问题简单描述]

代码中，需要进行类似于下面的引用方式，A和B组件是循环引用的关系：

A组件
```
<A>
  <B />
</A>
```

B组件
```
<B>
  <A />
</B>
```

参照https://cn.vuejs.org/v2/guide/components.html#%E7%BB%84%E4%BB%B6%E9%97%B4%E7%9A%84%E5%BE%AA%E7%8E%AF%E5%BC%95%E7%94%A8  ，我在A组件的beforeCreate生命周期钩子才去注册B组件，然后发现在web环境下正常，在mpvue小程序下面不能正常显示B组件。

**Comment by F-loat** [comment]
小程序不支持循环引用

**Comment by Zhangjd** [comment]
是暂未支持还是无法实现？或者以后能通过注册全局组件解决吗

**Comment by F-loat** [comment]
小程序方面不支持的话应该是无法支持了，使用 mpvue 也是要预先编译出 wxml 文件作为 template 的
