### ISSUE TITLE
怎么跳转至外部链接？

### ISSUE THREAD

**Issue by liubin915249126** [Meituan-Dianping/mpvue#399]
从小程序里面直接跳转至外部链接比如google?

**Comment by kala888** [comment]
不太准确的来说是不能的，小程序本身就不让这么干。除非你在即搭建一个代理服务器，在后台转发数据，是可以的，而且还是用到webview

**Comment by aOrz** [comment]
https://developers.weixin.qq.com/miniprogram/dev/component/web-view.html 目前只能跳业务域名

**Comment by liubin915249126** [comment]
看了下，目前只支持企业认证的可以。
