### ISSUE TITLE
如何配置less？？

### ISSUE THREAD

**Issue by a526059306** [Meituan-Dianping/mpvue#40]
webpack.base.config.js配置了less-loader后，控制台还是说没有less模块

**Comment by falost** [comment]
你还需要安装下less的模块哦

**Comment by ToyYan** [comment]
`npm i less -D`

**Comment by anchengjian** [comment]
不需要任何配置，只需要 `npm i less less-loader --save`，在 .vue 文件中添加 <style lang="less"></style> 的样式然后启动既可。

如果需要在 js 中用 less ，则还需要在 `build/webpack.base.config.js` 中添加 less 相关的rule。

**Comment by Stupidism** [comment]
@anchengjian 现在貌似无法在scoped style中使用`@import './mixins.less'` 这样的语法. 请问如何才能做到呢. 我试了试, 自己配的less和mpvue的cssLoaders貌似有冲突

**Comment by xiaowuzei** [comment]
@Stupidism 这个问题解决了嘛？

**Comment by Stupidism** [comment]
@xiaowuzei 我想了一个workaround 曲线救国

比如你想要用.max-len() 这个mixin
就声明一下  
```less
// mixins.less
.max-len-2{
  .max-len(2);
}
```
然后就能在vue里面用这个class了, 但是像变量什么的还是没法复用

**Comment by doinbean** [comment]
less中如何使用@impotr 以及 less @常量的写法
