### ISSUE TITLE
同时引入子组件样式失效

### ISSUE THREAD

**Issue by xiaowuzei** [Meituan-Dianping/mpvue#403]
这有一个子组件A, 父组件B引用组件A木有问题，然后父组件C引入组件A 只是单纯的import引入，此时发现B中的子组件A样式不生效了。

**Comment by aOrz** [comment]
看下新版 quickStart，配置下 webpack-mpvue-asset-plugin https://github.com/mpvue/mpvue-quickstart/blob/master/template/build/webpack.base.conf.js#L109
