### ISSUE TITLE
多个页面的created事件在首页被一次性触发

### ISSUE THREAD

**Issue by RenShine** [Meituan-Dianping/mpvue#405]
# [问题简单描述]
我任何一个页面写的的created事件都会在首页触发 不知道为什么
**问题复现步骤:**

1. 新建多个pages
![image](https://user-images.githubusercontent.com/6385962/39562436-363c6ec6-4ede-11e8-9f2f-096f13f978f7.png)

2. 每个pages的created里面都打上一句console
![image](https://user-images.githubusercontent.com/6385962/39562445-44651818-4ede-11e8-818e-9248b0658d22.png)
![image](https://user-images.githubusercontent.com/6385962/39562449-4dfbd20e-4ede-11e8-88ff-979eca76963f.png)
![image](https://user-images.githubusercontent.com/6385962/39562450-55d07c6e-4ede-11e8-892f-4e262c4b9e72.png)

**期望的表现:**
首页只输出 this is Index

**观察到的表现:**

![image](https://user-images.githubusercontent.com/6385962/39562466-6ce867ea-4ede-11e8-96ec-d6324be23ec3.png)

**Comment by RenShine** [comment]
改成onload可以实现我想要的效果  但是官方文档不推荐使用onload

**Comment by F-loat** [comment]
mounted 和 onload 对应

**Comment by F-loat** [comment]
#167 #368

**Comment by vinceok** [comment]
我感觉这样十分不合理，一进小程序把所有页面的created方法都执行了，再进某个页面就不会执行。所以我都写在onLoad里

**Comment by Rem486** [comment]
“一进小程序把所有页面的created方法都执行了”  
这样的话，是不是第一进入小程序的时候就会把所有代码都请求到本地

**Comment by aOrz** [comment]
@Rem486 小程序的代码除了分包之外都是一次下载的

**Comment by JayLee2** [comment]
@aOrz 我把created换成mounted就可以了，但是我想了解一下为什么刚进入小程序，所有页面的created都会触发

**Comment by dsonet** [comment]
一进入应用就把所有页面都初始化了?why?
