### ISSUE TITLE
如何引入外部的样式库

### ISSUE THREAD

**Issue by xiaojiangjiang** [Meituan-Dianping/mpvue#406]
# 想在mpvue中引入![flex.css](https://github.com/lzxb/flex.css),然而尝试无法成功

**问题复现步骤:**

1. main.js中 import "flex.css" 没用
2. App.vue中的<script>import "flex.css"; </script>没用
3. App.vue中的<style>@import "node_modules/flex.css/dist/flex.css";</style>没用

**期望的表现:**
可通过编译，写入wxss中

**Comment by lessthanno** [comment]
外部库需要进行修改。目前可以一个个改

**Comment by aasailan** [comment]
遇到一样的问题。
