### ISSUE TITLE
如何实现图片懒加载呢？小程序原生组件image的lazy-load属性好像没有效果

### ISSUE THREAD

**Issue by hiboyluo** [Meituan-Dianping/mpvue#407]
# [问题简单描述]

**问题复现步骤:**

1. [第一步]
2. [第二步]
3. [其他步骤...]

**期望的表现:**

[在这里描述期望的表现]

**观察到的表现:**

[在这里描述观察到的表现]

**屏幕截图和动态 GIF 图**

![复现步骤的屏幕截图和动态 GIF 图](图片的 url)

**Comment by lessthanno** [comment]
亲测有效果的，而且一直再跑的。可能是写法不对 
//bad
<img  :lazy-load />
//good
<img  lazy-load />

**Comment by hiboyluo** [comment]
img组件是要放在<page>或<scroll-view>组件里面吗

**Comment by hiboyluo** [comment]
img组件是要放在page或scroll-view组件里面吗

**Comment by hiboyluo** [comment]
或者您告诉我一下您的使用方式

**Comment by The-five-stooges** [comment]
对的，放page或者scroll-view内

**Comment by hiboyluo** [comment]
`但是小程序最外层不就是page元素吗？还要单独在image组件外包裹page元素吗？像这样吗？
`<page>
<image lazy-load="{{true}}"></image>
<image lazy-load="{{true}}"></image>
<image lazy-load="{{true}}"></image>
</page>`
但是加上之后感觉没什么效果？还是图片要放多才有效果

**Comment by hiboyluo** [comment]
但是小程序最外层不就是page元素吗？是还要再image外再包裹一个page元素吗？
<page>
<image lazy-load="{{true}}"/>
<image lazy-load="{{true}}"/>
<image lazy-load="{{true}}"/>
</page>
像这样，但是好像也没什么效果，是不是图片放得多才有效果。
