### ISSUE TITLE
cross-env not working

### ISSUE THREAD

**Issue by gengjiawen** [Meituan-Dianping/mpvue#408]
**问题复现步骤:**
npm 增加个 task
```
"dev-prod": "cross-env NODE_ENV=production node build/dev-server.js",
```
main.js打印process.env, 还是 {NODE_ENV: "development"}。

我这么做要解决的问题是根据环境变量来改变运行时的参数，比如测试环境和正式环境不同的url配置。

**Comment by aOrz** [comment]
![image](https://user-images.githubusercontent.com/6347990/40279753-db964f82-5c7a-11e8-92d1-6b0f213e7d37.png)
可自行配置webpack.DefinePlugin

**Comment by gengjiawen** [comment]
我知道这个可以，我想要cross-env也可以，跟普通的vue和wepy那样

**Comment by hopkinson** [comment]
请问解决了吗？
