### ISSUE TITLE
methods中return值没有返回

### ISSUE THREAD

**Issue by The-five-stooges** [Meituan-Dianping/mpvue#411]
# methods中return值没有返回

**问题复现步骤:**

1. dom:
` <p class="ddd">{{methodMessage()}}</p>`
2. methods: 
```
methodMessage () {
    return this.message.split('').reverse().join('')
}
```

**期望的表现:**
![e03e60e8-8a08-473b-bc25-9671dd24b351](https://user-images.githubusercontent.com/18204304/39612052-9ca922c0-4f8e-11e8-9c5f-82aa86a73c2a.png)
`<view class="_p data-v-55b6605c ddd">olleh</view>`

**观察到的表现:**

`<view class="_p data-v-55b6605c ddd"></view>`

**Comment by F-loat** [comment]
不支持这种写法，可以使用 computed

**Comment by The-five-stooges** [comment]
有些场景下需要根据index动态返回参数，computed没法满足需求

**Comment by F-loat** [comment]
组件的 prop 可以接受 method

**Comment by The-five-stooges** [comment]
但是slot中使用组件，props和computed数据无法正常渲染

**Comment by youngluo** [comment]
@F-loat 
![image](https://user-images.githubusercontent.com/7480381/44148234-09c8df12-a0ca-11e8-9e7a-b0e0427cc7c8.png)
这个问题有什么解决方案吗
