### ISSUE TITLE
加减购物车：多层级嵌套的数组点击不能更新数据。。。

### ISSUE THREAD

**Issue by CWTgithub** [Meituan-Dianping/mpvue#412]
![image](https://user-images.githubusercontent.com/21306982/39614788-1b768064-4fa5-11e8-9e5e-ff39a466bff4.png)

这里的count并没有用到，我要更新的是goodNumber[$shopIndex][$actIndex][$itemIndex]。。。这种情况下加的有反应，减的没反应。。。放开this.count--后就都正常了，，，不知道为何？？？

**Comment by F-loat** [comment]
复现是要你把业务逻辑去掉。。

**Comment by CWTgithub** [comment]
let 声明 的变量没法改变，但是经过data的就可以，找不着原因，但是通过很不优雅的代码解决了

**Comment by F-loat** [comment]
你为什么不直接对传入的 item 操作

**Comment by aOrz** [comment]
https://cn.vuejs.org/v2/guide/list.html#%E6%95%B0%E7%BB%84%E6%9B%B4%E6%96%B0%E6%A3%80%E6%B5%8B
