### ISSUE TITLE
mpvue 使用小程序的scroll-view 横向不能滚动诶

### ISSUE THREAD

**Issue by EzioL** [Meituan-Dianping/mpvue#416]
mpvue 使用小程序的scroll-view 横向不能滚动诶
<img width="1105" alt="wx20180504-181837 2x" src="https://user-images.githubusercontent.com/16730259/39623647-eb097a5c-4fc8-11e8-9d15-981bb884f8d3.png">

**Comment by EzioL** [comment]
<template>
  <div>
    <p class="section__title">horizontal scroll</p>
    <scroll-view scroll-x="true" style="width: 500px;height:100%;background-color: black">
      <div style="width: 200px;height:200px;background-color: #ffed18"></div>
      <div style="width: 200px;height:200px;background-color: #0eff1d"></div>
      <div style="width: 200px;height:200px;background-color: #ff73f0"></div>
      <div style="width: 200px;height:200px;background-color: aqua"></div>
      <div style="width: 200px;height:200px;background-color: #ff1b78"></div>

    </scroll-view>

  </div>
</template>

**Comment by hucq** [comment]
@EzioL 可以在模拟器里检查一下 page 元素被默认设置了 overflow-x: hidden；模拟器和真机存在差异也是常见的事情。在模拟器里你可以强制重置掉此条默认样式即可。

**Comment by EzioL** [comment]
scroll-x="true"  赋值进不去呀 变成了 竖直排列了 @hucq

**Comment by F-loat** [comment]
直接写 scroll-x 就行吧

**Comment by EzioL** [comment]
不可以的诶，第一次就写的 scroll-x  赋值进不去 @F-loat

**Comment by lixiang** [comment]
@EzioL https://www.cnblogs.com/miu-key/p/7606024.html  我是这样解决的 item 使用 inline-block

**Comment by sonicG** [comment]
@hucq 这个问题并没有解决，真机上不可以的，必须要给scroll-view内部嵌套一个容器，并固定宽度才可以，小程序原生的示例代码都不行，求官方给个解决方案

**Comment by F-loat** [comment]
@sonicG 估计还是样式问题，按楼上说的设置 display: inline-block 可以解决，小程序官方示例省略了样式部分，原生直接那么写也是一样不行的吧

**Comment by bravekingzhang** [comment]
@EzioL @F-loat 参考小程序官方demo即可。
```
        <scroll-view class="scroll-view_H" scroll-x="true" bindscroll="scroll" style="width: 100%">
          <view id="demo1" class="scroll-view-item_H demo-text-1"></view>
          <view id="demo2"  class="scroll-view-item_H demo-text-2"></view>
          <view id="demo3" class="scroll-view-item_H demo-text-3"></view>
        </scroll-view>
```
```
.page-section-spacing{
  margin-top: 60rpx;
}
.scroll-view_H{
  white-space: nowrap;
}
.scroll-view-item{
  height: 300rpx;
}
.scroll-view-item_H{
  display: inline-block;
  width: 100%;
  height: 300rpx;
}

```
估计还是样式问题，我用flex布局实现，也是不ok，还是要display:inline-block
