### ISSUE TITLE
如何自定义page名，目前只能是main

### ISSUE THREAD

**Issue by herodhb** [Meituan-Dianping/mpvue#417]
# [问题简单描述]
如何自定义page名，目前只能是main，查看文档后修改webpack.base.config.js的entry，但是static中并没有对应的wxss文件
**问题复现步骤:**

1. ![image](https://user-images.githubusercontent.com/14303897/39628901-13cac77a-4fdd-11e8-95c9-43afbb50cc42.png)
2. npm run dev
3. dist/pages/mine 目录下正确生成了4个文件
4. static目录下js正常，css没有
5. ![image](https://user-images.githubusercontent.com/14303897/39629128-b641b144-4fdd-11e8-876f-b5c28052b306.png)

**期望的表现:**
期望static/css目录下有正确的文件

**观察到的表现:**
没有生成

**Comment by wonderffee** [comment]
你可以用mpvue-entry，参考https://github.com/F-loat/ithome-lite 看看，它里面就没用到main.js，因为是自动生成的

**Comment by F-loat** [comment]
你的写法应该是没问题的，可以先重新创建一个项目，看能不能复现这个问题

**Comment by binghuis** [comment]
你好，我也遇到了这个问题，static/css下没有生成对应的文件，你后来是怎么解决的呢。

**Comment by wjy4124** [comment]
+1

**Comment by F-loat** [comment]
可以试下用这个模板生成项目 https://github.com/F-loat/mpvue-quickstart

**Comment by F-loat** [comment]
目前好像不行，不过可以支持，你需先把额外的页面写在 main.js 里，然后我处理时保留下来就可以

**Comment by wjy4124** [comment]
嗯 我发现 main.js 里的 pages 被盖了

**Comment by F-loat** [comment]
@wjy4124 更新 mpvue-entry 到 1.2.3 以上版本就可以了，https://github.com/F-loat/mpvue-entry#tips

**Comment by wjy4124** [comment]
@F-loat thx
