### ISSUE TITLE
mpType是干什么用的？

### ISSUE THREAD

**Issue by linfan68** [Meituan-Dianping/mpvue#419]
能不能简单解释一下mpType（‘app’或者‘page'）是做什么用的？不指定有什么影响？
我在用typescript写mpvue，不知道这个flag是不是正确的设了，尝试不设置根本不管好像也没啥问题……

**Comment by F-loat** [comment]
mpType = ‘app’ 是要设置的，具体作用参考以下源码，其他地方也有用到的，可以自行搜索查看
https://github.com/Meituan-Dianping/mpvue/blob/df0162bdc32b9e30edcc0d2b962782e055cd27f0/src/platforms/mp/runtime/lifecycle.js#L65-L102

**Comment by F-loat** [comment]
另外后面 mpvue-loader 里应该也会改为根据这个属性判断页面类型
