### ISSUE TITLE
小程序原生组件背景图的引入问题

### ISSUE THREAD

**Issue by fangdiao** [Meituan-Dianping/mpvue#420]
# [问题简单描述]
在mpvue中size小的背景图会被打包为base64。但是如果在mpvue中使用原生自定义组件会遇到背景图无效的问题，因为wxss不支持引入本地背景图片。请问如何在原生自定义组件中引入背景图，需要修改webpack的配置吗。
**问题复现步骤:**

1. [第一步]
2. [第二步]
3. [其他步骤...]

**期望的表现:**

[在这里描述期望的表现]

**观察到的表现:**

[在这里描述观察到的表现]

**屏幕截图和动态 GIF 图**

![复现步骤的屏幕截图和动态 GIF 图](图片的 url)

**Comment by F-loat** [comment]
原生组件目前应该只是复制而已，可以自己写个插件处理
