### ISSUE TITLE
v-for渲染列表，绑定:key索引的时候，出现重复的子项

### ISSUE THREAD

**Issue by itboke** [Meituan-Dianping/mpvue#423]
**v-for渲染列表，绑定:key索引的时候，出现重复的子项**

![b qm2pu5y _d 7r 9yl2 d](https://user-images.githubusercontent.com/8155864/39660590-d0e4ff1e-5074-11e8-8cbf-4269384a679a.png)
![7 7y_ bt0m8jif ao tr0 5](https://user-images.githubusercontent.com/8155864/39660593-d94ccdc6-5074-11e8-9e1c-89f79ee5b7b4.png)

**Comment by aOrz** [comment]
同楼上
