### ISSUE TITLE
如何设置 page的navigationBarTitleText? 配置好像没有生效 生命周期中会有延迟

### ISSUE THREAD

**Issue by Stupidism** [Meituan-Dianping/mpvue#428]
# [问题简单描述]

**问题复现步骤:**

![image](https://user-images.githubusercontent.com/5801015/39674576-8183fb7a-5180-11e8-8bb4-50ffafdef6d1.png)

**期望的表现:**

应该生成对应的page/main.json, 并且在小程序中显示出对应的tigle

**观察到的表现:**

生成了对应的page/main.json, 但在小程序中没有显示出对应的tigle

**屏幕截图和动态 GIF 图**

![复现步骤的屏幕截图和动态 GIF 图](图片的 url)
![image](https://user-images.githubusercontent.com/5801015/39674544-14be43ce-5180-11e8-999d-72c7dfbcdebf.png)
![image](https://user-images.githubusercontent.com/5801015/39674585-9302cfe8-5180-11e8-9871-b184264ffa81.png)

**Comment by hucq** [comment]
@Stupidism 请参见小程序官方说明 https://developers.weixin.qq.com/miniprogram/dev/framework/config.html
页面窗口的设置无需添加 window 这一层，这和 app 不一样。

```javascript 
export default {
  config: {
    "navigationBarBackgroundColor": "#ffffff",
    "navigationBarTextStyle": "black",
    "navigationBarTitleText": "微信接口功能演示",
    "backgroundColor": "#eeeeee",
    "backgroundTextStyle": "light"
  }
}
```

**Comment by Stupidism** [comment]
@hucq 谢谢啊, 之前尝试了各种配置方式, 可能是机缘巧合, 恰好没碰到这个正确的情况~~~

**Comment by anming-john** [comment]
![image](https://user-images.githubusercontent.com/15686326/47601960-3a73dd00-da0a-11e8-8a26-0d5289d23498.png)
我是了下发现不行啊。 在dist 并没有生成
![image](https://user-images.githubusercontent.com/15686326/47601965-511a3400-da0a-11e8-934b-498e9a46f92b.png)

**Comment by F-loat** [comment]
mpvue-loader 在 1.1.0 之后的版本修改了页面的配置方式，需要新增一个 json 文件，具体的可以查看官网文档

**Comment by F-loat** [comment]
推荐使用 mpvue-entry，方便配置
