### ISSUE TITLE
在vue中如何使用sass语法，老是包缺少依赖

### ISSUE THREAD

**Issue by hjx5309** [Meituan-Dianping/mpvue#43]

**Comment by aOrz** [comment]
具体的错误贴出来？

**Comment by luoquanquan** [comment]
需要安装sass-loader 和 node-sass 这俩货经常安装失败，可以分别 npm i sass-loader -D  /  npm i node-sass -D  成功几率会高一点

**Comment by wangminyi** [comment]
重装 sass-loader 后解决

**Comment by lizesheng0313** [comment]
https://developers.weixin.qq.com/community/develop/doc/000ee63dca0ff0dc189731e535fc00?commentid=00088259c940605c1a9715281534&idescene=7&jumpto=comment    报错
