### ISSUE TITLE
mpvue-simple build error

### ISSUE THREAD

**Issue by wzdwc** [Meituan-Dianping/mpvue#432]
![image](https://user-images.githubusercontent.com/12741381/39710656-0345e18a-5250-11e8-8a34-34190150d5c7.png)
![image](https://user-images.githubusercontent.com/12741381/39710710-2e5472ec-5250-11e8-92e9-0257087b92cf.png)
![image](https://user-images.githubusercontent.com/12741381/39710758-4d713250-5250-11e8-8c36-055fe704d061.png)

请问是否哪里配置错误了？

**Comment by anchengjian** [comment]
这里用了 https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_syntax，升级下 node 版本应该就好了。

**Comment by wzdwc** [comment]
![image](https://user-images.githubusercontent.com/12741381/39762188-965e0a80-530c-11e8-8ca6-7ebc0deb99c1.png)
v8.2.1都不行？
