### ISSUE TITLE
能有人来说明下mpvue-simple生成的文件怎么使用么？

### ISSUE THREAD

**Issue by lishenggang** [Meituan-Dianping/mpvue#434]
如问题：
#430 
简直要崩溃了！怎么试也不行啊！必须得整个项目编译才能跑得起来

**Comment by hlwen** [comment]
试试node v9



发自我的小米手机
在 lishenggang <notifications@github.com>，2018年5月8日 22:55写道：

如问题：
#430<https://github.com/Meituan-Dianping/mpvue/issues/430>
简直要崩溃了！怎么试也不行啊！必须得整个项目编译才能跑得起来
