### ISSUE TITLE
img 默认图 应该怎么配置

### ISSUE THREAD

**Issue by guoshiqiufeng** [Meituan-Dianping/mpvue#435]
# [img 默认图不显示]
img标签设置默认图，应该怎么弄，试了vue的和小程序的binderror都不好使
**问题复现步骤:**

1. [第一步] 在vue中 <img :src="item.pictureAddress" binderror="errorFunction"/>
2. [第二步] 编译完成<imageclass="_img data-v-2baf6d24"src="http://192.168.1.60:8890/root/"></image>
3. [其他步骤...]
在vue中声明了errorFunction () {
    console.log('error')
  }
在小程序显示找不到
Do not have errorFunction handler in current page: pages/classify/main. Please make sure that errorFunction handler has been defined in pages/classify/main, or pages/classify/main has been added into app.json
**期望的表现:**
求助应该怎么写

**Comment by saiyao** [comment]
能请教一下，这个问题怎么解决吗

**Comment by guoshiqiufeng** [comment]
有两种方式，一样用js，一种用css
第一种：在图片加载失败后用默认图片替换
html
  <img` :src="userIcon" @error="errorLoadImg">
js
  import userDefaultIcon from '../../assets/images/my_icon/my_def_portrait.png'
...
computed: {
      userIcon () {
        return this.$store.state.headIconUrl
      },
  ...
  methods: {
   errorLoadImg () {
        this.userIcon = userDefaultIcon
      },
}
第二种：设置默认css，在img加载成功后会自动显示图片
html
  <img  class="default-image"  :src="userIcon">
js
   import userDefaultIcon from '../../assets/images/my_icon/my_def_portrait.png'
   ...
    computed: {
      userIcon () {
        return this.$store.state.headIconUrl
      },
  ...
css
    img{
          float: left;
          width: px2rpx(150);
          height: px2rpx(150);
          border-radius:px2rpx(75);
        }
        .default-image{
          @include bis(url)
        }
mixin
  @mixin bis($url) {
  background-image: url($url);
  background-repeat: no-repeat;
  background-size: 100% 100%;
}

**Comment by XinjianQi** [comment]
我用第一种方式怎么不行呢？没有调error事件

**Comment by guoshiqiufeng** [comment]
检查下代码，或者把代码贴出来，或者用第二种方式

**Comment by XinjianQi** [comment]
![image](https://user-images.githubusercontent.com/2142885/44980014-3d6dc680-afa1-11e8-9eaf-ae2906b0adf8.png)
![image](https://user-images.githubusercontent.com/2142885/44980031-452d6b00-afa1-11e8-8f7b-f1230802c098.png)
![image](https://user-images.githubusercontent.com/2142885/44980066-5e361c00-afa1-11e8-952c-2b39dcb14c18.png)
![image](https://user-images.githubusercontent.com/2142885/44980128-8d4c8d80-afa1-11e8-84ae-0dfbed5b17ba.png)

这是我的代码，应该没啥问题吧，
主要是没有吊 errorLoadImg 事件

**Comment by guoshiqiufeng** [comment]
![image](https://user-images.githubusercontent.com/15354567/44981369-eff35880-afa4-11e8-8e8a-bce0cf033f74.png)
![image](https://user-images.githubusercontent.com/15354567/44981387-fe417480-afa4-11e8-92f5-cceb9f4b2ae2.png)
我这走了，你method单词写错了

**Comment by XinjianQi** [comment]
😓 抱歉，打扰了，非常感谢你啊。
