### ISSUE TITLE
同一组件内嵌套的 v-for 不能连续使用相同的索引

### ISSUE THREAD

**Issue by Zronel** [Meituan-Dianping/mpvue#436]
我使用双重循环的时候报错了，本意是产生20行10列的div
<div class="row" v-for="row of 20" :key="row">
      <div class="column" v-for="column of 10" :key="`${row}-${column}`">{{row * 20 + column}} 
      </div>
</div>

报错如下：
(Emitted value instead of an instance of Error)
  Error compiling template:

    <div class="row" v-for="row of 20" :key="row">
       <div class="column" v-for="column of 10" :key="`${row}-${column}`">{{row * 20 + column}} 
       </div>
    </div>

  - 同一组件内嵌套的 v-for 不能连续使用相同的索引，目前为: index,index
  - 同一组件内嵌套的 v-for 不能连续使用相同的索引，目前为: index,index

**Comment by F-loat** [comment]
手动指定下 index 就可以，`v-for="(row, rowIndex) of 20"` 这样

**Comment by Zronel** [comment]
不行，还是报统同样的错

**Comment by sonicsunsky** [comment]
我也遇到这个问题了，请问是如何解决的？F-loat说的对吗？

**Comment by F-loat** [comment]
嵌套的 index 都自己指定下，不重复应该就行
