### ISSUE TITLE
mpvue 不支持 vuex-loading?

### ISSUE THREAD

**Issue by smithyj** [Meituan-Dianping/mpvue#438]
mpvue 不支持 vuex-loading?

**Comment by F-loat** [comment]
涉及 DOM 操作的库都不支持

**Comment by F-loat** [comment]
看了下这个库试用了全局组件，可以更新 mpvue-loader 到最新版本，然后引用 src/vuex-loading.js 这个文件试下

**Comment by smithyj** [comment]
@F-loat 用了下 不兼容好像

**Comment by F-loat** [comment]
dist 文件肯定是不能直接用的，具体的问题你可以看下 vuex-loading 的源码排查下
