### ISSUE TITLE
全局组件渲染问题

### ISSUE THREAD

**Issue by pigjane** [Meituan-Dianping/mpvue#444]
# 全局组件没有渲染

**问题复现步骤:**

1.写了个全局组件`tdiv`
 ```
Vue.component('tdiv', {
  template: "<div>aaa</div>"
})
```
2. 经过`mpvue`编译，小程序中的`wxml`
```
<tdiv></tdiv>
```

**期望的表现:**

```
<view>aaaa</view>
```

应该是被编译成小程序组件了吧。如果只能通过`vue`文件写组件，那有n个组件就得在页面中引n次，
如果是全局组件，就不需要引，这样比较方便。

**Comment by F-loat** [comment]
最新版的 mpvue-loader 应该已经支持了，可以更新试试

**Comment by pigjane** [comment]
更新了依赖，还是不行哦

**Comment by F-loat** [comment]
https://github.com/mpvue/mpvue-loader/pull/17 有什么错误提示没

**Comment by pigjane** [comment]
@F-loat 没有哦 [需求池](https://trello.com/b/ZBP1leCF/mpvue)

**Comment by F-loat** [comment]
你看下 mpvue-loader 的那个 pr

**Comment by linrui1994** [comment]
这个pr虽然合了，但是还没发布新版本，所以现在是不支持的，另外需要通过引入文件的方式来引入组件才会生效

**Comment by pigjane** [comment]
@F-loat @linrui1994 好的，谢谢你们

**Comment by F-loat** [comment]
emmm我记得上周五发版了吧

**Comment by linrui1994** [comment]
loader应该没发吧，release上没找到

**Comment by F-loat** [comment]
确实，我好像是之前测试的时候直接装了 git 上的代码

**Comment by zaxlct** [comment]
@F-loat 所以打算什么时候发布呢

**Comment by weilongfei** [comment]
在 main.js  里面直接注入可生效 但是 通过 Vue.use 的 install 就不行了 望解释
