### ISSUE TITLE
如何在pages中的main.js使用变量?

### ISSUE THREAD

**Issue by kaykie** [Meituan-Dianping/mpvue#445]
# [问题简单描述]

**问题复现步骤:**

import Vue from 'vue'
import App from './menuDetail.vue'
import store from '../../models/store'

const app = new Vue(App);
app.$mount();

export default {
  config: {
    navigationBarTitleText: store.state.menu[0].title
  }
}
以上是一个page页面main.js的代码,目前是报错

**期望的表现:**
不报错,可以在使用变量

**观察到的表现:**

如何在config使用变量,报的错是:store is not defined,这里如何引入变量呢?

**Comment by F-loat** [comment]
应该是你代码的问题

**Comment by kaykie** [comment]
@F-loat 就是说 我这写是对的吗? 可是我删除这一行就不报错了,或者给赋值为字符串就不报错了.同学,你有赋值变量的例子吗?

**Comment by F-loat** [comment]
感觉是 store 没导出或者变量名写错了吧

**Comment by kaykie** [comment]
@F-loat import Vue from 'vue'
import App from './menuDetail.vue'
import store from '../../models/store'
const stor = 'vvvv';
const app = new Vue(App);
app.$mount();

export default {
  config: {
    navigationBarTitleText: stor
  }
}
我这样用也是报错的

**Comment by F-loat** [comment]
emmm 我试下，配置文件可能确实不支持变量。。

**Comment by F-loat** [comment]
@kaykie  你使用变量的目的是什么，如果是为了动态修改是做不到的，需要调用小程序的 api 才行

**Comment by kaykie** [comment]
@F-loat 我应该怎么动态修改page里的navigationBarTitleText呢?

**Comment by F-loat** [comment]
https://developers.weixin.qq.com/miniprogram/dev/api/ui.html#wxsettopbartextobject

**Comment by kaykie** [comment]
3Q 搜索到了

**Comment by some-code** [comment]
````
export default {
  config: {
      navigationBarTitleText: stor
  }
}
````
修改为以下方式即可
````
const config = {
  config: {
      navigationBarTitleText: stor
  }
}
export default config;
````
