### ISSUE TITLE
touch 下组件内的click不触发

### ISSUE THREAD

**Issue by 1578388951** [Meituan-Dianping/mpvue#446]
# [问题简单描述]

**问题复现步骤:**
我页面这一模块需要监控touchstart和touchmove,里面是我封装的组件，组件内是我循环的列表我在我的列表上添加click时间不是报错，提出了警告，并且时间就触发不了

**期望的表现:**

怎么解决touch中的click事件无法触发

**观察到的表现:**

我页面这一模块需要监控touchstart和touchmove,里面是我封装的组件，组件内是我循环的列表我在我的列表上添加click时间不是报错，提出了警告，并且事件就触发不了，我要是把组件内的列表不封装直接拿到那个页面click就可以执行封装起来就不能执行了

**屏幕截图和动态 GIF 图**
![image](https://user-images.githubusercontent.com/18043983/39861039-ed73939c-5471-11e8-825e-9949042b26dc.png)
![image](https://user-images.githubusercontent.com/18043983/39861074-0b0ce5d4-5472-11e8-990c-1675474be40f.png)
![image](https://user-images.githubusercontent.com/18043983/39861100-1b821718-5472-11e8-84ed-6eaa089f0e60.png)
![image](https://user-images.githubusercontent.com/18043983/39861111-29119a70-5472-11e8-98c5-05faf1dde1f4.png)
![q gdrw5 5 e b 83t s8](https://user-images.githubusercontent.com/18043983/39861128-313f5a8e-5472-11e8-9d89-f6a62b689edd.png)

**Comment by F-loat** [comment]
#308
