### ISSUE TITLE
mpvue如何修改switch的宽高？

### ISSUE THREAD

**Issue by cquptpei** [Meituan-Dianping/mpvue#451]
# [如何在mpvue中修改switch的宽高？]

**问题复现步骤:**

1. 小程序的switch组件没有提供修改宽高的方式，网上查资料发现可以通过设置.wx-switch-input类来修改，但是在mpvue中通过这个类修改之后，经过编译会在每个类的后面加上一个类名：.wx-switch-input.data-v-04cc7343，导致修改switch宽高失效

**期望的表现:**

求问，有没有什么方法可以去掉添加的类名：.data-v-04cc7343，或者有没有其他方法修改switch组件的宽高？

**Comment by linrui1994** [comment]
不要使用scoped

**Comment by aOrz** [comment]
可以对
