### ISSUE TITLE
关于新增文件夹需要重新npm run dev，有一点小建议，不知能否实现

### ISSUE THREAD

**Issue by spencer1994** [Meituan-Dianping/mpvue#453]
使用到了webpack的require.context的上下文
![image](https://user-images.githubusercontent.com/19463934/39911098-bd2f0f7a-552c-11e8-9900-42d02b94276c.png)
这个可以搜索文件夹下的所有main.js的文件。功能与官方恰恰相反，新增的文件夹会自动读取，仅在删除文件夹时需要重新运行`npm run dev`，相对来说删除文件夹应该更低频一些，项目需求来的时候，创建文件夹应该比较高频。
附上之前写的[vue.js关于自动读取文件来自动注册store及router的文章](https://zhuanlan.zhihu.com/p/35487954)

**Comment by F-loat** [comment]
这样也没法更新 webpack 的 entry 吧

**Comment by spencer1994** [comment]
@F-loat 抱歉..确实不可行。
刚看到mpvue loader 才发现官方的做法是：`它会从 webpack 的配置中的 entry 开始，分析依赖模块，并分别打包。`
