### ISSUE TITLE
支持css module吗

### ISSUE THREAD

**Issue by sunzongzheng** [Meituan-Dianping/mpvue#454]
# css modules无效，生成的模板没有带上className

**问题复现步骤:**

1. 
````html
<div :class="s.app"></div>
````
2. 
````css
<style module="s">
.app {
    font-size: red;
}
</style>
````
3. dist生成的内容，模板上没有带上className。如
![image](https://user-images.githubusercontent.com/12635613/39912998-fd4298e2-5532-11e8-8668-26c1ff5b41f8.png)

**期望的表现:**

生成的模板带上className

**观察到的表现:**

  - 生成的样式中已经被替换成变量，如：
    ![image](https://user-images.githubusercontent.com/12635613/39913033-18b6edbc-5533-11e8-9724-af4e54425f26.png)
  - created中打印this.s变量，数据也正确
    ![image](https://user-images.githubusercontent.com/12635613/39913056-2fb56886-5533-11e8-9c1d-aeb6de4a489c.png)

**Comment by aOrz** [comment]
暂不支持
