### ISSUE TITLE
关于每个组件的main.js的一点疑问

### ISSUE THREAD

**Issue by spencer1994** [Meituan-Dianping/mpvue#455]
> mpvue版本：1.0.10

>  关于各个子页面的main.js
不是很理解为什么每一个页面都要放一段如下所示的代码。页面的page.json也写在这里面。
``` js
import Vue from 'vue'
import App from './index'

const app = new Vue(App)
app.$mount()

export default {
  config: {
    navigationBarTitleText: '查看启动日志'
  }
}

```

我想了一下：
+ 是否能在index.vue里加多一个config配置。然后在构建打包的时候去获取vue页面里面的config对象即是小程序的page.json。
+ 构建打包的时候是否能实现自动挂载pages里面的每一个vue页面呢？

新手刚用，有点疑惑提了好几个issue不好意思。也想着帮mpvue进步！

**Comment by F-loat** [comment]
可以使用 [mpvue-entry](https://github.com/F-loat/mpvue-entry)，每个页面的 main.js 是作为 webpack 的入口文件的，所以不能完全去掉，加到 vue 文件里然后自动生成是可行的，不过目前官方应该不会支持，有能力的话可以给 mpvue-entry 提 pr

**Comment by spencer1994** [comment]
@F-loat 最近有点忙。。正好要做一个微信小程序，所以时间不是很充裕。。我再开一个关于store.js的issue，这个已经改好了。

**Comment by spencer1994** [comment]
@F-loat 最近有点忙。。正好要做一个微信小程序，所以时间不是很充裕。。

**Comment by PerseveranceZ** [comment]
可以用文件命名区分就比较好了，首页类似 home.mp.vue ,识别 *.mp.vue，自动帮 $mount，不然每个页面都要建一个文件夹，项目大了或者层级深了也会拖慢编译速度。
