### ISSUE TITLE
能否支持钉钉小程序?

### ISSUE THREAD

**Issue by KellerLong** [Meituan-Dianping/mpvue#457]
如题!
目前阿里的钉钉也开始做小程序了
支付宝也有小程序模块
问下 钉钉 和支付宝的小程序 是否可以一并支持了

**Comment by BoleLee** [comment]
@KellerLong 请问钉钉小程序文档之类的在哪里可以看到？

**Comment by aOrz** [comment]
提issue 前请看下有没有重复的 issue，同 #100
