### ISSUE TITLE
这个项目是否已经无人维护了? 

### ISSUE THREAD

**Issue by Stupidism** [Meituan-Dianping/mpvue#460]
看了一下contribution, 最近的commit在两个月前, issues 堆积

刚刚提了一个PR倒是瞬间回复了...

如果是, 那么现在是怎么解决"用Vue或者React小程序开发"的问题的? 
是有别的框架了 还是直接就用H5 webapp了?

**Comment by Stupidism** [comment]
@F-loat

**Comment by F-loat** [comment]
并没有停止维护，一般是每周五发版这样，上次更新是 8 天前，这周应该是没有什么重要更新所以停了一周，后面随着 vue 的更新这个项目应该是会更好的，而且大的改动毕竟需要投入很多精力的
