### ISSUE TITLE
Do not have userInfoHandler handler in current page: pages/index/main

### ISSUE THREAD

**Issue by jc91715** [Meituan-Dianping/mpvue#462]
在页面放置原生授权按钮
```
<button open-type="getUserInfo" bindgetuserinfo="userInfoHandler"> Click me </button>
```
在 `methods` 增加函数 `userInfoHandler`
```
   userInfoHandler(){
      console.log('success')
    }
```
点击授权之后，提示
```
Do not have userInfoHandler handler in current page: pages/index/main
```

先前使用wepy 框架，可以调用成功。在文档的[事件处理器](http://mpvue.com/mpvue/#_13)中，我没有找到我想要的，我是不是在哪里遗漏掉了什么。

**Comment by imgss** [comment]
bindgetuserinfo改成@ getuserinfo试试

**Comment by LiuShuoyu** [comment]
<button open-type="getUserInfo"  @getuserinfo="bindGetUserInfo">获取用户信息</button>
methods: {
    bindGetUserInfo (e) {
      console.log(e.mp.detail.errMsg)
      console.log(e.mp.detailuserInfo)
      console.log(e.mp.detail.rawData)
    }
}

**Comment by F-loat** [comment]
文档下面的 **踩坑注意** 里就有写的
