### ISSUE TITLE
项目js报错导致整个项目崩溃

### ISSUE THREAD

**Issue by cwc845982120** [Meituan-Dianping/mpvue#463]
# [问题简单描述]
js只要一报错（运行时报错），按钮点击效果、页面渲染全部都不行了，按钮点击有接口访问，但是点击效果没了，接口返回数据，但是没有渲染出来。
**问题复现步骤:**
1. [第一步]
访问接口
2. [第二步]
比如一个接口异常传了null 我这边空指针异常 然后就整个项目都点击异常 显示异常，页面渲染不了

**期望的表现:**
只是这个页面显示异常 而不是整个项目都异常

**观察到的表现:**
整个项目都异常，点击效果没了，页面渲染不上

**Comment by aOrz** [comment]
来个可复现 demo ？

**Comment by aOrz** [comment]
长时间无回复，issue 先关了

**Comment by BrightYang0801** [comment]
我也遇到了空指针异常小程序崩溃
