### ISSUE TITLE
在哪里设置页面的分享功能

### ISSUE THREAD

**Issue by lujunpeng** [Meituan-Dianping/mpvue#466]
如题

**Comment by aOrz** [comment]
new Vue({
  data: {
    a: 1
  },
  created () {
    // `this` 指向 vm 实例
    console.log('a is: ' + this.a)
  },
  onShow () {
    // `this` 指向 vm 实例
    console.log('a is: ' + this.a, '小程序触发的 onshow')
  },
onShareAppMessage () {}
})
