### ISSUE TITLE
Do not have handler in current page: pages/home/main. Please make sure that handler has been defined in pages/home/main, or not use handler with 'v-if'

### ISSUE THREAD

**Issue by kala888** [Meituan-Dianping/mpvue#467]
问题比较不好描述，将子Component作为另外component的slot内容的时候，报错

1.两个component，组件1，Searchbar，组件2，TopSticky（里面有slot）
2.单独使用组件1Searchbar和组件2TopStick（slot为简单的div），没有问题
3.两个组合在一起的时候，组件展示问题，且不能正常工作。点击search的icon出现warring：
```
Mon May 14 2018 13:37:45 GMT+0800 (CST) 事件警告
VM238:1 Do not have handler in current page: pages/home/main. Please make sure that handler has been defined in pages/home/main, or not use handler with 'v-if'
 ```

 [测试代码在github上](https://github.com/kala888/biubiuguai/commit/28672bba385bc86cc097ea11c84b05ce670113cd)

![image](https://user-images.githubusercontent.com/1215976/39980063-7a891fc4-577c-11e8-8d11-9173dd8a1ea5.png)

**Comment by F-loat** [comment]
可以试下是不是 #459 这个问题

**Comment by fyzhu** [comment]
<button  v-if='!userinfo' open-type='getUserInfo'    bindgetuserinfo='onGotUserInfo'>getUserInfo</button>
如何触发bindgetuserinfo
总是报错
 Do not have onGotUserInfo handler in current page: pages/me/main. Please make sure that onGotUserInfo handler has been defined in pages/me/main, or pages/me/main has been added into app.json

**Comment by heriky** [comment]
@fyzhu 
使用vue的语法绑定getuserinfo事件
```html
<button v-if='!userinfo' open-type='getUserInfo' @getuserinfo='onGotUserInfo'>getUserInfo</button>
```

```javascript
 methods: {
   onGotUserInfo() {
     console.log(‘登陆成功’)
   }
}
```

**Comment by fyzhu** [comment]
@heriky 问题已经解决了，谢谢，另外 @getuserinfo是mpvue规定的吗，不能写成其他的吧

**Comment by F-loat** [comment]
getuserinfo 是事件名，和 tap 之类的一样，原生小程序通过 bind 修饰符来绑定事件，所以写成 bindgetuserinfo，vue 中使用的是 @ 修饰符，所以要写成 @getuserinfo

**Comment by codingJia** [comment]
题主问的问题有解决办法了吗？我也遇到了，找到了半天也没有解决办法
