### ISSUE TITLE
unhandled promise rejection 没有任何提示,我尝试了多种方式，都没有一个地方能够全局捕获这类错误

### ISSUE THREAD

**Issue by liusome** [Meituan-Dianping/mpvue#468]
#280
**问题复现步骤:**

脚手架生成一个代码
在index.vue里面的
`created () {`
`  (async () => {`
`     let a = {}`
`     a.b.c = 0`
`  })()`
`},`
**期望的表现:**

期望在控制台里面报告created中不能够赋值给undefined

**观察到的表现:**

没有任何提示

**官方给出的回答是**
![image](https://user-images.githubusercontent.com/13285305/39857082-ad614ea0-5464-11e8-85bf-48b7a1a61109.png)
**小程序没有window对象，Promise对象的报错不会冒泡到全局，请看一下这个问题。** 

![image](https://user-images.githubusercontent.com/13285305/39982751-e6c77d42-5787-11e8-8a9e-3a5f17cac568.png)

![image](https://user-images.githubusercontent.com/13285305/39982760-edf45482-5787-11e8-8ed7-4f86015fc5d1.png)

**Comment by freedomcly** [comment]
created () {
    (async () => {
      let a = {}
      a.b.c = 0
    })**().then(
      v => console.log(v),
      e => console.log(e)
    )**
  }

这种方式有提示

**Comment by yedf** [comment]
@freedomcly 
通常的写法是async created() {
 let {data: r} = await axios.get('....')
 let a = {}
 a.b.c = 0
}
如果需要上述的写法，那么asyn的都得加几行
created() {
(async ()=>{
 let {data: r} = await axios.get('....')
 let a = {}
 a.b.c = 0
)().then(
v => console.log(v),
e => console.log(e)
)
}
代码明显的多了，不简洁了。

**Comment by freedomcly** [comment]
@yedf 
也不是一定要用立即执行函数吧。
关键是对async函数和promise做一下error catch。
error catch也可以抽出来的。

**Comment by yedf** [comment]
写个代码看看呢？无论如何都没有全局错误处理来得优雅 @freedomcly

**Comment by weilao** [comment]
未捕获的错误应该在 console 中报错。
跟了一下这个问题，首先在控制台中使用代码
```js
new Promise((resolve, reject) => {
  let a = {};
  a.b.c = 0;
});
```
可以正确获得报错如下：
```
VM754:3 Uncaught (in promise) TypeError: Cannot set property 'c' of undefined
    at Promise (<anonymous>:3:9)
    at Promise (<anonymous>)
    at <anonymous>:1:1
```

然后我检查了一下，在控制台中的 Promise 对象为原生的 Promise 对象：
```
Promise() { [native code] }
```

而在 mpvue 代码中的 Promise 对象为 core-js polyfill 对象：
```
Promise(executor) {
      anInstance(this, $Promise, PROMISE, '_h');
      aFunction(executor);
      Internal.call(this);
      try {
        executor(ctx($resolve, this, 1), ctx($reject, this, 1));…
```

**小结一下，因为 mpvue 中的 Promise 对象被替换成了 core-js polyfill 的 Promise 对象，而这个版本的 Promise 对象无法正常抛出错误提示。**


浏览器环境中有原生 Promise 的情况下，为什么还会替换原生 Promise 呢？让我们看一下 core-js：
![image](https://user-images.githubusercontent.com/3257035/41504019-d0489572-7214-11e8-8b46-25c19ca9f86c.png)
可以看到小程序中的 global 在并不是真正的 global，里面是没有 Promise 对象的，所以 core-js 误以为环境中没有 Promise，而进行了替换。当然，这也揭示了一个更大的问题：**除了Promise之外，几乎所有polyfill都被错误的应用了！！！**

经过一番查找，我发现在 mpvue 中还是能访问到原生的 Promise 对象的，在 mpvue 执行如下程序，可以获得报错：
```js
new __global.parent.Promise((resolve, reject) => {
  let a = {};
  a.b.c = 0;
});
```

**Comment by weilao** [comment]
因此得到一个 Workaround
找到
/node_modules/core-js/library/modules/_global.js 文件
将其改为：
```js
module.exports = __global.parent;
```
问题暂时解决。

**Comment by weilao** [comment]
@liusome @freedomcly @yedf @anchengjian

**Comment by yedf** [comment]
追查了较多的源代码之后，找到了一个可接受的workaround，比修改core-js要更好，不必在每次npm i之后去修改文件。
在src下的main.js中添加一行
require('core-js/library/modules/_global.js').console = console
或者require('core-js/library/modules/_global.js').onunhandledrejection = console.errror
@weilao @anchengjian @freedomcly @liusome 
能否把这个workaround集成到框架里面去呢？

**Comment by aOrz** [comment]
@weilao Promise 被替换是因为使用了 transform-runtime 插件，小程序环境和浏览器和 node 环境都不太一样，多数的 polyfill 都是不需要的，所以可以选择关闭掉 transform-runtime 的自动添加 polyfill （缺点是小程序一些不支持的特性可能需要手动引入）
async 函数是 babel-preset-env 给转换成了 generator ，我们可以禁用 transform-async-to-generator，换成 async-to-promises 插件，最终babelrc 配置如下，可参考：
`{
  "presets": [
    ["env", {
      "modules": false,
      "targets": {
        "chrome": 53,
        "safari": 8
      },
      "exclude": [
        "transform-async-to-generator"
      ]
    }]
  ],
  "plugins": ["async-to-promises", ["transform-runtime", {
    "polyfill": false
  }]],
  "env": {
    "test": {
      "presets": ["env", "stage-2"],
      "plugins": ["istanbul"]
    }
  }
}
`
