### ISSUE TITLE
每次新增页面都要重新npm run dev 

### ISSUE THREAD

**Issue by miracllife** [Meituan-Dianping/mpvue#473]
# [问题简单描述]

**问题复现步骤:**
每次新增页面都要重新npm run dev ,能否调整下，新增页面时不再需要 重新npm run dev
**期望的表现:**
新增页面时不再需要 重新npm run dev

**屏幕截图和动态 GIF 图**

![复现步骤的屏幕截图和动态 GIF 图](图片的 url)

**Comment by F-loat** [comment]
需要解决这个问题才行 https://github.com/mpvue/mpvue-loader/pull/15

**Comment by miracllife** [comment]
@F-loat 大佬，我们之间信息传递好像有些差别，我说的是mpvue启动后，每次新增vue页面时，你说的问题是多入口问题，多入口问题是新增html页面，

**Comment by F-loat** [comment]
mpvue 的每个页面是单独的入口的(各页面的 main.js 文件)，可以理解为多页面开发

**Comment by aOrz** [comment]
见文档：http://mpvue.com/qa/#_2
