### ISSUE TITLE
example/echarts打包失败

### ISSUE THREAD

**Issue by tim0991** [Meituan-Dianping/mpvue#476]
# [问题简单描述]

**问题复现步骤:**

1. git clone https://github.com/mpvue/examples.git
2. cd examples/echarts && yarn
3. 创建project.config.json
4. yarn dev

**期望的表现:**

正常运行，显示图标

**观察到的表现:**
![image](https://user-images.githubusercontent.com/26053904/40033682-0b8120c6-582c-11e8-8600-d760dc08139d.png)

**Comment by F-loat** [comment]
直接使用 dist 目录没有报错，应该是你 project.config.json 配置的问题，推荐使用 [mpvue-echarts](https://github.com/F-loat/mpvue-echarts)

**Comment by Zhulmin** [comment]
@F-loat
