### ISSUE TITLE
简单引入VUX，编译无法通过

### ISSUE THREAD

**Issue by FantasyWind2016** [Meituan-Dianping/mpvue#477]
# [问题简单描述]

在别的issue里看到mpvue是无法支持VUX的，但我只是想简单引入一下，看看效果；但是引入时发现连编译都无法通过，其他issue里也没有提到。

**问题复现步骤:**

1. [第一步]
使用官方的quickstart模板创建工程；
2. [第二步]
在webpack里引入VUX和VUX-Loader;
在.vue代码中import一些VUX的组件；
3. [其他步骤...]
npm run dev

**期望的表现:**

可以正常编译成小程序代码。

**观察到的表现:**

```
/Users/jifeng/MiniProgramProjects/learn-mpvue/mmpvue/node_modules/mpvue-template-compiler/build.js:4740
        var slotId = moduleId + "-" + slotName + "-" + (mpcomid.replace(/\'/g, ''));
                                                                ^

TypeError: Cannot read property 'replace' of undefined
```

**Comment by aOrz** [comment]
看起来是 slot 的问题

**Comment by aOrz** [comment]
vux 库使用了很多 mpvue 不支持的属性，所以可能不能直接使用，需要做修改
