### ISSUE TITLE
何时可以支持在template中直接调用函数

### ISSUE THREAD

**Issue by tim0991** [Meituan-Dianping/mpvue#478]

**Comment by aOrz** [comment]
由于小程序 wxml 限制，暂时无法支持

**Comment by guyuejinshang** [comment]
请问这种情况应该用什么替代呢？或者说代码应该怎么写？
<div :class="btnCls(v)" v-for="v in list"></div>
v是一个object，元素的样式是根据v的好几个字段一起来决定的
@aOrz
