### ISSUE TITLE
求一个mpvue微信小程序项目的源码，

### ISSUE THREAD

**Issue by qzhly1234567** [Meituan-Dianping/mpvue#479]
求一个mpvue开发的微信小程序的demo ，我最近在使用mpvue开发一个微信小程序的项目，遇到了很多问题，十分需要一个成功的项目来借鉴一下。谁能给我一套项目借鉴下！不胜感激！！！

**Comment by 673800357** [comment]
@qzhly1234567  [mpvue cnode](https://github.com/673800357/mpvue-cnode)。之前写的cnode论坛，可以参考下

**Comment by qzhly1234567** [comment]
@673800357 万分感谢！
