### ISSUE TITLE
v-for嵌套v-if，最后一个节点的事件绑定失败

### ISSUE THREAD

**Issue by az031120103** [Meituan-Dianping/mpvue#492]
v-if  条件中使用 && 运算符，完成渲染后，点击 0~29 可以触发 choseDate 事件。
然而，点击 30 控制台报如下错误：
VM12205:1 Do not have handler in current page: pages/calendar/main. Please make sure that handler has been defined in pages/calendar/main, or not use handler with 'v-if'

代码如下：

    <template>
	    <div class="date-item" v-for="i in 42" :key="i">
    	            <span v-if="(i > 0 && i <= 30)" @click="choseDate">{{i}}</span>
    	            <span v-else-if="(i > 30)"></span>
	    </div>
     <template>

    <script>
	    export default {
    	    data() {
        	    return {}
            }
            methods: {
                choseDate() {
            	    console.log('选择日期')
                }
            }
        }
    </script>

麻烦看看。

**Comment by linrui1994** [comment]
这个问题是v-for常数的时候，vue里是从1开始计算的，而小程序的wx:for常数是0开始，因为需要编译成wxml使用wx:for来循环，所以导致了这个问题。你可以换成数组的形式就不会报错了

**Comment by az031120103** [comment]
@linrui1994 正解
