### ISSUE TITLE
无法绑定 data-    dataset

### ISSUE THREAD

**Issue by xixiyang1216** [Meituan-Dianping/mpvue#494]
```
<image v-if="item_ticket.status==0" class="scratchMask" :class="{fade:item_ticket.scratchStatus}" src="../../static/image/gift_scratchMask2.png"
:data-ticketid="item_ticket.id" @click="scratchMask(item_ticket.id)"></image>
```
渲染结果：data-ticketid="item_ticket.id"

过了一会又渲染正确了 data-ticketid="1"
这种时好时不好是为啥遇到好几次了
这是微信开发工具bug还是框架bug

**Comment by aOrz** [comment]
mpvue 会把 :data-ticketid="item_ticket.id" 模板转成 data-ticketid="{{item_ticket.id}}" 的 wxml 模板，应该不会是 mpvue 造成的这个问题
