### ISSUE TITLE
我在使用lodash和rxjs的库，dev环境下正常，build后程序无法运行，并且报错。

### ISSUE THREAD

**Issue by januwA** [Meituan-Dianping/mpvue#496]
是我引入库姿势问题吗？
我在main.js里面，组件里面引入打包后都发生了错误。

**Comment by katherinesnow** [comment]
那两天我也遇到了，build，是lodash下面的一个ws.prototype打包问题。因为项目中只用到了深拷贝。所以暂时自己用其他深拷贝方式解决，不引用lodash.
如果你很急的话可以尝试下了

有时候是包的版本不同的打包问题

**Comment by katherinesnow** [comment]
那两天我也遇到了，build，是lodash下面的一个ws.prototype打包问题。因为项目中只用到了深拷贝。所以暂时自己用其他深拷贝方式解决，不引用lodash.
如果你很急的话可以尝试下了

有时候是包的版本不同的打包问题

**Comment by januwA** [comment]
哭@katherinesnow

**Comment by luanwulin** [comment]
@januwA 同样遇到问题，现在只能关掉了代码压缩，，，但是这样tree shacking没法用了啊。哭哭
