### ISSUE TITLE
尝试了下，居然兼容其他小程序的UI框架（小程序官网的自定义component组件）

### ISSUE THREAD

**Issue by iSword007** [Meituan-Dianping/mpvue#498]
因在vue的component下slot表现情况很差，于是我闲着蛋疼试了下MinUI（其使用的是小程序官网的自定义组件框架），居然成功使用了。

教程，按MinUI教程，先安装 min-cli

`yarn global add @mindev/min-cli`

然后根据MinUI提供的组件，安装自己需要的，如 countdown 倒计时组件
`min install @minui/wxc-countdown`
安装时，会提示如下：

- 安装位置
选择 dist 路径下的任意位置，比如我安装在 ‘dis/components’，默认为 'dist/packages'

- 是否启动ES6转ES5
选择Y 是  (否则运行报错哦)

安装完后，在相关页面的main.js的config下，注册绑定组件，如
``` main.js
export default {
  config: {
    usingComponents: {
      'wxc-countdown': '/components/@minui/wxc-countdown/dist/index'
    }
  }
}
```

下一步在，index.vue中插入代码，如：
```
<wxc-countdown :countdown="10"></wxc-countdown>
```

重启编译，即可运行（实时更新会报错）

注，在使用这种组件框架下，要注意事项，当我们mpvue进行build的时候，是会清空dist目录的，build之后记得重新运行一遍min-cli添加安装使用的组件。当然，你可以写个脚本在清空目录后，自动添加所用组件。

同理，使用有赞的小程序框架可以用。

最后，希望mpvue，兼容小程序官网的组件框架，有点小期待

**Comment by cds803** [comment]
为你点赞

**Comment by SoyMeng** [comment]
组件最好的实现方式是使用原生组件，跟vue原生的区别还是比较大的

**Comment by harrydengchao** [comment]
很强！亲测 zan-ui 也可以这样使用

**Comment by brucecodezone** [comment]
不能自定义安装位置吗？只能dist/xxx?

**Comment by jia345** [comment]
对于minui，放到static目录就不用每次都要运行min-cli了

**Comment by teri5354** [comment]
@iSword007 大神你好，我按你的操作方式，npm run dev之后，发现还是无法引用语minui的组件呀。我的目录是static，定义是usingComponents: {
      'wxc-countdown': '../../../static/@minui/wxc-countdown/dist/index'
    }
但是运行也没有报错，就是没有效果，换了几种组件和路径写法，都不行呢，可以指导一下吗？
