### ISSUE TITLE
mpvue好像不支持 vue 动态组件？

### ISSUE THREAD

**Issue by Juliancn** [Meituan-Dianping/mpvue#499]
# [问题简单描述]
目前mpvue好像不支持  <component v-bind:is="currentTabComponent"></component> 特性。
![image](https://user-images.githubusercontent.com/25763921/40222937-d2c4f412-5ab3-11e8-9a2b-d58905fd169e.png)

**期望的表现:**

[在这里描述期望的表现]

请问是否有意支持。

[在这里描述观察到的表现]

**屏幕截图和动态 GIF 图**

![复现步骤的屏幕截图和动态 GIF 图](图片的 url)

**Comment by F-loat** [comment]
文档有写不支持的

**Comment by F-loat** [comment]
现在的实现方式应该没法支持动态组件的，因为要预先编译出模板文件才行

**Comment by Juliancn** [comment]
恩恩，了解了，谢谢
