### ISSUE TITLE
mpvue有Promise化小程序API吗？&& mpvue微信学习交流群

### ISSUE THREAD

**Issue by cuitianze** [Meituan-Dianping/mpvue#5]
请问mpvue有Promise化小程序API吗？
文档和Demo里都没有提供说明，在Demo里尝试了不生效。

建了个群方便大家一起来学习交流，共同尝尝螃蟹，非官方
![image](https://user-images.githubusercontent.com/5918515/37188980-f5a14b42-238c-11e8-807d-910d440c2d89.png)
群超100人了，吃螃蟹尝尝鲜共同学习，加我微信拉进群，请备注：mpvue
![image](https://user-images.githubusercontent.com/5918515/37195785-31c099a8-23af-11e8-93bd-670aed5b5565.png)

**Comment by aOrz** [comment]
mpvue 没有 Promise 化小程序 API 库，关于 微信的原生 api，直接使用 wx. 去调用即可，可以自己去封装

**Comment by pcloth** [comment]
我封装了一个，抛砖引玉吧：
`import store from '@/store'

import qs from 'qs'

import config from '../../config'

const baseURL = (process.env.NODE_ENV !== 'production' ? config.dev.httpUrl : config.build.httpUrl)

const ajax = {
    get(url, params) {
        return new Promise(function (resolve,reject,) {
            wx.request({
                url: baseURL + url,
                method: 'GET',
                data: params,
                header: {
                    'token': store.state.token,
                    'openid':store.state.openid
                },
                success(res) {
                    resolve(res)
                },
                fail(error) {
                    reject(error)
                }
            })
        })        
    },
    post(url, data) {
        return new Promise(function (resolve,reject,) {
            wx.request({
                url: baseURL + url, 
                method: 'POST',
                data: qs.stringify(data),
                header: {
                    'token': store.state.token,
                    'openid':store.state.openid
                },
                success(res) {
                    resolve(res)
                },
                fail(error) {
                    reject(error)
                }
            })
        })  
    },
    all(ajaxArray) {
        return new Promise.all(ajaxArray)
    }
}


export default ajax
`

**Comment by zhangjiana** [comment]
mpvue技术qq群： 518705527
欢迎加入

**Comment by michaelzx** [comment]
@cuitianze 微信群满了，请留下微信号

**Comment by cuitianze** [comment]
@michaelzx 微信号 cuitianze001

**Comment by cdll** [comment]
安利一个本人的自行车, 欢迎拍砖~
https://www.npmjs.com/package/whenx
