### ISSUE TITLE
【问号脸 】更新某个data属性，这里实际是更新了全部data属性 :( 

### ISSUE THREAD

**Issue by sokis** [Meituan-Dianping/mpvue#500]
https://github.com/Meituan-Dianping/mpvue/blob/2a947d0baff4b7b1c1dfb72ad66ebcce048f6f1f/src/platforms/mp/runtime/render.js#L131-L139

不太明白初衷是什么？ 
但是这里确实是造成map使用以及各种性能问题的罪魁祸首。

#483 #452 #401

**Comment by prozwang** [comment]
lz 你用了throttle函数之后有解决问题么？

**Comment by gengjiawen** [comment]
@anchengjian 请问这个近期有时间改进吗？

**Comment by chuangbo** [comment]
@anchengjian ping

**Comment by luckyyyyy** [comment]
@anchengjian 有兴趣了解一下吗 
自己尝试了一些方法 只是暂时解决 还是需要优化一下这个位置

**Comment by charleslo1** [comment]
看了下源码，确实是这样，但又不知道怎么改

**Comment by charleslo1** [comment]
这个确实是引起 mpvue 诸多性能问题的根本原因

**Comment by anchengjian** [comment]
@luckyyyyy 啥方法，来个PR看看？

因为 Vue 的响应式特性，在某一数据变动时候会频繁的更新与其相关的数据和组件数据变动（长列表的数据雪崩），当时没有精耕细作解决根本问题，简单的加了节流操作，我记得我在代码中留了微信文档相关的注释。

**Comment by hucq** [comment]
升级新版本，全量更新已经优化为增量更新了。
mpvue  1.0.18
mpvue-loader 1.1.4
mpvue-template-compiler 1.0.18

**Comment by shawon1220** [comment]
页面循环组件长列表翻页到一定长度时卡死，不用组件方式循环没问题。
