### ISSUE TITLE
关于 issues 的问题

### ISSUE THREAD

**Issue by baby179888** [Meituan-Dianping/mpvue#501]
# [问题简单描述]
我在美团开源框架mpvue里面提交了一个问题，之后问题解决了，我把Issues关闭了。现在我每次登陆github，仓库列表的位置都会显示"Meituan-Dianping/mpvue" 这个仓库，很无解，不知道怎么去掉了。

**问题复现步骤:**

1. [第一步]

在Issues发布评论

2. [第二步]

关闭问题

3. [其他步骤...]

**期望的表现:**

不想显示“Meituan-Dianping/mpvue”这个库名，

[在这里描述期望的表现]

**观察到的表现:**

[在这里描述观察到的表现]

**屏幕截图和动态 GIF 图**

![复现步骤的屏幕截图和动态 GIF 图](图片的 url)

**Comment by aOrz** [comment]
这个问下 github，谢谢
