### ISSUE TITLE
在浏览器上localhost: 8080无法访问

### ISSUE THREAD

**Issue by frankxjkuang** [Meituan-Dianping/mpvue#502]
# 通过浏览器访问localhost: 8080 报错Cannot GET

**问题复现步骤:**

1.npm run dev
2. 浏览器访问localhost: 8080

**期望的表现:**

访问到该页的首页

**观察到的表现:**

Cannot GET /

**Comment by F-loat** [comment]
小程序要使用微信开发工具来调试，网页版需要额外处理的

**Comment by frankxjkuang** [comment]
我看了官网的文档，没发现相关的说明，官网原画是：需要更改小部分平台差异代码和更新下 webpack 的建构配置就可以直接运行。但是也没有具体说明，请问有相关的文档么？

**Comment by frankxjkuang** [comment]
我以为mpvue可以同时支持在线编辑测试 web 端和小程序的开发测试。我看了你的文章，要改的地方还有比较细节比较多的，官网也没给两种开发的配置区别，刚刚才开始上手这个也没有什么比较权威的文档，连官网都没写全，很难受啊。尴尬
