### ISSUE TITLE
三元计算符

### ISSUE THREAD

**Issue by ddztomcat** [Meituan-Dianping/mpvue#505]
# [问题简单描述]
三元计算符后面如果是简单字符串就可以正常展示，比如{{item.type === TYPE_SINGER ? ‘item.type’ : ‘TYPE_SINGER’}}，但如果是这样{{item.type === TYPE_SINGER ? item.type: TYPE_SINGER}}后面就无法正常显示

**Comment by F-loat** [comment]
使用的是最新版吗，之前修复过一次这个问题
