### ISSUE TITLE
关于组件引入方式问题

### ISSUE THREAD

**Issue by lixiang** [Meituan-Dianping/mpvue#506]
# [问题简单描述]
如果定义了一个组件 组件是以文件夹形式导出  会出现模板找到的情况
比如 新建文件夹 test , 文件夹有test.vue index.js 2个文件 index.js 导出test.vue ,这种方式在其他vue项目是没问题的。
**问题复现步骤:**

1. [第一步]
新建组件文件夹 并用index.js 方式导出
2. [第二步]
出现 warning为 Template "index$63a27a96" not found. 情况 组件不会渲染出来
3. [其他步骤...]

**期望的表现:**
如果直接import 这个vue  还是可以渲染，是不是考虑文件夹形式导入问题？
[在这里描述期望的表现]

**观察到的表现:**

[在这里描述观察到的表现]

**屏幕截图和动态 GIF 图**

![复现步骤的屏幕截图和动态 GIF 图](图片的 url)

**Comment by linrui1994** [comment]
由于在loader中要静态解析vue文件，所以不支持用js这种来动态抛出组件

**Comment by F-loat** [comment]
这种引用方式在组件生成方面其实是没问题的，但是页面里引用时组件的 name 无法正确识别，做了下简单的修复 https://github.com/mpvue/mpvue-loader/pull/23
