### ISSUE TITLE
无法加载图片

### ISSUE THREAD

**Issue by BriseLee** [Meituan-Dianping/mpvue#507]
第一次使用mpvue

直接上截图
![qq 20180519185635](https://user-images.githubusercontent.com/6055762/40267875-e67e3872-5b96-11e8-882b-a7d2409fe66f.png)
![qq 20180519185700](https://user-images.githubusercontent.com/6055762/40267876-ec494bf2-5b96-11e8-8933-42222a5fff1a.png)
![qq 20180519185713](https://user-images.githubusercontent.com/6055762/40267877-ec8520aa-5b96-11e8-9e2b-76c5240c813b.png)

图片地址尝试过去掉~，依然不行

我还有个疑问，为什么编译后的文件夹dist中没有图片文件呢？mpvue不打包图片文件？

**Comment by 372572571** [comment]
放在 src 同级的 static 目录下然后引入

**Comment by linrui1994** [comment]
刚发布了新版本，更新`mpvue-loader`到最新版本，使用相对路径来引入图片，也就是`./`或`../`开头，就可以了

**Comment by BriseLee** [comment]
@372572571 果然，谢谢了
