### ISSUE TITLE
使用vuex将store注入app时报错

### ISSUE THREAD

**Issue by heriky** [Meituan-Dianping/mpvue#509]
如下代码，在new Vue（）将store注入，小程序开发工具会报错，麻烦看一下

![tim 20180520095117](https://user-images.githubusercontent.com/12195736/40274887-c78bc9ba-5c14-11e8-8e48-5f4437e40217.png)

```
import Vue from 'vue'
import App from './index'
import store from '@/store'

const app = new Vue({
  store,
  ...App
})

app.$mount()
export default {
  config: {
    navigationBarTitleText: 'Index中设置的标题'
  }
}
```

**Comment by heriky** [comment]
找到原因了，因为使用App使用了vue-class-compoennt定义，{ ...App }的操作符报错

**Comment by aasailan** [comment]
App是个VueCompoment的构造函数，不是Options对象，用...操作符肯定就报错了

**Comment by heriky** [comment]
@aasailan 
如果使用原生的方式构造App的时候：
```javascript
// 实际上导出的是一个纯对象
export default {
    name: 'app',
    methods: {}
}
```
这个时候使用 new Vue({...App， store}) 是可以的，因为App的实质是一个对象，使用展开操作符...App是可以的。

但是实际上我这里定义App使用的是vue-class-component的方式，定义如下：
```javascript
// 这里实际上导出的是class
@Component()
export default class App extends Vue {
}
```
以class的方式定义App时， 使用展开操作符，展开的时class，肯定是报错了。
