### ISSUE TITLE
小程序的scroll-view组件的事件绑定不支持吗？

### ISSUE THREAD

**Issue by wuqiuyude** [Meituan-Dianping/mpvue#51]
用小程序的scroll-view的bind事件，发现都没有用，已经修改为@scroll，@scrolltolower

**Comment by wuqiuyude** [comment]
发现原因了，高度不能设置为100%

**Comment by ryan-hung** [comment]
@wuqiuyude 哥们你是怎么弄好的啊？ 为何我给scroll-view设置了固定高度还是不行呢？

**Comment by czhaoli** [comment]
@ryan-hung <div class="index-area" @scroll="scrollHandler" scroll-y> class设置固定高度，在div设置scroll-y就支持滚动了，和能够触发@scroll的回调方法

**Comment by xchz** [comment]
@czhaoli 我测试了一下一定要写在class里，这不等于没有用吗.....
