### ISSUE TITLE
如何禁用转发？

### ISSUE THREAD

**Issue by yuki070** [Meituan-Dianping/mpvue#510]
小程序原生代码只要不实现onShareAppMessage即可禁用转发功能，mpvue貌似没法去掉

**Comment by aOrz** [comment]
升级下 mpvue 版本

**Comment by zzzzzshPig** [comment]
不适用 onShareAppMessage 就可以啦~ 估计版本问题把

**Comment by yuconora** [comment]
wx.hideShareMenu()

**Comment by yuki070** [comment]
新版本的mpvue确实可以了。之前的版本是没有定义也自动绑上去的。感谢
