### ISSUE TITLE
mpvue-simple 一直在 ⠏ building for production... 加载中

### ISSUE THREAD

**Issue by imageslr** [Meituan-Dianping/mpvue#517]
# 如题，按照官网mpvue-simple command line的步骤尝试构建page级，但是一直在building。

**再次更新**：~~我的临时解决方案~~，可以编译出来，但是编译出来的组件不知如何使用，缺少wxml文件。

1. 删除`my-project/node_modules/mpvue-simple/config/argv.js`第146行判断是否为vue的条件判断

![image](https://user-images.githubusercontent.com/17822028/40344705-995f9dc2-5dc8-11e8-8a58-94ef57e1d6ea.png)

2. 运行`mpvue-simple --build`，此时提示 `CANNOT RESOLVE 'src' in 'src/main0.js'`

![image](https://user-images.githubusercontent.com/17822028/40343714-c9ea460e-5dc3-11e8-9a5e-08be5a4f6dc8.png)
(这是一个旧截图，mp-com是App.vue所在的文件夹名字）

3. 复制`my-project/node_modules/mpvue-simple/src/main0.js`到`my-project/src/main0.js`
4. 修改 `mpvue-simple/webpack.base.conf.js`, 设置entry为

```JS
entry: {
    app: '/Users/imageslr/DevelopFolder/my-project/src/main.js'
  },
```

5. 运行`mpvue-simple --build`，成功。

---

**问题复现步骤:**

1. `npm install -g mpvue-simple`
2. `echo -e '<template><h1>Hello {{msg}}!</h1></template>\n<script>\nexport default {\n  data () {\n    return { msg: 233 }\n  }\n}\n</script>\n<style>\n  h1 {\n    color: red;\n  }\n</style>' > App.vue`
3. `mpvue-simple --build --entry ./App.vue`

**采用node.js的方式，依然是相同的问题**。

**期望的表现:**

生成编译后的文件

**观察到的表现:**

一直在building，五分钟后都不动

**附注**
node版本：v10.0.0
npm版本：v5.6.0

**Comment by anchengjian** [comment]
再试一下，刚刚锁了 mpvue-simple 中的某依赖的版本，应该是可用的。
