### ISSUE TITLE
执行npm run dev后不动

### ISSUE THREAD

**Issue by rmchen-12** [Meituan-Dianping/mpvue#518]
# [问题简单描述]
执行npm run dev后调用node build/dev-server.js，然后就一直这样了，等了很久都没反应

**期望的表现:**
显示编译成功或失败

**观察到的表现:**
不会显示编译结果

**Comment by rmchen-12** [comment]
可以了，换了个编辑器后可以正常编译了，搞不懂什么原理。。。

**Comment by kenberkeley** [comment]
same issue
