### ISSUE TITLE
appServiceSDKScriptError Converting circular structure to JSON; at wx.invokeWebviewMethod TypeError: Converting circular structure to JSON

### ISSUE THREAD

**Issue by Sniper-2** [Meituan-Dianping/mpvue#519]
![image](https://user-images.githubusercontent.com/27018323/40339620-d5a1cd0c-5dad-11e8-8bea-0b79146a3271.png)

# [问题简单描述]
成功连接socketio后，后台也响应到小程序发送过去的群聊消息，但是开发者工具控制到报错，在真机调试下也报错，请问有什么具体的解决方法吗？

**观察到的表现:**
![image](https://user-images.githubusercontent.com/27018323/40339737-57ab5b42-5dae-11e8-9584-238b67620806.png)
![image](https://user-images.githubusercontent.com/27018323/40339757-695e50a6-5dae-11e8-9544-d271a5424528.png)
![image](https://user-images.githubusercontent.com/27018323/40339773-78d2b81a-5dae-11e8-8691-67b38f9a203f.png)
![image](https://user-images.githubusercontent.com/27018323/40339774-7e681478-5dae-11e8-892f-6c4e2c9ff757.png)

**Comment by anchengjian** [comment]
环形 Object 被 JSON.stringify 了，检查下 console 和 JSON.stringify 的地方

**Comment by shuizhongyueming** [comment]
@anchengjian 为**console**点赞，我就是`console.log(this)`，把整个vue实例log出来debug，结果安卓下就报错了，查了半天
