### ISSUE TITLE
<button bindgetphonenumber="getPhoneNumber">获取手机号</button>其中的bindgetphonenumber编译后就没了

### ISSUE THREAD

**Issue by gz65555** [Meituan-Dianping/mpvue#52]
bindgetphonenumber是调用微信获取手机号的授权窗口的回调，拿到授权的加密信息。但是在mpvue里编译过后，dist里面的bindgetphonenumber就没有了

**Comment by gz65555** [comment]
找到答案了，谢谢某位大牛。
把bindgetphonenumber改成@getphonenumber就ok了
<button @getphonenumber="getPhoneNumber" open-type="getPhoneNumber">获取手机号</button>

**Comment by lianjie5664** [comment]
mark

**Comment by fangqingqing2** [comment]
Cannot read property 'encryptedData' of undefined

**Comment by fangqingqing2** [comment]
Cannot read property 'encryptedData' of undefined，获取号码时报这个错，有知道原因的吗

**Comment by JesseZhao1990** [comment]
> Cannot read property 'encryptedData' of undefined，获取号码时报这个错，有知道原因的吗

e.target.encryptedData 就可以了
