### ISSUE TITLE
示例程序中的跳转不起效

### ISSUE THREAD

**Issue by aboutqx** [Meituan-Dianping/mpvue#523]
# [问题简单描述]
示例程序中的跳转在几次来回之后不起效不起效
**问题复现步骤:**

1. [第一步] 按照教程到示例的首页,点击下放区网示例页面
2. [第二步] 点击去往首页
3. [其他步骤...] 来回点击这2个按钮,3次以后就不跳转了

**期望的表现:**

[在这里描述期望的表现]
正常切换跳转
**观察到的表现:**

[在这里描述观察到的表现]
三次以后按钮失效,无法跳转
**屏幕截图和动态 GIF 图**

![复现步骤的屏幕截图和动态 GIF 图](图片的 url)
![1](https://user-images.githubusercontent.com/4919094/40352423-5fd649e8-5de1-11e8-87f1-97607bd9d7b7.gif)

**Comment by aOrz** [comment]
小程序有跳转层级限制，超过限制后不能跳转，建议看下小程序的文档
