### ISSUE TITLE
输入框在绑定数据后快速输入/删除时概率出现回退

### ISSUE THREAD

**Issue by zhangbinalex** [Meituan-Dianping/mpvue#524]
不管是用v-model还是手动 :value 和 @input， 只要输入框绑定了数据后，一旦快速输入或者一直按住删除键，输入框就会概率出现回退问题，体验很差。。现在小程序准备发版了，这个问题还不知道怎么解决。。很难受呀

使用lazy修饰符的话回退是没有了，但无法实时根据绑定的值渲染（比如有内容时出现‘发送’按钮）
如果输入框不和数据进行绑定的话，就无法清空输入框

看了下一二十天前相关的issue，好像还没有一个结论，不知道现在有没有修复这个问题呢？

**Comment by lanshengzhong** [comment]
新版貌似是可以了

**Comment by zhangbinalex** [comment]
@lanshengzhong 是吗？ 我刚才更新了一下mpvue  mpvue-loader mpvue-template-compiler 的版本到最新了，然而还是疯狂回退啊， 还有老哥那个 红楼梦之美 是啥，去哪搜？

**Comment by lanshengzhong** [comment]
红楼梦之美是我公司的小程序 升级新版之火没有这个问题了哦

**Comment by zhangbinalex** [comment]
@lanshengzhong  兄弟你确定没问题吗。。我刚才试了下，并没有好啊。。。你试试切到数字键盘四个指头快速输入，然后一直点击删除。。。。难道是我手机太垃圾了？ = =

**Comment by lanshengzhong** [comment]
好的吧  你不知道旧版都不能用 ，现在的还能接受吧

**Comment by dowinweb** [comment]
用小程序原生的表单提交的方式可以解决

**Comment by shaonialife** [comment]
#639 看看这个
