### ISSUE TITLE
当组件slot内为变量时，不显示

### ISSUE THREAD

**Issue by dream2023** [Meituan-Dianping/mpvue#526]
代码如下：
![e1130953-f607-4515-9100-65f1f2f6d4b8](https://user-images.githubusercontent.com/19297757/40362941-9624a8cc-5e00-11e8-9519-07717ab6a69c.png)

问题描述：
当外部使用此component时：
<test>123</test> 正常显示
<test>{{123}}</test>  正常显示
<test>{{count}}</test>  不显示

**Comment by linrui1994** [comment]
#427

**Comment by dream2023** [comment]
@linrui1994 原谅我太小白，请问这个问题是解决了吗，还是没解决？

**Comment by linrui1994** [comment]
没有

**Comment by LiangFuzhi** [comment]
同样遇到相同问题

**Comment by hughfenghen** [comment]
@LiangFuzhi 这里其实还有一个bug，slot用了子组件的作用域，实际上在初次执行的时候还会去父组件取一下绑定的值。
以楼主的例子，如果父组件中没有在data中注册`count`变量也会报错。

我的处理方式是，slot要用到变量都包在`props: scope`中传递到组件，然后在父组件data中注册一个空的`scope: {}`变量。

例：
```html
<image-previewer :scope="{ deleteIcon }">
  <img class="delete-photo" :src="scope.deleteIcon" >
</image-previewer>
```

```js
export default {
  data() {
    return {
        scope: {}, // 占位，mpvue的bug，slot中绑定的状态必须在父组件注册，不然会报错
    }
  }
}
```

**Comment by limichange** [comment]
😅 slot问题太多，最好不要往里面传东西。

**Comment by Stupidism** [comment]
mpvue 问题太多, 最好不要用了 直接用 web-view 吧
