### ISSUE TITLE
嵌套组件插槽内容不显示

### ISSUE THREAD

**Issue by dream2023** [Meituan-Dianping/mpvue#527]
问题描述：
组件Test使用TestA，TestA使用TestB，组件Test传递的插槽值不显示

代码如下：
![3](https://user-images.githubusercontent.com/19297757/40363978-ac55ddf2-5e03-11e8-92aa-c71dbb75729f.png)
![1](https://user-images.githubusercontent.com/19297757/40364099-f94b7c52-5e03-11e8-8806-34a659f01df7.png)
![2](https://user-images.githubusercontent.com/19297757/40364101-fc050b34-5e03-11e8-903b-dc4db1e5fb39.png)

**Comment by ANT-CYJ** [comment]
放心吧，我已经收到啦。
