### ISSUE TITLE
如何进行Web端开发调试？

### ISSUE THREAD

**Issue by Johcha** [Meituan-Dianping/mpvue#532]
#如何进行Web端开发调试？

**问题复现步骤:**

1. 修改config/index.js中autoOpenBrowser: true
2. 修改port: 8282
3. npm run dev
4.不能自动打开浏览器,并且手动打开浏览器http://localhost:8282/访问失败

**期望的表现:**

可以在浏览器中同时对页面进行开发调试工作

**观察到的表现:**

Cannot GET /

**观察到的目录结构:**

1.编译后dist文件夹中不包含html文件,.wxss文件只能在微信小程序中运行。。。

**项目如何配置才可以在web端进行调试或发布？**

**Comment by melongz** [comment]
这个应该需要自己手动转换吧 [https://segmentfault.com/a/1190000013977813](url)

**Comment by youngcube** [comment]
#103
