### ISSUE TITLE
this.$root.$mp 为 undefined,  console.log(this.$root) 明明可以看到 $mp的....

### ISSUE THREAD

**Issue by ql2005** [Meituan-Dianping/mpvue#533]
按照文档`this.$root.$mp.query` 获取参数
结果取不到,调试发现console.log(this.$root) 明明可以看到 $mp
下一行console.log(this.$root.$mp)就变成了undefined...
这是什么鬼??....
如图
![](https://wx1.sinaimg.cn/mw690/64cfe490gy1frl4ia31tjj206w0120so.jpg)
![](https://wx1.sinaimg.cn/mw690/64cfe490gy1frl4ibtlakj20im03mdgg.jpg)
![](https://wx1.sinaimg.cn/mw690/64cfe490gy1frl4idtylmj2067017747.jpg)

**Comment by F-loat** [comment]
onLoad 触发后才能获取到参数

**Comment by ql2005** [comment]
囧, 2了, 随便挑了个地方写, 没注意生命周期还没进入onLoad
