### ISSUE TITLE
scroll-view滚动加载更多，数据更新无法保持位置，自动返回顶部

### ISSUE THREAD

**Issue by ZTrainWilliams** [Meituan-Dianping/mpvue#536]
# [scroll-view滚动加载更多，数据更新无法保持位置，自动返回顶部]

**期望的表现:**

[有无更好的支持方法，在scroll-view滚动加载保持位置]

**观察到的表现:**

[使用scroll记录scrollTop不可取，容易造成抖动]

**Comment by shaonialife** [comment]
#316

**Comment by shengbaise** [comment]
请问问题解决了吗？为也遇到了同样到问题
