### ISSUE TITLE
v-if使用在slot标签上，报Template "default" not found.警告

### ISSUE THREAD

**Issue by dream2023** [Meituan-Dianping/mpvue#537]
# [问题简单描述]
v-if使用在slot标签上，就会报Template "default" not found.警告

**问题复现步骤:**
![wechatimg42](https://user-images.githubusercontent.com/19297757/40425544-3f7eb32a-5ecb-11e8-9c47-29522b461282.png)

![wechatimg43](https://user-images.githubusercontent.com/19297757/40425494-21ae32ee-5ecb-11e8-9063-282646a453bf.jpeg)

**Comment by Somefuture** [comment]
mpVue不是不暂时支持slot么
