### ISSUE TITLE
事件触发异常

### ISSUE THREAD

**Issue by dream2023** [Meituan-Dianping/mpvue#538]
**问题描述**
现在要做一个遮罩组件 mask ，点击mask组件能toggle显示，但其会自动触发通过slot插槽传递过去的按钮的click事件

**问题复现步骤:**
外部按钮-->click(mask显示)-->mask click -->触发 mask click事件 + mask 插槽按钮click事件

代码如下：
https://github.com/dream2023/issue/blob/master/index.vue
https://github.com/dream2023/issue/blob/master/mask.vue

**期望的表现:**
mask的click不应该触发插槽内button的click事件

**Comment by CZYAce** [comment]
+1  请问楼主解决了吗

**Comment by dream2023** [comment]
> +1 请问楼主解决了吗

没有，但是不用mpvue了，用uni-app开发了
