### ISSUE TITLE
关于页面实现loading效果的复用问题

### ISSUE THREAD

**Issue by tim0991** [Meituan-Dianping/mpvue#540]
# [问题简单描述]
希望在所有的page中能复用一个Loading组件，在进入页面数据未请求到时显示只loading，不显示page，在请求结束之后显示page，隐藏loading，便尝试使用hoc

`loadingHoc`
```js
export default (Page) => {
    return {
        components: {
            Loading
        },
        data() {
            return {
                _loadingLayer: true
            }
        },
        mountd() {
            this.hideLoadingLayer();
        },
        methods: {
            hideLoadingLayer() {
                this._loadingLayer = false;
            }
        },
        render(h) {
            return this._loadingLayer ? h(Loading, {}) : h(Page, {});
        }
    }
};
```

`page`
```vue
<template>
...
</template>
<script>
let page = {
    .....
};
export default loadingHoc(page);
</script>
```

后来搜索发现mpvue不支持自定义render，那有以下两个问题
1. 有没有迂回的办法实现自定义render
2. 不用hoc的话应该用什么方法能实现上述效果，并且可以最大程度复用代码？

**Comment by anchengjian** [comment]
自定义 render 意味会操作 DOM ，所以没办法自定义迂回实现。
复用的话，初略想了一下，比较原始：在根组件那个地方插入 loading ，然后封装统一的请求出入时候控制 loading 展示与否的变量。

**Comment by tim0991** [comment]
根组件是指`src/App.vue`吗？ 我刚试了一下 插入`template`标签就报错啊

**Comment by anchengjian** [comment]
每个页面下的 index.vue 都是一个根组件，小程序不是单页的概念

**Comment by tim0991** [comment]
那如果是在index.vue中添加loading的话，那是不是需要为不同的page每个都单独写一遍这个loading的相关代码

**Comment by shaonialife** [comment]
写个webpack的自定义loader, 在mpvue-loader执行之前把所有页面都插入组件的注册代码就行了

**Comment by tim0991** [comment]
@shaonialife 这样可以解决，但是太过于抽象，从代码层面来看不直观，不好管理

在我主观看来这个不是webpack层面的东西

**Comment by shaonialife** [comment]
@tim0991 小程序限制, 不能做到动态添加视图, 那索性静态注入, 让每个页面都有这个组件, 要不然只能每个页面都手动引入, 那就更不爽了

**Comment by shiweiqi19930328** [comment]
@tim0991
你们是不是简单问题复杂化了，全局注册一个loading组件不就行了，具体页面具体根据实际情况控制。
main.js： 
import loading from '@/components/loading'
Vue.component('loading', loading)
page页面：
<block>
       <div v-if="loaded">业务代码</div>
        <loading  v-else></loading>
</block>
