### ISSUE TITLE
页面之间传递参数

### ISSUE THREAD

**Issue by scutcl** [Meituan-Dianping/mpvue#542]
# 页面A -> 页面B  
页面B返回至页面A时，如何传递参数给页面A

**Comment by Howie126313** [comment]
使用 vuex 或者在跳转的时候路径？后面拼接参数

**Comment by F-loat** [comment]
存在全局，哪种形式都可以，然后在 onShow 里获取并重置

**Comment by hucq** [comment]
小程序本身支持的参数传递方式很多，`mpvue` 框架本身不提供额外支持，可能的方式有：
1. app global 对象
2. 本地存储
3. 通过事件 订阅+发布 的三方库，或者自实现都可以

**Comment by ananiy** [comment]
@F-loat 如果我想要用户第一次打开的时候传递参数 就必须用 /pages/index/main?key=value 这种形式了吧
然后我怎么样可以重置url到 /pages/index/main 呢 
直接redirectTo会导致页面刷新

所以最终我想要的是  
用户第一次点击 或者说 点了别的分享 都会传参数过来 然后我再onShow里边处理完参数
将 url 重置 

否则每次 show 都会调用处理函数...

**Comment by F-loat** [comment]
@ananiy 你应该在页面的 onLoad 或 app 的 onShow 里执行逻辑

**Comment by ananiy** [comment]
@F-loat 我就是在page的onShow里面执行逻辑 然后不是每次onShow执行
如果判断场景值 也会有问题
url又重置不掉

**Comment by F-loat** [comment]
@ananiy 你仔细看下我回复你的，另外不要考虑重置 url 这种了，实现方式很多的吧

**Comment by ananiy** [comment]
@F-loat 那如果我分享出去小程序 应该怎么样携带参数...然后获取呢? 
如果用onLoad, 如果用户是在打开过小程序的状态下, 再去点击新的分享链接, 这时候onLoad不就不执行了吗 囧rz

**Comment by F-loat** [comment]
@ananiy 请阅读小程序官方的文档，分享的参数是推荐在 app 的生命周期里获取的吧

**Comment by ananiy** [comment]
@F-loat 这个推荐在哪... 我怎么找不到呢 囧 
我不觉得把逻辑移到app的生命周期能解决我说的问题诶

**Comment by F-loat** [comment]
@ananiy 😐 你加点逻辑判断也可以的吧，onShow 时的参数保存起来，每次对比下，不一致再执行后面的逻辑。。

**Comment by ananiy** [comment]
@F-loat 😢我加不了啊 每次onShow我怎么知道是从分享点进来的还是从别的入口点进来的...那个场景值会保留诶 如果我是从分享点进来的 $root.$mp.appOption不会变了...

**Comment by F-loat** [comment]
@ananiy 首先你需要清楚 page 只有 onLoad 钩子可以获得参数，而且只有 url 里的 query，而 app 的 onLaunch 及 onShow 是可以获取场景等额外信息的，其次这些信息都没有缓存，每次的参数都是当次的信息，这些信息足以判断应该进行何种操作，最后 $root.$mp.appOption 是 mpvue 替你保存的一份参数信息，方便调用，但应该只有 onLoad 触发时才会更新，所以不一定能代表页面当前的状态，具体怎么做你就自己考虑吧

**Comment by ananiy** [comment]
@F-loat 搞明白了 十分感谢!
