### ISSUE TITLE
重复进入page时，page里component的mounted事件没有触发

### ISSUE THREAD

**Issue by linfan68** [Meituan-Dianping/mpvue#543]
# [问题简单描述]
页面里面的Component的mounted事件只在这个页面第一次展示的时候调用
如果重复进入同一个页面的话，Vue Instance被复用所以没有created事件，Page的mounted事件被调用了，但是Page里面的Component的mounted事件没有被调用

**问题复现步骤:**
新建两个页面A和B
A里面一个按钮调用wx.navigateTo(B)
B里面放一个compoment C
A作为起始页

打开A，点击按钮去B，后退到A，再点击去B

**期望的表现/观察到的表现** 
```
[page-A] beforeCreate()
[page-A] created()
[page-B] beforeCreate()
[page-B] created()
[page-A] onLoad()
[page-A] onShow()
[page-A] onReady()
[page-A] beforeMount()
[page-A] mounted()
-------------NAVIGATION TO B-------------
[page-A] onHide()
[page-B] onLoad()
[page-B] onShow()
[page-B] onReady()
[page-B] beforeMount()
[Comp-C] beforeCreate()
[Comp-C] created()
[Comp-C] beforeMount()
[Comp-C] mounted()
[page-B] mounted()
-------------GO BACK-------------
[page-B] onUnload()
[page-A] onShow()
-------------NAVIGATION TO B-------------
[page-A] onHide()
[page-B] onLoad()
[page-B] onShow()
[page-B] onReady()
[page-B] beforeMount()
[page-B] beforeUpdate()
[page-B] mounted()
>>> [Comp-C] beforeMount() <<< 这两个事件没有触发
>>> [Comp-C] mounted() <<< 这两个事件没有触发
[Comp-C] beforeUpdate()
[Comp-C] updated()
```

再怎么说，父节点（PAGE-B）被mount了之后，子节点（Comp-C）的mount也得被调用吧？

**Comment by F-loat** [comment]
组件里尽量不要用生命周期吧

**Comment by linfan68** [comment]
@F-loat 着我是同意的，可是如果要处理一些比较复杂的有状态的空间（比如坑爹的<video>），没有生命周期做一些初始化/清理工作根本不行……
目前我想到的workaround是组件mount好了emit一个事件给上层，在参数里面给两个callback，然后上面的page接住了之后吧自己的生命周期事件forward给这个回掉……

**Comment by linfan68** [comment]
@F-loat 有没有什么hack的方法能够在component里面找到page的vue instance然后偷偷注册一下生命周期回掉？其实真正要用的地方也不多，hack一下是可以的……

**Comment by F-loat** [comment]
你是要做什么啊，组件内的 data 尽量还是设计成状态无关的比较好，有关状态的数据通过 props 传递，或者说目前为了规避这个问题需要这样设计

**Comment by F-loat** [comment]
父组件的东西子组件都可以调用的，但是这样太强耦合了吧

**Comment by F-loat** [comment]
可以在父组件调用子组件的方法这样？

**Comment by linfan68** [comment]
父组件调用子组件方法的推荐做法是什么呢？目前我们的方法是子组件emit一个事件，把自己的控制interface扔出去让父组件接住，然后就可以调用了。这就是我说的第一个方法。
但是这样的问题是每次setup这个组件步骤很多，还涉及到事件顺序的问题，从Page级别开始所有的父组件需要理解里面有一个特殊的组件

所以后来我想有没有让子组建更“自制”的方法，用某个方法直接找到自己属于哪个Page，然后把自己的callback注册到Page的生命周期里面。这样虽然dirty一些，但是封装的更好，污染区域小，用起来更像一个”纯数据“的组件。

**Comment by F-loat** [comment]
可以通过 ref 获取到组件实例的，然后直接调用相应的方法就可以

**Comment by linfan68** [comment]
刨了下源代码，我现在倾向于这样处理，在Component里面的create或者mount里面加这么一句：

```
this.$parent.$options.onShow.push(() => {
  console.log('Parent page show()')
})
```

还需要做一些特殊处理，比如组件第一次create的时候应该是在Page.onShow()之后的了，得补一个event，还有要处理多层parent的情况，可以用`$parent.$mp.mpType === ‘page’`找到根上的page

@F-loat 这样处理您觉得怎么样呢?

**Comment by F-loat** [comment]
不太懂，在父组件里调用子组件的方法不是更合理一点，会有什么问题吗

**Comment by linfan68** [comment]
嗯上面两件事儿说的有点儿乱，有两个问题
1. Parent要调用子组件的方法，使用ref比较方便，我上面说的那种emit事件确实不如用ref直接调

2. 子组件需要根据Page的生命周期做一些initialization和cleanup。这个我觉得用后面我说的子组件注入Page的handler列表的方法更合理一些，这样子组件的用户不需要知道子组件需要特殊处理这件事儿，只要当作一个正常的data-driven的组件用就可以了

**Comment by F-loat** [comment]
嗯，第二个也可以吧，但是感觉出问题的话会不便于调试，一般还是提供方法给用户调用

**Comment by limichange** [comment]
这是一个bug，我建议reopen。父类mounted之后子组件肯定是要触发的。

**Comment by limichange** [comment]
这是因为组件没有的被销毁，一直存在。

**Comment by hughfenghen** [comment]
虽然利用组件mounted钩子不一定合理，但mounted钩子还是应该触发。
应该跟页面组件保持一致，从运行机制来理解也更合理。

**Comment by xchz** [comment]
这是真的有点坑..

**Comment by GuardianRay** [comment]
页面引用组件时加 v-if 进行销毁设置
