### ISSUE TITLE
关于bind Style 后设置 backgroundImage 的 url

### ISSUE THREAD

**Issue by Howie126313** [Meituan-Dianping/mpvue#544]
#  [问题简单描述]
通过 bind style 来设置背景图片时，小程序报错变量为 not defined
**问题复现步骤:**
代码如下：
```
     <div class="emptyCards" :style="{backgroundImage: `url(${pictures.exampleCard})`}"></div>
```

**Comment by Howie126313** [comment]
使用字符串拼接后好用但是报错
```
      <div class="emptyCards" :style="{background: 'url(' + pictures.exampleCard + ')'}"></div>
```
<img width="502" alt="9574cea37e5677c4e749b62e189ab914" src="https://user-images.githubusercontent.com/32697672/40468519-3740e2ec-5f60-11e8-9111-8a95aef61537.png">

**Comment by Howie126313** [comment]
这个变量是一个网络连接
  exampleCard: 'http://img.798youxi.com/product/upload/5b0658831777f.png'

**Comment by F-loat** [comment]
exampleCard 这个变量以文本的形式是可以正常显示的吗

**Comment by Howie126313** [comment]
@F-loat 才看到不好意思... 是的可以正常显示，背景图也可以正常渲染。

**Comment by Howie126313** [comment]
@F-loat 效果啥的都实现了。。就是报错。。很烦 想知道原因

**Comment by F-loat** [comment]
你加个判断吧，估计那个值开始的时候不存在

**Comment by Howie126313** [comment]
@F-loat 可以了 就很尴尬... 原因是什么那..

**Comment by F-loat** [comment]
数据是异步请求的话，pictures 初始值估计是个空对象吧，那个属性自然是 undefined

**Comment by Howie126313** [comment]
@F-loat 不是 picture 是 import 进来的一个保存图片地址的对象

**Comment by F-loat** [comment]
emmm 那就不清楚是怎么回事了

**Comment by Howie126313** [comment]
@F-loat 多谢~

**Comment by kungfuboy** [comment]
@Howie126313 请问判断是怎么加的？

**Comment by xiaowuzei** [comment]
判断怎么加的？

**Comment by Howie126313** [comment]
@kungfuboy  就直接判断 pictures.exampleCard 就可以

**Comment by Arman19941113** [comment]
我也是报错，开发者工具可以显示，ios无法显示
