### ISSUE TITLE
组件中写的css不生效

### ISSUE THREAD

**Issue by hgq520** [Meituan-Dianping/mpvue#546]
# [问题简单描述]

**问题复现步骤:**

1. [第一步]
2. [第二步]
3. [其他步骤...]

**期望的表现:**

[在这里描述期望的表现]

**观察到的表现:**

[在这里描述观察到的表现]

**屏幕截图和动态 GIF 图**

![复现步骤的屏幕截图和动态 GIF 图](图片的 url)

**Comment by aOrz** [comment]
请按照 issue 规范提问题，提供更多更多的细节信息，以供排查问题。
