### ISSUE TITLE
有计划支持分包加载么？

### ISSUE THREAD

**Issue by Howie126313** [Meituan-Dianping/mpvue#548]
# [问题简单描述]
项目开发需求功能越来越多优化之后也接近2M了，还有需求未完成。请问 mpvue 会支持分包加载么？

**Comment by Howie126313** [comment]
@F-loat

**Comment by F-loat** [comment]
分包加载好像得调整一些打包策略才有实际意义，你可以先在图片和代码的压缩上做些优化

**Comment by Howie126313** [comment]
@F-loat ok 也可能我这边产品规划的不太合理。功能太多，感觉做完会很重。

**Comment by hucq** [comment]
同 #26 #106 ，目前暂未提供分包构建。在计划中，一旦支持，我们会第一时间在文档中注明。建议提issue之前先搜索issue列表，对于相同的问题，你能更快知道答案。
