### ISSUE TITLE
编译后提示 vendor.js文件过大，跳过ES6 转 ES5 和压缩的处理

### ISSUE THREAD

**Issue by SevenChen** [Meituan-Dianping/mpvue#550]
# [问题简单描述]
以下 JS 文件过大（超过 500K），已跳过 ES6 转 ES5 和压缩的处理：
static/js/vendor.js

因为要考虑兼容性问题，这个有办法解决吗？

**Comment by aOrz** [comment]
mpvue 的构建工具已经有 ES6 转 ES5 和压缩功能，可以关闭开发者工具的这些功能

**Comment by SevenChen** [comment]
好的，3q

**Comment by ZhuRuiHeng** [comment]
请问楼主怎么解决的，我安装npm i mpvue-echarts运行也报这个错

**Comment by ZhuRuiHeng** [comment]
安装npm i mpvue-echarts编译后提示 vendor.js文件过大

**Comment by ZhuRuiHeng** [comment]
请问楼主怎么解决的，我安装npm i mpvue-echarts编译后也提示 vendor.js文件过大

**Comment by DearAKuan** [comment]
我也碰到了一样的问题 压缩过后都超过500kb了 现在上传了功能错误。。怎么出阿里

**Comment by SevenChen** [comment]
@ZhuRuiHeng @DearAKuan 这个其实文件过大没关系的。

如果碰到有的js不兼容es6的花，要自己写一个转换的
我在我的package.json里面加了一个 es5 转换程序 
npm run build 之后再 npm run es5 之后再上传到小程序平台

"scripts": {
    "dev": "node build/dev-server.js",
    "start": "node build/dev-server.js",
    "build": "rimraf \"dist/pages/!(ohqmore)\" && node build/build.js",
    "es5": "babel ./dist/static/js/vendor.js -d ./"
  },

注意：run es5之前要改一下 ，吧plugins 改成空数组，run build 之前不用改

.babelrc 文件
  //"plugins": ["transform-runtime"],
  "plugins": [],
