### ISSUE TITLE
npm run dev 后出现UnhandledPromiseRejectionWarning

### ISSUE THREAD

**Issue by onyz4x** [Meituan-Dianping/mpvue#556]
# [问题简单描述]
按照官方五分钟教程，当进入npm run dev步骤的时候  出现问题

**问题复现步骤:**

![image](https://user-images.githubusercontent.com/15812120/40600674-f0294e6c-6284-11e8-9b5f-01e7f6f19f56.png)

**Comment by F-loat** [comment]
#555

**Comment by CarmenHYC** [comment]
遇到同样的问题，之前的项目更新后跑不起来了，好像是因为  :class="{active: isActive}" 这种语法写在标签里出的错，应该是mpvue-template-compiler更新后出了问题

**Comment by onyz4x** [comment]
更新了prettier后就出现这个问题
解决问题的方法 F-loat 已经提供了  安装老版本的prettier
npm install --save-dev prettier@1.12.0
