### ISSUE TITLE
npm run dev 出错( UnhandledPromiseRejectionWarning / DeprecationWarning )

### ISSUE THREAD

**Issue by jxj322991** [Meituan-Dianping/mpvue#559]
# 按照官方文档步骤,在 npm run dev 时出错

**问题复现步骤:**

1. 按照文档   $ vue init mpvue/mpvue-quickstart my-project  => $ cd my-project => $ npm install => npm run dev
2. 终端出现警告提示: UnhandledPromiseRejectionWarning / DeprecationWarning
![0](https://jxj322991.github.io/2018imgs/error/052801.png)
3. 构造进程卡住,不在运行

**Comment by F-loat** [comment]
#555，提问前先看下已有 issue，谢谢
