### ISSUE TITLE
v-bind:style写法无效

### ISSUE THREAD

**Issue by hzfhhh** [Meituan-Dianping/mpvue#56]
如题，不支持v-bind:style，比如在vue中这样写`:style="{'background-color': bgColor}"`,编译后小程序对应的地方变成这个样子：`style="background-color"`

**Comment by lyh2668** [comment]
可以考虑写到computed里面，这个文档上有描述

**Comment by ZhuRay** [comment]
我也遇到

**Comment by ZhuRay** [comment]
绑定样式对象方法也无效，`<div v-bind:style="styleObject"></div>`编译出来的结果是`<view style="[object Object]">`

**Comment by KingNight67** [comment]
用计算属性拼接字符串吧- -

**Comment by gz65555** [comment]
+1 希望能支持绑定属性

**Comment by anchengjian** [comment]
已置为P0需求 https://trello.com/c/Jo7gJEd4/8-class-%E4%B8%8E-style-%E7%BB%91%E5%AE%9A%E6%94%AF%E6%8C%81%E5%A4%8D%E6%9D%82%E8%A1%A8%E8%BE%BE%E5%BC%8F

**Comment by anchengjian** [comment]
https://github.com/Meituan-Dianping/mpvue/releases/tag/1.0.3 修复了
