### ISSUE TITLE
npm run dev编译不成功，也不报错

### ISSUE THREAD

**Issue by 2015-lizaiyang** [Meituan-Dianping/mpvue#562]
# [问题简单描述]
在vue文件中不加入<style></style>和<script></script>会出现无法编译，一直在
```ssh
$ node build/dev-server.js
```
也不出现报错提示

**问题复现步骤:**
1. [第一步]
在pages新建一个目录
在目录里的vue文件中加入
```
<template>
  <div>
    首页
  </div>
</template>
```
2. [第二步]
运行npm run dev

**期望的表现:**
期望能正常编译，或者提示错误
[在这里描述期望的表现]

**观察到的表现:**
无法编译，一直停留在
```ssh
$ node build/dev-server.js
```
也不报错
[在这里描述观察到的表现]
![image](https://user-images.githubusercontent.com/21666293/40633450-6a293c8e-6322-11e8-8872-5a621c2b4fea.png)

![复现步骤的屏幕截图和动态 GIF 图](图片的 url)

**Comment by F-loat** [comment]
style 应该已经有默认值了，缺 script 确实会有这个问题，可以也加下默认值，但是为什么会没有写 script 呢。。

**Comment by Lyplba** [comment]
战略mark，今天给这玩意坑了几个钟😭

**Comment by kilohaty** [comment]
确实是缺少script标签的坑，尴尬了😂

**Comment by DevinWell1ee** [comment]
。。。真的坑

**Comment by kenberkeley** [comment]
same issue

**Comment by sunmydream** [comment]
好吧，看来不是我一个人有这个问题，真的是script的问题，补上就OK了
