### ISSUE TITLE
小程序从首页点击进其他的页面就卡，有遇到过这个问题的吗？

### ISSUE THREAD

**Issue by lww555** [Meituan-Dianping/mpvue#565]
小程序从首页点击进其他的页面就卡，有遇到过这个问题的吗？

**Comment by F-loat** [comment]
真机吗，开发工具的话无所谓的

**Comment by hucq** [comment]
@lww555 你这个问题描述没有任何上下文，我们无从排查！
这不是好的提问方式。可以参考一下其它 issue 怎么写的。
