### ISSUE TITLE
如何引用小程序插件

### ISSUE THREAD

**Issue by weiyunpeng** [Meituan-Dianping/mpvue#568]
如果想在mpvue中使用小程序插件，在页面中该如何获取
**问题复现步骤:**

1. [第一步]
在main.js中加入
plugins: {
      WechatSI: {
        version: '0.0.6',
        provider: 'wx069ba97219f66d99'
      }
    },
2. [第二步]
在页面中引用
const plugin = requirePlugin('WechatSI');
报 'requirePlugin' is not defined 

**期望的表现:**
可以使用小程序插件功能

**Comment by aOrz** [comment]
.eslintrc.js 里面 添加 
`
globals: {
    App: true,
    Page: true,
    wx: true,
    getApp: true,
    getPage: true,
    requirePlugin
  }`

**Comment by ziyehuang** [comment]
引入插件后报这个是什么情况啊？[non-writable] modification of global variable "String.prototype.startsWith" is not allowed when using plugins at app.json.
