### ISSUE TITLE
import导入的图片使用v-bind指令绑定到<img>的src上在小程序里显示为空

### ISSUE THREAD

**Issue by taoweicn** [Meituan-Dianping/mpvue#569]
# [问题简单描述]
使用官方提供的快速启动模板构建的项目，在.vue文件里用import导入图片并设置img的:src=图片地址，在微信开发者工具中发现渲染生成的image组件的src为空，如果直接写`<img src='../../图片地址'>`又能显示

**问题复现步骤:**

- 使用import导入本地图片
- 在data定义图片地址变量
- 设置img标签的:src等于图片地址

**观察到的表现:**

生成的image小程序原生组件的src属性为空

**屏幕截图和动态 GIF 图**

![_20180530201430](https://user-images.githubusercontent.com/25795549/40719977-d3b1c72c-6447-11e8-9264-03a7643e0e81.png)
![_20180530201453](https://user-images.githubusercontent.com/25795549/40719979-d3f590e2-6447-11e8-89ea-970e45be9d89.png)

**Comment by taoweicn** [comment]
我已经找到问题所在了，原因是在页面中引入上图那个TabBar的组件时，不能采用PascalCase的写法（即`<TabBar />`），而必须采用kebab-case写法（即`<tab-bar />`），不然data和生命周期都会失效，而在Vue里这两种写法都是可以的。
理论上.vue文件里会经过loader打包不存在这个问题，我猜测可能是mpvue-loader的bug，把这种组件当做普通html标签解析了，所以data和生命周期都失效了。有人能解释一下这个问题吗？

**Comment by F-loat** [comment]
https://github.com/Meituan-Dianping/mpvue/blob/master/src/platforms/mp/util/index.js#L7-L14
tabbar 是保留列表里的，尽量不要用这类常规组件名

**Comment by taoweicn** [comment]
@F-loat 了解了，谢谢
