### ISSUE TITLE
如何引入YDUI

### ISSUE THREAD

**Issue by lisztj** [Meituan-Dianping/mpvue#57]
引入YDUI，编译报错
`VM3320:2 ./static/css/app.wxss
 unexpected token "~"
  3405 | }
  3406 | 
> 3407 | .yd-radio>._input[type=radio]:disabled~.yd-radio-text {
       |                                       ^
  3408 |   color: #ccc;
  3409 | }
  3410 | 
(anonymous) @ VM3320:2`

**Comment by anchengjian** [comment]
虽然没用过 YDUI 但粗看文档发现这是个移动端的 UI 库，由于小程序平台限制，无法支持使用了 DOM或BOM 相关 API 的库和框架。

这个报错看起来是使用了兄弟选择器，小程序也并不支持这个选择器，postcss-mpvue-wxss 也暂未做处理，已列入计划 https://trello.com/c/TrdvXgBq/23-postcss-mpvue-wxss-%E4%BC%98%E5%8C%96。
