### ISSUE TITLE
为什么用了v-for="(item ,index) in items" 这种类型的语法，还是会有提示 Now you can provide attr "wx:key" for a "wx:for" to improve performance

### ISSUE THREAD

**Issue by FanYuanhe** [Meituan-Dianping/mpvue#570]
# [问题简单描述]
为什么用了v-for="(item ,index) in items" 这种类型的语法，还是会有提示 Now you can provide attr "wx:key" for a "wx:for" to improve performance
**问题复现步骤:**

1. [第一步]
2. [第二步]
3. [其他步骤...]

**期望的表现:**
应该没有提示的

**观察到的表现:**
v-for="(item ,index) in items"  后面继续添加 wx:key="" 提示消失
**屏幕截图和动态 GIF 图**

![复现步骤的屏幕截图和动态 GIF 图](图片的 url)

**Comment by F-loat** [comment]
vue 里使用循环也是要指定 key 的啊，用 vue 的写法
