### ISSUE TITLE
BUG：部分页面报错 invoking page() in async task 

### ISSUE THREAD

**Issue by zaxlct** [Meituan-Dianping/mpvue#572]
# [问题简单描述]

**问题复现步骤:**
假设有 10 个 page，其中有两个 page ，开发者工具上正常，iOS 9 和 部分低端安卓手机报这个错误
**期望的表现:**

**观察到的表现:**
"mpvue": "^1.0.12",
https://github.com/F-loat/mpvue-entry/issues/24#issuecomment-393387453

**Comment by lvjs** [comment]
解决了没，没有的话参考下这个
https://github.com/F-loat/mpvue-entry/issues/24

**Comment by zaxlct** [comment]
@lvjs 谢谢，已经解决了

**Comment by prozwang** [comment]
请问怎么解决的，我可能遇到类似的问题

**Comment by zaxlct** [comment]
@prozwang 
采用二分法，一点一点排查错误，肯定是某个语法不兼容导致的
