### ISSUE TITLE
全局安装完成后，vue init失败返回404

### ISSUE THREAD

**Issue by yh4922** [Meituan-Dianping/mpvue#574]
D:\project\> vue init mpvue/mpvue-quickstart my-project
  Unknown command init.
? Generate project in current directory? Yes
   vue-cli · Failed to download repo vuejs-templates/[object Object]: Response code 404 (Not Found)

为啥啊

**Comment by imvicchen** [comment]
同问！我也遇到了

**Comment by F-loat** [comment]
暂时使用 vue-cli@2.9.3 版本吧，新版的问题

**Comment by F-loat** [comment]
vue-cli@2.9.4 改了命令，应该使用 `vue-init mpvue/mpvue-quickstart my-project`

**Comment by ZHBITXJX** [comment]
同样的错误marvin@Insomnia:~/myproject$ vue init mpvue/mpvue-quickstart first

  A newer version of vue-cli is available.

  latest:    2.9.6
  installed: 2.9.3

   vue-cli · Failed to download repo mpvue/mpvue-quickstart: Response code 404 (Not Found)

**Comment by yison-king** [comment]
弱弱的问句 怎么处理 我也遇到 这个问题

**Comment by imvicchen** [comment]
> 弱弱的问句 怎么处理 我也遇到 这个问题

楼上有回答~

**Comment by zhengyixin** [comment]
改成2.9.3版本也不行
