### ISSUE TITLE
嵌套组件传值的问题

### ISSUE THREAD

**Issue by ranwawa** [Meituan-Dianping/mpvue#575]
### 业务背景
-------------
####模仿拼多多的抢购进度条效果,如下

![image](https://user-images.githubusercontent.com/30344590/40765517-4382b4ca-64df-11e8-90a9-31c633a6a298.png)

- 商品列表是一个组件`goods`,循环渲染一个商品
- 进度条是一个组件`progress`,在商品列表的循环中进行引入
### 遇到的困难
-------
- 渲染组件时,进度条组件`mounted`钩子里面打印的值分别是`30` `90`
- 最终渲染完成后
- 每个商品的进度条数据都是取的最后一个商品的进度条数据`90`
### 示例代码
--------
>index.vue
```
<template>
  <goods :list.sync="list"></goods>
</template>
<script>
  import goods from 'componects/goods';
  data () {
    return {
      list:[
        {name:'xx', progress: 30},
        {name:'bb', progress: 90},
      ]
    }
  }
  components: {
    goods
  }
  ...
</scrip>
```
> goods.vue
```
<template>
  <div>
    <div v-for='item in list'>
      ...
      <progress :progress="item.progress"></progress>
      ...
    </div>
  </div>
</template>
<script>
  import progress from './progress';
  props: {
      list: Array
  }
  components: {
    progress
  }
  ...
</scrip>
```
>  progress.vue
```
<template>
  <div :progress="progress"> 进度条 </div>
</template>
<script>
  props: {
    progress: 0
  },
  mounted () {
    console.log(this.progress); // => 30,90
  }
</script>
```
### 问题
----
- 为什么会产生这样的问题?(感觉和闭包引用的问题一样)
- 有什么样的解决方法?

**Comment by ranwawa** [comment]
### 已解决
---------------
在`goods`组件里面,把`progress`组件名修改为`pp`即可
### 可是这是为什么?????
--------
期待你的回答

**Comment by js5323** [comment]
是小程序自有组件也有progress，progress标签没编译成你自定的组件

**Comment by aOrz** [comment]
http://mpvue.com/qa/#_3
