### ISSUE TITLE
input 使用小程序的 focus 后，键盘会莫名的跳出

### ISSUE THREAD

**Issue by LuDongWei** [Meituan-Dianping/mpvue#576]
`              
       <input type="text" class="search-bar__input" :focus="focusState" placeholder="搜索 关键字 / 商品款号 / 序号" v-model="inputVal"  @confirm="inputConfirm" />
 `

进入页面 设置  focusState = true , input获得了焦点了，键盘也弹出了正常，但是一输入文字，键盘就出现不正常的跳出

![ezgif-1-daabf1bbae](https://user-images.githubusercontent.com/7650992/40768846-0365bfcc-64e9-11e8-8fa9-1d194c6f6e9e.gif)

**Comment by shaonialife** [comment]
原因 #500 解决方案 #639
