### ISSUE TITLE
两次for循环使用indexOf判断字符串全部返回包含，将其返回渲染在页面为空白

### ISSUE THREAD

**Issue by qinxuanyu** [Meituan-Dianping/mpvue#579]
# [问题简单描述]

**问题复现步骤:**

1. [第一步]
两次for循环使用indexOf判断字符串全部返回包含，将其返回渲染在页面为空白
 2. [第二步]
3. [其他步骤...]
![1527827555 1](https://user-images.githubusercontent.com/23647423/40821215-0cd0361e-6598-11e8-9bf3-6e09cebaf9f3.png)

**期望的表现:**

[在这里描述期望的表现]

**观察到的表现:**

[在这里描述观察到的表现]

**屏幕截图和动态 GIF 图**

![复现步骤的屏幕截图和动态 GIF 图](图片的 url)

**Comment by taditang** [comment]
[http://mpvue.com/mpvue/#javascript](url)
大概是因为不支持复杂的javascript表达式，建议是之前处理一遍数据，模板里只需要使用一个变量

**Comment by aOrz** [comment]
小程序模板的限制，暂不支持在模板中使用 function
