### ISSUE TITLE
自定义弹出层  无法阻止主页面的滑动

### ISSUE THREAD

**Issue by LIZHIBIN513** [Meituan-Dianping/mpvue#580]
# [问题简单描述]
自定义弹窗  无法阻止主页面的滑动，每一个页面不能定位生成的小程序中page标签，无法设置overflow:hidden
**问题复现步骤:**

1. [第一步]
2. [第二步]
3. [其他步骤...]

**期望的表现:**

[在这里描述期望的表现]

**观察到的表现:**

[在这里描述观察到的表现]

**屏幕截图和动态 GIF 图**

![复现步骤的屏幕截图和动态 GIF 图](图片的 url)

**Comment by HadesMoon** [comment]
你可以给除了page之外的最外层标签设overflow:hidden

**Comment by gzlock** [comment]
@HadesMoon 这样会造成滚动位置归零

**Comment by mosade** [comment]
如果有蒙层 在蒙层添加个@touchmove.stop就行了

**Comment by hucq** [comment]
问题1：自定义弹窗 无法阻止主页面的滑动
这是纯粹的前端交互实现问题，框架本身并不涉及。建议可以尝试类似scroll-view 之类方案。

问题2：每一个页面不能定位生成的小程序中page标签，无法设置overflow:hidden
page 标签有自动生成规则，并不建议直接依赖该标签做交互实现。如果需要，可以将页面内容添加一层包裹并在包裹元素上进行设置。

**Comment by wufeng123456** [comment]
> 如果有蒙层 在蒙层添加个@touchmove.stop就行了

加了@touchmove.stop 外部是不会滚动   但蒙层内部的滚动也被禁止了
