### ISSUE TITLE
页面回传 除了全局对象,vuex,或者localstorage,能直接用getCurrentPages()拿到上一页setData吗

### ISSUE THREAD

**Issue by codeLittleNewbie** [Meituan-Dianping/mpvue#581]
# [问题简单描述]
页面回传时能使用getCurrentPages()拿到页面直接setData吗

**问题复现步骤:**
a -> b页,然后b页想回传值给a,使用getCurrentPages()拿到a后setData, 然后a页面的onshow方法里打印设置的值,发现没有变化

**Comment by F-loat** [comment]
558

**Comment by Lyplba** [comment]
刚好初次做小程序就遇到这个（我没想到过去用本地存储或者vuex、event bus之类的），以下提供下这边的操作：

A页面接收B页面返回的参数：
`
onShow() {
    let vm = this;
    let pages = getCurrentPages();
    let currPage = pages[pages.length - 1];
    if (currPage.data.yourData=== '1') {
        vm.updateSomething(vm.id);
    }
}
`

B页面设置要提供给A页面的参数：
`
let pages = getCurrentPages();
let prevPage = pages[pages.length - 2];

prevPage.setData({
    yourData: '1'
});
`
