### ISSUE TITLE
img中使用bindload事件无效

### ISSUE THREAD

**Issue by shengmi** [Meituan-Dianping/mpvue#583]
# [img中使用bindload事件无效]
**问题复现步骤:**
`
<img src="http://xxx.jpg" model="aspectFit" @load="imageLoad"/>
`
**methods中的imageLoad函数中打印语句不执行。**
**首次加载页面控制台打印警告**
`
VM5593:1 Do not have handler in current page: pages/note/main. Please make sure that handler has been defined in pages/note/main, or not use handler with 'v-if'
`

**Comment by F-loat** [comment]
load 事件是没问题的，请再检查下你的代码

**Comment by 0415ypt00** [comment]
解决了吗，我也是出现了这个问题

**Comment by hgq520** [comment]
把这个方法提到methods最上面就可以了
