### ISSUE TITLE
嵌套组件中使用slot无法正常渲染

### ISSUE THREAD

**Issue by heriky** [Meituan-Dianping/mpvue#585]
自定义组件中使用了slot传递内部组件，但是如果在嵌套组件中使用slot，slot对应的内容不会显示。请问这个问题有解决方案了吗？？？

### 定义组件
![image](https://user-images.githubusercontent.com/12195736/40895475-48d24c32-67e2-11e8-9bcc-b5f35930af31.png)

### 使用组件
![image](https://user-images.githubusercontent.com/12195736/40895463-3f25a1ca-67e2-11e8-97fe-28b86cb1757e.png)

**Comment by hualongdai** [comment]
这个 问题 好像到现在都不能支持！

**Comment by hnu0416** [comment]
试试把组件style上scoped属性去掉

**Comment by wjy4124** [comment]
试试把 组件名换成驼峰

**Comment by heriky** [comment]
@wjy4124  vue模板中本身不识别驼峰形式的写法吧

**Comment by hualongdai** [comment]
@heriky  支持驼峰的

**Comment by wjy4124** [comment]
这货好像不会自动 转换名命 components 里是驼峰 template 里就要用驼峰

**Comment by heriky** [comment]
@wjy4124 仍然渲染不出来，心塞。
![image](https://user-images.githubusercontent.com/12195736/41090994-21a6020a-6a78-11e8-9121-871726738ca7.png)
![image](https://user-images.githubusercontent.com/12195736/41091022-32e7ef74-6a78-11e8-9b04-c58dc361119a.png)

渲染出来嵌套组件内部的值全部失效。

这个问题大幅度限制了组件的组合能力。

**Comment by JRliu** [comment]
我也被坑了，但我无意中发现，mpvue@1.0.11，mpvue-template-compiler@1.0.11，mpvue-loader@1.0.13  的环境下嵌套组件的slot可以正常使用，其他情况slot的作用域跑到父组件那里去了

**Comment by zWingz** [comment]
@JRliu 我也恰好遇到这个问题...作用域跑到父组件上面去了

**Comment by zWingz** [comment]
@JRliu mpvue@1.0.11还真能解决问题..

**Comment by limichange** [comment]
@JRliu @zWingz 如果降版本就能正常是吗？

**Comment by limichange** [comment]
😅 发现降版本也没有用。

**Comment by heriky** [comment]
这个问题官方没打算修复一下吗

**Comment by zWingz** [comment]
@limichange 我降了版本可以用哦~, 我只降了mpvue和compiler.

**Comment by VimMing** [comment]
@JRliu 把版本换成1.0.11行是行， 有2个具名的slot， 它只给我渲染出一个， 列表有时渲染的出， 有时渲染不出， 真的被吓怕了

**Comment by JRliu** [comment]
@VimMing 我选择用小程序原生的代码实现那些嵌套slot的组件，mpvue做没嵌套的组件

**Comment by limichange** [comment]
🤣 但是降版本不会出别的问题嘛

**Comment by limichange** [comment]
@zWingz 能贴一下你的devDependencies吗？

**Comment by zWingz** [comment]
@limichange 需要slot的我都改用小程序原生组件了

**Comment by limichange** [comment]
@zWingz 你这个混用小程序原生组件是怎么做到的？
