### ISSUE TITLE
授权登录，获取头像失败

### ISSUE THREAD

**Issue by Hezhong123** [Meituan-Dianping/mpvue#586]
` wx.login({
        success: (res) => {
          console.log(res)
          wx.getUserInfo({
            success: (res) => {
              this.userInfo = res.userInfo
            }
          })
        }
      })`

**问题复现步骤:**

1. 登录
2. 获取用户信息
3.用户信息获取失败，wx.getUserInfo函数没有执行

**  疑问 **
是原生和mpvue的不兼容？？？

**Comment by shaonialife** [comment]
第一次调用  wx.getUserInfo 或者 用户关闭了授权, 都会失败, 只能用 <button open-type="getUserInfo"/> 方式调用, 只有获取成功, 后面都可以使用wx.getUserInfo来获取用户数据, 具体参考官网, 我的经验是 直接用 wx.getUserInfo 获取数据, 失败就跳到一个登陆页, 里面有一个 <button open-type="getUserInfo"/>, 用户点击之后把数据回传过来
![image](https://user-images.githubusercontent.com/16135960/40957212-a009b6ae-68c6-11e8-9eb5-0a811ea3886b.png)
