### ISSUE TITLE
打开多个同一页面回退问题

### ISSUE THREAD

**Issue by 948911908** [Meituan-Dianping/mpvue#587]
打开多个同一页面，通过传参的方式获取接口返回不同的数据填充之后，之前的所有同一路由的页面数据全部被替换了

**Comment by F-loat** [comment]
#140

**Comment by 948911908** [comment]
感觉并不是同一个问题，我的问题如下
![brand](https://user-images.githubusercontent.com/19320137/40916163-44f154e2-6831-11e8-85f2-68b8c607e3a4.gif)

代码如下：
![2018-06-04_195442](https://user-images.githubusercontent.com/19320137/40916170-4e3abf2a-6831-11e8-99b1-364ca4cc8ec6.png)

**Comment by 948911908** [comment]
@F-loat 当我打开10个页面  每个页面都展示不同的数据，然后一直回退到最原始的页面，前面的这所有页面都变成了10，我有试过用小程序原生的方式去跳转，然而并没有这种情况出现

**Comment by F-loat** [comment]
https://github.com/Meituan-Dianping/mpvue/issues/140#issuecomment-380145031 有写解决方法

**Comment by F-loat** [comment]
保留有差异的数据就可以

**Comment by 948911908** [comment]
@F-loat 只能在mounted里面才生效的嘛，我试过在onLoad里面无效
