### ISSUE TITLE
import的文件无法热更新

### ISSUE THREAD

**Issue by laravelup** [Meituan-Dianping/mpvue#589]
1.7.2版本、更改import的文件无法热更新，需要重新编译才会看到效果 已经加了 --no-cache

**Comment by F-loat** [comment]
emmm 走错了？

**Comment by linweiwei123** [comment]
import  { CalenderHotel } from 'widow-mpvue/calender-hotel/index' 
改成
import CalenderHotel from 'widow-mpvue/lib/calender-hotel/index';
没有热更新，暂停后重新npm run start 后正常。我还以为我代码哪里错了一直排查

**Comment by linweiwei123** [comment]
@laravelup 要怎么样解决呢
