### ISSUE TITLE
Vux的Card使用问题

### ISSUE THREAD

**Issue by OkOkOkNoNoNo** [Meituan-Dianping/mpvue#59]
import {Card} from 'vux'

编译报错：
error:  嵌套的 v-for 不能连续使用相同的 iterator: [ 'index', 'index' ]

  error:  嵌套的 v-for 不能连续使用相同的 iterator: [ 'index', 'index' ]

  error:  嵌套的 v-for 不能连续使用相同的 iterator: [ 'index', 'index' ]

  error:  嵌套的 v-for 不能连续使用相同的 iterator: [ 'index', 'index' ]

  error:  嵌套的 v-for 不能连续使用相同的 iterator: [ 'index', 'index' ]

这。。。。

**Comment by anchengjian** [comment]
连续 v-for 嵌套，需要指定不同索引。

```
    <ul v-for="(items, i) in list">
      <li v-for="(item, j) in items">
        <p>{{i, j}}</p>
      </li>
    </ul>
```

**Comment by OkOkOkNoNoNo** [comment]
可是我没有做任何操作啊，只是import { Card } from 'vux'

那这是Vux的问题？问题是我在纯Vue的单页程序里没这个问题啊

**Comment by anchengjian** [comment]
从这个报错看，只能得出这是多层 v-for 嵌套问题，不确定是否还有其他问题。

**Comment by cmideal** [comment]
card这个里面好像没有for 循环
`<template>
	<div class="weui-panel weui-panel_access">
    <div class="weui-panel__hd" v-if="header && header.title" v-html="header.title" @click="$emit('on-click-header')"></div>
    <slot name="header"></slot>
    <div class="weui-panel__bd">
      <div class="vux-card-content"><slot name="content"></slot></div>
    </div>
    <div class="weui-panel__ft">
      <a class="weui-cell weui-cell_access weui-cell_link" href="javascript:" v-if="footer && footer.title" @click="onClickFooter">
        <div class="weui-cell__bd" v-html="footer.title"></div>
      </a>
    </div>
    <slot name="footer"></slot>
  </div>
</template>`

**Comment by tuhe32** [comment]
@cmideal ,你好，请问你是怎么把vux融进到mpvue里面的？

**Comment by cmideal** [comment]
@tuhe32 我没有融合，也是相融合的用，但是没看还

**Comment by mcu13321** [comment]
我也遇到这个问题，在我自己写的一个组件上直接v-for报嵌套的v-for不能连续使用相同的iterator，组件内部确定再无嵌套

**Comment by anchengjian** [comment]
@mcu13321 是否在 v-if  同时用了 v-for ？此处有个 bug 我们正砸处理

**Comment by happybobo** [comment]
@anchengjian 我也是在build的时候报：
`error:  嵌套的 v-for 不能连续使用相同的 iterator: [ 'index', 'index' ]`
的确是 v-if 同时用了 v-for

**Comment by anchengjian** [comment]
@happybobo 已经修复了，请升级最新版 mpvue / mpvue-template / mpvue-loader

**Comment by dowinweb** [comment]
@anchengjian 已经删掉重新安装还是报错，，是版本号不对吗，请指教
