### ISSUE TITLE
微信原生的enablePullDownRefresh不生效

### ISSUE THREAD

**Issue by lemonpigpig** [Meituan-Dianping/mpvue#591]
# [问题简单描述]
微信原生的enablePullDownRefresh不生效
**问题复现步骤:**
enablePullDownRefresh： true

1. [第一步]
下拉
2. [第二步]
3. [其他步骤...]

**期望的表现:**
期望正常显示并且有三个点
[在这里描述期望的表现]

**观察到的表现:**
不能弹回去而且没有三个点
[在这里描述观察到的表现]

**屏幕截图和动态 GIF 图**

![复现步骤的屏幕截图和动态 GIF 图](图片的 url)

**Comment by F-loat** [comment]
回弹需要主动调用相关 api，那三个点估计是和背景色颜色一样了，所以看不到

**Comment by lemonpigpig** [comment]
坑爹的忘记设置背景颜色了

**Comment by wjf9492** [comment]
怎么设置背景颜色 @lemonpigpig
