### ISSUE TITLE
可以把模板拿出去一个文件吗？比如 <template src="a.html">

### ISSUE THREAD

**Issue by flylee2011** [Meituan-Dianping/mpvue#594]
这种支持吗？`<template src="./a.html">`
我试了一下，编译就卡住了。

**Comment by F-loat** [comment]
目前不支持

**Comment by banxi1988** [comment]
其实我倒是希望这个模板做成真模板。比如增加像 nunjucks 这样。
可以 include 啊 macro 之类的。
我们可以为 CSS 引入编译预处理增加函数变量 ，引入。为什么不给 html 增加真模板功能呢？
我想这样的功能应该能提高开发效率。
