### ISSUE TITLE
根据5分钟快速开始运行后报错

### ISSUE THREAD

**Issue by aqingyan** [Meituan-Dianping/mpvue#596]
# [问题简单描述]
根据mpvue网站的5分钟快速开始运行后，报错误
![image](https://user-images.githubusercontent.com/20829988/40984524-b249bee2-6914-11e8-848c-00ead014351c.png)
在运行时报这个warn，应该没影响吧
![image](https://user-images.githubusercontent.com/20829988/40984686-0e069cf0-6915-11e8-8f80-492a04109b30.png)

**Comment by 969723815** [comment]
把微信web开发者工具升级到最新版就好了
