### ISSUE TITLE
mpvue 编写的组件,同时有两个页面在引用该组件时，共用组件样式丢失

### ISSUE THREAD

**Issue by binlucky** [Meituan-Dianping/mpvue#597]
mpvue 编写的组件,同时有两个页面在引用该组件时， sass编写
样式会丢失(static/css/pages/index/wxcss)
**问题复现步骤:**
component/a
共用组件a

pages/b
b页面引用a 显示正常

pages/c
c页面引用a时  此时 a组件样式全部消失

**期望的表现:**

a 组件样式正常显示

[在这里描述期望的表现]

[在这里描述观察到的表现]

![复现步骤的屏幕截图和动态 GIF 图](图片的 url)

**Comment by weineel** [comment]
你可以看看这个issue
#180

**Comment by binlucky** [comment]
@weineel  谢谢，解决了我的困扰
