### ISSUE TITLE
原有项目 过渡到 mpvue 方案

### ISSUE THREAD

**Issue by wjy4124** [Meituan-Dianping/mpvue#598]
请问 原有的小程序项目（什么框架都没用）
怎样可以过到 mpvue

我发现 如果 webpack 的 entry 没有 app 会构建不了 卡住
![image](https://user-images.githubusercontent.com/8455577/41010968-0c86440e-696d-11e8-807f-c30a85beb5ec.png)

如果 把原有的 app.js 里代码，放到 mpvue 里的 app.vue 里，getApp 会找不到 app.vue 定义的方法（原有很多页面，getApp 取得实例再调用 app 里的方法，还有变量）

**Comment by yuconora** [comment]
mpvue 最后也是编译成原生的小程序代码 如果只是灵活的添加几个页面  用mpvue-simple 编译相关的页面手动添加到原生里面去就行了

**Comment by wjy4124** [comment]
@yuconora 
主要是 不想跑 entry 里的 app
只想跑 page
我注释掉 entry 的 app 就卡住了

**Comment by yuconora** [comment]
mpvue全局方法 用 vuex 会比 getApp 用起来方便

**Comment by wjy4124** [comment]
看来我用错工具了 
谢谢
