### ISSUE TITLE
WXS 支持

### ISSUE THREAD

**Issue by Jimco** [Meituan-Dianping/mpvue#6]
看文档 mpvue 没有关于 WXS 的介绍，请问目前框架支持了吗？如果不支持，目前对于复杂的 Javascript 渲染表达式要怎么处理？

**Comment by aOrz** [comment]
复杂的 Javascript 渲染表达式 建议使用 computed 去实现

**Comment by Jimco** [comment]
@aOrz computed 不是银弹，并不能解决所有问题，mpvue 后续不考虑 WXS 的支持吗？

**Comment by aOrz** [comment]
后续会考虑要不要支持

**Comment by rchunping** [comment]
确实有这方面的需求

不过倒是觉得可以把wxs实现成filter的那样的用法，有明确的管道符分割编译器应该更好写

一开始可以简单点，像wepy那样只支持.wxs文件形式引入

**Comment by watsonhaw** [comment]
@rchunping 今天在写今日头条的小程序的时候发现今日头条不支持wxs，不知道有什么好的办法可以在组件中写filter
