### ISSUE TITLE
频繁更新vue属性的时候报错

### ISSUE THREAD

**Issue by z008hy** [Meituan-Dianping/mpvue#60]
![image](https://user-images.githubusercontent.com/20768496/37324405-38439146-26c4-11e8-85bc-3f6b60ebee0d.png)
// 具体报错方法

![image](https://user-images.githubusercontent.com/20768496/37324441-6a052d34-26c4-11e8-86c0-83826e0b0fb5.png)

**Comment by falost** [comment]
可否 提供下 调用的代码呢

**Comment by z008hy** [comment]
@falost 刚刚调试了一下，已解决，原因是循环的时候key的问题。多谢了
