### ISSUE TITLE
小程序的获取用户方式改变了，需要点击才能获取用户信息

### ISSUE THREAD

**Issue by yzbgyq** [Meituan-Dianping/mpvue#600]
看到网上有方法说在mpvue下的index.js下加onGetUserInfo方法，与created同级，这样是可以，但是不想每次都这样啊，求解决

**Comment by F-loat** [comment]
这个问题 mpvue 和原生差别不大吧

**Comment by luogeng2017** [comment]
我也遇到同样的问题，button的bindgetuserinfo属性不知道怎么绑定

**Comment by luogeng2017** [comment]
找到了---------->bindgetuserinfo改成@ getuserinfo试试

**Comment by georgezouq** [comment]
@SongOfSpring mpvue 什么时候会更新？？

**Comment by qiaolevip** [comment]
2018-08-21解决方案：
```html
<template>
  <button class="weui-btn" type="primary" open-type="getUserInfo" @getuserinfo="getUserInfo">授权</button>
</template>
```

```javascript
methods: {
      getUserInfo(e) {
        console.log(e.target.userInfo)
      }
}
```

{avatarUrl
:
""
city
:
""
country
:
"China"
gender
:
1
language
:
"zh_CN"
nickName
:
"🇯 🇴 🇪"
province
:
""}
