### ISSUE TITLE
npm包import组件不能正常使用

### ISSUE THREAD

**Issue by linweiwei123** [Meituan-Dianping/mpvue#601]
# [问题简单描述]
npm 模块的组件引入不正常，改成全路径精准到模块的某个组件的却可以，无法解决，请帮忙看下什么原因？

**问题复现步骤:**

`  import { CalenderHotel }  from 'widow-mpvue'; `   NO OK！😭
`  import CalenderHotel  from 'widow-mpvue/lib/calender-hotel/index';`  It's OK!😁

**期望的表现:**

All OK!

**观察到的表现:**

[在这里描述观察到的表现]
![image](https://user-images.githubusercontent.com/11659687/41019173-1dfdbbae-6990-11e8-8c94-c648909c7fe9.png)

是否存在此问题？如果存在，是什么原因

**Comment by F-loat** [comment]
暂时不支持间接引用
