### ISSUE TITLE
import scss 不编译

### ISSUE THREAD

**Issue by longdan** [Meituan-Dianping/mpvue#607]
# [问题简单描述]
<style lang="scss" scoped>
  @import url("~@/styles/index.scss");
  .userinfo {
    display: flex;
    flex-direction: column;
    align-items: center;

    .userinfo-nickname {
      color: #aaa;
      font-size:12px;
    }
  }
</style>

import 进来的scss文件没有编译

**Comment by shaonialife** [comment]
![image](https://user-images.githubusercontent.com/16135960/41077250-22e9e71a-6a48-11e8-80ab-e0881d2235d7.png)
像这样引入, 直接在 script 标签内引入

**Comment by longdan** [comment]
@shaonialife    这样引入的样式文件内定义的变量，在页面上的style标签 里是引用不到的吧

**Comment by longdan** [comment]
@import  "~@/styles/index.scss"；  把url去掉好像就可以了
