### ISSUE TITLE
mpvue use nuxt

### ISSUE THREAD

**Issue by yuchonghua** [Meituan-Dianping/mpvue#608]
# 使用 nuxt的 layouts实现就可以了

**问题复现步骤:**

1. [第一步]
2. [第二步]
3. [其他步骤...]

**期望的表现:**

[在这里描述期望的表现]
[使用 nuxt的 layouts实现就可以了](https://github.com/nuxt/nuxt.js/issues/3418)

**观察到的表现:**

[在这里描述观察到的表现]

**屏幕截图和动态 GIF 图**

![复现步骤的屏幕截图和动态 GIF 图](图片的 url)

**Comment by aOrz** [comment]
小程序无法使用 ssr
