### ISSUE TITLE
使用git submodule管理vue

### ISSUE THREAD

**Issue by gzzhanghao** [Meituan-Dianping/mpvue#610]
现在mpvue的代码库是直接从vue项目fork过来的，新旧代码混杂在一起比较难维护，同时要更新vue也比较麻烦。希望可以用git的submodule方式引用vue模块。

一个例子： https://github.com/gzzhanghao/mpvue-ex

**Comment by aOrz** [comment]
mpvue 也改了一些 vue 的构建和 runtime 部分的代码。使用 submodule 也无法解决 “新旧代码混杂在一起” 的问题，使用 submodule 也会导致目录结构不优雅。

**Comment by gzzhanghao** [comment]
把 `platforms/mp` 下的代码迁移到 `src` 后，只需做一些兼容性修改就能跑通 mpvue 的全部测试用例。同时 vue 也升级到了v2.5.16。

https://github.com/gzzhanghao/mpvue-ex
