### ISSUE TITLE
通过this.$root 访问全家变量

### ISSUE THREAD

**Issue by Rahim-Chan** [Meituan-Dianping/mpvue#611]
# [问题简单描述]
new Vue({ data: { name: 1}})  拿不到name值
**问题复现步骤:**
子级页面this.$root.name 拿不到
1. [第一步]

2. [第二步]
3. [其他步骤...]

**期望的表现:**
像web vue那样拿到值
[在这里描述期望的表现]

**观察到的表现:**

[在这里描述观察到的表现]

**屏幕截图和动态 GIF 图**

![复现步骤的屏幕截图和动态 GIF 图](图片的 url)

**Comment by F-loat** [comment]
模板里应该拿不到，js 里应该没问题，可以通过 compute 来使用
