### ISSUE TITLE
npm run build后上传为体验版，怎么样凭借运维中心的错误记录找出错误位置？

### ISSUE THREAD

**Issue by gzlock** [Meituan-Dianping/mpvue#612]
# 运维中心错误记录截图
![image](https://user-images.githubusercontent.com/2311740/41095844-5e4be2da-6a85-11e8-9640-c1efbac503a9.png)
我在开发者工具里和我手里的两台手机没有在体验版找出错误，但是其他人的iPhone会有错误。
因为npm run build压缩了代码，很难定位到错误到位置

**问题复现步骤:**
开发环境无法复现，试不出错误。

**期望的表现:**
因为手里没有iPhone，希望可以凭借微信运维中心的错误记录找出错误原因

**观察到的表现:**
我手里的两台安卓测试体验版都没有错误

**屏幕截图和动态 GIF 图**
![image](https://user-images.githubusercontent.com/2311740/41095844-5e4be2da-6a85-11e8-9640-c1efbac503a9.png)

**Comment by hucq** [comment]
看上面的错误堆栈信息，后两个基本能确定出错的页面和方法，剩下的需要仔细排查一下。
引入框架的确会对排查问题带来更大的挑战，毕竟代码量增加了，代码经过混淆后尤其困难。
此外并没有特别好的方法，或者可以考虑增加一些异常捕获，可以更精确的定位。
