### ISSUE TITLE
为什么数据发生了改变就要整个渲染这样列表页面就会回弹如果有滚动

### ISSUE THREAD

**Issue by lemonpigpig** [Meituan-Dianping/mpvue#615]
# [问题简单描述]

**问题复现步骤:**

1. [第一步]
2. [第二步]
3. [其他步骤...]

**期望的表现:**

[在这里描述期望的表现]

**观察到的表现:**

[在这里描述观察到的表现]

**屏幕截图和动态 GIF 图**

![复现步骤的屏幕截图和动态 GIF 图](图片的 url)

**Comment by sokis** [comment]
#500 data更新机制导致的

**Comment by shaonialife** [comment]
看看这个 #639
