### ISSUE TITLE
元素 class 与 text 都编译近了 js文件？

### ISSUE THREAD

**Issue by alexsunnysun** [Meituan-Dianping/mpvue#616]
最近看了编译好的static下的js文件，发现 page页面里的标签元素的class与text内容都编译进了js文件里这是为什么？   这样文件也变大了~~

**Comment by aOrz** [comment]
mpvue 依赖 vue 的 vdom，所以 render 函数也被打包进去，后续会计划对  render 函数进行瘦身

**Comment by alexsunnysun** [comment]
ok，收到   加油哟
