### ISSUE TITLE
使用MPVue编译后每个Page下都会产生很大的wxss文件

### ISSUE THREAD

**Issue by shipfi** [Meituan-Dianping/mpvue#618]
### 使用MPVue编译后每个Page下都会产生很大的wxss文件

1. .vue文件中@import css/less文件。
2. 在css/less里面import了 svg和ttf这些比较大的数据。
3. 打包后，svg和ttf数据被编译到每一个页面的wxss文件中，导致dist下目录过大。

有没有这样的编译方案：将某些通用的css文件编译成单独的wxss文件，各个Page下的wxss只是通过@import方式引入？或其它更好的思路？

#### 具体的方式
> 1. 通用样式文件
![image](https://user-images.githubusercontent.com/15029373/41202531-76e0fbcc-6cfc-11e8-917b-65a3288a502b.png)
> 2. 页面通用样式文件
![image](https://user-images.githubusercontent.com/15029373/41202540-9831d92c-6cfc-11e8-9ba2-a49b07993308.png)
> 3. 各个页面引用后导致各个目录下的wxss文件都很大。
![image](https://user-images.githubusercontent.com/15029373/41202640-bfaeee84-6cfe-11e8-840e-8e4ee06dd9dd.png)

**Comment by JJJYY** [comment]
你这样不是相当于在每个文件都引入了 一个 './iconfont'，放到`App.vue`试试

**Comment by F-loat** [comment]
默认模板 build 时会提取公共样式文件的吧，而且应该不会生成 map 文件

**Comment by SongOfSpring** [comment]
ttf文件应该是不会上传的

**Comment by aOrz** [comment]
参考最新的 https://github.com/mpvue/mpvue-quickstart，引用两次及以上的资源会被打包到 vender 里面
