### ISSUE TITLE
亲，下一个版本有计划吗？大概什么时候更新？

### ISSUE THREAD

**Issue by sharkdong** [Meituan-Dianping/mpvue#619]
# [问题简单描述]

**问题复现步骤:**

1. [第一步]
2. [第二步]
3. [其他步骤...]

**期望的表现:**

[在这里描述期望的表现]

**观察到的表现:**

[在这里描述观察到的表现]

**屏幕截图和动态 GIF 图**

![复现步骤的屏幕截图和动态 GIF 图](图片的 url)

**Comment by mdsb100** [comment]
我觉得可以发展几个非美团的外部维护者，毕竟美团这样的大厂经常要加班搬砖吧。这样至少可以快速响应issue。

**Comment by Vultur** [comment]
可以关注 mpvue-loader 的需求池动态 👌

**Comment by hucq** [comment]
mpvue 会继续采分大小版本号的方式保持更新
1. bugfix 和小迭代不定期更新
2. 接下来比较大的迭代是 slot 问题修复、生命周期改进，周期会更长一些。
