### ISSUE TITLE
页面内子组件引入store.js 切换回页面 计算属性中的state无法更新

### ISSUE THREAD

**Issue by ChobitsSP** [Meituan-Dianping/mpvue#62]
"mpvue": "^1.0.1",
"vuex": "^2.3.1"

页面中子组件引入src/store/index.js 使用store.getters.xxxx map到子组件的计算属性

在页面切换回来时 操作store无法更新子组件的计算属性

**Comment by ChobitsSP** [comment]
当且只有在页面根组件中计算属性 引入store.getters.a时 子组件的store.getters.a才会生效
否则切回页面 操作store后子组件的store.getters.a不变

**Comment by ChobitsSP** [comment]
是v-if的问题

<button v-if="!is_sub" @click="sub"> sub </button>
<button v-if="is_sub" @click="unsub"> unsub </button>

sub和unsub中操作store.commit后 会出现此问题

**Comment by ChobitsSP** [comment]
![2018-03-13_15-05-35](https://user-images.githubusercontent.com/4433217/37327259-7df01c3a-26d0-11e8-866f-20821a203e21.gif)

**Comment by lanshengzhong** [comment]
我也遇到了  等官方修复吧 伤心~~

**Comment by lanshengzhong** [comment]
官方有消息吗？

**Comment by pcloth** [comment]
各位有写了什么优雅的替代方案么

**Comment by lanshengzhong** [comment]
试试子组件传递给父组件再执行事件看看  我没在用了  暂时还在用wepy  等这些bug修复了再回来看看

**Comment by anchengjian** [comment]
你们能不能提供一个小 demo，毕竟 vuex 用的不多，怕 match 不到你们的具体用法

**Comment by lanshengzhong** [comment]
[https://gitee.com/lanshengzhong/mpvue-bug](url)
问题一  左上角返回子组件state无法更新
问题二 在组件上使用v-if无效   详细请看 home/index.vue   页面中的  <card v-if="count"></card>

**Comment by lanshengzhong** [comment]
@anchengjian

**Comment by anchengjian** [comment]
问题一：你用 [develop/packages/mpvue/index.js](https://github.com/Meituan-Dianping/mpvue/blob/develop/packages/mpvue/index.js) 的代码替换掉你本地 node_modules/mpvue/index.js 的后看一下是否还会复现。

问题二：v-if 那个是 demo 中 home/index.vue 的 components 字段被写成了 component 导致不能识别。

**Comment by lanshengzhong** [comment]
测试ok，感谢~

**Comment by aOrz** [comment]
已修复，见：https://github.com/Meituan-Dianping/mpvue/releases/tag/1.0.7

**Comment by houyazhao** [comment]
感谢，终于能继续进行了

**Comment by houyazhao** [comment]
你说的是页面之间传值吗@soapper

**Comment by soapper** [comment]
@houyazhao 是的页面之间传值。我看到有redux方案，今天测试vuex 计算属性不响应

**Comment by houyazhao** [comment]
@soapper mpvue确实不支持计算属性。传值是真的可以。官方文档有说的

**Comment by houyazhao** [comment]
vuex是支持的。但是计算属性不支持@soapper

**Comment by soapper** [comment]
@houyazhao 好的吧我知道了。。谢谢哦
