### ISSUE TITLE
px2rpx中的/*no*/不起效果

### ISSUE THREAD

**Issue by mdsb100** [Meituan-Dianping/mpvue#623]
# [问题简单描述]
写在css中的/\*no\*/不起效果

**问题复现步骤:**

**期望的表现:**

写在css中的/\*no\*/起效果

**观察到的表现:**

读了源码以后发现：
px2rpx-loader只使用了`generaterpx`这个方法，而没有使用`generateThree `方法。

配置中keepComment只出现在了`generateThree `方法中，所以/\*no\*/不可能起效果。
```javascript
var defaultConfig = {
  baseDpr: 2,             // base device pixel ratio (default: 2)
  remUnit: 75,            // rem unit value (default: 75)
  remPrecision: 6,        // rem value precision (default: 6)
  forcePxComment: 'px',   // force px comment (default: `px`)
  keepComment: 'no'       // no transform value comment (default: `no`)
};
```

所以我不确定是不是作者有意为之？但是README提了这句`don't intend to transform the original value, eg: 1px border, add /*no*/ after the declaration`，所以我认为是issue。

因为px2rpx不能提issue，我就提在了这里。

**Comment by mdsb100** [comment]
补充下px2rpx-loader中，获得的source已经被去除注释了，所以更不可能起效果。
```
module.exports = function (source) {
  var query = loaderUtils.parseQuery(this.query)
  var px2rpxIns = new Px2rpx(query)
  console.log(source)
  return px2rpxIns.generaterpx(source)
}
```

**Comment by mdsb100** [comment]
看了下px2rem，也有这个[问题](https://github.com/songsiqi/px2rem/issues/2)。主要是注释先被去除了，我觉得要修的话，靠关键字吧。@aOrz

**Comment by iulo** [comment]
别试了，如果是scss的，之前debug过，scss编译出的代码已经没注释了, 拿ast也没这个节点。
需要px的 写成`PX`就好了，可生效

**Comment by mdsb100** [comment]
@iulo 感谢。似乎也只能这样了。

**Comment by xiaoai7904** [comment]
> 别试了，如果是scss的，之前debug过，scss编译出的代码已经没注释了, 拿ast也没这个节点。
> 需要px的 写成`PX`就好了，可生效

是的，我之前用的scss也是通过该方式成功了
