### ISSUE TITLE
打包发布后，低版本IOS会报错 SyntaxError: Unexpected keyword 'const'. Const declarations are not supported in strict mode

### ISSUE THREAD

**Issue by xuyangqiao** [Meituan-Dianping/mpvue#624]
打包发布后，低版本IOS手机会报错 SyntaxError: Unexpected keyword 'const'. Const declarations are not supported in strict mode

请问这个问题改如何解决
![image](https://user-images.githubusercontent.com/10104349/41220838-2f5e69da-6d95-11e8-93a3-6662db1b71a2.png)

**Comment by banxi1988** [comment]
出错可能性。
 1）const 是新的语法， babel 没有帮忙转？
2） 支持 const 声明，但是使用有误。

**Comment by xuyangqiao** [comment]
@banxi1988 但是大部分手机都没有问题，就是那几个手机有问题，所以很疑惑，用的就是mpvue的cli启动的项目

**Comment by thundernet8** [comment]
@xuyangqiao 
你的某个npm包没有编译到es5语法，但是webpack的js loader默认不babel处理node_modules内的包，所以找到那个包，include进去

```js
test: /\.js$/,
include: [
      resolve('node_modules/xxx')
]
```

**Comment by hucq** [comment]
建议排查思路：
1. 走查具体代码
2. 检查构建策略
基本可以断定和框架本身无关。

**Comment by xiongwn** [comment]
ios9.3必显，既然用了webpack还不做兼容，默认配置没有把依赖库做babel转换。

**Comment by prozwang** [comment]
同样遇到类似的问题，请问有解决办法么？ mpvue 1.4开始就报这个错了

**Comment by xuyangqiao** [comment]
是因为某些包是es6，加到babel里处理下就好了。




------------------ 原始邮件 ------------------
发件人: "prozwang"<notifications@github.com>; 
发送时间: 2019年7月3日(星期三) 晚上6:00
收件人: "Meituan-Dianping/mpvue"<mpvue@noreply.github.com>; 
抄送: "superXu"<283081688@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [Meituan-Dianping/mpvue] 打包发布后，低版本IOS会报错 SyntaxError: Unexpected keyword 'const'. Const declarations are not supported in strict mode (#624)




同样遇到类似的问题，请问有解决办法么？ mpvue 1.4开始就报这个错了
