### ISSUE TITLE
项目拷贝到其他文件夹，构建后报错

### ISSUE THREAD

**Issue by luosijie** [Meituan-Dianping/mpvue#625]
### 问题复现:

1. 一个项目拷贝到另一个文件夹
2. 删除 node_modules 文件夹
3. 重新执行 npm install 和 npm run dev

### 观察到的表现:
我在 构建命令 里，使用使用了环境变量

![image](https://user-images.githubusercontent.com/16912206/41266656-7ce6d922-6e2a-11e8-91c7-79899435748f.png)

编译没有问题

![image](https://user-images.githubusercontent.com/16912206/41266674-922b498a-6e2a-11e8-940a-27218b45bb74.png)

微信调试工具报错，找不到 development

![image](https://user-images.githubusercontent.com/16912206/41266693-b3e4da3c-6e2a-11e8-9d68-7615d70373a6.png)

发现 这里的 development 本来应该转化成字符串的

![image](https://user-images.githubusercontent.com/16912206/41266828-54cc1ece-6e2b-11e8-8169-a1e3e9fb347f.png)

**Comment by aOrz** [comment]
应该是你的配置的问题，检查下代码配置
