### ISSUE TITLE
可以使用ts编写么？有没有小伙伴用了的

### ISSUE THREAD

**Issue by innocces** [Meituan-Dianping/mpvue#628]
rt

**Comment by JJJYY** [comment]
可以自己改配置，把babel换成ts，改下loader

**Comment by banxi1988** [comment]
有一个开箱即用。 mpvue-starter 了解一下：
https://github.com/banxi1988/mpvue-starter

**Comment by hucq** [comment]
完全可以的。框架本身不做限制，完全可以按自己的意思来，具体配置可以自行研究下。
