### ISSUE TITLE
scroll-view scrolltop问题

### ISSUE THREAD

**Issue by lemonpigpig** [Meituan-Dianping/mpvue#630]
# [问题简单描述]
<view class="gotop" style="width:30px;height:30px;position:fixed;top:0;left:0;background:pink;z-index:999;" @click="goTop" id="gotop" v-if="show">
			回到顶部
		</view>
在mpvue中使用微信原生scroll-view设置回到顶部按钮，把scrolltop的值放在了data中，发现当在临界值点也就是show=true的时候发现页面会过一会上弹，原因就是mpvue只要有一个数据改变就会序列化所有的数据，然后重新渲染，个人不是很明白，这样性能就很差吧，还有wepy在这一块是让用户选择渲染的部分，个人觉得这样更科学，项目做了一半多了，发现mpvue的坑真的太多了，也许是我们的需求本来就复杂吧，而且本来想用小程序原生的setdata方法，但是不支持，这就比较烦了，现在这个问题基本上是无解，希望美团的同事出来指导下，毕竟项目做了一半多了，不想换wepy
**问题复现步骤:**

1. [第一步]
2. [第二步]
3. [其他步骤...]

**期望的表现:**

[在这里描述期望的表现]

**观察到的表现:**

[在这里描述观察到的表现]

**屏幕截图和动态 GIF 图**

![复现步骤的屏幕截图和动态 GIF 图](图片的 url)

**Comment by shaonialife** [comment]
看看这个 #639

**Comment by charleslo1** [comment]
我也是功能都做完后来优化性能才发现有这么大一个坑，但自己水平太菜有不知道怎么改源码，只好项目延期上线了

**Comment by Rem486** [comment]
请问你的 scrolltop 值是怎么绑定的呢？为什么我这边动态绑定了scrolltop之后，他的值无法自动更新始终都是初始值？

`:scroll-top="scrollTop"`
`scrollTop: 0 `

**Comment by ExcellentJR** [comment]
@Rem486 他说的就是这个问题，一旦data()里的一个值发生改变，data()里的所有值都会重新渲染，然后导致scrollTop值变成了0（或者你设置的初始值），无解的问题。。。mpvue的坑，上面[#639](https://github.com/Meituan-Dianping/mpvue/issues/639)的issue可以看看
