### ISSUE TITLE
下拉加载更多

### ISSUE THREAD

**Issue by lemonpigpig** [Meituan-Dianping/mpvue#631]
# [问题简单描述]
下拉加载更多零界点状态发生变化，然后上弹页面，美团你真的是页面只要状态改变就是重新渲染，如果真的这样，求解，还有各种抖动也是这个造成的
**问题复现步骤:**

1. [第一步]
2. [第二步]
3. [其他步骤...]

**期望的表现:**

[在这里描述期望的表现]

**观察到的表现:**

[在这里描述观察到的表现]

**屏幕截图和动态 GIF 图**

![复现步骤的屏幕截图和动态 GIF 图](图片的 url)

**Comment by shaonialife** [comment]
看下这个 #639
