### ISSUE TITLE
animation 编辑器和手机端效果不一致

### ISSUE THREAD

**Issue by Howie126313** [Meituan-Dianping/mpvue#635]
# [问题简单描述]
使用 animation 旋转 canvas 时，电脑端和微信端效果不一致

**问题复现步骤:**
开发者工具效果
![](https://user-images.githubusercontent.com/32697672/41335779-97b5917e-6f1c-11e8-9c11-fc18fa779a9d.gif)
微信端效果
![](https://user-images.githubusercontent.com/32697672/41336246-3dba34e8-6f1e-11e8-9bea-1ed4384967ac.gif)
代码：
```
      var animation = wx.createAnimation({
        duration: 500,
        timingFunction: 'ease'
      })
      this.animation = animation
      animation.rotate(this.rotateNum * 90).step()
      this.animationData = this.animation.export()
```

**Comment by shaonialife** [comment]
导出的是css动画, 官网上说 css 动画对 canvas 组件无效
![image](https://user-images.githubusercontent.com/16135960/41387745-30e5cd5c-6fbb-11e8-8d72-ffa12c85d048.png)

**Comment by Howie126313** [comment]
@shaonialife 多谢大佬

**Comment by hucq** [comment]
问题与框架不相关。
