### ISSUE TITLE
npm 包里面没有 types 文件夹

### ISSUE THREAD

**Issue by Allenice** [Meituan-Dianping/mpvue#64]
如题，npm isntall 后，mpvue 这个包没有 types 文件夹，typescript 开发者表示非常需要这个。

**Comment by fengcen** [comment]
可以加一下吗，我也需要使用 typescript

**Comment by Allenice** [comment]
@fengcen 可以使用 minapp 的定义文件。https://github.com/qiu8310/minapp
在 tscofnig 那里配置 typeRoots

**Comment by fengcen** [comment]
好，我直接用 minapp 开发了，离不开 typescript 😂

**Comment by hucq** [comment]
是否使用ts开发我们不强行要求，开发的时候可自行决定。
对于项目支持来说，只需要在webpack构建策略中配置一个 ts 的 loader 即可。 

细节可以参考一下知乎上 @小爝 爝神的回复：https://www.zhihu.com/question/268421668

**Comment by hucq** [comment]
是否使用ts开发我们不强行要求，开发的时候可自行决定。
对于项目支持来说，只需要在webpack构建策略中配置一个 ts 的 loader 即可。 

细节可以参考一下知乎上 @小爝 爝神的回复：https://www.zhihu.com/question/268421668
