### ISSUE TITLE
程序没有正常编译

### ISSUE THREAD

**Issue by limichange** [Meituan-Dianping/mpvue#642]
**问题复现步骤:**

正常引入组件并使用
```js
import Card from '@/components/Card'
```

**期望的表现:**

正常编译，正常显示

**观察到的表现:**

需要重洗启动编译服务才可以正常的编译，否则就是空白

**Comment by aOrz** [comment]
新增页面需要重新 run dev，其他情况不需要

**Comment by limichange** [comment]
并不是新增页面，而仅仅是引入一个组件。

**Comment by aOrz** [comment]
提供下可复现的 demo

**Comment by xinconan** [comment]
也遇到同样的问题
```js
import hbItem from '@/components/hbItem';
```
新引入的组件会被编译成这样的：
![image](https://user-images.githubusercontent.com/8479810/48173412-96a9fb80-e33e-11e8-8c52-19b668dca253.png)
只有重新`npm run dev` 才有效
