### ISSUE TITLE
创建项目时没有填写小程序 ID 后来应该放到哪个文件里呢

### ISSUE THREAD

**Issue by weikx** [Meituan-Dianping/mpvue#647]
如题

**Comment by weikx** [comment]
重新打开开发工具填进去就好了...

**Comment by tanggaowei** [comment]
项目根目录中的 project.config.json 文件，修改其中的 "appid" 配置项。

**Comment by Sutonline** [comment]
@tanggaowei 是修改之后，要在小程序编辑工具里删除再增加一遍吧？ 
![image](https://user-images.githubusercontent.com/11715724/43306513-09e9755e-91ae-11e8-83eb-43d63bd15099.png)
我的小程序版本是这个，需要再重新添加一遍

**Comment by Niofh** [comment]
![image](https://user-images.githubusercontent.com/15324717/45399611-53ebe000-b67b-11e8-849a-57b23a3e90ef.png)
添加了Appid还是不行啊！
