### ISSUE TITLE
mpvue如何实现vue-router可以按需加载路由的功能？

### ISSUE THREAD

**Issue by xwLyc** [Meituan-Dianping/mpvue#650]
比如首页需要登录，转发给好友的的页面也需要好友登录，不做任何处理的话，页面加载会调用两次登录。
不想加载转发后的页面怎么处理？

**Comment by xwLyc** [comment]
比如首页需要登录，转发给好友的的页面也需要好友登录，不做任何处理的话，页面加载会调用两次登录。
不想加载转发后的页面怎么处理？

**Comment by aOrz** [comment]
沒明白要實現什麼功能？

**Comment by xwLyc** [comment]
我之前的请求方法写在creating里面，写在小程序的onshow里面就好了，谢谢~~~
