### ISSUE TITLE
自定义底部导航条点击跳转只能跳转9次，第十次能点击但无跳转

### ISSUE THREAD

**Issue by SnowBeatRain** [Meituan-Dianping/mpvue#656]
# [问题简单描述]

**问题复现步骤:**
`      <a  class="nav_list" :class=" {active:l.active}" @click='clickTo(l.path)'>
          <p>
            <i class="icon iconfont icon-daohangshouye"></i>
          </p>
          <P>{{l.name}}</P>
      </a>`
之前是用a标签跳转的，目前转为了wx.navigateTo()跳转，依旧是只能跳转9次，

**Comment by shaonialife** [comment]
![image](https://user-images.githubusercontent.com/16135960/41633260-88d42fe0-7470-11e8-9dc1-a38fabfd6704.png)

**Comment by banxi1988** [comment]
哇，原来还有这个限制啊。
不过什么交互需要超过9次的跳转呢？

**Comment by shaonialife** [comment]
从用户角度来看, 太多层可能会让用户迷失, 找不到方向
从程序角度来看, 一个页面就是一个 Activity或者是一个Fragment(在Android上, iOS不清楚), 里面嵌套WebView, 开多了比较占内存, 随时面临被系统回收的风险

**Comment by SnowBeatRain** [comment]
谢谢，只是我自己学习的时候设置了一个导航，随便点点，结果发现的这个问题。实际开发是不会出现超过10层的
