### ISSUE TITLE
mpvue 不支持 Coffee 吗？

### ISSUE THREAD

**Issue by ZweiZhao** [Meituan-Dianping/mpvue#659]
# [问题简单描述]
<script lang="coffee">
...Coffee 语法报错。
**问题复现步骤:**
coffeescript coffee-loader
<script lang=‘coffee'>’

**期望的表现:**
向 Vue-loader 一样正常使用 Coffee，如果是我弄错了，还请告知。

**Comment by anchengjian** [comment]
能给个简单的复现demo库，或者分享一下你的配置，能更好的辅助排查

**Comment by ZweiZhao** [comment]
https://github.com/ZweiZhao/MergeMoney
麻烦跟进

**Comment by aOrz** [comment]
@ZweiZhao 404

**Comment by ZweiZhao** [comment]
https://github.com/ZweiZhao/LittleTargetBill

**Comment by hunnble** [comment]
@ZweiZhao mpvue暂时不支持在单文件组件中直接使用coffeescript，建议采用引入coffee文件的写法

**Comment by ZweiZhao** [comment]
好的，谢谢

**Comment by anchengjian** [comment]
@hunnble @ZweiZhao 在 webpack rule 中配一个 coffee-loader，然后在 但文件组件中 `<script lang="coffee">` 然后就可以写 coffee 了吧，类似 https://vue-loader.vuejs.org/guide/pre-processors.html#typescript

**Comment by ZweiZhao** [comment]
@anchengjian 就是试过不行才问的啊。
