### ISSUE TITLE
给canvas动态绑定canvasId,不能渲染出所画内容～

### ISSUE THREAD

**Issue by DevinWell1ee** [Meituan-Dianping/mpvue#660]
# 动态绑定canvasId,不能渲染出内容

**实际需求**
将canvas所画的图表作为一个复用component,一个页面多个地方需要调用该component,所以需要不同的canvasid，但是当使用:canvasId='uuid'时，不能渲染出所画内容

**期望的表现:**

能渲染出内容

**观察到的表现:**

不能渲染

**Comment by shaonialife** [comment]
![image](https://user-images.githubusercontent.com/16135960/41649873-3cda3460-74af-11e8-91c7-3e558c0bc094.png)
加 v-if
