### ISSUE TITLE
给web-view绑定事件message无效

### ISSUE THREAD

**Issue by Joshwoooooooooooooooooooooooooooooooong** [Meituan-Dianping/mpvue#663]
# [问题简单描述]

**问题复现步骤:**

1. [第一步]

在小程序中添加一个web-view组件

```vue
<template>
  <div>
    <web-view src="https://thisisaurl" @message="test"/>
  </div>
</template>

<script>
export default {
  methods: {
    test(res) {
      console.log('test: ', res);
    },
  },
};
</script>
```

2. [第二步]

在页面中添加一段脚本

```javascript
window.onload = () => {
  wx.miniProgram.postMessage({ data: 'hello josh' });
};
```

**期望的表现:**

触发test方法且小程序控制台输出'hello josh'

**观察到的表现:**

test方法未被触发

**Comment by songlairui** [comment]
为什么close？
我现在遇到的问题是，第一次进入带有web-view的页面时，点击分享，postMessage未出发。
第二次进入时，就触发 @message了

**Comment by ChobitsSP** [comment]
> 为什么close？
> 我现在遇到的问题是，第一次进入带有web-view的页面时，点击分享，postMessage未出发。
> 第二次进入时，就触发 @message了

https://developers.weixin.qq.com/community/develop/doc/00084aef264080818f36ceb8851c00
