### ISSUE TITLE
npm run dev 之后dist 文件夹里边出现一个copy-asset 文件夹，里边也是图片，是怎么回事

### ISSUE THREAD

**Issue by ZjVirus** [Meituan-Dianping/mpvue#668]
# [问题简单描述]

**问题复现步骤:**
![image](https://user-images.githubusercontent.com/21301648/41752622-1b5921c8-75fb-11e8-91e6-60ab598416fb.png)

1. [第一步]
2. [第二步]
3. [其他步骤...]

**期望的表现:**

[在这里描述期望的表现]

**观察到的表现:**

[在这里描述观察到的表现]

**屏幕截图和动态 GIF 图**

![复现步骤的屏幕截图和动态 GIF 图](图片的 url)

**Comment by aOrz** [comment]
build 之后，图片会都放在 copy-asset 里面

**Comment by ZjVirus** [comment]
build 之后 static 里边是全部的图片，copy-asset里边是部分图片，并且是重复的

**Comment by aOrz** [comment]
webpack 配置里面有个 CopyWebpackPlugin 插件，如果不需要 copy static 文件夹，就去掉

**Comment by jfliapp** [comment]
注释了 也没用  还是有

**Comment by jfliapp** [comment]
![image](https://user-images.githubusercontent.com/27725921/42375642-bf34fba6-814e-11e8-8215-d9694e2e0eb8.png)
