### ISSUE TITLE
vue组件无法引用小程序自定义组件

### ISSUE THREAD

**Issue by kakaoG** [Meituan-Dianping/mpvue#671]
footer.vue
![image](https://user-images.githubusercontent.com/12584373/41762544-afcb241e-762d-11e8-9b10-d3035dfa03d5.png)
./button
![image](https://user-images.githubusercontent.com/12584373/41762568-c8c17d88-762d-11e8-83c9-cd7825683213.png)
./button/index
![image](https://user-images.githubusercontent.com/12584373/41762594-db050244-762d-11e8-9f6d-563cf64ddb08.png)
能否新增vue组件对小程序自定义组件的支持

**Comment by schinvendy** [comment]
你的引用方式不对的。
mpvue文档有介绍了怎么引用echarts 等小程序原生组件
http://mpvue.com/qa/#echarts
需要在对应的page的main.js里面添加需要使用的组件：
export default {
  config: {
    // 这儿添加要用的小程序组件
    usingComponents: {
      'ec-canvas': '../../../static/ec-canvas/ec-canvas'
    }
  }
}

**Comment by TonyLuo** [comment]
遇到同样的问题，vue页面可以引入原生组件，但vue的component不能引用原生组件

**Comment by JJJYY** [comment]
`mpvue`的`component`并不会被编译为原生组件，并不会存在`json`文件，所以要引入原生组件只能在对应的使用页面的`main.js`中引用
