### ISSUE TITLE
v-for="(item) in tabList" 在有item没有index时加上括号会报错

### ISSUE THREAD

**Issue by railgun20001** [Meituan-Dianping/mpvue#674]
v-for="(item) in tabList" 在有item没有index时加上括号会报错

Final loader didn't return a Buffer or String
![image](https://user-images.githubusercontent.com/22837283/41767590-a6273c54-763c-11e8-8e5b-a3510d039cd1.png)

**Comment by sideFlower** [comment]
建议你先把文档撸一遍

**Comment by railgun20001** [comment]
@sideFlower vue的还是mpvue,都撸过啊.
v-for="item in tabList"是正常的
v-for="(item) in tabList"会报错,而这种写法在vue中是可通过的

**Comment by railgun20001** [comment]
@sideFlower 哦,晓得了,我以为他说的必须要key呢,原来是index
