### ISSUE TITLE
全局变量支持

### ISSUE THREAD

**Issue by NanQi** [Meituan-Dianping/mpvue#676]
在APP()中写的全局变量，在mpvue中如何实现？
onLaunch和onError等事件倒是支持，但是写全局变量就无法支持。

**Comment by shaonialife** [comment]
用vuex

**Comment by NanQi** [comment]
@shaonialife 需要多端统一，多页面没必要用vuex。

**Comment by NanQi** [comment]
已解决。
`this.$root.$mp.app`里直接赋值即可。

**Comment by shaonialife** [comment]
多端统一用vuex更方便，你在this.$root.$mp.app反而不利于多端统一
