### ISSUE TITLE
将每个 page 的入口 js 的名称由 main.js --> index.js，打包结果不一致

### ISSUE THREAD

**Issue by dwqs** [Meituan-Dianping/mpvue#68]
复现步骤：

1. 根据 [mpvue-quickstart](https://github.com/mpvue/mpvue-quickstart/) 生成一个项目
2. 安装项目依赖
3. `npm run dev` 查看 build 后的 `dist` 目录：

![image](https://user-images.githubusercontent.com/7871813/37330121-04ff3cba-26db-11e8-8a81-0967cea2f371.png)

4. 将 `pages` 目录下的每个 page 的入口文件由 `main.js` 命名为 `index.js`
5. 更改 `build/webpack.base.config.js`：

```js
const pagesEntry = getEntry(resolve('./src/pages'), 'main.js')

↓ ↓ ↓ ↓ ↓ ↓

const pagesEntry = getEntry(resolve('./src/pages'), 'index.js')
```

6. 运行 `rm -rf dist && npm run dev` 查看 `dist` 目录：

![image](https://user-images.githubusercontent.com/7871813/37330284-8a2888e2-26db-11e8-9a00-2b1acaa53a47.png)

build 结果不一致。

经测试，将名称由 `main.js` 改为非 `index.js` ， build 结果是正确的

node: 8.9.4
os: macOS 10.13.3

**Comment by ilovemyboys** [comment]
我也测到了这个问题。

**Comment by aOrz** [comment]
这个是修改下代码就能修复，因为你的页面目录下有两个名为 index的文件，分别为 index.js 和 index.vue，当你在 index.js 中 `import App from './index'` 时，webpack 默认的查找规则是先 .js 文件后 .vue 文件，导致了index.js 循环引用了自己，建议改下名，或者写上完整后缀 import App from './index.vue'`
