### ISSUE TITLE
v-model初始化的值 无法传到组件内部

### ISSUE THREAD

**Issue by luosijie** [Meituan-Dianping/mpvue#682]
自定义组件使用v-model
父组件的初始值传不进去

**Comment by luosijie** [comment]
在组件内部 给 value 绑定一个属性
在组件外部传进去
![_20180731113624](https://user-images.githubusercontent.com/16912206/43436259-27c4e0e4-94b6-11e8-8758-f329f11dfba6.png)

**Comment by uwjiaoxing** [comment]
后面看了下文档，官方文档是这样用的，我们都用错了。。=_=||
 [在组件上使用-v-model](https://cn.vuejs.org/v2/guide/components.html#%E5%9C%A8%E7%BB%84%E4%BB%B6%E4%B8%8A%E4%BD%BF%E7%94%A8-v-model)
