### ISSUE TITLE
关于globalData的使用

### ISSUE THREAD

**Issue by baixiaosh** [Meituan-Dianping/mpvue#686]
# [问题简单描述]
在入口App.vue里添加globalData属性不能通过小程序的getApp方法获取到globalData的值
**问题复现步骤:**

1. [第一步]
App.vue里添加globalData属性
2. [第二步]
在index.vue内
const app = getApp()
console.log(app)
3. [第三步]
在小程序开发工具上查看打印的值
**期望的表现:**
打印值里应该包含globalData属性

**观察到的表现:**
结果并没有globalData属性

**Comment by F-loat** [comment]
globalData 不是响应式的，用了也没什么意义吧，简单的数据传递感觉都不如 storage 靠谱

**Comment by baixiaosh** [comment]
只是觉得小程序里面提供这么一个东西，为什么不利用起来呢

**Comment by F-loat** [comment]
因为不好用，记得用 wepy 的时候用了 globalData，每次都得在 onShow 时手动更新。。

**Comment by F-loat** [comment]
而且你前面写的用法不太对，你搜 issue 看看吧，目前不是那么用的

**Comment by baixiaosh** [comment]
那暂时先不考虑这个

**Comment by baixiaosh** [comment]
我这里还有个问题：
a.js
`export default {}`
b.js
```
import a from 'a';
//a is not defined 编译的时候
```

**Comment by F-loat** [comment]
这样呢 `import a from './a';`

**Comment by baixiaosh** [comment]
我就是这么写的，路径是对的

**Comment by F-loat** [comment]
我这边是没问题的

**Comment by baixiaosh** [comment]
但是奇怪的是在vue里面引入就是对的

**Comment by baixiaosh** [comment]
我在创建的项目里面的utils文件夹下面新建一个config.js文件
```
export default {
  baseUrl: '/'
}
```
然后在index.js内
```
import config from './config'
export default {
  config
}
```
编译就会报unknown: config is not defined

**Comment by F-loat** [comment]
config 换个名字就没事，不太清楚是什么问题，config 也不是关键字吧

**Comment by baixiaosh** [comment]
刚发现了 换个名字就对了
