### ISSUE TITLE
自动化部署时，npm构建在dist目录下没有生成project.config.json报错

### ISSUE THREAD

**Issue by johnson8999** [Meituan-Dianping/mpvue#687]
自动化部署时，npm构建，在dist目录下没有生成project.config.json，上传代码的时候报错无法找到project.config.json

我们是直接通过命令行拷贝了一份project.config.json到dist目录下实现的，mpvue团队可否直接在npm 构建的时候，直接把project.config.json放到dist目录下

**Comment by chentianyuan** [comment]
同，是不是 

> 请检查 project.config.json 是否存在及是否有效
奇怪了一天

**Comment by chentianyuan** [comment]
用这个插件可以在构建时就拷贝好
```
    new CopyWebpackPlugin([
      {
        from: path.resolve(__dirname, '../project.config.json'),
        to: '../'
      }
    ])
```
