### ISSUE TITLE
npm run build 后会出现  Cannot read property 'call' of undefined，需要修改配置文件webpack.prod.conf.js

### ISSUE THREAD

**Issue by gengchen528** [Meituan-Dianping/mpvue#689]
# [问题简单描述]
npm run build 后会出现  Cannot read property 'call' of undefined，需要修改配置文件webpack.prod.conf.js
**问题复现步骤:**

1. [第一步]

npm run build 后
2. [第二步]

在小程序调试工具打开会报错，Cannot read property 'call' of undefined

解决办法：
原：
   ```
 new ExtractTextPlugin({
      filename: utils.assetsPath('css/[name].wxss')
    }),
```

改后：
  ```
 new ExtractTextPlugin({
      filename: utils.assetsPath('css/[name].wxss'),
      allChunks: true
    }),
```

**Comment by F-loat** [comment]
这类直接提 pr 好点

**Comment by hucq** [comment]
可升级新版本解决此问题（mpvue/quickstart 中的 package.json 配置，build/ 目录配置）
如果升级了webpack 大版本，可能会有问题。
