### ISSUE TITLE
mpvue支持mixins吗?

### ISSUE THREAD

**Issue by yzw2017** [Meituan-Dianping/mpvue#690]
# [问题简单描述]

**问题复现步骤:**

1. [第一步]
2. [第二步]
3. [其他步骤...]

**期望的表现:**

[在这里描述期望的表现]

**观察到的表现:**

[在这里描述观察到的表现]

**屏幕截图和动态 GIF 图**

![复现步骤的屏幕截图和动态 GIF 图](图片的 url)

**Comment by F-loat** [comment]
支持的啊

**Comment by NanQi** [comment]
@yzw2017 
mixins是支持的，但是最好是单独混入。
如果全局混入，经过测试，在mixins中写data，可能会报错。
