### ISSUE TITLE
突然就不能运行了，就是不报错。一直卡在开始那里

### ISSUE THREAD

**Issue by lirunwin** [Meituan-Dianping/mpvue#693]
# [问题简单描述]
不知道什么情况，突然就不能npm run dev了。 也不报错。 并没有是没地方没有写script标签。
**问题复现步骤:**

**期望的表现:**
有什么问题可以报错吗？
**观察到的表现:**
不报错，就是不能运行。

**Comment by JhonYoung** [comment]
同问， win10, node 版本 8.x 9.x都卡在那儿

**Comment by imvicchen** [comment]
同问啊，run dev卡主了不动，也不抱错！连夜改回原生，好坑啊！

**Comment by aOrz** [comment]
@imvicchen 提供下依赖版本号

**Comment by lessthanno** [comment]
开发换个mac，可能会提高开发效率
