### ISSUE TITLE
详情页渲染越来越慢

### ISSUE THREAD

**Issue by letyougo** [Meituan-Dianping/mpvue#694]
操作
列表页面：list ,详情页面back
list -> detail?id=1 --- back  -> detail?id=2 ----back - > detail ?id=3

操作很多次后，详情页 渲染就变的 巨慢。小程序页面栈也没问题的。请问这个问题怎么解决

这个问题太严重了

**Comment by lqsyyy** [comment]
也遇到了这个问题，正在排查原因

**Comment by anchengjian** [comment]
可以试试腾讯的 TBS 打开小程序的远程调试能力，看一下内存泄漏啊啥的具体原因，或者你们搞个 demo 吧

**Comment by lqsyyy** [comment]
内存占用还好，150-170之间

**Comment by tailorsira** [comment]
官方文档上说，避免在v-for中嵌套子组件，会导致setData冗余数据，这是为什么呢？

**Comment by kala888** [comment]
类似问题，使用了大量的for和自定义component https://github.com/Meituan-Dianping/mpvue/issues/907

**Comment by lichenabson** [comment]
@kala888  你这个应该不是直接原因, 详情页即使是一个很简单的页面 例如这样
![image](https://user-images.githubusercontent.com/20200267/44642724-1ee75880-aa00-11e8-88f0-b8ae779125c3.png) 加入mpvue.trace 监控updateDataToMP函数的话,不停的重新进入退出,可以看到update递增式的被触发,如果页面数据复杂或者客户端机型破旧的话的话,就会感知到明显的卡顿
![image](https://user-images.githubusercontent.com/20200267/44642888-d8dec480-aa00-11e8-917f-368977b521c5.png)

**Comment by letyougo** [comment]
@lichenabson 我和你遇到的问题一样，就是 简单的渲染，导致越来越慢。

**Comment by letyougo** [comment]
官方，应该让小程序的页面栈 应该和 vue 页面实例的生命周期，保持同步。。 不然 就没法用了

**Comment by lichenabson** [comment]
#966

**Comment by Renford** [comment]
@lichenabson 有没有好的解决方案
