### ISSUE TITLE
不同页面报错后，其他页面数据绑定无效

### ISSUE THREAD

**Issue by NanQi** [Meituan-Dianping/mpvue#695]
问题复现：
1. 创建官方最新工程mpvue/mpvue-quickstart
2. 给页面logs增加data变量info={}
```
  data() {
    return {
      logs: [],
      info: {}
    };
  },
```
3. template中增加绑定`{{info.name}}`
4. 在mounted中给info设置为null
```
  mounted() {
    const logs = (wx.getStorageSync('logs') || [])
    this.logs = logs.map(log => formatTime(new Date(log)))
    this.info = null
  }
```
只要打开logs页面，index页面数据绑定无效（改了值无效，在第一个input中输入，其他值不变）

只要把mounted改成created则不会有问题，但是created中无法获取页面参数。

我无法保证所有页面不出错，但是只要一个页面报错，其他页面全部出问题相当于没办法使用，而且还没有其他办法，用户只能删除小程序再次扫码或搜索打开。

**Comment by shaonialife** [comment]
在 created 钩子里, 页面并没有创建出来, 你不管怎么改info, 数据都不会渲染到页面, 也就不会报错的.
即使你使用原生, 你在数据渲染完成之后再把info置为null, 也会报错, 因为小程序不知道name从哪里得到.
这个很好避免, 只要知道 info 可能为空, 那 {{info.name}} 就可以写成 {{info && info.name}}, 多个可以用 v-if 做开关
