### ISSUE TITLE
真机运行报TypeError错误的同学请看这里

### ISSUE THREAD

**Issue by NanQi** [Meituan-Dianping/mpvue#698]
真机不能打印this对象

```
console.log(this)
```

找了很长时间的错误，希望能帮助大家。

**Comment by shaonialife** [comment]
因为在手机微信上 console.log 调用了JSON.stringify 来对数据转成字符串用以显示, 然而对一个有循环引用的对象调用 JSON.stringify 肯定会抱错, 你这里的this应该指的就是 Vue 实例, 一个Vue实例是很复杂的, 里面就包含有循环引用, 所以在手机上console.log(this)就会报错
