### ISSUE TITLE
在小程序首页 wx.navigateBack() 退不出小程序，原小程序是可以的

### ISSUE THREAD

**Issue by yinpeng633** [Meituan-Dianping/mpvue#699]
# 在小程序首页 wx.navigateBack() 退不出小程序，原小程序是可以的

**问题复现步骤:**

1. 在小程序首页首页 调用wx.navigateBack({ delta: 1}) 

**期望的表现:**

退出小程序

**观察到的表现:**

没有任何反应

**屏幕截图和动态 GIF 图**

无

**Comment by aOrz** [comment]
这个应该跟 mpvue 没有关系
