### ISSUE TITLE
组件样式好像不生效啊。是要配置什么东西么？

### ISSUE THREAD

**Issue by pcloth** [Meituan-Dianping/mpvue#7]
如题。
在vue init mpvue/mpvue-quickstart my-project新建的项目里，组件card的class name能正确，但是样式丢失了。是要配置什么东西么？

**Comment by aOrz** [comment]
暂不支持在组件引用时，设置组件级别的 class，例 <card class="s"></card>

**Comment by F-loat** [comment]
@aOrz 同样发现了这个问题，看了下生成的代码里，组件内的 css 样式被提取到了 vendor.css 中，但并未被任何文件引用，导致样式丢失

**Comment by aOrz** [comment]
@F-loat  稍后会修复这个bug,你可以先改下webpack 配置 webpack.*.conf.js 中 
`new webpack.optimize.CommonsChunkPlugin({
      name: 'vendor',
      minChunks: function (module, count) {
        // any required modules inside node_modules are extracted to vendor
        return (
          module.resource &&
          /\.js$/.test(module.resource) &&
          module.resource.indexOf('node_modules') >= 0
        ) || count >= 2
      }
    }),`
为 `new webpack.optimize.CommonsChunkPlugin({
      name: 'vendor',
      minChunks: function (module, count) {
        // any required modules inside node_modules are extracted to vendor
        return (
          module.resource &&
          /\.js$/.test(module.resource) &&
          module.resource.indexOf('node_modules') >= 0
        )
      }
    }),`
避免 css 打到 vendor.wxss 中

**Comment by F-loat** [comment]
好的，就是去掉 ` || count >= 2` 就可以吧，那暂时先就这么解决了😃

**Comment by mcu13321** [comment]
mark

**Comment by aOrz** [comment]
@mcu13321 参考最新的 quickstart
