### ISSUE TITLE
DeprecationWarning: loaderUtils.parseQuery() received a non-string value

### ISSUE THREAD

**Issue by linrui1994** [Meituan-Dianping/mpvue#70]
(node:10085) DeprecationWarning: loaderUtils.parseQuery() received a non-string value which can be problematic, see https://github.com/webpack/loader-utils/issues/56
parseQuery() will be replaced with getOptions() in the next major version of loader-utils.

打包有时候会这样报错，可能是什么原因？

![image](https://user-images.githubusercontent.com/20953049/37337395-1d5bf64a-26ef-11e8-8c40-8087cf434c12.png)

**Comment by anchengjian** [comment]
可以分享下原因么？

**Comment by KuangPF** [comment]
在webpack里面配置下好像就不会报错:
`process.noDeprecation = true`
可参考 [这里](https://github.com/vuejs/vue-loader/issues/666)

**Comment by linrui1994** [comment]
我是没找到解决办法，但是好像不影响，就没管了，@KuangPF 可能就是解决办法
