### ISSUE TITLE
代码有错误，控制台不会报错

### ISSUE THREAD

**Issue by diamondloler** [Meituan-Dianping/mpvue#700]
# [问题简单描述]
例如我在page的mounted（用了async）回调随便写了个console.log(this.asdasd.length)

**期望的表现:**
Uncaught TypeError: Cannot read property 'length' of undefined at <anonymous>:1:12

**观察到的表现:**
控制台什么错误都没报

**Comment by diamondloler** [comment]
日后假如小程序出现bug 我该怎么排查 - -

**Comment by aOrz** [comment]
可先参考：https://juejin.im/post/5b332fd7e51d4558d727051e
> 4.mpvue代码中有异常时，小程序开发者工具有时候不会抛出异常报错，除了缺少文件会报错外，控制台大部分时间都是安静的，难以调试 。
  经查找，正常情况下代码错误时开发者工具是有错误提示的，而promise中的代码异常时不会有错误抛出。原因：mpvue中的promise被替换为 core-js polyfill 的 Promise 对象，global上没有全局错误处理。
  解决方案：在src下的main.js中添加一行require('core-js/library/modules/_global.js').console = console或者require('core-js/library/modules/_global.js').onunhandledrejection = console.errror


作者：花卷爱学习
链接：https://juejin.im/post/5b332fd7e51d4558d727051e
来源：掘金
著作权归作者所有。商业转载请联系作者获得授权，非商业转载请注明出处。

**Comment by youmengme** [comment]
终于解决了，感动到哭。
