### ISSUE TITLE
数据能正常展示，但是控制台报thirdScriptError Cannot read property 'xxx' of undefined

### ISSUE THREAD

**Issue by fernandoxu** [Meituan-Dianping/mpvue#702]
# [问题简单描述]
字段{{courseInfo.lecturerInfo.identity}}可以显示在页面里，但是控制台报了thirdScriptError
Cannot read property 'identity' of undefined;at pages/class page lifeCycleMethod onReady function
TypeError: Cannot read property 'identity' of undefined
虽然没什么影响但是想知道为什么会报这个？

**Comment by aOrz** [comment]
请按照 issue 模板提 issue，并提供可复现 demo，帮助排查问题，谢谢

**Comment by lisun0459** [comment]
我也遇到这个问题，:src="reportDetail.article.imgurl"，图片已经渲染出来了，但是控制台报错thirdScriptError
Cannot read property 'imgurl' of undefined;at pages/article/main page lifeCycleMethod onReady function
TypeError: Cannot read property 'imgurl' of undefined

**Comment by fernandoxu** [comment]
@lisun0459 初始化的时候把对象的属性也列出来就不报错了。。反正我的是这样
