### ISSUE TITLE
@vue/cli 3.0 怎么创建mpvue项目?

### ISSUE THREAD

**Issue by wleven** [Meituan-Dianping/mpvue#704]
@vue/cli 3.0 怎么创建mpvue项目?

**Comment by aOrz** [comment]
https://cli.vuejs.org/guide/creating-a-project.html#pulling-2-x-templates-legacy

**Comment by NineSwordsMonster** [comment]
也就是说不支持 vue cli3？

**Comment by xieyezi** [comment]
为什么用3.0脚手架新建项目之后，微信开发工具导入不了

**Comment by abumphy** [comment]
首先，确定你已经全局安装了vuecli3.x；

然后，`npm install -g @vue/cli-init`；
> 根据文档，可以知道这是一个[桥接工具](https://cli.vuejs.org/guide/creating-a-project.html#using-the-gui)

最后，`vue init mpvue/mpvue-quickstart my-project`

**Comment by xiaomizhou66** [comment]
使用了 桥接工具 之后，出现了其他的问题，
`λ yarn                                                                                                                                     
yarn install v1.13.0                                                                                                                       
info No lockfile found.                                                                                                                    
[1/5] Validating package.json...                                                                                                           
[2/5] Resolving packages...                                                                                                                
warning css-loader > cssnano > autoprefixer > browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in oth
er tools.                                                                                                                                  
warning css-loader > cssnano > postcss-merge-rules > browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used
 in other tools.                                                                                                                           
warning css-loader > cssnano > postcss-merge-rules > caniuse-api > browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3
.0 config used in other tools.                                                                                                             
warning eslint > file-entry-cache > flat-cache > circular-json@0.3.3: CircularJSON is in maintenance only, flatted is its successor.       
warning px2rpx-loader > px2rpx > fs-extra > graceful-fs@3.0.11: please upgrade to graceful-fs 4 for compatibility with current and future v
ersions of Node.js                                                                                                                         
warning px2rpx-loader > px2rpx > fs-extra > graceful-fs > natives@1.1.6: This module relies on Node.js's internals and will break at some p
oint. Do not use it, and update to graceful-fs@4.x.                                                                                        
warning webpack-bundle-analyzer > bfj-node4@5.3.1: Switch to the `bfj` package for fixes and new features!                                 
[3/5] Fetching packages...                                                                                                                 
info fsevents@1.2.7: The platform "win32" is incompatible with this module.                                                                
info "fsevents@1.2.7" is an optional dependency and failed compatibility check. Excluding it from installation.                            
[4/5] Linking dependencies...                                                                                                              
warning "mpvue-loader > vue-loader@13.7.3" has unmet peer dependency "vue-template-compiler@^2.0.0".                                       
[5/5] Building fresh packages...                                                                                                           
success Saved lockfile.                                                                                                                    
Done in 29.32s.                                                                                                                            `

初始化会有很多的警告，然后项目没有 npm run dev

**Comment by xiaomizhou66** [comment]
```BASH
λ yarn                                                                                                                                     
yarn install v1.13.0                                                                                                                       
info No lockfile found.                                                                                                                    
[1/5] Validating package.json...                                                                                                           
[2/5] Resolving packages...                                                                                                                
warning css-loader > cssnano > autoprefixer > browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in oth
er tools.                                                                                                                                  
warning css-loader > cssnano > postcss-merge-rules > browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used
 in other tools.                                                                                                                           
warning css-loader > cssnano > postcss-merge-rules > caniuse-api > browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3
.0 config used in other tools.                                                                                                             
warning eslint > file-entry-cache > flat-cache > circular-json@0.3.3: CircularJSON is in maintenance only, flatted is its successor.       
warning px2rpx-loader > px2rpx > fs-extra > graceful-fs@3.0.11: please upgrade to graceful-fs 4 for compatibility with current and future v
ersions of Node.js                                                                                                                         
warning px2rpx-loader > px2rpx > fs-extra > graceful-fs > natives@1.1.6: This module relies on Node.js's internals and will break at some p
oint. Do not use it, and update to graceful-fs@4.x.                                                                                        
warning webpack-bundle-analyzer > bfj-node4@5.3.1: Switch to the `bfj` package for fixes and new features!                                 
[3/5] Fetching packages...                                                                                                                 
info fsevents@1.2.7: The platform "win32" is incompatible with this module.                                                                
info "fsevents@1.2.7" is an optional dependency and failed compatibility check. Excluding it from installation.                            
[4/5] Linking dependencies...                                                                                                              
warning "mpvue-loader > vue-loader@13.7.3" has unmet peer dependency "vue-template-compiler@^2.0.0".                                       
[5/5] Building fresh packages...                                                                                                           
success Saved lockfile.                                                                                                                    
Done in 29.32s.                                                                                                                            
```

**Comment by xiaomizhou66** [comment]
使用了 桥接工具，创建项目的时候就会有很多警告，然后最后项目没法 run dev

**Comment by kid1412621** [comment]
vue cli 都快出 4 了...

**Comment by zhaoyuanmeng** [comment]
这个cli4用不了这个啊 下载了cli-init也不行
