### ISSUE TITLE
可以引入小程序原生代码编写的组件吗？

### ISSUE THREAD

**Issue by ganchengyuan1990** [Meituan-Dianping/mpvue#707]
RT，在MPVUE中可以引入小程序原生代码编写的组件吗？是否需要特殊配置？

**Comment by konglx90** [comment]
同问 已经写了比较多的原生小程序代码了 怎么可以复用小程序的原生组件?

**Comment by JJJYY** [comment]
[`import-weapp-component`](https://github.com/JJJYY/import-weapp-component)

**Comment by aOrz** [comment]
http://mpvue.com/qa/#echarts
