### ISSUE TITLE
使用 mpvue/mpvue-quickstart 创建的项目没有开启热重载的吗？

### ISSUE THREAD

**Issue by Riant** [Meituan-Dianping/mpvue#709]
# 根据 5 分钟上手教程安装启动的小程序

**问题复现步骤:**

1. vue init mpvue/mpvue-quickstart my-project
2. npm install
3. cd my-project & npm run dev
4. 尝试修改 /pages/index/index 或者 /pages/counter/index 文件里边的 template/script/style 任一部分，保存文件

**期望的表现:**

如 Vue Web 项目一样，页面无刷新自动更新到了新的 UI, 样式，Js 逻辑等

**观察到的表现:**

小程序中的页面明显刷新了，导航到子页面的话，刷新之后也返回到首页了

查看了 /build/dev-server.js 文件，发现 hotMiddleware 相关代码被注释了，取消注释， npm run dev 跑不起来了。

但是看 issue ，貌似大家的热重载都这种基本问题；所以想问一下是 mpvue-quickstart 框架项目没有热重载的配置，还是说我缺少了其他的什么步骤？

谢谢。

**Comment by F-loat** [comment]
小程序无法支持网页里的 hot-reload，采用的是保存文件在本地，更新后重新生成的方式

**Comment by aOrz** [comment]
同上

**Comment by Riant** [comment]
嗯，明白了，那文档里边还是不要轻言 hot-reload 的好。

**Comment by tailorsira** [comment]
无法支持热更新是因为微信模拟器不支持websocket，因为模拟器客户端和小程序客户端无法与Node服务器保持通信，传递更新后的modules，因此这个mpvue是解决不了的。
