### ISSUE TITLE
怎么设置全局的component

### ISSUE THREAD

**Issue by shengxinjing** [Meituan-Dianping/mpvue#71]
你好，自己写了几个button、badge组件，想全局能使用，而不是每次都import，在哪里设置vue.component呢

**Comment by anchengjian** [comment]
就目前的实现方式来说，咱不支持全局 component ， 已加到 [需求池](https://trello.com/c/MBS4qUxO/25-%E5%85%A8%E5%B1%80-component-%E6%94%AF%E6%8C%81)

**Comment by xmsz** [comment]
又是3月份的需求
插个眼 继续关注
