### ISSUE TITLE
button组件open-type="launchApp" 绑定error事件问题

### ISSUE THREAD

**Issue by lianruhe** [Meituan-Dianping/mpvue#711]
# [问题简单描述]
button组件open-type="launchApp" 绑定error事件，第一次进入该页面点击button，当不能唤起app时没有回调error事件（能唤起时还没测试）。然后关闭小程序，当再次进入点击button，可以回调error事件
**问题复现步骤:**

1. 用mpvue初始化一个小程序项目，页面只写一个button
```
<button open-type="launchApp" @error="launchAppError">打开app</button>
....

methods: {
    launchAppError () {
      wx.showLoading({
        title: 'success'
      })
    }
  }
```
2. 第一次预览进入该页面，点击该按钮无法回调launchAppError方法
3. 关闭小程序，再从列表进入，点击可以响应

**期望的表现:**
用原生小程序是没有这种情况的。希望第一次可以响应

**Comment by Jayson1004** [comment]
我也碰到这个问题，你现在解决了吗？

**Comment by lianruhe** [comment]
@Jayson1004 感觉好像是微信的问题，因为查看了知乎和大众点评的分享返回到app也会第一次不能响应。目前我是监听click事件，第一次响应click走error逻辑，之后click不做响应（目前只想到这种丑陋做法～～）

**Comment by huangzenghuang** [comment]
我这边走小程序支付试了一下@click事件，放回上一页好像不是很管用
      wx.navigateBack({
        delta: -1
      })
