### ISSUE TITLE
vue页面可以引用原生组件，但vue的component不能引用原生组件

### ISSUE THREAD

**Issue by TonyLuo** [Meituan-Dianping/mpvue#713]
vue页面可以引用原生组件，但vue的component不能引用原生组件

**Comment by yuconora** [comment]
参考https://github.com/mpvue/examples/tree/master/echarts

**Comment by TonyLuo** [comment]
https://github.com/mpvue/examples/tree/master/echarts只是页面级别引用原生组件，如果是vue的组件级别的文件引用不了原生组件

**Comment by anchengjian** [comment]
不支持混用
