### ISSUE TITLE
请问如何改变页面背景颜色？设置page样式不起作用

### ISSUE THREAD

**Issue by 85636682** [Meituan-Dianping/mpvue#719]
# [问题简单描述]
请问如何改变页面背景颜色？设置page样式不起作用

**Comment by hurely** [comment]
按照如下这样设置可以，你可以试一下，另外我这是局部设置
`<style>
page {
  width: 100%;
  height: 100%;
  background-color: #FF4B00;
}
<style>`

**Comment by aOrz** [comment]
同上

**Comment by pengjinlong** [comment]
这个问题解决了吗？还是无法设置呀

**Comment by yellowpig** [comment]
在入口文件App.vue中设置page样式，可以改变所有页面的背景颜色
`<style>
page {
  background-color: #e6e6e6;
}
</style>`
