### ISSUE TITLE
将组件做为slot时,报template not found

### ISSUE THREAD

**Issue by linrui1994** [Meituan-Dianping/mpvue#72]
```html
<!-- 打开的页面 -->
<card>
    <testslot></testslot>
</card>
<script>
components: {
  card,
  testslot
}
</script>
```

```html
<!-- card.vue -->
<div>
    <slot></slot>
</div>
```

```html
<!-- testslot.vue -->
<span>123</span>
```

![image](https://user-images.githubusercontent.com/20953049/37344375-29a2bc8e-2705-11e8-8c9e-b788aa136786.png)

**Comment by linrui1994** [comment]
这个特性不打算支持吗，这样组件不能嵌套组件，如何做组件库呢?

**Comment by linrui1994** [comment]
在mpvue-loader/lib/mp-compiler/index.js中的 createSlotsWxml中，不知道为什么使用emitFile生成出来的slots会缺失导致上面的bug。
下面终端截图打印出来的是正常的，但是生成出来的结果少了。
![image](https://user-images.githubusercontent.com/20953049/37418466-40ee7fb6-27ed-11e8-8f7e-79ec22924e95.png)
![image](https://user-images.githubusercontent.com/20953049/37418567-7970d122-27ed-11e8-849a-010b629b6179.png)

改成使用fs.writeFile后能正常输出。

**Comment by linrui1994** [comment]
@anchengjian 

生成的wxml变量可能也有问题，应该得生成 style={{style}}  但是变成了 style={{ tyl}}

截图是源码和对应输出的文件

![image](https://user-images.githubusercontent.com/20953049/37443434-1610d60e-2847-11e8-86a1-09c8f9006a26.png)

![image](https://user-images.githubusercontent.com/20953049/37443427-08a16efc-2847-11e8-8a5d-895014d6f906.png)

**Comment by anchengjian** [comment]
嗯，style 那儿是一个 bug

**Comment by anchengjian** [comment]
@linrui1994 style 问题修复了，考虑到 scoped 事件等若干复杂情况，将组件作为 slot 目前还无法支持。已经添加到 [支持更复杂的-slot](https://trello.com/c/UKF5tFv9/34-%E6%94%AF%E6%8C%81%E6%9B%B4%E5%A4%8D%E6%9D%82%E7%9A%84-slot) 计划表

**Comment by linrui1994** [comment]
好的 感谢大佬

**Comment by anchengjian** [comment]
[1.0.8](https://github.com/Meituan-Dianping/mpvue/releases/tag/1.0.8) 已修复，请升级相应的 `mpvue mpvue-template-compiler mpvue-loader` 后使用

**Comment by linrui1994** [comment]
👍
