### ISSUE TITLE
`globalData` 在 App.vue `onShow` 方法中，未定义

### ISSUE THREAD

**Issue by yingye** [Meituan-Dianping/mpvue#722]
# [问题简单描述]

**问题复现步骤:**

1. 在 App.vue 中定义 `globalData`，在 `onShow` 方法中调用，undefined

```
<script>
export default {
  globalData: {
    hasLogin: false
  },
  onShow () {
    console.log('this.globalData', this.globalData)
  }
}
</script>
```

**期望的表现:**

可以正常设置 `this.globalData`

**屏幕截图和动态 GIF 图**
![image](https://user-images.githubusercontent.com/19258729/42305688-b29b46d4-805e-11e8-9e17-833c38b2c0c1.png)

**Comment by shaonialife** [comment]
globalData 这种写法完全是原生小程序不完善之下的产物, 用vue完全不需要这中写法

**Comment by aOrz** [comment]
this 指向不同

**Comment by yingye** [comment]
@aOrz 那在APP.vue 中，怎么使用？无法支持吗？

**Comment by yingye** [comment]
藏得好深...
![image](https://user-images.githubusercontent.com/19258729/42493097-134d356c-844e-11e8-9609-b240a4a7f4cc.png)

**Comment by lessthanno** [comment]
完全没有必要使用globalData

**Comment by cdll** [comment]
所以我一个老项目赋值了getApp().user= {}重构为mpvue应该怎么处理呢?

**Comment by yingye** [comment]
在 this.$mp.app.globalData 里面设置

**Comment by cdll** [comment]
@yingye 感谢, 不过我这边是要在Page的onLoad里面读取``getApp()``下的user, 现在看来``mpvue``在Page的onLoad里是没有``this.$mp.app.globalData``的

**Comment by cdll** [comment]
试了一下在Page的onShow里面也是没有``this.$mp``的

**Comment by yingye** [comment]
那直接使用 getApp() 就可以，这个issue里面说的是 app.js 中的使用
