### ISSUE TITLE
为什么编译会提示这个异常？

### ISSUE THREAD

**Issue by yzbgyq** [Meituan-Dianping/mpvue#726]
![1aa4ed3765eeed44d4572dfd8b76405](https://user-images.githubusercontent.com/32931212/42360077-fb74927e-8118-11e8-84f9-af229dee346a.png)

**Comment by aOrz** [comment]
代码里面有引用这三个文件吗

**Comment by yzbgyq** [comment]
有引用的

**Comment by aOrz** [comment]
建议去小程序官方那问下
