### ISSUE TITLE
[Feature Request] 添加对子组件引用的支持

### ISSUE THREAD

**Issue by samwang1027** [Meituan-Dianping/mpvue#73]
[子组件引用](https://cn.vuejs.org/v2/guide/components.html?#%E5%AD%90%E7%BB%84%E4%BB%B6%E5%BC%95%E7%94%A8)
![image](https://user-images.githubusercontent.com/11900676/37346694-f063a644-270a-11e8-8913-8857aab2e300.png)

**Comment by samwang1027** [comment]
临时解决方案：
```
export const getComponentByTag = (parent, tag) => {
  for (let c of parent.$children) {
    if (c.$options._componentTag === tag) {
      return c
    }
  }
}
```

```
export default {
    components: {
      toptips: ZanTopTips
    },
    data () {
      return {
      }
    },
    methods: {
      showTopTips () {
        getComponentByTag(this, 'toptips').showZanTopTips('toptips的内容')
      }
    }
  }
```

**Comment by anchengjian** [comment]
$refs 更多时候有 DOM 相关操作，支持意愿不大，建议直接从 $children 属性进行获取。

**Comment by F-loat** [comment]
通过 $refs 来调用子组件的方法这种场景也比较多见，希望后面能支持

**Comment by zhangfuli** [comment]
如何获取dom节点呢？既然用vue来编写，我觉得这种情况也是很常见

**Comment by ZzMark** [comment]
获取dom应该是不行的，毕竟小程序本就没有传统意义上的dom操作

**Comment by zhangfuli** [comment]
虽然小程序没有dom操作，我觉得mpvue可以增加对wx.createSelectorQuery()的适配和扩展

**Comment by saint3347** [comment]
![image](https://user-images.githubusercontent.com/7347133/40595179-b10fca54-6265-11e8-8b42-2c76148d9b45.png)
this.$refs['xxx']是undefined

希望尽快支持refs引用。。

**Comment by saint3347** [comment]
希望尽快支持refs子组件引用。。。

**Comment by F-loat** [comment]
子组件引用在 v1.0.9 开始支持，普通节点暂不考虑支持
