### ISSUE TITLE
使用原生Swpier组件   在image 上 绑定点击事情 无效的问题

### ISSUE THREAD

**Issue by jackycaojiaqi** [Meituan-Dianping/mpvue#734]
# [问题简单描述]
使用原生Swpier组件   在image 上 绑定点击事情 回调方法没有响应，是我使用方式有误吗？而且我尝试了将  @click="onItemClick"  写在image的外面任何一层，结果一样不能得到回调。

我想要的效果就是 ，点击轮播图 跳转 看大图，但是得不到点击事件，所以无法进行跳转

**问题复现步骤:**

1. 

```
  <div class="page" >
                <swiper style="height: 11rem" :indicator-dots="indicatorDots" :autoplay="autoplay" :interval="interval" :duration="duration" :circular="circular" >
                    <div  v-for="(item,index) in loops" :key="index">
                      <swiper-item >
                          <image  @click="onItemClick" :src="item.imgserver" class="slide-image" style="width: 100%" />
                      </swiper-item>
                    </div>
                </swiper>
        </div>
```

2. 如上诉代码   在image中 绑定事件后   onItemClick方法中 没有回调

```
 methods: {
     onItemClick() {
       console.log("onItemClick");
     }
   }
 
```

**Comment by ExcellentJR** [comment]
@jackycaojiaqi 
`<div v-if="item.detail.mainPicture.length>1" @tap="getGoodDetail(item.id, item.type)">`
            `<swiper style="width: 100vw;height: 700rpx;" `
             ` :indicator-dots="indicatorDots" `
             ` :indicator-color="indicatorColor" `
            `  :indicator-active-color="indicatorActiveColor"`
             ` :autoplay="autoplay" `
              `:interval="interval" `
              `:duration="duration" `
              `:circular="circular" `
              `@change="swiperChange" `
             ` @animationfinish="animationfinish"`
            `>`
              `<div v-for="(imgItem, imgIndex) in item.detail.mainPicture" :key="imgIndex">`
               ` <swiper-item>`
                 ` <image :src="imgItem" class="slide-image" />`
                `</swiper-item>`
              `</div>`
            `</swiper>`
          `</div>`
我这里这样写的是可以点击的，你是想点击不同的图片跳转到不同的链接吗？

**Comment by jackycaojiaqi** [comment]
后来发现是 在组件中   点击事件就会无效   我的做法是  放在  index.vue  中。
