### ISSUE TITLE
vuex中引入一个module叫app.js，然后就编译时候假死

### ISSUE THREAD

**Issue by kala888** [Meituan-Dianping/mpvue#736]
一个神奇的bug
引入一个叫app的module

![image](https://user-images.githubusercontent.com/1215976/42504157-68b84ee6-846d-11e8-9c01-68876e097968.png)

然后npm run dev,npm run build 就卡起不动了，去掉这个module，就好了

![image](https://user-images.githubusercontent.com/1215976/42504191-8523e5c2-846d-11e8-9495-88a1d5bd496c.png)

当然，把app.js改名，也可以

**Comment by F-loat** [comment]
app 和 config 应该都有特殊处理，暂时规避下吧
