### ISSUE TITLE
元素的类名中"data-v-"是否可以去除?

### ISSUE THREAD

**Issue by Darcrandex** [Meituan-Dianping/mpvue#738]
编译后的元素, 类名的部分会有一个'data-v-'开头的类名, 这个类名的作用是什么, 是否可以去掉, 如果可以, 应该怎么做?

**Comment by F-loat** [comment]
居然就快三个月了。。过两天放假了处理下 https://github.com/mpvue/mpvue-loader/pull/12

**Comment by HellKingdom** [comment]
这个类名是将样式锁定到当前界面，去除style 中的scope就可以了@Darcrandex
