### ISSUE TITLE
Vue.component()的第一个参数必须为静态字符串

### ISSUE THREAD

**Issue by Kellercai** [Meituan-Dianping/mpvue#740]
src/main.js
```
import { cpInput } from '@/components'
// 全局注册组件
const components = [
  cpInput
]
components.map(component => {
  Vue.component(component.name, component)
})
```

**问题复现步骤:**
_**报错**_
![image](https://user-images.githubusercontent.com/20681598/42557277-9a53198c-8520-11e8-97f4-a57293e9dfdc.png)

**_打印出来的组件，存在name的key值。_**
![image](https://user-images.githubusercontent.com/20681598/42557335-cdb34b9e-8520-11e8-981c-175b561ff64b.png)

**_报错源码出处_**
![image](https://user-images.githubusercontent.com/20681598/42557452-2c5bb5aa-8521-11e8-8237-fcc724f59ac0.png)

**期望的表现:**
能够正常在所有页面中全局引用组件

**Comment by anchengjian** [comment]
因为 template 需要编译到 wxml ，这就会导致全局组件这种语法糖支持程度不会很高
