### ISSUE TITLE
组件嵌套 props 传值无效

### ISSUE THREAD

**Issue by fancymo** [Meituan-Dianping/mpvue#741]
组件嵌套 props 传值无效，在 template 里，如 Star 的 size，渲染时获取不到值，但是在组件Star生命周期函数内可以获取到对应的属性 size。确认组件写法没问题，目前仅在嵌套组件用 slot 渲染时会发生问题。

对应的写法大致如下：
```
// mian.vue
...
<List>
    <OrderItem :dataSource="dataSource"></OrderItem>
</List>
...
```
```
// OrderItem.vue
...
<div>
    <Star :size="20"></Star>
</div>
...
```
```
// Star.vue
...
```
望回复，谢谢！

**Comment by weikx** [comment]
应该是List或其他组件命名冲突了
把出问题的组件换个名字试试

**Comment by fancymo** [comment]
问题已解决，查看了对象上props是已经传进子组件，没有渲染原因推测是命名不符合mp-vue规范，渲染时替换组件名就可以了。
