### ISSUE TITLE
打包不自动编译wxss问题

### ISSUE THREAD

**Issue by LinFeng1987** [Meituan-Dianping/mpvue#743]
1. 运行npm run dev
2. \dist\static\css下没有编译wxss
3. \dist\pages下正常
4.mpvue中使用的less
![image](https://user-images.githubusercontent.com/16728816/42574613-60ee437a-8551-11e8-921a-18a20cacb584.png)

**Comment by LinFeng1987** [comment]
找了一下其它问题，也有踩过坑的同学，目前已解决。谢谢大佬 支持vue支持mpvue

**Comment by aOrz** [comment]
已解决问题先关了

**Comment by LaxusT** [comment]
这个问题如何解决的 @LinFeng1987

**Comment by LinFeng1987** [comment]
@LaxusT 
![image](https://user-images.githubusercontent.com/16728816/43364757-efe03d36-9352-11e8-88de-fa3ed2d7d93f.png)
