### ISSUE TITLE
mian.js创建实例时添加provide后在app.vue以及其子组件中无法取到值

### ISSUE THREAD

**Issue by chaim1986** [Meituan-Dianping/mpvue#744]
# [问题简单描述]

// main.js 
const app = new Vue({
  ...App,
  provide: { a: 'hello' },
});
app.$mount();

// app.vue
export default {
    name: 'App',
    inject: ['a'],
    mounted() {
    console.log(this.a);    //取不到，输出undefined
  },

上面这种provide不能生效。

**问题复现步骤:**

【  "mpvue": "^1.0.11"】

1. [第一步]

main js 里面 创建实例时，加入provide 编译不报错，但是vue以及子组件inject不到provide。

**期望的表现:**

期望可以取到。

**Comment by anchengjian** [comment]
注意一下

```
// main.js
const app = new Vue({
...App,
provide: { a: 'hello' },
})
```

App.vue 就是根组件，可能会导致你在根组件里面 inject 不到值
