### ISSUE TITLE
build产出带有hash的文件，导致小程序无法找到module

### ISSUE THREAD

**Issue by tonyc726** [Meituan-Dianping/mpvue#746]
# [问题简单描述]
第一次接触小程序，项目使用`vue init mpvue/mpvue-quickstart my-project`初始化，在完成开发，运行`npm run build`后，小程序报错，提示相关模块无法找到。

**问题复现步骤:**

1. `npm run build`
2. Console控制台报错

**期望的表现:**
能够正确识别hash过的文件

**观察到的表现:**
小程序无法识别hash过的文件，导致程序无法运行

**屏幕截图和动态 GIF 图**

![image](https://user-images.githubusercontent.com/2699004/42645678-3f739020-8631-11e8-85d3-7288b9ddd22d.png)

**Comment by chinadbo** [comment]
遇到同样的问题

**Comment by tonyc726** [comment]
resolved，直接去除webpack配置中的`[hash]`部分，不过文档中没有找到此处的说明
