### ISSUE TITLE
打开多个同一页面，页面数据互相影响

### ISSUE THREAD

**Issue by wJianZhong** [Meituan-Dianping/mpvue#747]
# [问题简单描述]
商城小程序，列表（1）进入详情页（A）（获取并展示当前商品详情），如果这个详情页有通往另一个列表（2）的入口（比如店铺），在列表（2）再点开一个商品到详情页（B）（获取并展示当前商品详情）。
这个时候开始返回，返回到详情（A）的时候发现其页面展示数据是详情（B）的，页面query参数也会最后一个的了。
为了避免尴尬，只能用redirect，请问有更好的解决办法吗？

**Comment by F-loat** [comment]
#140

**Comment by wJianZhong** [comment]
#140 又更新了一些临时方案

**Comment by zxzhgk** [comment]
使用 https://github.com/HelloZJW/mpvue-page-factory 他的这个方法可以解决同一页面多次访问时 watch,props,computed 等一系列缓存问题
