### ISSUE TITLE
mpvue可以使用mixins混入吗？如果可以，请解答

### ISSUE THREAD

**Issue by xfFelix** [Meituan-Dianping/mpvue#748]
# [问题简单描述]

**问题复现步骤:**

1. [第一步]
2. [第二步]
3. [其他步骤...]

**期望的表现:**

[在这里描述期望的表现]

**观察到的表现:**

[在这里描述观察到的表现]

**屏幕截图和动态 GIF 图**

![复现步骤的屏幕截图和动态 GIF 图](图片的 url)

**Comment by shaonialife** [comment]
可以

**Comment by anchengjian** [comment]
https://github.com/Meituan-Dianping/mpvue/issues/385 类似，可以多看文档 https://vuejs.org/v2/guide/mixins.html

**Comment by xfFelix** [comment]
thanks，mixins大多数是运用于什么场景，我是用于封装commons API，感觉有点杀猪用牛刀了

**Comment by PureJoker** [comment]
是因为你mixin用在来两个组件上吗
