### ISSUE TITLE
mpvue应该是支持svg的吧，然而显示不出来，是姿势问题吗

### ISSUE THREAD

**Issue by lendie** [Meituan-Dianping/mpvue#749]
# [问题简单描述]

`**问题复现步骤: <svg height='110px' width='144px' xmlns="http://www.w3.org/2000/svg">
    <rect x="10" y="10" width="50px" height="50px" style="fill:#fdd835;"></rect>
  </svg>`

**期望的表现: `希望有一个矩阵`

[在这里描述期望的表现]

**观察到的表现:矩阵显示长宽为0*0

[在这里描述观察到的表现]

**屏幕截图和动态 GIF 图*
![screenshot from 2018-07-13 17-17-19](https://user-images.githubusercontent.com/30063965/42683738-c61e8212-86c0-11e8-87a8-37aa505eb8b5.png)

![复现步骤的屏幕截图和动态 GIF 图](图片的 url)

**Comment by fancymo** [comment]
小程序自身对svg支持不好～
