### ISSUE TITLE
需要更改什么呢？

### ISSUE THREAD

**Issue by lanshengzhong** [Meituan-Dianping/mpvue#75]
import base64 from '@/utils/base64.min.js'

![image](https://user-images.githubusercontent.com/20151096/37350925-e78a3380-2714-11e8-9b35-c2ba8a85dbc8.png)

**Comment by anchengjian** [comment]
抱歉，不知道 base64.min.js 咋封装的？

从报错看应该是你的模块包装问题。

**Comment by lanshengzhong** [comment]
感谢，确实是我这边的问题
