### ISSUE TITLE
怎么取到用户二维码分享出去，用户扫描二维码进入携带的参数 

### ISSUE THREAD

**Issue by yzbgyq** [Meituan-Dianping/mpvue#750]
# [问题简单描述]

**问题复现步骤:**

1. [第一步]
2. [第二步]
3. [其他步骤...]

**期望的表现:**

[在这里描述期望的表现]

**观察到的表现:**

[在这里描述观察到的表现]

**屏幕截图和动态 GIF 图**

![复现步骤的屏幕截图和动态 GIF 图](图片的 url)

**Comment by hucq** [comment]
如果你说的是 `扫普通链接二维码打开小程序` 的场景，直接在 onload 入参中可获取到完整的 url 地址，其中包含了带入的参数。

另外：问题描述请准确填写，否则不能有效沟通。
