### ISSUE TITLE
Bus 监听事件接手值，不刷新页面

### ISSUE THREAD

**Issue by LIZHIBIN513** [Meituan-Dianping/mpvue#751]
# [问题简单描述]
B页面使用Bus 监听A页面之间的传递,更新data中的数据，B页面并不会刷新页面。
**问题复现步骤:**

1. [第一步]
2. [第二步]
3. [其他步骤...]

**期望的表现:**

[在这里描述期望的表现]

**观察到的表现:**

[在这里描述观察到的表现]

**屏幕截图和动态 GIF 图**

![复现步骤的屏幕截图和动态 GIF 图](图片的 url)

**Comment by anchengjian** [comment]
麻烦给个复现的 demo，看完都不明白 A 和 B 页面究竟是什么级别，怎么触发的。
