### ISSUE TITLE
使用vux报错

### ISSUE THREAD

**Issue by dzlishen** [Meituan-Dianping/mpvue#752]
# [问题简单描述]
引用vux中的组件编译就报错了。
**问题复现步骤:**

1. [第一步]
2. [第二步]
3. [其他步骤...]

**期望的表现:**

[在这里描述期望的表现]

**观察到的表现:**

[在这里描述观察到的表现]

**屏幕截图和动态 GIF 图**

![复现步骤的屏幕截图和动态 GIF 图](图片的 url)

**Comment by anchengjian** [comment]
https://github.com/Meituan-Dianping/mpvue/issues/10
https://github.com/Meituan-Dianping/mpvue/issues/477
https://github.com/Meituan-Dianping/mpvue/issues/168

约等于不支持这种重依赖 DOM 和 BOM 的 UI 框架
