### ISSUE TITLE
您好，这个项目会一直维护吗？

### ISSUE THREAD

**Issue by lycHub** [Meituan-Dianping/mpvue#753]
我看release似乎并不频繁，请问该项目会随着vue和小程序一直更新下去吗？

**Comment by lycHub** [comment]
vue-cli马上发布3.0，已经用create代替init创建项目了，mpvue会更新吗？

**Comment by hucq** [comment]
1. mpvue 会持续维护，有自己的发版节奏，并不严格跟随 vue 和小程序的节奏。
2. vue-cli 暂是不计划更新。

**Comment by lycHub** [comment]
好的  谢谢解答
