### ISSUE TITLE
 安装webpack4之后不能npm run dev 不能正常工作了

### ISSUE THREAD

**Issue by Create-Peace** [Meituan-Dianping/mpvue#754]
# [问题简单描述]
安装了webpack4之后， 出现了这个问题，现在没有办法正常的开发小程序了，
(node:7136) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
(node:7136) DeprecationWarning: Tapable.apply is deprecated. Call apply on the plugin directly instead
没有找到空闲端口，请打开任务管理器杀死进程端口再试 Error: Plugin could not be registered at 'jsonp-script'. Hook was not found.
BREAKING CHANGE: There need to exist a hook at 'this.hooks'. To create a compatiblity layer for this hook, hook into 'this._pluginCompat'.
**问题复现步骤:**

1. [第一步]
2. [第二步]
3. [其他步骤...]

**期望的表现:**

[在这里描述期望的表现]

**观察到的表现:**

[在这里描述观察到的表现]

**屏幕截图和动态 GIF 图**

![复现步骤的屏幕截图和动态 GIF 图](图片的 url)

**Comment by aOrz** [comment]
暂不兼容 webpack4

**Comment by pantt** [comment]
我也是同样的错误，升级到了mpvue2.0还是报错

**Comment by AnKangZhouWei** [comment]
怎么解决的呢???

**Comment by cdd111** [comment]
请问解决了了吗 一样的报错

**Comment by pantt** [comment]
> 请问解决了了吗 一样的报错

官方回复了啊，不兼容webpack4，只能用3.x版本的，我的项目里面有个框架上传了，你看看需要不

**Comment by cdd111** [comment]
> > 请问解决了了吗 一样的报错
> 
> 官方回复了啊，不兼容webpack4，只能用3.x版本的，我的项目里面有个框架上传了，你看看需要不
我看到issue有人更新了webpack4方案
