### ISSUE TITLE
怎么在mpvue项目里面写img便签的样式

### ISSUE THREAD

**Issue by AllenZho** [Meituan-Dianping/mpvue#755]
# [问题简单描述]
怎么在mpvue项目里面写img便签的样式
**问题复现步骤:**
写的img标签样式全被转成了._img

**期望的表现:**
我希望支持自定义标签样式
这样就可以修改rich-text里面支持标签的样式

**Comment by hucq** [comment]
`便签` 是 `标签` 的意思么？

小程序的标签集合和 HTML 并不完全一致, mpvue 会做映射转换，css 中的 标签选择器会做同步修改。如你遇到的例子：写 img 标签且写 img 标签选择器的样式规则，我们会在模板语法上转换成 image 标签，同时将 img {} 转换成 ._img {}, 并附加到 image 标签上。

建议你直接写 class 选择器。
