### ISSUE TITLE
(node) warning: possible EventEmitter memory leak detected. 16 listeners added. Use emitter.setMaxListeners() to increase limit.

### ISSUE THREAD

**Issue by tomatosqq** [Meituan-Dianping/mpvue#757]
表单页面跳转到下一个表单页面的时候报这个错误，不知道如何解决，网上给了方案：
const emitter = new EventEmitter()
emitter.setMaxListeners(100)//指定一个最大监听数量

emitter.setMaxListeners(0)//或者关闭最大监听阈值
但是不知道放在哪个，也不知道对不对

**Comment by anchengjian** [comment]
这个是 Node.js 报出来的警告，跟小程序没关系。。。贴报错截图或者复现的 demo 吧

**Comment by tomatosqq** [comment]
贴出来了报错了

**Comment by anxsec** [comment]
在远程调试中也遇到了这个报错，只有在远程调试中会出现，不影响功能。

**Comment by anchengjian** [comment]
这看起来是开发者工具抛的异常，建议去小程序社区反馈。

**Comment by DearAKuan** [comment]
我也碰到这个问题了 请问楼主解决了吗
