### ISSUE TITLE
尽管绑定了 v-model，但是仍然无法清空 textarea 的内容（数据单向流动，能获取，不能设置）

### ISSUE THREAD

**Issue by gemmi** [Meituan-Dianping/mpvue#763]
# [问题简单描述]
用 v-model 给 textarea 绑定变量txt后，无法通过this.txt=‘’对 textarea 进行清空

**问题复现步骤:**

1. [第一步]
自定义 mask 组件
2. [第二步]
在mask 组件中的 slot 中使用 textarea
```html
<mask :isVisiable="isVisiable">
        //...
        <textarea v-model="txt"  name="textarea" />
        <button @click="changeTxt"></button>
      //...
</mask>
```
3. [其他步骤...]
在 methods.changeTxt 中对txt变量置空：
```js
changeTxt(){
    this.txt = ''
}
````

**期望的表现:**

textarea 中内容被清空
重新打开 mask（通过isVisiable变量控制），textarea 中内容为空

**观察到的表现:**

textarea 中内容没有变化，重新打开后，textarea 内容仍在，即无法通过 js 对 textarea 进行清空。
但是通过 v-model 可以单向绑定 textarea 的内容，即可以获取到 textarea 输入的内容，但是无法设置为空。

**屏幕截图和动态 GIF 图**

由于某些原因无法截图

**Comment by F-loat** [comment]
小程序文档有写不推荐对 textarea 的内容进行操作，通过 form 进行重置吧

**Comment by gemmi** [comment]
@F-loat 恩,好的,也就是说要使用textarea和提交按钮, 必须包在form里, 而不能单独拿出来用,对吗?

**Comment by gemmi** [comment]
今天试了下，form 并没有 reset 方法调用，也就是说，要提交后清空 textarea，还是没有办法的，只能通过点取消按钮触发 reset 事件来清空。
这个问题还是没解决呀？

**Comment by gengchen528** [comment]
> 小程序文档有写不推荐对 textarea 的内容进行操作，通过 form 进行重置吧

我在苹果6s机器上测试发现，textarea组件在进行v-model绑定时失效，已经输入内容，v-model绑定的值却没有变化
