### ISSUE TITLE
自定义组件不支持v-model

### ISSUE THREAD

**Issue by Airkro** [Meituan-Dianping/mpvue#766]
**问题复现步骤:**

1. [第一步] 创建小程序自定义组件

```js
Component({
  methods: {
    switchTab() {
      this.triggerEvent('change', 123);
      this.triggerEvent('input', 123);
    }
  }
});
```

2. [第二步] 引入组件
```html
<my-component v-model="count" />
```

**期望的表现:**

像小程序input、select组件一样支持v-model

**观察到的表现:**

自定义组件使用v-model指令时，value被成功传递，但是事件无法触发

**Comment by anchengjian** [comment]
自定义组件和 Vue 的组件不复用，mpvue 组件机制的实现也不是用的小程序自定义组件，完全无法通用。

**Comment by JL-Code** [comment]
意思是没有办法了吗

> 自定义组件和 Vue 的组件不复用，mpvue 组件机制的实现也不是用的小程序自定义组件，完全无法通用。

意思是没有解决方法了吗
