### ISSUE TITLE
是否支持引入 element-ui

### ISSUE THREAD

**Issue by zhaowanhua** [Meituan-Dianping/mpvue#767]
我已经使用mpvue开发了一段时间，小程序也一直编译的很顺利，最近想要在项目中引入 element-ui，按照官网做了下来，会报错，想请问下，是否支持引入呢？
如果不支持，推荐配套的ui框架是什么呢？
谢谢！

![ibwvw1763w5i z0mlzz_nn](https://user-images.githubusercontent.com/22017926/42866443-1b135018-8a9f-11e8-9dc4-67ecd3cc1570.png)

**Comment by aOrz** [comment]
#10
#477
#168

约等于不支持这种重依赖 DOM 和 BOM 的 UI 框架
