### ISSUE TITLE
为什么我定义了组件，prop传值无效

### ISSUE THREAD

**Issue by shiweiqi19930328** [Meituan-Dianping/mpvue#77]
我定义了个cell组件
`<template>
  <div class="weui-cell">
    <div class="weui-cell__bd">{{title}}</div>
    <div class="weui-cell__ft">{{value}}</div>
  </div>
</template>

`<script>`
export default {
  name: 'cell',
  props: {
    title: {
      type: String,
      default: 'cell标题'
    },
    value: {
      type: String,
      default: ''
    }
  },
  data(){
    return {
      
    }
  },
  mounted(){
    console.log('我是组件cell')
    console.log(this.title)
  }
}
</script>

<style>

</style>`
引用后prop传值，组件解析了，但是没有值，组件的mounted钩子也没生效，什么原因
`import cell from '@/components/cell/cell.vue'
export default {
  components : {
    cell
  },`
`<cell title="cell标题" value="cell内容"></cell>`

**Comment by Grain-full** [comment]
你试试props去除type

**Comment by heroofchina** [comment]
写错了 大哥 传值的时候 title前面加上: (冒号)
这样 <cell   ：title="cell标题"  ：value="cell内容"></cell>

**Comment by fansenze** [comment]
都说的什么玩意儿。
':' 忘加不是根本问题
根本问题是父组件引入使用该组件使用的时候, 该组件标签不能是 cell, 估计是 loader 那边冲突了

**Comment by kaykie** [comment]
也不能用list  用list也是一样的问题
