### ISSUE TITLE
为什么不将p标签转成小程序的text组件呢？转成view展示文字会有问题，后端返回的文字里的回车符并不会换行，而text组件就可以。

### ISSUE THREAD

**Issue by fernandoxu** [Meituan-Dianping/mpvue#770]
# [问题简单描述]
如标题
**问题复现步骤:**

1. [第一步]
后端返回的数据是一段文字，回车符号表示换行。
2. [第二步]
用p标签展示拿到的数据，p标签被转成了view，回车符转义成了空格，造成展示错误。

**期望的表现:**
[在这里描述期望的表现]
p转换成小程序的text组件，文字可以正常展示。
**观察到的表现:**

[在这里描述观察到的表现]

**Comment by shaonialife** [comment]
因为p是块级元素, 而text是内联元素

**Comment by anchengjian** [comment]
@shaonialife 说的对，建议加 css 样式 `white-space: pre;` 试试
