### ISSUE TITLE
页面是单例的吗

### ISSUE THREAD

**Issue by Murphycx94** [Meituan-Dianping/mpvue#774]
# 页面是单例的吗？

**复现:**

1. 首先我打开A页面
2. 从A页面wx.navigateTo跳转到B页面
3. 再从B页面跳转的新的A页面，结果数据还是最初的A页面。

真实场景：
1. 打开A用户的粉丝列表
2. 在粉丝列表中点开某个用户B的个人主页
3. 从用户B的个人页进入用户B的粉丝列表
4. 此时粉丝列表的数据是A用户的粉丝列表，如果重新获取一遍数据覆盖的话，点返回到A的粉丝列表，数据就变成B的数据了

**期望的表现:**

能否在保持A粉丝列表页面状态的同时，打开一个新B粉丝列表

**Comment by F-loat** [comment]
#140
