### ISSUE TITLE
请问下如何让mpvue使用vue组件库（比如ele），和vue-cli一样吗？

### ISSUE THREAD

**Issue by JokerLoLgrey** [Meituan-Dianping/mpvue#775]
如题，现在根据网上的方法暂时只实现使用小程序第三方ui组件库，vue的第三方ui组件库会使vendor.js过大，请问支持cdn引入vue第三方组件库吗？

**Comment by aOrz** [comment]
由于小程序的限制不支持使用 cdn 引入
