### ISSUE TITLE
eventid 和data-eventid 问题

### ISSUE THREAD

**Issue by fshare** [Meituan-Dianping/mpvue#78]
如：<view @click="showList" id="market-all" eventid="market-all" data-eventid="market-all">添加自选行情</view>
如果不加eventid 和data-eventid 属性，会调用页面中所有绑定有事件的标签一次
swichNav事件有13个标签绑定，点击“添加自选行情”，swichNav同时调用了13次
加了eventid 和data-eventid 属性，就不会多次调用了

**Comment by anchengjian** [comment]
eventid 和data-eventid 这俩属性是通过 compiler 生成的，目前请避免使用相同属性，以免发生冲突。后期考虑换特殊一点的标识符。

**Comment by kevinlvhsl** [comment]
表单组件提交
```
<form report-submit="true">
    <button formType="submit">Submit</button>
</form>
```
提交后为什么拿不到formId了，没有formId，你们是怎么推送模板消息的？

**Comment by anchengjian** [comment]
@kevinlvhsl  可以拿到

``` html
<template>
  <div>
    <form report-submit="true" @submit="formSubmit">
      <button formType="submit">Submit</button>
    </form>
  </div>
</template>

<script>
export default {
  data () {
    return {}
  },
  methods: {
    formSubmit (e) {
      console.log('Submit', e)
    }
  }
}
```

**Comment by lessthanno** [comment]
@anchengjian 很奇怪，打印了formSubmit中返回的event，但是event.detail是空的，得event.mp.detail才能获取到值
