### ISSUE TITLE
macOS文件static路径问题

### ISSUE THREAD

**Issue by 1255437355** [Meituan-Dianping/mpvue#781]
# [问题简单描述]
今天下载的mpvue包，在static下的图片文件无法显示
**问题复现步骤:**
在main.json下的list选项里，放入iconPath的路径，如/static/img/icon.png，报错，找不到文件。必须输入../static/img/icon.png，这样虽然报错消失，但是底部导航的icon图标无法显示。

**Comment by anchengjian** [comment]
是今天创建的工程？还是之前的工程只更新了依赖包？

**Comment by aOrz** [comment]
同 #782
