### ISSUE TITLE
编译.wxss出错问题

### ISSUE THREAD

**Issue by zhuxchen** [Meituan-Dianping/mpvue#784]
# [问题简单描述]
pages 页面去引用pages里面的页面，这时候会把另外一个页面的css抽成一个vendor.wxss,
但是页面main.wxss 引用还是@import "../../static/css/pages/xxx/main.wxss";

**Comment by aOrz** [comment]
把项目 demo 发我一下，是不是升级了 mpvue-loader 没有改 webpack 的配置？

**Comment by luanjinxin** [comment]
我也遇到这个问题了，你是怎么解决的，跪求。。。

**Comment by fuguxu** [comment]
遇到同样的问题，请问解决了吗
