### ISSUE TITLE
新安装的环境生成新项目中img图片路径生成了绝对路径

### ISSUE THREAD

**Issue by lzq921** [Meituan-Dianping/mpvue#785]
# [问题简单描述]
win7新安装的环境生成新项目中img图片路径生成了绝对路径
**问题复现步骤:**

1. [第一步]
在页面中有img引用static/imgs/中图片
2. [第二步]
用 调试编译打包
3. [其他步骤...]

**期望的表现:**
页面img 引用了图片绝对路径
[在这里描述期望的表现]
 `<image src="/static/imgs/home2.png" class="_img data-v-2b3f2740"></image>` 
**观察到的表现:**
  `<image src="F:\IT\weixin\mpvue\porj\demo1\dist\static\imgs\home2.png" class="_img data-v-2b3f2740"></image>`
[在这里描述观察到的表现]

**屏幕截图和动态 GIF 图**

![复现步骤的屏幕截图和动态 GIF 图](图片的 url)

**Comment by lzq921** [comment]
用#780 中有人提到的，改mpvue-loader版本号成1.0.14 也没效果呢

**Comment by aOrz** [comment]
试下：+ mpvue-loader@1.1.2-rc.1

**Comment by lzq921** [comment]
改成` "mpvue-loader": "^1.1.2-rc.1",`了，但生成的路径还是不对。vue原代码`<img src="../../../static/imgs/home2.png">` dev打包后生成`<image src="../../../static/imgs/home2.png" class="_img data-v-2b3f2740"></image>`。并没有生成希望的`<image src="/static/imgs/home2.png" class="_img data-v-2b3f2740"></image>`
现在这方式在开发者工具上能显示图片，到真机上是不能显示的。

**Comment by aOrz** [comment]
@lzq921 升级下 mpvue-loader@1.1.2-rc.2 。
为了优化 build 后的目录结构，去掉了源代码中的 src 目录，导致了路径解析除了问题。同时推荐把图片放到 src 目录下，就近依赖，方便以后分包。

**Comment by lzq921** [comment]
@aOrz 好的，只能先把图片资源放到 src 目录下了

**Comment by aOrz** [comment]
@lzq921 mpvue-loader@1.1.2-rc.2  已经支持放在根目录下

**Comment by lzq921** [comment]
@aOrz 改成 mpvue-loader@1.1.2-rc.2 已解决img标签的图片路径引用问题。但又发现某张图片如果没在页面img标签引用，只在main.json中作为tabBar的iconPath引用 `"iconPath":"static/imgs/news1.png"`。 调式打包时在dist中并没发现图片生成。

**Comment by aOrz** [comment]
@lzq921  *.json 中的文件，推荐使用 webpack-copy-plugin 拷贝过去
