### ISSUE TITLE
img路径问题

### ISSUE THREAD

**Issue by jpdan** [Meituan-Dianping/mpvue#786]
`<img src="@/assets/img/home/a.png" />`
or
`<img src="../../assets/img/home/a.png" />`
都不行，mpvue-loader升级前还能用相对路径，升级两个都玩完

**Comment by aOrz** [comment]
试下：+ mpvue-loader@1.1.2-rc.1

**Comment by jpdan** [comment]
tabBar中`"iconPath": "static/img/icon-home.png"`还是不行，不报错，图标不显示

**Comment by jpdan** [comment]
static目录打包没有copy？

**Comment by jpdan** [comment]
`<img src="@/assets/img/home/a.png" />`
or
`<img src="~assets/img/home/a.png" />`
啥时候能支持，显示只能用相对路径，很麻烦

**Comment by aOrz** [comment]
> tabBar中"iconPath": "static/img/icon-home.png"还是不行，报错找不到，图标不显示，../static不报错，图标也不显示

看下 #787 ，app.json 文件中的路径是没有解析的，需要配置 copy-webpack-plugin copy 到 dist 文件夹下。
相对路径后续会支持
