### ISSUE TITLE
以前的项目生成的dist文件没有app.json 在最新的开发者工具打不开

### ISSUE THREAD

**Issue by LiAo0821** [Meituan-Dianping/mpvue#787]
# [问题简单描述]

**问题复现步骤:**

1. [第一步]
2. [第二步]
3. [其他步骤...]

**期望的表现:**

[在这里描述期望的表现]

**观察到的表现:**

[在这里描述观察到的表现]

**屏幕截图和动态 GIF 图**

![复现步骤的屏幕截图和动态 GIF 图](图片的 url)

**Comment by aOrz** [comment]
之前的 main.js 中 export 出来的 app.json 改成了使用 copy-webpack-plugin 直接复制目录下的 main.json 文件

**Comment by aOrz** [comment]
```js
new CopyWebpackPlugin([
      {
        from: path.resolve(__dirname, '../static'),
        to: path.resolve(__dirname, '../dist/static'),
        ignore: ['.*']
      }
    ])
```

**Comment by LiAo0821** [comment]
照着改了 图片依然没有显示
