### ISSUE TITLE
Vue.extend问题

### ISSUE THREAD

**Issue by ilovemyboys** [Meituan-Dianping/mpvue#79]
使用Vue.extend后导致不能生成wxml文件。
import Vue from 'vue';
import App from './App';

let Vue1 = Vue.extend({});
const app = new Vue1(App);
app.$mount()

测试前请删除dist目录后再编译。

**Comment by ilovemyboys** [comment]
进一步测试，不是Vue.extend的问题。关闭！

**Comment by anchengjian** [comment]
和 #83 是同一个原因
