### ISSUE TITLE
新环境下 page的json 无效

### ISSUE THREAD

**Issue by fengzhiqiang012** [Meituan-Dianping/mpvue#791]
page页面的 json配置不生效了 还是换方法配置了

**Comment by aOrz** [comment]
之前的 main.js 中 export 出来的 app.json 改成了使用 copy-webpack-plugin 直接复制目录下的 main.json 文件，参考新版 QuickStart: https://github.com/mpvue/mpvue-quickstart/blob/master/template/build/webpack.base.conf.js#L23
