### ISSUE TITLE
components目录下img路径问题

### ISSUE THREAD

**Issue by jpdan** [Meituan-Dianping/mpvue#793]
components目录下有个通用组件TopBar
`<img class="cs-img" src="../assets/img/customservice.png"/>`
有时报错：`Failed to load local image resource /pages/assets/img/home/icon-star-tag.png 
 the server responded with a status of 404 (HTTP/1.1 404 Not Found) `
有时不报错，但是不显示图标

`<img class="cs-img" src="/assets/img/customservice.png"/>`
用绝对路径就可以了。

为啥在pages下可以用相对路径，components不行？#785
@aOrz

**Comment by LiAo0821** [comment]
我也遇到问题 components写的组件里面引入的图片 打包生成

![image](https://user-images.githubusercontent.com/25658190/43067581-4f9a8f14-8e9a-11e8-9f65-c5e1fad8a4d3.png)

到了wx开发工具上面 就变成了
![image](https://user-images.githubusercontent.com/25658190/43067619-6d9bea8a-8e9a-11e8-8828-f1ac98198968.png)

**Comment by aOrz** [comment]
@LiAo0821  mpvue-loader 版本是多少，是 1.1.2-rc.2 ？

**Comment by aOrz** [comment]
@jpdan 小程序的 template 好像不能引用相对路径，+ mpvue-loader@1.1.2-rc.3 改成绝对路径了。。

**Comment by LiAo0821** [comment]
1.1.2-rc.2

**Comment by aOrz** [comment]
@LiAo0821 能提供个 demo 吗

**Comment by LiAo0821** [comment]
升级到 mpvue-loader@1.1.2-rc.3 绝对路径引入没有问题了

**Comment by LiAo0821** [comment]
![image](https://user-images.githubusercontent.com/25658190/43110659-d3d43e9e-8f1f-11e8-8aba-cfb85181fa3e.png)
更新了以后 wxParse 出问题了 

打包后生成的
![image](https://user-images.githubusercontent.com/25658190/43110679-fbd7c442-8f1f-11e8-8b81-ad28b04f16b0.png)

**Comment by jpdan** [comment]
@aOrz 升级到rc.3，在components下可以使用相对路径了
![image](https://user-images.githubusercontent.com/3361732/43112676-c5e785ca-8f29-11e8-9687-dc93fa95ba3a.png)
？？？？？

**Comment by aOrz** [comment]
@jpdan  mpvue-loader@1.1.2-rc.3 将生成的 wxml 里面的路径改成了绝对路径
