### ISSUE TITLE
mpvue-loader@1.1.2-rc.4 升级指南

### ISSUE THREAD

**Issue by aOrz** [Meituan-Dianping/mpvue#795]
> 本次升级意在调整生成文件目录结构，对依赖的文件由原来的写死绝对路径该改为相对路径。目前 mpvue-loader@1.1.x 还不稳定，暂不建议线上使用
## 不兼容的地方
1. mpvue-loader@1.1.2-rc.4 依赖 webpack-mpvue-asset-plugin@0.1.0 做依赖资源引用
2. 之前写在 main.js 中的 config 信息，需要在 main.js 同级目录下新建 main.json 文件，使用 webapck-copy-plugin copy 到 build 目录下

## 那些坑

1.  app.json 中引用的图片不会自动 copy 到 dist 目录下
  json 配置文件是由 webapck-copy-plugin copy 过去的，不会处理依赖，可以将图片放到根目录下 static 目录下，使用 webapck-copy-plugin copy 过去

详细升级指南：http://mpvue.com/change-log/
大家有啥疑问可以在下面讨论

**Comment by liumin1128** [comment]
webapck-copy-plugin copy 能自动进行吗？若不能可以给个案例吗

**Comment by aOrz** [comment]
@liumin1128 最新的 mpvue-quickstart 可以自动进行 copy，可以参考下

**Comment by F-loat** [comment]
可以整理下自行修改 webpack 配置的步骤

**Comment by LiAo0821** [comment]
![image](https://user-images.githubusercontent.com/25658190/43121359-1066416a-8f50-11e8-9143-69b38b6391cc.png)
目前这三个包版本 依然报错Template not found

**Comment by aOrz** [comment]
@LiAo0821 升级下 + mpvue-loader@1.1.2-rc.4，解决了生成的目录中包含 node_modules 的问题

**Comment by LiAo0821** [comment]
@aOrz 问题解决 感谢

**Comment by hizhm** [comment]
那每个页面单独的配置,也是需要新建一个main.ison吗?写在main.js里面的没有生效

**Comment by aOrz** [comment]
@hizhm quickstart 已经单独拆分出 main.json 了，https://github.com/mpvue/mpvue-quickstart/tree/master/template/src

**Comment by hizhm** [comment]
组件里面的main.js也单独拆分出一个main.json吗?案例里面没有拆分..全局的main.json可以生效..

**Comment by hizhm** [comment]
@aOrz 问题解决,多谢

**Comment by yanping-jessie** [comment]
请问，src/main.json可以热更新，但是pages/xx/main.json不能，，怎么破？

**Comment by yanping-jessie** [comment]
不行，我用mpvue-quickstart新建的项目也不行

**Comment by PittYong** [comment]
每个页面main.js单独配置的config不生效

**Comment by aOrz** [comment]
@PittYong 看下升级指南：http://mpvue.com/change-log/

**Comment by PittYong** [comment]
@aOrz 感谢您的回复，问题已经解决

**Comment by Nick930826** [comment]
按照升级指南升级了  "mpvue-loader": "^1.1.2-rc.4" 和  "webpack-mpvue-asset-plugin": "^0.1.1"  这两个包，且在pages下加了main.json  打包出来还是没有相应显示title

**Comment by fangdiao** [comment]
请问现在使用小程序原生组件可以使用本地图片资源了吗
