### ISSUE TITLE
mpvue生成的小程序dist文件夹里没有app.json等配置文件?

### ISSUE THREAD

**Issue by syyzz3** [Meituan-Dianping/mpvue#797]
我把mpvue项目上传到git上，另外clone了一份，npm run dev,只生成了这两个文件夹其他的配置文件都没有，也没有报错不知道是什么原因？

![qq 20180723181158](https://user-images.githubusercontent.com/11385973/43112330-2b2ab904-8f28-11e8-931d-1629e42a4ead.png)

**Comment by xzylzz** [comment]
依赖包版本的原因吧 有些更新了 但是你的模板还是旧的

**Comment by aOrz** [comment]
mpvue-loader@1.1.2-rc4，升级指南：http://mpvue.com/change-log/

**Comment by githubwangqiang** [comment]
在新安装的包里 
![image](https://user-images.githubusercontent.com/25969944/43176669-5107126a-8ff7-11e8-8596-f62f632d7573.png)

![image](https://user-images.githubusercontent.com/25969944/43176609-05b641fa-8ff7-11e8-9501-17f77726bac1.png)

这里的emitted不兼容？
有处理的吗？
目前把这个删掉可以正常跑了，希望尽快优化！
