### ISSUE TITLE
mpvue怎样实现的图片预览，就是那种点击放大可以左右滑动的效果

### ISSUE THREAD

**Issue by lisun0459** [Meituan-Dianping/mpvue#798]
我使用了vue-picture-preview，但是终端会有报错，报错内容如下：
(Emitted value instead of an instance of Error)   - 不支持此属性-> v-preview="img"

还有一个担忧是我需要H5和小程序都能使用，如果不能至少H5能使用，目前还没有编译为H5，请求大神赐教。

**Comment by Lison-CN** [comment]
你好，怎么实现请问

**Comment by KuangPF** [comment]
[wx.previewImage(Object object)](
https://developers.weixin.qq.com/miniprogram/dev/api/media/image/wx.previewImage.html)

**Comment by Lison-CN** [comment]
> [wx.previewImage(Object object)](https://developers.weixin.qq.com/miniprogram/dev/api/media/image/wx.previewImage.html)

**Comment by Lison-CN** [comment]
你好我的意思是在mpvue中使用，小程序原生很简单，但是mpvue我不知道怎么传src的路径

**Comment by KuangPF** [comment]
[不知这个有帮助没得?](https://kuangpf.com/mpvue-weui/#/uploader)

**Comment by Lison-CN** [comment]
请问可以像小程序这样写吗
wx.previewImage({
  current: '', // 当前显示图片的http链接
  urls: [] // 需要预览的图片http链接列表
})

但是不知道data-src，，mpvue的写法是怎么样子的

**Comment by KuangPF** [comment]
和 vue 中写法一样 
``` html
<div data-url='https://baidu.com' @click="getUrl"></div>
```

``` js
getUrl(e) {
    console.log(e.currentTarget.dataset.url); // url
},
```

**Comment by Lison-CN** [comment]
谢谢啦，已经解决了
