### ISSUE TITLE
最新版本mpvue - DevTools failed to parse SourceMap

### ISSUE THREAD

**Issue by haifn** [Meituan-Dianping/mpvue#799]
![image](https://user-images.githubusercontent.com/18524223/43113243-2a3cb804-8f2c-11e8-82fe-101591841622.png)
请问要怎么解决这个问题呢？也有其他用了新环境的小伙伴也遇到和我一样的情况，所以应该不是个例。

**Comment by anchengjian** [comment]
什么叫 `新环境下mpvue` ????? 我感觉要开启强制 issue 模版了，不然这答复和复现效率骤降

**Comment by xream** [comment]
@anchengjian 我也遇到这个问题了 我猜 @haifn 跟我一样是刚升级了吧 https://github.com/Meituan-Dianping/mpvue/issues/795

**Comment by haifn** [comment]
@anchengjian  就是用最新的mpvue-quickstart模板来构建的项目。

**Comment by aOrz** [comment]
升级下 + webpack-mpvue-asset-plugin@0.1.1

**Comment by jytx** [comment]
我也遇到了类似的情况,用最新版的模板创建项目,但是发现无法打断点,楼主这个问题解决了吗

**Comment by daolanfler** [comment]
+ 1  升级了插件还是这样
> "name": "webpack-mpvue-asset-plugin",
>   "version": "0.1.2",

**Comment by palytoxin** [comment]
一样的问题

> 
> "devDependencies": {
>     "babel-core": "^6.22.1",
>     "babel-eslint": "^8.2.3",
>     "babel-loader": "^7.1.1",
>     "babel-plugin-transform-runtime": "^6.22.0",
>     "babel-preset-env": "^1.3.2",
>     "babel-preset-stage-2": "^6.22.0",
>     "babel-register": "^6.22.0",
>     "chalk": "^2.4.0",
>     "connect-history-api-fallback": "^1.3.0",
>     "copy-webpack-plugin": "^4.6.0",
>     "css-loader": "^0.28.11",
>     "cssnano": "^3.10.0",
>     "eslint": "^4.19.1",
>     "eslint-config-airbnb-base": "^12.1.0",
>     "eslint-friendly-formatter": "^4.0.1",
>     "eslint-import-resolver-webpack": "^0.9.0",
>     "eslint-loader": "^2.1.1",
>     "eslint-plugin-html": "^4.0.6",
>     "eslint-plugin-import": "^2.11.0",
>     "eslint-plugin-node": "^6.0.1",
>     "eventsource-polyfill": "^0.9.6",
>     "express": "^4.16.4",
>     "extract-text-webpack-plugin": "^3.0.2",
>     "file-loader": "^1.1.11",
>     "friendly-errors-webpack-plugin": "^1.7.0",
>     "glob": "^7.1.2",
>     "html-webpack-plugin": "^3.2.0",
>     "http-proxy-middleware": "^0.18.0",
>     "mpvue-loader": "^1.1.2",
>     "mpvue-template-compiler": "^1.0.18",
>     "mpvue-webpack-target": "^1.0.3",
>     "node-sass": "^4.11.0",
>     "optimize-css-assets-webpack-plugin": "^3.2.0",
>     "ora": "^2.0.0",
>     "portfinder": "^1.0.20",
>     "postcss-loader": "^2.1.4",
>     "postcss-mpvue-wxss": "^1.0.2",
>     "prettier": "~1.12.1",
>     "px2rpx-loader": "^0.1.10",
>     "relative": "^3.0.2",
>     "rimraf": "^2.6.0",
>     "sass-loader": "^7.1.0",
>     "semver": "^5.6.0",
>     "shelljs": "^0.8.3",
>     "uglifyjs-webpack-plugin": "^1.2.5",
>     "url-loader": "^1.1.2",
>     "vue-style-loader": "^4.1.0",
>     "webpack": "^3.12.0",
>     "webpack-bundle-analyzer": "^2.2.1",
>     "webpack-dev-middleware-hard-disk": "^1.12.0",
>     "webpack-merge": "^4.1.5",
>     "webpack-mpvue-asset-plugin": "^0.1.2"
>   },

**Comment by daolanfler** [comment]
> > +1 升级了插件还是这样
> > > "name": "webpack-mpvue-asset-plugin",
> > > "version": "0.1.2",
> 
> 我退回到 0.1.1 修复了问题。webpack-mpvue-asset-plugin@0.1.1
> 
> 0.1.2打包出来的app.js.map 格式不对

谢谢 解决了我的问题。
吐槽一下：mpvue 升级也太随意了吧。
