### ISSUE TITLE
mpvue是否能使用echarts？

### ISSUE THREAD

**Issue by LGY-color** [Meituan-Dianping/mpvue#8]
在mpvue中能否使用echarts，百度有一个echarts小程序版的https://github.com/ecomfe/echarts-for-weixin 原生写小程序用echarts这个版本没问题，能否在mpvue中也使用呢

**Comment by KarnaughK** [comment]
同问，我这边是需要高德地图和环信，这些官网只提供了小程序版本的第三方库，我们要如何引入到mpvue中？

**Comment by hucq** [comment]
查阅了 echart 小程序版本实现，其思路是一个自定义的小程序组件，通过 canvas 绘制，上层页面中以组件的方式引入即可。目前 mpvue 尚未对小程序 Component 做支持，但方案已经调研过了，实现上没有问题。后续支出了会同步给大家。

如果有在小程序中使用的场景，现阶段可以采用部分页面原生、部分页面mpvue 结合的方式实现。这么做，你可能需要参考：[mpvue-simple](http://mpvue.com/mpvue/simple/) 这种页面级打包的构建方式。

**Comment by aOrz** [comment]
@KarnaughK 纯 js 的库的话可以直接引用

**Comment by hucq** [comment]
经过我们实际测试，echat 是能正常运行的。详情请参见 [mpvue 使用之 echart](https://github.com/mpvue/examples)

**注意：** 小程序开发者工具请使用最新版本，否则不能正常运行。

**Comment by he5050** [comment]
@KarnaughK  想问一下 你们直接引入环信的嘛
