### ISSUE TITLE
能与mint-ui等其他第三方移动端组件使用吗？

### ISSUE THREAD

**Issue by chenxi2015** [Meituan-Dianping/mpvue#80]

**Comment by aOrz** [comment]
原理上是可以的，但是要去掉 Dom 和 Bom 相关的 API 操作，还要去掉 mpvue 不支持的一些 vue 特性，小程序不支持的 css 选择器等，去掉这些就可以使用了，欢迎大家贡献 mpvue 的 UI 组件库。
已经有开发者做了 weui 的 mpvue 版本，可以试下https://github.com/KuangPF/mpvue-weui
