### ISSUE TITLE
按照最新分包之后  Template "xxx" not found.

### ISSUE THREAD

**Issue by a897830933** [Meituan-Dianping/mpvue#800]
![Uploading image.png…]()

**Comment by aOrz** [comment]
mpvue-loader 版本是多少？最新是 mpvue-loader@1.1.2-rc.4，升级试下

**Comment by a897830933** [comment]
![image](https://user-images.githubusercontent.com/20568594/43123543-184a8088-8f57-11e8-8528-270d40c5ae4d.png)

**Comment by aOrz** [comment]
@a897830933 能给个 demo 吗

**Comment by a897830933** [comment]
我把组件抽出来不从npm里引用的话是不报这个错误的，但是 数据绑定不上了

**Comment by EngMJ** [comment]
想了一下，应该是小程序分包加载的限制问题。 前几天升级后也遇到，按照小程序官方说明，来做目录引用就没这种问题了。
![target](https://user-images.githubusercontent.com/32951696/44395859-c3cfe480-a56d-11e8-97ad-b34094701921.png)

@aOrz 建议在文档中适当进行说明，不想爬坑靠蒙。
