### ISSUE TITLE
page的config指定不生效

### ISSUE THREAD

**Issue by zengshide123** [Meituan-Dianping/mpvue#804]
# [问题简单描述]
    项目模版会在最外层生成一个json文件作为全局config，
    在指定page的config，在当前page的main文件中，使用export config时，
    并没有产生作用。
**问题复现步骤:**

1. [第一步]
全局config
```
{
  "pages": [
    "pages/index/main",
    "pages/counter/main",
    "pages/logs/main"
  ],
  "window": {
    "backgroundTextStyle": "light",
    "navigationBarBackgroundColor": "#fff",
    "navigationBarTitleText": "首页",
    "navigationBarTextStyle": "black"
  }
}
```

2. [第二步]
、page（counter）的config
```
export default {
  config: {
    navigationBarTitleText: '计数页'
  }
}

```
3. [其他步骤...]

**期望的表现:**

顶部title修改为计数页

**观察到的表现:**

页面title没有发生改变

**屏幕截图和动态 GIF 图**

![image](https://user-images.githubusercontent.com/31063702/43131073-b350a37e-8f6a-11e8-9a48-322382cbd619.png)
![image](https://user-images.githubusercontent.com/31063702/43131096-c7de3220-8f6a-11e8-8f9c-81ab873d6142.png)

![复现步骤的屏幕截图和动态 GIF 图](图片的 url)

**Comment by aOrz** [comment]
mpvue-loader 版本是多少？

**Comment by Ben199011** [comment]
我的也是 @aOrz 拉的是官方模板，最新的

**Comment by aOrz** [comment]
参考下 #795 ，将 *.json  的生成逻辑改成使用 webpack-copy-plugin copy 过去了

**Comment by zengshide123** [comment]
@aOrz  谢谢，很有用

1、升级mpvue-loader版本
`
"mpvue-loader": "^1.1.2-rc.4",
`
2、在需要配置的 page下新建main.json
直接写入配置对象
```
{
    "navigationBarTitleText": "查看启动日志",
    "enablePullDownRefresh": true,
    "backgroundColor":"#eee",
    "navigationBarBackgroundColor":"#f00",
    "navigationBarTextStyle":"white"
}
```

**Comment by MontageD** [comment]
@zengshide123 这位大大的方法是可以用的，只是需要加上一句，要重新启动才能产生效果，如果只是配置到json 文件，它是不会自己热刷新的
