### ISSUE TITLE
scroll-view的scroll-into-view属性没法设置

### ISSUE THREAD

**Issue by KiraSu** [Meituan-Dianping/mpvue#805]
npm run dev之后报错如下：
Interpolation inside attributes has been removed. Use v-bind or the colon shorthand instead. For example, instead of `<`div id="{{ val }}"`>`, use `<`div :id="val"`>`.
提示说用v-bind，但不知道怎么在scrollview里面用，有知道怎么解决的大侠么？谢谢了

**Comment by KiraSu** [comment]
solved

**Comment by douyongduo** [comment]
怎么解决的？？？？
