### ISSUE TITLE
删除依赖node_modules文件夹，重新npm i 后运行npm run dev ，dist文件夹没有编译生成app.json

### ISSUE THREAD

**Issue by lovedaan** [Meituan-Dianping/mpvue#807]
# [问题简单描述]
上周生成的项目模板开始做项目，今天换台电脑拉项目代码下来，安装完依赖后运行，dist文件夹没有编译生成app.json，折腾一天了。
初步怀疑是包依赖的包有更新，不兼容，package.json里面记录的包是没有变化的，
**问题复现步骤:**

1. [第一步]
2. [第二步]
3. [其他步骤...]

**期望的表现:**

[在这里描述期望的表现]

**观察到的表现:**

[在这里描述观察到的表现]

**屏幕截图和动态 GIF 图**

![复现步骤的屏幕截图和动态 GIF 图](图片的 url)

**Comment by F-loat** [comment]
mpvue-loader 使用 1.0.x 的版本

**Comment by lovedaan** [comment]
就是这个版本"mpvue-loader": "^1.0.13"的，还有装更低的版本？

**Comment by F-loat** [comment]
这个直接安装是 1.x.x 的最新版

**Comment by lovedaan** [comment]
安装的是1.0.10版本，Module build failed: TypeError: unknown: Cannot read property 'type' of undefined，就报这个错

**Comment by lovedaan** [comment]
解决了，先把package.json里面devDependencies里面记录的mpvue-loader删掉，之后npm i 安装完其他依赖后，再单独安装 npm i -D mpvue-loader@1.0.15，不知道为什么明明package.json里面记录的mpvue-loader的版本已经是1.0.15的，但是统一 npm i 之后安装的却是1.1.1的版本
