### ISSUE TITLE
可否配合vue-resource使用？

### ISSUE THREAD

**Issue by bradenhan** [Meituan-Dianping/mpvue#81]
# [问题简单描述]

**问题复现步骤:**

1. import VueResource from 'vue-resource'
2. Vue.use(VueResource)
3. 调用
  mounted () {
    this.$http.get('XXX',{
        params:{ 
          name:'xxx'
        }
      }).then(response => {
          console.log('请求成功')
      },
      response => {
          console.log('请求失败')
      });
  }

**一直报错**

This dependency was not found:

`* fs in ./~/got/index.js, ./~/electron/index.js`

To install it, you can run: npm install --save fs

安装了fs模块还是报错

**Comment by aOrz** [comment]
不可以，vue-resource 使用了XMLHttpRequest 等小程序不支持的特性，可以自己封装下 wx.request
