### ISSUE TITLE
mpvue-quickstart 无法运行，未找到入口app.json文件

### ISSUE THREAD

**Issue by icewind7030** [Meituan-Dianping/mpvue#812]
# mpvue-quickstart 无法运行，未找到入口app.json文件

**问题复现步骤:**

1. 按照[官方QuickStart](http://mpvue.com/mpvue/quickstart/)进行部署运行

**期望的表现:**

小程序按照官方示例呈现和运行

**观察到的表现:**

小程序console报错，`未找到入口 app.json 文件，或者文件读取失败，请检查后重新编译。`

**屏幕截图和动态 GIF 图**

![报错内容](https://easyread.nosdn.127.net/web/trunk/1532487833541/wechatimg461.png)

**Comment by yeyifen** [comment]
遇到相同的问题，求解~

**Comment by aOrz** [comment]
锁定下 "mpvue-loader": "1.0.13" 和 "webpack-mpvue-asset-plugin": "0.0.2" 版本

**Comment by molvqingtai** [comment]
我也遇到了，static目录也不能正确打包

**Comment by molvqingtai** [comment]
我重新构建了一遍，然后把main.json改回mian.js，居然就好了

**Comment by vampireXia** [comment]
我也遇到了这个问题 捣鼓了半天解决了 不知道你是不是我这种情况
执行了run dev 生成了dist  默认是dist下面就是一些小程序的文件了
然而我run dev 以后生成的目录是 dist/wx/小程序文件

所以只要打开根目录的 **project.config.json**文件 
把其中的 **"miniprogramRoot": "./dist/"** 修改为 **"miniprogramRoot": "./dist/wx/"**
就好了

**Comment by 35860368** [comment]
把项目下面的project.config.json文件里
miniprogramRoot:"dist" 改成 dist/wx/
