### ISSUE TITLE
mpvue 如何判断当前运行环境是生产环境还是测试环境

### ISSUE THREAD

**Issue by HelloVass** [Meituan-Dianping/mpvue#814]
# [问题简单描述]
mpvue 有没有类似 devTools 这样的变量来判断小程序当前是开发环境还是生产环境，便于动态切换服务器地址，不需要手动更改。

**Comment by githubwangqiang** [comment]
switch (process.env.NODE_ENV) {
  case 'development':
    baseUrl = global.baseUrl.development
    break
  case 'production':
    baseUrl = global.baseUrl.production
    break
}
