### ISSUE TITLE
更新mpvue-loader为1.1.2-rc.4之后热更新的问题

### ISSUE THREAD

**Issue by yanping-jessie** [Meituan-Dianping/mpvue#815]
不知道你们有没有这个问题，升级了mpvue-loader为1.1.2-rc.4和更新webpack的配置之后，修改代码保存打包之后的代码没有更新，需要重新npm run dev才有效。我试出来是pages下面增加了main.json配置的页面就不会更新代码，没有main.json的就可以保存立即更新。实在是搞不懂。

**问题复现步骤:**

1. 使用mpvue-quickstart新建一个项目
2.启动项目，正常运行
3.修改counter里面的vue文件，保存，页面立即更新
4 给counter文件增加一个main.json修改title（这里新增文件要重新启动项目）
5. 启动项目，正常运行
6.修改counter里面的vue文件，保存，页面刷新但是没有任何变化，即使页面有错误也不会提示

**Comment by aOrz** [comment]
@Elity  感谢反馈，已经复现

**Comment by zjwshisb** [comment]
经过我这测试，更改src下面的main.js，随意增加几个aaa保存使之编译出错然后再改回去保存就能触发热更新

**Comment by Elity** [comment]
@aOrz 无法稳定复现是？ 有时可以有时不可以么？
这个问题出现的前提是目录内有main.json文件

**Comment by netbuffer** [comment]
+1,同样遇到了

**Comment by aOrz** [comment]
@Elity @netbuffer  是 mac 还是 win ？微信开发者工具版本是多少？文件改动之后 dist 目录下的文件有没有更新？

**Comment by yanping-jessie** [comment]
win7系统
微信开发者工具版本：v1.02.1807200
文件改动后dist里面的index.vue.wxml没有任何变化
即使把文件改错编译也是通过的

**Comment by aOrz** [comment]
按照下图改下 build/webpack.base.conf.js 试下，应该是 win 下与 webpack-copy-plugin 的兼容性问题
![image](https://user-images.githubusercontent.com/6347990/43254633-6a8dfd4e-90fa-11e8-804a-f1128703ae54.png)

**Comment by yanping-jessie** [comment]
@aOrz 已经可以了，我这边测试过了，已经可以立即更新了，并且pages下面的main.js也可以立即更新，完美解决，谢谢！
