### ISSUE TITLE
wx.showToast() 设置image图片无法显示

### ISSUE THREAD

**Issue by xxxsimons** [Meituan-Dianping/mpvue#821]
# [问题简单描述]
调用wx.showToast()时使用image属性自定义图片，无法显示
**问题复现步骤:**
无论用不用require都不行，但是控制台打印出来的是能找到图片的
```
console.log(require("@/../static/icons/error.png"));
wx.showToast({
                title: "登陆超时",
                image: require("@/../static/icons/close.png"),
                duration: 1000
              });
```

[![PtbDaj.jpg](https://s1.ax1x.com/2018/07/26/PtbDaj.jpg)](https://imgchr.com/i/PtbDaj)
[![PtbBZQ.jpg](https://s1.ax1x.com/2018/07/26/PtbBZQ.jpg)](https://imgchr.com/i/PtbBZQ)

**Comment by zhangmin2020** [comment]
把图片放在static文件夹中  然后
wx.showToast({
              title: '无网络信号',
              image: "/static/no_wifi.png"
            })

**Comment by xxxsimons** [comment]
老哥可以了诶，只能用绝对路径嘛？为啥我那个方法不行

**Comment by aOrz** [comment]
试下 wx.showToast img 支不支持 base64

**Comment by xxxsimons** [comment]
我issue的那个控制台图片就是用require引入的 不行 @aOrz

**Comment by chenjing1552** [comment]
wx.showToast({
      title: '请求失败',
      image: '/static/img/error.png',
      duration: 10000
    })
 我这样引入了都没用效果, 是跟文件摆放有关系吗
