### ISSUE TITLE
vue中的vuex实例运行问题

### ISSUE THREAD

**Issue by XYjourney** [Meituan-Dianping/mpvue#824]
调试基础库2.2.1，一开始运行是没问题的，之后报错，目前懵逼状态
在vue原型中引入fly和vuex实例不生效，报下面错误
请大神看一下

![ec5b3f969a42cd824c07404ad3cb2b3](https://user-images.githubusercontent.com/18476675/43298549-0d567cde-9189-11e8-94f4-03e2d7cd40ec.png)

![402ca21a18d9fe514db43438af08e22](https://user-images.githubusercontent.com/18476675/43298530-fcf4c788-9188-11e8-9e8a-159d4efeb839.png)

![b2be7524f5d201e117c1863f956fe3d](https://user-images.githubusercontent.com/18476675/43298710-b7896720-9189-11e8-9a80-7eacf2a688c9.png)

**Comment by tiger8888** [comment]
我也遇到同样的问题,一升级微信开发工具,就不行了,原来可以的

**Comment by xianengqi** [comment]
同学 问题解决了没，我也遇到相同的问题了

**Comment by XYjourney** [comment]
解决了 通过这种方式将fly实例引出export const flyio = fly， 然后import

**Comment by XYjourney** [comment]
|

解决了 通过这种方式将fly实例引出export const flyio = fly， 然后import

|


发自网易邮箱大师
在2018年9月4日 19:29，XiaNengQi<notifications@github.com> 写道：

同学 问题解决了没，我也遇到相同的问题了
