### ISSUE TITLE
没有生成app.json文件

### ISSUE THREAD

**Issue by jpdan** [Meituan-Dianping/mpvue#825]
[https://github.com/mpvue/mpvue-quickstart/compare/develop](url)
按照这个改了配置后，发现src目录下main.json不会编译成app.json，导致开发者工具报错，
不该webpack copy plugin配置情况下，直接改main.json为app.json即可
@aOrz

**Comment by wuzhefang** [comment]
按照 #672 的方法升级了 mpvue-loader 之后就无法生成 app.json 等文件了。 @aOrz 
网上查到了一篇文章 http://blog.sina.com.cn/s/blog_60cf05130102xz1v.html

**Comment by wuzhefang** [comment]
找到问题的答案了，辛苦  @aOrz 
@jpdan 看一下 #795

**Comment by aOrz** [comment]
已更新到 quickSatrt，感谢反馈
