### ISSUE TITLE
mpvue 是否支持 微信小程序数据分析

### ISSUE THREAD

**Issue by XiaoWangXueBianCheng** [Meituan-Dianping/mpvue#828]
# [问题简单描述]
使用
[小程序数据分析](https://developers.weixin.qq.com/miniprogram/analysis/custom/#%E4%BA%8B%E4%BB%B6%E7%9A%84%E7%BC%96%E8%BE%91%E4%B8%8E%E5%8F%91%E5%B8%83)
![image](https://user-images.githubusercontent.com/13784844/43322815-5f73e188-91e2-11e8-8cb8-e92cfffd8017.png)

**问题复现步骤:**

1. [第一步]
小程序 的page 中计算属性 list:[],,定义了点击事件，点击第一个卡片触发了事件，但提示取不到 list[0]的值

**期望的表现:**
如何能取到值

**Comment by F-loat** [comment]
这个应该不支持的，可以主动调用相关接口
