### ISSUE TITLE
自定义组件的不具名slot失效，报警告，具名slot则没有问题

### ISSUE THREAD

**Issue by YTU94** [Meituan-Dianping/mpvue#832]
# [问题简单描述]
自定义组件使用slot,如果带有name属性没有问题，可是要是不带name就会报警告，让后插槽内容不现实
**问题复现步骤:**

1. 自定义组件
<button
    @click="handleClick"
    :class="['tSign-button--' + type, 'tSign-button--' + size, {
      'round': round,
      'disabled': disabled
    }]"
    :style="{'background-color': color, 'color': color ? '#fff' : null, 'border': color ? '0' : 'inherit'}"
    :disabled="disabled || loading">
      <span class="btn-content" v-if="!loading">
        <slot></slot>
      </span>
      <span class="btn-content" v-else>
        <img class="btn-loading-icon" src="./images/loading.png" alt="loading">
        <span class="btn-loading-text">加载中</span>
      </span>
    </button>
2. 调用组件

**期望的表现:**

渲染出正常的button按钮

**观察到的表现:**

button是渲染出来了，可是button中的slot渲染不出来，slot对应的lable标签中没有内同

如果是具名slot就没有这个问题
控制台包warnning
![image](https://user-images.githubusercontent.com/19224071/43375333-f1492ad6-93e6-11e8-873c-2005b1554183.png)

**Comment by aOrz** [comment]
mpvue-loader 版本？

**Comment by YTU94** [comment]
^1.1.2-rc.4

**Comment by aOrz** [comment]
1.1.2-rc.5 试下

**Comment by YTU94** [comment]
哦

**Comment by YTU94** [comment]
哦

**Comment by YTU94** [comment]
在家测了下 貌似编译后app.js app.json都编译不出来，，，

**Comment by YTU94** [comment]
是我init的版本低了，，，（我的）

**Comment by YTU94** [comment]
可以了

**Comment by zhowiny** [comment]
怎么解决的
