### ISSUE TITLE
新建mpvue项目一直在downloading template处转

### ISSUE THREAD

**Issue by janforp** [Meituan-Dianping/mpvue#833]
# [问题简单描述]
vue init mpvue/mpvue-quickstart my-project
之后一直显示  downloading template
![tim 20180730110620](https://user-images.githubusercontent.com/19358272/43375596-aa092b2e-93e8-11e8-8953-3a1c053e97e7.png)

**Comment by anchengjian** [comment]
这个时候是在从 GitHub 下载 `mpvue/mpvue-quickstart` ，估计是网络问题。
