### ISSUE TITLE
我有一个小程序原生项目，另外一个mpvue项目，由于想用mpvue项目的部分页面功能，现在只能在mpvue项目里开发，生成好相关的小程序文件再拷贝到原生项目中，我这种情况只能这样吗

### ISSUE THREAD

**Issue by kingning** [Meituan-Dianping/mpvue#835]
遇到的痛点，例如，读取全局配置的写法，两个项目写法不一样，目前只能在打包生成好的小程序文件里手动再改一次，这样，每次mpvue需要重新打包，我就要在打包后的文件里手动改一次，否则会被替换

**Comment by F-loat** [comment]
有 mpvue-simple 可以开发单个页面，原生页面也可以直接放在 mpvue 项目里，读取全局配置具体是指什么

**Comment by wfsovereign** [comment]
@F-loat 你好，你说的原生页面也可以放在mpvue项目，是指mpvue能够引入原生组件并使用（usingComponents引用原生组件等）还是指原生代码写的页面，能够放入mpvue项目中，最后打包成一个项目？

**Comment by aOrz** [comment]
可以把公共的部分发布到 npm 上，直接引用？
