### ISSUE TITLE
想在Components目录下新建一个 index.js文件当作入口文件。但是无法引用

### ISSUE THREAD

**Issue by Pain-and-Love** [Meituan-Dianping/mpvue#837]
-Components
  + Modal.vue
  + Title.vue
  + ...
  + index.js

这个index.js中import 所有components,然后导出,但是无法在别的Pages中引用index.js。只能在Pages单独引用某一个组件。

**Comment by liuweiGL** [comment]
升级到最新版本，然后在main.js中可以使用 `Vue.component()`注册全局组件 http://mpvue.com/change-log/2018.7.24/
