### ISSUE TITLE
v-model放在slot里面 无法接收一个初始值

### ISSUE THREAD

**Issue by luosijie** [Meituan-Dianping/mpvue#838]
![image](https://user-images.githubusercontent.com/16912206/43435353-37cbeaea-94b2-11e8-8848-eb3cddc221d2.png)
比如 给 formdata.applicationName 一个值， input 没有生效

**Comment by marsDes** [comment]
貌似没有支持slot吧；之前看官方文档的时候有看到这点

**Comment by fengshadu** [comment]
同关注这个问题。v-model放在slot里面，无法接受一个初始值。

**Comment by JuanJuanZhang123** [comment]
现在有解决方案了吗
