### ISSUE TITLE
能不能做支持wepy代码一键转mpvue的工具？

### ISSUE THREAD

**Issue by jamninetyfive** [Meituan-Dianping/mpvue#84]
# [问题简单描述]
能不能做支持wepy代码一键转mpvue的工具？
**问题复现步骤:**

1. [第一步]
2. [第二步]
3. [其他步骤...]

**期望的表现:**

[在这里描述期望的表现]
能不能做支持wepy代码一键转mpvue的工具
不引起战争，只是我比较喜欢用vue编代码。

只是因为有同时编写h5 小程序的需求 

wepy的转web还不完善  可以说是根本就不是个健全的功能。~
但是代码量太多。不可能全部重写，。~
**观察到的表现:**

[在这里描述观察到的表现]

**屏幕截图和动态 GIF 图**

![复现步骤的屏幕截图和动态 GIF 图](图片的 url)

**Comment by falost** [comment]
哈哈 这个应该可以等等 热心大佬的作品

**Comment by cuijiemmx** [comment]
我已对wepy失望，准备转mpvue了，希望不是类wepy的坑

**Comment by fantasthu** [comment]
顶起来顶起来,还是很期待wepy赚mpvue的

**Comment by marty0929** [comment]
对hera wepy weweb都已经失望了，最近才发现这个框架，希望能坚持更新。

**Comment by marty0929** [comment]
现在也是遇到需要小程序转h5的需求，不知什么时间能更新

**Comment by fantasthu** [comment]
wepy 使用起来还可以,该走的坑我们基本走的差不多了
