### ISSUE TITLE
从某个tab页进入详情页面的时候，有闪现其他tab页面的问题

### ISSUE THREAD

**Issue by Wolkenritter** [Meituan-Dianping/mpvue#841]
# [问题简单描述]
如题
**问题复现步骤:**
比如只有两个底部tab，首页和个人中心；
  1、先点击个人中心tab;
  2、切换回首页，然后进入项目详情页面;
问题呈现：
  在进入详情页面的过程中，底部会先变成之前点击的个人中心，然后才进入到了详情页面。如果编译完成之后不点击个人中心，直接从首页进入到详情页面是没这种问题的。

页面进入是使用的this.$router.push

大家有没有遇到这种情况，是怎么解决的？

gif上传不上来 -_-||

**Comment by Wolkenritter** [comment]
![1](https://user-images.githubusercontent.com/17428401/43501618-f649c628-9588-11e8-87b6-1d2574e0857c.gif)

**Comment by anchengjian** [comment]
帮你圈作者@F-loat 😂

**Comment by F-loat** [comment]
真机也有这个问题吗，怎么感觉是开发工具的锅
