### ISSUE TITLE
style里px不会转成rpx, rpx变成了px

### ISSUE THREAD

**Issue by zhowiny** [Meituan-Dianping/mpvue#843]
![image](https://user-images.githubusercontent.com/13558007/43518037-4b48aac0-95bd-11e8-87c7-3864b1dcc55c.png)
![image](https://user-images.githubusercontent.com/13558007/43518072-666bd55c-95bd-11e8-96e0-c7408a82d5a5.png)

**Comment by wenlinguo** [comment]
我也遇到

**Comment by Renford** [comment]
我痛一段代码，有的转了，有的没转

**Comment by GpingFeng** [comment]
请问解决了么，我是使用   :style="{ width: commentPopWidth +'px' }" 。

![image](https://user-images.githubusercontent.com/20135760/43947804-8cf505a4-9cbb-11e8-9414-1f16f18446d3.png)

**Comment by laoboxie** [comment]
我也是遇到同样的问题，最后单位换成vw

**Comment by aOrz** [comment]
看下编译后的文件，不要看微信开发者工具中显示的内容
