### ISSUE TITLE
为什么不支持模板字符串？

### ISSUE THREAD

**Issue by joenil** [Meituan-Dianping/mpvue#845]
# [问题简单描述]
模板里不支持``模板字符串

**Comment by anchengjian** [comment]
目前是直接把 template 转译成 wxml ，wxml 不支持 ``，所以目前暂无法支持

**Comment by joenil** [comment]
wxml 不支持 ``，但是在转译时替换成''字符串和变量拼接不难吧，有支持的计划吗？

**Comment by F-loat** [comment]
可以看下相关源码，没想象中那么容易🌚
