### ISSUE TITLE
【真机复现】分包加载，点击子包报错

### ISSUE THREAD

**Issue by hjdshu** [Meituan-Dianping/mpvue#846]
![img_3006](https://user-images.githubusercontent.com/5915245/43556664-85d785a0-9633-11e8-9aa5-913b43b334e8.PNG)
复现路径: 进首页没问题， 点击跳转到子包任何一个页面，报错，但是不影响页面js执行。

**Comment by aOrz** [comment]
给个可复现demo ？

**Comment by hjdshu** [comment]
https://github.com/hjdshu/mpvue-subpackages @aOrz

**Comment by hjdshu** [comment]
已经放弃了自己改的方案，采用f-loat大神的架子： https://github.com/F-loat/mpvue-quickstart

**Comment by hjdshu** [comment]
终极方案： https://github.com/F-loat/mpvue-quickstart

**Comment by hjdshu** [comment]
终极方案： https://github.com/F-loat/mpvue-quickstart
