### ISSUE TITLE
说好的一套代码可以直接跑在多端？？？？

### ISSUE THREAD

**Issue by lisun0459** [Meituan-Dianping/mpvue#847]
一套代码可以直接跑在多端？？？？看到这个ad果断将最近的H5项目入坑，结果写完要编译成h5的时候，奔溃了，文档里就这么一句话“其中只需要更改小部分平台差异代码和更新下 webpack 的建构配置就可以直接运行。”遍网搜索方法，按掘金里大神的配置，一步一步跟着的配，结果多端都不可运行了！！！难道这是一次弃坑之旅。官方能不能发发慈悲抽点时间出个详细的多端运行文档？？？毕竟多端运行的名声在外了。

**Comment by puzzle9** [comment]
你 你让我说什么好
你至少得把报错截图流出来吧
再者 对于vue的这个 你使用那些地方有差异
你自己没察觉出来吗
自己对技术不精 而来怪作者文档不详细
你很有想法

**Comment by qianyinghuanmie** [comment]
话糙理不糙，确实多端运行的文档应该写的更详细点。

**Comment by youngcube** [comment]
[mpvue-html-electron-typescript-starter](https://github.com/youngcube/mpvue-html-electron-typescript-starter)

做了一个小脚手架，支持 Web + Electron + 小程序，基于这个脚手架已经上线了小程序 + Web，效果还是可以的。

因为多平台运行，主要麻烦就是 Webpack 的配置。这边已经把一些基本相同的配置放在了一起。也方便查看以及按实际项目需求做进一步修改。
