### ISSUE TITLE
# Mpvue递归组件问题 

### ISSUE THREAD

**Issue by wangxuedongOvO** [Meituan-Dianping/mpvue#850]
# Mpvue递归组件问题

想写一个树形结构，如下：
![image](https://user-images.githubusercontent.com/24949711/43576948-1a29c670-967d-11e8-855f-3da07c508195.png)

请问使用，pvue该如何实现。

**Comment by F-loat** [comment]
小程序目前没法支持递归的吧，只能多写几层这样。。

**Comment by wangxuedongOvO** [comment]
我已经实现了任意深度的分层。

**Comment by F-loat** [comment]
。。你实现了分享一下呗，就这个需求而把数据打平之后通过循环应该就能解决，但是嵌套形式的数据用递归组件应该是没办法的

**Comment by johnnynode** [comment]
https://blog.csdn.net/qq_41049816/article/details/84840461
在mpvue中使用小程序原生的自定义组件
@F-loat
