### ISSUE TITLE
单个页面的main.json配置

### ISSUE THREAD

**Issue by lzh-kf** [Meituan-Dianping/mpvue#851]
单个页面main.json配置，修改没有实时更新，需要重新npm run dev

**问题复现步骤:**
第一步
main.json配置文件
{
   "navigationBarTitleText": "管理收货地址"
}
第二步
{
   "navigationBarTitleText": "管理收货地址测试"
}

**实时到小程序上面:**
发现修改，在终端并没有编译

[希望导航页变为管理收货地址测试]

[实际小程序导航页还是管理收货地址}

**Comment by Kellercai** [comment]
我也是今天刚刚分包成功，就是有个问题，以前页面级的main.js文件都是要废弃掉，用main.json代替吗？

**Comment by lzh-kf** [comment]
main.js里面的export default {
config:{
}
}
config里面的东西，应该都是都要写在main.json里面，写在main.js里面不起作用，而且 我感觉 mpvue的分包加载，又回到了原生小程序上的那种分包加载，都是通过json文件配置，和原生小程序的配置特别像

**Comment by jianzhou520** [comment]
最近一个项目有类似强需求, 通过修改webpack配置实现单页配置效果了,晚点提PR

**Comment by jianzhou520** [comment]
最新已支持, 参见 https://github.com/mpvue/mpvue-quickstart/blob/master/template/build/webpack.base.conf.js#L114

**Comment by aOrz** [comment]
升级指南里有提到：http://mpvue.com/change-log/2018.7.24/
