### ISSUE TITLE
小程序每个页面的page样式

### ISSUE THREAD

**Issue by flymeonce** [Meituan-Dianping/mpvue#853]
小程序每个页面的page 样式定义不了
![image](https://user-images.githubusercontent.com/30708895/43643764-f39556ae-975e-11e8-9f76-60eae9b9d4b2.png)

**Comment by F-loat** [comment]
小程序 page 的 css 没必要加 scoped

**Comment by flymeonce** [comment]
您好！是每个页面我想给页面的根节点page标签加些样式发自我的华为手机-------- 原始邮件 --------主题：Re: [Meituan-Dianping/mpvue] 小程序每个页面的page样式 (#853)发件人：柴茂源 收件人：Meituan-Dianping/mpvue 抄送：flymeonce <897088171@qq.com>,Author 小程序 page 的 css 没必要加 scoped

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/Meituan-Dianping/mpvue","title":"Meituan-Dianping/mpvue","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/Meituan-Dianping/mpvue"}},"updates":{"snippets":[{"icon":"PERSON","message":"@F-loat in #853: 小程序 page 的 css 没必要加 scoped"}],"action":{"name":"View Issue","url":"https://github.com/Meituan-Dianping/mpvue/issues/853#issuecomment-410258814"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/Meituan-Dianping/mpvue/issues/853#issuecomment-410258814",
"url": "https://github.com/Meituan-Dianping/mpvue/issues/853#issuecomment-410258814",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [Meituan-Dianping/mpvue] 小程序每个页面的page样式 (#853)",
"sections": [
{
"text": "",
"activityTitle": "**柴茂源**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@F-loat",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"Meituan-Dianping/mpvue\",\n\"issueId\": 853,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"Meituan-Dianping/mpvue\",\n\"issueId\": 853\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/Meituan-Dianping/mpvue/issues/853#issuecomment-410258814"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 364360840\n}"
}
],
"themeColor": "26292E"
}
]
