### ISSUE TITLE
在mixins中使用this会在真机上报循环依赖的错误,

### ISSUE THREAD

**Issue by tutuerhao** [Meituan-Dianping/mpvue#855]
# [问题简单描述]
在mixins中使用this会在真机上报错
![image](https://user-images.githubusercontent.com/29938085/43674872-b83cbf26-980c-11e8-9bee-910ec29b9c0a.png)

![2_zv5x0vc6r8n6r8t 96 l](https://user-images.githubusercontent.com/29938085/43674880-dc0481dc-980c-11e8-9a34-3832c6d13dfe.jpg)

**Comment by shaonialife** [comment]
#698
