### ISSUE TITLE
MPvue 编译wxss文件出错

### ISSUE THREAD

**Issue by alexxiaoa** [Meituan-Dianping/mpvue#857]
# [问题简单描述]

**问题复现步骤:**

1. [第一步]
第一次正常编写相关代码后，关掉相关IDE和小程序工具
重新打开编辑程序运行 RUN DEV 
就提示找不到文件，编译WXSS文件出错；

删除掉相关文件，重新建又可以

3. [其他步骤...]
![image](https://user-images.githubusercontent.com/20310904/43699761-ab83b2d6-9982-11e8-8bfd-3e113a2066a8.png)

**Comment by John-z-x** [comment]
![wui gxr gm 7br6v vg 0b7](https://user-images.githubusercontent.com/17636286/43951642-38d4a2ee-9cc6-11e8-9f3e-dfe21cd0ce69.png)

**Comment by kevinlvhsl** [comment]
我也遇到这个问题， 在配置pages的时候你这样写：  pages: ['^pages/banwu/banwu'] 应该就没问题了 
是否是一个bug？
