### ISSUE TITLE
关于slot绑定值的问题以及不太好的临时解决方案？

### ISSUE THREAD

**Issue by photon-phalanx** [Meituan-Dianping/mpvue#860]
# [问题简单描述]
已经有许多demo提到了这个问题，具体可以见步骤。
**问题复现步骤:**
父组件
```js
<template>
  <div class="container">
    <tem>
      <div>以下val的初始值取不到</div>
      <input v-model="val">
    </tem>
  </div>
</template>

<script>
  import Tem from './tem'
  export default {
    data () {
      return {
        val: 123
      }
    },
    components: {
      Tem
    }
  }
</script>

```
子组件
```js
<template>
  <div>
    <slot></slot>
  </div>
</template>

<script>
  export default {
    name: 'tem'
  }
</script>
```
**期望的表现:**

在初始的时候，input已经有值123。

**观察到的表现:**

没有获取到初始值。

**可能的原因**
从编译后的wxml来看，value已经绑定到val变量上。但是这个val变量并没有传下来。
```js
<import src="test$070a3823" />
<template name="data-v-3296f12b-default-0">
  <view class="_div data-v-3296f12b">val的值取不到</view>
  <input value="{{val}}" bindinput="handleProxy" data-eventid="{{'0'}}" data-comkey="{{$k}}" class="_input data-v-3296f12b" />
</template>
```

**一个极为不妥的解决方式**
将mpvue-template-compiler/build中的第4587行改为
```js
      attrsMap['data'] = "{{...$root[0],...$root[$k], $root}}";
```
已知这样做的坏处是会把父组件自身的多个非必须属性一起传下去。但是似乎并不会发生属性重名时的冲突问题，重名时子组件应该是能遮蔽掉父组件的。其他副作用未知。

希望官方能够改进complier逻辑使slot能够更加好用，谢谢。

**Comment by photon-phalanx** [comment]
#838

**Comment by photon-phalanx** [comment]
#838

**Comment by KamiJam** [comment]
mark,快被slot整疯了

**Comment by vanpipy** [comment]
临时的解决方案可以从业务的方向得到临时性的解决，但是首先需要了解的是，为什么slot发生了意想不到的情况。

假设如下面的情况
```
//modal.vue
//template
<div>
    Im a modal.
    <slot name="body"></slot>
</div>

//script
export default {
    props: {
        error: 'Im modal error inside'
    }.
}

// main.vue
//template
<modal>
    <div name="body">{{ error }}</div>
</moda>

//script
export default {
    component: { modal },
    props: {
        error: 'Im an error',
    }.
}
```

实际可以看到的结果是 `error` 等于 'Im modal error inside', 这说明在slot生效的时候上下文引用的是modal组件，但是这个上下文在main.vue 进行渲染的时候，又会引用为main.vue的上下文。此类情况可以通过将 `error` 替换成 `Object` 变量进行观察。

所以这就有点类似我们挥手，但是在阳光下没有影子一样。在javascript中的 `{}` 具有一种神奇的特性，可以补充这种可以成为缺失影子现象，就是 `{}` 属性类型的改变并不影响其本身的性质，`{}` 是不可变的。

所以可能的话，请尝试
```
//modal.vue
//template
<div>
    Im a modal.
    <slot name="body"></slot>
</div>

//script
export default {
    props: {
        shadow: {
            default: {},
        }
    }.
}

// main.vue
//template
<button @click="changeMsg()">Try some change</button>
<modal>
    <div name="body" :shadow="shadow">{{ shadow.msg }}</div>
</moda>

//script
export default {
    component: { modal },
    props: {
        shadow: {},
    }.
    computed: {
        error: function () { return this.shadow },
    },
    methods: {
        changeMsg: function() {
             this.error.msg = 'The error message you want.';
        }
    }
}
```
通过利用 `{}` 的这种引用特性，来临行的处理slot特性的使用。

希望构建工具开发的小伙伴能够定位问题，从而在构建工具的角度，整体的解决这种特性问题。

**Comment by ljtang2009** [comment]
测试了楼主的方法，在他的测试案例下，他的方法是可行的。即对于单层组件，可以用该方法使slot绑定值。
但是对于组件里又引用了组件，该方法就无效了。
例如：
父组件 main.vue
`<template>
  <div>
    <son></son>
  </div>
</template>

<script>
  import son from './son'
  export default {
    components: {
      son
    }
  }
</script>`

子组件 son.vue
`<template>
  <div>
    <gson>
        <div>{{param}}</div>
    </gson>
  </div>
</template>

<script>
  import gson from './gson'
  export default {
    components: {
      gson
    },
    data() {
        return {
            param: 'gsonName'
       }
    }
  }
</script>`

孙组件: gson.vue
`<template>
  <div>
    <slot></slot>
  </div>
</template>`

这种情况下，子组件的值无法在孙组件的slot中绑定。
目前只能参考vanpipy方法，修改业务代码。

**Comment by photon-phalanx** [comment]
@ljtang2009 @vanpipy  非常感谢大佬们的指点和测试。本身这也不是一个好的做法，多次引用的情况在下也考虑不周。
由于mpvue还是存在一些问题，所以现在业务已经使用原生重写，可能在最近也不能为此问题找到更好的代码修改方法，故close该issue。
再次感谢两位。

**Comment by cdll** [comment]
same issue here!
