### ISSUE TITLE
npm run dev未生成app.wxss文件

### ISSUE THREAD

**Issue by liaorende** [Meituan-Dianping/mpvue#861]
编译结束在dist/static/css下未生成app.wxss 运行报错

"mpvue": "^1.0.11",
"mpvue-loader": "1.0.13",

**Comment by guotie** [comment]
同样的错误

新建的一个项目就可以生成，原来的一个项目无法生成。

将新建的项目与原来的项目逐个文件对比过，都是一样的内容，node_modules也删除重建过，还是无法生成

**Comment by guotie** [comment]
app.json 也没有

**Comment by guotie** [comment]
我把 build\webpack.base.conf.js 文件中的

```
const pagesEntry = getEntry(resolve('./src'), 'pages/**/main.js')
```

改成过 'pages/**/index.js'， 然后又改会原来的，现在在dist目录下生成的文件名都不一样了

**Comment by guotie** [comment]
对比了yarn.lock，发现是mpvue版本的问题：

1.0.11没有问题，

1.0.13有问题

**Comment by kozzzx** [comment]
通过使用最新版本解决了,暂时没遇到不兼容的地方
1. 用mpvue-quickstart新建新的同名项目
2. 将src中编写的代码拷贝到新的项目中,并将APP/Page的配置,改成符合新版要求的json格式
3. 将其他之前修改了的文件文件修改一下,比如.eslintrc.js之类,如果有static也拷贝进去
4. npm run build成功后,将.git文件夹拷贝过来,提交覆盖之前的版本

**Comment by ljx09195117** [comment]
@kozzzx 
通过使用最新版本解决了,暂时没遇到不兼容的地方

用mpvue-quickstart新建新的同名项目
将src中编写的代码拷贝到新的项目中,并将APP/Page的配置,改成符合新版要求的json格式
将其他之前修改了的文件文件修改一下,比如.eslintrc.js之类,如果有static也拷贝进去
npm run build成功后,将.git文件夹拷贝过来,提交覆盖之前的版本

这里说的第2点里面的符合新版要求的json格式是什么格式？？在哪里能看到啊

**Comment by kozzzx** [comment]
@ljx09195117 
升级参考这里 [升级指南](http://mpvue.com/change-log/2018.7.24/)
json格式参考这里 [小程序官方文档](https://developers.weixin.qq.com/miniprogram/dev/quickstart/basic/file.html#json-%E9%85%8D%E7%BD%AE)
![qq 20180824162828](https://user-images.githubusercontent.com/9611408/44574015-c2dfc280-a7ba-11e8-96ed-d01563996b18.png)
就是把原来main.js中config字段放到app.json, Page如果有设置则也把其main.js中config字段放到对应文件夹下的main.json中
![qq 20180824162554](https://user-images.githubusercontent.com/9611408/44574017-c4a98600-a7ba-11e8-9b8e-231c9f462aad.png)

**Comment by ljx09195117** [comment]
@kozzzx 感谢
