### ISSUE TITLE
有小伙伴和我一样图片被拉伸了吗？而不是显示图片原本的大小

### ISSUE THREAD

**Issue by shengbaise** [Meituan-Dianping/mpvue#863]
# [问题简单描述]

**问题复现步骤:**

1. [第一步]
2. [第二步]
3. [其他步骤...]

**期望的表现:**

[在这里描述期望的表现]

**观察到的表现:**

[在这里描述观察到的表现]

**屏幕截图和动态 GIF 图**

![复现步骤的屏幕截图和动态 GIF 图](图片的 url)

**Comment by hughfenghen** [comment]
https://developers.weixin.qq.com/miniprogram/dev/component/image.html

查看官方文档 image 组件的mode 13 种模式

![image](https://user-images.githubusercontent.com/3307051/43871896-6934cd4e-9bb1-11e8-9be8-8eeae1068ae4.png)

**Comment by kakayunmu** [comment]
你解决了吗？我也遇到这个问题了。image 组件设置mode 完全不起作用。在原生的小程序里 mode设置是起作用的。。现在不知道怎么弄了

**Comment by shengbaise** [comment]
我解决了，你代码怎么写的，截一下图
