### ISSUE TITLE
页面返回后重新进入，_watchers一直在增加。

### ISSUE THREAD

**Issue by joenil** [Meituan-Dianping/mpvue#865]
# [问题简单描述]
页面返回之后，重新进入页面，watcher数量一直在增加，就是之前都watcher没有被清理。

``` javascript
export default {
  mounted () {
    console.log(this._watchers.length)
  }
}
```

**Comment by joenil** [comment]
这样造成很大的问题，如果store里的数据有变，watcher还是会执行，可能会有一些请求发出造成浪费，也可能查询页面selector后造成报错。希望能尽快从框架层面解决这个问题。

**Comment by lichenabson** [comment]
#966
