### ISSUE TITLE
新建项目卡在wxmp appid

### ISSUE THREAD

**Issue by zxlau** [Meituan-Dianping/mpvue#866]
# [问题简单描述]

新建项目卡在wxmp appid，回车不起作用，怎么都没反应了。

**问题复现步骤:**
新建项目，到wxmp appid项

![复现步骤的屏幕截图和动态 GIF 图](图片的 url)
![image](https://user-images.githubusercontent.com/23397868/43876986-280c8a32-9bca-11e8-8801-99d58d0c6636.png)

**Comment by xuech** [comment]
我也是
