### ISSUE TITLE
mpvue跳转相同的页面 点击返回 会显示最后一次访问的数据

### ISSUE THREAD

**Issue by cxh1991** [Meituan-Dianping/mpvue#871]
商品列表页，点击跳转带goodid过去请求接口到详情页，展示数据，然后详情页，里面有商品推荐列表，继续点击跳转带goodid过去请求接口到详情页，层层操作，当我点击返回的时候，这时候应该回到上一个商品详情页，但是确实显示 刚刚的详情页，我没有在onshow里面重新请求接口 ，我把this.$root.$mp.query.id 在onshow里面打印出来，始终是我最后返回的id，导致始终显示的详情是我最后一次访问的页面，请问怎么解决，我返回上一页是我上次浏览的记录？

**Comment by lzh-kf** [comment]
这个会造成数据污染 ，你可以使用vux的进行数据存储，给你说下我的做法，我是在onLoad里面用同步的方式 ，等页面数据全部加载完成，存到vux里面，在卸载页面的的时候onUnload里面删除vux里面的数据，在onReady里面读取之前存储的数据，大致思路就是这样`  
 onLoad(options) {
     // 默认是false
     //在vux里面，存一个全局标识,页面初始化的时候，重置为false
        store.commit('resetFlag')
        Object.assign(this.$data, this.$options.data())
        this.query.id = this.$getParams(options).id
        this.query.itemId = this.$getParams(options).itemId
    },
    onShow() {
    // 页面显示的时候，第一次，默认不读取vux里面的数据，之后会退的时候，在读取vux里面的数据
        let flag = store.state.itemFlag
        if (flag) {
            let itemIdLength = store.state.itemList.length - 1
            let itemList = store.state.itemList[itemIdLength]
            Object.assign(this.$data, itemList)
        }
      // 改变全局唯一标识
        flag === false ? store.commit('changeFlag') : ''
    },
    async onReady() {
        await this.getItemInfoById()
       // 储存数据
        let testList = JSON.parse(JSON.stringify(this.$data))
// 这个方式是push进数组
        store.commit('addItem', testList)
    },
    onUnload() {
        Object.assign(this.$data, this.$options.data())
// 删除数组的最后一位
        store.commit('deleteItem')
    },`
你可以参考下
