### ISSUE TITLE
使用v-bind.sync 给子组件传入对象控制台报警告

### ISSUE THREAD

**Issue by leanTim** [Meituan-Dianping/mpvue#872]
# [问题简单描述]
使用v-bind.sync 给子组件传入对象控制台报警告

**问题复现步骤:**
通过v-bind.sync 传入一个对象props 
```javascript
  <ShareToast v-bind.sync="testVisible" />
testVisible: {
  visible: true,
  title: 'testtest'
}
```
子组件 `ShareToast` 这样接收
```javasctipt
export default {
  props: ['visible', 'title']
}
```

表现与预期一样 就是功能其实是正常的 但是控制台会有警告
如果`.sync`绑定的是一个简单地值一切都都正常

![警告](http://3-im.guokr.com/fl0-hLdOH99C0xTddR9gFwYefdZxUGjOz-QNDZXCjwxYBQAA3gEAAFBO.png)

**Comment by ccwq** [comment]
mpvue看着挺美，用着总感觉哪儿不对。
