### ISSUE TITLE
npm run dev 突然运行不动了。。。

### ISSUE THREAD

**Issue by qiaolevip** [Meituan-Dianping/mpvue#876]
# [问题简单描述]
一下午开发的好好的，突然间 npm run dev就卡在
```bash
$ npm run dev

> color-life@1.0.0 dev /home/happy/Dev/coding/color-life
> node build/dev-server.js
```

**问题复现步骤:**

1.npm run dev不行
2. 删除module重装也不行
3. 重新初始化项目也不行

**期望的表现:**

[已失望]

**观察到的表现:**

Ubuntu16 (current: {"os":"linux","arch":"x64"})

```json
"dependencies": {
    "flyio": "^0.6.0",
    "mpvue": "^1.0.11"
  },
  "devDependencies": {
    "mpvue-loader": "^1.1.2",
    "mpvue-webpack-target": "^1.0.0",
    "mpvue-template-compiler": "^1.0.11",
```

**Comment by aOrz** [comment]
ubuntu 16，node 8.9 未复现，提供下其他有用的信息？

**Comment by qiaolevip** [comment]
什么叫有用的信息？
为什么console没有有效的报错，而是卡死。

**Comment by F-loat** [comment]
你想想你卡住之前做了什么啊，而且 issue 里有大量这个问题，基本都是有文件缺 script 部分造成的

**Comment by qiaolevip** [comment]
:rofl: 可定位到问题了，一个组件由于纯template写的不需要script，后面加了
```JavaScript
<script>
  export default {}
</script>
```

再次允许就成功了，主要是很多卡在这的issues里面的答案并没有说明，而且也没有报错信息，为刚入坑的新户来说定位并不是那么容易。

不过解决了，还是很开心的，thx。 :+1:

**Comment by lavyun** [comment]
希望能加个提示，这个坑挺恶心的

**Comment by pxzsl** [comment]
我也被卡住了，完全定位不到问题呀
