### ISSUE TITLE
使用scrollview的scroll-into-view属性进行锚点定位，页面退回前一页后再打开，锚点定位不准确

### ISSUE THREAD

**Issue by LenaLiu** [Meituan-Dianping/mpvue#880]
# [问题简单描述]
用scrollview的scroll-into-view属性进行锚点定位，页面退回前一页后再打开，锚点定位不准确；

**问题复现步骤:**
1. [第一步]
从首页打开这个城市选择列表，点击字母能定位到对应的锚点
2. [第二步]
返回首页后再进去城市选择列表，点击字母不能定位到对应的锚点，总感觉view视图没有滚动完全

**期望的表现:**
预期是希望每次打开列表都能定位到点击字母所对应的锚点

**Comment by blackerer** [comment]
兄弟，这个问题在后面解决了吗？
