### ISSUE TITLE
父组件利用props传值时，虽然成功，但是却无法获取该值内部的某个键的值

### ISSUE THREAD

**Issue by YeahDreamItPossible** [Meituan-Dianping/mpvue#881]
#父组件利用props传值时，虽然成功，但是却无法获取该值内部的某个键的值

第一步：
父组件Index利用props给子组件StoreIndexBanner 动态传值storeInfo，该值类型未Object，且在父组件中data已经初始化
第二部：
在子组件StoreIndexBanner中的钩子函数created中虽然可以打印出这个storeInfo,但是却打印不出这个对象内部某个键所对应的值

父组件截图：
父组件初始化storeInfo:
![1](https://user-images.githubusercontent.com/41123661/44065967-780bed6e-9fa0-11e8-8b34-d2afb5728e76.png)
父组件liyo利用props传值给子组件StoreIndexBanner:
![2](https://user-images.githubusercontent.com/41123661/44065978-8a8ca992-9fa0-11e8-8e3f-0783048294fe.png)
子组件StoreIndexBanner打印出这个对象及对象内某个键所对应的值:
![3](https://user-images.githubusercontent.com/41123661/44065996-a4993ab2-9fa0-11e8-8086-56cc4aa3f0cd.png)
小程序中的打印结果：
![4](https://user-images.githubusercontent.com/41123661/44066024-c4cb8718-9fa0-11e8-8cb3-7f950618e35f.png)

**Comment by YeahDreamItPossible** [comment]
但是在vue项目中这种方式传值就可以得到想要的结果。。。

**Comment by xiaojiangjiang** [comment]
#567 你这问题 和 我之前提的问题 应该是一类问题 我也遇到了 不知何解

**Comment by YeahDreamItPossible** [comment]
@xiaojiangjiang     我这边是这样处理的：   在父组件传值前，将子组件所有的数据处理都放在父组件中，子组件仅仅用于展示（template中可以展示出这个值内部的键值对）。   其次，我觉得可能是框架内部在利用props传值时vue与小程序冲突了。。。。

**Comment by breederComrade** [comment]
同样遇到这个问题！ 如果出现props内对象属性键值队就无法获取到

**Comment by wjf9492** [comment]
有解决的么？？我也遇到这个问题了
