### ISSUE TITLE
线上报错：thirdScriptError t is not a function. (In 't(e)', 't' is undefined)...

### ISSUE THREAD

**Issue by dream2023** [Meituan-Dianping/mpvue#883]
问题：
线上不断（很频繁）报错 t 函数找不到，本地没报过错，错误信息如下：

thirdScriptError t is not a function. (In 't(e)', 't' is undefined);
at pages/article/detail/main onReady function;
at setTimeout callback function c _onNativeTimer global code

**Comment by chuquancai** [comment]
后台错误日志确实能看到这个，不知道跟mpvue有没有关系
