### ISSUE TITLE
1.1.2版本的升级文档有个小错误

### ISSUE THREAD

**Issue by liuweiGL** [Meituan-Dianping/mpvue#887]
# [问题简单描述]

[升级文档](http://mpvue.com/change-log/2018.7.24/#srcmainjs)中提示把`main.js`中的`config`字段移到`main.json`文件中是错误的，应该是`app.json`文件；还有记得把首页路径中的`^`去掉。新版本可以注册全局组件，赞一个！！！

---

**问题复现步骤:**

无

1. [第一步]
2. [第二步]
3. [其他步骤...]

**期望的表现:**

[在这里描述期望的表现]

**观察到的表现:**

[在这里描述观察到的表现]

**屏幕截图和动态 GIF 图**

![复现步骤的屏幕截图和动态 GIF 图](图片的 url)

**Comment by aOrz** [comment]
已修复，感谢反馈
