### ISSUE TITLE
全局store怎么使用啊

### ISSUE THREAD

**Issue by wo2095296** [Meituan-Dianping/mpvue#89]
# [问题简单描述]

**问题复现步骤:**

1. [第一步]
2. [第二步]
3. [其他步骤...]

**期望的表现:**

[在这里描述期望的表现]

**观察到的表现:**

[在这里描述观察到的表现]

**屏幕截图和动态 GIF 图**

![复现步骤的屏幕截图和动态 GIF 图](图片的 url)

**Comment by anchengjian** [comment]
第一，可以写在一个 `js module` 里，然后哪里用哪里 `import`。
第二，参考第一种玩法，用 `vuex` 或者类似的数据管理工具进行全局数据储存。
第三，就是各种存储 `storage` 里面。
第四，就是在组件里可以 `this.$root.$mp.appOptions` 上进行存取。
第五，通过小程序自身全局方法。

```
const app = getApp();
app.globalData = { store: {} }
```

**Comment by hlg-facai** [comment]
this.$root.$mp.appOptions 里面的值小程序缩小再点击进入值就没了

**Comment by smoothdvd** [comment]
@anchengjian
```
const app = getApp();
app.globalData = { store: {} }
```
这个代码写在哪个文件里呢？

**Comment by anchengjian** [comment]
@smoothdvd 不推荐这种玩法，这是小程序自身的全局对象，任何文件都可以。 https://developers.weixin.qq.com/miniprogram/dev/framework/app-service/app.html 这个文档里面有 getApp 相关资料

**Comment by smoothdvd** [comment]
@anchengjian 明白了

**Comment by 1021683053** [comment]
再 入口 main.js中使用
`Vue.prototype.$store = store`

**Comment by ExcellentJR** [comment]
@1021683053 老铁这样用的时候，有没有遇到过在某些情况下（真机）无法正常获取到store对象的问题？出现的概率很小，但是偶尔会有

**Comment by 1021683053** [comment]
@ExcellentJR 老铁，我后来换Taro开发了，应该没啥问题。
