### ISSUE TITLE
在项目的index.html中配置<meta name="referrer" content="no-referrer"/>请求图片的时候还是会带上referrer

### ISSUE THREAD

**Issue by shengbaise** [Meituan-Dianping/mpvue#891]
# [问题简单描述]

**问题复现步骤:**

1. [第一步]
2. [第二步]
3. [其他步骤...]

**期望的表现:**

[在这里描述期望的表现]

**观察到的表现:**

[在这里描述观察到的表现]

**屏幕截图和动态 GIF 图**

![复现步骤的屏幕截图和动态 GIF 图](图片的 url)

**Comment by leonskywalker** [comment]
这个referer是小程序自己加的，没法去掉的

**Comment by aOrz** [comment]
同上
