### ISSUE TITLE
返回问题

### ISSUE THREAD

**Issue by webHuangKe** [Meituan-Dianping/mpvue#894]
# [A页面跳到B页面，在B页面通过getCurrentPages()进行修改A页面data的内容如何修改？]

**Comment by xianxingzhe** [comment]
vuex不适合此场景，希望大牛给指导下，用getCurrentPages()进行上一个页面data数据修改

**Comment by aOrz** [comment]
https://github.com/Meituan-Dianping/mpvue/issues/300
