### ISSUE TITLE
”mpvue-loader": "^1.1.2”最外层的main.js 里面的config不自动生成app.json

### ISSUE THREAD

**Issue by stringworld** [Meituan-Dianping/mpvue#896]
# 使用最新的”mpvue-loader": "^1.1.2”打包不会自动生成app.json，会把main.js同级目录下的app.json拷贝到打包的dist文件中
此处的config不会自动编译成app.json
![image](https://user-images.githubusercontent.com/9764134/44203442-7de7da80-a181-11e8-880e-84cc032397e6.png)

![image](https://user-images.githubusercontent.com/9764134/44203317-1a5dad00-a181-11e8-9489-479ab9097226.png)
![image](https://user-images.githubusercontent.com/9764134/44203330-26e20580-a181-11e8-8e24-812a618b432f.png)
解决方式是把app.json手动创建，写原生的app.json

**Comment by aOrz** [comment]
http://mpvue.com/change-log/2018.7.24/
