### ISSUE TITLE
小程序代码上传问题

### ISSUE THREAD

**Issue by langlangbody** [Meituan-Dianping/mpvue#898]
# [mpvue生成的小程序码在开发者工具上传的时候出现体积过大提示]

**问题复现步骤:**

1. 
以下文件体积超过 500KB，已经跳过压缩以及 ES6 转 ES5 处理，如在该文件有使用到 ES6 特性，请使用其它工具转换成 ES5 或压缩，否则可能会在低版本设备上运行有风险：
· static/js/vendor.js

**Comment by liufeics** [comment]
我也遇到这个问题，1.用cdn把一些资源包分离出来。2.不管他，build后已经压缩和转化过了

**Comment by qinghua5453** [comment]
我直接提示 上传错误，原因：Error: 未找到 app.json 中的定义的 pages "pages/index" 对应的 JS 文件。
我是npm run build 后点击上传，出现这个报错的。

**Comment by qinghua5453** [comment]
好吧，刚试了下，居然npm run dev后是可以上传的，npm run build后就不行。哎。

**Comment by qinghua5453** [comment]
npm run build 后可以上传，但无法启动小程序首页。

**Comment by dushibaiyu** [comment]
@qinghua5453  我也遇到build后错误，你需要重新打开项目的。
我的是关闭项目，在重新打开就好了。
那个提示过大的一直有

**Comment by aOrz** [comment]
vender 文件过大时可以修改 vender 拆分的逻辑 https://github.com/mpvue/mpvue-quickstart/blob/master/template/build/webpack.prod.conf.js#L74

**Comment by aetherwu** [comment]
> vender 文件过大时可以修改 vender 拆分的逻辑 https://github.com/mpvue/mpvue-quickstart/blob/master/template/build/webpack.prod.conf.js#L74

能否烦请描述一下操作的细节吗？
