### ISSUE TITLE
我想提交一个地址联动的组件可是不知道怎么做

### ISSUE THREAD

**Issue by vellsuan** [Meituan-Dianping/mpvue#903]
# [问题简单描述]
组件我已经写好了，fork了项目，打了分支，可是不知道如何去操作clone下来的项目，写这个的原因是我发现mpvue并没有三级联动的省市县组件，而微信本身的组件不能够灵活的使用公司的一套数据去渲染省市县，和对应的code。。。可能说的不是很清楚，请告诉我怎么贡献
**问题复现步骤:**

1. [第一步]
现在没有合适的可定制数据的三级联动组件
2. [第二步]
3. [其他步骤...]

**期望的表现:**

[想把写的三级联动贡献一下]
![y x5ne vxbbmg nwhqev](https://user-images.githubusercontent.com/25877064/44255157-aa5e2e00-a237-11e8-9ca0-266a2806f69c.png)
)

**Comment by LeeHarlan** [comment]
mpvue不涉及UI组件，你可以去其他项目提PR

**Comment by vellsuan** [comment]
谢谢哈哈我搞错了 应该是去mpvue的ui库
