### ISSUE TITLE
vue.js + vux + vuex 项目转mpvue 能实现吗

### ISSUE THREAD

**Issue by useraxian** [Meituan-Dianping/mpvue#904]
目前的项目是用vue.js + vux + vuex ，其中也用到vue 的router 。想用mpvue转小程序，不知道能不能实现，改动大不大呢？

**Comment by xieyihao** [comment]
看vux常见[问题](https://doc.vux.li/zh-CN/faq/can-vux-used-in-weapp.html)


> VUX 能否在微信小程序里使用
Sorry，不能。微信小程序是个相对封闭的平台，无法简单地适配也没有计划支持小程序版本。

> 目前企业主体用户可以使用 web-view 组件直接显示 web 页面，间接地使用 VUX。

> mpvue 解决方案能否直接迁移 VUX
目前 mpvue 还不支持 slot、slot-scope，因此迁移有难度，并且小程序存在较多差异，暂未计划。

**Comment by aOrz** [comment]
可以做到大量的代码复用，由于小程序和 H5 还有很多差异无法抹平，还无法做到直接转换
