### ISSUE TITLE
删除node_modules后，重装后编译不会产生app.json文件，100%出现

### ISSUE THREAD

**Issue by dream2023** [Meituan-Dianping/mpvue#906]
出现原因：
删除node_modules后，重装后编译不会出现app.json，app.wxss ，无法正常启动，出现过两次，而且其他人也遇到了相同的问题，但我自己初始化新的项目进行测试，却没能复现，求解答

**Comment by liuweiGL** [comment]
你这样描述问题别人也只能猜答案。。。
---
思考方向：

Q:  删除 `node_modules` 影响的是什么？

> 依赖的类库版本：本来是1.0.0的依赖，你删除`node_modules`再 install，依赖的版本可能就变了。我对nodejs的版本控制不太了解，没法给出精准的解答。

---

解决方法：

> 既然重新初始化的项目没问题，那就把初始化的项目资源删掉，把你当前项目的资源拷贝过去；然后 `package.json` 中的 `生产依赖` 重新安装一遍。

**Comment by liuweiGL** [comment]
补充一下：项目资源是指 `src` 目录以及 `static` 目录下的资源

**Comment by dream2023** [comment]
事实上，做了，竟然也奇葩的不行，不知道为什么，编译不出来app.json

**Comment by liuweiGL** [comment]
你的项目资源拷贝过去之后，之前的 `main.js` 中的 `config` 内容需要转移到 `app.json` 中，不然最新的 `mpvue-loader` 是不会生成 `app.json` 的。具体的你可以看下[升级文档](http://mpvue.com/change-log/2018.7.24/#srcappjson)

**Comment by dream2023** [comment]
@liuweiGL 但是我的不是最新版，老版本，1.0.11

**Comment by dream2023** [comment]
@liuweiGL 多谢，我试试
