### ISSUE TITLE
npm run dev报错：`Syntax Error: /Users/llee/git/mpvue-echarts/node_modules/mpvue-loader/lib/mp-compiler/util.js:154 });`

### ISSUE THREAD

**Issue by HecateDK** [Meituan-Dianping/mpvue#910]
# [问题简单描述]
照着文档，第一次搭建mpvue项目，
![image](https://user-images.githubusercontent.com/19571458/44318425-5ede9680-a468-11e8-9ab9-cd78bddf6f55.png)

`npm i`后
![image](https://user-images.githubusercontent.com/19571458/44318443-8170af80-a468-11e8-9609-86ea5f1fe37c.png)

一些版本：
```js
"dependencies": {
    "mpvue": "^1.0.11",
    "vuex": "^3.0.1"
  },
  "devDependencies": {
    "mpvue-loader": "^1.1.2",
    "mpvue-webpack-target": "^1.0.0",
    "mpvue-template-compiler": "^1.0.11",
    "postcss-mpvue-wxss": "^1.0.0",
    "webpack-mpvue-asset-plugin": "^0.1.1",
}
```

**Comment by maixiya0724** [comment]
node_modules\_mpvue-loader@1.1.3@mpvue-loader\lib\mp-compiler/utils.js  文件 第 139 行 少了个 } 结束 括号 这种bug 我也是很服气，太低级了 ，加个 } 就行了

**Comment by Eric--** [comment]
mmp，me too

**Comment by yangjjfc** [comment]
mmp，me too

**Comment by wtus** [comment]
mmp，me too

**Comment by anchengjian** [comment]
同 #911
