### ISSUE TITLE
在index.html中引入static目录下公共的css和js样式不起作用

### ISSUE THREAD

**Issue by qinghua5453** [Meituan-Dianping/mpvue#912]
在index.html中引入static目录下公共的css和js样式不起作用
**问题复现步骤:**

vue的单页面的根文件，index.html中经常需要引入一些公共的css或js，但引入后，并没有成功
   mpvue-cli中index.html中有一句备注：
   built files will be auto injected  （build的文件会自动注入）

**期望的表现:**

[期望想vue的spa的单页面应该那样在index.html中可以引入公共的css或js文件]

**Comment by qinghua5453** [comment]
@liufeics 我直接在index.html中写一个<script>alert(0)</script> 都无法弹出。

**Comment by liufeics** [comment]
你不管在那里alert都不会成功。小程序没有提供这个api

**Comment by qinghua5453** [comment]
@liufeics 
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>my-project</title>
  </head>
  <body>
    <div id="app"></div>
    
  </body>
  <script>
    console.log(1)
  </script>
</html>

这样也不行。在index.html中。我是直接git clone mpvue 的脚手架。所以对这个框架的搭建不是很清楚。

**Comment by qinghua5453** [comment]
@liufeics 感觉就是在index.html中不能引入js文件，也不能引入css文件，所有的静态资源都只能通过import到vue文件，然后build后才能导入。那公共静态资源文件，就很尴尬了

**Comment by liufeics** [comment]
怎么尴尬了？多的是解决方案，最简单的就是cdn都能本地化。不知道你要干嘛？至少你在做之前了解一下小程序的机制。

**Comment by aOrz** [comment]
忽略 index.html，这个是个无用的文件

**Comment by qinghua5453** [comment]
@aOrz ok 已经解决了，直接在App.vue里面的引入静态资源了，或者我想main.js 入口文件也是可以。index.html确实没啥用。跟以前spa页面不太一样。

**Comment by Javebean** [comment]
@qinghua5453 请问在app.vue中怎么引入静态资源的呢？

**Comment by limengge291** [comment]
> @aOrz ok 已经解决了，直接在App.vue里面的引入静态资源了，或者我想main.js 入口文件也是可以。index.html确实没啥用。跟以前spa页面不太一样。

但是编译在小程序里面还是不对呢，app.wxss是这样的@import url(/static/dist/common/index.wxss);
