### ISSUE TITLE
Syntax Error: \mpvue\my-project\node_modules\_mpvue-loader@1.1.3@mpvue-loader\lib\mp-compiler\util.js:154 });

### ISSUE THREAD

**Issue by chenweiyang1** [Meituan-Dianping/mpvue#916]
# [问题简单描述]
npm run dev报错
**问题复现步骤:**

![image](https://user-images.githubusercontent.com/14137223/44326298-c824d080-a48d-11e8-98eb-d2d2f27451a2.png)

**Comment by chenweiyang1** [comment]
突然报个这种错误， 什么情况啊？

**Comment by anchengjian** [comment]
同 #911

**Comment by chenweiyang1** [comment]
![image](https://user-images.githubusercontent.com/14137223/44327433-2c955f00-a491-11e8-8113-6b3c27964770.png)
这儿，少个"}" !!!!!!   太不严谨了！！
