### ISSUE TITLE
scroll-view 绑定scroll-top，无法监听

### ISSUE THREAD

**Issue by Rem486** [Meituan-Dianping/mpvue#917]
# [问题简单描述]
需求：需要有一键返回顶部功能。
对小程序组件 scroll-view 绑定 `:scroll-top="scrollTop"` ，通过改变scrollTop的值来实现返回顶部的功能。
**问题复现步骤:**

1. `<scroll-view class="h100" scroll-y  :scroll-top="scrollTop"
             scroll-with-animation="true">`
2. js部分，初始化 `scrollTop:0`，返回顶部方法，直接修改scrollTop的值。
     `goToTop () {
      this.scrollTop = 0
    }`
3. 页面内滑动，scroll-top的值无变化，始终是0，导致修改scrollTop = 0无效**(猜测)**。

**期望的表现:**
可以实现返回顶部功能。

**观察到的表现:**
之后通过增加了监听scroll方法，然后动态给scrollTop赋值的方法，实现了滚动到了顶部，但是抖动异常严
重，而且返回顶部的图标会偶尔消失。
`<scroll-view class="h100" scroll-y @scroll="scroll" :scroll-top="scrollTop"
             scroll-with-animation="true">`
**屏幕截图和动态 GIF 图**

![复现步骤的屏幕截图和动态 GIF 图](图片的 url)

![5b7adb6216aa0](https://user-images.githubusercontent.com/22462424/44349492-b9f7a400-a4cf-11e8-88cc-e6923f1af5ee.gif)

**Comment by ExcellentJR** [comment]
所以你最后实现了吗？还是没解决？

**Comment by simicn** [comment]
我也遇到了这个问题，使用时绑定`:scroll-top="scrollTop"`

```
<scroll-view class="qa-chat-list"
        scroll-y
        :scroll-top="scrollTop"
        @scroll="onScrollViewScroll">
</scroll-view>
```
在兼听滚动事件中设置 scrollTop 的值，以达到"双向绑定"变量 `scrollTop` 的值的目的。
```
onScrollViewScroll(e) {
    const d = e.mp.detail;
    this.scrollTop = d.scrollTop;
    console.log("onScrollViewScroll scrolltop:", this.scrollTop);
  }
```
1. 在**微信开发者工具**中体验良好，比如向下滚动时 `scrollTop` 的值都是按期望值变化的，没有发生可察觉的抖动的现象。
```
onScrollViewScroll scrolltop: 1
onScrollViewScroll scrolltop: 1
onScrollViewScroll scrolltop: 4
onScrollViewScroll scrolltop: 6
onScrollViewScroll scrolltop: 10
onScrollViewScroll scrolltop: 12
onScrollViewScroll scrolltop: 16
onScrollViewScroll scrolltop: 18
onScrollViewScroll scrolltop: 22
onScrollViewScroll scrolltop: 25
onScrollViewScroll scrolltop: 29
onScrollViewScroll scrolltop: 30
onScrollViewScroll scrolltop: 32
onScrollViewScroll scrolltop: 33
onScrollViewScroll scrolltop: 33
```
 2. 可是在真机调试(iPhone X iOS 12)中`scrollTop` 的值就不按期望值变化了
![image](https://user-images.githubusercontent.com/902283/46903266-32457900-cf05-11e8-8fbc-4552560f96ab.png)

```
onScrollViewScroll scrolltop: 1
onScrollViewScroll scrolltop: 7
onScrollViewScroll scrolltop: 16
onScrollViewScroll scrolltop: 25
onScrollViewScroll scrolltop: 32
onScrollViewScroll scrolltop: 39
onScrollViewScroll scrolltop: 47
onScrollViewScroll scrolltop: 54
onScrollViewScroll scrolltop: 60
onScrollViewScroll scrolltop: 66
onScrollViewScroll scrolltop: 71
onScrollViewScroll scrolltop: 74
onScrollViewScroll scrolltop: 76
onScrollViewScroll scrolltop: 77
onScrollViewScroll scrolltop: 79
onScrollViewScroll scrolltop: 81
onScrollViewScroll scrolltop: 0 // scroll-view 滑到了顶部
onScrollViewScroll scrolltop: 81  // scroll-view 滑到了期望的位置
onScrollViewScroll scrolltop: 0  // scroll-view 滑到了顶部
onScrollViewScroll scrolltop: 0 // scroll-view 滑到了顶部
```
3. 在真机预览中就发发生明显的抖动现象，体验结果和真机调试的又不一样。
![image](https://user-images.githubusercontent.com/902283/46903262-15a94100-cf05-11e8-830f-6fe85b223a3a.png) 

看到这个问题 Closed 了，请问 @Rem486 是解决了这个问题吗？
是我使用的姿势不正确吗？请指点一二，十分感谢。
