### ISSUE TITLE
我目前想实现一个路由功能 但是组件中的render在返回了jsx语法片段以后 不渲染

### ISSUE THREAD

**Issue by heroofchina** [Meituan-Dianping/mpvue#92]

**Comment by heroofchina** [comment]
我的实现思路是这样的
1.初始化一个路由stack，并将依赖的组件注入
2.router-view组件核心是通过jsx进行页面渲染 也就是加载组件（之所以不考虑小程序原有的navigator是因为如果针对一些复杂情况的navigator并不满足）
3.但是在最后一步 使用render渲染组件时候，无法支持动态加载的jsx

**Comment by anchengjian** [comment]
由于 wxml 限制，mpvue 会把 .vue SFC 中的 template 部分编译成 wxml 供渲染使用，所以，不能支持自定义 render。
