### ISSUE TITLE
看到官网的更新日志8月10号发布了 mpvue-loader@1.1.2，现在是否可以支持分包，需要做哪些调整？

### ISSUE THREAD

**Issue by Leeehuixian** [Meituan-Dianping/mpvue#922]

**Comment by aOrz** [comment]
http://mpvue.com/change-log/2018.7.24/

**Comment by Leeehuixian** [comment]
已经按照#672中的配置修改了相关文件，打包后，开发者工具报错：subPackages[0].root 字段需为 目录，现将我的项目目录结构截图，求指正错误：
![image](https://user-images.githubusercontent.com/17973371/44656597-09882380-aa2c-11e8-8ad4-efe8abd51e47.png)

`
//main.json
{
  "pages": [
    "pages/homePage/main",
    "pages/informationIntroduction/main",
    "pages/projectList/main",
    "pages/paymentMethod/main",
    "pages/ordeSubmission/main",
    "pages/my/main",
    "pages/myCollection/main",
    "pages/myOrder/main",
    "pages/myCoupon/main",
    "pages/myShippingAddress/main",
    "pages/personalInformation/main",
    "pages/voucherCenter/main",
    "pages/payAttentionPublicNumber/main",
    "pages/viewConsumptionCode/main",
    "pages/orderDetails/main",
    "pages/addRreceivingAddress/main",
    "pages/modifyAddress/main"

  ],
  "subPackages": [
    {
      "root":"memberCenter",
      "pages":[
        "pages/memberCenter",
        "pages/registeredMember/main",
        "pages/bindingMembershipCard/main",
        "pages/membershipCardDetails/main",
        "pages/myMembershipCard/main",
        "pages/purchaseHistory/main",
        "pages/purchaseSecondaryCard/main",
        "pages/recharge/main",
        "pages/electronicCard/main",
        "pages/confirmationOrder/main"
      ]
    },
    {
      "root":"integralMall",
      "pages":[
        "pages/integralMall/main",
        "pages/integralRule/main",
        "pages/membershipCardIntegralDetail/main",
        "pages/signIn/main",
        "pages/detailsExchangeGoods/main",
        "pages/integralSelectedUse/main",
        "pages/recordExchange/main"
      ]
    },
    {
      "root":"selfHelpOrder",
      "pages":[
        "pages/selfHelpOrder/main",
        "pages/selfHelpPointDetails/main",
        "pages/admissionInformation/main",
        "pages/bindHand/main",
        "pages/electronicHand/main",
        "pages/pointSingleBindingHand/main",
        "pages/bindHandSuccess/main",
        "pages/selfCheckout/main",
        "pages/selfCheckoutPay/main",
        "pages/selfCheckoutAfter/main",
        "pages/outCard/main",
        "pages/micropoint/main",
        "pages/paymentDetial/main"
      ]
    }
  ],
  "window": {
    "backgroundTextStyle": "white",
    "navigationBarBackgroundColor": "#f3f5f9",
    "navigationBarTitleText": "首页",
    "navigationBarTextStyle": "black",
    "enablePullDownRefresh": true
  },
  "tabBar": {
    "color": "#666666",
    "selectedColor": "#5a90fc",
    "borderStyle": "white",
    "backgroundColor": "#fff",
    "list": [
      {
        "text": "商城",
        "pagePath": "pages/homePage/main",
        "iconPath": "/static/images/homeBefore.png",
        "selectedIconPath": "/static/images/homeAfter.png"
      },
      {
        "text": "个人中心",
        "pagePath": "pages/my/main",
        "iconPath": "static/images/shopBefore.png",
        "selectedIconPath": "static/images/shopAfter.png"
      }
    ]
  }
}`

**Comment by Leeehuixian** [comment]
@aOrz

**Comment by zxzhgk** [comment]
我也是，mpvue-loader@1.1.2已经是最新版，但是分包后报错VM621:2 未找到 subPackages[0] 中的定义的 pages "subpageA/pages/abc/main" 对应的 WXML 文件
未找到 subPackages[0] 中的定义的 pages "subpageA/pages/abc/main" 对应的 JS 文件

**Comment by magicLaLa** [comment]
最新的把app.json 单独放到了 src下，那新增的页面路径会自动填充到 app.json下的pages里面不？我通过vue init mpvue/mpvue-quickstart my-project 初始化一个模板后，我新增了一个页面文件，重新npm run dev 之后，发现 dist 里面的 app.json 没有把我新增的页面路径添加到 pages里边

**Comment by qinghua5453** [comment]
我是更奇怪，虽然我引入了mpvue-entry 这个库，但实现分片逻辑应该跟不引入这个库类似， 出现这个报错。pages pages/index 不应该在分包 subPackages[0] 中。我的小程序主页pages/index这个文件是不分片打包的，其他页面都准备采用分片打包的形式。

**Comment by qinghua5453** [comment]
也出现了这样的报错 subPackages[0].root 字段需为 目录

**Comment by wpbestway** [comment]
同样
`未找到 subPackages[0] 中的定义的 pages "packageA/pages/college/main" 对应的 WXML 文件`
难道现在没有人维护了吗

**Comment by F-loat** [comment]
> pages/index 不应该在分包 subPackages[0] 中

这个是分包配置的问题，小程序限制分包的根目录不能和主包一致
