### ISSUE TITLE
能否在index.html引入cdn的css样式文件

### ISSUE THREAD

**Issue by xxxsimons** [Meituan-Dianping/mpvue#923]
# [问题简单描述]
想使用iconfont的font-class图标，但是通过在index.html页面引入，发现不起作用，下载到本地是可以的。
```
// index.html
<link rel="stylesheet" href="https://at.alicdn.com/t/font_802177_1s4xda8it7n.css">

// 不生效，但是下载css到本地是有效的
<i class="iconfont icon-plus"></i>
```

请问有什么办法解决吗？

**Comment by KamiJam** [comment]
好像你更改一次iconfont资源包括添加图标这个地址是会变的，你至少要保证地址不变才能这样用吧

**Comment by xxxsimons** [comment]
这个我知道，主要是<link/>引入都无效，我看了network请求，压根没有。我在想是不是不支持CDN引入 @KamiJam

**Comment by zxzhgk** [comment]
这个得看看是不是微信小程序本身支不支持了吧，跟mpvue  感觉关系不大

**Comment by xxxsimons** [comment]
应该是小程序不支持了 @zxzhgk

**Comment by qinghua5453** [comment]
index.html 不管是本地引入还是cdn引入都没效，建议在main.js中本地引入他们。

**Comment by aOrz** [comment]
微信小程序限制，无法支持

**Comment by Javebean** [comment]
@qinghua5453 请问在main.js中本地如何引入他们?
