### ISSUE TITLE
数据刷新问题

### ISSUE THREAD

**Issue by zhangweia** [Meituan-Dianping/mpvue#927]
# [问题简单描述]
    从A产品列表页面点击进入B详情页面，B页面接口获取列表数据保存到data定义的数组里面，返回到A页面，关闭网络，进入到另外一个产品的B详情页面，这个时候显示的是上一个详情页面的数据

**期望的表现:**
  按道理从B页面返回到A页面的时候，B页面data里面定义的数据应该清空了，目前发现是缓存了，这样我需要每次在onUnload中去清理数据，非常麻烦。

[在这里描述期望的表现]

**观察到的表现:**

[在这里描述观察到的表现]

**屏幕截图和动态 GIF 图**

![复现步骤的屏幕截图和动态 GIF 图](图片的 url)

**Comment by chenxi2008** [comment]
我这边每次都是页面关闭的时候清掉数据...

**Comment by aOrz** [comment]
https://github.com/Meituan-Dianping/mpvue/issues/300
