### ISSUE TITLE
pages下面的main.js的config分包之后一定要分离出来放在main.json里面吗？

### ISSUE THREAD

**Issue by Kellercai** [Meituan-Dianping/mpvue#929]
# pages下面的config之前是放在main.js里面的，分包之后一定要分离出来放在main.json里面吗？

![image](https://user-images.githubusercontent.com/20681598/44509483-627e5180-a6e4-11e8-9d01-1e14999b7e65.png)

**期望的表现:**

在之前版本的pages下页面main.js中在分包之后也可以使用，而不是重新在写一个main.json

**Comment by aOrz** [comment]
http://mpvue.com/change-log/2018.7.24/

**Comment by aOrz** [comment]
@Kellercai 放在各自的页面下就好了

**Comment by Jam1zhu** [comment]
突然就觉得文件多了很多。。。原来的模式舒服
