### ISSUE TITLE
引入weui.css模拟器报错，必须删除含‘~’符号的样式

### ISSUE THREAD

**Issue by danielzy301** [Meituan-Dianping/mpvue#930]
# 引入weui.css模拟器报错，必须删除含‘~’符号的样式

**问题复现步骤:**

1. https://github.com/Tencent/weui/wiki/getting-started下载weui.css
2. 编译成功
3. 微信模拟器报错：提示‘~’异常

**期望的表现:**

支持weui.css

**Comment by vitozyf** [comment]
有三四处地方，注释掉吧

**Comment by aOrz** [comment]
微信小程序不支持 ~
