### ISSUE TITLE
希望打包后dist不保持开发时的文件结构

### ISSUE THREAD

**Issue by edenYfb** [Meituan-Dianping/mpvue#932]
# [问题简单描述]
最近用小程序原生语言写了个helloword，快开发完了，发现网上反编译特别简单
https://blog.csdn.net/qq_33858250/article/details/80543815
社区里官方又不怎么顶事，比如
https://developers.weixin.qq.com/community/develop/doc/0006844b710388edc5170222156400?highLine=%25E5%258F%258D%25E7%25BC%2596%25E8%25AF%2591
https://developers.weixin.qq.com/community/develop/doc/0000e2ef3b0a30dcafb6ecd6151000?highLine=%25E5%258F%258D%25E7%25BC%2596%25E8%25AF%2591
把我吓到了，准备用mpvue重写build后至少看起来比较麻烦，希望mpvue能提供配置，让打包后的文件结构可以不保持开发时的结构，最好能揉在一起。
分包机制 2018.7.23+  http://mpvue.com/mpvue/quickstart/#4-2018723
**问题复现步骤:**

1. [第一步]
2. [第二步]
3. [其他步骤...]

**期望的表现:**

[在这里描述期望的表现]

**观察到的表现:**

[在这里描述观察到的表现]

**屏幕截图和动态 GIF 图**

![复现步骤的屏幕截图和动态 GIF 图](图片的 url)

**Comment by aOrz** [comment]
mpvue  build 之后会被 uglifyjs 压缩，而且经 webpak build 之后的代码很难还原，文件结构只是一个很小的点，混淆文件结构并不能解决根本问题
