### ISSUE TITLE
原生小程序开发 如何引入mpvue

### ISSUE THREAD

**Issue by wfsovereign** [Meituan-Dianping/mpvue#937]
# [问题简单描述]
一个已经使用原生代码开发的小程序，在不改动原代码的情况下如何引入mpvue，使得原生代码与mpvue共行？有人实践过吗

**Comment by jhs1873** [comment]
mpvue-simple了解下。

**Comment by wfsovereign** [comment]
@jhs1873 是的，现在正在尝试这个，不过坑挺多，还有其他工具吗

**Comment by jhs1873** [comment]
@wfsovereign 官网上只有这一种方法。其他的倒是没发现。用mpvue-simple最好是在linux环境下。win环境总是报错。

**Comment by wfsovereign** [comment]
@jhs1873 多谢。最后还是没用mpvue-simple，用的不太顺手，后面用了mpvue-entry实现了想要的功能。不过最后这个需求被砍了...
