### ISSUE TITLE
tabBar.iconPath和tabBar.selectedIconPath的图片是如何处理的？

### ISSUE THREAD

**Issue by youngluo** [Meituan-Dianping/mpvue#94]

**Comment by weineel** [comment]
1. 图片放在`static/images`下
2. 在`src/main.js`中配置就行了。

![image](https://user-images.githubusercontent.com/13328625/37447672-0d8c3a8e-285e-11e8-868c-29dfd5cbf4de.png)

**Comment by youngluo** [comment]
@weineel 感谢

**Comment by wuxiaolan91** [comment]
感谢~

**Comment by sunmydream** [comment]
哇，我被这个问题坑了一下午，试了无数种方案，发现在打包后的文件里一直找不到这个图片，最后自己手动改成static/img里面的文件路径就可以了。。。。
