### ISSUE TITLE
使用微信开发者工具发现部分代码无法打断点

### ISSUE THREAD

**Issue by jytx** [Meituan-Dianping/mpvue#941]
# [问题简单描述]
新创建的一个mpvue项目,尝试打断点时发现文件打断点的时候会出现有些行上无法打断点,或者打了断点之后断点乱跑.
**问题复现步骤:**
vue-cli 版本 v2.9.6

1. [第一步]
创建一个新工程
2. [第二步]
直接在代码上打断点
3. [其他步骤...]

**期望的表现:**
可以正常打断点
[在这里描述期望的表现]

**观察到的表现:**
有些行无法打断点,且打了的断点乱跑
[在这里描述观察到的表现]

**屏幕截图和动态 GIF 图**
![image](https://user-images.githubusercontent.com/9834906/44614313-db042000-a854-11e8-95f4-44a89cb40adf.png)

![复现步骤的屏幕截图和动态 GIF 图](图片的 url)

猜测是source Map 的问题,把webpack.dev.conf.js的devtool完全注释掉,删除dist目录的代码后可以正常打断点。
微信开发者工具的es6转es5已经关闭,但是还是不行,映射还是错误

![image](https://user-images.githubusercontent.com/9834906/44615756-6b9e2880-a874-11e8-8b11-9316e57565fa.png)

**Comment by jytx** [comment]
猜测是source Map 的问题,把webpack.dev.conf.js的devtool完全注释掉,删除dist目录的代码后可以正常打断点。

**Comment by unclexiao** [comment]
这个问题我也遇到了。
1. 之前使用1.0.11的时候，dev时可以看到每个js都有对应的map文件，build生成的是标准的四个文件（js，html，wxml，json）；
2. 现在换1.0.13了，dev时没有map文件了，build后多了**.vue.wxml文件，然后任何await函数都无法打断点，甚至连部分class内方法都无法调试；
3. 尝试修改了webpack的配置，比如：
```js
  dev: {
    env: require('./dev.env'),
    port: 8080,
    // 在小程序开发者工具中不需要自动打开浏览器
    autoOpenBrowser: false,
    assetsSubDirectory: '',
    assetsPublicPath: '/',
    devtool: '#source-map',
    proxyTable: {},
    cssSourceMap: true
  }
```

但是依旧无效，请问如何破？

**Comment by FrankRoc** [comment]
我也遇到了mpvue生成的小程序无法在微信小程序开发工具里面下断点,已经找到了对应的js的对应行,但是一点,莫名的就跳到了index.vue中去?太奇怪了

**Comment by hucq** [comment]
> 我也遇到了mpvue生成的小程序无法在微信小程序开发工具里面下断点,已经找到了对应的js的对应行,但是一点,莫名的就跳到了index.vue中去?太奇怪了

可以先升级一下：mpvue, mpvue-template-compiler 1.0.16, mpvue-loader 1.1.4。
