### ISSUE TITLE
No parser and no filepath given......

### ISSUE THREAD

**Issue by langlangbody** [Meituan-Dianping/mpvue#943]
# [不论是在dev or build 时 都会出现这样的错误]
No parser and no filepath given, using 'babylon' the parser now but this will throw an error in the future. Please specify a parser or a filepath so one can be inferred.

**Comment by yanxiafu** [comment]
npm install prettier@1.12.1 --save-dev  降级prettier解决了

**Comment by Michel-Yang** [comment]
解决了。感谢
