### ISSUE TITLE
click后拿不到target对应元素里面的内容

### ISSUE THREAD

**Issue by qinghua5453** [Meituan-Dianping/mpvue#945]
# [click后拿不到target对应元素里面的内容]

**问题复现步骤:**

1. 比如`<td @click="test">1</td>`
2. 调用test的时候，打印出来e，无法拿到1的值。不管是target还是detail里面都没有。
3. 另外绑定比如:disabled ="disabled"也不起效果

**Comment by qinghua5453** [comment]
看见mpvue中有在事件一栏 说了这么一句话，暂不支持在组件引用时，在组件上定义 click 等原生事件
那你们再点击事件想要获取dom元素里面的值，是怎么获取的啊

**Comment by qinghua5453** [comment]
好吧，原来需要传值进去，单纯的原生获取e里面的值获取不到，get到了

**Comment by nosizi** [comment]
@qinghua5453 请问传什么值呢？我今天学习mpvue也遇到了@click事件无法取target的value，打印的event中target并没有value

**Comment by aOrz** [comment]
可以看下小程序的事件，是拿不到 取dom元素值的

**Comment by nosizi** [comment]
@aOrz 嗯嗯，已经了解到了，我目前的做法是设置自定义属性
