### ISSUE TITLE
深拷贝无效？

### ISSUE THREAD

**Issue by qinghua5453** [Meituan-Dianping/mpvue#946]
# [深拷贝无效？]

**问题复现步骤:**

不管是数组的concat 还是对象的JSON.parse(JSON.stringify(obj))均无法实现，感觉实现的就是浅复制啊。

**Comment by lichenabson** [comment]
深拷贝是可以的,我没遇到深拷贝失效的问题

**Comment by qinghua5453** [comment]
@lichenabson 这样啊 ，那估计是我用的姿势不对了。哎。再看看我

**Comment by zaxlct** [comment]
深拷贝无效你在这里发 issues 干啥。。。

**Comment by qinghua5453** [comment]
@zaxlct 我能说 是我在小程序 环境吗？再说 你不回答就好了啊，奇怪

**Comment by zaxlct** [comment]
就是想吐槽无意义的 issues

**Comment by hughfenghen** [comment]
想吐槽无意义的 issues
