### ISSUE TITLE
无法正常导入组件

### ISSUE THREAD

**Issue by haoxinjieFE** [Meituan-Dianping/mpvue#951]
![image](https://user-images.githubusercontent.com/42566011/44653227-b9f02a80-aa20-11e8-95b5-685715a80e79.png)
![image](https://user-images.githubusercontent.com/42566011/44653290-e7d56f00-aa20-11e8-9272-1e8ee0590fb3.png)
![image](https://user-images.githubusercontent.com/42566011/44653296-edcb5000-aa20-11e8-85f2-275798aadf8f.png)
![image](https://user-images.githubusercontent.com/42566011/44653318-fae83f00-aa20-11e8-9b8d-93aafe848169.png)
![image](https://user-images.githubusercontent.com/42566011/44653324-fe7bc600-aa20-11e8-9d88-13c3f1322ad5.png)

我尝试写新的组件导入 index.vue 中，但是发现当组件叫 nav/menu/... .vue 的时候会抛出上图错误，但是改为 list/NavMenu... 之类的就不会报错。

**Comment by aOrz** [comment]
有部分保留命名 http://mpvue.com/qa/
