### ISSUE TITLE
引入两个第三方插件 第二个插件会报错: Cannot read property 'version' of undefined

### ISSUE THREAD

**Issue by GongJS** [Meituan-Dianping/mpvue#952]
# [问题简单描述]

**问题复现步骤:**

1.单独引入两个第三方插件的其中一个都不会报错，但是如果两个一起引入，后引入都那个第三方插件就会报错
2.报错代码:Cannot read property 'version' of undefined

**期望的表现:**

难道mpvue不支持引入多个第三方插件嘛？

**观察到的表现:**

**屏幕截图和动态 GIF 图**

![复现步骤的屏幕截图和动态 GIF 图](图片的 url)

**Comment by aOrz** [comment]
信息太少，无法复现，建议完善复现步骤后重新开 issue
