### ISSUE TITLE
新建页面只能是pages/*/main.js吗？

### ISSUE THREAD

**Issue by xiaoxintang** [Meituan-Dianping/mpvue#953]
# [场景描述]
原有的小程序想用mpvue重构，之前扫码进入的页面是/pages/orderFood/orderFood(之前是外包写的)

**期望的表现:**
我想通过重构之后可以生成/pages/orderFood/orderFood而不是/pages/orderFood/main

**本人尝试过的方法:**
1. [方法一]
修改src/main.js的pages选项，添加^pages/orderFood/orderFood
2. [方法二]
修改webpack.base.conf.js
const pagesEntry = getEntry(resolve('./src'), 'pages/**/*.js')

**Comment by jocchoc** [comment]
我和你遇到同样的问题。用最新的框架重构了项目，但是曾经给出去的二维码为pages/home/home
我的解决办法是：
1. 将src目录下的app.json页面配置修改为"pages/home/home"。
2.将pages目录下的home文件夹下的main.js改为home.js
3.修改webpack.base.conf.js。如你所示，将你看到的'/pages/**/main.js'改为'/pages/**/*.js'

**Comment by javanf** [comment]
请教，为什么，config的配置没有生效了？
path: 'pages/user/register',
  config: {
    navigationBarTitleText: '文章详情'
  }

**Comment by xiaoxintang** [comment]
抱歉，方法一和方法二需要同时使用，因为涉及到首页。谢谢各位。至于三楼，只能抱歉了，我是新手

**Comment by xiaoxintang** [comment]
好像还是不行。。。应该是可以使用index.js,换别的名字好像不行
` WARNING  Compiled with 1 warnings11:57:21

 warning  in ./src/pages/orderFood/orderFood.js

3:18-21 "export 'default' (imported as 'App') was not found in './orderFood'
`

**Comment by F-loat** [comment]
最新版 mpvue-entry 可以随意定义路由了

**Comment by xiaoxintang** [comment]
哈哈，原谅我个小菜鸡，自编自导自演了，orderFood.js里import *.vue文件的时候写错了名字：应该是App.vue的我给写成了orderFood
