### ISSUE TITLE
下拉刷新时页面移动方向异常

### ISSUE THREAD

**Issue by kelrvins** [Meituan-Dianping/mpvue#961]
# 下拉刷新时页面上升，刷新完成后下降
下拉刷新时，页面上弹又下来，mpvue github 首页上推荐的使用 mpvue 项目除了 sina 财经的项目都有这个问题，目前只在iPhone8, ios12上发现，微信版本6.7.2。

**问题复现步骤:**

1. [第一步]
使用 mpvue github 首页的《使用mpvue的项目》做演示：
“享物说”，“地铁公交车来了”

2. [第二步]
“享物说” 首页下拉刷新，“地铁公交车来了” 第二页和第三页下拉刷新。

**期望的表现:**
下拉刷新时屏幕顶部正常显示加载的三个点点，整体页面下降。

**观察到的表现:**
下拉刷新时整体页面上升，刷新完成后下降。

**屏幕截图和动态 GIF 图**

- http://pba4wd618.bkt.clouddn.com/456.gif
- http://pba4wd618.bkt.clouddn.com/123.gif

![地铁公交车来了](http://pba4wd618.bkt.clouddn.com/456.gif)
![享物说](http://pba4wd618.bkt.clouddn.com/123.gif)

**Comment by LeeHarlan** [comment]
我项目里面也出现了这个问题，目前没解决。应该是微信官方的问题[onPullDownRefresh包含showLoading代码会bug](https://developers.weixin.qq.com/community/develop/doc/0006ca373480280ece17e4e2e56c00?highLine=%25E4%25B8%258B%25E6%258B%2589%25E5%2588%25B7%25E6%2596%25B0Loading)，下拉刷新的三个点跟showLoading有冲突

**Comment by kelrvins** [comment]
解决了，谢谢
