### ISSUE TITLE
怎么设置别的页面的背景颜色，在app.json中设置不了 

### ISSUE THREAD

**Issue by wjf9492** [Meituan-Dianping/mpvue#962]

**Comment by leanTim** [comment]
什么意思？ 在页面的css里设置不行吗

**Comment by wjf9492** [comment]
就是除了 首页，想在别的页面的设置不同的背景色，好像设置不成功

**Comment by wjf9492** [comment]
@leanTim

**Comment by leanTim** [comment]
怎么设置的 代码贴出来看看

**Comment by zyz13071059219** [comment]
你可以在那个页面目录下添加一个json，就跟原生的小程序一样的用法

**Comment by gechen186** [comment]
自己解决了，pages下的*.json，应改名为main.json

**Comment by wjf9492** [comment]
@leanTim 
![Uploading 1535956000644.jpg…]()

**Comment by wjf9492** [comment]
@leanTim 
![image](https://user-images.githubusercontent.com/24648326/44970676-79932e00-af85-11e8-9b57-53ac5376b7d9.png)

**Comment by wjf9492** [comment]
@blackerer 我设置了 好像也不行，你有试过么？求代码
![1535956156840](https://user-images.githubusercontent.com/24648326/44970777-c414aa80-af85-11e8-94e6-bbca475c23b3.jpg)

**Comment by blackerer** [comment]
@wjf9492 
http://mpvue.com/build/mpvue-loader/
文档上说mpvue-loader的版本为1.1.1以上时，跟原声的小程序一样的配置方法，你吧你的config还有花括号去掉就行了，只留配置项

**Comment by wjf9492** [comment]
@blackerer 你说的是指在那个页面目录下添加的json里面么？

**Comment by wjf9492** [comment]
@blackerer 好了， 我明白了 谢谢
![image](https://user-images.githubusercontent.com/24648326/44971517-7483ae00-af88-11e8-9f4d-adf8dec4a121.png)

**Comment by blackerer** [comment]
@wjf9492 
是的，你要单独配置一个页面的话，就在那个页面的main.json中直接写配置项就行了，跟原生的一样

**Comment by wjf9492** [comment]
好的， 谢谢，mpvue 坑不少，继续跳坑

**Comment by forMine** [comment]
改动有点多~~
