### ISSUE TITLE
npm run build 后，上传代码到小程序，作为体验版，扫一扫二维码无法直接进去到首页。

### ISSUE THREAD

**Issue by qinghua5453** [Meituan-Dianping/mpvue#963]
# [npm run build 后，上传代码到小程序，作为体验版，扫一扫二维码无法直接进去到首页。]

**问题复现步骤:**

1. [npm run build]
2. [上传到小程序服务器]
3. [扫一扫体验版二维码]
4. [无法出现首页，只能点击右上角，再点击返回首页才能加载首页]

**期望的表现:**

[扫一扫二维码直接能访问首页]

npm run build后 有这个提示：

 Tip: built files are meant to be served over an HTTP server.
  Opening index.html over file:// won't work.
大致能理解什么意思。
npm run build后是不是只有发布审核以后，才能正式访问到首页

**Comment by monw3c** [comment]
一样发现这个问题，有这个疑问，请官方解释下谢谢
