### ISSUE TITLE
服务直达如何集成在小程序里，之前原生小程序只用在根目录加上searchWidget即可

### ISSUE THREAD

**Issue by wpbestway** [Meituan-Dianping/mpvue#965]
# [问题简单描述]
微信的服务直达，需要以插件的形式使用，在根目录上直接创建searchWidget目录，便可写上相应的页面，但是mpvue似乎并没有考虑这种情况

问题复现请看截图

**期望的表现:**

能正确加载或编译服务直达的相关内容，即根目录下的searchWidget插件；

以下是原生编译的：
![image](https://user-images.githubusercontent.com/21271890/44888031-af27e500-ad01-11e8-94a6-2eeda7f6711b.png)

以下是mpvue的：
![image](https://user-images.githubusercontent.com/21271890/44888072-d67eb200-ad01-11e8-83d8-3a27f3281ad2.png)
注意打包后的dist文件夹下没有searchWidget

![复现步骤的屏幕截图和动态 GIF 图](图片的 url)

**Comment by hucq** [comment]
这个配置项小程序官网上没有找到，mpvue 确实没有支持，建议你调整一下webpack构建脚本。
实在要简单处理，你放到src目录，构建完了再拷贝出来也行。
