### ISSUE TITLE
关于页面越来越卡的问题

### ISSUE THREAD

**Issue by lichenabson** [Meituan-Dianping/mpvue#966]
如#694  

**问题复现步骤:**
1. [第一步]
不停的进入退出一个页面的话,会发现这个页面数据渲染越来越慢, debug得知
![image](https://user-images.githubusercontent.com/20200267/44892068-624e0980-ad15-11e8-8b8d-acd5c9660bf0.png)
Vue$3.prototype.$updateDataToMP这个函数在被递增式调用,所以当页面数据复杂,或者是客户端手机性能跟不上的时候就会感觉越来越卡顿
2. [第二步]
继续debug可以看到

watch 观察者并没有被清空
![image](https://user-images.githubusercontent.com/20200267/44892159-c53fa080-ad15-11e8-8c59-df95f300e8a1.png)
看到源码中每次new Watcher的时候,都在新增观察者,所以不停进入页面的时候 不停的调用所有的watch,数据渲染会越来越慢

**暂时解决方法:**
目前暂时的解决方法,每次进入upload的时候,手动清空_watch
所以页面upload的时候,不只需要清空data数据,也需要清空watch

![image](https://user-images.githubusercontent.com/20200267/44892291-70e8f080-ad16-11e8-83bc-58f7e9746ca2.png)

**Comment by luckyyyyy** [comment]
这个问题非常严重  我就好奇 难道没有人使用过mpvue开发过大型的项目吗？ 
这问题不可能没被发现啊

**Comment by Synaric** [comment]
一个简单的小程序，反复操作半小时就能卡出新世界...目前我们项目把所有watcher替换为$watch方法并手动释放了

**Comment by xmsz** [comment]
@Synaric  请问是如何临时解决的

**Comment by luckyyyyy** [comment]
@Synaric 不需要半小时 我的操作5分钟 掉电速度肉眼可见 最后直接报内存不足

**Comment by wangleigege** [comment]
确实很难受

**Comment by nbhaohao** [comment]
执行了图中的代码后，，第二次进入页面。
原来的 watch 全部失效了，
请问有办法解决吗？

**Comment by lichenabson** [comment]
@nbhaohao 贴份代码看看

**Comment by nbhaohao** [comment]
@lichenabson    第一次进入是正常的表现，然后我退出这个页面，(使用了 wx.redirectTo )再回来的时候，这个页面子组件的 watch 就失效了，麻烦了，感谢。
```
//页面中定义 onUnload 方法, 这个页面同时引用了子组件
  onUnload(){
    if (this.$options.data) {
      Object.assign(this.$data, this.$options.data())
    }
    this._watchers = []
    if (this._watcher && this._watcher.teardown) {
      this._watcher.teardown()
    }
  },
  // 定义了一个子组件
  components: {
    GameRoleList,
  },


//子组件中使用了 watch 方法，同时 onUnload 也执行了与父页面一样的代码

onUnload() {
  ....
}


watch: {
  type() {
    ....
  }
  playerList() {
   ....
  }
}

**Comment by lichenabson** [comment]
@nbhaohao 试一下在你GameRoleList的upload中不做处理,我这边watch是没问题的

**Comment by nbhaohao** [comment]
嗯，在子组件中不做处理是可以的，感谢 @lichenabson

**Comment by Renford** [comment]
@luckyyyyy 我这也出现这种问题了。
操作几分钟，掉电速度很快，手机发热，内存不足。
有解决方案吗？

**Comment by luckyyyyy** [comment]
@Renford 上面不是已经给出方案了么 也可以修改源码

**Comment by SyMind** [comment]
这尼玛就自动关闭了该issue，真的骚。

**Comment by jsydliuqing** [comment]
在 src/main.js 中添加如下代码，即可解决数据会保留的问题。
`Vue.mixin({
  // 记录页面回退的日志
  onUnload: function() {
    // Fixbug: 再次进入页面时，页面还保留上一次的旧数据（预期是清空数据）
    if (this.$options.data) {
      Object.assign(this.$data, this.$options.data());
    }

    // Fixbug-Watcher: 关闭页面时 Watcher 没有被取消订阅，再次进入页面会出现重复订阅的情况
    let watcherId = -1;
    if (this._watcher) {
      watcherId = this._watcher.id;
      this._watcher.teardown();
    }
    let i = this._watchers.length;
    while (i--) {
      if (this._watchers[i].id === watcherId) {
        this._watchers[i].teardown();
      }
    }
  }
});`

**Comment by jsydliuqing** [comment]
解决缓存和Watcher不断增加的问题，可以用上面的方式。

卡顿的问题，我这里发现是开启了debug模式。 如果不开debug模式，不会越来越卡。 你们如果发现卡顿，可以把debug模式关掉试试。
