### ISSUE TITLE
picker组件完成的二级联动，用到了$set更新视图，数据多时，更新缓慢

### ISSUE THREAD

**Issue by realzy** [Meituan-Dianping/mpvue#968]
小程序自带的picker组件完成的二级联动，用到了$set更新视图，在手机上，数据多时，第一列变了，第二列会延迟一两秒才会更新数据。怎么处理这种情况
![1](https://user-images.githubusercontent.com/17307019/44898823-98e64d00-ad32-11e8-8702-3a857969e288.gif)

**Comment by KuangPF** [comment]
不知道你二级联动的数据结构是怎样。我测试过一下，如果将二级联动的所有数据放在一个数组里面，当数据量比较大的时候更新是很慢，然后我改变了数据结构，每一列都对应一个数组，当 picker 的 value 改变的时候直接将每列的数据对应更新下就好了，这样目前测试没有明显的卡顿现象。
[mpvue-citypicker](https://github.com/MPComponent/mpvue-citypicker)就是这样实现的，不知道对你有没有帮助。

**Comment by realzy** [comment]
非常感谢，我试试这个办法
