### ISSUE TITLE
单独设置navigationBarBackgroundColor的问题

### ISSUE THREAD

**Issue by SandZn** [Meituan-Dianping/mpvue#97]
试过组件js里的config可以单独设置“navigationBarTitleText”，但是“navigationBarBackgroundColor”却是不生效的，想问下如何给每个页面设置单独的navigationBarBackgroundColor呢？

**Comment by aOrz** [comment]
每个页面的 main.js 都可以 export 一个页面 config

**Comment by SandZn** [comment]
我知道了，是因为不支持"#ccc"这种简写，换成"#cccccc"就可以了

**Comment by KuangPF** [comment]
每个页面的 `main.js`下面不写 `window` 就可以 @SandZn 
![zdy](https://user-images.githubusercontent.com/20694238/37444441-8be57542-284c-11e8-8cc0-5a535157e44f.png)

**Comment by SandZn** [comment]
是的，多写一层window所以没生效。
并且一旦写了window层，就算在外层也写了，依然不会生效。

**Comment by anchengjian** [comment]
目前只支持把 export default 中的 config 字段对应的对象打包成 app.json 或者 page.json
