### ISSUE TITLE
原小程序项目和mpvue项目如何共存

### ISSUE THREAD

**Issue by QzhouZ** [Meituan-Dianping/mpvue#970]
# 场景说明
小程序项目已经开发了很多页面了，打算新页面用mpvue来写，老的项目打算不动，那如何进行共存，老项目的app.js和mpvue的app.js还是有点差别，如果用mpvue-simple，如何进行热更新配置？

**Comment by wangchenxunum** [comment]
你只管复制.vue和main.js编译产生的文件和其他单独单的脚步和资源到你的老项目对应目录就行吧

**Comment by hucq** [comment]
简单来说，构建策略分开，只是最终构建出来的目标文件目录整合在一起而已。
你也可以把各自的构建策略通过webpack 或者 scripts 命令集成在一起。

**Comment by QzhouZ** [comment]
好的，谢谢了

**Comment by superSheng11** [comment]
请问怎么用mpvue-simple？能给个demo吗？我这边跑起来一直报错...
