### ISSUE TITLE
这个项目还活着吗？好久都没有更新

### ISSUE THREAD

**Issue by TonyLuo** [Meituan-Dianping/mpvue#973]
# [问题简单描述]

**问题复现步骤:**

1. [第一步]
2. [第二步]
3. [其他步骤...]

**期望的表现:**

[在这里描述期望的表现]

**观察到的表现:**

[在这里描述观察到的表现]

**屏幕截图和动态 GIF 图**

![复现步骤的屏幕截图和动态 GIF 图](图片的 url)

**Comment by luckyyyyy** [comment]
fork了一个自己改呗，坑是多了点，但是总要有人填。

**Comment by julyL** [comment]
如果作者不是再憋大招的话，那差不多是gege了

**Comment by YaoaY** [comment]
GG........

**Comment by julyL** [comment]
应该是加薪了，然后就....

**Comment by TonyLuo** [comment]
隔壁的wepy和Taro更新都很频繁，这个项目两个月都没有动静......

**Comment by zxzhgk** [comment]
他们在修改测试分支，切到测试分支看看，最新修改是两天前

**Comment by DreamPWJ** [comment]
大家散了吧  mpvue项目更新太不重视了  坑好多  看来赚了人气就行了也没动力了

**Comment by TonyLuo** [comment]
大家要慎重是否选择mpvue，已经三个月都没有版本发布了....

**Comment by luckyyyyy** [comment]
正在迁移到 Taro

**Comment by TonyLuo** [comment]
官方是不是应该回应下进展？ @aOrz

**Comment by LeeHarlan** [comment]
项目小，仍然还在坚持中还没弃坑...

**Comment by haoxinjieFE** [comment]
@aOrz

**Comment by aOrz** [comment]
负责项目的同学没有跑路，由于工作压力比较大，我们投入的时间比较少，我们会尽量协调时间来维护项目，感谢大家的理解。
