### ISSUE TITLE
初始安装mpvue失败

### ISSUE THREAD

**Issue by lamb2014** [Meituan-Dianping/mpvue#974]
# [问题简单描述]
按官网初始化安装出现下面的错误，node版本：8.11.4 npm:6.4.1  vue-cli:2.9.3
vue-cli · Failed to download repo mpvue/mpvue-quickstart: self signed certificate in certificate chain
1. [第一步]
npm i vue-cli@2.9.3 -g(按很多网友说的改成这个版本也不行)
2. [第二步]
vue init mpvue/mpvue-quickstart my-project
3. [其他步骤...]
nrm use taobao(切换淘宝源也不行）
**期望的表现:**
能成功初始化一个mpvue项目
**观察到的表现:**
vue-cli · Failed to download repo mpvue/mpvue-quickstart: self signed certificate in certificate chain

**Comment by aOrz** [comment]
这是从 github 上下载 template 失败，注意科学上网

**Comment by 12215380** [comment]
请问你解决了吗？
