### ISSUE TITLE
使用自定义组件命名为tabBar，会跟原生tabBar组件发生冲突

### ISSUE THREAD

**Issue by jgchenu** [Meituan-Dianping/mpvue#975]
情况描述：
使用自定义组件命名为tabBar，会跟原生小程序tabBar组件发生冲突，导致出现的后果是
1：可以正常显示自定义组件样式布局
2：不会触发自定义组件tabBar组件生命周期事件，不会挂载点击等事件。

问题解决方法：
将tabBar命名改为其他命名如：tabMenu等

**Comment by lichenabson** [comment]
发issue之前请先看文档
![image](https://user-images.githubusercontent.com/20200267/44963423-f5c54b80-af5c-11e8-85db-33966df1b485.png)
