### ISSUE TITLE
mpvue配置echars报错？

### ISSUE THREAD

**Issue by syyzz3** [Meituan-Dianping/mpvue#976]
![2345 20180901172450](https://user-images.githubusercontent.com/11385973/44951032-a105d000-ae8b-11e8-97ba-aef91f12d46a.jpg)
![2345 20180901172529](https://user-images.githubusercontent.com/11385973/44951033-a105d000-ae8b-11e8-8f27-69adec5c950c.jpg)
根据官网示例一步一步配置

https://github.com/mpvue/examples/tree/master/echarts
最后执行报ec-canvas文件没有找到，但是我明明在static目录下有这个文件？
最后我干脆把官网示例沾过来还是报这样的错？

**Comment by zhllucky** [comment]
你怎么解决的呀。我这里碰到了同样的问题
