### ISSUE TITLE
期望支持 webpack 4 编译

### ISSUE THREAD

**Issue by thewei** [Meituan-Dianping/mpvue#98]
目前测试mpvue-loader、mpvue-webpack-target不支持 webpack4，期望能够支持 webpack 4 编译

**Comment by aOrz** [comment]
已经列入进程了，因为有更多更紧急的工作要做，所以优先级不是很高，issue 同 #61 ,我先关了

**Comment by xmsz** [comment]
为啥还没支持！

**Comment by zdmission** [comment]
希望能早日支持webpack4.x
