### ISSUE TITLE
module "pages/**/main.js" is not defined 

### ISSUE THREAD

**Issue by Vultur** [Meituan-Dianping/mpvue#982]
# [问题简单描述]
module "pages/**/main.js" is not defined 
**问题复现步骤:**
async created () {
  await foo()
}
1. [第一步]
2. [第二步]
3. [其他步骤...]

**期望的表现:**

[在这里描述期望的表现]

**观察到的表现:**
不使用 async/await 正常
[在这里描述观察到的表现]

**屏幕截图和动态 GIF 图**

![复现步骤的屏幕截图和动态 GIF 图](图片的 url)

**Comment by wangchenxunum** [comment]
因为babel的原因：
1.你需要在页面中顶部导入babel-runtime/regenerator
2.如果用require方式导入的，全局async函数不能采用定义的方式，只能采用以下方式：const func = async functio func(){}
