### ISSUE TITLE
急急急，即将完成的mpvue小程序项目，如何分包？

### ISSUE THREAD

**Issue by MrMrZ** [Meituan-Dianping/mpvue#983]
# [问题简单描述]
我们的项目是是使用mpvue开发的，现在小程序快开发完了，但是    启动的时候太慢了，想要进行分包处理，目前使用了http://www.cnblogs.com/imgss/p/9478628.html这个链接进行测试，修改配置文件，但是在npm run dev的时候出现了问题--->VM2211:2 subPackages[0].root 字段需为 目录，目前不知道什么原因，求大神指教,
**问题复现步骤:**

1. [第一步]
2. [第二步]
3. [其他步骤...]

**期望的表现:**

[在这里描述期望的表现]

**观察到的表现:**

[在这里描述观察到的表现]

**屏幕截图和动态 GIF 图**

![复现步骤的屏幕截图和动态 GIF 图](图片的 url)
![image](https://user-images.githubusercontent.com/28997356/44970675-78fa9780-af85-11e8-80ca-c1d6611ea847.png)
![image](https://user-images.githubusercontent.com/28997356/44970691-7ef07880-af85-11e8-9b02-9e66d047ffd3.png)

**Comment by MrMrZ** [comment]
![image](https://user-images.githubusercontent.com/28997356/44970735-aba49000-af85-11e8-95cd-694e6c9dc030.png)
这是项目里面的main.json文件内容

**Comment by cduyzh** [comment]
https://github.com/cduyzh/mp_webpack 可以看下我的解决方案呢

**Comment by MrMrZ** [comment]
@cduyzh 可以加个联系方式不，之后有问题可以请教大佬，这是我的qq:1519025391

**Comment by flyfox11** [comment]
@cduyzh 你写的哪有分包，骗人！！！

**Comment by flyfox11** [comment]
@MrMrZ 我已经解决了，你写的路径不对

**Comment by MrMrZ** [comment]
@flyfox11 可以加个联系方式不，QQ1519025391，想详细了解请教一下

**Comment by flyfox11** [comment]
@MrMrZ 你的加不上，需要回答问题，加我的吧，qq2474016183

**Comment by flyfox11** [comment]
@cduyzh 也不知道谁搞笑，你懂啥叫分包吗

**Comment by flyfox11** [comment]
@cduyzh 也不知道谁搞笑，你懂啥叫小程序分包吗，不懂自己好好学学再出来说

**Comment by aOrz** [comment]
看下官方的分包文档
