### ISSUE TITLE
我有个需求是先渲染变量，再转小程序

### ISSUE THREAD

**Issue by 836438020** [Meituan-Dianping/mpvue#987]
# [问题简单描述]

`<i-notice-bar i-class="notice" icon="systemprompt" loop>
      {{content}}
    </i-notice-bar>`
比如这种情况
我想mpvue先把content的结果显示出来
`<i-notice-bar i-class="notice" icon="systemprompt" loop>
      这是content渲染出来的值
    </i-notice-bar>`
请问这样如何做

**Comment by icksky** [comment]
这种应该是打包过程的问题, 不知道有没有相关 `webpack` 的插件, 可以试试修改 `/build/build.js`, 读取并修改你变量所在文件.

**Comment by hucq** [comment]
你这个变量是运行期的数据？那是做不到的。如果是构建期的数据，那没必要用这种方案。
