### ISSUE TITLE
scroll-view中v-for循环的文字内容不显示

### ISSUE THREAD

**Issue by gaoyangbuzai** [Meituan-Dianping/mpvue#988]
# [问题简单描述]
scroll-view内循环列表，可横向滑动显示
**问题复现步骤:**
在scroll-view中v-for循环列表，
 <scroll-view class="aaa" scroll-x>
            <view class="bbb" v-for="(item,index) in list" :key="index">{{item.channel_name}}</view>
        </scroll-view>
[在这里描述期望的表现]
          显示可横向滑动的列表
**观察到的表现:**
          wxml中的结构显示正常，但是页面上未显示出文字
[在这里描述观察到的表现]

**屏幕截图和动态 GIF 图**
![image](https://user-images.githubusercontent.com/25842042/45076477-0c1a0580-b11d-11e8-9f41-479fc032eca7.png)

![复现步骤的屏幕截图和动态 GIF 图](图片的 url)

**Comment by liufeics** [comment]
给scroll-view设置高度宽度

**Comment by aOrz** [comment]
非 mpvue 问题，内容已经渲染，调整下 css
