### ISSUE TITLE
mpvue 引入其他项目的组件编译失败

### ISSUE THREAD

**Issue by ql9075** [Meituan-Dianping/mpvue#994]
# [问题简单描述]
mpvue 引入另一个项目的vue组件，编译失败。路径应该都是正确的，js都可以引用就vue引用不了。
**问题复现步骤:**

![_a444d8fa-b142-46ef-b3f8-34b48a294819](https://user-images.githubusercontent.com/1701645/45195050-7a2f0b80-b288-11e8-9324-53dabbc53afe.png)
![_f4d235ac-b5ff-4967-a45e-20ceef5fa21f](https://user-images.githubusercontent.com/1701645/45195051-7ac7a200-b288-11e8-957b-29955a971290.png)
![_192069f5-23b1-4767-9ca5-7f24498dc11a](https://user-images.githubusercontent.com/1701645/45195052-7ac7a200-b288-11e8-8ee5-bfd693673632.png)

**Comment by yuxianwen** [comment]
引入另外一个组件里面的引用有问题吧

**Comment by ql9075** [comment]
@yuxianwen 不是，组件里面什么都不写或者用当前目录可以用的放过去依然有问题

**Comment by yuxianwen** [comment]
你可以不用alias试试，我这边也是写了很多组件引用都没问题呢用的@

**Comment by aOrz** [comment]
另一个项目里面装了 mpvue 了吗？
